### ISSUE TITLE
Use the official Asciidoctor icon (when it's available)

### ISSUE THREAD

**Issue by aalmiray** [asciidoctor/asciidoctor-intellij-plugin#1]
The icon should probably be based on 

  https://0.gravatar.com/avatar/d37200188177ee76a4acfdb4d92acbcf?d=https%3A%2F%2Fidenticons.github.com%2F0081753798cce67879990a6017c45170.png&s=400

or

  https://github.com/asciidoctor/asciidoctor-chrome-extension/blob/master/img/asciidoc_icon_128.png

**Comment by mojavelinux** [comment]
The logo is indeed ready. And the fill variant is preferred. The outline variant should only be used if for some reason the fill variant just doesn't fit (hence giving you an alternative).

Getting the logo to work at 16x16 is tough. I'm going to try to fiddle with it and see if I can get something that maintains the shape at that size.

**Comment by ahus1** [comment]
Closed via #219
