### ISSUE TITLE
Can't open AsciiDoc file due to StackOverflowError

### ISSUE THREAD

**Issue by Grolribasi** [asciidoctor/asciidoctor-intellij-plugin#1005]
## Observed vs. expected behavior

So I wanted to open a file that's a part of Antora project. But every time I open it, only the preview loads and StackOverflowError occurs. Editor goes into infinite load loop while preview looks fine.

## Environment

Plugin Version:
0.37.7

IntelliJ Details: 
IntelliJ IDEA 2021.3.2 (Community Edition)
Build #IC-213.6777.52, built on January 28, 2022
Runtime version: 11.0.13+7-b1751.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4086M
Cores: 8
Non-Bundled Plugins:
    org.asciidoctor.intellij.asciidoc (0.37.7)

Kotlin: 213-1.6.10-release-961-IJ6777.52

I'm attaching the stacktrace. I've also submitted several reports and updated the [test repo](https://github.com/Grolribasi/testrepo).

[stacktrace-2.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/8245136/stacktrace-2.txt)

**Comment by ahus1** [comment]
Thanks, it seems that I introduced a bug in the pre-release 0.37.7. I'm sorry that this breaks the editor.

 Please roll back to 0.37.6 while I prepare an update. Please see [this page](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) for a description on how to download and install an older release.

**Comment by Grolribasi** [comment]
So far I've noticed it breaks the editor only on this one file.

Thanks for quick reply and for the guidelines how to install the previous version.

**Comment by ahus1** [comment]
Thank you for providing the example. I'd seen the stack trace, but failed to reproduce it locally before. The code changes were done as part of #1003.

Pre-release 0.37.9 is now available that this fix it. Please give it a try when you have the time.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by Grolribasi** [comment]
Just tested the new prerelease on the file. It opened with no errors. Thank you for the fix!

**Comment by ahus1** [comment]
Thanks for testing this, I'm closing this issue.
