### ISSUE TITLE
Move the preview out of the editor tab.

### ISSUE THREAD

**Issue by neher** [asciidoctor/asciidoctor-intellij-plugin#101]
It's not very handy when the preview is a different tab inside the active editor component.
It is now impossible to have the preview side by side the asciidoc text.

Possible solution :
The intellij plantuml plugin uses a tool window for the preview.
This is a lot more convenient/flexible.  Now we can arange the windows so we have the text and the preview side. Heck, we can even move it to preview to another screen.

**Comment by mojavelinux** [comment]
I agree. From what I've observed, people like to see the preview while they are typing.

**Comment by bodiam** [comment]
Sorry, maybe I don't understand, but the normal way is to split the editor, and open the same file twice. This way you can see the document you're editing and the live preview. So, maybe I'm missing something, but this is not impossible.

**Comment by mojavelinux** [comment]
Ah, I didn't realize you could split to get another window. @neher does that work for you?

**Comment by neher** [comment]
Yes, thanks for the workaround!
I had no idea you could do it like that.
I can now even move the 2nd file to another window.

**Comment by mojavelinux** [comment]
Perhaps this is something worth mention in the README? A screencast gif would really get the point across.

**Comment by bodiam** [comment]
That's in the readme since 0.4: https://cloud.githubusercontent.com/assets/46468/5202715/c2bfdcec-7580-11e4-91f6-82f9be257b5d.gif

**Comment by petko** [comment]
Splitting works, but is not very convenient if you work with a large number of AsciiDoc files. So, having dual pane support would still be useful IMO.

**Comment by ahus1** [comment]
fixed by PR #118
