### ISSUE TITLE
Crash when opening Asciidoc document using version 0.37.11 of the plugin.

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-intellij-plugin#1013]
## Observed vs. expected behavior

Plugin crashes when opening an Asciidoc document.

See attached stack traces.

## Environment

Plugin Version: 0.37.11

IntelliJ IDEA 2021.3.3 (Community Edition)
Build #IC-213.7172.25, built on March 15, 2022
Runtime version: 11.0.14.1+1-b1751.46 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2036M
Cores: 4
Non-Bundled Plugins:
    de.docs_as_co.intellij.plugin.diagramsnet (0.1.12)
    org.jetbrains.kotlin (213-1.6.20-RC-release-196-IJ6777.52)
    org.asciidoctor.intellij.asciidoc (0.37.11)
    org.asciidoctor.intellij.asciidoclet (0.1.2)
    PythonCore (213.7172.26)
    PlantUML integration (5.11.1)
    CMD Support (1.0.5)
    Batch Scripts Support (1.0.13)
    org.intellij.scala (2021.3.529)

Kotlin: 213-1.6.20-RC-release-196-IJ6777.52

**Comment by wfouche** [comment]
False positive. Closing as not reproducible.

**Comment by ahus1** [comment]
Thanks for reporting anyway, will keep a look for that. Found a bug in 0.37.11 that there is a hard dependency on the Grazie plugin; will issue 0.37.12 in a few minutes to fix that.

**Comment by wfouche** [comment]
OK, it makes sense now. I installed Grazie, which was not installed on my home laptop, and the issue went away.

**Comment by ahus1** [comment]
I recommend using the AsciiDoc plugin with Grazie. The text parsing for the structure and breadcrumb view will be more advanced when the Grazie plugin is installed, as the Grazie-AsciiDoc-bundle includes the logic to extract plain-text from AsciiDoc content.
