### ISSUE TITLE
Enable  Edit -> Find in the preview

### ISSUE THREAD

**Issue by neher** [asciidoctor/asciidoctor-intellij-plugin#102]
It would be handy to Edit -> Find available in the preview.

**Comment by ahus1** [comment]
Starting in October 2016 the preview now scrolls to the cursor position if you have enabled JavaFX preview. 

As you can now use find in the editor, this will also scroll the preview to the position of the match. Similar, if you use the global file search and choose a match, this will scroll the preview to the editor position. 

@neher - I wonder if this sufficient for day-to-day work and if this ticket could be closed.

**Comment by neher** [comment]
ticket can be closed
