### ISSUE TITLE
Installing plantuml extensions using local file is broken

### ISSUE THREAD

**Issue by hpenne** [asciidoctor/asciidoctor-intellij-plugin#1026]
## Observed vs. expected behavior

I want to install the dependencies for diagrams, but I am unable to download due to technical reasons and need to select "Pick local file after download.  This works fine for asciidoctorj-diagram-2.2.1.jar, but fails for asiccdoctorj-diagram-plantuml-1.2021.8.jar because the settings page requires that I select asciidoctorj-diagram-2.2.1.jar again but actually wants to load asiccdoctorj-diagram-plantuml-1.2021.8.jar (which cannot be selected).

## Steps to reproduce

Open Settings / Languages and Frameworks / AsciiDoc.
Disconnect from the internet.
Click on Download AsciiDoc dependencies for diagrams and PDF creation
When this fails, click on Pick Local File After Download.
Select the asciidoctorj-diagram-2.2.1.jar file

Everything works as expected so far.  The IDE now wants you to download asiccdoctorj-diagram-plantuml-1.2021.8.jar

Try download first, then click on Pick Local File After Download.  The IDE requires that you click on asciidoctorj-diagram-2.2.1.jar in the file browser even though asiccdoctorj-diagram-plantuml-1.2021.8.jar.  The correct file can thus never be selected, and installation cannot be completed.

## Environment

Plugin Version: 0.36.18

**Comment by ahus1** [comment]
Sorry to hear this causes you trouble. I'll prepare a new release that fixes this.

**Comment by ahus1** [comment]
There is now pre-release 0.37.13 available that fixes the problem you reported. Please give it a try and let me know if this works for you. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by hpenne** [comment]
I'm sorry for getting back to you so late, but I am happy to tell you that
the fix in the pre-release worked perfectly.  Thank you for your excellent
support.

Best regards,
Helge Penne

**Comment by ahus1** [comment]
Happy to hear this works now!
