### ISSUE TITLE
Please support screen adaptation and do not limit the maximum width.

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-intellij-plugin#1029]
I have a very wide, wide screen. However, when previewing the document, the image does not display well. 

**Please support screen adaptation and do not limit the maximum width.**

![image](https://user-images.githubusercontent.com/2121467/162382020-9a812942-c9d4-403f-82ec-2f2acc73b1d2.png)

**Comment by ahus1** [comment]
Hi @diguage - the preview uses the standard Asciidoctor stylesheet. It will display like a standard Asciidoctor website. 

Users can use the plugin's feature to modify or replace the built in stylesheet. [Please have a look at the docs on how to do this](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/stylesheets.html).

Please let me know if this solves your problem.

**Comment by mojavelinux** [comment]
The max-width of the content column can be controlled using the max-width attribute on the document. See https://github.com/asciidoctor/asciidoctor/issues/3513 and https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes-ref/#html-styling-attributes.

**Comment by ahus1** [comment]
The `max-width` attribute is currently not supported by the plugin as the plugin uses the convert method that returns just the body without the header. I'll use this issue to add support for this attribute to a future version of the plugin.

**Comment by ahus1** [comment]
There is now pre-release 0.37.13 available that includes support for `max-width`. I tested it locally and it worked for me, therefore I close this issue. 

The attribute can be set in the document or in the plugin's settings:

![image](https://user-images.githubusercontent.com/3957921/162579207-3a9f02ce-d9d5-4cb2-a542-90d8052d2fc6.png)

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
