### ISSUE TITLE
Support Asciidoclet

### ISSUE THREAD

**Issue by pniederw** [asciidoctor/asciidoctor-intellij-plugin#103]
Would be awesome if `View->Tool Windows->Documentation` rendered Asciidoclet powered Javadoc correctly.

**Comment by bodiam** [comment]
Hi Peter, thanks for the suggestion. Sound interesting. However, I'm not going to build it, since it will take too much of my time and provide little benefit. However, if you, or anyone else, wants to give it a shot, I'll for sure merge it in.

**Comment by ahus1** [comment]
Raised issue with IntelliJ to support language injection for JavaDoc-comments. AFAIK this is a pre-requisite to implement this.

**Comment by ahus1** [comment]
I found a hook that seems to work to pre-render Asciidoclet.
The next version of the plugin will have first support for Asciidoclet in the editor. 

See screenshot below. 

I'll update the issue again once a pre-release is available.

This is an experimental feature. Please have a [look at the docs](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/doc/users-guide/modules/ROOT/pages/features/advanced/asciidoclet.adoc) before using it to know about known limitations.

![image](https://user-images.githubusercontent.com/3957921/86486590-f3e89100-bd5b-11ea-8893-21d74ec0a893.png)

**Comment by ahus1** [comment]
This has been released as part of version 0.31.9 of the plugin.

This version works with the latest IntelliJ 2020.2 EAP release (202.6109.22). 

I love to get feedback. Please note that this latest EAP release doesn't include JavaFX in the pre-bundled JRE, and the plugin will default to JCEF preview. 
If you want to continue using the JavaFX preview, install the plugin ["JavaFX for Plugins"](https://plugins.jetbrains.com/plugin/14250-javafx-runtime-for-plugins).

Once the functionality matures and feedback is positive, it might be backported to 0.30.x and 2019.3.1+ releases

**Comment by ahus1** [comment]
There is now pre-release 0.30.83 supporting 2019.3.1 ... 2020.1. It received the functionality when showing Asciidoclet documentation using Ctrl+Q. 

As the release-branch 0.30.x supports also 2019.3.1, the AsciiDoc rendering in not available when showing rendered docs in he editor. This will only work in 2020.2 together with 0.31.9+

**Comment by ahus1** [comment]
Asciidoclet support will move to a separate plugin, please follow #521 for details.
