### ISSUE TITLE
Word wrap in IDEA plugin

### ISSUE THREAD

**Issue by jottinger** [asciidoctor/asciidoctor-intellij-plugin#1044]
## Why the new feature should be added

When writing content in AsciiDoctor using IDEA, it's trivial to go past a reasonable wrap point in the text; in this sentence, it'd probably show up around "trivial" for most screens. IDEA supports soft wrap, of course, so the text is legible, but soft wrap has other editing issues.

The markdown editor for IDEA has a set of "hard wrap" settings that can help nudge the text to a more maintainable form, and I think it would be nice for the AsciiDoctor plugin to have the same feature: support hard wrap for text breaks after a specific column if the user desires it.

Thus, if applied to the previous sentence, it would be TYPED as one paragraph (and would be "one line" without soft wrap) but with the hard wrapping turned on and column set to 72, it might end up looking like:

```
The markdown editor for IDEA has a set of "hard wrap" settings that can 
help nudge the text to a more maintainable form, and I think it would be 
nice for the AsciiDoctor plugin to have the same feature: support hard wrap
for text breaks after a specific column if the user desires it.
```

## How the new feature should work

The AsciiDoctor plugin has no wrap facility as of yet. The Markdown editor in IDEA does, however, and I would imagine that the AsciiDoctor wrap functionality would mirror what the Markdown mode provides.

**Comment by ahus1** [comment]
Thanks for suggesting this change and providing the reasons when this would be helpful. 

There is a different [line of thought of "one sentence per line"](https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line), that works well for moving around sentences, version control and commenting sentences and blocks.

For the full picture, there is also [semantic line breaks](https://sembr.org/) that goes even further. The [Grazie Professional](https://plugins.jetbrains.com/plugin/16136-grazie-professional) plugin supports automatic semantic breaks as you type.

I'd say the "one sentence per line" is currently the strategy that's best supported with this plugin, as it is also implemented in the AsciiDoc reformat (shortcut: Ctrl+Alt+L) that will reformat it. As you've mentioned in your previous comment, this works best with word wrap. 

I'd like you to have a look at "one sentence per line" if that would work for you. Please comment here with your conclusion. Eventually this plugin might support other strategies.

**Comment by jottinger** [comment]
I can certainly see the value in "one sentence per line," and I'm going to leave it in place for a bit just to see if my initial response is actually just a resistance to change, but my first impression...

Intellectually, it makes sense: select a line, move it. Very easy. And from a VCS perspective, it makes a lot of sense, too, because you're more likely to change a sentence than you are a paragraph (although changing paragraphs would be pretty common as well.)

But on USE, it feels a lot like turning on typographic symbols in Word: "Yes, yes, I know there's a space there. I typed it. Yes, a paragraph marker. I AM TYPING ALL OF THESE, please stop showing them to me" - the line wraps make reading the text really gross for me, personally.

But like I said, this is an initial, visceral response. I think that's *important* - if I hand someone a draft and their visceral response is "ew" and later they come back and say "you know, that was actually awesome when I finally got it" - I scrap it because surely I can find the awesome without the initial "ew."

Will try to let you know what my final decision is. I'm going to try to use this for a week or two to let it settle in.

**Comment by ahus1** [comment]
Closed due to inactivity. Please comment, and I'll reopen the issue.
