### ISSUE TITLE
Inline anchors on list items incorrectly flagged as unresolved

### ISSUE THREAD

**Issue by RayOffiah** [asciidoctor/asciidoctor-intellij-plugin#1049]
## Observed vs. expected behavior

Using an anchor in a list item like so:

`. [#setup]#The setup process#`

results in a unresolved anchor error when I reference it like this:

`xref:offending-page.adoc#setup[This doesn't resolve]`

When I build the page it does resolve though, so it's not a massive problem.

This is an Antora site, by the way.

## Steps to reproduce

Create the page and the anchor as described above.

## Environment

Plugin Version: 0.37.18

IntelliJ Details: ____

WebStorm 2022.1
Build #WS-221.5080.193, built on April 10, 2022
Licensed to me
Runtime version: 11.0.14.1+1-b2043.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins:
    org.toml.lang (221.5080.126)
    name.kropp.intellij.makefile (221.5080.126)
    com.intellj.plugin.SpringBootBannerPlugin (0.2.9)
    com.intellij.ideolog (203.0.28.1)
    org.asciidoctor.intellij.asciidoc (0.37.18)
    com.github.beansoft.iscratch (2022.1.5)
    com.intellij.jira (4.0.0)
    String Manipulation (9.4.0)
    Shifter (1.9.6)
    PlantUML integration (5.12.0)
    org.rust.lang (0.4.169.4584-221)
    com.intellij.database (221.5080.193)
    izhangzhihao.rainbow.brackets (6.22)
    com.github.shiraji.yaemoji (1.0.7)

**Comment by mojavelinux** [comment]
Although I should agree it should/could work either way, the correct way to write the anchor in this case is as follows:

```
. [[setup]]The setup process
```

As things stand now, AsciiDoc parsers do not discover IDs defined using the generic phrase element. And for list items and table cells, the inline anchor must be at the very start of the element. See https://docs.asciidoctor.org/asciidoc/latest/macros/xref/#internal-cross-references

**Comment by RayOffiah** [comment]
Okay, that's fair enough. Nothing to be fixed then.
