### ISSUE TITLE
Is there a reason why .idea files are checked in

### ISSUE THREAD

**Issue by ehmkah** [asciidoctor/asciidoctor-intellij-plugin#105]
Is there a reason why some .idea files .idea/encodings, .idea/gradle.xml, .idea/misc.xml are checked in? Could you imagen that I delete it? :-)

**Comment by mojavelinux** [comment]
I think we had discussed removing them, but no one followed up. Unless @bodiam has a preference, I say nuke 'em.

**Comment by bodiam** [comment]
Nope, no preference at all, do if they cause problems, remove them!

**Comment by bodiam** [comment]
I guess these files are gone now.
