### ISSUE TITLE
Code inspection skips some xrefs

### ISSUE THREAD

**Issue by Grolribasi** [asciidoctor/asciidoctor-intellij-plugin#1057]
## Observed vs. expected behavior

I have an Antora component with a lot of files. When I was authoring with IntelliJ AsciiDoc plugin I checked the whole component code for errors. Inspection returned me errors which I fixed. Then I commited the changes, ran Antora and was surprised when Antora found a lot of errors that the plugin didn't.

The xref is clearly broken, IntelliJ knows it since it doesn't open anthing when I click it. But for some reason code inspection doesn't return results.

## Steps to reproduce

You can see an example of such file [here](https://github.com/Docsvision/Programmer-Antora/blob/dev/modules/BackOffice-DigitalSignature/pages/SignatureInfo_CT.adoc). 

## Environment

Plugin Version: 0.37.19

IntelliJ IDEA 2022.1.1 (Community Edition)
Build #IC-221.5591.52, built on May 10, 2022
Runtime version: 11.0.14.1+1-b2043.45 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4086M
Cores: 8
Non-Bundled Plugins:
    org.asciidoctor.intellij.asciidoc (0.37.19)

Kotlin: 221-1.6.21-release-337-IJ5591.52

**Comment by Grolribasi** [comment]
Oh, I was fixing the errors Antora found and didn't realize that there will be no example left. The link to the example is now fixed. And I can't provide other one. Sorry, you can close the issue.

**Comment by ahus1** [comment]
Hi, I had a look at the last commit to the file you linked: https://github.com/Docsvision/Programmer-Antora/commit/a748496bceb5df245ee9c7e58779de1f88740955

After looking at the commit, this shows some situation where the IDE will not show an error, when Antora will report it on the CLI later. 

Most of them stem from the following situation: The IDE will validate the components and modules it knows about. If an unknown component or module appears, it assumes that it might be specified in a different repository. Something similar might happend if you specify a version for the component. [You find more about distributed component versions here](https://docs.antora.org/antora/latest/distributed-component-version/), they can distribute not only modules of a component, but even single files. Powerful, but also good to shoot your own foot.

Examples: 

The following fixed a wrong module name. The IDE will assume that this module might be defined in a different repository, and will therefore report it not as an error. 

```diff
-Тип: `xref:BackOffice-ObjectModel:Document_CL.adoc[Document]`
+Тип: `xref:BackOffice-ObjectModel-Document:Document_CL.adoc[Document]`
```

In the following example, it won't report an error, as `xref` will be an unknown component.

```diff
-Тип: `xref:BackOffice-ObjectModel:StaffEmployee_CL.adoc[StaffEmployee]`
+Тип: `xref:xref:BackOffice-ObjectModel-Staff:StaffEmployee_CL.adoc[StaffEmployee]`
```

The current behavior could be re-visited; I could think that an unknown module could trigger a warning or an error. I'm still not sure that an unknown component should trigger an error or a warning.

I could imagine two new warnings: "unknown component" and "unknown module". Depending on the context users can deactivate one or the other if they don't fit their environment.

WDYT?

**Comment by Grolribasi** [comment]
Though warnings "unknown component" and "unknown module" would be useful.

If someone doesn't want to have such notices, they may be configurable too.

**Comment by ahus1** [comment]
There is now a pre-release [0.37.23](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases/tag/0.37.23) that includes support for validating Antora component and module references. 

[From the docs](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/antora.html#antora-component-and-module-name-validation):

> The plugin validates the referenced component and module names. If they don’t exist, it will highlight this as an error in the editor window.
If a reference includes a version, the module name is only validated if the version and the component exist within the current project. If they don’t exist, it skips this reference for validation, as the plugin assumes this component to exist in a different branch that isn’t checked out in the current project.
For this to work, all components of the Antora site need to be opened in one IntelliJ project. If this isn’t suitable in a given setup, suppress the inspection for a given reference, or disable the inspection in the IDE’s setting for the given project.
To learn more about how to bundle multiple Git repositories as one IntelliJ project, see the chapter on [multi-module projects](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/multimodule.html) for details.

I'd be happy if you could give it a try.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by Grolribasi** [comment]
Thanks for the alert! I confirrm the inspection works now as desribed.
