### ISSUE TITLE
When moving a file, prefix page$ is lost and shows an error

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#1062]
Hi! Thanks for working on the refactoring for moving files, this is an awesome feature and works great for xrefs. However for include:: it is still (0.37.19) creating incorrect Antora syntax, losing the page$.

Example:

```
include::docs:page$AAA/file.adoc[]
```

when moved it produces

```
include::docs:BBB/file.adoc[] 
```

instead of 

```
include::docs:page$BBB/file.adoc[]
```

_Originally posted by @LukeCz in https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/981#issuecomment-1136953674_

**Comment by ahus1** [comment]
Hi  @LukeCz - thanks for reporting this. Could you please provide a minimal example for this, either as a ZIP file or as a GitHub repository? 

I'm wondering where this include is written, is it part of a partial, or a page? An example would clarify that. Thanks!

**Comment by LukeCz** [comment]
I will work on the example but I got it in all cases, even basic page, not partial.

**Comment by LukeCz** [comment]
[sample.zip](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/8778845/sample.zip)

Here is a very basic example. After moving it looks like this

![image](https://user-images.githubusercontent.com/6900878/170485525-046cadc0-086f-40c2-a4bf-cd848982962b.png)

**Comment by ahus1** [comment]
Thanks for reporting this and providing this example. This will be fixed in the next upcoming release: All includes will assume "pages" as the default family. With this example, I was able to test that this now works as expected.

I'll update this issue once a pre-release is available.

**Comment by ahus1** [comment]
The pre-release 0.37.22 is now available that includes the fix.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
