### ISSUE TITLE
Add support to convert AsciiDoc to DOCX format

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#1074]
## Why the new feature should be added

A user should be able to convert AsciiDoc to the DOCX format to be able to open it for example in OpenOffice or Microsoft Word.

## How the new feature should work

Next to the HTML and PDF buttons there should be a DOCX button that the user would click. 

The currently open document will be converted to DocBook, which is then converted to DOCX using Pandoc. Pandoc will be automatically downloaded.

**Comment by ahus1** [comment]
The next release will include this for Windows and Linux as it has been tested there. Test for macOS is pending, and it will be activated for macOS only after such a test.

**Comment by ahus1** [comment]
This is now available in pre-release [0.37.24](https://github.com/asciidoctor/asciidoctor-intellij-plugin/tree/0.37.24).

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by MuppetGate** [comment]
Hi, just installed on macOS Monterey, and I can't see the conversion button in the toolbar.

**Comment by RayOffiah** [comment]
Hello. 

I've installed the plugin (0.37.24), but I'm not seeing the DOCX button

I'm running on macOS Monterey and IntelliJ IDEA.

**Comment by ahus1** [comment]
Hi @RayOffiah - thanks for reaching out and your interest in testing it. 

As it is not supported on macOS yet, it is hidden behind a feature flag until it has been tested. 

To see the button you'll need to enable the internal mode, see [Enabling the internal mode](https://plugins.jetbrains.com/docs/intellij/enabling-internal.html) for the IDE in the JetBrain's IDE documentation.

Once you enabled this mode and restarted your IDE, you should see DOCX in your toolbar: 

![image](https://user-images.githubusercontent.com/3957921/175774472-2810a5d8-95b2-4af1-af43-7203abd4609b.png)

Once you click "DOCX", it should create first an XML file (DocBook) in the current file's folder. Then it creates DOCX file and opens it with the associated application (for example Microsoft Word of LibreOffice). 

If it doesn't work, we'll need to debug this, and I'll have lots of questions. A picture what you see would be a nice start if it doesn't work (and also if it works). 

Thanks!

**Comment by RayOffiah** [comment]
Yep, got the button now.

I'm clicking it.

Nothing seems to happen.

Right okay, the test.xml file has appeared in the folder. Just needs a click away to update the file window by the looks of it.

The Docbook xml file is generated and it looks fine; no DOCX file though.

**Comment by ahus1** [comment]
Did you get a small red notification icon at the lower right corner of your IDE? 

![image](https://user-images.githubusercontent.com/3957921/175776584-f39ed31c-b8f9-4242-826f-dff52fb3cf88.png)

If you did, please click on it and send a screenshot, and also click on the "Report" button. If the exception is correctly classified as a problem with the AsciiDoc plugin, the "Report" button will send this to my inbox. It might contain additional information about an exception that helps me to analyze the problem.

To analyze this further, please send me the log file of your IDE via email. Retrieve the log file via "Help | Show Log in Explorer" (might be a different menu item on macOS). Then send the file via email to the email address you see when clicking on my profile on GitHub. It might contain more information that I need to analyze the problem.

Let's hope that yields some additional information. If not, the next best thing I can think of is pairing up for a screen sharing session. Let's see.

Thanks!

**Comment by RayOffiah** [comment]
Ah, yes. I have this:

/Library/Caches/JetBrains/IntelliJIdea2022.2/download-cache/asciidoctor-intellij-plugin/pandoc-2.18/bin/pandoc error=13, Permission denied

**Comment by ahus1** [comment]
Could you please send a screen shot, or copy the text? I'd be interested in the stacktrace that would show me the location of the code where this happened.

Does that file listed above exist in the file system? It would be interesting to know what you find in and below the folder "pandoc-2.18".

Thanks!

**Comment by RayOffiah** [comment]
Yeah, the full line reads:

Cannot run program "/Users/raymond/Library/Caches/JetBrains/IntelliJIdea2022.2/download-cache/asciidoctor-intellij-plugin/pandoc-2.18/bin/pandoc" (in directory "/Users/raymond/projects/asciidoctor-external-callout-js"): error=13, Permission denied

I've had a quick look, and the file is definitely where it's supposed to be. Hold on, I'll see if I can sort out a stack trace

**Comment by ahus1** [comment]
Hm, maybe you could try to make the file executable, and give it another try - not sure how to do that on macOS, I'd try a `chmod +x pandoc` on Linux.

**Comment by RayOffiah** [comment]
I was just looking that up :-)

**Comment by ahus1** [comment]
Ok, just had a look, this is a simple error message, probably together with the text "Error creating DOCX from AsciiDoc file" and that wouldn't have a stack trace. 

Let's see if the executable permissions change something. I'll automate that in the next upcoming pre-release.

**Comment by RayOffiah** [comment]
<img width="655" alt="Screenshot 2022-06-25 at 15 27 20" src="https://user-images.githubusercontent.com/77050471/175777981-668be5c4-422b-4371-a4d0-73ef57795e77.png">

Perfect!

**Comment by RayOffiah** [comment]
Yes, aside from the permissions it works!

This is game changing!

**Comment by ahus1** [comment]
Nice! Let me prepare another pre-release that should include the "make executable"...

**Comment by RayOffiah** [comment]
Incidentally, the plugin works fine with the new IntelliJ look and feel.

**Comment by RayOffiah** [comment]
Okay, I have to go and see Top Gun :-(

When I get back, I'll scrub the plugin and the cache directory, and then reload it from scratch from the IntelliJ prerelease repo.

**Comment by ahus1** [comment]
Have fun! I'm also about to leave...

**Comment by RayOffiah** [comment]
This is great work!

**Comment by ahus1** [comment]
There is now pre-release [0.37.25](https://github.com/asciidoctor/asciidoctor-intellij-plugin/tree/0.37.25) available, this should set the executable permission for the pandoc file automatically on macOS. 

This new pre-release still needs the internal mode enabled as described above on macOS until this is fully tested..

To try this out:
* update the plugin to version 0.37.25 and restart the IDE
* delete the folder `pandoc-2.18`
* press the DOCX button again

I'd be happy to hear back from you once your time permits. Have fun watching Top Gun! Please, no spoilers here...

**Comment by RayOffiah** [comment]
Yep, working perfectly now. Cache reinstalled and works straight away.

**Comment by ahus1** [comment]
Thank you very much, your testing revealed a bug that has now been fixed. It also gives me the confidence to remove that flag for macOS that would then make it generally available for macOS.

I plan to for a regular release (non-pre-release) next week.

**Comment by ahus1** [comment]
Thank you very much, your testing revealed a bug that has now been fixed. It also gives me the confidence to remove that flag for macOS that would then make it generally available for macOS.

I plan to for a regular release (non-pre-release) next week.

By the way: did you test on an Intel Mac or a M1?

**Comment by RayOffiah** [comment]
Glad to help, and once again, thanks again for such a great plugin!

Oh, it was an Intel Mac.

**Comment by ahus1** [comment]
With pre-release 0.37.26 this is now generally available for macOS. Thanks again to @RayOffiah for testing this on macOS and helping me to find bugs. 

If you've enabled the internal mode, I recommend to disable it once you've installed the latest version of the plugin, as that setting might affect other parts of the IDE as well.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by KLynn2019** [comment]
I tested it out and...this may be what finally tips my team over to IntelliJ. 🙂 Great work!

The only downside really isn't with the plugin but with Pandoc's limited number of styles in reference.docx. Our department template is much more detailed...but it's nothing a VBA macro can't fix.

**Comment by ahus1** [comment]
@KLynn2019 - this makes me both happy and shiver that "we support DOCX export" can achieve something like that. Maybe #953  (convert AsciiDoc to Markdown) might shift it even more?

Please let me know if the approach to place the `reference.docx` just somewhere in the project is helpful, it was a random attempt to make it as frictionless as possible. 

As you mention it here: It seems to me that you've read the docs when trying out the feature (not everyone does that) and it that you've been "rewarded" with the discovery of a built-in feature. I'd be happy to hear ideas to make it even more discoverable without reading the docs.
