### ISSUE TITLE
Plugin does not work on my machine

### ISSUE THREAD

**Issue by AdilTestelin** [asciidoctor/asciidoctor-intellij-plugin#1077]
I've downloaded the latest version of AsciiDoc on Intellij IDEA 2022 1.2 and it keeps giving me this error message :

![174319429-78893422-ca12-4e9e-9cf4-d23ba8f8721a](https://user-images.githubusercontent.com/49147566/174396518-bc5148ad-e99a-4142-b6fe-7354f81e6ac6.png)

Plugin Version: 0.37.19

IntelliJ Details: 

IntelliJ IDEA 2022.1.2 (Ultimate Edition)
Build #IU-221.5787.30, built on May 31, 2022
Subscription is active until December 31, 2022.
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    org.asciidoctor.intellij.asciidoc (0.37.19)
    com.mallowigi (64.0.0)
    org.intellij.scala (2022.1.16)
    com.chrisrm.idea.MaterialThemeUI (7.5.2.2)

Kotlin: 221-1.6.21-release-337-IJ5787.30

Thanks in advance !

**Comment by ahus1** [comment]
Hi @AdilTestelin - thanks for reporting this. I'm sorry to hear that it doesn't work on your machine. 

Unfortunately I haven't seen that error message before, therefore I got some questions to narrow things down:

* The screenshot shows "/Users/201..." - does this folder exist on your machine?
* Did you install any [Asciidoctor extension from a folder `.asciidoctor`](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctor-extensions.html) in your project? There should be a notification in the editor when you open a project.
* Is the repository you're working publicly available, or can you share a minimal example project as a GitHub repository?

Thanks, Alexander

**Comment by AdilTestelin** [comment]
Hi Alexander, 

Thank you for answering me. 
* I verified and yes, this path exist on my machine (it is a work laptop from my enterprise)
* Yes, I installed the plugin from the IDE after fresh install, from the banner at the top telling me to install a plugin that have support for .adoc files.
* Unfortunatly, the repo I work on are private i'm sorry, but colleagues have pulled those same repos and don't have problem running AsciiDoctor on their laptop.

Thank you again for your help, 
Adil

**Comment by ahus1** [comment]
@AdilTestelin - thank you for the details. Could you please send me the log file of your IDE via E-Mail (you'll find my email in my GitHub's profile). This will contain the full exception with additional information that I'll need to analyze the problem.

You'll find the log file with the menu item "Help | Show Log in Explorer...".

Please don't upload it here as it might contain information you don't want to share publicly.

Thanks!

**Comment by AdilTestelin** [comment]
Hello, the new version of the plugin have solved my problem, thank you very much !
