### ISSUE TITLE
How can one redirect the PDF/HTML export output?

### ISSUE THREAD

**Issue by KerimG** [asciidoctor/asciidoctor-intellij-plugin#1088]
I tried using the `:outdir:` attribute both in the file `.adoc` file itself and in the `.asciidoctorconfig` file but the exports are always placed next to the `.adoc` file.

My project structure looks like this:

```
myproject
-> .asciidoctor
    -> custom-styles.css
-> .asciidoctorconfig
-> .idea
-> dist
-> src
     -> somedocument.doc
```

I tried

`:outdir: ../dist` and `:outdir: {asciidoctorconfigdir}/dist` and `:outdir: dist` but so far now luck. Am I missing something?

**Comment by ahus1** [comment]
Hi @KerimG - I had [a look at the docs](https://docs.asciidoctor.org/asciidoc/latest/attributes/document-attributes-ref/#intrinsic-attributes), and they state: 

> Cannot be referenced in the content. Only available to the API once the document is converted.

They can't be set in the document. 

As those is about where the output file is created when invoking it from the API, I wonder: what is it you're trying to achieve here?

As you'll see when you enter `{outdir}` to show the current setting of that attribute, you'll see that the plugin sets it at runtime to ensure all temporary files created for the preview end up in a temporary folder, and not in the current project the user has opened.

**Comment by KerimG** [comment]
Hi @ahus1 ,

oh, I saw the statement in the docs but for some reason thought that the plugin makes use of the API.

> what is it you're trying to achieve here?

When I press the PDF or HTML export button, I'd like the generated PDF/HTML file to be placed into a specific folder (in the case above into the `dist` folder). Is that possible? Is that even recommended?

**Comment by ahus1** [comment]
What you're trying to achieve is actually not possible today. Stil, I see the need for that, and recently this issue came up also here #1087. Let's close this issue, and use the existing issue with a broader scope.
