### ISSUE TITLE
Feature: Add dual-panel support

### ISSUE THREAD

**Issue by gengjiawen** [asciidoctor/asciidoctor-intellij-plugin#109]
Like jetbrains markdown plugin <https://plugins.jetbrains.com/plugin/7793>.

**Comment by petko** [comment]
+1 Most people already have big monitors, so this will make smart use of the screen real estate!

**Comment by ygra** [comment]
You can just split the window in IDEA and have the file open in both panes. In one you then view the source tab and in the other the preview tab. Works just fine here, albeit it took me a while to even find the preview tab.

**Comment by petko** [comment]
I've found that in some of the previous issues and it works fine for simple cases (if you want to edit a single file for example). But as soon as you start using includes and have to edit several files at the same time, it becomes tedious to constantly switch two panes at a time (one for the file and one for the preview)..
