### ISSUE TITLE
Markdown to AsciiDoc conversion when document only contains a heading and a bullet

### ISSUE THREAD

**Issue by Grolribasi** [asciidoctor/asciidoctor-intellij-plugin#1109]
## Observed vs. expected behavior

Markdown to AsciiDoc conversion fails when a document only contains a heading and a bullet.

## Steps to reproduce

1. Create a markdown document:

```
# Some title

-
```

2. Try to convert it to AsciiDoc
3. Expected to get an AsciiDoc with a title and a bullet. Instead, there is no result or an exception.

[stacktrace-conversion.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/9159261/stacktrace-conversion.txt)

## Environment

IntelliJ IDEA 2022.1.4 (Community Edition)
Build #IC-221.6008.13, built on July 19, 2022
Runtime version: 11.0.15+10-b2043.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4086M
Cores: 8
Non-Bundled Plugins:
    org.asciidoctor.intellij.asciidoc (0.37.32)

Kotlin: 221-1.7.10-release-333-IJ5591.52

**Comment by ahus1** [comment]
Thanks for reporting this. I've seen this exception being reported, still I haven't seen a way to reproduce it. And trying the example you provided, I still can't reproduce it. 

Could please try that snippet again? Have there maybe some blanks at the end of the line, or empty lines at the end?

Thanks!

**Comment by Grolribasi** [comment]
Yes, indeed, a blank space after `-` is required to get the error.

**Comment by ahus1** [comment]
Thank you for the example! Now that I was able to reproduce it with the example you provided, I was able to provide a fix for the upstream library. Will publish a new pre-release soon and then update this issue.

**Comment by ahus1** [comment]
The fix is part of pre-release 0.37.36.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
