### ISSUE TITLE
"java.lang.NullPointerException: Cannot invoke "Object.toString()" because "item" is null" error in preview

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/asciidoctor-intellij-plugin#1115]
## Observed vs. expected behavior

When I preview *some* files in my Antora project I get the NPE in the subject. 

I have a `:page-description:` attribute that gets the red highlight indicating this is the cause of the error. 

![2022-07-27_09-41-41](https://user-images.githubusercontent.com/952793/181130631-ae605e37-6abf-446f-a9cd-8ac4554adc18.png)

I have other pages with the same parameter and they do not have any NPE.

## Steps to reproduce

Frustratingly, I can't seem to find any way of working out what is causing only some of my files to cause the preview to break.

I've attached my log file to see if there are any clues hidden inside.

[idea-logs-20220727-09303316306038993727049878.zip](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/9193886/idea-logs-20220727-09303316306038993727049878.zip)

## Environment

MacOS Monterey v12.4
Plugin Version: 0.37.33

IntelliJ Details:

IDEA 2022.2 (Community)
Build #IC-222.3345.118, built on July 26, 2022
Runtime version: 17.0.3+7-b469.32 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by ahus1** [comment]
Sorry that this is causing you troubles and thank for letting me know. 

It seems that there might have been an empty `nav` entry in an `antora.yml` file that confused the plugin. 

There is now pre-release 0.37.34 that should fix this. Please 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by jaredmorgs** [comment]
Wow, that was incredibly fast support @ahus1 
I have installed the EAP plugin and have verified that the issue is resolved for me. 
No more NPEs happen in the preview.

**Comment by ahus1** [comment]
That only works when all information is available in the ticket created - and you did this very well.

Thank you for the retest, closing this issue.
