### ISSUE TITLE
Cancel in safe delete deletes anyway

### ISSUE THREAD

**Issue by Grolribasi** [asciidoctor/asciidoctor-intellij-plugin#1126]
## Observed vs. expected behavior

In a project, try to delete a file that is referenced in other files.
Confirm deletion.
Safe delete dialog will pop out. 
Between buttons: View usages, Delete Anyway, Cancel select Cancel.
The file will be deleted anyway.

## Environment

IntelliJ IDEA 2022.2 (Community Edition)
Build #IC-222.3345.118, built on July 26, 2022
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4086M
Cores: 8
Non-Bundled Plugins:
    org.asciidoctor.intellij.asciidoc (0.37.38)

Kotlin: 222-1.7.10-release-334-IJ3345.118

**Comment by ahus1** [comment]
It seems that you found a regression in IntelliJ 2022.2, thanks for reporting it here. I created an issue in YouTrack: https://youtrack.jetbrains.com/issue/IDEA-299352/. Please consider voting and watching that issue. 

As a workaround I suggest to click "View Usages" instead until this has been fixed. 

I close this issue as I don't see anything I can do for the plugin's perspective.
