### ISSUE TITLE
Code inspection skips missing include

### ISSUE THREAD

**Issue by Grolribasi** [asciidoctor/asciidoctor-intellij-plugin#1127]
## Observed vs. expected behavior

You can test the issue in [my test repository](https://github.com/Grolribasi/testrepo).

1. Open repository as a project.
2. Run code inspection on the whole project/module/directory.
3. No AsciiDoc errors found.
4. Open file named `test-page.adoc`
5. Broken include directive is reported on the page, but not in code inspection results.

## Environment

IntelliJ IDEA 2022.2 (Community Edition)
Build #IC-222.3345.118, built on July 26, 2022
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4086M
Cores: 8
Non-Bundled Plugins:
    org.asciidoctor.intellij.asciidoc (0.37.39)

Kotlin: 222-1.7.10-release-334-IJ3345.118

**Comment by ahus1** [comment]
Thanks for raising this. What you see it that some validations are done by the plugin, and therefore are available via the code inspection. Other validations are done when rendering AsciiDoc content via the Asciidoctor implementation. This is a lot slower and not run when using the code inspections. 

If you'd like to have the inspection of the tag attribute for the include as a code inspection, please create a feature request for this.

**Comment by Grolribasi** [comment]
This is a rare case. God to know it's not a bug.
