### ISSUE TITLE
Slow down IDE & UI

### ISSUE THREAD

**Issue by nikitasius** [asciidoctor/asciidoctor-intellij-plugin#1129]
## Observed vs. expected behavior
**observed:** I open a 600kb text file (`.txt`) from project folder which is not added to git, click on `Edit` menu and nothing happens.. menu have sick lag, `File`, `Edit`, `View` - all the menubar almost except `Help`.
**expected:** I open a 600kb text file (`.txt`) from project folder which is not added to git, click on `Edit` menu and wanna search some data.

## Steps to reproduce

install the plugin, open a 600kb+ text file in `.txt` format

## Environment

* `AMD 4600H, 16Gb ram, nvme`
* `Linux pentagon 5.10.0-16-amd64 #1 SMP Debian 5.10.127-2 (2022-07-23) x86_64 GNU/Linux`

Plugin Version: 0.37.36

IntelliJ Details:
```
IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022
Licensed to 😃
Subscription is active until August 17, 2022.
Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.10.0-16-amd64
GC: G1 Young Generation, G1 Old Generation
Memory: 3072M
Cores: 12
Registry:
    ide.balloon.shadow.size=0

Non-Bundled Plugins:
    org.asciidoctor.intellij.asciidoc (0.37.36)

Kotlin: 222-1.7.10-release-334-IJ3345.118
Current Desktop: XFCE
```

**Comment by nikitasius** [comment]
probably same as #1121

**Comment by ahus1** [comment]
Hi @nikitasius - could you please update to pre-release 0.37.38 and see if this works better for you?

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

If it doesn't, please collect some tracing information as described in the other issue: 

> See https://intellij-support.jetbrains.com/hc/en-us/articles/207241235 in chapter "The CPU usage is high or IDE is slow" for more information. Unfold the details below "2019.2 and above".

As you're running IntelliJ Ultimate, collecting the information should be possible without installing another plugin. 

Thanks!

**Comment by nikitasius** [comment]
updated plugin for a new version
![image](https://user-images.githubusercontent.com/3670331/186364321-56a358e9-1a41-4bcc-ab02-e2538c5baff8.png)
on 600kb files is better (=faster, just small lag), on 2Mb files it's fuckedup. So i disabled the plugin.

**Comment by mojavelinux** [comment]
@nikitasius Please do not use profanity when commenting on issues in this organization. It's unnecessary and it does not create a welcoming environment. You can express emotion, but that's not the way to do it.

**Comment by nikitasius** [comment]
@mojavelinux ok, hope it will help to fix the issues :+1:

**Comment by mojavelinux** [comment]
You don't need to be sarcastic. I politely asked you to use respectful language in this community and I don't deserve to ridiculed for that request.

**Comment by nikitasius** [comment]
@mojavelinux well, you can critic the "profanity" but you have nothing to do with my sarcasm. It's simply not your business.

**Comment by mojavelinux** [comment]
If you continue with this attitude, you will no longer be welcome in this community. We don't tolerate that kind of disrespect here. We believe in being friendly to each other.

**Comment by nikitasius** [comment]
Well you don't tolerate sarcasm within the technical issues. Thats huge and problem.

**Comment by mojavelinux** [comment]
I'm not going to tolerate this back talk in my own community. This user has been blocked from this organization. The person clearly does not understand the code of conduct or is not willing to honor it.

**Comment by mojavelinux** [comment]
This person proceeded to harass me on social media after being blocked. I'm closing and locking this issue now since nothing good is going to come from it.
