### ISSUE TITLE
no table formatting?

### ISSUE THREAD

**Issue by axd1967** [asciidoctor/asciidoctor-intellij-plugin#114]
is it me, or is all table formatting missing by default? (PyCharm CE 2016.1 with AsciiDoc 0.12)

```
.test
|===
|Header 1 |Header 2

|Column 1, row 1
|Column 2, row 1

|Column 1, row 2
|Column 2, row 2
|===
```
gives

![sci](https://cloud.githubusercontent.com/assets/3529789/15857769/60f400f6-2cbd-11e6-94ee-a54894cac841.png)

(I would expect something like https://gist.github.com/axd1967/b56acfc0c77602c5df586158de81f93d)

**Comment by bodiam** [comment]
Hi Alex,

What exactly are you missing? It's just a rendered table, you might want to
check the CSS for the table formatting.

Erik

**Comment by axd1967** [comment]
(sorry, updated the issue with PyCharm version info)

**Comment by bodiam** [comment]
I see what you mean. At the moment, there is no table formatting indeed, but if you want to add it, that would be very appreciated. It involves only changing the CSS file, but I'm not 100% sure what the capabilities of IntelliJ are concerning the rendering of CSS.

**Comment by axd1967** [comment]
no idea...

might be handy to be able to specify inline CSS... but I guess that's another (AsciiDoc) issue.

thx. Guess we can close this, then.

**Comment by axd1967** [comment]
where can we open this issue, then? Is it at IntelliJ?

**Comment by mojavelinux** [comment]
It's just a matter of customizing the CSS stylesheet (see https://github.com/asciidoctor/asciidoctor-intellij-plugin/tree/master/src/main/java/org/asciidoc/intellij/editor).

As far as I understand, IntelliJ uses the renderer in Swing, which only supports CSS2 (and you thought IE was bad before). So there are limits to how you can style it. But with enough dedication, you can achieve something that looks reasonable.

**Comment by axd1967** [comment]
OK, I'll try to build the plugin myself and dabble in the CSS code.

**Comment by mojavelinux** [comment]
:+1:
