### ISSUE TITLE
Add PHP source snippet

### ISSUE THREAD

**Issue by dozer111** [asciidoctor/asciidoctor-intellij-plugin#1142]
## Why the new feature should be added

There is a couple of programming language source snippets.

Need to add PHP to this list

## How the new feature should work

It will be new PHP source snippet

**Comment by ahus1** [comment]
Pre-release 0.37.44 is now available that includes your change. Thank you very much for this contribution!

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
