### ISSUE TITLE
Imagefiles doesn't resolve, if the filename has german umlauts.

### ISSUE THREAD

**Issue by HaLo1701** [asciidoctor/asciidoctor-intellij-plugin#1146]
## Observed vs. expected behavior

When I am using the image-directive and the filename of the image has german "umlauts" like ß, the file will be marked as "File doesn't resolve".

## Steps to reproduce

Create an image with a filename that uses german umlauts and use it in the document.

![grafik](https://user-images.githubusercontent.com/50229818/186875412-e5f21eba-1757-433c-9a6d-ecf260683ac0.png)

In the document preview, the process works fine.

Other images are working fine.

## Environment

Plugin Version: 0.37.43

IntelliJ Details:

IntelliJ IDEA 2022.2.1 (Ultimate Edition)
Build #IU-222.3739.54, built on August 16, 2022
Licensed to nextN GmbH / Hans Lohuis
Subscription is active until September 28, 2022.
Runtime version: 17.0.3+7-b469.37 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Non-Bundled Plugins:
    youngstead.relative-line-numbers (1.0)
    org.asciidoctor.intellij.asciidoc (0.37.43)

Kotlin: 222-1.7.10-release-334-IJ3739.54

Many thanks in advance.

**Comment by ahus1** [comment]
Pre-release 0.37.44 is now available that includes a fix for the error your reported. Thank you for the accurate description of the problem.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by HaLo1701** [comment]
Hello @ahus1,

many thanks for the quick response and bugfix.
It works fine.

**Comment by ahus1** [comment]
Thanks for testing this. I'll now promote the release 0.37.45 that includes also these changes to the main repository.
