### ISSUE TITLE
Links to files or directories containing whitespace character are not working correctly

### ISSUE THREAD

**Issue by karol-bujacek** [asciidoctor/asciidoctor-intellij-plugin#1147]
## Links are not working correctly both in editor and preview if there are white space characters in the path

If I try to create a link to another adoc file with white spaces, the link is not rendered as a link in the preview pane.

If white space is escaped with “%20” sequence, then link is clickable, but an error is shown in the editor (File doesn’t resolve).

If `++` characters are used, then click on link is not working and an error is shown in the editor (File doesn’t resolve).

(escape methods taken from https://github.com/asciidoctor/asciidoctor.org/issues/301 and https://github.com/asciidoctor/asciidoctor/issues/1093)

Autocomplete feature recognizes directory with white space, but the link is not working.

![screenshot_20220828-152324](https://user-images.githubusercontent.com/4030734/187076314-62baa9d0-537f-472d-ae88-2752ac79767b.png)

![screenshot_20220828-152448](https://user-images.githubusercontent.com/4030734/187076319-f66f2663-0704-4677-a506-86bd95b7f98e.png)

![screenshot_20220828-152504](https://user-images.githubusercontent.com/4030734/187076325-2e3c4edd-4430-45a7-b50b-d636dd621ab1.png)

## Steps to reproduce

Create simple file with this content:

```
link:new directory/another file.adoc[not rendered as a link]

link:new%20directory/another%20file.adoc[working, but with error in editor]

link:++new directory/another file.adoc++[rendered as link, click does not work, error in editor]

link:old_directory/old_file.adoc[working]

link:test file.adoc[not rendered as link]

link:file.adoc[working]
```

## Environment

Plugin Version: 0.37.43
IntelliJ Details: Build #IU-222.3345.118, built on July 26, 2022

**Comment by ahus1** [comment]
Thank you for the extensive description and the test cases. It seems that I broke the support for blanks in release 0.37.28.

I'll prepare a fix to make this work in the plugin as blanks also works for Asciidoctor. Still, I'd like to discourage blanks in file names where possible.

**Comment by ahus1** [comment]
There is now pre-release 0.37.45 that include changes related to your bug report. I'm sorry this caused you troubles.

Please note: 
* The items you marked with "not rendered as a link" are still not rendered as a link - this is how Asciidoctor (the renderer for the preview) works. The editor and the plugin will try to imitate its parsing as closely as possible. The [AsciiDoc working group at the Eclipse foundation](https://asciidoc-wg.eclipse.org/) set out to create specification that would eventually serve as a reference.
* All other items now work in the editor (will not show any errors and will link to the files). Also, clicking on the rendered preview will take you to the respective file.

Please give it a try when you have the time. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by karol-bujacek** [comment]
Dear Alexander,

I tried version 0.37.45 and it is working as I expected. If code complete feature is used it is necessary to insert %20 or ++ characters manually, but it is not a big deal.

Karol

**Comment by ahus1** [comment]
Thanks for trying it out and I'm happy to hear that it works for you. I'll therefore close this issue. If find other issues, please don't hesitate to raise issues here on GitHub.
