### ISSUE TITLE
AsciiDoc preview doesn't render in CLion

### ISSUE THREAD

**Issue by bodand** [asciidoctor/asciidoctor-intellij-plugin#1160]
## Observed vs. expected behavior

An error occurs when opening any AsciiDoc file. 
Instead of rendering the preview, the preview panel just shows the following error.

The expected behavior is that it renders the preview. 

![image](https://user-images.githubusercontent.com/17098729/190022560-f6c1e32b-7916-4615-93ff-81f2bf6e5223.png)

Text for convenience:
```
unable to render AsciiDoc document

org.jruby.exceptions.LoadError: (LoadError) no such file to load -- asciidoctor

(the full exception stack trace is available in the IDE's log file. Visit menu item 'Help | Show Log in Explorer' to see the log)
```

When hovering over the header with the squiggly lines the following shows:
![image](https://user-images.githubusercontent.com/17098729/190023150-822badf5-184f-455b-adc3-c7e974c9c828.png)

As instructed, I looked at the log file, but only found the following that refers to AsciiDoc, repeated a few times at different intervals--when I tried to open adoc files:
```
2022-09-14 00:32:18,593 [  38426]   WARN - #o.a.i.AsciiDocWrapper - unable to render AsciiDoc document
org.jruby.exceptions.LoadError: (LoadError) no such file to load -- asciidoctor
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1017)
	at RUBY.<main>(<script>:12)
```

I checked I have a working `asciidoctor` installed, available on PATH.
![image](https://user-images.githubusercontent.com/17098729/190023326-44b0f301-bd7b-418b-889b-422dc1110ef8.png)

Warnings, as shown by the `# Test` heading's background, work, and so do the floating open-in-browser buttons.

For additional context, I also have an IntelliJ Community installed, on which everything works, and so did CLion until recently.

## Steps to reproduce

The error occurs on opening any type of AsciiDoc file, even the empty file will cause it.

![image](https://user-images.githubusercontent.com/17098729/190021358-bd97e41a-2c24-48b7-b322-cb30627313a6.png)

Sadly I don't know any concrete ways to reproduce it. 

## Environment

Plugin Version: 0.37.45

IntelliJ Details:
CLion 2022.2.1
Build #CL-222.3739.54, built on August 16, 2022
Licensed to András Bodor
Subscription is active until June 10, 2023.
Runtime version: 17.0.3+7-b469.37 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 12000M
Cores: 12
Registry:
    run.processes.with.pty=true
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    some.awesome (1.14)
    org.rust.lang (0.4.178.4873-222)
    org.jetbrains.plugins.rest (222.3739.24)
    org.jetbrains.plugins.localization (222.3739.24)
    org.jetbrains.plugins.hocon (2022.1.0)
    org.jetbrains.intellij.scripting-ruby (1.0)
    org.editorconfig.editorconfigjetbrains (222.3739.53)
    net.seesharpsoft.intellij.plugins.csv (2.19.0)
    hunspell (222.3739.24)
    com.yanncebron.intellipikchr (0.3.1)
    com.wakatime.intellij.plugin (14.1.1)
    com.vincentp.gruvbox-theme (0.5.5)
    com.vermouthx.idea (1.13.3)
    com.vecheslav.darculaDarkerTheme (1.2.0)
    com.sercapnp (1.4)
    com.qbutton.Flashlight (1.0)
    com.perl5 (222.2964.55-EAP-SNAPSHOT)
    com.paperetto.dash (3.3)
    com.materkey.codepoints (1.0.2)
    com.jetbrains.plugins.ini4idea (222.3739.64)
    com.intellij.ideolog (203.0.30.0)
    com.intellij.properties (222.3739.16)
    com.herokuapp.vuesion (1.9.2)
    com.github.b3er.idea.plugins.arc.browser (0.32)
    de.nordgedanken.auto_hotkey (0.10.2)
    com.fwdekker.randomness (2.7.5)
    color.scheme.Tokyo Night (0.3)
    com.perl5.lang.mojo (222.2964.55-EAP-SNAPSHOT)
    com.intellij.plugin.adernov.powershell (2.0.10)
    com.github.jk1.ytplugin (2022.1.212)
    Statistic (4.2.5)
    Org4Idea (0.4.1)
    IdeaVIM (1.11.1)
    GrepConsole (12.15.211.6693.1)
    mobi.hsz.idea.gitignore (4.4.2)
    nl.rubensten.texifyidea (0.7.22)
    PlantUML integration (5.17.1)
    org.jetbrains.plugins.vue (222.3739.61)
    org.asciidoctor.intellij.asciidoc (0.37.45)
    com.eny.i18n (2.6.1)
    org.jetbrains.fortran (2022.2)
    io.xmake (1.1.7)
    izhangzhihao.rainbow.brackets (6.25)
    Batch Scripts Support (1.0.13)

(If any of these may break things, I can probably remove a lot of them, and see if anything changes, seeing as I don't use a significant subset of them.)

**Comment by ahus1** [comment]
Thanks for reporting this and sorry that this doesn't work for you yet.

I haven't tried this myself in the IDE yet, and looking at the error it seems that the ruby runtime didn't initialize.

Looking at the list of other plugins, it might be the scripting-ruby plugin.

Could you please try out after disabling that plugin?

**Comment by bodand** [comment]
Thank you for the quick response, and yes, that fixes it.
I don't know what that plugin was for, but I'm removing it now.

**Comment by ahus1** [comment]
Thanks for confirming that this works. The next version of the plugin detects if this incompatible plugin is installed and shows actionable advice to the user.
