### ISSUE TITLE
Ecological view on your versioning

### ISSUE THREAD

**Issue by Waize** [asciidoctor/asciidoctor-intellij-plugin#1163]
Dear Maintainers, 

due to the global ecological crisis it should be common sense that everybody has to do everything he can to save some energy.
You could have some impact with a small change in your versioning.

Currently you are releasing new versions at least once a week with average two issues. Every version produces an artifact with ~38MB in size. That are ~2GB at artifacts that needs to be uploaded and replicated somewhere. 
Sounds not much but this is just the upload part.

Looking today at IntelliJs Plugin download number (see image below)
![grafik](https://user-images.githubusercontent.com/16035154/190948177-d6dc3c03-1a46-4790-b13b-1d020ee09384.png)
I could not find some docs if this number is cumulating or the number of individual downloads excluding Plugin-Updates.

If we calculating ~2 million downloads times ~38MB Plugin size this plugin alone produces ~76 TB in download traffic. 
If the download number presents the indvidual number of persons which are updating their plugins regulary (1x every 2 weeks) whe have to multiply the result again with 26 (weekly updates / 2 makes 26 releases a year) this plugin alone produces ~1976 TB in download traffic.
Sounds terrifying to me. 

I would kindly ask you to review your current versioning and publishing strategy. 
Maybe you could make a "beta-plugin" for those who need every single update or needs to have a bugfix as fast as possible. 
But I guess for the most of the plugin user a single release per month would be enough.
*You* will save 1000TB in download traffic.
It's a small change, but has a huge impact!

**Comment by ahus1** [comment]
Thanks for reaching out here with this question.

The release strategy this plugin aims for is a monthly release for features and an eventual weekly release for bug fixes.

The recent release number has been higher, and it will eventually return to the release cadence given above.

When looking at the releases at GitHub, many of the releases are marked as pre-releases. Those are being published to an EAP (early access program) channel for those users who are interested in the latest changes, or those who test the changes included. Almost all versions that are not pre-releases have been pre-releases before being promoted to regular releases.

When users download the plugin as an upgrade from the marketplace, the IntelliJ platform will download only the contents that changed within the zip file. As most content is unmodified dependency jar files, those will not be downloaded again.

In the past the download of the plugins dependencies has been switched to on demand for dependencies for diagrams and pdf generation to reduce the footprint of the plugin. 

As you are asking about the download number in the store: to my understanding this counts both initial downloads and downloads of updates. As a maintainer I see the number of downloads on a daily basis, and they are a lot smaller.

Given your comment, I might consider removing the ZIP content from pre-releaes on GitHub. This might make it more difficult to track historical releases, still it might reduce the storage footprint of the plugin.

Please let me know if that answers your question. Feel free to post more questions to this thread.

**Comment by Waize** [comment]
Thank you! 
I really appreciate your answer!

At the moment, all of my questions are answered and I'm glad, that you will try to reduce the footprint on GitHub. 

Keep up the great work! :)
