### ISSUE TITLE
Never ending inspection since 0.37.49

### ISSUE THREAD

**Issue by dvponomarev** [asciidoctor/asciidoctor-intellij-plugin#1183]
## Observed vs. expected behavior

After upgrade plugin from 0.37.45 to 0.37.49 or 0.37.50 the inspection never ends, that leads to high CPU usage.
On 0.37.45 it is OK.
In the down-left corner of IDEA there is a constantly spinning icon:
![Selection_159](https://user-images.githubusercontent.com/11571006/193675599-7cede28c-0d1f-406b-b7e1-10900149352c.png)
In the asciidoc file there is a constant inspection message:
![image](https://user-images.githubusercontent.com/11571006/193677257-12a7ac07-1f99-4df7-bc9f-762fa0dd49ec.png)

## Steps to reproduce

It appears after some time I open my projects with asciidoc files. IDEA restart helps but not for long..
IDEA threads dump I will send you by email (issue id will be in the email title). In the threads dump there are very long stacktraces with `AsciiDocInspectionBase` class.

## Environment

Plugin Version: 0.37.50

IntelliJ Details: IntelliJ IDEA 2022.2.2 (Community Edition)
Build #IC-222.4167.29, built on September 13, 2022
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-192-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins:
    com.j92.current-date-generator (1.1)
    org.asciidoctor.intellij.asciidoc (0.37.50)

Kotlin: 222-1.7.20-release-201-IJ4167.29
Current Desktop: ubuntu:GNOME

**Comment by ahus1** [comment]
I'm sorry to hear that this is giving you troubles. I received the thread dump and will have a look.

**Comment by ahus1** [comment]
This is actually a performance regression in #1150; instead of looking only at the current file, it will recurse also files and directories. I'll release 0.37.52 shortly.

**Comment by ahus1** [comment]
Release 0.37.52 is now available that fixes this performance regression. Thank you for providing all necessary details in the original issue. 

I was able to reproduce it locally therefore I'm quite sure that this has been fixed. Still I'd be happy if you could give it a try as well.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and will also be available from the JetBrains marketplace shortly.

**Comment by dvponomarev** [comment]
Tried 0.37.52 - it works OK!
Thank you very much!

**Comment by ahus1** [comment]
What a relief! Thank you for the fast feedback.
