### ISSUE TITLE
Error use mermaid diagram

### ISSUE THREAD

**Issue by sercheo87** [asciidoctor/asciidoctor-intellij-plugin#1190]
## Observed vs. expected behavior

Error on rederize of mermaid plugin

## Steps to reproduce
Create file ***demo.adoc***

Put this code

```
[mermaid]
----
sequenceDiagram
    Alice->>+John: Hello John, how are you?
    Alice->>+John: John, can you hear me?
    John-->>-Alice: Hi Alice, I can hear you!
    John-->>-Alice: I feel great!
----

```

![image](https://user-images.githubusercontent.com/1036090/194358506-f733dd88-9fd7-440e-b5af-f039efce469d.png)

## Environment

Plugin Version: 0.37.52

IntelliJ Details: 2022.2.3 (Ultimate Edition)

**Comment by ahus1** [comment]
Hi @sercheo87 - to use Mermaid diagrams, there are two choices: 

* Use Asciidoctor Diagram - Currently you'll need to have the Mermaid CLI executable installed, see https://docs.asciidoctor.org/diagram-extension/latest/#specifying-diagram-generator-paths and https://github.com/mermaid-js/mermaid-cli
* Use Kroki - See https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/preview/diagrams.html#kroki for details on Kroki. 

There's already an issue #1199 to support it "out of the box", without additional add-ons.

**Comment by sercheo87** [comment]
Hello @ahus1  , with the configuration of Kroki I don't have any more problems.
But using it with a local installation did not work for me on Windows 10.

Thanks.

**Comment by ahus1** [comment]
Happy to hear that it now works for you. Sorry it took me so long to respond.
