### ISSUE TITLE
asciidoctorj-diagram version

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#120]
the plugin currently contains asciidoctorj-diagram in V 1.3.1
can this be upgraded to V 1.5.1?

This would allow to render plantUML without Graphviz:
http://plantuml.com/smetana02.html

**Comment by ahus1** [comment]
I'm happy to update the version of aaciidoctorj-diagram.

But smetana seems to be in the early stages: Reading the docs it seems that it doesn't support arrows and labels yet. Have you given it a try? What is your experience?

**Comment by rdmueller** [comment]
Yes, it does not support arrow heads, but lines between elements are drawn. What I've tested so far, it is quite stable and I see real value in the current version, because in some environments you are not able to install graphviz...

**Comment by ahus1** [comment]
Maven Central lists 1.5.0 as the most recent version. Is that fine as well?

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22org.asciidoctor%22%20AND%20a%3A%22asciidoctorj-diagram%22

**Comment by rdmueller** [comment]
hm. I guess the chances are good. Can we give it a try? I have no idea how to test it otherwise.

Sorry, I tried to checkout the code and update the plugin myself in order to test, but I didn't succeed :-(

**Comment by ahus1** [comment]
Alright, expect a preview early next week. How will I be able to test it? I assume I will need to add the `pragma` to the plantuml?

A snippet for me to test it would be great.

**Comment by rdmueller** [comment]
Great!
In order to test,  just use a normal plantUML diagram and add the pragma line as first line.
It should render normal but the arrow heads will disappear :-)

**Comment by ahus1** [comment]
Hello Ralf,

please have a look at the preview https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases/tag/0.13-preview1

This contains asciidoctorj-diagram 1.5.0. A sample of 

```
[plantuml, pic, png]
--
!pragma graphviz_dot jdot
node node1
node node2
node1 --> node2
--
```

renders without arrows like this:

![render](https://cloud.githubusercontent.com/assets/3957921/17279971/e08859c0-5783-11e6-967c-b10116b867f6.png)

I suppose this is a good sign. Please comment and/or close this ticket if this works for you as well.

Regards,
Alexander

**Comment by rdmueller** [comment]
Thanx! Works like a charm!
