### ISSUE TITLE
cannot click on URL

### ISSUE THREAD

**Issue by axd1967** [asciidoctor/asciidoctor-intellij-plugin#121]
when given a simple URL, the preview pane shows a "hand" pointer, but the link does not open in a browser.

Asciidoctor 0.13 (by the way, why is that version stated here as "not released yet"?)

PyCharm Community Edition 2016.2
Build #PC-162.1237.1, built on July 20, 2016
JRE: 1.8.0_76-release-b216 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

**Comment by Matthias-Ni** [comment]
I have the same problem. This is super annoying. It prevents us from using different texts for long links because you have to copy paste them in your browser.

**Comment by bodiam** [comment]
Do you have this with both render engines?

**Comment by Matthias-Ni** [comment]
Oh I was not even aware that there are multiple rendering engines.  

In Swing tables are not rendered correctly (they have no layout). Links are not clickable. 

JavaFx Webview renders tables correctly. 
Links can be clicked. But they do not open a Browser instead they load directly in the View. So it is not possible to navigate back anymore... 
Also the text looks blurry.

**Comment by ahus1** [comment]
@axd1967 - sorry about the version confusion. It's now fixed: 0.13 was tthe released when you reported the bug. Now 0.14 is released with JavaFX preview.

**Comment by ahus1** [comment]
In the (new) JavaFX preview you can click on links and they will open in the preview. Once you continue editing your source the preview will return to your document. 

With the (old) Swing preview nothing (but the change of the mouse pointer) will happen when you click/hover over links.

I'm tagging this as an enhancement.

**Comment by Matthias-Ni** [comment]
I deleted my IDEA config folder and installed the plugin again. Now I cannot switch to the JavaFxWebview. I can only select Swing. I have JDK7 JavaFX Plugin is activated and working...

**Comment by ahus1** [comment]
@Matthias-Ni - JavaFX preview requires that your IDE runs on JDK 8. Please past the IDE version details here (go to Help -> About, click on 'Copy to Clipboard' and paste the contents of your clipboard here)

**Comment by ahus1** [comment]
The next iteration of the JavaFX preview is on the way. It will support that links in the preview are opened in an external browser. Stay tuned.

**Comment by Matthias-Ni** [comment]
Thanks for the info. Now it's working. Also good to hear about the browser improvement.

**Comment by ahus1** [comment]
This feature is now available in the JavaFX preview as part of the  [0.15.0 preview release](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases/tag/0.15.0). 

Please give it a try. I'm also looking forward to some comments on the automatically scrolling preview #129.

**Comment by axd1967** [comment]
not really useful... smells more like a quick & dirty fix, maybe you should spend a bit more time on polishing before publishing: when I click on an URL, the preview also loads the clicked website. I don't want to open an external website in my preview window, I want to **open the clicked URL in an external browser**! And how would you go BACK to the adoc preview??? (I don't actually want to know, because that's not what I am looking for...)

**Comment by mojavelinux** [comment]
@axd1967 I appreciate your feedback and the time you're dedicating to testing the changes. Let's keep a positive tone to show our appreciation for the time @ahus1 has dedicated to advance this plugin. I have no doubt he's trying his best to polish each release before publishing. Naturally, users like yourself are going to have feedback and ideas about how to improve it. That's to be expected. It's the cycle of OSS life. So we just keep iterating by sharing those ideas.

**Comment by DiabolusExMachia** [comment]
@axd1967 you can go back by typing something in the editor. 

Nice to hear you are still working on this feature! I also think the default action should be that an external browser is opened with the clicked link. The preview however should not load the url. 
It may seem like a nice technically feature but in my opinion it is not what the user wants.

**Comment by ahus1** [comment]
I found a situation where a slow or not loading image referenced in the JavaFX preview stalled the initialization of the click handler (see 33820a1). Version 0.15.3 is now available as GA over the regular update channels. Please open a new issue with an example and setup details if this behavior still occurs.
