### ISSUE TITLE
Basic inline styles not rendered in preview

### ISSUE THREAD

**Issue by dan-cohn-sabre** [asciidoctor/asciidoctor-intellij-plugin#1210]
## Observed vs. expected behavior

When using inline styles to change the text color, I expect to see these in the preview, but the text appears in its default color. Here is a simple example:

```
[red]#This text should be red.#
```

I suspect the plugin isn't loading the default stylesheet.

By the way, this works correctly with the AsciiDoc extension for VS Code. I mention this because I don't think it requires a custom stylesheet.

## Steps to reproduce

Create an AsciiDoc file that includes an inline style with one of the standard CSS classes such as a color or "big" or "small".

## Environment

Plugin Version: 0.37.54

IntelliJ Details: IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Licensed to Sabre GLBL Inc.

Runtime version: 17.0.4.1+7-b469.62 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Non-Bundled Plugins:
    com.andrewbrookins.wrap_to_column (1.8.0)
    PlantUML integration (5.18)
    org.asciidoctor.intellij.asciidoc (0.37.54)

Kotlin: 222-1.7.10-release-334-IJ4345.14

**Comment by mojavelinux** [comment]
While it's up this project to decide whether to support these color roles, please note that they are deprecated and are scheduled to be removed. Colors names are not portable across themes nor are they semantic. Custom semantic roles are preferred.

See https://docs.asciidoctor.org/asciidoc/latest/text/text-span-built-in-roles/#built-in-roles-for-text

**Comment by dan-cohn-sabre** [comment]
Thanks, @mojavelinux. I wasn't aware that the colors were deprecated. I imagine they are still in wide use nonetheless.

**Comment by mojavelinux** [comment]
I've been warning against using the built-in color roles for almost as long as I've been working on Asciidoctor (read as: a decade). And I've beat the drum for separating content and presentation for just as long. You should not be putting color directly into a document. That's just not a good technical writing / publishing practice. Hints in the form of semantic roles, yes. Explicit color names, no.

**Comment by ahus1** [comment]
Hi @dan-cohn-sabre - thanks for reaching out. 

I'm missing a screen shot in this report, so I ran some local tests: 

* When adding the example text in a plain AsciiDoc file, the preview shows the red color:
   ![image](https://user-images.githubusercontent.com/3957921/198345198-137df771-8a69-4ae1-aedd-47a88e580db0.png)
* When adding the example text on a page in an Antora file, the preview shows the text in plain colors: 
   ![image](https://user-images.githubusercontent.com/3957921/198345383-e96d5d54-d8ce-46e3-9a8b-d5607efa7471.png)

The cause to this behavior lies in the different stylesheets used for each of the files: 
* When previewing standard AsciiDoc file, it uses the classic Asciidoctor stylesheet which includes the colors.
* When previewing an Antora file, it uses the standard Antora stylesheet which doesn't include the colors.

So I'm assuming that you're editing a page in an Antora setup. 

If that color doesn't show up in the preview, but in your final rendered site, that site is most likely using a custom stylesheet. To configure your setup to use the final site's stylesheet, see [the plugin's docs on how to achieve that](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/stylesheets.html).

If the color doesn't show up in the final rendered site, I support Dan's recommendation to have custom semantic styles to reference, and not a color.

Please let me know if my assumptions where going in the right direction, and if the link to the docs is helpful in your setup.

**Comment by dan-cohn-sabre** [comment]
@ahus1 Thanks for your detailed reply. I found out that the colors for our Antora site are defined in a footer "partial" and not in a stylesheet. So, I think the best option for us is to define semantic styles. I agree that it's better than using color names.

Let's consider the issue closed.

**Comment by ahus1** [comment]
Happy to hear that my hints helped to solve this problem. 

For the case you describe, I'd recommend the following to have a preview in your IDE that matches the final site:

* move the CSS from the template to a CSS file and include that in the header of the site (see https://github.com/ahus1/intellij-asciidoc-plugin.ahus1.de/blob/main/_antora/supplemental_ui/partials/head-styles.hbs for an example which includes a CSS file `custom.css`)
* publish a CSS file for the preview to you Antora site that combines all styles and possibly fonts (see https://github.com/ahus1/intellij-asciidoc-plugin.ahus1.de/blob/main/_antora/supplemental_ui/css/preview.css for an example)
* use an config file in your Antora documentation project that provides a hint for the IDE to use that stylesheet for the preview (see https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/main/doc/.asciidoctorconfig for an example)
