### ISSUE TITLE
Cannot Install Latest Asciidoc Plugin From ZIP Behind Company Firewall

### ISSUE THREAD

**Issue by duffymo** [asciidoctor/asciidoctor-intellij-plugin#1211]
## Observed vs. expected behavior

I posted [this question ](https://intellij-support.jetbrains.com/hc/en-us/community/posts/8266242896530-403-status-code-when-installing-asciidoc-plugin-from-disk)to Jetbrains IntelliJ support.

I recently upgraded to IntelliJ 2022.2.2 on my Mac OS Monterey version 12.6 Macbook Pro.

That meant reinstalling plugins for PlantUML and Asciidoc from disk.  

The PlantUML installation went fine.  

The Asciidoc 0.37.54 install failed with status code 403.  

Why does the installation have to call out to a server when I install from disk?

My machine is behind a company firewall.  Direct access to the Jetbrains plugin server is blocked.  

How can I get the Asciidoc plugin back?

## Steps to reproduce

1. Copied asciidoc plugin ZIP file version 0.37.54 to my local desktop.
2. Went into IntelliJ 2022.2.2 to install plugin from disk and selected the ZIP file from my local desktop.
3. Observed an error popup with status code 403 - HTTP forbidden.
4. I expected to see the latest asciidoc plugin installed.  Shouldn't have to connect to plugin marketplace server when installing from disk.

Installed PlantUML plugin from ZIP file immediately afterwards - no issues.

## Environment

My work Mac is behind a company firewall.  I cannot connect directly to the plugin marketplace server.  I have to get the plugin ZIP file from a company-approved share.

I copied ZIP file version 0.37.54 to my local machine to install from disk.

Asciidoc plugin is not installed.  Downloaded the latest ZIP file for installation from disk here:

https://plugins.jetbrains.com/plugin/7391-asciidoc

Plugin Version: 0.37.54

Build #IU-222.4167.29, built on September 13, 2022

Licensed to Michael Duffy
Subscription is active until November 6, 2022.

Runtime version: 17.0.4+7-b469.53 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by ahus1** [comment]
Hi @duffymo - the procedure you describe should work as you expect, and it is also [described in the docs](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/installation.html#download-install-from-disk).

I did the following locally to find out if it works:
* disconnected my PC from the internet
* installed the ZIP file via the UI as described in the docs
* then the plugin was available

To find out more about the circumstances that lead to the error message you saw, please do the following: 

(A) provide the logs of the IDE. Do to that, 

1. Retry the procedure to create an entry in the current log file
2. Go to the menu entry "Help | Show log in explorer..."
3. Search the log file for an error message and paste it here, OR send the file to my via email to the address you find in my GitHub profile

(B) retry the procedure after disconnecting your PC from the network; maybe it makes it behave differently from getting a 403 from the proxy

Best,
Alexander

**Comment by ahus1** [comment]
Hi @duffymo - good to hear that there is that workaround.

The AsciiDoc plugin doesn't issue any call during installation, so I suspect the IntelliJ plugin manager to do that. To double check, it would still be great if you could try with the PC connected and provide some logs.

To prevent other uses to go though the same process (any possibly helping your future self on the next install), it would be great if you could open a bug here https://youtrack.jetbrains.com/issues/IDEA and add the issue number created here for future reference. I'd assume the subsystem would be "Core. plugin management". 

I suspect they would like to see some logs to analyze the issue.

Thanks!
