### ISSUE TITLE
Using the plugin in repositories with symlinks

### ISSUE THREAD

**Issue by themr0c** [asciidoctor/asciidoctor-intellij-plugin#1216]
When opening a repository containing symlinks, Code Inspection is duplicating reports (and execution time grows).

It is tempting to mark symlink as Excluded directories, manually, or via a plug-in such as https://plugins.jetbrains.com/plugin/16110-symlink-excluder or https://plugins.jetbrains.com/plugin/16110-symlink-excluder. It seems the most common way to proceed to avoid duplicate reports (and duplicate modules detection).

But then, the jump function in the Asciidoctor plug-in stops working.

Would it be possible for the Asciidoctor plug-in to bypass the "excluded directory" flag?

**Comment by ahus1** [comment]
Thanks for pointing to this problem, and the previous attempts. 

For pre-release 0.37.55 there are now custom search scopes, that aim to fix this. They work for "Code | Inspect Code...", and they work for "Find in Files", "Find usages", etc.  I tested it with a local example, still I need to test it with a larger example. Please let me know how this works for you.

![image](https://user-images.githubusercontent.com/3957921/202149596-8e372a99-b859-411e-9357-f1142ebd2d01.png)

![image](https://user-images.githubusercontent.com/3957921/202149792-471a4b0e-c564-459a-b365-3845e29a46e3.png)

![image](https://user-images.githubusercontent.com/3957921/202150563-e56a42c3-7c5a-46ef-9afa-35e914fb2253.png)

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by themr0c** [comment]
* Added the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
* Installed version 0.37.55.
* Tested successfully on a large repository with 70+ symlinks: 

	* With Scope "AsciiDoc files without Symlinks", the inspection progress bar moved fast, the inspection finished in less than 1 minute, without duplicates, reporting 3984 Style alerts.
	* With Scope "All files without Symlinks", the inspection progress bar moved slightly slower, the inspection finished in less than 5 minute, without duplicates, reporting 4043 style alerts.
	* With Scope "AsciiDoc files", the inspection progress bar moved very slowly, I could see duplicate reports appearing after 5 minutes, and I stopped the inspection before it ended.

**Comment by ahus1** [comment]
Thanks for testing this; I'll therefore close this issue. 
In the next release, I will rename the search scope _All files without Symlinks_ to _Project files without Symlinks_, as this is more in line with the search scope "Project files" in IntelliJ.
