### ISSUE TITLE
Is it possible to change the tab size from the configuration window?

### ISSUE THREAD

**Issue by HaLo1701** [asciidoctor/asciidoctor-intellij-plugin#1218]
When using the configuration to change the tab key to spaces, is it possible to change the amount of spaces to use like it was in other languages?

Configuration in all languanges:

![grafik](https://user-images.githubusercontent.com/50229818/202149856-8dd3307b-b89b-4215-aee7-a53556d7842e.png)

Configuration in AsciiDoc:

![grafik](https://user-images.githubusercontent.com/50229818/202149949-76ba5e41-7ee7-4ed8-938a-1cf073e5ee7a.png)

Used settings by editor:

![grafik](https://user-images.githubusercontent.com/50229818/202150083-fd9b2f34-52bf-4652-8fa6-d4dd07d41295.png)

Many thanks in advance.

**Comment by ahus1** [comment]
What you're asking for is not available at the moment AFAIK. It seems that I missed it so far as I wasn't using tabs so much, and therefore didn't need this configuration, yet.

I'll keep this issue open to look into it and update the settings eventually.

**Comment by HaLo1701** [comment]
Hello @ahus1,
ok, many thanks for your fast response.
This is a "nice to have"-feature, so has got a low priority.

**Comment by ahus1** [comment]
I've been triaging this feature and it was a limited amount of work. It will be available in the next release. I'll add a note to this issue when it is available. Another good news: this also enables `.editorconfig` support for these settings for AsciiDoc files.

**Comment by HaLo1701** [comment]
Wow, now I'm really surprised. Also the support of .editorconfig. This is like early Christmas.
Thanks a lot for that.
Again: it is an excellent plugin which makes the work much easier.

**Comment by ahus1** [comment]
I'm also a big fan of `.editorconfig`. I first tried that as a workaround for the UI configuration, but it didn't work until I change those few lines of code. 

KUDOs to the people at JetBrains as the `.editorconfig` just worked once I had the settings in the UI working as well.

**Comment by ahus1** [comment]
Closing this as it is resolved. Will comment again once the pre-release is avaiable.

**Comment by ahus1** [comment]
This is now available in pre-release 0.37.56.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by HaLo1701** [comment]
Wow, many thanks.

I have done a quick test with the EAP-Repo.

It works fine.

Test done with and without .editorconfig in the project.

Many thanks for the fast response and excellent work.

**Comment by ahus1** [comment]
Release 0.37.56 has now been promoted to a regular release, so this change is now available to all users of the JetBrains marketplace.

**Comment by HaLo1701** [comment]
Great,
many thanks again by implementing this feature.
