### ISSUE TITLE
Slow preview and high CPU usage in IDEA Ultimate

### ISSUE THREAD

**Issue by dvponomarev** [asciidoctor/asciidoctor-intellij-plugin#1226]
## Observed vs. expected behavior

Slow opening .adoc file preview with high CPU usage in IDEA Ultimate. Veeeery slow scroll of the file preview with high CPU usage.
I observe this problem for a year or more, cannot tell when the problem arized...

## Steps to reproduce

In IDEA Ultimate I have several projects with single README.adoc file. This file is quite simple, one or two pages.
When I open README.adoc, it hangs for a 10-20 seconds, then preview opens finally. Scroll in the preview is veeeery slow and uses much more CPU than it should.
Temporary workaround is to restart whole IDEA, but after some time the problem returns.

Note that in IDEA Community it works like a charm for many years.

May be it is related to:

- #1217 
- https://youtrack.jetbrains.com/issue/IDEA-299007/Idea-2022.2-Markdown-Preview-not-working 
ide.browser.jcef.gpu.disable=true (Actions > Registry) does not help

I will send you by email: IDEA profiling data collected with "Help | Diagnostic Tools | Start CPU Usage Profiling".
2 files: the first one - opening .adoc file, the second one - scrolling in .adoc file.

### Ultimate (problem is here)

IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-196-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Registry:
    actionSystem.playback.typecommand.delay=20
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    org.intellij.RegexpTester (1.0.8)
    org.jetbrains.kotlin (222-1.7.21-release-272-IJ4167.29)
    com.jetbrains.jax.ws (222.4345.14)
    com.intellij.guice (222.4345.14)
    co.anbora.labs.kse (1.2.2)
    org.asciidoctor.intellij.asciidoc (0.37.54)
    ris58h.lacopom (1.1.1)

Kotlin: 222-1.7.21-release-272-IJ4167.29
Current Desktop: ubuntu:GNOME

Plugin Version: 0.37.54

### Community (no problems)

IntelliJ IDEA 2022.2.3 (Community Edition)
Build #IC-222.4345.14, built on October 5, 2022
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-196-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12

Non-Bundled Plugins:
    com.j92.current-date-generator (1.1)
    org.asciidoctor.intellij.asciidoc (0.37.54)

Kotlin: 222-1.7.20-release-201-IJ4167.29
Current Desktop: ubuntu:GNOME

**Comment by ahus1** [comment]
Thanks for sharing the profiling information. Look at those files regarding scolling, it looks to me that IntelliJ's Java process is not using so much CPU. Can you confirm this? I suspect there is another process that is rendering the preview (probably named "jcef" or similar), 

The initial 10-20 seconds before the preview shows are due to the initialization of Asciidoctor and its JRuby engine which is used to render the preview. Once that is complete, the preview should work fast. 

I also saw the slowly scrolling preview now and then, but only on Linux so far. I'll prepare a pre-release that will reduce the interaction with JCEF to save some CPU cycles. 

While I prepare that pre-release, I'd like to hear from you what "top" shows which process uses the CPU. Thanks!

**Comment by dvponomarev** [comment]
Observe one processor core at constant 100% on IDEA java process during preview initialization and during scrolling.
jcef_helper process uses less then 4%(of one core) in both cases.

After IDEA restart: scrolling uses no more than 30% of one processor core.

**Comment by ahus1** [comment]
I had a look at the scrolling JFR, and found that 30% of all CPU of IntelliJ are used by the sweeper thread (if I understand this correctly) - see screenshot below.

Don't know when this happens. Could you try to change your memory settings (from 8 GB to 4 GB or to 10 GB)?

I created pre-release 0.37.57 that minimizes the interaction with JCEF; maybe this helps? 
The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html). 

Please let me know if any of these changes improve your situation.

![image](https://user-images.githubusercontent.com/3957921/204053942-210cab31-0584-4a35-b097-ccfa60547095.png)

**Comment by dvponomarev** [comment]
Thanks, will try pre-release, but this requires several days, because the bug doesn't occur immediately after IDEA restart.

**Comment by dvponomarev** [comment]
Now I cannot reproduce the issue on pre-release and 0.37.54 :) May be it requires more time to reproduce, several weeks of IDEA Ultimate uptime, I don't know :)
Last time I observed issue and investigated it with profiler the problem was in C2 compiler which used 70% of processor core.
I think that the issue should be rejected... I'll try to collect more data if the problem returns.
Thanks for your help.

**Comment by ahus1** [comment]
I'm closing this issue for now as I didn't hear otherwise after your previous comment. If it re-appears, please comment here and I'll re-open the issue.
