### ISSUE TITLE
Allow running inline shell scripts

### ISSUE THREAD

**Issue by ctron** [asciidoctor/asciidoctor-intellij-plugin#1227]
## Why the new feature should be added

The markdown editor supports a nice feature, running inline code:

![image](https://user-images.githubusercontent.com/202474/203925210-dbbb0167-e7b5-4591-8ae4-e3984818ba22.png)

With a simple click on the green arrows, it executes the command in an IntelliJ terminal. This is great for walking through installation instructions.

## How the new feature should work

For all `[source,shell]` blocks, this should behave similar to the Markdown editor. Showing a green run icon, executing the script using IntelliJ standard functionality.

**Comment by ctron** [comment]
I just figured out it already does. But I was using the wrong block delimiter!

Instead of using (correct):

```
[source,shell]
----
----
```

I was using (wrong!):

```
[source,shell]
====
====
```

Which doesn't work, and is expected to not work. Sorry for the noise!

**Comment by ahus1** [comment]
Happy to hear this now works for you. Happy coding!
