### ISSUE TITLE
The {nbsp} macro is not recognized as space in spellchecker

### ISSUE THREAD

**Issue by widle** [asciidoctor/asciidoctor-intellij-plugin#1228]
## Observed vs. expected behavior

If I replace a space between two words with the non-breaking space macro, the spellchecker marks it as incorrect (reading the two words as a single one).

This does not seem to happen when writing English, but it does happen consistently when writing in Czech. I have Czech spellchecking enabled using the [Hunspell plugin](https://plugins.jetbrains.com/plugin/10275-hunspell), so the issue might be related with the plugin.

![spellchecker underlining two words separated with nbsp](https://user-images.githubusercontent.com/1525335/203958319-1c0d248c-d93e-4886-bf3c-4412da8a93dc.png)

## Environment

Plugin Version: 0.37.54

IntelliJ Details: 
Build #IC-222.4459.24, built on November 22, 2022
Runtime version: 17.0.5+7-b469.71 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

**Comment by ahus1** [comment]
Hi @widle - thanks for providing this example. I started to tune the tokenizer which prepares the content for the spell checker. 

I tried to setup the Hunspell plugin locally, then stumbled across a problem in IntelliJ 2022.3 which will hopefully be released soon: https://youtrack.jetbrains.com/issue/IDEA-306477/, and even with 2022.2 I still have problem with words with special characters on a Windows machine. 

I'll update this issue once a pre-release is available, and will ask you to test the change.

**Comment by ahus1** [comment]
Hi @widle - there's now pre-release 0.38.1 that includes the changes described above. Please give it a try and let me know if this works better for you.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by widle** [comment]
Hi @ahus1, I have tested the pre-release and can confirm it works well for me now, words are recognized as expected. Many thanks for your help! And also for the plugin as a whole, it's a great tool.

**Comment by ahus1** [comment]
Happy to hear this now works! Thanks for opening the issue in the first place, it wouldn't be the plugin it is today without the community that submitted tickets for new ideas and edge cases.

From this ticket I learned about the Hunspell plugin which I didn't know about before. As it supports languages which are not supported by for example the Grazie plugin, I'd like to document it [in the technical writers docs of the plugin](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/technical-writing/recommended-plugins.html).

I tried to set it up myself, but it didn't recognize some words. They still have the green lines below two of the words: 

![image](https://user-images.githubusercontent.com/3957921/205493115-3f87a404-9b16-4018-8414-de35ba1523f7.png)

Could you please describe how you set it up? I checked out the repository https://github.com/JetBrains/hunspell-dictionaries/tree/master/cs_CZ and pointed it to the file `cs_CZ.dic`, but it still highlights errors for me on a Windows machine. Is it maybe a charset issue, as my Windows machine is setup for Windows-1252? Thanks!

![image](https://user-images.githubusercontent.com/3957921/205493084-e21f916b-280a-4e2e-8a48-2490b478ce72.png)

**Comment by widle** [comment]
Hi,
I have actually applied two files to the plugin: the `cs_CZ.dic` and `cs_CZ.aff`. I think both are needed.

**Comment by widle** [comment]
Update: I upgraded IDEA to 2022.3 and the spellchecker has stopped working, so that's probably what you're seeing too.

**Comment by ahus1** [comment]
I found that the dictionary I used wasn't correctly converted to UTF-8 correctly. Once I fixed it, it started to work.

I created a PR: https://github.com/JetBrains/hunspell-dictionaries/pull/3

I've also added the plugin to the docs.

**Comment by ahus1** [comment]
I read some comment in this issue https://youtrack.jetbrains.com/issue/IDEA-307064, and this revealed the following news to me after some experiments:

* IntelliJ 2022.3 supports Hunspell dictionaries out-of-the-box. No additional plugin is required.
* Due to that, JetBrains will deprecate the Hunspell plugin. 
* Some users report problems, still I was able to use the Czech hunspell dictionary without problems.

I update the docs accordingly. If you find out that this doesn't work as I describe, or something new evolves, I'd be happy if you could leave a comment here.

**Comment by widle** [comment]
Hello, I'm sorry for not answering earlier, but anyway: I can confirm that since the update to 2022.3, my dictionaries work again. Many thanks for your help!
