### ISSUE TITLE
Toolbar icons for bold/italic trigger twice

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#123]
The toolbar icons don't work as expected (anymore?). Whenever I select a piece of text, and mark it as bold, italic, or code, it adds each markup character twice. As an example:

`it's a great day`

With 'great' selected, and then pressing 'bold', becomes:

`it's a **great** day`

Instead of:

`it's a *great* day`

**Comment by mojavelinux** [comment]
I wonder if this was done as a quick fix to get the formatting to work under any circumstances. The double marks are for unconstrained formatting (applies anywhere), whereas the single marks are constrained formatting (applies at boundaries of a word). The default should be constrained formatting. If possible, the action should detect when the unconstrained varient is needed.

**Comment by ahus1** [comment]
The MakeBold/MakeItalic used the unconstrained (twice the sign) formatting all the time. Therefore I re-label it as an enhancement.

I'm preparing a PR for this.

**Comment by mojavelinux** [comment]
Great! If you need help with the rules for constrained vs unconstrained, don't hesitate to ask.

**Comment by ahus1** [comment]
@bodiam, @mojavelinux - this is now included in the [0.15.0 preview release](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases/tag/0.15.0). Please give it a try if you have the time.

**Comment by mojavelinux** [comment]
It works beautifully!

One minor comment. When clicking on the strike through button, I'd like to see the role use the modern syntax:

```
[.line-through]#strike me#
```

It might be nice to have a toolbar button for "highlight", which is the `#` formatting without a role.

```
#mark me#
```

**Comment by ahus1** [comment]
I've changed the code to have the dot in the formatting. 

@mojavelinux - Please open a new ticket for the highlighting shortcut. I don't want to handle this in this ticket as I also need to find an icon for highlighting matching the existing icons.

**Comment by mojavelinux** [comment]
:+1:

**Comment by ahus1** [comment]
This has now been released as part of 0.15.1
