### ISSUE TITLE
"run in terminal" executes lines in the inverse order

### ISSUE THREAD

**Issue by pedrolamarao** [asciidoctor/asciidoctor-intellij-plugin#1231]
## Observed vs. expected behavior

Whenever I "run in terminal" a [source,shell] block containing multiple lines, these lines are run in the exact inverse order, from last to first.

## Steps to reproduce

1. Write this in an asciidoc file:

```adoc
[source,shell]
----
echo 1
echo 2
echo 3
echo 4
----
```

2. "run in terminal" this block

Actual output:

```shell
>> echo 4
>> echo 3
>> echo 2
>> echo 1
4
3
2
1
```

Expected output:

```shell
>> echo 1
>> echo 2
>> echo 3
>> echo 4
1
2
3
4
```

## Environment

Intellij IDEA running on Windows with a PowerShell terminal.

Plugin Version: 0.37.54

IntelliJ Details: IntelliJ IDEA 2022.2.4 (Ultimate Edition)
Build #IU-222.4459.24, built on November 22, 2022
Licensed to Pedro Lamarão
Subscription is active until April 11, 2023.
Runtime version: 17.0.5+7-b469.71 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1536M
Cores: 12
Non-Bundled Plugins:
    org.jetbrains.kotlin (222-1.7.21-release-272-IJ4167.29)
    org.asciidoctor.intellij.asciidoc (0.37.54)

Kotlin: 222-1.7.21-release-272-IJ4167.29

**Comment by ahus1** [comment]
Thanks for taking the time and letting me know about this. I can reproduce it with a PowerShell terminal. Testing it with bash on Windows, this works as expected. 

I traced it down to some internal functionality in IntelliJ, and I raised a bug upstream: https://youtrack.jetbrains.com/issue/IDEA-307043 - please upvote it. 

I close this issue as I can't change something in AsciiDoc plugin AFAIK. If there is any change and I can do something in the plugin, I'll update this issue.
