### ISSUE TITLE
4k resolution, font too small

### ISSUE THREAD

**Issue by gengjiawen** [asciidoctor/asciidoctor-intellij-plugin#125]
Another plugin, Markdown plugin([https://plugins.jetbrains.com/plugin/7793](https://plugins.jetbrains.com/plugin/7793)) has no problem.I use javafx to render.

**Comment by ahus1** [comment]
Please provide the name and version information of the IDE you are using. You can retrieve these from the menu _Help -> About_ and then click on _Copy to Clipboard_.

A screenshot would be helpful as well. 

Thanks.

**Comment by gengjiawen** [comment]
Below is my webstorm info. In fact, this problem occurred on IntelliJ IDEA and Pycharm too.
```
WebStorm 2016.2.1
Build #WS-162.1447.27, built on August 2, 2016
JRE: 1.8.0_102-b14 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
```
Screenshot
![Scrennshot](https://cloud.githubusercontent.com/assets/3759816/17461508/58810cf0-5cc1-11e6-89d3-04e3c1d16c05.png)

**Comment by ahus1** [comment]
I've looked at the Markdown plugin but didn't find an option for HiRes. Also lacking a 4k screen to reproduce. I think I need some help here.

**Comment by rdmueller** [comment]
I do have the same problem and can reproduce it on my MS surface pro 4.
How could I help?
A workaround could be a setting which let's you change the scaling. Standard for surface pro 4 is 200%.
Maybe this blog could also help: http://news.kynosarges.org/2015/06/29/javafx-dpi-scaling-fixed/

**Comment by ahus1** [comment]
@rdmueller - I've read the article and no obvious solution jumped at me. I would be great if you could run some tests here. 

it could help if you try out the markdown plugin side-by-side and see how that reacts. 

Please state what JDK you are using. Recent versions of IntelliJ for Window can use the 64bit OpenJDK JRE from JetBrains. They report as "JRE: 1.8.0_112-release-736-b13 amd64 / JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o". I'd prefer to use the JetBrains JVM for further testing.

At one point I suspected the AsciiDoctor CSS, but again there was no chance to debug this for me.

**Comment by rdmueller** [comment]
ok. here are some test results. I use the following IDE:

IntelliJ IDEA 2017.1
Build #IC-171.3780.107, built on March 22, 2017
JRE: 1.8.0_112-release-736-b13 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

I made four screenshots:

asciidoc with JavaFX:
![ad_fx](https://cloud.githubusercontent.com/assets/1856308/24819954/101e1a94-1be7-11e7-9a07-ea25d17854ff.png)

asciidoc with swing:
![ad_swing](https://cloud.githubusercontent.com/assets/1856308/24819968/1c2b99ce-1be7-11e7-9a15-7e7d1cf8eaa6.png)

markdown with JavaFX:
![md_fx](https://cloud.githubusercontent.com/assets/1856308/24819981/27b192f8-1be7-11e7-83c4-23a0d1730c66.png)

markdown with default renderer (whatever this is):
![md_default](https://cloud.githubusercontent.com/assets/1856308/24820000/3595d172-1be7-11e7-9847-84352decff02.png)

The asciidoc with JavaFX screenshot look ok here, but as you can see, the font of the paragraph is much smaller than normal. On a high DPI display, it is too small. But the title is even bigger and uses a different font...

The funny part is, that the markdown preview with the default renderer is even unreadable with this screenshot :-)

**Comment by jansorg** [comment]
I just came across this issue, maybe may comment is relevant. If not, just ignore this :)
IntelliJ does its own font scaling, depending on the platform. If you render px units then you should use JBUI.scale() afaik. Better render font sizes with pt units (which are then scaled by the Java text rendering engine, suitable for the current screen's DPI).

**Comment by Entea** [comment]
Bump, have the same issue :)

**Comment by ahus1** [comment]
@jansorg was actually right about JBUI.scale(). I ported the change from the Markdown plugin, and also ported a bug fix for Windows 10 available in the Markdown plugin. 

The release 0.20.5 is available as a preview from [the releases page](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases).

As I still don't have a hiDPI display, I need someone to try it out. One thing I noticed already: when you switch to presentation mode, the preview now scales!

Please comment.

**Comment by ahus1** [comment]
Another note: hiDPI will only work with the JavaFX preview. Volunteers to fix the Swing preview are welcome to join in.

**Comment by rdmueller** [comment]
Just gave the preview a try - JavaFX works great with my highDPI settings. Swing is unusable on my device :-)
Don't know what changed in the current version, but my older Version 0.20.1 already worked fine for me.

Thanx for all your work!

**Comment by ahus1** [comment]
I close this issue as this now works in JavaFX preview. 

If someone wants this to work also in the Swing preview, support by creating a pull request. I'm happy to guide you through the necessary steps. You'll need Java skills for this task. 

The scaling feature would also allow for a zoom of the preview. Some ideas about the UI for this would be needed. I'd be happy to guide there as well, including wiring IDEA internals.
