### ISSUE TITLE
Antora component schema should support boolean type for `prerelease` and the `ext` property

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#1254]
## Observed vs. expected behavior

When opening an `antora.yml` file with 

```
prerelease: true
```

or 

```
ext:
  collector:
   ...
``` 

the IDE shows a warning, as the schema for `prerelease` doesn't allow a boolean value, and the property `ext` is unknown.

## Steps to reproduce

Use: [antora.yml from the Eclipse Che docs](https://github.com/eclipse-che/che-docs/blob/0c0deddbeb5292db8d86ccf26dbe41908a06d336/antora.yml)

## Environment

Plugin Version: 0.38.4

cc: @themr0c

**Comment by ahus1** [comment]
Fixed in upcoming release.

**Comment by ahus1** [comment]
This is part of pre-release 0.38.5.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by mojavelinux** [comment]
Keep in mind the `ext` key is still in alpha as only Antora Collector supports it. That will likely change when Antora Collector goes final.

**Comment by ahus1** [comment]
This change only prevents the "ext" property in the YAML file to show with a warning. That warning might otherwise confuse users.

**Comment by mojavelinux** [comment]
Ack. Just wanted to give you a heads up that we still haven't made a final decision about the name yet. We also haven't yet decided whether this is an open schema or whether the keys are fixed (or if there is an reserved part that is an open schema). We're letting experience be the guide here.
