### ISSUE TITLE
Quillbot integration

### ISSUE THREAD

**Issue by jvmlet** [asciidoctor/asciidoctor-intellij-plugin#1263]
If https://quillbot.com/ exposes API, would be great to have it integrated.

**Comment by ahus1** [comment]
Thanks for suggesting this. Looking at their FAQ they don't have an API. 

If there would be a similar service with an API, I would rather see this as a separate plugin so it can evolve at its own speed.

https://help.quillbot.com/hc/en-us/articles/4541472549527-Does-QuillBot-Offer-an-API-
