### ISSUE TITLE
"Smart single quotes" live template introduces extra backticks

### ISSUE THREAD

**Issue by blueglyph** [asciidoctor/asciidoctor-intellij-plugin#1286]
## Observed vs. expected behavior

When I select text and type `'` (single quote) then `` ` `` (backtick), I get a single quote and **two** backticks around the selected text, instead of one single quote and **one** backtick. 

## How to reproduce ##

- I select "word" in the following line:

```Put word between curly single quotes.```

- I type `'` then `` ` ``

=> result:

```Put '``word``' between curly single quotes.```

![image](https://user-images.githubusercontent.com/31706195/215286947-e5bc1c27-ad57-48f6-8624-32092afb7e7a.png)

I have to manually delete the extra pair of backticks to get the expected effect.

## Additional information ##

- I only have this problem in AsciiDoc files, not in other types (source code, Markdown, ...).
- I don't have this problem with double quotes if I select text then type `"` and `` ` ``.
- I don't have this problem if I type `` '` `` before the text, then after the text, it's just less convenient.
- The options are the default ones; in particular I have both single-quote and double-quote live templates enabled:

![image](https://user-images.githubusercontent.com/31706195/215286720-7bcbb70d-66f5-4dc3-8899-a9fb35e85c03.png)

## Environment

Plugin version:    org.asciidoctor.intellij.asciidoc (0.38.9)

> IntelliJ IDEA 2022.3.1 (Ultimate Edition)
> Build #IU-223.8214.52, built on December 20, 2022
> Runtime version: 17.0.5+1-b653.23 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> Windows 10 10.0
> GC: G1 Young Generation, G1 Old Generation
> Memory: 2024M
> Cores: 16
> Registry:
>     action.toolbar.position.bottom.on.mac=true
>     caches.scanningThreadsCount=8
>     ide.ui.new.file.chooser=true
> 
> Non-Bundled Plugins:
>     org.rust.lang (0.4.186.5143-223)
>     com.intellij.nativeDebug (223.8214.16)
>     org.asciidoctor.intellij.asciidoc (0.38.9)
> 
> Kotlin: 223-1.7.21-release-272-IJ8214.52

**Comment by ahus1** [comment]
Thanks for reporting this, I agree this should be fixed. 

In the meantime: The "around template" for single quotes is accessible via the shortcut Alt+Ctrl+T.

![image](https://user-images.githubusercontent.com/3957921/215314752-b5863c1d-b459-4cef-b0a1-6f6359dc3e83.png)

**Comment by blueglyph** [comment]
@ahus1 Thanks for the suggestion!

It would even be more convenient if it could be accessed directly by a shortcut, is there a way to map those live templates? I don't see them in the Keymap, and Alt-Ctrl-T only brings the "Surround With" menu.

Creating a macro is possible but it's very slow and awkward to use because macros don't work very well in IntelliJ (for ex. if I click on ad-smart-single-quotes, this is not registered, so I have to go down there one down key at a time since there is no shortcut numbers for those options).

**Comment by ahus1** [comment]
@blueglyph - true, I see that those are too many strokes. Let's see that this one gets into the next pre-release.

**Comment by blueglyph** [comment]
@ahus1 Thanks!

I've seen a PR about [keymapping live templates](https://youtrack.jetbrains.com/issue/IDEA-67811), which would be really helpful. But it looks like they are not planning to do that anytime soon. I've added another vote to it, just in case, but I've seen enough of those PRs to believe it won't be implemented anytime soon.

**Comment by blueglyph** [comment]
I'm looking at `org/asciidoc/intellij/actions/FormattingQuotedTypedHandler.java`, more precisely at those lines:

```java
        // ... or add it around the text
        int border = 0;
        if (newText == null) {
          boolean word = FormatAsciiDocAction.isWord(editor.getDocument(), selectionStart, selectionEnd, "" + c);
          if (word || c == '"' || c == '\'' || c == '~' || c == '^') {
            newText = c + selectedText + c;
            border = 1;                                                      // (1)
          } else {
            // prefix a string to prevent that adding two chars results in an integer
            newText = "" + c + c + selectedText + c + c;                     // (2)
            border = 2;
          }
        }
```

After quickly recompiling the plugin and going a test, it seems that
- when c == ` `` ` inside `"`, it triggers (1)
- when c == ` `` ` inside `'`, it triggers (2), which causes the issue

And indeed, if I do a non-word selection, the same problem occurs with `"` and ` `` `! So there was another hidden issue.

**Comment by blueglyph** [comment]
Changing the test to include the backtick like this seems to solve the issue, but I'm not familiar with that method to be sure there aren't any side-effects:

```java
          if (word || c == '"' || c == '\'' || c == '~' || c == '^' || c == '`') {
```

**Comment by blueglyph** [comment]
I'm creating the pull request with a reference to this issue in the git message.

**Comment by ahus1** [comment]
There's now pre-release 0.38.10 that contains this change. I plan to publish it as a regular release soon as this release contains also a fix to support the 2023.1 EAP release. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by blueglyph** [comment]
Thanks!

**Comment by ahus1** [comment]
Triggered the build for the public release, will be available within the next hour. Thank you for your contribution!
