### ISSUE TITLE
Should support scrolling preview to edit position

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#129]
IntelliJ's markdown plugin and also AsciidocFX can scroll the preview automatically to the current cursor position. 

The automatically scrolling preview will then be the way the JavaFX preview will work. 

Any objections here? I'd like to keep the "what to implement" inside this issue. The "how to implement" in the pull request.

**Comment by ahus1** [comment]
See PR #130

**Comment by ahus1** [comment]
A first preview is now available in the [0.15.0 preview release](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases/tag/0.15.0) available form the releases.

The preview will start scrolling once the editor position reaches to the top or bottom of the preview. Also if you edit the text and have scrolled the preview to a different position, the preview will snap back to the edit position.

I'm looking for feedback if this is the "expected" behavior from a user's perspective (aka "don't make me think"). There might also be corner cases where the preview is unable to correctly determine the current editor position in the preview.

Please give it a try in your daily work.

**Comment by mojavelinux** [comment]
In general, I'd say this is a very good start. As long as the preview is in view of what is being edited, I think that's what most people want.

In the future, it might be nice to have a scroll sync so that when you scroll the source it also scrolls the preview. Since that might not always be desired, it might be necessary to have that be behind an option.

>  if you edit the text and have scrolled the preview to a different position, the preview will snap back to the edit position.

I noticed that if you use an item from the toolbar, it doesn't scroll to the position of the text that was affected.

**Comment by ahus1** [comment]
Dan, you are right, the behavior is different from what I described above. 

The *actual* current behavior: if have scrolled the preview to a different position, the preview will snap back **to the cursor position once you move the cursor to a different row**.

I'm not a fan of sync scrolling, but it might be the thing the users expect as a default. So there might be options like "sync/lazy/off" with sync being the default, and lazy the currently implemented behavior.

I'm looking forward to more comments on this.

**Comment by mojavelinux** [comment]
>  So there might be options like "sync/lazy/off" with sync being the default

I like that proposal, though I would support lazy as the default.

**Comment by kastork** [comment]
Personally I don't need the sync scrolling, I basically like the current behavior.

This might be a separate feature, but I'd like the inverse relationship to have a similar capability.  That is, I'd like a way to ask the source window to move to where the preview is -- this can be approximate.  Perhaps something like a control click on an element in the preview brings the corresponding source line into view.

Great plugin, I use it frequently.

**Comment by ahus1** [comment]
@kastork, great idea. Let's continue the discussion in PR #141.

I also got used to the lazy scrolling. So I'm thinking about not implementing the sync scrolling at all.

**Comment by ahus1** [comment]
I'll keep the lazy preview "as is". The suggested click-on-preview feature will be part of 0.16.1 to be released later today.
