### ISSUE TITLE
The file you're editing is outside of the current project's folder.

### ISSUE THREAD

**Issue by maharvey** [asciidoctor/asciidoctor-intellij-plugin#1318]
## Observed vs. expected behavior

When I open an asciidoc file in CLion or IntelliJ, it always complains that: _the file you're editing is outside of the current project's folder. Autocomplete and validation is limited_. There is a link to "tell me more" that does not solve the issue.

In a project, I create a doc (documentation) directory that is within the project directory, at the root. I can put text files, plantUML files, and markdown files in there and they all work as expected, but asciidoc files all produce the same cryptic warning that something is broken. (It specifically says certain features are limited, which I take to mean not functional or perhaps not fully functional.) I have tried moving the asciidoc files to other directories within the project, including moving them into source directories and that does not solve the issue.

The "tell me more" link says that files opened individually are not part of the project, and files opened as part of a directory are. This makes no sense to me, as all my other files (source or otherwise) are part of the project. I tried creating asciidoc files using the new file dialog, and on the command line, but they behave the same way. Opening an asciidoc file by double clicking in the Project tree produces the warning; I cannot find another way to open the file for editing, except to drop to the command line and edit it in vim which completely defeats the point of using a plugin.

I tried closing the entire project containing the *.adoc files and re-opening it "as a project" (?) but that makes no difference, the warning never goes away.

The expected behavior is that the plugin works, or provides documentation on how to configure it correctly. Working in this case means "does not produce warnings, and does not have functionality disabled."

I don't like to have a broken plugin and want to fix it, not just dismiss the error.

## Steps to reproduce

1. Install asciidoc plugin into an Jetbrains product
2. Create an *.adoc file anywhere in the project
3. Double-click the *.adoc file and open it
4. Observe the warning banner at the top of the file window.

## Environment

Plugin Version: 0.38.12

IntelliJ Details: CLion 2022.3.1
Build #CL-223.8214.51, built on December 20, 2022
Licensed to Michael Harvey
You have a perpetual fallback license for this version.
Subscription is active until January 8, 2024.
Runtime version: 17.0.5+1-b653.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.94-1-manjaro
GC: G1 Young Generation, G1 Old Generation
Memory: 2000M
Cores: 12
Registry:
    run.processes.with.pty=TRUE

Non-Bundled Plugins:
    IdeaVIM (2.0.0)
    PlantUML integration (5.23.0)
    org.asciidoctor.intellij.asciidoc (0.38.12)

Current Desktop: XFCE

**Comment by ahus1** [comment]
Thanks for sharing this. The behavior you describe shouldn't occur when you choose "File | Open..." and choose a folder which is then the root of a project. 

Could you please share a screenshot with a small example project wich the project view opened?

**Comment by ahus1** [comment]
I haven't heard back from you for two weeks, so I close this issue. If this issue still exists, provide more details by adding a comment to this issue and I'll re-open it.
