### ISSUE TITLE
Plantuml diagrams stopped working in pdf

### ISSUE THREAD

**Issue by LukeCz** [asciidoctor/asciidoctor-intellij-plugin#1323]
## Observed vs. expected behavior

Embedded diagrams rendered with Kroki (default public server) are displayed fine in preview but fail to rendered in pdf - replaced by broken links.
The issue is that the embedded link in pdf is broken into multiple lines. In the example provided in the attachment the link is
```
[Diagram] |
https://kroki.io/plantuml/svg/eNpzKC5JLCopzc3hKs7OzCtILErMVQjJLMlJdcvPKwkuqcxJVcjLL8pNzOE
qAYkqqJalFhVn5udpaHI5pOalADUCAEw8GJc=

```
while it should be a single line. I.e. if you manually concatenate the 2 lines it is a valid URL but when opening in pdf viewer only the first line is clickable as a link.

## Steps to reproduce

[example.zip](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/11145837/example.zip)
Just a simplest adoc file, does not matter if part of Antora structure or not. Kroki server enabled in settings with default (empty) URL.

## Environment

Plugin Version: 0.38.12

IntelliJ IDEA 2023.1 (Community Edition)
Build #IC-231.8109.175, built on March 28, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4006M
Cores: 20
Non-Bundled Plugins:
    idea.plugin.protoeditor (231.8109.91)
    com.intellij.grazie.pro (0.3.214)
    org.asciidoctor.intellij.asciidoc (0.38.12)

Kotlin: 231-1.8.20-IJ8109.175

**Comment by ahus1** [comment]
I prepared the change and it will be part of the next release. I also update the docs. I'll comment here once a pre-release is available.

**Comment by ahus1** [comment]
This is part of pre-release 0.38.13. Please let me know if you still experience issues. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
