### ISSUE TITLE
Do not follow (external) links in the internal browser - open a real browser instead

### ISSUE THREAD

**Issue by ascheman** [asciidoctor/asciidoctor-intellij-plugin#1324]
## Why the new feature should be added

Not sure wether the current behaviour isn't a bug?

As a user of the plugin I would like to open an external bug if I click on an URL in the preview in order to not confuse the UI and still see the preview instead of a referenced page.

## How the new feature should work

* If I click on some internal link (e.g., `link:../another/document.adoc[]`) I would like to open the referred document,
* if I click on some external link (e.g., `https://some.site.tld/`) I would like to open this link in my (default) browser.

Additionally it would be great if I could configure how to open it (e.g., which Browser, new window vs. new tab).

**Comment by ahus1** [comment]
Thanks for reporting this. And yes, the expected behavior you describe is the implemented behavior. 

Have you been able to reproduce it? 

There is some JavaScript code running after each preview refresh which instruments all links. Maybe it is a timing issue... once you manage to navigate away from the preview, all pages that follow will stay within the preview window.

**Comment by ahus1** [comment]
Have you been able to reproduce the problem? Was it maybe a very long document, or with complex Math or embedded diagrams?

**Comment by ascheman** [comment]
> Have you been able to reproduce it?

Unfortunately not. I vaguely remember that I had seen this already (long time ago). But I cannot reproduce it ...

> There is some JavaScript code running after each preview refresh which instruments all links. Maybe it is a timing issue... once you manage to navigate away from the preview, all pages that follow will stay within the preview window.

... Seems to be a race condition? And yes, once the preview has navigated to another page you are trapped inside of that page (No back button or other option to get back).

**Comment by ascheman** [comment]
> Have you been able to reproduce the problem? Was it maybe a very long document, or with complex Math or embedded diagrams?

Nope, it was a rather small document without much content and nothing special like Math.

**Comment by ahus1** [comment]
Thanks for investigating this. Yes, I assume this is a race condition. 

With the current version of the plugin, the preview is reset once the user changes something in the editor. The next version of the plugin will watch the URL for the preview and will reset the preview automatically.

**Comment by ahus1** [comment]
This is part of pre-release 0.38.13. Please let me know if still occurs. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ascheman** [comment]
No further issues within the last days (using 0.38.13 now).
