### ISSUE TITLE
include file not found 

### ISSUE THREAD

**Issue by qck4fun** [asciidoctor/asciidoctor-intellij-plugin#1325]
## Observed vs. expected behavior

We're having trouble with newer plugin versions accessing files using include such as shown on the picture

![image](https://user-images.githubusercontent.com/7276555/230046023-dfca6735-ceb7-40ab-a39c-f44e3be98eda.png)

```
include::{partialsdir}/generated-snippets/company-backoffice-controller-test/company/add-identity/path-parameters.adoc[]
```

This issue can be reproduced on versions: 0.38.12, 0.38.10, 0.38.9

but the same configuration works on version 0.38.4

What should I do to fix it?

Thank you

IntelliJ Details:

IntelliJ IDEA 2022.3.2 (Ultimate Edition)
Build #IU-223.8617.56, built on January 26, 2023
Runtime version: 17.0.5+1-b653.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.2.6-76060206-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Non-Bundled Plugins:
    org.asciidoctor.intellij.asciidoc (0.38.4)

Kotlin: 223-1.8.0-release-345-IJ8617.56
Current Desktop: pop:GNOME

**Comment by ahus1** [comment]
Thanks for reporting this and sorry for this regression. I was able to reproduce this on Linux systems. 

As a fix, consider replacing `{partialsdir}` with `partial$` which is the modern syntax of Antora. This will work on Linux and Windows systems alike.

The next version of the plugin will support `{partialsdir}` again. I'll update this issue once a pre-release is available.

**Comment by mojavelinux** [comment]
It should be noted that `{partialsdir}` is deprecated in Antora, and thus not an intrinsic attribute you should rely on anymore.

**Comment by qck4fun** [comment]
I can confirm the fix is working. Thank you! :pray:
