### ISSUE TITLE
When expanding selection, would be nice to select sentence before paragraph.

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#1332]
See attached animated gif.

![expand-word-up-to-sentence-before-paragraph](https://user-images.githubusercontent.com/1031625/232980054-229ea041-6684-481b-8a9e-b2c0d18257ca.gif)

In it I have a two sentence paragraph, where the second sentence is in brackets.  If I use ctrl-W to expand selection, the plugin correctly increases the selection from word, to sentence, to sentence + brackets, to entire paragraph.

If however I remove the brackets, then extending the selection goes from word, to entire paragraph.

It would be nice if instead the selection would go from word, to sentence, to paragraph.

**Comment by ahus1** [comment]
Thanks for suggesting this. I did a change for the next upcoming release. I'll update this issue once a pre-release is available.

**Comment by ahus1** [comment]
The pre-release 0.38.18 is now available which fixes this bug. Please give it a try if it works for you as expected.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by danhaywood** [comment]
Did a couple of tests... certainly an improvement, but some slightly inconsistent behaviour:


![ctrl-w-expand-sentence-not-quite-there-1](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/1031625/ef218266-65bd-4a8d-b156-0959b4217f4f)

and

![ctrl-w-expand-sentence-not-quite-there-2](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/1031625/888bcdfc-046a-460d-924b-49b8cd764d84)

**Comment by danhaywood** [comment]
@ahus1  - can this be re-opened on the basis of the above?  else create a new ticket I suppose and copy over those examples to it.

**Comment by ahus1** [comment]
Reopened. It would be great if you could copy the text to the issue for simpler testing.

**Comment by ahus1** [comment]
There's now pre-release 0.38.19 wich includes a rework. I'd did a local test and it look ok to me. I'd be happy if you could take a look as well and comment here with your findings.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by danhaywood** [comment]
Agreed, looks good to me - thanks!

**Comment by ahus1** [comment]
Thank you for the test - I'm closing this issue as it works for you.
