### ISSUE TITLE
How to include custom extensions that depend upon gems

### ISSUE THREAD

**Issue by david0** [asciidoctor/asciidoctor-intellij-plugin#1333]
## Description

Hi,
we have a custom asciidoctor extension that depends upon gems like prawn.

unfortunately this fails with :
```
unable to render AsciiDoc document

org.jruby.exceptions.LoadError: (LoadError) no such file to load -- prawn

(the full exception stack trace is available in the IDE's log file. Visit menu item 'Help | Show Log in Explorer' to see the log)
```

is there anyway to make 3rd party dependencies like prawn available?

(it can be reproduced e.g. by adding `require "prawn"` to [const-inline-macro.rb](https://github.com/arquillian/smart-testing/blob/master/.asciidoctor/lib/const-inline-macro.rb)

**Comment by ahus1** [comment]
Thanks for reaching out with this question. In the case of "prawn", the simplest thing to do would be to have the AsciiDoc plugin enable the PDF support, which will download asciidoctor-pdf which will include prawn. 

This will be downloaded when you click on the "PDF" button, or when accessing the plugin's settings an clicking the download action. 

Please let me know if you miss any other gem. It might work if you put the other needed gems in the same folder and require them with a relative path like it is done in the example with `require 'copy-to-clipboard-inline-macro/extension'`. 

![image](https://user-images.githubusercontent.com/3957921/233438387-fccddf47-a304-4950-9c51-28b9bc485a7e.png)

**Comment by david0** [comment]
Thanks, that fixes the problem.
We add an rouge lexer too and rexml but that is working too.

Another workaround I came up with in the meantime might be helpful for future readers of this issue:
```ruby
ENV['GEM_PATH']="/usr/local/lib/ruby/gems/3.1.0/"
require 'rubygems'
Gem.use_gemdeps('/absolute/path/to/your/extension/Gemfile.lock')
```
