### ISSUE TITLE
Add toolbar button to mark / highlight a span of text

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-intellij-plugin#134]
It might be nice to have a toolbar button to mark / highlight a span of text. It would produce the following markup.

```
#text#
```

or

```
##t##ext
```

By default, the marked text will be highlighted (using the `<mark>` HTML tag). But it also sets up the user to be able to apply a custom role, which may cause the text to be styled differently (depending on how the role is interpreted).

```
[.application]#text#
```

**Comment by ahus1** [comment]
The upcoming release will have the toolbar button for highlighting text.

![image](https://user-images.githubusercontent.com/3957921/66275228-d8149500-e886-11e9-9325-9113c2e39842.png)

**Comment by ahus1** [comment]
Pre-release 0.30.9 is now available that contains this change.
