### ISSUE TITLE
Run Snippet in Terminal does not use correct shell

### ISSUE THREAD

**Issue by reitzig** [asciidoctor/asciidoctor-intellij-plugin#1340]
## Observed vs. expected behavior

1. Include a bash script snippet AsciiDoc
   ![image](https://user-images.githubusercontent.com/4246780/234324309-85d43f5f-6e53-4929-92e4-1bf86c5f958a.png)

 2. Click the gutter icon to "Run in Terminal"

***What is the expected result?***

- A terminal window opens, running bash
- The command is run

***What happens instead?***

- A terminal window opens with the user's default shell (fish, in my case)
- The command is run, but fails due to syntax differences
  ![image](https://user-images.githubusercontent.com/4246780/234324523-d37c9ef1-8521-4192-8908-1253668ae050.png)

---

FWIW, if the specified snippet language was `shell`, I'd say the behaviour is fair. With `bash` explicitly given, though, I expect different behaviour.

I reported [IDEA-318953](https://youtrack.jetbrains.com/issue/IDEA-318953) since I'm seeing the same behaviour with their bundled Markdown plugin. Can't say which subsystem needs changing, but since they assigned it to Lang.Markdown, I'm mirroring here.

## Environment

Plugin Version: 0.38.13

IntelliJ Details: PyCharm 2023.1 (Professional Edition)
Build #PY-231.8109.197, built on March 29, 2023
Runtime version: 17.0.6+10-b829.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-69-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2500M
Cores: 8
Registry:
    debugger.click.disable.breakpoints=true
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    org.jetbrains.plugins.go-template (231.8109.91)
    com.github.mikesafonov.jenkins-linter-idea-plugin (0.6.0)
    com.intellij.ideolog (203.0.30.0)
    ir.msdehghan.plugins.ansible (0.92)
    Key Promoter X (2023.1.0)
    com.crunch42.openapi (1.52)
    com.intellij.plugins.macoskeymap (231.7515.9)
    name.kropp.intellij.makefile (231.8109.91)
    com.intellij.kubernetes (231.8109.91)
    org.asciidoctor.intellij.asciidoc (0.38.13)
    ru.meanmail.plugin.requirements (2022.4.1)
    net.ashald.envfile (3.4.1)
    mobi.hsz.idea.gitignore (4.5.0)
    org.sonarlint.idea (8.1.0.65508)
    com.dmarcotte.handlebars (231.8109.91)
    org.nik.presentation-assistant (1.0.10)

Current Desktop: i3

**Comment by ahus1** [comment]
Thanks for raising this also in JetBrain's issue tracker. I'm re-using those bits of the JetBrains platform, and will need to wait once they fix this. I started watching the upstream issue for notifications. 

Until there is change there, there is AFAIK no way to solve this for the AsciiDoc plugin. I was thinking to send the name of the shell as a "prefix" when there is a new shell, but I can't determine if this is the first command run in a shell. Let's see what the JetBrains people come up with.

**Comment by ahus1** [comment]
There hasn't been a change in the upstream issue. Until JetBrains comments there (or even better fixes it), there is not much I can do here. 

I've subscribed to the upstream issue. While I wait for some activity there, I close this issue. I might then re-open this issue, or open a new issue depending on the result.
