### ISSUE TITLE
How to disable/hide preview-in-browser buttons?

### ISSUE THREAD

**Issue by static-moonlight** [asciidoctor/asciidoctor-intellij-plugin#1351]
Whenever the mouse pointer has been moved over the editor area, there will be a small button panel for a short amount of time in the top-right corner with buttons to open a preview with different browsers. Often this panel, even when it's small, get is the way and hides the text below it. Since I find that annoying and I never ever used that feature before, I would like to disable or hide it.

How do I do that?

**Comment by ahus1** [comment]
Thanks for reaching out. There is a general "Web Browsers and Preview" option in IntelliJ's settings. Once you disable the option "For HTML Files", the button panel should be gone. You can also make it smaller by disabling some of the browsers you don't want to see. 

See below for a screenshot. Maybe this should be added to the docs. The feature of opening the AsciiDoc contents in a browser is currently described on the page [Editing Content](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/editor.html) starting at "In the editor, the user can select from a list of browsers that are shown in the upper right corner of the editor to preview the document...". do you want to give it a try and add a paragraph on how to disable this? 

![image](https://user-images.githubusercontent.com/3957921/236932172-aa5d7909-0dfe-4c60-a77d-00287cb8c7f9.png)

**Comment by ahus1** [comment]
Closing this question as I assume it was answered. Please comment again if you want it to be re-opened.
