### ISSUE TITLE
Rearranging editor and preview pane

### ISSUE THREAD

**Issue by kszafran** [asciidoctor/asciidoctor-intellij-plugin#136]
AsciiDoc Plugin Version: 0.14.2

IDE Name and Version: IntelliJ IDEA 2016.2.2 Ultimate

As far as I can see there is no way to rearrange the editor and preview panes. I would be very useful if we could e.g. switch their places (to have preview on the left and editor on the right), or split them horizontally (e.g. to have the preview on the bottom, and editor on top). It would suit different monitors and different user preferences better.

**Comment by chkypros** [comment]
I came for the issue described in the last line. I use my IDE on a monitor at a vertical position. Thus, the vertical split results in two narrow and long panes. Right now as a workaround I split the IDE's tab into two, horizontally and have one tab as editor and the other as preview.

Setup:
AsciiDoc Plugin Version: 0.24.4
IDE Name and Version: IntelliJ IDEA 2019.1 Ultimate

**Comment by ahus1** [comment]
I've added a horizontal split view that is accessible from the settings menu starting from version 0.26.2. Vertical split is still the default. I attach a screenshot at the end of this comment.

This version is available as a pre-release from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases). Please download and install it manually. 

As you are upgrading from 0.24.4, there are several other changes included in this pre-release as well. Please have a look at the [CHANGELOG](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CHANGELOG.adoc) before upgrading.

Please provide feedback in this ticket if this works for you.

![settings](https://user-images.githubusercontent.com/3957921/57889960-85cecb00-7836-11e9-841b-719998dc9c36.png)

**Comment by mojavelinux** [comment]
So cool!

**Comment by ahus1** [comment]
The next preview release will support also switching left/right and upper/lower as requested in this ticket.
