### ISSUE TITLE
Error when using diagrams with a local Kroki instance

### ISSUE THREAD

**Issue by a-bronx** [asciidoctor/asciidoctor-intellij-plugin#1361]
## Observed vs. expected behavior

An Asciidoc document includes a simple Mermaid diagram:

```
= Test diagrams

[mermaid, svg]
----
gitGraph
  commit
  commit
----
```

A local Kroki server is running on `http://localhost:8000` (in a Podman container). The server is independently (using a VS Code plugin) confirmed to be functional and producing the diagrams.

The IDEA plugin is configured to use the Kroki server instead of a public server:

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/2594227/2a1ee9fe-46a1-486a-9ba5-7aeaa0f7a6d4)

Expected: the diagram is shwon in the preview.
Observed: an `Error 503: Connection refused: /127.0.0.1:8002` string instead of a diagram:

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/2594227/124170a0-0156-433b-ae58-1609d42cd709)

## Environment

Plugin Version: 0.38.13

IntelliJ IDEA 2023.1.2 (Community Edition)
Build #IC-231.9011.34, built on May 15, 2023
Runtime version: 17.0.6+10-b829.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 750M
Cores: 16
Non-Bundled Plugins:
    org.asciidoctor.intellij.asciidoc (0.38.13)

Kotlin: 231-1.8.21-IJ9011.34

----
P.S. Also, looks like the IdeaJ plugin does not respect `diagram-server-*` attributes defined in the `.asciidoctotconfig.adoc`, probably should be a separate issue.

**Comment by ahus1** [comment]
Thanks for reporting this. I have to admit I've never used it this way myself. Please provide the details on how you started Kroki via podman. 

BTW: I'm a bit confused that one URL notes "8000", while another displays "8002" in the error message. Hm.

**Comment by a-bronx** [comment]
I used the Kroki's own instructions: https://docs.kroki.io/kroki/setup/use-docker-or-podman/   , following them exactly.

Yes, the offset between the configured and queried ports is what I noticed immediately too.

**Comment by a-bronx** [comment]
The issue is resolved -- actually it was a wrong Kroki configuration on my side. I finally [noticed](https://docs.kroki.io/kroki/setup/install/#_the_kroki_container) that the default `yuzutech/kroki` image does not include Mermaid diagram server by default, but requires to run a "companion" container (`yuzutech/kroki-mermaid`) which listens to the port `8002`. And it looks like the VS Code extension continued using the online server (either falling back, or ignoring the config), which gave me a perception of a working local server and confused me.

After composing and running both containers, diagrams finally appeared in the preview.

Here is a `compose.yml` file that made it working:

```yaml
services:
  kroki:
    image: yuzutech/kroki:latest
    depends_on:
      - mermaid
    environment:
      - KROKI_MERMAID_HOST=mermaid
    ports:
      - "8000:8000"
  mermaid:
    image: yuzutech/kroki-mermaid:latest
    expose:
      - "8002"
```

**Comment by ahus1** [comment]
Interesting, thanks you for continuing to investigate it. 

BTW, if the only diagrams you're using are Mermaid diagrams, the AsciiDoc plugin for IntelliJ includes an experimental support for Mermaid diagrams out of the box. I seems to works ok, although not all feature might work at the moment - see #1280.

You can enable it in the plugin's settings. I'd be happy to hear your feedback about it.

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/3957921/2b1138b1-27e6-40b4-b08c-35ac5820e56f)

**Comment by a-bronx** [comment]
I need Mermaid only for gitGraph diagrams, other than that I prefer PlantUML.

BTW, why is the plugin not attempt using the `diagram-server-url` or `kroki-server-url` attributes in the `.asciidoctorconfig.adoc` file? Is it by design? What is a recommended way to make everyone in a team to use a specific Kroki server without making them to manually conifgure the plugin?

**Comment by ahus1** [comment]
For PlantUML, you could use the embedded asciidoctor-diagram - this works well with the built-in Mermaid Diagrams. My previous comment was wrong.
 
The current behavior is that one Kroki is enabled, a setting of `kroki-server-url` would override the Kroki server URL. If you want the current behavior to change, this would require a new ticket to discuss how this should work in the future.
