### ISSUE TITLE
NoMethodError rendering Structurizr diagram

### ISSUE THREAD

**Issue by timw** [asciidoctor/asciidoctor-intellij-plugin#1364]
## Observed vs. expected behavior

Attempting to include a Structurizr diagram in an Asciidoc file. 
Support for this was added to asciidoctor-diagram in 2.2.8 (https://github.com/asciidoctor/asciidoctor-diagram/issues/386).

The `[structurizr]` diagram type is detected, but rendering fails with the following error in the logs:

> 2023-05-27 09:18:24,216 [ 124293] SEVERE - org.asciidoctor.jruby.internal.JRubyAsciidoctor - org.jruby.RubyNoMethodError
> 2023-05-27 09:18:24,217 [ 124294]   WARN - #org.asciidoc.intellij.AsciiDocWrapper - unable to render AsciiDoc document
> org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.NoMethodError: (NoMethodError) asciidoctor: FAILED: /Users/timw/projects/indexity/empi/indexing/backend/dev/doc/struct_test.adoc: Failed to load AsciiDoc document - undefined method `gsub' for #<Asciidoctor::Reader:0x4c216325>
> 	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:330)
> 	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:346)
> 	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.convert(JRubyAsciidoctor.java:341)
> 	at org.asciidoc.intellij.AsciiDocWrapper.render(AsciiDocWrapper.java:816)
> 	at org.asciidoc.intellij.AsciiDocWrapper.render(AsciiDocWrapper.java:782)
> 	at org.asciidoc.intellij.annotator.AsciiDocExternalAnnotatorProcessor.doAnnotate(AsciiDocExternalAnnotatorProcessor.java:98)
> 	at org.asciidoc.intellij.annotator.AsciiDocExternalAnnotatorProcessor.doAnnotate(AsciiDocExternalAnnotatorProcessor.java:52)
> 	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:204)
> 	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:198)
> 	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:274)
> 	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$1(ExternalToolPass.java:176)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
> 	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
> 	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:361)
> 	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:339)
> 	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:175)
> 	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:350)
> 	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:340)
> 	at com.intellij.util.ui.update.MergingUpdateQueue.doExecute(MergingUpdateQueue.java:297)
> 	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:280)
> 	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:245)
> 	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:249)
> 	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:365)
> 	at com.intellij.util.Alarm$Request.run(Alarm.java:354)
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
> 	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:272)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:248)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:28)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:221)
> 	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:227)
> 	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:210)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
> 	at java.base/java.lang.Thread.run(Thread.java:833)
> Caused by: org.jruby.exceptions.NoMethodError: (NoMethodError) asciidoctor: FAILED: /Users/timw/projects/indexity/empi/indexing/backend/dev/doc/struct_test.adoc: Failed to load AsciiDoc document - undefined method `gsub' for #<Asciidoctor::Reader:0x4c216325>
> 	at RUBY.load(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/load.rb:104)
> 	at RUBY.convert(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/convert.rb:78)
> Caused by: org.jruby.exceptions.NoMethodError: (NoMethodError) undefined method `gsub' for #<Asciidoctor::Reader:0x4c216325>
> 	at RUBY.sub_attributes(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/substitutors.rb:214)
> 	at RUBY.apply_target_subs(uri:classloader:/gems/asciidoctor-diagram-2.2.8/lib/asciidoctor-diagram/diagram_processor.rb:384)
> 	at RUBY.create_source(uri:classloader:/gems/asciidoctor-diagram-2.2.8/lib/asciidoctor-diagram/diagram_processor.rb:394)
> 	at RUBY.process(uri:classloader:/gems/asciidoctor-diagram-2.2.8/lib/asciidoctor-diagram/diagram_processor.rb:71)
> 	at RUBY.process(<script>:37)
> 	at RUBY.process(uri:classloader:/gems/asciidoctor-diagram-2.2.8/lib/asciidoctor-diagram/structurizr/extension.rb:25)
> 	at org.jruby.RubyMethod.call(org/jruby/RubyMethod.java:132)
> 	at RUBY.build_block(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/parser.rb:1053)
> 	at RUBY.next_block(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/parser.rb:904)
> 	at RUBY.next_section(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/parser.rb:397)
> 	at RUBY.parse(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/parser.rb:97)
> 	at RUBY.parse(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/document.rb:538)
> 	at RUBY.load(uri:classloader:/gems/asciidoctor-2.0.18/lib/asciidoctor/load.rb:84)
> 	... 1 more

## Steps to reproduce

Minimal reproducer:

```
= Structurizr Test

[structurizr]
----
workspace {
}
----

```
## Environment

Plugin Version: 0.38.16

IntelliJ Details: IntelliJ IDEA 2023.1.2 (Community Edition)
Build #IC-231.9011.34, built on May 16, 2023
Runtime version: 17.0.6+10-b829.9 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Registry:
    scala.erase.compiler.process.jdk.once=false

Non-Bundled Plugins:
    com.intellij.properties.bundle.editor (231.8109.91)
    com.github.camork.fileExpander (2.1)
    org.intellij.scala (2023.1.18)
    org.asciidoctor.intellij.asciidoc (0.38.16)
    io.kanro.idea.plugin.protobuf (1.7.12)
    org.sonarlint.idea (8.2.0.68615)
    MavenRunHelper (4.23.222.2964.0)

Kotlin: 231-1.8.21-IJ9011.34

**Comment by timw** [comment]
This also fails from the `asciidoctor` CLI, so I'm assuming it's a bug in [asciidoctor-diagram](https://github.com/asciidoctor/asciidoctor-diagram).

Raised issue to fix the root cause in https://github.com/asciidoctor/asciidoctor-diagram/issues/415

**Comment by ahus1** [comment]
Thank you for raising this in the upstream project. I've subscribed to the ticket and will watch it as well.

**Comment by timw** [comment]
@ahus1 - this is fixed upstream now.

**Comment by ahus1** [comment]
Happy to hear that. I'm now waiting for `asciidoctorj-diagram` to be released so I can update the dependency in the plugin.

**Comment by ahus1** [comment]
I upgraded to the latest version of asciidoctorj-diagram, and now I see the following error message: 

```
Failed to generate image: Could not load Structurizr. Specify the location of the Structurizr JAR(s) using the 'DIAGRAM_STRUCTURIZRCLI_HOME' or DIAGRAM_STRUCTURIZR_CLASSPATH' environment variable.
```

Could you point me to the location where to download that JAR?

**Comment by ahus1** [comment]
There's now pre-release 0.38.19 which includes asciidoctor-diagram 2.2.9 which gives me the error message I "Failed to generate image: Could not load Structurizr". Would you know what to do next with `DIAGRAM_STRUCTURIZRCLI_HOME` - I didn't find details on the [Asciidoctor Diagram docs](https://docs.asciidoctor.org/diagram-extension/latest/).

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment]
Hm, I found that the JAR file is packages with AsciidoctorJ Diagram, still it is not picked up. Do you know if this works with AsciidoctorJ Diagram outside of the plugin, standalone?

**Comment by timw** [comment]
I saw that message as well. 
I installed `structurizr-cli` using Homebrew, and then did:

```
export DIAGRAM_STRUCTURIZRCLI_HOME=/opt/homebrew/Cellar/structurizr-cli/1.30.0/libexec
asciidoctor -r asciidoctor-diagram struct_test.adoc
```

With the 0.38.19 plugin installed from the EAP repository, I can run IntelliJ from the command line using the shell script launcher (i.e. with the `DIAGRAM_STRUCTURIZRCLI_HOME` variable in the environment) and the diagram renders correctly in the IntelliJ preview pane.

<img width="500" alt="image" src="https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/670828/1e08bb46-0c3d-49c5-8bcf-063f5c697e18">

It appears that the asciidoctor code _requires_ the use of environment variables for configuration in this module:
- [uses env variables to find Jars](https://github.com/asciidoctor/asciidoctor-diagram/blob/0a52fe31d90dfe9b6efac63ce079b273eb809e57/lib/asciidoctor-diagram/structurizr/converter.rb#L14) 
- [requires Jars from env be specified]([asciidoctor plugin code](https://github.com/asciidoctor/asciidoctor-diagram/blob/0a52fe31d90dfe9b6efac63ce079b273eb809e57/lib/asciidoctor-diagram/structurizr/converter.rb#L14) )

It looks like it's forking a Java invocation, so knowing where the jars are seems reasonable. I'm not sure what the `structurizr-2.0.1.jar` in the source tree is, but it appears to be an asciidoctor-diagram plugin, and not the Structurizr implementation (only a single class + some service loader info in it).

By comparison, it looks like [plantuml](https://github.com/asciidoctor/asciidoctor-diagram/blob/0a52fe31d90dfe9b6efac63ce079b273eb809e57/lib/asciidoctor-diagram/plantuml/converter.rb#L13) and [ditaa](https://github.com/asciidoctor/asciidoctor-diagram/blob/0a52fe31d90dfe9b6efac63ce079b273eb809e57/lib/asciidoctor-diagram/ditaa/converter.rb#L28) (being the other asciidoctor-diagram plugins that use Java) special case this handling, so I suspect something similar is required for this to be friendly to use.

I'd guess we'd need to discuss with the asciidoctor-diagram maintainers the right approach here - the Structurizr distribution is quite extensive (40+ jars), so including that in asciidoctor-diagram might be too much. Perhaps there's another attribute based mechanism that they could support to point to the Structurizr distribution (as we do for pointing to Grapviz now), which the IntelliJ plugin could wire in, and people could externally install Structurizr as I did.

**Comment by timw** [comment]
@ahus1 - I mentioned this in another issue that  asciidoctor-diagram-java had with Structurizr, and the maintainer there mentioned Java system properties as an alternative, which I think could work well enough to make it serviceable.

https://github.com/asciidoctor/asciidoctor-diagram-java/issues/13

**Comment by ahus1** [comment]
The discussion seems to continue in the the upstream project, therefore I'm closing this for now. 

As described above, use the environment variables stated in the error message to point to a local installation of Structurizr. On Windows or Linux, those can be configured in the Operating System's user profile. I know this is a bit different for MacOS. Although I don't use MacOS, I recall people describing that launching the app directly doesn't pick up those environment variables, only launching it from the command line. 

As the IDE and its Java process is already running, the AsciiDoc plugin can't set those environment variables.
