### ISSUE TITLE
Add hard line breaks at configured column

### ISSUE THREAD

**Issue by matthewadams** [asciidoctor/asciidoctor-intellij-plugin#137]
Add a togglable setting for `Insert line break at column [ 80 ]` (where `[ 80 ]` is a text box).  In the editor, display a margin at the configured column and automatically reformat text while typing to ensure lines are no longer than the configured line length, and, optionally, so that artificially truncated lines are untruncated and reformatted.

AsciiDoc Plugin Version: 0.14.3

IDE Name and Version: WebStorm 2016.2.2
Build #WS-162.1628.41, built on August 16, 2016
Licensed to SciSpike / Matthew Adams
Subscription is active until March 15, 2017
For educational use only.
JRE: 1.8.0_76-release-b216 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by ahus1** [comment]
Hello Matthew,

thanks for sharing. Do you know another open source IntelliJ plugin that does this so I can have a look how this might work?

We're doing something different in my current project: we use one sentence per line. This leads to long lines, but creates very nice-looking diffs. If we would reformat the lines to break at 80 characters, this would leads to  very strange looking diffs as an added word could re-wrap a whole paragraph. 

I hear that one line per sentence is not uncommon in the asciidoc community. 

This works very well with IntelliJ's settings of "Use soft wraps in editor" and "Use original line's indent for wrapped parts".

Please give it a try and let me know what you think. 

Regrads,
Alexander

**Comment by mojavelinux** [comment]
While I'm not against adding this feature, understand that I strongly recommend against hard wrapping at a fixed column width. It allows minor changes to cause disproportionally-sized diffs and it takes the focus off the writing. I'm a strong proponent of the sentence-per-line style. It not only reinforces good writing habits, it also makes writers more efficient.

Of course, no wrapping at all is bad because it causes horizontal scrolling that makes the source hard to scan. That's why I use soft wrapping with line numbers enabled. The line numbers give me a clear indication where a line begins.

**Comment by matthewadams** [comment]
I created this issue while reviewing existing asciidoc source, which I found tough to navigate due to the horizontal scrolling.  However, since that time, I've authored a substantial amount of asciidoc and agree that inserting hard line breaks make for more difficult change tracking.

You might just leave this issue open and see if anyone else wants the feature.  I prefer your suggestion of having the IDE insert soft breaks, which makes reading better, while using one sentence per line, which makes diffs easier to read.

**Comment by ahus1** [comment]
Hello Matthew, 

thanks for sharing. I think a at the minimum a "best practices" section about soft line wraps in the docs of the plugin could help. Maybe it is possible to have soft line wraps as default within the plugin independent of the settings in the general config - but I don't know if this is possible.

Best regards,
Alexander

**Comment by ahus1** [comment]
As part of #221 there will be a toolbar icon to toggle soft wraps. This is a gradual improvement for this issue.

**Comment by ahus1** [comment]
In the most recent IntelliJ versions you can enable soft-wrap per file type (see sceen shot). Therefore everyone using AsciiDoc can enable softwrap for all Asciidoc files as default - or use the per-editor-toggle in the toolbar. 

I hope this solution works for most of you; I close this ticket. Please see a screenshot where to find the setting (and to setup the filter) below.

![softwap](https://user-images.githubusercontent.com/3957921/57518927-217daa00-7312-11e9-8917-9bff592220f8.png)
