### ISSUE TITLE
Problem with page breaks `<<<`

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#1388]
`<<` defines a reference to another anchor. The plugin support this by going into autocomplete mode with a drop down showing all known anchors. That's great!

`<<<` defines a page break for page oriented media. The plugin things it is a reference and displays a drop down, but I need a new-line. The dropdown is in my way.

Is it possible to avoid the dropdown for the triple `<`?

**Comment by ahus1** [comment]
Thank you for spotting this. This will be fixed in the next release. I'll update this issue once there is a pre-release.

**Comment by ahus1** [comment]
The change is included in pre-release 0.39.1. Please let me know if this works for you.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by rdmueller** [comment]
works as expected. Thanx!
