### ISSUE TITLE
When in project explorer, select an .adoc, then press 'esc', the cursor focus does not move to the editor.

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#139]
I then have to click in the editor with the mouse.

This problem has appeared with the new preview stuff (that otherwise it's pretty nifty, thank you!)

AsciiDoc Plugin 

Version: 0.15.3

IDE Name and Version: 

![image](https://cloud.githubusercontent.com/assets/1031625/18577319/a7ae2e50-7be0-11e6-87af-84d252cd8620.png)

**Comment by ahus1** [comment]
Hello Dan, I tried to reproduce it on IntelliJ 2016.2.4 and Windows. For me this works (both ESC in project view and double-click on file will focus on the file). 

What OS are you using (Mac/Windows/Linux)? Did you consider updating to 2016.2.4?

**Comment by ahus1** [comment]
There has been no feedback for two weeks. Please re-open once you have more information. Thanks!

**Comment by mojavelinux** [comment]
@danhaywood mentioned this problem to me when we were together at JAX London. That suggests to me it's still a concern for him. I'll reach out to him to see if we can move this forward.

**Comment by danhaywood** [comment]
Hi @ahus1 (and @mojavelinux),
happy for this to be closed... I just checked and it does work indeed work as expected on 2016.2.4.
Sorry for the noise.
Cheers
Dan

**Comment by ahus1** [comment]
Hi @danhaywood - good to hear that it's working for you now. Please continue to open issues on Github for new ideas or bug you might encounter with this plugin.
