### ISSUE TITLE
Make it an option to wrap text instead of run off the end of the page

### ISSUE THREAD

**Issue by gregturn** [asciidoctor/asciidoctor-intellij-plugin#140]
IDE Name and Version: IntelliJ IDEA 15.0.2

I sometimes prefer letting an entire paragraph of asciidoctor text stay on one line. That way, I don't waste any time reformatting stuff based on what editor I'm viewing it with. As a side effect, text will run off the page. 

<img width="1024" alt="screen shot 2016-09-20 at 5 07 41 pm" src="https://cloud.githubusercontent.com/assets/311040/18690653/c998f8b6-7f54-11e6-91bb-02758f3a4fae.png">

Comparably, Sublime Text 3 wraps text.

<img width="1136" alt="screen shot 2016-09-20 at 5 07 48 pm" src="https://cloud.githubusercontent.com/assets/311040/18690654/ca76a1b6-7f54-11e6-80d3-7eff995bfed9.png">

If this was a setting inside IntelliJ where I toggle word wrapping on, that would be great!

**Comment by bodiam** [comment]
Hi Greg,

Wouldn't "soft wrap" be the feature you're looking for? It's standard in Intellij.

Cheers,
Erik

**Comment by gregturn** [comment]
Okay, thanks. That works perfectly.
