### ISSUE TITLE
pandoc on apple silicon

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#1413]
## Observed vs. expected behavior

On my windows machine, "paste formatted" works perfect. On my M2pro Mac, it does nothing at all. When I take a look at the notifications window, I see

"AsciiDoc Download - Download PanDoc sucessful"

written in an endless loop

## Steps to reproduce

Copy an HTML table to the copy buffer and use the "paste formatted" button on a Mac with Apple Silicon

## Environment

Plugin Version: 0.38.20

IntelliJ Details: 

IntelliJ IDEA 2023.1.5 (Ultimate Edition)
Build #IU-231.9392.1, built on July 25, 2023

Runtime version: 17.0.7+10-b829.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 10
Metal Rendering is ON
Non-Bundled Plugins:
    de.docs_as_co.intellij.plugin.diagramsnet (0.2.4)
    com.intellij.plugin.adernov.powershell (2.0.10)
    PlantUML integration (6.3.0-IJ2022.2)
    org.asciidoctor.intellij.asciidoc (0.38.20)
    Pythonid (231.9392.1)
    org.intellij.grails (231.8770.17)

Kotlin: 231-1.8.21-IJ9392.1

**Comment by rdmueller** [comment]
found the problem. the x86 version is downloaded.

os.arch ist aarch64 !
https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/a46904104452e86e9224079729e1315e46230990/src/main/java/org/asciidoc/intellij/download/AsciiDocDownloaderUtil.java#L183

arm64 and aarch64 seem to be the same and should be handled this way

**Comment by ahus1** [comment]
Pre-release 0.39.2 is now available and ready for a test run. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment]
@rdmueller - did you have a chance to test that this latest pre-release works on your Mac?

**Comment by rdmueller** [comment]
Yes, and I didn't succees. I still need some time to investigate on this. The right version gets downloaded but the behaviour is still the same. If I try to .anually use the downloaded pandoc, I don't succeed. Maybe there are some restrictions on the folder?

**Comment by ahus1** [comment]
Thank s for testing this. I'm marking this as "help wanted", as I don't have a Mac at hand to develop and test this. If anyone wants to pair on a coding session with me, I'd be happy to join.

**Comment by ahus1** [comment]
I @rdmueller - @mlasevich prepared fixes for Intel macs in #1429 and I would hope they also work for M* chips. 

There is now pre-release 0.39.8 available which includes this change. Please give it a try, and let me know if this works for you as well. Thanks!

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by rdmueller** [comment]
thanx for the update. Now I get a new error message:

Cannot run program "/Users/ralfmueller/Library/Caches/JetBrains/IntelliJIdea2023.1/download-cache/asciidoctor-intellij-plugin/pandoc-3.1.2-arm64/bin/pandoc" (in directory "/Users/ralfmueller/projects/micrositemaster-ng"): error=13, Permission denied

already investigating

**Comment by rdmueller** [comment]
success! I only got the error message from an older download. I removed the pandoc download folder in order to force a re-download and now it works. Thanx!

fixed in 0.39.8
