### ISSUE TITLE
AsciiDoctor shows warnings in item lists if the entries do not start with upper case

### ISSUE THREAD

**Issue by ascheman** [asciidoctor/asciidoctor-intellij-plugin#1419]
## Description

If I create a list like the following, I see warnings from AsciiDoctor. How could I prevent these?

```asciidoc
The following list usually creates some warnings in IntelliJ.

`feature/XXX`:: Feature Branches
`bugfix/YYY`:: Bugfix Branches
```

<img width="1045" alt="image" src="https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/456000/fdd97890-b5c7-41c2-b06b-52375d0951a1">

**Comment by ahus1** [comment]
Thank you for reporting this, @ascheman - there's now a pre-release 0.39.3 that includes an updated parser that separates the parts before and after the colons into separate AST elements that are now checked separately in the grammar check. Also the highlighting for monospaced text in the definition term is improved (the backticks are now marked to be part of the monospace contents, and the element is highlighted to be monospaced). 

Please give this pre-release a try and see if it works for you, and if additional rework is necessary to fix this issue or any regressions you might find.

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/3957921/aaa89fdf-475f-4504-85d5-60f6b9534961)

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ascheman** [comment]
Thanks, @ahus1 - due to vacation I was not able to test this up to now.
I have loaded the latest regular version (0.39.4) of the plugin and the problem seems to have vanished.

**Comment by ahus1** [comment]
Thank you for testing this version. I've promoted 0.39.4 to a regular release to day, so it will roll out to all users via the JetBrains marketplace.
