### ISSUE TITLE
Asciidoc plugin hangs when attempting to paste from Chrome or Safari

### ISSUE THREAD

**Issue by RayOffiah** [asciidoctor/asciidoctor-intellij-plugin#1420]
## Observed vs. expected behavior

Copying text from Chrome or Safari and attempting to paste into IntelliJ will cause the IDE to hang with no cursor showing.
Closing the IDE will show a dialog indicating that there is a process running somewhere, and ask if it should close the process before terminating. However, the IDE will shut down before you can press any other button.

It is possible that the plugin isn't the underlying cause, but I suspect it is; the IDE can copy/paste normally if the plugin is disabled.

## Steps to reproduce

1.  Copy text using Chrome or Safari
2. Switch to the IDE.
3. Attempt to paste the text.

## Environment

Chrome version: 116.0.5845.110 
Safari version: Version 16.6 (18615.3.12.11.2)
Plugin Version: 0.39.2

IntelliJ Details: 

IntelliJ IDEA 2023.2.1 (Ultimate Edition)
Build #IU-232.9559.62, built on August 23, 2023
Licensed to Ray Offiah
You have a perpetual fallback license for this version.
Subscription is active until September 4, 2025.
Runtime version: 17.0.8+7-b1000.8 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.5.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.jetbrains.plugins.ini4idea (232.9559.64)
    com.intellij.plugins.watcher (232.8660.88)
    com.mroche.JsonHelper (1.2.0)
    one.util.ideaplugin.screenshoter (1.7.1)
    ru.meanmail.plugin.requirements (2022.4.1)
    com.intellij.ideolog (222.1.0.0)
    Batch Scripts Support (1.0.13)
    String Manipulation (9.10.0)
    org.rust.lang (0.4.200.5421-232)
    Shifter (1.9.6)
    name.kropp.intellij.makefile (232.8660.88)
    com.intellij.grazie.pro (0.3.244)
    PlantUML integration (7.0.0-IJ2023.2)
    org.asciidoctor.intellij.asciidoc (0.39.2)
    com.intellij.ml.llm (232.9613)
    com.dmarcotte.handlebars (232.8660.88)
    com.intellj.plugin.SpringBootBannerPlugin (0.2.9)
    com.intellij.plugins.html.instantEditing (232.8660.142)

Kotlin: 232-1.9.0-IJ9559.62

**Comment by ahus1** [comment]
Hi @RayOffiah - sorry to hear that this doesn't work for you. 

I have some questions: 
* I see that you're using a Mac. Is it a new M1/M2 Mac? 
* Does this affect all pasting in IntelliJ, or only pasting into AsciiDoc documents?
* When pasting, do you use the "Past Formatted Text" icon in the AsciiDoc ![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/3957921/4ee7954b-fd87-48a7-b566-655cefa7d6b8) or did you check "Enable conversion of clipboard text via Pandoc" in the plugin's settings? (see below)

I've just published a preview version 0.39.3 of the plugin that might fix the Pandoc issue on M1/M2, see #1413 - maybe that version will fix it for you if you're using M1/M2. 

Thanks!

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/3957921/68a0ffdc-ba42-41ef-83a6-7c760ac51a96)

**Comment by RayOffiah** [comment]
I think that last message got messed up. Turning off the Pandoc option seems to have fixed the problem. Pasting now works correctly.I think it's fine to close this.
