### ISSUE TITLE
Support for asciidoctor-tabs rendering

### ISSUE THREAD

**Issue by mikeholler** [asciidoctor/asciidoctor-intellij-plugin#1425]
## Why the new feature should be added

Asciidoctor tabs is an official asciidoctor plugin and it would be nice to have some rendering in IntelliJ. First-party plugins like `asciidoctor-diagram` are already supported in the plugin and this would be a nice next step.

Right now, when I copy [tabs.adoc](https://github.com/asciidoctor/asciidoctor-tabs#syntax) from the syntax section of `asciidoctor-tabs`, I get the following rendering:

![Screenshot from 2023-08-30 11-41-13](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/1164112/d9e4761f-faca-46f2-80e7-5aa587f3575b)

## How the new feature should work

I would like to see rendering with a default CSS stylesheet, looking something like this crude mockup shamelessly stolen from [here](https://docs.spring.io/spring-restdocs/docs/1.1.0.RELEASE/reference/html5/#documenting-your-api):

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/1164112/8e2f73d8-c889-40bc-ae56-4de5308fa73a)
![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/1164112/d282e869-e68d-444b-aee4-12be9fb68331)

**Comment by ahus1** [comment]
Thank you for suggesting this. The next version of this plugin will support it when using the Browser preview and the JCEF preview  (the default preview). JavaFX and Swing will not support it.

I'll update this issue once a preview release is available.

**Comment by ahus1** [comment]
There is now version 0.40.3 of the plugin available. I tried your example and it worked for me: The preview shows the tabs, and it also keeps showing the tab when editing the content. 

Please give it a try if it works as expected for you. If it doesn't, please provide an example and a screen shot / screen recording.

See below for an example recording.

![tabs-preview](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/3957921/4f571980-76bd-43b9-8ccf-a15402a178e4)

**Comment by mikeholler** [comment]
It's working! Thank you @ahus1 :heart:

**Comment by ahus1** [comment]
Happy to help and thank you for the suggestion.

**Comment by sroach** [comment]
One observation I have is the preview works great but when I use the html button to create a document with this plugin the tabs are not present in the document. Is that expected? Am I missing something?

**Comment by mikeholler** [comment]
@sroach asciidoctor-tabs is a plugin and not enabled out of the box, similar to asciidoctor-diagrams.

**Comment by sroach** [comment]
> @sroach asciidoctor-tabs is a plugin and not enabled out of the box, similar to asciidoctor-diagrams.

Is there a way to get this plugin in a java environment I am using asciidoctorj at the moment.

**Comment by ahus1** [comment]
I'll give it a try and see that the HTML button renders tabs as well.

**Comment by ahus1** [comment]
I needed rearrange some files and folders so that the plugins picks up the necessary JavaScript and CSS from the right places.

There is now pre-release 0.40.5 which adds the following: 
* Asciidoctor Tabs support when pressing the HTML button (it is still not supported when creating a PDF)
* Dark CSS theme for Asciidoctor Tabs (only JCEF and Browser preview, not HTML conversion)

Please give it a try and let me know if it works for you. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by sroach** [comment]
Sorry for the delay, I can confirm the changes you've made works.

**Comment by ahus1** [comment]
Thank you for checking this - closing this issue!
