### ISSUE TITLE
Upgrade embedded Mermaid JS version to 10.3.x

### ISSUE THREAD

**Issue by mcbeelen** [asciidoctor/asciidoctor-intellij-plugin#1430]
## Why the new feature should be added

The [Mermaid Plugin](https://plugins.jetbrains.com/plugin/20146-mermaid) for IntelliJ has updated the underlying Mermaid.js version to 10.3.1
While editing .mmd-files I see the result for some diagrams.

This Asciidoctor-Intellij-Plugin still uses version 9.2.2, which sometimes causes:

```
Syntax error in graph
mermaid version 9.2.2
```

## How the new feature should work

The plugin should be able to render 
```
[mermaid]
----
include::partial$some-diagram-with-10.y.z-syntax.mmd[]
----
```

**Comment by mcbeelen** [comment]
I'm trying to create a MR to solve this, but have some questions about how to build the included `mermaid.esm.min.mjs`-file.

The content of the file currently in this project is rather different from the file on [unpkg.com](https://unpkg.com/browse/mermaid@10.4.0/dist/mermaid.esm.min.mjs)

Should we include everything from the [Mermaid Dist](https://unpkg.com/browse/mermaid@10.4.0/dist/)


@ahus1 

When you added built-in Mermaid support in [4bfcf96a77952](https://github.com/asciidoctor/asciidoctor-intellij-plugin/commit/4bfcf96a779521158a6c8f1ed6bb62beb6b7ada7), you pushed a file `mermaid.esm.min.mjs`.
Where did you manage to download / generate that file?

**Comment by ahus1** [comment]
Hi @mcbeelen - Thank you for letting me know that there is an update.

That old version of Mermaid 9 has a monolithic file `mermaid.esm.min.mjs` which included everything. Looking at the current release, it seems that this has been split into smaller modules files. The `dist` folder contains multiple versions like `mermaid.esm.min.mjs` and `mermaid.esm.mjs` which reference different versions of each module. 

The two files that are still monolithic are `mermaid.min.js` and `mermaid.js`, so it is simpler to pick `mermaid.min.js` instead. 

I just pushed a commit that includes the update. Please let me know you would like to see a pre-release to try it, or if you want to build it yourself. 

If you could post a small sample diagram here, this would be helpful for me so I can test before/after the upgrade. I tested a Sankey diagram which is only available in 10.3+, and it seems to work.

**Comment by ahus1** [comment]
There is now pre-release 0.39.5 which includes my fixes. Please give it a try when you have the time. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by mcbeelen** [comment]
Hi @ahus1 ,

Thank you for effort.
I installed v0.39.5 from the EAP-repository and the diagram do get rendered now.

To verify that the issue is fixed I used the following Gist: 
[AsciiDoc with mermaid block containing v10 syntax to demonstrate #1430 is fixed](https://gist.github.com/mcbeelen/a8b0aebaa9913e5025e686f371669a62)

**Comment by mcbeelen** [comment]
![proof-of-fix-for-1430](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/1905153/173afd98-8440-4554-9104-f5069aca93e7)
