### ISSUE TITLE
Disable included files redirection

### ISSUE THREAD

**Issue by alexps99** [asciidoctor/asciidoctor-intellij-plugin#1436]
## Included files redirection + Collapsibles = Catastrophe

When you click on an included file in the preview, the IDE automatically switches to that file. I'm accustomed to working with AsciiDoc, using collapsible blocks for easy reading. However, I face a challenge: how can I expand a block without switching files when I want them to remain collapsed by default?

I would like to request a feature that allows me to disable all included file redirectioning or specify one include redirectioning, and being able to choose the lvl of redirectioning disabling. So i can choose if any file dependant of that include will redirection or not, for example having an adoc inside an adoc and inside a image, so if i click the image it redirects but dont redirect to the 2nd adoc.

**Comment by ahus1** [comment]
Hi @alexps99 - thanks for reaching out. I see your point for includes and nesting. 

I think I have an idea on how to tune the mechanism that it allows for expanding blocks and and not opening the include as long as you click on the expand symbol. 

Could you please provide a short AsciiDoc sample which I can use for testing?

**Comment by ahus1** [comment]
I came up with an example myself, and hope it matches your scenario. 

The next version of the plugin will behave as follows: If the user clicks on the title/summary, as well as on the indicator before it, it triggers the expand/collapse. The include will not open. Only if the user clicks on the details below (the actual contents), the include opens.

Please let me know if this would work for you, or where your scenario is different.

This will be part of the next release of the plugin. 

![expand-collapse](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/3957921/f980b9bc-046b-48d6-abac-2413d1cf479d)

**Comment by ahus1** [comment]
There is now version 0.40.3 of the plugin available which includes the change. Please let me it know if it works for you. Thanks!

**Comment by alexps99** [comment]
It works perfectly, thanks.

11/10 if i would rate.

**Comment by ahus1** [comment]
Good to hear it now works for you. Happy writing!
