### ISSUE TITLE
Synchronization between code and preview not fully working

### ISSUE THREAD

**Issue by pysaumont** [asciidoctor/asciidoctor-intellij-plugin#144]
AsciiDoc Plugin Version: 0.16.2

IDE Name and Version: IntelliJ IDEA (Community Edition) 2016.3 EAP
Build #IC-163.6512.17, built on October 19, 2016
JRE: 1.8.0_112-release-b403 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

The HTML frame does not scroll when the Asciidoc frame is scrolled. One has to click in the code to have the preview scrolling. May be it is not a bug, but a feature, but in such case, it's not a good one! (At least when comparing to other Asciidoc editing solutions.)

Also, after scrolling the code, if one scrolls the preview forward and then clicks back in the code, the preview is scrolled back to show the point of the click. On contrary, if the preview is scrolled backward, clicking in the code often does nothing. One has to scroll the preview by several lines and click again to make synchronization work.

Another problem is that scrolling the preview will not make the code to scroll. A very useful feature would be to have the two frames really synchronized, rather that only in one direction.

**Comment by ahus1** [comment]
Hello @pysaumont, thanks for sharing your experiences.

Currently the following two interactions are supported:
* When you move your cursor in the left window up and down (using cursor up/down or page up/down), the focus of the preview will scroll as needed to keep the cursor's position in view. 
* When you click on the preview with your mouse, the cursor on the left will be placed near the location you clicked. 

You also described that nothing happened when you clicked. That shouldn't be the case. I'll look into this. 

The interaction might evolve over time and as time permits - this is spare time project. Pull requests are welcome.

**Comment by ahus1** [comment]
Hello @pysaumont,

you described the following behavior:

> Also, after scrolling the code, if one scrolls the preview forward and then clicks back in the code, the preview is scrolled back to show the point of the click. On contrary, if the preview is scrolled backward, clicking in the code often does nothing. One has to scroll the preview by several lines and click again to make synchronization work.

This is fixed in release 0.17.1 that is now available as a preview in [Github releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases). 

The 0.17.x branch includes a refurbished parser for syntax highlighting in the editor (#143). Due to this the 0.17.x is only available as a preview until it proves to be stable in my day-to-day work.
