### ISSUE TITLE
Error during PlantUML diagram generation since asciidoctor-intellij-plugin v0.39.8

### ISSUE THREAD

**Issue by nagromc** [asciidoctor/asciidoctor-intellij-plugin#1445]
Not sure if I should create a ticket here, or in asciidoctor/asciidoctorj-diagram.

## Observed vs. expected behavior

When using asciidoctor-intellij-plugin v0.39.8 and up, generated image shows the following error:

```
An error has occured : java.lang.NullPointerException: Cannot invoke "net.sourceforge.plantuml.dot.GraphvizVersion.useShieldForQuantifier()" because "graphvizVersion" is null
```

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/752443/950d98ad-fcee-438a-852b-c99605a83e2f)

With v0.38.7, no problem.

## Steps to reproduce

Asciidoc example:

```asciidoc
# test

[plantuml]
....
interface test
....
```

## Environment

Plugin Version: 0.39.8 to 0.40.3

IntelliJ Details:

IntelliJ IDEA 2023.2.2 (Ultimate Edition)
Build #IU-232.9921.47, built on September 12, 2023
You have a perpetual fallback license for this version.
Subscription is active until September 1, 2025.
Runtime version: 17.0.8+7-b1000.22 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.github.lppedd.idea-conventional-commit (0.22.0)
    Batch Scripts Support (1.0.13)
    com.github.b3er.idea.plugins.arc.browser (0.32)
    IdeaVIM (2.5.1)
    org.nik.presentation-assistant (1.0.10)
    com.dekonoplyov.KeymapNationalizer (0.2.8)
    org.jetbrains.plugins.vagrant (232.8660.88)
    com.wakatime.intellij.plugin (14.2.2)
    Error-prone plugin (232.8660.142)
    com.intellij.datagen (232.8660.88)
    com.jetbrains.jax.ws (232.8660.142)
    String Manipulation (9.11.3)
    PIT mutation testing Idea plugin (1.4.8)
    com.intellij.plugin.adernov.powershell (2.2.0)
    org.apache.camel (1.0.3)
    org.exbin.deltahex.intellij (0.2.8.1)
    org.asciidoctor.intellij.asciidoc (0.39.8)
    org.sonarlint.idea (9.0.0.75308)
    mobi.hsz.idea.gitignore (4.5.1)
    com.github.codespaces.jetbrains.gateway (0.5.0.1214)
    com.intellij.java.rareRefactorings (232.8660.142)

Kotlin: 232-1.9.0-IJ9921.47

**Comment by ahus1** [comment]
The latest version of PlantUML seems to have some regressions, see #1446. 

There is now a pre-release 0.40.5 which downgrades PlantUML. In a local test the example you provided worked for me, although I wasn't able to reproduce the original problem you describe. Please give 0.40.5 a try and let me know if it works for you. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by nagromc** [comment]
Pre-releases v0.40.5 and v0.40.6 have fixed the issue.

Thanks @ahus1!
