### ISSUE TITLE
Illegible preview in Darcula theme

### ISSUE THREAD

**Issue by anidotnet** [asciidoctor/asciidoctor-intellij-plugin#145]
When I switch on the JavaFX based preview of the plugin and when default Darcula theme is on, the preview is coming very illegible, specially the code blocks. The default source highlighter I use is - coderay. In recent update the background color of the preview changed from white to dark under Darcula theme which made things worse. 

For IntelliJ or GTK+ theme (I am currently under Ubuntu 16.04), the preview is fine, but for Darcula it is painful to the eye.

To reproduce it follow these steps

- Enable Darcula theme
- Enable JavaFX based preview
- Write a codeblock in an adoc file - either java or xml should be ok
- Open the preview and voila!!!

![screenshot from 2016-10-23 21-15-21](https://cloud.githubusercontent.com/assets/696662/19627619/5f8c767c-9968-11e6-8e7a-d621fc4731af.png)

AsciiDoc Plugin Version: _0.16.2_

IDE Name and Version: _IntelliJ IDEA Ultimate 2016.2.5_

**Comment by mojavelinux** [comment]
It's going to be necessary to set the code highlighting theme. These styles get added to the content stylesheet. It's possible for these styles to be overridden. See https://github.com/asciidoctor/asciidoctor/blob/master/data/stylesheets/coderay-asciidoctor.css.

Unfortunately, CodeRay, the highlighter in use, only has a single style. This is one of the reasons we're working on integrating Rouge, since it offers themes.

**Comment by anidotnet** [comment]
But 2 release back also the plugin was good. I mean the background color was white irrespective of intellij theme, making the preview looks readable. Suddenly the background color became dependant on intellij theme. For darcula it became black and for other it remains white. 

Is there any reason to change this behavior?

**Comment by mojavelinux** [comment]
I'm sure it was an unintended side effect of the Improvements to the
Darkula theme. My point is that the effect on the code highlighting needs
to be considered, but it's tricky to get right. Ideally, the snippets
should also be dark, but that means implementing a full code highlighting
theme.

**Comment by anidotnet** [comment]
So what would be the way out now?

**Comment by ahus1** [comment]
With the recent update the JavaFX preview implemented something that the Swing preview had for a long time: darcula support. 

I have to admit that the highlighting of code is not good enough. But the colors of text and tables match quite closely the Swing Darcula theme.

A temporary fix could be to disable code highlighting for the darcula theme until it is ready.

What do you think?

**Comment by abelsromero** [comment]
> But 2 release back also the plugin was good. I mean the background color was white irrespective of intellij theme, making the preview looks readable. Suddenly the background color became dependant on intellij theme. For darcula it became black and for other it remains white.
> 
> Is there any reason to change this behavior?

I just updated the plugin and found this issue. Independently of the specific code highlight issue I'd like to be able to use the original white style even when using Darcula. Can this be made into an option?
Mainly because is the same look I get when rendering the documents so I get a better idea of the final result.
Also, and this is a personal thing, it helps me switching from 'coding mindset' to 'documenting mindset'

**Comment by ahus1** [comment]
The release [0.16.3 (available as a preview from the GitHub releases)](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) adds a setting "Preview Theme" with three settings: Use same theme as IntelliJ, use darcula theme, use light (standard) asciidoc theme. "Same theme as IntelliJ" is the default.

If the preview is in darcula mode, it filters out any coderay colors. This has been done by post-processing and is hacky, and it needs to be revised in an upcoming version. But it should work for now.

**Comment by abelsromero** [comment]
> The release 0.16.3 (available as a preview from the GitHub releases) adds a setting "Preview Theme"

This worked perfectly for me. You can even switch themes with a document opened and it will refresh automatically.

You're the best @ahus1 :+1:

**Comment by mojavelinux** [comment]
> You're the best @ahus1 :+1:

I second that! :beers:
