### ISSUE TITLE
Is it possible to support extension written in Javascript?

### ISSUE THREAD

**Issue by RayOffiah** [asciidoctor/asciidoctor-intellij-plugin#1468]
## Description

Is this possible. It can be done in Ruby, but I wondered if Javascript support is possible.

Thanks.

**Comment by RayOffiah** [comment]
Yup, you can with Janet.

**Comment by ahus1** [comment]
Hi @RayOffiah - can you share a link to "Javet" so I can read about your solution? Or did you mean "Java"?

**Comment by RayOffiah** [comment]
Hi there 👋🏾

Sorry about the confusion; I misspelt "Javet" in the original message.

https://github.com/caoccao/Javet/

I wrote a Kotlin extension using Javet to call the Node JavaScript extension I wrote a few weeks earlier.

I'm still fiddling with it, (I need to work up the installation instructions) but I now have the Grammkit extension rendering diagrams live with the Asciidoctor plugin.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
