### ISSUE TITLE
Some things are not properly styled in Darcula theme

### ISSUE THREAD

**Issue by Vampire** [asciidoctor/asciidoctor-intellij-plugin#147]
``` asciidoc
* sidebar blocks (\****) have a white background

****
foo
****

* example blocks (====) have a white background

====
foo
====

* preamble has black text +
  With this as start of a document bar will be in black:

====
[source,asciidoc]
----
= foo

bar

== baz
====

* verse has black text

[verse]
--
foo
--

* admonition paragraphs have black text +
+++e. g. +++

TIP: foo

[NOTE]
====
foo
====

[WARNING]
--
foo
--

* horizontal definition lists have black text

[horizontal]
foo:: bar
baz:: bam
```

**Comment by ahus1** [comment]
Thank you for this list. It would be helpful for me if you could extend the asciidoc example.

BTW: Version 0.16.3 added a switch to select the preview theme independently of the IDE theme - in case you need a workaround until this has been updated.

**Comment by Vampire** [comment]
I already have the preview. Found it when I was going to report this issue. :-) Btw. it would be nice if this would be switchable from the editor like switching whether the preview should be shown at all. :-)

**Comment by Vampire** [comment]
I changed the issue text to an asciidoc document that also shows the faulty examples except for one. This list of course can be incomplete, it is just what I stumbled upon. :-)

**Comment by ahus1** [comment]
Thank you for the examples. I updated some css classes to handle them. It will be included in the next release.
