### ISSUE TITLE
Support AppCode

### ISSUE THREAD

**Issue by sdavids** [asciidoctor/asciidoctor-intellij-plugin#1470]
## Why the new feature should be added

It is supported in all the other JetBrains IDEs so far.

## How the new feature should work

One can install the IntelliJ AsciiDoc Plugin from the JetBrains Marketplace into [AppCode](https://www.jetbrains.com/appcode/).

---

Similar to #1456 but for AppCode.

**Comment by ahus1** [comment]
Hi - AppCode seems to be no longer maintained: 

> AppCode is no longer available as a commercial product as of December 14, 2022.

Let me know the version you use via "Help -> About", then use the "Copy and Close" button and paste the information below (assuming this works like in all other JetBrains IDEs). I can then look up a matching version.

**Comment by sdavids** [comment]
AppCode 2023.1.4
Build #OC-231.9225.18, built on July 13, 2023

**Comment by ahus1** [comment]
I don't have a mac, so I can't test this. Looking at 

https://plugins.jetbrains.com/plugin/7391-asciidoc/versions/stable/422593

This version would support `AppCode — 2022.2.1 — 2023.1.4`. I don't know why it doesn't show up in the marketplace. 

Please give it a try and download and install it manually. See the following link for the necessary steps: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/installation#download-install-from-disk

**Comment by ahus1** [comment]
There hasn't been an answer for three weeks, so I'm closing this issue. If you have any new, please share them as a comment, and I can re-open the issue.
