### ISSUE TITLE
Cyrillic fonts supporting in projects used asciidoctor-intellij-plugin in conjunction with Antora

### ISSUE THREAD

**Issue by vetalalien** [asciidoctor/asciidoctor-intellij-plugin#1473]
Hi, there!

Could anybody be kind to tell if there is a way to turn on cyrillic fonts supporting in used asciidoctor-intellij-plugin in conjunction with Antora?
I mean, for example, the issue that in the plugin preview area some meant to be bold text containing cyrillic (for example, 
\*{some_bold_text_with_cyrillic*) isn't rendered as bold.

**Comment by mojavelinux** [comment]
This is related to the following issue: https://gitlab.com/antora/antora-ui-default/-/merge_requests/177

**Comment by ahus1** [comment]
The next version of the plugin will update to the lastest version of the Antora default UI theme, so this should be solved. 

In the meantime, if you have already deployed an Antora site with the latest UI theme that includes Cyrillic fonts, you can point the plugin to those CSS. Unfortunately you can't point this at the CSS as is, as embedded CSS doesn't support relative font names. See https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/stylesheets#remote-stylesheet for the details. 

I'll update this issue once the next preview release of this plugin is available which would include this change.

**Comment by ahus1** [comment]
There is now pre-release 0.41.1 which includes this change.

This version will only work with the current 2023.3 EAP version of IntelliJ, as the latest development of the plugin is needed to move to the latest APIs. If you could make the effort to test it there, I could later port it back to an earlier plugin release to support older versions if needed.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by vetalalien** [comment]
I installed 0.41.6 for checking if cyrillic fonts work are supported in the plugin - it's great, they are, thank you much!
