### ISSUE TITLE
Adding a support for "csharp" language auto injection and highlight in the preview

### ISSUE THREAD

**Issue by vladyslav-androshchuk** [asciidoctor/asciidoctor-intellij-plugin#1474]
## Why the new feature should be added

We are working on the documentation with many C# code examples, and currently, there is no auto language inject for C# (csharp). Also `[source,csharp]` examples have no highlight in the preview window.

## How the new feature should work

Code blocks like the one below should benefit from automatic language injection and show highlight in the preview window:

```
[source,csharp]
----
// Example
----
```

**Comment by vladyslav-androshchuk** [comment]
> Thank you for suggesting that. The automatic language inject is supported as long as the user has a plugin installed for that specific language.
> 
> What IDE are you using, and is there a plugin which you use to write C# code?

We are using Rider for our development with the latest AsciiDoc plugin. We are not using any other plugins for C#. I can inject the language manually, but it's quite time-consuming if a lot of examples are present. Also, the `.adoc` files are part of the Antora project.

Just a little visual example:

<img width="2157" alt="image" src="https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/77970522/6f9cd4c5-e1c9-4fd0-8f04-715d52a3f57e">

<img width="309" alt="image" src="https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/77970522/55bfe79e-0c86-475d-bbe5-663b319930f5">

**Comment by ahus1** [comment]
I figured out the problem: Rider registers the syntax highlighting for C# as `C#`, where highlight.js expect it to be `csharp`. I added a translation to the plugin which will be available in the next release of the plugin. 

Thank you for raising this issue. I'll post a note in this issue once it is available as a preview.

**Comment by vladyslav-androshchuk** [comment]
> I figured out the problem: Rider registers the syntax highlighting for C# as `C#`, where highlight.js expect it to be `csharp`. I added a translation to the plugin which will be available in the next release of the plugin.
> 
> Thank you for raising this issue. I'll post a note in this issue once it is available as a preview.

Thanks a lot!

**Comment by ahus1** [comment]
There is now pre-release 0.41.1 which includes this change. It also contains two other fixes for Rider: It should no longer show that you're opening a file outside of the project, and also the Antora includes should work. Please give a try and comment hier with your results.

This version will only work with the current 2023.3 EAP version of Rider, as the latest development of the plugin is needed to move to the latest APIs. If you could make the effort to test it there, I could later port it back to an earlier plugin release to support older versions of Rider.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by vladyslav-androshchuk** [comment]
> There is now pre-release 0.41.1 which includes this change. It also contains two other fixes for Rider: It should no longer show that you're opening a file outside of the project, and also the Antora includes should work. Please give a try and comment hier with your results.
> 
> This version will only work with the current 2023.3 EAP version of Rider, as the latest development of the plugin is needed to move to the latest APIs. If you could make the effort to test it there, I could later port it back to an earlier plugin release to support older versions of Rider.
> 
> The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

I took a look at the new updated version:

1. `source` blocks are now correctly auto-injected in the Rider.
2. In the Preview window code blocks are gray without highlighting.
3. I have an "Antora Module doesn't resolve" error for the `xref` (I assume because our Antora folder is starting from capital "Docs" and not in the root of the repository).

<img width="1840" alt="Screenshot 2023-11-29 at 09 54 35" src="https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/77970522/5242c8cc-3d4b-4d52-87f9-7664a0cf4e0f">

<img width="606" alt="Screenshot 2023-11-29 at 09 59 00" src="https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/77970522/3be8c66e-a130-4419-871f-1d423190df2e">

**Comment by ahus1** [comment]
Update: I've published 0.41.2 which now explicitly adds the root folder opened in Rider as a search path for Antora components. I still don't fully understand what Rider considers a content root for C# projects - let's use this as a safe fallback. 

This was, item 3 should now work as intended as long as the folder is indexed.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment]
I've also backported the changes to 0.40.8 which is available as a pre-release.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
