### ISSUE TITLE
PlantUML Version

### ISSUE THREAD

**Issue by cachescrubber** [asciidoctor/asciidoctor-intellij-plugin#1491]
## Description

in #1445 the PlantUML Version has been downgraded to 1.2023.5.

I need features of the more recent versions, specially updates to plantuml-stdlib.

Is there a possibility to override the PlantUML Version?

Thanks

**Comment by ahus1** [comment]
Thanks for reaching out. Can you provide an example PlamtUML snippet for me to test this? 

There is no simple way to override this. I've asked the upstream project to package a more recent version. I've created an upstream issue: https://github.com/asciidoctor/asciidoctorj-diagram/pull/47

While we wait: You can exchange your local file `asciidoctorj-diagram-plantuml-1.2023.5.jar` with the file in this ZIP file.
[asciidoctorj-diagram-plantuml-1.2023.12.jar.zip](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/13692339/asciidoctorj-diagram-plantuml-1.2023.12.jar.zip). Note that when you replace the file, you would need to keep the original file name, or the plugin will download the old version again. 

Once you've don this, the following snippet 

```
[plantuml]
----
@startuml
legend
<size:12> Rendered with Plantuml Version %version() </size>
end legend
@enduml
----
```

should show

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/3957921/4be4d250-de63-4b69-8f97-cf9cb918dbcf)

Testing this would show us if this version of PlantUML is ok, or if you would need a more recent version.

**Comment by cachescrubber** [comment]
Hi @ahus1 ,

I created a gist with an example.

https://gist.github.com/cachescrubber/ca9a91c8d1ff32eb423735d7941057aa

The toolchain is Structurizr rendering plantuml-c4. The generated plantuml code needs the changes introduced with
[Update C4-PlantUML to v2.8.0](https://github.com/plantuml/plantuml-stdlib/commit/8d03254cf64d85ea0cfa829479e7aab1bf57464a) released in V1.2023.11 (13 Sep, 2023) 

Thanks for your support

**Comment by ahus1** [comment]
You didn't share an example output, but does that look right?

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/3957921/da57e4aa-3cae-4c42-bdb1-8fcdd9fdbf4a)

**Comment by ahus1** [comment]
Another question: Which version of IntelliJ are you using? I'd hope for 2023.3, as the latest version of the plugin is only compatible with that version.

**Comment by cachescrubber** [comment]
Yes, the output is as expected. I'm using IntelliJ 2023.3.1. Many Thanks!

To test the full workflow of the [Structurizr Diagram Type](https://docs.asciidoctor.org/diagram-extension/latest/diagram_types/structurizr/), you can find various example workspaces in the [structurizr-dsl cookbook](https://github.com/structurizr/dsl/tree/master/docs/cookbook) directory.

**Comment by ahus1** [comment]
There is now pre-release 0.41.3 that includes PlantUML 1.2023.12. Even though this is switching to the LGPL version, I found a way to include Graphviz for Windows users in the plugin. 

Please give this pre-release a try and let me know if it works as expected. If not, please share error messages, screen shots and AsciiDoc snippets as necessary. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment]
Hm, just found that I fumbled some checksum, will publish 0.41.4 soon.

**Comment by ahus1** [comment]
Preview version 0.41.4 is now available, please give it a try.

**Comment by cachescrubber** [comment]
Works like a charm. Thanks again!

**Comment by ahus1** [comment]
Happy to hear that and thank you for testing this. I'll promote this pre-release to the regular release within the next week or two. Closing this issue for now.
