### ISSUE TITLE
Replace JRuby with Asciidoctor.js?

### ISSUE THREAD

**Issue by bodiam** [asciidoctor/asciidoctor-intellij-plugin#15]
Currently, JRuby is bundled with the plugin. JRuby takes 23 MB, and replacing this with a more light version would slim down the plugin enormously.

See this: https://github.com/asciidoctor/asciidoctorj/issues/189

**Comment by ahus1** [comment]
Starting with #220 we experimentally support Ruby Asciidoctor extensions in this plugin. Changing to Asciidoctor.js conflicts with this task. I close it for now.

**Comment by mojavelinux** [comment]
I tend to agree that sticking with AsciidoctorJ is the right direction for this plugin. Given that the plugin is in Java, it makes sense to use a Java library.
