### ISSUE TITLE
One variant of callout list is rendered as quote paragraph instead

### ISSUE THREAD

**Issue by Vampire** [asciidoctor/asciidoctor-intellij-plugin#150]
According to http://asciidoc.org/userguide.html#X105 the following is a valid callout list definition, but it is rendered as quote paragraph instead:

``` asciidoc
> foo
> bar
```

**Comment by ahus1** [comment]
The Asciidoctor implementation supports Markdown style quotes instead - http://asciidoctor.org/docs/user-manual/#markdown-style-blockquotes

For Asciidoctor the callout list definitions need to have their number. 

http://asciidoctor.org/docs/user-manual/#callouts

You might want to have a look if this issue has already been raised with the Asciidoctor project. But as the syntax is already used for quotes, I think this will not be supported (although I might be wrong here).

**Comment by mojavelinux** [comment]
I agree with @ahus1.
