### ISSUE TITLE
Creating a new AsciiDoc file freezes the IDE.

### ISSUE THREAD

**Issue by timelmer-uw** [asciidoctor/asciidoctor-intellij-plugin#1502]
## Observed vs. expected behavior
The file is created, but the IDE UI freezes.

Tested on multiple devices.

## Steps to reproduce
1. Right-click in file system tree and select **Add** -> **AsciiDoc File**.
2. Enter name for the file and press enter.

## Environment
Plugin Version: 0.41.2

### IntelliJ Details
```
JetBrains Rider 2023.3.2
Build #RD-233.13135.100, built on December 19, 2023
Licensed to Tim Elmer
Subscription is active until March 26, 2024.
Runtime version: 17.0.9+7-b1087.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
.NET Core v7.0.10 x64 (Server GC)
GC: G1 Young Generation, G1 Old Generation
Memory: 4048M
Cores: 16
Registry:
  editor.config.csharp.support=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  PlantUML integration (7.3.0-IJ2023.2)
  org.asciidoctor.intellij.asciidoc (0.41.2)
  mobi.hsz.idea.gitignore (4.5.2)
```

**Comment by ahus1** [comment]
Thank you for reporting this, and sorry for breaking this. I'll see that I'll fix this soon.

**Comment by ahus1** [comment]
Sorry again for the issue. There is now plugin-version 0.41.6 which fixes it for me. Please give it a try. 

I've already published it as a regular release. If it shouldn't be available on the marketplace, you can install it as a pre-release as described below.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by timelmer-uw** [comment]
Looks like that took care of it. Thanks!

**Comment by ahus1** [comment]
Thank you for the fast retest!
