### ISSUE TITLE
Paste HTML link as an AsciiDoc link

### ISSUE THREAD

**Issue by ellipticview** [asciidoctor/asciidoctor-intellij-plugin#1504]
When copying a link from a web page, the clipboard contains the link text and the URL.

When pasting, the plugin currently only pastes the link text. This enhancement request is to change this behavior to paste as:

`https://www.example.com/acme[link text]`

**Comment by ahus1** [comment]
Thanks for reaching out. The functionality you're looking is probably included in the "formatted paste" option which is available in the icon toolbar: 

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/3957921/b49383f2-6228-4af1-8e05-3d1400d58adc)

The first time you use it, it will download Pandoc and will use it to convert formatted text copied from a web page, a word processor or a spreadsheet to AsciiDoc. 

When you like this option, and want to make it the default when you copy contents from the clipboard using keyboard shortcuts, you can do so in the plugin's settings: 

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/3957921/7ce11685-f215-4484-8fbd-2fe55927d17d)

Please let me know if this functionality is sufficient for what you're looking for.

**Comment by ellipticview** [comment]
Formatted Paste indeed provides this functionality. Thanks for the prompt response!
