### ISSUE TITLE
Images in svg-Format in themes not rendered by using PDF-Generation

### ISSUE THREAD

**Issue by HaLo1701** [asciidoctor/asciidoctor-intellij-plugin#1511]
## Observed vs. expected behavior

If I am using svg-Images in a theme in a title page or header and generates a PDF with the "Create PDF from current file"-Button, the images not rendered in PDF.

PNG-Images working fine.

When I am generate the PDF by calling asciidoctor-pdf in the CLI, the svg's are rendered correct.

## Steps to reproduce

Add a svg in the template folder and use it in the theme and use the theme.

## Environment

Plugin Version: 0.41.6

IntelliJ Details:
IntelliJ IDEA 2023.3.2 (Ultimate Edition)
Build #IU-233.13135.103, built on December 20, 2023
Licensed to nextN GmbH / Hans Lohuis
Subscription is active until September 28, 2024.
Runtime version: 17.0.9+7-b1087.9 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4056M
Cores: 28
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  markdown.open.vcs.log.link=true
Non-Bundled Plugins:
  Batch Scripts Support (1.0.13)
  MultiHighlight (3.1.0)
  de.netnexus.camelcaseplugin (3.0.12)
  light.flat.theme (0.14)
  Key Promoter X (2023.3.0)
  AceJump (3.8.18)
  indent-rainbow.indent-rainbow (2.2.0)
  youngstead.relative-line-numbers (1.1.1)
  GsonFormatPlus (1.6.1)
  com.jetbrains.jax.ws (233.13135.65)
  com.intellij.javaee.webSocket (233.11799.196)
  com.antoshk.jsf-el-extension-plugin (0.2.3.1)
  com.intellij.javaee.ejb (233.11799.196)
  PlantUML integration (7.4.2-IJ2023.2)
  org.asciidoctor.intellij.asciidoc (0.41.6)
  MavenRunHelper (4.27.1-IJ2022.2)
  com.intellij.ml.llm (233.13135.116)
  com.intellij.jsf (233.11799.196)
  com.intellij.javaee.batch (233.11799.196)
  com.bruce.intellijplugin.generatesetter (2.8.4)
  izhangzhihao.rainbow.brackets.lite (1.1.0)
  zielu.gittoolbox (500.1.5+222)
Kotlin: 233.13135.103-IJ

**Comment by ahus1** [comment]
Sorry to hear this is not working for you. Please provide a small example project that helps me to test, reproduce and fix it locally.

**Comment by HaLo1701** [comment]
Hello,
sorry for the delay.
[SVGTest.zip](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/14207789/SVGTest.zip)
Attached a small project for you to test.
I have made further tests and saw, that the image logo.svg works fine in all generations.
Our company logo logoN.svg doesn't work with the generation from the toolbar button "PDF" in the editor pane.
With the command 
`asciidoctor-pdf -a pdf-themesdir=themes -a pdf-theme=basic -a compress -r asciidoctor-diagram SVGTest.adoc `
it works fine with both images.
I am not aware enought in the svg-Format, if it is corrupt.
Many thanks for your time in advance.

**Comment by ahus1** [comment]
Sorry for the delay on my side. 

I had a look and saw that when running this in the IDE, there is a warning in the IDE's notification when running with plugin version 0.41.6, which is running Asciidoctor PDF 2.3.10: 

> WARN uri:classloader:/gems/asciidoctor-pdf-2.3.10/lib/asciidoctor/pdf/converter.rb:on_image_error: could not embed image: C:/Users/ahus1/Downloads/SVGTest/SVGTest/images/logoN.svg; Unknown error (SystemCallError) -  

Instead of the logo, I see "[logoN] | logoN.svg" in the PDF when created from the IDE. 

When running with 0.4.10, which is running Asciidoctor PDF 2.3.15 which doesn't show this warning and the output is rendered correctly. 

I see that between these releases a the SVG libraries for Asciidoctor PDF were updated. I assume one of these upgrades includes a fix, and this is now resolved in the latest version of the plugin.

**Comment by HaLo1701** [comment]
Hello,

many thanks for your reply and no problem for the delay.

I have tested it with the latest update and it works fine now.

Thank you for your spending time for that.
