### ISSUE TITLE
source code syntax highlighting is broken

### ISSUE THREAD

**Issue by Vampire** [asciidoctor/asciidoctor-intellij-plugin#152]
The code

```asciidoc
== Foo

====
[source,groovy]
----
baz
====

== Bar
```

renders fine in the preview panel, so I guess it is syntactically correct.
Yet the source code syntax highlighting in the editor is broken after the second `====` line.

**Comment by ahus1** [comment]
I believe that the "----" should be closed to form a 

```
====
[source,groovy]
----
baz
----
====
```

There's ongoing work in #143 to make the parser more robust. The other code handles this better already, but it's not ready to be released yet.

Still, I'm closing this one for now.
