### ISSUE TITLE
provide Ctrl+click-ability where possible

### ISSUE THREAD

**Issue by Vampire** [asciidoctor/asciidoctor-intellij-plugin#153]
As far as I remember when you create a language support plugin for IJ, you can also provide the ability to do Ctrl+click or Ctrl+B to navigate to other things. So you could provide the ability to navigate to link destinations, reference destinations include destinations and so on.

**Comment by ahus1** [comment]
The plugin versions 0.27.9 and later (currently only available as previews) add linking to for the following in the editor:
 
* include::[]
* image::[]
* <<id>>

The link:[] elements will navigate in the preview - soon they will also navigate in the editor.

Please let me know if you miss other elements and re-open the ticket.
