### ISSUE TITLE
unfloat::[] block macro has no effect but is printed in plain text

### ISSUE THREAD

**Issue by Vampire** [asciidoctor/asciidoctor-intellij-plugin#154]
According to http://asciidoc.org/userguide.html#X55, this

```asciidoc
image::image.png[float=right]

text left of the image

unfloat::[]

text below the text / image block
```

should display the image on the right with `text left of the image` on the same line at the left side and `text below the text / image block` bleow this block, but it seems the unfloat macro has no effect.

**Comment by ahus1** [comment]
This plugin is using http://asciidoctor.org to render the output. There might be differences to  http://asciidoc.org, or the differences might be due to limitations in the Swing or JavaFX preview. Please allow some time to investigate this and the other tickets you have opened.

**Comment by Vampire** [comment]
Sure, no problem, and no hassle. :-)
Isn't http://asciidoc.org the official language homepage and thus the canonical reference?
If so, I'd expect asciidoctor to be conformant to this.

**Comment by ahus1** [comment]
Asciidoc has been there first, and Asciidoctor is a re-implementation. 

Please raise this issue with https://github.com/asciidoctor/asciidoctor together with examples. I've had a look and unfloat::[] is mentioned in the docs of Asciidoctor - but doesn't seem to have any effect as far as I can see.

**Comment by mojavelinux** [comment]
I decided not to implement the unfloat block in Asciidoctor. Instead, we use float groups (a role). See http://asciidoctor.org/docs/user-manual/#control-the-float

Asciidoctor is where AsciiDoc is being developed. See the Asciidoctor user manual for the latest information about (modern) AsciiDoc.

**Comment by mojavelinux** [comment]
The reason I decided not to implement the unfloat macro is because it is not semantic. This is a presentation concern that should be handled by the converter. Keep in mind, it's possible to implement this macro using a block macro extension.
