### ISSUE TITLE
Unreadable text with Darcula theme

### ISSUE THREAD

**Issue by erikpragt-siteminder** [asciidoctor/asciidoctor-intellij-plugin#155]
Hi Alexander, great work on the plugin, but since one of the last updates, the text is hard to read.

Version 0.16.3 of the plugin has unreadable text when using the Darcula theme

![screen shot 2016-11-03 at 09 07 43](https://cloud.githubusercontent.com/assets/17152440/19949389/6e8d1254-a1a5-11e6-97b7-2aa8c7991e33.png)
![screen shot 2016-11-03 at 09 10 30](https://cloud.githubusercontent.com/assets/17152440/19949388/6e8adf3e-a1a5-11e6-84d0-828bd494cef1.png)

**Comment by ahus1** [comment]
I've missed CSS classes for #preamble - will be fixed in next release.
