### ISSUE TITLE
Language is not injected into listings with implicit source style

### ISSUE THREAD

**Issue by Vampire** [asciidoctor/asciidoctor-intellij-plugin#1566]
## Observed vs. expected behavior

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/325196/045ba6c7-a9e9-41dd-9ae9-d9311f2d319f)

## Steps to reproduce

```adoc
[,kotlin]
----
layout.buildDirectory / "dist" / "foo"
----

[source,kotlin]
----
layout.buildDirectory / "dist" / "foo"
----
```

## Environment

Plugin Version: 0.41.8

IntelliJ Details: IntelliJ IDEA 2023.3.4 (Ultimate Edition)
Build #IU-233.14475.28, built on February 13, 2024

**Comment by ahus1** [comment]
It is part of the AsciiDoc language spec, so the plugin should support it. Still, I like the explicit style more. 

The next version of the plugin will support it. I'll update the issue once a pre-release is available.

**Comment by mojavelinux** [comment]
We're trying to encourage the implicit style since one of the notable complaints about AsciiDoc is that `source,java` is much longer to type than the Markdown equivalent. We found a way to make it as concise as possible without deviating from the syntax.

**Comment by ahus1** [comment]
@mojavelinux - thank you for the explanation

**Comment by ahus1** [comment]
There is now release 0.41.12 which includes this change.

I published just now to the JetBrains marketplace. It should be available via the automatic update mechanism later today.

The release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) for manual installation in the meantime.
