### ISSUE TITLE
Locked PDF does not produce any error

### ISSUE THREAD

**Issue by Vampire** [asciidoctor/asciidoctor-intellij-plugin#1569]
## Observed vs. expected behavior

On Windows locked files cannot be overwritten.
The Acrobat Reader locks a PDF file while it is displayed.
So while a PDF is displayed in Acrobat Reader, no PDF-generation tool can update the file.

If you press the "PDF" button in the toolbar, it looks like the PDF gets generated and then the PDF is opened in Acrobat Reader - i.e. brought to front.
But if the PDF was already opened from a previous conversation, the file is simply not changed and you still look at the old version.

It would be great if you would instead get an error message, that the PDF could not be generated / updated.

## Steps to reproduce

- Use Windows
- Generate the PDF
- Make sure it is displayed with Acrobat Reader
- Generate the PDF again

## Environment

Plugin Version: 0.41.8

IntelliJ Details: IntelliJ IDEA 2023.3.4 (Ultimate Edition)
Build #IU-233.14475.28, built on February 13, 2024

**Comment by ahus1** [comment]
Thank you for reporting this. 

The current version of the plugin shows error messages in the notification tool window.

The next version of the plugin will show a popup window with a descriptive error message. It will also not bring the PDF file into the foreground.

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/3957921/edaafcf2-23ca-43ad-8091-b3ace8bff162)

I'll update this issue when the next version of the plugin is available.

**Comment by Vampire** [comment]
Ah, now that you say it, I see the notifications.
Thanks for making them more obvious for the future ;-)

**Comment by ahus1** [comment]
This fix is now available as pre-release 0.41.10.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
