### ISSUE TITLE
Asciidoc preview window requires horizontal scrolling

### ISSUE THREAD

**Issue by matthewadams** [asciidoctor/asciidoctor-intellij-plugin#157]
AsciiDoc Plugin Version: 0.16.4
IDE Name and Version:
WebStorm 2016.3
Build #WS-163.7743.25, built on November 10, 2016
Licensed to SciSpike / Matthew Adams
Subscription is active until March 15, 2017
For educational use only.
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

What steps will reproduce the problem?
1. Open asciidoc file
2. Show split screen with source on left & preview on right
3. Observe horizontal scrollbar at bottom of preview window

What is the expected result?
No horizontal scrolling required to see entire asciidoc preview

What happens instead?
You have to scroll horizontally in order to see full asciidoc preview content.

Attach a code sample as text, a screenshot or screencast if possible
Screenshot shows horizontal scrollbar at bottom of preview windows.

Originally filed as https://youtrack.jetbrains.com/issue/WEB-24331

**Comment by matthewadams** [comment]
![image](https://cloud.githubusercontent.com/assets/449952/20533344/cc17ba58-b0a2-11e6-9479-551e1d8eefd8.png)

**Comment by ahus1** [comment]
Hello Matthew, I tried this with the docs you presented. This only happens with the Swing preview, not with the JavaFX preview. 

As the JavaFX preview is the new one that also supports more features and a richer preview, I'll not analyze the problem. I also see that your IntelliJ installation is running on 64bit Java, a pre-requisite for the JavaFX preview. 

I therefore close it as "won't fix". I hope you don't mind. If you think this should be fixed anyway please comment here.

Regards,
Alexander

**Comment by matthewadams** [comment]
That's fine.  I just haven't had a chance yet to try it.  I'm sure it'll be fine.
