### ISSUE TITLE
Provide option to automatically scroll asciidoc preview when editing 

### ISSUE THREAD

**Issue by matthewadams** [asciidoctor/asciidoctor-intellij-plugin#158]
AsciiDoc Plugin Version: 0.16.4
IDE Name and Version:
WebStorm 2016.3
Build #WS-163.7743.25, built on November 10, 2016
Licensed to SciSpike / Matthew Adams
Subscription is active until March 15, 2017
For educational use only.
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

What steps will reproduce the problem?
1. Open an asciidoc file
2. Show split screen of source on left, preview on right
3. Navigate in source file, preview doesn't scroll to match cursor location in asciidoc source file

What is the expected result?
Preview window should scroll to match location of cursor in source.

What happens instead?
Preview window doesn't scroll to match location of cursor in source.

Attach a code sample as text, a screenshot or screencast if possible
Screenshot shows source scrolled down ~75% to end of file, but preview window is at top of file, evident from content & location of scrollbars in editor versus preview windows.

Originally filed at https://youtrack.jetbrains.com/issue/WEB-24330
![image](https://cloud.githubusercontent.com/assets/449952/20533323/b73484cc-b0a2-11e6-9cd5-cf71d07797e5.png)

**Comment by ehmkah** [comment]
Have you tried the javaFX implementation of the preview? It seems that the slider is not working but as a workaround you can move the cursor (up/down) inside editor-view.

**Comment by matthewadams** [comment]
@ehmkah I haven't tried the JavaFX impl.  I also don't understand your suggested workaround.  It sounds like you're describing the very functionality that's broken.  I'll try JavaFX & report back.

**Comment by ehmkah** [comment]
Sorry for confusing you.
If you use JavaFX implementation and your editining and your moving around with the cursor inside the editing screen=> it works.
If you are using the scrollbar (i used the wrong name slide) than it is not working.

**Comment by ahus1** [comment]
Hello Matthew, 

as @ehmkah outlined the features you're looking for are available in the JavaFX preview. Please go to "Settings... -> Languages & Frameworks -> AsciiDoc" and switch to "JavaFX WebView" (see screenshot below).

Once the JavaFX preview is active, the following will work:
* When you move the cursor in the editor on the left, the preview on the right will scroll and keep the corresponding block in the preview. 
* When you click a text element on the right, the cursor position in the editor on the left will be placed in the according block of text. 

Just scrolling either the preview or the editor with the scroll bar will not affect the other.

Please let me know if this works for you.

![image](https://cloud.githubusercontent.com/assets/3957921/21200013/12c34f08-c246-11e6-9c0c-c43820b1efc8.png)

**Comment by matthewadams** [comment]
Ok.  I had a chance to check this out.  I'm seeing the preview move as I move the caret in the editor, but I'm not seeing the cursor being moved in response to clicking a text element in the preview, unless there's a keyboard shortcut to move back from the preview pane to the editor, which I would expect to place the cursor to the corresponding location in the editor's source.  You can see in the image below that I've highlighted a word in the preview ("generate", toward the bottom), but the cursor isn't even visible in the editor.
![image](https://cloud.githubusercontent.com/assets/449952/21392465/a065c070-c755-11e6-87d6-de7b07b11bbe.png)

**Comment by ahus1** [comment]
Ok, I was able to reproduce the problem with the document you showed in the screenshot.

I've updated it for 0.17.2 version, it works for my examples, but apparently not only all cases. I'll look into it.

**Comment by ahus1** [comment]
I've tracked it down to a recent change in JDK 8 update 111, see https://bugs.openjdk.java.net/browse/JDK-8170515. This affects both the click-on-link-to-open and click-on-block-to-scroll-editor behavior. 

Annoying if your IDE's JRE is newer than the JDK you're using for development.

It will be fixed in the next patch release.

**Comment by ahus1** [comment]
Version 0.17.3 is now available from github releases and from jetbrains plugin repository. Please re-open the issue if you still experience a problem. 

Thanks for being persistent and providing accurate details about your setup. That helped to reproduce the bug.
