### ISSUE TITLE
Preview broke since most recent upgrade to 0.41.11

### ISSUE THREAD

**Issue by kistlin** [asciidoctor/asciidoctor-intellij-plugin#1585]
## Observed vs. expected behavior
```
unable to render AsciiDoc document

org.asciidoctor.jruby.internal.AsciidoctorCoreException: org.jruby.exceptions.NameError: (NameError) asciidoctor: FAILED: /home/user/doc.adoc: Failed to load AsciiDoc document - uninitialized constant AsciidoctorExtensions::KrokiDiagram::Base64

org.jruby.exceptions.NameError: (NameError) asciidoctor: FAILED: /home/user/doc.adoc: Failed to load AsciiDoc document - uninitialized constant AsciidoctorExtensions::KrokiDiagram::Base64

org.jruby.exceptions.NameError: (NameError) uninitialized constant AsciidoctorExtensions::KrokiDiagram::Base64

(the full exception stack trace is available in the IDE's log file. Visit menu item 'Help | Show Log in Explorer' to see the log)
```
Expected behavior is that the preview is rendered.

## Steps to reproduce
Setup this docker compose file to run a local instance.
https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/1361#issuecomment-1564984564

Configure the plugin to use the local Kroki instance on http://localhost:8000/.
And use the plugin to try and render a mermaid diagram. (same with PlantUML)

Setup a `*.adoc` with content
```
[mermaid]
....
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>Bob: Hello Bob, how are you?
    Bob-->>Alice: Great!
....
```
This used to render, but now fails with the mentioned error.

## Environment
Plugin Version: 0.41.11
IntelliJ Details: 2023.3.4

A downgrade to [0.41.9](https://plugins.jetbrains.com/plugin/7391-asciidoc/versions/stable/503052) makes it work again.

**Comment by ahus1** [comment]
Thank you for reporting this, and sorry this causes you trouble. I'll be porting change https://github.com/asciidoctor/asciidoctor-kroki/issues/444 to the AsciiDoc plugin. 

BTW, the AsciiDoc plugin for IntelliJ as an embedded Mermaid support which is experimental, still you might want to give it a try. You enable it in the same settings menu where you enabled Kroki.

**Comment by ahus1** [comment]
This will be fixed in the next upcoming release. I'll update the issue once a pre-release is available.

**Comment by ahus1** [comment]
This will be fixed in the next upcoming release. I'll update the issue once a pre-release is available. Thank you for providing a nice reproducer for the problem.

**Comment by ahus1** [comment]
There is now release 0.41.12 which includes this change.

I published just now to the JetBrains marketplace. It should be available via the automatic update mechanism later today.

The release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) for manual installation in the meantime.

**Comment by kistlin** [comment]
Thank you for the quick fix. It works.
