### ISSUE TITLE
Plugin breaks inline code refactor

### ISSUE THREAD

**Issue by alturkovic** [asciidoctor/asciidoctor-intellij-plugin#1591]
## Observed vs. expected behavior

Renaming a variable opens a modal dialog instead of refactoring a variable in-place in IntelliJ when this plugin is enabled.
More information available here: https://youtrack.jetbrains.com/issue/KTIJ-29171

## Steps to reproduce

Select any local variable in code editor and try to rename it using `Refactor -> Rename`.

## Environment

Plugin Version: 0.41.12

IntelliJ Details: 
IntelliJ IDEA 2023.3.6 (Ultimate Edition)
Build #IU-233.15026.9, built on March 21, 2024
Runtime version: 17.0.10+1-b1087.23 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.space (233.15026.16)
  commit-template-idea-plugin (1.2.0)
  cn.jxzhang.plugin.json-formatter (1.4)
  Key Promoter X (2023.3.0)
  AceJump (3.8.18)
  String Manipulation (9.12.0)
  org.jetbrains.plugins.hocon (2023.1.0)
  GrepConsole (12.25.0-IJ2023.3)
  MavenRunHelper (4.27.1-IJ2022.2)
  com.intellij.bigdatatools.core (233.15026.9)
  dev.turingcomplete.intellijdevelopertoolsplugins (4.1.1)
  kotest-plugin-intellij (1.3.74-IC-2023.3)
  com.github.nikolaikopernik.codecomplexity (1.5.0)
  com.intellij.bigdatatools.kafka (233.13135.103)
Kotlin: 233.15026.9-IJ

**Comment by ahus1** [comment]
Sorry for breaking this, and thank you for reporting it. It seems I broke it in #1533 when trying to fix the EAP compatibility. I'm investigating.

**Comment by ahus1** [comment]
Hi @alturkovic - there is now plugin version 0.41.13 which is available both from the JetBrains marketplace and as download from the GitHub releases page. I tested it locally with the examples I found in YouTrack and it now seems to work for me. 

Please give it a try and let me know if it works for you as well. 

If your IDE doesn't download it automatically, here the instructions on how to download and install it manually: The release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html)

**Comment by alturkovic** [comment]
That was fast! 

I can confirm that it works for me also 🙂 

Thank you for the quick fix, appreciate it 😄

**Comment by ahus1** [comment]
Happy to help, and sorry again for the inconvenience. I now consider this resolved, so I'm closing this issue.

**Comment by ahus1** [comment]
@alturkovic - as you seem to code Kotlin, maybe you have noticed the following feature for Java: If you have documentation like

```
This is a `Classname`
```

the AsciiDoc plugin will link you to that classname, and will ensure that if you rename the class that it is also renamed in your documentation. Is that something that would be useful for your docs as well? When I would implement this, I would need someone to test it in a real-world Kotlin setup.

**Comment by alturkovic** [comment]
It sounds very useful, and I would gladly help, but unfortunately, I have only used AsciiDoc documentation in Java projects so far :/
I'll write some documentation for a project I have in Kotlin, but it might take some while.

**Comment by ahus1** [comment]
Ok, then for now let's park it. When you start writing AsciiDoc documentation in a Kotlin project, please create a new issue.
