### ISSUE TITLE
Dash in front-matter keys breaks the syntax highlighting of the title

### ISSUE THREAD

**Issue by feliksik** [asciidoctor/asciidoctor-intellij-plugin#1595]
## Observed vs. expected behavior

When using frontmatter, the title is not highlighted in the editor (it's black). This makes it look like you're doing it wrong -- but you're doing it exactly right. 

I expect it to be Blue, like it is without frontmatter. 

Additionally, like the VS Code asciidoc plugin, I would expect squiggly error-lines and the "level 0 sections can only be used when doctype is book" error when the asciidoc is incorrect. 

## Steps to reproduce

Correct frontmatter, incorrect highlighting: 

```
---
this: is frontmatter
key: value
---
= My title

The title is black, should be blue. 
```

In the document below, blue highlighting of title makes it look correct, but this is incorrect asciidoc for non-book doctype (`"asciidoctor: ERROR: ../myfile.adoc: line 0: level 0 sections can only be used when doctype is book"`)

```
---
this: is frontmatter
key: value
---

= My title

The title is blue, but is incorrect asciidoc for non-book format. 
```

## Environment

Plugin Version: 0.41.13

IntelliJ Details: IntelliJ IDEA 2023.3.5 (Ultimate Edition) Build #IU-233.14808.21, built on March 12, 2024

**Comment by ahus1** [comment]
Thanks for reporting this. I'm trying to reproduce it locally, but yet without success, so I might be missing something. Some additional information might help: 

* Please share a screenshot of the editor + its preview
* Do you have an `.asciidoctorconfig` file? I wonder if its contents interfere here - it should work as long as you only for example set attributes there. 

> I would expect squiggly error-lines and the "level 0 sections can only be used when doctype is book" error when the asciidoc is incorrect.

I don't agree that the level 0 section warning is expected with the example you provided: While only a book is allowed to have multiple level 0 sections, an article is allowed to have a title which looks basically the same. As long as there is only a title, then there shouldn't be a warning. 

This is what I see: 

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/3957921/fc9a1e8b-bca0-4a3c-8e9b-d485fc560149)

**Comment by feliksik** [comment]
You are correct, my example was wrong. 

It turns out it's a dash in a frontmatter key breaks the highlighting; so it's a subtle bug. 

```
---
dashed-key-breaks-highting: blah
this: is frontmatter
key: value
---
= My title

The title is black, should be blue.
```

<img width="868" alt="image" src="https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/8527652/c86003b3-444b-43ba-82f0-7a8a9c49d672">

**Comment by ahus1** [comment]
The next version of the plugin will use a better heuristic to recognize YAML in the frontmatter. 

I'll update this issue once a pre-release is available.

**Comment by feliksik** [comment]
Thanks!!

**Comment by ahus1** [comment]
Plugin-version 0.41.14 is now available with a fix. It should be available from the JetBrains markeplace soon. 

The it is also available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html).
