### ISSUE TITLE
Embedded HTTP client

### ISSUE THREAD

**Issue by erikpragt-connectid** [asciidoctor/asciidoctor-intellij-plugin#1600]
## Why the new feature should be added

Hi @ahus1 , I was just commenting on an issue in the Youtrack issue tracker here: https://youtrack.jetbrains.com/issue/IJPL-65387/HTTP-Client-in-HTTP-Request-Markdown-Code-Block, and I was wondering if this feature would be a nice addition (maybe it's already supported?) in Asciidoctor?

Thoughts?

Cheers, Erik

**Comment by ahus1** [comment]
The AsciiDoc plugin reads all languages supported by the IDE, and then removes blanks and makes them lowercase. 

When using the language `httprequest` you would see the same behavior as in Markdown. 

But the gutters, that's something for that language to provide. Once it will work in Markdown, it will also work in AsciiDoc and any other place where it is injected automatically.

**Comment by ahus1** [comment]
Closing this issue as it depends on upstream support. Once it is there, it will also work in the AsciiDoc plugin.
