### ISSUE TITLE
Syntax highlighting: dark green (String color) for everything between `

### ISSUE THREAD

**Issue by ge0ffrey** [asciidoctor/asciidoctor-intellij-plugin#161]
Use the same color as Java uses for Strings such as "hello world" to color text between ` characters.

```
normal `green` normal
```

**Comment by ahus1** [comment]
With the work done in tickets #248 and #242, the plugin now has how highlighting for monospace, bold and italic formattings in most variations. 

Release 0.25.14 is available from the [GitHub releases page](/asciidoctor/asciidoctor-intellij-plugin/releases) of this plugin, and should soon be downloadable from the JetBrains plugin repo.
