### ISSUE TITLE
Preview broken with Asciidoc plugin 0.41.13 and IntelliJ CE 2024.1

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-intellij-plugin#1610]
## Description

Preview is blank when opening an Asciidoc document in IntelliJ 2024.1 (CE)

## Environment

Plugin Version: 0.41.13

## IntelliJ Details: 2024.1 (Broken)

IntelliJ IDEA 2024.1 (Community Edition)
Build #IC-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-28-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  PsiViewer (241.14494.158-EAP-SNAPSHOT)
  PythonCore (241.14494.240)
  de.docs_as_co.intellij.plugin.diagramsnet (0.2.4)
  com.tabnine.TabNine (1.82.0)
  com.jetbrains.space (241.14494.150)
  Docker (241.14494.251)
  com.intellij.grazie.pro (0.3.300)
  CheckStyle-IDEA (5.90.0)
  org.jetbrains.idea.grammar (2022.3.2)
  io.moderne (0.3.4)
  PlantUML integration (7.10.1-IJ2023.2)
  org.asciidoctor.intellij.asciidoc (0.41.13)
Kotlin: 241.14494.240-IJ
Current Desktop: X-Cinnamon

## IntelliJ Details: 2023.3.6 (Works)

IntelliJ IDEA 2023.3.6 (Community Edition)
Build #IC-233.15026.9, built on March 21, 2024
Runtime version: 17.0.10+1-b1087.23 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-28-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 4
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  PsiViewer (233.2)
  de.docs_as_co.intellij.plugin.diagramsnet (0.2.4)
  com.tabnine.TabNine (1.82.0)
  com.jetbrains.space (233.15026.16)
  Docker (233.15026.15)
  com.intellij.grazie.pro (0.3.294)
  CheckStyle-IDEA (5.90.0)
  org.jetbrains.idea.grammar (2022.3.2)
  io.moderne (0.3.4)
  PlantUML integration (7.10.1-IJ2023.2)
  PythonCore (233.14808.12)
  org.asciidoctor.intellij.asciidoc (0.41.13)
Kotlin: 233.15026.9-IJ
Current Desktop: X-Cinnamon

## How to reproduce

$ sudo snap remove intellij-idea-community
$ sudo snap install intellij-idea-community --channel=2023.3/stable --classic

Open Asciidoc document - preview works.

$ sudo snap remove intellij-idea-community
$ sudo snap install intellij-idea-community --channel=2024.1/stable --classic

Open Asciidoc document - preview is broken.

**Comment by wfouche** [comment]
## IntelliJ 2023.3.6

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/13682850/2f2bd652-0d9b-4170-b880-8192dba78c81)

**Comment by wfouche** [comment]
## IntelliJ 2024.1

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/13682850/b07d0cbb-3a91-4372-97f1-efb7ab34ecee)

**Comment by ahus1** [comment]
Hi, sorry to hear this is broken for you. I will try to look into this more next week.

I found a similar problem which was related to a hostname change, which happens to me whenever I change WiFi networks.

I raised this issue: https://youtrack.jetbrains.com/issue/IJPL-148653/Preview-of-Markdown-stays-empty-after-hostname-change

The issue includes a workaround. Please let me know if this works for you. The issue has been classified as a usability problem. I tend to disagree, but didn't find the time to discuss this. let's see first if this issue matches yours.

In the meantime as a workaround, you can try to enable the JavaFX preview. You'll need to install the JavaFX support plugin first. 

I will investigate this further next week.

**Comment by wfouche** [comment]
## IntelliJ 2024.1 (Swing Browser)

![image](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/13682850/7bcb4808-04b9-493d-b83b-9b39c5c759cd)

**Comment by wfouche** [comment]
Hi @ahus1,

I did change the hostname of my Linux Mint dev laptop recently.  :-)

I deleted the files in .cache/JetBrains for IntelliJ 2024.1 and now it works. Will test the JavaFX workaround as well.

Thanks.

**Comment by ahus1** [comment]
Good to hear the first option worked for you. The second option with JavaFX was very slow the last time I tried. Let's hear what your experiences are.

If jetbrains doesn't work on that issue, I might add a workaround to the plugin to delete the file automatically.

**Comment by wfouche** [comment]
JavaFX worked after configuring it according to your instructions at: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/preview/javafx-preview.html

However, I also find it a bit slow and my SVG Mermaid diagrams did not render and I had to change them to PNG then it worked fine.  JCEF is definitely preferred,  keeping JavaFX as a backup (Plan B) option.

**Comment by ahus1** [comment]
A fix that will delete the lock automatically on startup will be part of the next release of the plugin. I'll update this issue once a pre-release is available.

**Comment by ahus1** [comment]
Plugin-version 0.41.14 is now available with a fix. It should be available from the JetBrains markeplace soon. 

The it is also available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html).

**Comment by wfouche** [comment]
Thanks. I tested the fix and it works great.

**Comment by ahus1** [comment]
Happy to hear it works for you. Please upvote the issue I opened for IntelliJ, so it will be fixed there eventually as well: https://youtrack.jetbrains.com/issue/IJPL-148653/Preview-of-Markdown-stays-empty-after-hostname-change

**Comment by ahus1** [comment]
Starting with the upcoming release 0.43.3, I'll do this check not only once per IntelliJ run, but every time you open an AsciiDoc file to prevent problems after a machine has been suspended.

**Comment by ahus1** [comment]
@mehmandarov - about the blank-preview we talked about this week - this is the issue which I fixed in plugin version 0.41.14 which rolled out in May. Please let me know if you still experienced the blank screen after that. As a precaution, I'll update the logic in the next upcoming release to check this lock file more often. 

If you want to up-vote the issue at JetBrains, here's the link: https://youtrack.jetbrains.com/issue/IJPL-148653

**Comment by ahus1** [comment]
The change mentioned in my last comment is now part of pre-release 0.43.3

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
