### ISSUE TITLE
Asciidoc is not rendering in arm linux machine 

### ISSUE THREAD

**Issue by ananta-code** [asciidoctor/asciidoctor-intellij-plugin#1619]
I have mac m1/m2 laptop and one ubuntu VM is running .intelliJ idea for arm version IntelliJ IDEA 2024.1 (Ultimate Edition).
after installing the Asciidoc plugin version 0.41.14 i am expecting the asciidoc document should be rendered but it is blank nothing is coming.

Could someone suggest if it is a known issue or is there any WA?

**Comment by ahus1** [comment]
I'm sorry to hear that it isn't working for you. Unfortunately I don't have access to a m1/m2 to reproduce the setup. 

Please test if the preview of the Markdown plugin is working, as it is using the same technology for the IDE preview. Looking at this upstream issue, it seems to be a platform problem: https://youtrack.jetbrains.com/issue/IJPL-93409/Markdown-preview-doesnt-work-on-aarch64-Linux

A JetBrains developer suggested to add some dependencies and to provide some logs. Maybe some of the suggestions there work for you as well, or you can provide additional information to the upstream issue.

As a back-up solution, you could try to get the JavaFX preview working, but that is deprecated, slower compared to JCEF and lacks some features. See https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/preview/javafx-preview.html on how to enable it.

**Comment by ahus1** [comment]
Closing this issue due to lack of feedback. Please up-vote the issue https://youtrack.jetbrains.com/issue/IJPL-93409 so it will eventually be resolved upstream.
