### ISSUE TITLE
asciidoctor-diagram file location issues

### ISSUE THREAD

**Issue by GregDThomas** [asciidoctor/asciidoctor-intellij-plugin#162]
AsciiDoc Plugin Version:  0.16.4

IDE Name and Version:  
IntelliJ IDEA 2016.3
Build #IU-163.7743.44, built on November 17, 2016
Subscription is active until April 18, 2017
JRE: 1.8.0_112-release-408-b2 x86
JVM: OpenJDK Server VM by JetBrains s.r.o

We're using Asciidoc with the asciidoctor-diagram plugin. Because we're using two backends, it's necessary to adjust the output directory of the asciidoctor-diagram plugin, using Asciidoc syntax similar to the following ...

    :imagesoutdir: images

When compiling the Asciidoc, this will ensure that the diagrams get written to either

    ./build/asciidoc/html/images
or

    ./build/asciidoc/pdf/images
depending on the backend in use. However, because the IntelliJ Asciidoc plugin is rendering using HTML, when the .adoc file is opened in IntelliJ the plugin will generate images in the folder

    ./src/docs/asciidoc/images

i.e. in the source tree. Now, we can of course ignore these images, but it's less than ideal. Is there/could there be an attribute indicating that the document is being rendered by the IntelliJ plugin? That way we could have a directive similar to;

    :imagesoutdir: images
    ifdef::asciidoctor-intellij-plugin:[:imagesoutdir: ../../../build/src/docs/asciidoc/images]

To ensure that using the IntelliJ plugin doesn't write files in to the source tree.

Of course, there may be another solution, in which case I'm all ears!

Thanks

**Comment by mojavelinux** [comment]
I think the IntelliJ plugin should set some of the environment-specific variables we define in other integrations. I'm not sure what the values should be yet.

* platform
* env

Perhaps platform=java and env=ide (or intellij).

**Comment by GregDThomas** [comment]
OK, thanks for the pointer; a bit of experimentation gave me `{env}==idea` which means I'm now using ...

    // Define the images dir for the html & PDF backends - translates to ./build/asciidoc/[html|pdf]/images
    :imagesoutdir: images
    // But change it when viewed by the IntelliJ Asciidoc plugin to prevent it writing images to the source folder - translates to ./build/asciidoc/images
    ifeval::[{env}==idea]
    :imagesoutdir: ../../../build/asciidoc/images
    endif::[]

Note that this does mean that the image is missing in the preview window, This is because the image is written to `./build/asciidoc/images` but Asciidocotor is looking for images in `./src/docs/asciidoc/images` - which is where the 'regular' images are held. As it seems you can only set one images directory, we're stuck with seeing either the asciidoctor-diagram images /or/ the regular images in the preview window - but that's just something we'll have to live with.

**Comment by ahus1** [comment]
@GregDThomas - you've already found the already existing environment variable `{env}==idea` - well done. 

I'm considering to override `imagesoutdir` when rendering the preview. But I wonder if this would break something else. 

BTW: I found that rendering SVGs worked quite well for with both HTML and PDF. What are your experiences? What diagrams are you using?

**Comment by GregDThomas** [comment]
The drawback of overriding `imagesoutdir` is that, as far as I know, the preview window can only show images from a single folder. So you can either show images from asciidoctor-diagram /or/ regular images saved on the disc and embedded via `image::`. We've taken the decision to prefer the latter over the former in the preview window using the `ifdef` directive highlighted above. Other users may prefer the former. If you can overcome the "single images folder" limitation then great, otherwise you may need a mechanism for users of the plugin to select which behaviour they prefer.

Our build process overcomes this by copying the source Asciidoc in to `./build/asciidoc` and compiling it from there.

We're using plantuml sequence diagrams (http://plantuml.com/sequence-diagram) in our Asciidoc - it works very well.

**Comment by GregDThomas** [comment]
PS. The other thing I'll add is that even with `imagesoutdir` set to a scratch folder with plugin preview enabled, a folder ".asciidoctor" gets created in the source folder. It would be better if it were created in `imagesoutdir` if possible.

**Comment by agorges** [comment]
I hit the same problem. I hacked the plugin (quick and dirty, not checked for side effects, JavaFX Preview only) to get a temporary solution. I place the images somewhere in build/asciidoctor-intellij. The Plugin will check every parent folder for build/asciidoctor-intellij to find the image file. You can find the hacked plugin here (use at your own risk!): https://github.com/softwaregenerator/asciidoctor-intellij-plugin/releases/tag/0.17.1.hack

If your *.adoc file resides in src/docs/asciidoc then add
```
[ifeval::[{env}==idea]
:outdir: ../../../build/asciidoctor-intellij/images
endif::[]
```
to your file.
 
I hope someone could look into this issue...

**Comment by ahus1** [comment]
Hello @agorges - I like your idea! Would you consider extending your solution to a pull request? 

I'm fine if this only works with JavaFX. 

Some thoughts and snippets that might help: 

To find out if JavaFX is enabled you can have a look at the settings: 

    final AsciiDocApplicationSettings settings = AsciiDocApplicationSettings.getInstance();
    settings.getAsciiDocPreviewSettings()....

AsciiDoc.java has a method getDefaultOptions() - you can use it to pass imagesoutdir or outdir when JavaFX preview is enabled. 

AsciiDocPreviewEditor might be a good place to create a temporary folder using java.nio.file.File#createTempDirectory. It can pass the folder to AsciiDoc.java and to JavaFxHtmlPanel. Once the  AsciiDocPreviewEditor is disposed it can remove the folder.

**Comment by agorges** [comment]
Yep, I'm looking into it. Thanks for the heads up @ahus1.

**Comment by agorges** [comment]
Ok, I created a pull request.
The plugin is available under https://github.com/softwaregenerator/asciidoctor-intellij-plugin/releases/tag/0.17.1-tempImagesDir

**Comment by ahus1** [comment]
Thank you for the pull request! I've update the code to handle windows folders. It should now also calculate the md5 sums that are used to detect changes in the images for the files in the temporary folder. 

I've uploaded a preview version 0.17.2 to the [github releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases/). It runs fine for me on Windows and Ubuntu. Please give it a try - I plan to publish it on the IntelliJ site in a few days after some testing in the real world.
