### ISSUE TITLE
White background hides quoted code blocks

### ISSUE THREAD

**Issue by Bonjour123** [asciidoctor/asciidoctor-intellij-plugin#1620]
## Observed vs. expected behavior

In webstorm, I get annoying background when using `these code quotes`: "\`".
They overlap the quotes and appear only in asciidoc editor. It seems I can't control neither the color nor the behavior in the intelliJ settings .
I get this issue for any `theme` and `color scheme` combination.
Modifying the `asciidoc color scheme` entries and setting a black background doesn't help, as after a few milliseconds after each keypress, the white background appears again.
So I think this behavior is neither derived from a theme nor a color scheme, I think it's shipped within the plugin.

The problem is that when using a dark color scheme, the background color becomes almost white, and I can't see the text.
As a workaround, I can modify asciidoc color scheme and set the foreground text to black.

**But** then:
1) I still get some unreadable text (depends on the color scheme settings, since this whitish background is *not* from the color scheme). 
2) My editor is full of big white rectangles that really are not helpful highlighting, as code-wrapped text is not that important
3) All the white rectangles flicker at every single key press

## Steps to reproduce

Any adoc containing code quotes "`" works.

_Shows the unreadable and flickery rectangles as well as the color scheme where *no* background is set_

[unreadable and flickery rectangles](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/17679888/2cfe522b-1f6d-44a2-b805-972a4e563c20.webm)

_Before_

![Screenshot from 2024-05-10 12-28-10](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/17679888/57ec055c-8eb2-4f68-b189-a4c9dddecff7)

_After setting foreground to black in asciidoc color scheme_

![Screenshot from 2024-05-10 12-29-18](https://github.com/asciidoctor/asciidoctor-intellij-plugin/assets/17679888/46bf88db-21e4-413d-88d5-c3794e1a537a)

## Environment

Plugin Version: 0.41.14

IntelliJ Details: WebStorm 2023.3.3
Build #WS-233.14015.89, built on January 23, 2024
Runtime version: 17.0.9+7-b1087.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 6.5.0-28-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 3938M
Cores: 16
Registry:
  debugger.new.tool.window.layout=true
  run.configuration.max.name.length=180
  ide.experimental.ui=true
  eslint.additional.file.extensions=svelte
  run.anything.context.recent.directory.number=15
Non-Bundled Plugins:
  de.netnexus.camelcaseplugin (3.0.12)
  com.intellij.properties (233.11799.172)
  dev.meanmail.plugin.nginx-intellij-plugin (2022.1.1)
  XPathView (233.11799.188)
  com.intellij.aqua (233.14015.147)
  org.asciidoctor.intellij.asciidoc (0.41.14)
  de.timo_reymann.intellij-mjml-support (3.3.0)
  dev.blachut.svelte.lang (233.14015.23)
Current Desktop: ubuntu:GNOME

**Comment by Bonjour123** [comment]
Yes, I actually shifted to the Dark theme from the Light one. No problems with the dark themes, but only with the light ones.
->Just re-read my issue, I actually thought that it was working well with dark themes, so don't know why I wrote `I get this issue for any theme and color scheme combination.`... maybe I forgot to save the edits..

Unfortunately I had to reinstall my os for another unrelated problem, so I currently have default settings in Webstorm.

**Comment by ahus1** [comment]
I found that the AsciIDoc plugin picked the background color or the light theme where it should have picked the color of the dark theme as some function was looking for the theme of the IDE and not the editor. 

This will be fixed in the next release of the plugin, and I'll post a note here once a preview version is available.

In the meantime, when using a dark theme for the editor, use it with a dark theme of the IDE.

**Comment by Bonjour123** [comment]
Great to hear ! Thank you for the awesome work !

**Comment by ahus1** [comment]
The changes are available as part of version 0.41.15 of the plugin which is currently available as a pre-release.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
