### ISSUE TITLE
Incompatible with IDEA 2024.2 EAP

### ISSUE THREAD

**Issue by jtiee** [asciidoctor/asciidoctor-intellij-plugin#1636]
## Observed vs. expected behavior

IntelliJ's Plugin UI shows "Marked as incompatible" for version 0.41.14 on IDEA 2024.2 EAP.

Ideally, the plugin should work on 2024.2 EAP.

## Steps to reproduce

. Upgrade to IDEA 2024.2 EAP
. Notification appears alerting "Marked as incompatible"

## Environment

Plugin version: 0.41.14

IntelliJ IDEA 2024.2 EAP (Ultimate Edition)
Build #IU-242.18071.24, built on June 20, 2024
Runtime version: 21.0.3+13-b499.2 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.5
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
  ide.browser.jcef.gpu.disable=true
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (242.18071.27)
  com.maaxgr.intellij.jsonviewer (1.0.19)
  IdeaVIM (2.12.0)
  org.jetbrains.plugins.ruby (242.18071.24)
  com.intellij.grazie.pro (0.3.313)
  PlantUML integration (7.10.1-IJ2023.2)
  com.dmarcotte.handlebars (242.18071.12)
  com.github.copilot (1.5.10.5840)
  com.jetbrains.php (242.18071.27)
Kotlin: 242.18071.24-IJ

**Comment by jtiee** [comment]
I see you've already started work on this in #1629. Feel free to close this issue.

**Comment by ahus1** [comment]
Thanks, I already started looking into it earlier today. Expect an update soon. 
Version 242.16677.21 should still work, but  242.18071.24 changed its APIs.

**Comment by ahus1** [comment]
There is now a new pre-release 0.42.0 that includes a fix. Please give it a try, I will also give it a try over the next days before I promote it to a regular release.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment]
I've promoted the releases and it is now available as a regular update on the marketplace.

**Comment by ahus1** [comment]
Reopeing this, as it seems I've broken the preview functionality with this.

**Comment by jtiee** [comment]
Thanks for the update! 0.42.0 no longer complains about being incompatible.

The preview does seem to work, but the styling is different in several ways (image captions, table headings, and some others). Clicking the preview no longer scrolls to the source markup location, and clicking the markup no longer scrolls the preview. The preview does update as I type source modifications.

**Comment by ahus1** [comment]
@jtiee - see my comment above: 

> Reopeing this, as it seems I've broken the preview functionality with this.

**Comment by jtiee** [comment]
0.42.2 seems to work well. The styling and scrolling issues seem to be addressed. 👍

**Comment by ahus1** [comment]
@HaLo1701 - there is now release 0.42.2 which fixes what I broken in 0.42.0. I'm sorry for this mistake on my side. 

@jtiee - thank you for testing this!
