### ISSUE TITLE
Lost focus on Recent files (Ctrl + e)

### ISSUE THREAD

**Issue by luismoramedina** [asciidoctor/asciidoctor-intellij-plugin#164]
When i am on a file and go back to a my whatever.adoc using shortcut **ctrl + E**, (recent files) the focus is lost and i cannot edit the file without clicking in the text or doing a **Ctrl + Shift + N** (Go to file); this combination keeps the focus on the text...

Thanks and regards.

AsciiDoc Plugin Version: 1.16.4

IDE Name and Version: IntelliJ IDEA 2016.3
Build #IC-163.7743.44, built on November 17, 2016
JRE: 1.8.0_112-release-408-b2 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by ahus1** [comment]
I was able to reproduce this behavior. It only happens if you closed the whatever.adoc and then use **ctrl + E** - it doesn't happen when you go back to a file that is still open.

**Comment by luismoramedina** [comment]
My "tab limit" configuration is set to 1... so maybe when i change to another file, intellij closes the last file opened.

Tab limit configuration:
https://i.stack.imgur.com/n7xJW.png

**Comment by ahus1** [comment]
This was fixed in the "upstream" markdown plugin. It depended on the order of the setting of the focus: first trigger it on the preview, then on the editor. It will be part of the next release.
