### ISSUE TITLE
foootnote:[] is highlighted (incorrectly) 

### ISSUE THREAD

**Issue by kittylyst** [asciidoctor/asciidoctor-intellij-plugin#1650]
## Observed vs. expected behavior

When a misspelled footnote annotation is used (e.g. foootnote:[] with 3 o's) it highlights in the IDE as though it was a correct footnote:[]

When the document is rendered as a PDF, the literal text foootnote:[] is produced inline, and not as a footnote.

## Steps to reproduce

Create a foootnote:[] in a valid doc.

## Environment

Plugin Version: 41.14 (also verified on 0.42.2)

IntelliJ Details: IntelliJ IDEA 2024.1.2 (Ultimate Edition)
Build #IU-241.17011.79, built on May 22, 2024
Licensed to Ben Evans
You have a perpetual fallback license for this version.
Subscription is active until May 9, 2025.
Runtime version: 17.0.11+1-b1207.24 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.5
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.jetbrains.webstorm.web-assembly-plugin (241.14494.150)
  com.jetbrains.space (241.17011.48)
  com.intellij.kubernetes (241.17011.84)
  org.asciidoctor.intellij.asciidoc (0.41.14)
  com.intellij.ml.llm (241.17011.2)
  com.github.copilot (1.5.5.5632)
Kotlin: 241.17011.79-IJ

**Comment by ahus1** [comment]
Thank you for reporting this. Unfortunately it is quite hard to determine what is an inline macro and what is not. Asciidoctor, the renderer used here, will render a plain text unless a macro is registered. 

The macros are different depending on the activated extensions and custom macros, and it is difficult for an IDE to figure out which are available in this environment. Asciidoctor will render the macro as plain text if it is unknown. 

I'm asking @mojavelinux if Asciidoctor could render a warning if it comes across an unknown inline or block macro.

**Comment by mojavelinux** [comment]
> Asciidoctor could log a warning if it comes across an unknown inline or block macro.

No, because a macro is only positively matched and an extension can add any macro. It is not the responsibility of the processor to check for what isn't correct syntax...and it's also part of the mantra of AsciiDoc that anything which isn't correct syntax is just prose.

**Comment by ahus1** [comment]
Thank you for that clarification. Closing this issue as wont-fix here, as I don't see a way in the IDE to identify the names of available macros during editing.
