### ISSUE TITLE
Low contrast syntax highlighting in code block previews when in dark mode

### ISSUE THREAD

**Issue by BourneLoser** [asciidoctor/asciidoctor-intellij-plugin#1668]
<img width="460" alt="dark-code-block" src="https://github.com/user-attachments/assets/e6ca9605-2791-4b1c-8323-fc8a691f80fd">

Various words in code blocks are hard to see for example "args" in the screenshot above. The Markdown plugin doesn't seem to be affected. If it were a bug, I couldn't possibly be the only person experiencing the issue so I have to believe it's user error. I've tweaked various settings but cannot figure out how to get the previews back to normal. Code blocks are fine in light mode; rendered HTML is fine too. It's just an issue with the previewer. The behavior did seem to start after recently upgrading the asciidoc plugin though. Please let me know what setting is relevant to get it back to normal. Thanks.

```
IntelliJ IDEA 2024.1.5 (Community Edition)
Build #IC-241.18968.26, built on August 4, 2024
Runtime version: 17.0.11+1-b1207.30 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.6
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Metal Rendering is ON
Non-Bundled Plugins:
  com.jetbrains.space (241.18968.26)
  org.asciidoctor.intellij.asciidoc (0.42.2)
Kotlin: 241.18968.26-IJ
```

**Comment by ahus1** [comment]
Thanks for asking this question here. 

Please provide one more piece of information: In the AsciiDoc settings in your IDE, which "Preview browser" is selected there? It should be the JCEF browser, as it provides the best experience. 

Please provide the source code snipped you used as text in this issue so I can use it for testing this issue locally. 

Thanks!

**Comment by BourneLoser** [comment]
Thanks for looking into this!
Yes, I've had it on JCEF. Can't remember ever having it on Swing or anything else.

Preview browser: JCEF Browser
[x] Replace preview contents without flicker
[x] Enable built-in Mermaid Diagrams support

FWIW, just now I noticed it showed the option to download dependencies for diagrams. I remember doing this a while back which is why I still had Mermaid support checkbox enabled. Anyways, I clicked it, it seemed to download stuff, I waited a bit and restarted IntelliJ but it had no effect on the code block previews.

Here's the example code for the source blocks
```java
class HelloWorld {
    public static void main(String[] args) {
        System.out.println("Hello, World!");
    }
}
```

**Comment by ahus1** [comment]
Thank you for reporting this and sorry for the trouble. It seems to me I broke this when trying to fix issue #1601. 

The next version of the plugin will render it as follows for coderay: 

![image](https://github.com/user-attachments/assets/42f9f84f-4c87-40fa-a2cf-2428a18b1677)

and for rouge: 

![image](https://github.com/user-attachments/assets/76b3b0bf-c7c3-4065-88ee-00295dae3b8b)

I'll add a note in this issue once a pre-release is available.

**Comment by ahus1** [comment]
The version 0.43.1 is now available which includes this fix. 

It will be available from the JetBrains marketplace shortly. In the meantime, it is also available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html).

**Comment by BourneLoser** [comment]
Updated to 0.43.1. Issue is fixed, thanks!
