### ISSUE TITLE
Don't pollute source tree with generated diagrams

### ISSUE THREAD

**Issue by beikov** [asciidoctor/asciidoctor-intellij-plugin#167]
When I enter the preview view, the diagram files are generated and put into the source directory.
Is it possible to configure the plugin to put the generated files to an output directory instead?

AsciiDoc Plugin Version: 0.16.4
IDE Name and Version:

IntelliJ IDEA 2016.3
Build #IU-163.7743.44, built on November 17, 2016
Licensed to Christian Beikov
Subscription is active until May 3, 2017
JRE: 1.8.0_65-b17 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by ahus1** [comment]
Hello Christian, thanks for sharing your experience with this plugin. 

The temporary file handling was improved in version 0.17.2 for the JavaFX preview. See #162 for the discussion. 

Please upgrade your plugin and switch to the JavaFX preview. 

If you should still experience temporary files with the updated version and JavaFX preview please post a small sample document here and we'll have a look.
