### ISSUE TITLE
Antora includes do not display in preview

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-intellij-plugin#1686]
## Description

I am not sure whether this a bug or jst a misconfiguration, but I am seeing a lot of this with a Antora.  It is the same for both `example$` and `partial$`.

![image](https://github.com/user-attachments/assets/ee84b903-3ee8-4c15-bfea-1c634352f5c1)

When I build the docs they come out just fine, but they not work correctly in the IntelliJ preview.

This is with IntelliJ  2022.3.3 and a couple of different versions of the Asciidoc plugin. (I am now on the latest 0.39.11)

**Comment by ahus1** [comment]
Thanks for reaching out. Looking at the release notes it should work, Antora support should be present in that version.

Can you provide an example repository to reproduce it, or at minimum a screenshot of the folder structure you are using?

**Comment by ysb33r** [comment]
This project is a good example - https://gitlab.com/ysb33rOrg/org/ysf-project-plugins/-/tree/master/docs

**Comment by ysb33r** [comment]
It might be something with the setup, because I have another project where it seems to be working fine.

**Comment by ahus1** [comment]
Thank you for providing the example. The AsciiDoc plugin for IntelliJ is confused by the fact that there is no component name. 

All your YAML properties are replaced during the build process. And as they use hashes, this results on plain YAML parsing in an empty property value which is not supported.

```
name: ##COMPONENT##
title: ##TITLE##
version: ##VERSION##
start_page: ##STARTDOC##
```

If you instead add quotes for each of those to-be-replaced values, those will become the values. The plugin will start to work once you add quotes around `##COMPONENT##`. 

The validations for the YAML in the idea will still show a warning as a hash values is not allowed in the component name, still it will it will do well in showing the preview and resolving the `example$` prefix. 

I hope this resolves it for you. I'm not sure if I should teach the AsciiDoc plugin for IntelliJ to handle empty values for the component name gracefully - it is IMHO an undefined area. I'll have to think about that. I'd be happy to hear your thoughts.

**Comment by ysb33r** [comment]
Thanks @ahus1 !
