### ISSUE TITLE
antora: image placement

### ISSUE THREAD

**Issue by rasmusmk** [asciidoctor/asciidoctor-intellij-plugin#1692]
Using antora:
in a adoc file I want to add a image:

image::sub_folder/test.png[]

the adoc file and image is placed in antora style:

test_module/pages/sub_folder/test.adoc
test_module/images/sub_folder/test.png

In clion it can find the file but in preview it cannot find the file.

if I change image line to:
image::test.png[]

the preview can find the image, but clion and antora compilation cannot find the image

## Environment

Plugin Version: 0.43.1

IntelliJ Details: 
CLion 2024.2.1
Build #CL-242.21829.173, built on August 30, 2024

Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
.NET Core v8.0.4 x64 (Server GC)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2008M
Cores: 8
Registry:
  actionSystem.update.actions.warn.dataRules.on.edt=false
  debugger.attach.dialog.enabled=true
  run.processes.with.pty=TRUE
  ide.experimental.ui=true
  ide.slow.operations.assertion=false
  cache.folding.model.on.disk=false
  i18n.locale=
Non-Bundled Plugins:
  com.intellij.plugins.vscodekeymap (242.20224.385)
  PlantUML integration (7.11.2-IJ2023.2)
  org.asciidoctor.intellij.asciidoc (0.43.1)

**Comment by ahus1** [comment]
I had difficulties to reproduce it - can you please prepare a minimal example as a ZIP file attached to this issue, or point to an example GitHub repository?

**Comment by ahus1** [comment]
There hasn't been feedback for a while. Closing this issue for now. If you would provide feedback later, I'm happy to re-open the issue.
