### ISSUE TITLE
Sort/filter table

### ISSUE THREAD

**Issue by xuanswe** [asciidoctor/asciidoctor-intellij-plugin#1693]
## Why the new feature should be added

Allow to sort and filter in the render table, similar to Excel header.

## How the new feature should work

Currently, the table is rendered as below:

![image](https://github.com/user-attachments/assets/f7f585ca-d6a4-4554-850e-1b2b48b33d8a)

I would be nice to have a button similar to Excel to sort/filter the table as below:

![image](https://github.com/user-attachments/assets/7126153c-12f8-43b9-bc4d-defbeb650d2a)

**Comment by ahus1** [comment]
Thank you for reaching out. AsciiDoc and plugin IntelliJ includes only the support which comes with the Asciidoctor implementation, and that is as of today only simple tables. 

When you integrate the output in your final site with for example a Javascript library like https://datatables.net/ you can allow filtering based on the HTML AsciiDoc created for the table. 

There are a lot of different table plugins available, still I haven't tried them myself. The best way to contact people who tried out such setups would be the Asciidoctor chat: https://asciidoctor.zulipchat.com/
When you search the chat, you might also find answers to similar questions. 

I hope this solves your problem. As this is beyond the IntelliJ AsciiDoc plugin, I consider this questions answered. Let me know if I can continue to help, of if this issue can be closed.

**Comment by ahus1** [comment]
Closing as no comment for the last two weeks.
