### ISSUE TITLE
When PlantUML is output with SVG, the image is broken

### ISSUE THREAD

**Issue by masakura** [asciidoctor/asciidoctor-intellij-plugin#170]
When PlantUML is output with SVG, the image is broken.

```
.[plantuml,plantuml-seq-svg,svg]
[plantuml,plantuml-seq,svg]
----
Foo -> Bar
----

.[plantuml,plantuml-class-svg,svg]
[plantuml,plantuml-seq-svg,svg]
----
class Foo {
}
----
```

![broken](https://cloud.githubusercontent.com/assets/6840413/23578436/6756918e-011a-11e7-9114-86de0e945477.png)

PNG has no problem.

![normal](https://cloud.githubusercontent.com/assets/6840413/23578460/c01c962e-011a-11e7-9359-bf0367f480d0.png)

AsciiDoc Plugin Version: 0.17.3

IDE Name and Version: IntelliJ IDEA 2016.3.4

**Comment by ahus1** [comment]
I suppose you are using JavaFX preview. This uses the included SVG viewer of JavaFX's webview. Unfortunately the webview has limitations when displaying SVGs. Comments and ideas on how to improve the SVG preview are welcome - I'm currently not aware of a solution for this.

If you want a better preview for plantuml diagrams, I suggest you use the plantuml plugin for intellij. https://plugins.jetbrains.com/plugin/7017-plantuml-integration

I use it to preview and edit PlantUML diagrams in separate files like this. 

doc.adoc:
```
[plantuml, image, svg]
--
include::image.puml[]
--
```

image.puml:
```
@startuml
node node1
node node2
node node3
node1 --> node2
node2 --> node2
@enduml
```

Let me know if this workaround improves your situation. I'm also eager to hear about ideas to improve SVG rendering.

**Comment by masakura** [comment]
It's nice idea!

I am using AsciiDoc and PlantUML with GitLab. [Gitlab support PlantUML](https://docs.gitlab.com/ee/administration/integration/plantuml.html). But, the syntax of GitLab does not accept the syntax of Asciidoctor Diagram. Cannot use `include` inside GitLab PlantUML extension. (For your reference, this setting is not enabled for GitLab.com.)

```
(GitLab Style)

[plantuml,format="svg"]
--
Foo -> Bar
--

(Using include)

[plantuml,format="svg"]
--
include::test.puml[]
--
```

Case my internal GitLab.

![gitlab](https://cloud.githubusercontent.com/assets/6840413/23579371/83b02ed4-012f-11e7-9882-25e72b684ea8.png)

Case IntelliJ IDEA.

![intellij](https://cloud.githubusercontent.com/assets/6840413/23579385/d7f86c7c-012f-11e7-9563-9bb7d0d5827e.png)

I think GitLab will solve to some extent if it corresponds to the Asciidoctor Diagram format. But it is more pleasant if it is properly displayed in JavaFX preview.

**Comment by ahus1** [comment]
for now, there doesn't seem to be a better solution for the JavaFX preview. I close this due to inactivity. Won't fix for now.

**Comment by ahus1** [comment]
I thought again and the next version will render a PNG preview event if SVG was specified in the source. I used a crude ruby hack ...
