### ISSUE TITLE
include::sample[] directive NOT resolved

### ISSUE THREAD

**Issue by dancer1325** [asciidoctor/asciidoctor-intellij-plugin#1712]
## Observed vs. expected behavior
* In the [Gradle documentation](https://github.com/gradle/gradle/blob/master/platforms/documentation/docs/src/docs/userguide/authoring-builds/basics/build_lifecycle.adoc), you can find 

  ```
  include::sample[dir="snippets/buildlifecycle/basic/kotlin",files="settings.gradle.kts[];build.gradle.kts[]"]
  ```

  * you can preview in your IntelliJ
    <img width="873" alt="image" src="https://github.com/user-attachments/assets/d013336d-81f8-46ea-b33f-3f851f798ae4">
  * expected would be to preview the content [as in the website](https://docs.gradle.org/current/userguide/build_lifecycle.html)
    <img width="957" alt="image" src="https://github.com/user-attachments/assets/52120ad4-a6c5-4fe0-aa3d-3d192d3df4a6">
 
## Steps to reproduce

* Clone the repo https://github.com/gradle/gradle
* Open in your IntelliJ, the file https://github.com/gradle/gradle/blob/master/platforms/documentation/docs/src/docs/userguide/authoring-builds/basics/build_lifecycle.adoc

## Environment
* Plugin Version: 0.43.1
* IntelliJ Details: Build #IU-242.20224.387, built on August 13, 2024

## Notes
* if you want to preview it, you should avoid using `:sample`, but skipping to use their benefits

  ```
  ====
  include::../../../../snippets/buildlifecycle/basic/kotlin/settings.gradle.kts[]
  include::../../../../snippets/buildlifecycle/basic/kotlin/build.gradle.kts[]
  include::../../../../snippets/buildlifecycle/basic/groovy/settings.gradle[]
  include::../../../../snippets/buildlifecycle/basic/groovy/build.gradle[]
  ====
  ```
  <img width="871" alt="image" src="https://github.com/user-attachments/assets/e71f88fc-c349-482f-bc55-7d0c19b2882b">

**Comment by ahus1** [comment]
Thanks for reaching out and for providing an example. 

The project you're opening uses a customer project-specific Asciidoctor extension to render the preview. See https://github.com/gradle/gradle/tree/master/platforms/documentation/docs for more details. The extension used for the includes is available here: https://github.com/gradle/gradle/blob/842bb5f20974ca8fa90f352ed5be48b9005c8b5f/platforms/documentation/docs-asciidoctor-extensions-base/src/main/java/org/gradle/docs/asciidoctor/SampleIncludeProcessor.java#L76

To be able to render the preview in the IntelliJ plugin, some customizations are necessary, namely some attributes need to be set and the Asciidoctor extension needs to be provided to the preview. More background information on the concepts is described in the docs here: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctorconfig-file.html and here: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctor-extensions.html

Here are the steps that worked for me:

1. Create a file `platforms/documentation/docs/src/.asciidoctorconfig` with the following content: 
```
// essential for the SampleIncludeProcessor to work
:samples-dir: {asciidoctorconfigdir}

// additional Gradle-specific attributes to show images and render links
:snippetsPath: {asciidoctorconfigdir}/snippets
:imagesdir: {asciidoctorconfigdir}/docs/userguide/img
:groovyDslPath: https://docs.gradle.org/current/dsl
``` 

2. Build Gradle's custom Asciidoctor extension: 

```
gradlew build -p platforms\documentation\docs-asciidoctor-extensions-base
```

3. Copy the extension to `.asciidoctor/lib/gradle-docs-asciidoctor-extensions-base-8.12.jar`

4. In your IDE a notification will show when you open an AsciiDoc file to ask you if you trust the extension (you will see it every time when you restart your IDE). If you confirm, the extension will become active. 

This then shows as follows on my machine for file you linked above: 

![image](https://github.com/user-attachments/assets/addcabfc-daad-49b3-b0c3-8a13607bddd0)

I didn't try out other files. Additional customizations might be necessary to render other files in other modules.

I agree this is quite a complex setup. It is rooted in the ability of each project to specific its own file layout and custom attributes, so I would say adding a `.asciidoctorconfig` file with attributes is quite common. 

Only a few projects use extensions, still it provides a lot of power. Unfortunately the configuration of the preview is a bit more complex as described above. 

In case you are wondering if such customizations are always necessary: In the AsciiDoc world, there is the static site generator Antora, which comes with a well-defined directory layout. Thanks to the well-defined directory layout the preview works usually quite well, and fewer customizations are necessary. 

Let me know if this answers your question and if this issue can be closed.

**Comment by dancer1325** [comment]
Hi, @ahus1 
> Thanks for reaching out and for providing an example.
> 
> The project you're opening uses a customer project-specific Asciidoctor extension to render the preview. See https://github.com/gradle/gradle/tree/master/platforms/documentation/docs for more details. The extension used for the includes is available here: https://github.com/gradle/gradle/blob/842bb5f20974ca8fa90f352ed5be48b9005c8b5f/platforms/documentation/docs-asciidoctor-extensions-base/src/main/java/org/gradle/docs/asciidoctor/SampleIncludeProcessor.java#L76
> 
> To be able to render the preview in the IntelliJ plugin, some customizations are necessary, namely some attributes need to be set and the Asciidoctor extension needs to be provided to the preview. More background information on the concepts is described in the docs here: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctorconfig-file.html and here: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctor-extensions.html
> 
> Here are the steps that worked for me:
> 
> 1. Create a file `platforms/documentation/docs/src/.asciidoctorconfig` with the following content:
> 
> ```
> // essential for the SampleIncludeProcessor to work
> :samples-dir: {asciidoctorconfigdir}
> 
> // additional Gradle-specific attributes to show images and render links
> :snippetsPath: {asciidoctorconfigdir}/snippets
> :imagesdir: {asciidoctorconfigdir}/docs/userguide/img
> :groovyDslPath: https://docs.gradle.org/current/dsl
> ```
> 
> 2. Build Gradle's custom Asciidoctor extension:
> 
> ```
> gradlew build -p platforms\documentation\docs-asciidoctor-extensions-base
> ```
> 
> 3. Copy the extension to `.asciidoctor/lib/gradle-docs-asciidoctor-extensions-base-8.12.jar`
> 4. In your IDE a notification will show when you open an AsciiDoc file to ask you if you trust the extension (you will see it every time when you restart your IDE). If you confirm, the extension will become active.
> 
> This then shows as follows on my machine for file you linked above:
> 
> ![image](https://private-user-images.githubusercontent.com/3957921/378189186-addcabfc-daad-49b3-b0c3-8a13607bddd0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0MzIyMDgsIm5iZiI6MTcyOTQzMTkwOCwicGF0aCI6Ii8zOTU3OTIxLzM3ODE4OTE4Ni1hZGRjYWJmYy1kYWFkLTQ5YjMtYjBjMy04YTEzNjA3YmRkZDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjBUMTM0NTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTIyZDM2YzBiYWMzZGQwMzcwY2NkNmUyMzkwNjFiMjlhYzlkYTYyNGJhZmQ5YmRjMjliYTg3MTAwYzdjNWQ4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.Gmeq7WxI5AsgvWJJCnBZuhd0IuzcQ_SqJIgWQM9cPLE)

Thank you so much for so detailed explanation 🙏 !

> I didn't try out other files. Additional customizations might be necessary to render other files in other modules.
> 
> I agree this is quite a complex setup. It is rooted in the ability of each project to specific its own file layout and custom attributes, so I would say adding a `.asciidoctorconfig` file with attributes is quite common.
> 
> Only a few projects use extensions, still it provides a lot of power. Unfortunately the configuration of the preview is a bit more complex as described above.

🆗 , sorry for disturbing it with this issue, I was navigating through your documentation, and at first sight, I did NOT realize about it

> In case you are wondering if such customizations are always necessary: In the AsciiDoc world, there is the static site generator Antora, which comes with a well-defined directory layout. Thanks to the well-defined directory layout the preview works usually quite well, and fewer customizations are necessary.
> 
> Let me know if this answers your question and if this issue can be closed.

Sure, feel free to close it. Thanks again !

**Comment by ahus1** [comment]
I was curious if this would be working with the existing version of the plugin, and I was happy when it did!

All the best for your AsciiDoc journey!
