### ISSUE TITLE
In IntelliJ 2024.3 EAP 7, the JCEF browser preview gets stuck initializing the preview

### ISSUE THREAD

**Issue by jtiee** [asciidoctor/asciidoctor-intellij-plugin#1721]
## Observed vs. expected behavior

Observed: Opening an AsciiDoc file in a tab opens the preview pane, but it says `Initializing...` indefinitely.

Expected: Opening an AsciiDoc file in a tab opens the preview pane, and the AsciiDoc preview renders.

## Steps to reproduce

1. Update to IntelliJ 2024.3 EAP 7.
2. Make sure the AsciiDoc plugin is installed and enabled.
3. Open an AsciiDoc file.

## Environment

Plugin Version: 0.43.1

IntelliJ Details: IntelliJ IDEA 2024.3 EAP (Ultimate Edition)
Build #IU-243.21155.17, built on October 22, 2024
Licensed to IntelliJ IDEA EAP user: me
Expiration date: November 21, 2024
Runtime version: 21.0.4+8-b631.2 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.0.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192M
Cores: 10
Metal Rendering is ON
Registry:
  ide.browser.jcef.gpu.disable=true
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (243.21155.22)
  com.maaxgr.intellij.jsonviewer (1.0.19)
  IdeaVIM (2.17.0-eap.1)
  org.jetbrains.plugins.go (243.21155.17)
  org.jetbrains.plugins.ruby (243.21155.17)
  com.intellij.grazie.pro (0.3.343)
  PlantUML integration (7.11.2-IJ2023.2)
  org.asciidoctor.intellij.asciidoc (0.43.1)
  com.dmarcotte.handlebars (243.21155.22)
  com.jetbrains.php (243.21155.17)
Kotlin: 243.21155.17-IJ

**Comment by ahus1** [comment]
I'm trying to reproduce it on Linux. I see this happening when I first open an AsciiDoc editor. Once I close it and open it again, the preview is there. 
How does it look for you?

**Comment by ahus1** [comment]
There is now pre-release 0.43.2 of the plugin which includes a change which should fix the issue you described, although I am not 100% sure if that what I observed was the same problem you observed.

Please give this preview release a try an let me know if it works for you. 


The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by jtiee** [comment]
I've tried 0.43.2, and it works well. Thanks for fixing the issue so quickly!

Before I filed this issue, I did once see that closing and re-opening an editor would start the preview correctly. After that one instance, the plugin got stuck in `Initializing...` every time.

**Comment by ahus1** [comment]
Thank you for testing it, and I'm glad it works. I'm closing this issue now, and I am promoting the preview to a real release.
