### ISSUE TITLE
No error for missing image in a different Antora module

### ISSUE THREAD

**Issue by Grolribasi** [asciidoctor/asciidoctor-intellij-plugin#1727]
## Observed vs. expected behavior

When referring to a nonexistent image, there is usually an error. That's correct. 
But when referring to a nonexistent image in a different module, there is no error. That's not correct, there should be an error.

## Steps to reproduce

1. Create Antora component structure with at least two module folders. For example, module 1: "admin" and module 2: "user".
1. On a page from a module refer to a nonexistent image from the second module For example, in module "user" refer to an image from module "admin" like so: `image::admin:install.png[]`.
2. The image is not displayed in the preview area because it doesn't exist, but there is no error report "file doesn't resolve" for a missing image, you won't know the image is missing before you build the site.

## Environment

Plugin Version: 43.2

IntelliJ Details: 2024.2.4 Community

**Comment by ahus1** [comment]
Thank you for noticing this. I had a look and found that the regex I used identified the body as a URL due to the colon used in there. I update the plugin and the next version will be more restrictive and will recognize the error unless you would name a module `data` or `mailto`. 

I'll update this issue once a pre-release is available.

**Comment by ahus1** [comment]
Pre-release 0.43.4 now contains a fix for this, please give it a try. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
