### ISSUE TITLE
Antora includes don't work when component descriptor is incomplete

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#1728]
_Originally posted by @Uriziel47 in https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/967#issuecomment-2453300016_
            
 I also faced this kind of issue with "Unresolved Antora Reference: include::example$...". 
After digging in the code I realized. I forgot to add the required fields in the _antora.yml_, naming:

- name
- version

After adding these fields the include shows the expected output.

FYI:
Code analysis _antora.yml_ having not the required fields _name_ and _version_.

AntoraIncludeAdapter::process
 ```
if (localModule != null) {
  target = AsciiDocUtil.replaceAntoraPrefix(project, localModule, sourceDir, target, "page", "include").get(0);
}
```

AsciiDocUtil::replaceAntoraPrefix
_otherDirs_ are empty 
```
List<VirtualFile> otherDirs = getOtherAntoraModuleDir(project, moduleDir, myModuleName, myComponentName, myComponentVersion, otherComponentVersion, otherComponentName, otherModuleName);
List<String> result = new ArrayList<>();
for (VirtualFile otherDir : otherDirs) {
```

AsciiDocUtil::getOtherAntoraModuleDir
_otherComponentName_ is set to _myComponentName_ which is _null_, so the last if-statement is been skipped, which results in
empty list as return value.
```
if (otherComponentName == null && otherModuleName == null) {
  otherComponentName = myComponentName;
  otherModuleName = myModuleName;
}

if (otherComponentName != null) {
```

_myComponentName_ is set in AsciiDocUtil::replaceAntoraPrefix
```
String myComponentName = getAttributeAsString(antora, "name");
String myComponentVersion = getAttributeAsString(antora, "version");
```

**Comment by ahus1** [comment]
Hi  @Uriziel47 - thank you for sharing this scenario. 

At the moment, the plugin should show an error in a YAML file if the required version name is missing. The YAML plugin is enabled by default AFAIK. See below for an example.

![image](https://github.com/user-attachments/assets/59c1f241-e833-4302-8822-0ff6177ae7d3)

I wonder how a better heuristic or behavior could look like.

**Comment by ahus1** [comment]
I did some thinking, and maybe an editor notification can help. The ones below will show on the Antora component descriptor that is missing a name, and also on all AsciiDoc files inside of that module. The latter will also provides a hit to take the user to that file. Let me know what you think. It will be part of the next version of the plugin.

![image](https://github.com/user-attachments/assets/c8300025-9dbb-4f86-8065-6dde98ae3aa4)

![image](https://github.com/user-attachments/assets/4399526b-8300-4dbb-b3d3-322d4ad9323a)

**Comment by ahus1** [comment]
The change is now part of pre-release 0.43.3. Please give it a try and let me know your thoughts. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by Uriziel47** [comment]
Wow this was a very fast feedback!

I personally thought of a warning in the code block and using a placeholder for the name. But this comes with the risk of just ignoring, or even not recognizing, the warning. Leading to issues later.

So I prefer (and like) your solution. Because you are forced to do something.
I also like the developer experience with the provided links. Speaking: _Read more..._ and _Open 'antora.yml'_.

Thank you very much!

**Comment by ahus1** [comment]
Thank you for your feedback, and I'm glad you like it. Closing this is as resolved.
