### ISSUE TITLE
Headline Color in Darcula Theme

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#173]
AsciiDoc Plugin Version: 0.17.3

IDE Name and Version: IntelliJ IDEA 2017.1
Build #IC-171.3780.107, built on March 22, 2017
JRE: 1.8.0_112-release-736-b13 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

When using the dacular theme, it seems that only the background color changes but the link and headline color stays the same. This makes the headlines hard to read:

```
== a title
http://google.de[a link]
text
```
![dacula](https://cloud.githubusercontent.com/assets/1856308/24773072/fc60217e-1b13-11e7-89ff-8547b32f3ac1.png)

**Comment by mojavelinux** [comment]
I agree this needs to be fixed. To move this forward, it might be helpful to take a screenshot of the Darcula theme for the Markdown plugin (or similar) so we can be consistent.

**Comment by rdmueller** [comment]
This is the example created with the Markdown plugin:

```
## a title

[a link](http://example.com) text
```

![image](https://cloud.githubusercontent.com/assets/1856308/24775061/a68a83c2-1b1b-11e7-973e-549133944452.png)

quite different... :-)

**Comment by mojavelinux** [comment]
Thanks!

That color value is #CCCCCC.

**Comment by mojavelinux** [comment]
Here's the declaration needed in darcula.css:

```
h1,h2,h3,#toctitle,.sidebarblock>.content>.title,h4,h5,h6{color:#cccccc}
```

**Comment by mojavelinux** [comment]
The same would need to be done for links inside of those elements as well.

**Comment by ahus1** [comment]
Version 0.18.2 is available as a preview from the [Github Releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases). Please let me know if this fixes this issue or if anything else needs to be changed.

**Comment by rdmueller** [comment]
sorry for the delays.
The headlines are now much more readable!
