### ISSUE TITLE
JCEF Browser not working in Intellij

### ISSUE THREAD

**Issue by christlang** [asciidoctor/asciidoctor-intellij-plugin#1730]
## Observed vs. expected behavior

I open an adoc-file and the preview stays black with the JCEF Browser
![image](https://github.com/user-attachments/assets/3d3466f0-fe71-4a3b-97ef-f30318180b85)

in the swing Browser it is rendered
![image](https://github.com/user-attachments/assets/c447ec9d-7127-44b6-a68b-9df5c12bc9de)

I would expect to see the preivew in the JCEF Browser

## Steps to reproduce

just open an adoc file

I updated to latest AsciiDoc-Plugin and restarted the IDE several times without success.

## Environment

Plugin Version: 0.43.2

IntelliJ Details: 
IntelliJ IDEA 2024.2.4 (Ultimate Edition)
Build #IU-242.23726.103, built on October 23, 2024
Licensed to synyx GmbH & Co. KG / Christian Lange
You have a perpetual fallback license for this version.
Subscription is active until September 28, 2025.
Runtime version: 21.0.4+13-b509.26 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.11.3-200.fc40.x86_64
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4000M
Cores: 16
Registry:
  debugger.watches.in.variables=false
  analyze.exceptions.on.the.fly=true
  ide.experimental.ui=true
  i18n.locale=
  scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins:
  com.intellij.ml.llm (242.23726.20)
  org.jetbrains.plugins.go-template (242.20224.155)
  com.intellij.properties.bundle.editor (242.22855.32)
  name.kropp.intellij.makefile (242.23726.16)
  Pythonid (242.23726.103)
  PythonCore (242.23726.103)
  org.jetbrains.plugins.ruby (242.23726.38)
  org.intellij.plugins.hcl (242.23339.11)
  com.haulmont.jpab (242.22855.36)
  PlantUML integration (7.11.2-IJ2023.2)
  com.jetbrains.space (242.23726.16)
  de.docs_as_co.intellij.plugin.diagramsnet (0.2.6)
  dev.meanmail.plugin.nginx-intellij-plugin (2024.3)
  com.mnr.java.intellij.idea.plugin.base64helper (2.0.3)
  net.sjrx.intellij.plugins.systemdunitfiles (223.241106.306)
  org.asciidoctor.intellij.asciidoc (0.43.2)
  dev.flikas.idea.spring.boot.assistant.plugin (0.14.4)
  org.sonarlint.idea (10.12.0.79769)
  io.pivotal.jasmine (1.9)
  io.plugin.tsnode (2024.08.16-1)
  com.jetbrains.php (242.23726.107)
  de.timo_reymann.intellij-mjml-support (3.6.0)
  org.intellij.scala (2024.2.29)
  net.ashald.envfile (3.4.2)
Kotlin: 242.23726.103-IJ
Current Desktop: GNOME

**Comment by ahus1** [comment]
Hi, the situation you describe sounds similar to what I was working on in #1610

Can you please try out plugin version 0.43.3 which will be a bit more aggressive in clearing the left-over chromium lock files?

**Comment by christlang** [comment]
Hello, 
sorry for not responding. I overlooked you comment.
With Version 0.43.3 everything seems to be okay again
