### ISSUE TITLE
Use highlight.js for Antora projects by default

### ISSUE THREAD

**Issue by rocec** [asciidoctor/asciidoctor-intellij-plugin#1736]
## Current state

Antora uses highlight.js for source code highlighting. The IntelliJ AsciiDoc plugin preview defaults to Coderay. This leads to differences between preview and Antora output.

For example:
```
[source,python]
----
import pandas as pd
----
```

In the IntelliJ preview:
![image](https://github.com/user-attachments/assets/d0e35e6a-dacd-4246-8e76-305fdff87eeb)

Antora site:
![image](https://github.com/user-attachments/assets/c17360de-fc84-44e8-ba09-93ac9a6ef33d)

## Proposal

Use highlight.js by default if the plugin detects that it is working in an Antora project. This will make the preview match Antora's output even more closely.

**Comment by ahus1** [comment]
Thank you for this suggestion. This change is included in the next release. I'll update this issue once a preview release is available.

**Comment by ahus1** [comment]
A new pre-release 0.43.5 is now available that includes this fix. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
