### ISSUE TITLE
Codeblock and Newlines in generated PDF

### ISSUE THREAD

**Issue by 3XC1T3D** [asciidoctor/asciidoctor-intellij-plugin#1739]
Hi,

I am wondering if there is a possibility to configure the plugin that notices me, when the 82 characters are reached inside the codeblock, so a newline in the generated pdf output isnt made. I hope, my question is understandable. 

Do you have some hints?

**Comment by ahus1** [comment]
Thanks for reaching out. There is nothing out of the box, still I share some ideas that might help you. 

The most light-weight way is to configure either the hard-wrap or a visual rule at a specific number of characters. Still, this will not be specific for code blocks, but for all contents in a file. When using an `.editorconfig` file, you can limit this to only AsciiDoc files, still it wouldn't target code blocks. 

![image](https://github.com/user-attachments/assets/a4b2fec6-9c55-43b5-9140-b99d767d9edd)

An alternative on the other side of the spectrum could be an Asciidoctor extension (possibly of the type [Tree Processor](https://docs.asciidoctor.org/asciidoctor/latest/extensions/tree-processor/)) where you at the time of conversion log an error specific to that line number. If you enable it at build time, and combine it with the Asciidoctor options to break the build when there is an error, you will generate a PDF without line breaks, or no PDF at all. You can even [hook that extension to the AsciiDoc plugin IntelliJ](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctor-extensions.html) to see the errors in your editor when writing. 

Let me know if one of this could help you in your situation.

**Comment by 3XC1T3D** [comment]
Hi @ahus1

luckily you understood my 'problem' 😅 thank you very much for the tips!

I will take a look how i can configure a visual rule in the .editorconfig - i think that's the easiest way.

Am i understanding it right, that the extension you are suggesting, actually doesn't exist? And it could be a solution in the future?

best regards

**Comment by 3XC1T3D** [comment]
added .editorconfig file for visual guide in asciidoc files

**Comment by ahus1** [comment]
Thank you for adding the example, looks good. 

And about the Asciidoctor extension: There is no such extension yet that I am aware of. As it seems to be a very custom extension for your use case, such an extension  will not exist unless you write it (or you motivate someone else to write it for you).
