### ISSUE TITLE
Support for collapsing text blocks

### ISSUE THREAD

**Issue by marcschumacher** [asciidoctor/asciidoctor-intellij-plugin#174]
Currently there is no support to collapse text blocks. It would be helpful to be able to collapse text blocks which are on the same level or lower.

AsciiDoc Plugin Version: 0.17.3

IDE Name and Version: IntelliJ IDEA 2017.1.1

**Comment by Tejeev** [comment]
THIS

**Comment by ahus1** [comment]
I've added a folding for sections and blocks starting from version 0.26.3. I attach a screenshot at the end of this comment. The folded version uses the title of the section and the block (if available). If you fold a section, all its subsections will be part of the fold.

This version is available as a pre-release from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases). Please download and install it manually. 

There are several other changes included in this pre-release as well. Please have a look at the [CHANGELOG](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CHANGELOG.adoc) before upgrading.

Please provide feedback in this ticket if this works for you.

Unfolded:
![folding](https://user-images.githubusercontent.com/3957921/57912983-e9cfae80-788b-11e9-82c6-e63bed5b7cc7.png)

Folded:
![folding2](https://user-images.githubusercontent.com/3957921/57912984-e9cfae80-788b-11e9-97ec-cda44c78c343.png)

**Comment by ahus1** [comment]
Version 0.26.7 is now available from the jetbrains plugin repository.
