### ISSUE TITLE
plantuml `!include` not working

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-intellij-plugin#175]
*AsciiDoc Plugin Version:*
0.17.3

*IDE Name and Version:*
IntelliJ IDEA 2016.3.6
Build #IU-163.15188.11, built on March 24, 2017
JRE: 1.8.0_111-b14 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

*Issue description*
When I use the plantuml `!include` directive in a diagram block, the diagram-preview fails and shows the following text.

![image](https://cloud.githubusercontent.com/assets/5781153/25012667/84951e5c-2071-11e7-9969-24ed5505713e.png)

*Expected behaviour*
Should display the diagram correctly as if the contents of the included file were on the same plantum block.

*Severity (at least for me)*
Minor

*Notes*
I confirmed using the maven plugin, that the issue comes from the Asciidoctorj-diagram contained (version 1.5.0), with last version (1.5.4) this is fixed.
However, I am not sure this is enough, the includes are resolved relative to the AsciiDoc document. Unless this is taken into consideration, it won't work property.
Also, the plugin uses Asciidoctorj 1.5.4.1, last is 1.5.5. Does it make sense to you for a new release?

**Comment by ahus1** [comment]
@abelsromero - there is a preview version 0.18.0 of the plugin available from the [github releases page](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases). 

This includes already the versions asciidoctorj-diagram 1.5.4 and Asciidoctorj 1.5.5.

A small include example worked for me. Please give it a try. If it doesn't work, please post a small source code snippet that shows what doesn't work for you.

**Comment by abelsromero** [comment]
Works perfectly for me! :+1:

**Comment by tja-m** [comment]
I have a similar problem but with a different error message:

```
ERROR uri:classloader:/gems/asciidoctor-2.0.15/lib/asciidoctor/parser.rb:build_block: .../package1-classes.puml:0 Failed to generate image: PlantUML preprocessing failed: [From  (line 4) ]
@startuml 'https://plantuml.com/class-diagram 
!include classes/Class1.puml!0 
^^^^^ cannot include classes/Class1.puml
```

Sometimes it happens, sometimes it doesn't, when trying to render a PDF. Somtimes preview is broken. I cannot exactly tell, what triggers which behaviour. Only it seems, that opening the diagrams in PUML editor seems to help fixing broken display in preview.

Example attached

[asciidoctor-intellij-puml-include-v2.zip](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/6854692/asciidoctor-intellij-puml-include-v2.zip)
