### ISSUE TITLE
Theme may should not used with PDF-Button-Execution

### ISSUE THREAD

**Issue by HaLo1701** [asciidoctor/asciidoctor-intellij-plugin#1750]
## Observed vs. expected behavior

When I am using the button to generate a PDF, it seems to be, that the theme is not used since one of the last updates.

![grafik](https://github.com/user-attachments/assets/dac40eb2-60b0-48e1-9600-e72f6a33e6dd)

When I am using the command

asciidoctor-pdf -a pdf-themesdir=themes -a pdf-theme=basic -a compress -r asciidoctor-diagram HURIMS-119.adoc

it works:

![grafik](https://github.com/user-attachments/assets/eed6aecd-28cd-4e12-a43c-a6fc67fc04f9)

## Steps to reproduce

Try the PDF-Button or the command in a terminal window.

I am not sure since when the problem exists. By my colleague it still works with an older version.

If I have to give more information, let me know.

Many thanks in advance.

## Environment

Plugin Version: 0.43.4

IntelliJ Details:

IntelliJ IDEA 2024.3.1.1 (Ultimate Edition)
Build #IU-243.22562.218, built on December 18, 2024
Licensed to nextN GmbH / Hans Lohuis
Subscription is active until September 28, 2025.
Runtime version: 21.0.5+8-b631.28 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
Kotlin analyzer version: 2.1.20-ij243-27
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192M
Cores: 28
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
  ide.slow.operations.assertion=false
  i18n.locale=
  ide.images.show.chessboard=true
Non-Bundled Plugins:
  com.jetbrains.plugins.ini4idea (243.22562.180)
  com.fuhrer.intellij.jump (1.6)
  Batch Scripts Support (1.0.13)
  light.flat.theme (0.14)
  com.khmelyuk.multirun (1.14.1)
  youngstead.relative-line-numbers (1.1.1)
  manjaro.mpb (1.9)
  MultiHighlight (3.2.0)
  de.netnexus.camelcaseplugin (3.0.12)
  GsonFormatPlus (1.6.1)
  org.jetbrains.jumpToLine (0.1.17)
  org.01pawn.rainbow-variable (1.3)
  PlantUML integration (7.11.2-IJ2023.2)
  com.haulmont.jpab (243.22562.145)
  com.jetbrains.jax.ws (243.21565.129)
  com.antoshk.jsf-el-extension-plugin (0.2.3.1)
  dev.pnbarx.idea.treecolor (1.2.2)
  com.intellij.javaee.webSocket (243.22562.13)
  AceJump (3.8.19)
  DuplicateLines (1.0.1)
  indent-rainbow.indent-rainbow (2.2.0)
  de.andrena.tools.altn8-th (1.0.6)
  com.intellij.javaee.ejb (243.22562.13)
  org.asciidoctor.intellij.asciidoc (0.43.4)
  com.example.JumpingLines (2.2)
  MavenRunHelper (4.29.0-IJ2022.2)
  com.intellij.jsf (243.21565.129)
  com.intellij.javaee.batch (243.21565.129)
  com.github.copilot (1.5.30-242)
  com.nasller.CodeGlancePro (1.9.4)
  com.bruce.intellijplugin.generatesetter (2.8.4)
  com.liferay.ide.intellij.plugin (2.1.1)
  izhangzhihao.rainbow.brackets.lite (1.2.0)
  zielu.gittoolbox (600.0.11+243)
  com.pyfox.pps (2.0.0)
Kotlin: 243.22562.218-IJ

**Comment by ahus1** [comment]
Hi - thanks for reaching out. The AsciiDoc plugin picks up theme using attributes in the document or in an `.asciidoctorconfig` file. 

Assuming the source used for the screenshot is not publicly available, can you please provide a minimal reproducer and attach it to this issue as a ZIP file or publish it as an example repository on GitHub?

**Comment by ahus1** [comment]
Ok, I think I can reproduce it locally, no need to provide an example. Will have an update on this one soon.

**Comment by ahus1** [comment]
I found at https://docs.asciidoctor.org/pdf-converter/latest/theme/apply-theme/ that you should use an absolute path to point to the theme folder if possible. 

It seems that when creating the PDF from the IDE, there is a different working directory compared to when you run it from the CLI. 

I also remember it worked earlier without that change, not sure why and when. Once I changed it in my example https://github.com/ahus1/asciidoctor-deepdive/commit/07de87ea4d1383534cced7859bbf3f3847d3a87c it started to work again. 

I'll update the docs and examples in the plugin's documentation accordingly.

**Comment by ahus1** [comment]
See 860318abc7d70d9abb17f0e1b7d4cdbfa9e49175 for the docs update. Please let me know if adding `{docsdir}` works for you.

**Comment by HaLo1701** [comment]
Hi,
unfortunately, specifying the directory does not work.
The PDF is no longer generated with this specification.
I have attached an example as a zip file.
[Test mit InelliJ.zip](https://github.com/user-attachments/files/18206917/Test.mit.InelliJ.zip)

The file Featuretest.adoc contains the example.

**Comment by ahus1** [comment]
Thank you for providing the sample. When trying it locally, there was an error in the Notifications pointing me to also add it for the fonts. 

Once I changed it to 

```
:pdf-fontsdir: {docdir}/fonts
```

It started to work. I'll update the docs accordingly. 

BTW, it seems that there ways a Kroki timeout when rendering the images, so the first rendering took a bit longer this morning :-)

Let's me know if this is then resolved for you.

**Comment by HaLo1701** [comment]
Wow, yes thats works.

Thank you for your fast help and reply.

Merry christmas.

**Comment by ahus1** [comment]
Thank you for the fast feedback! The docs are now updated for the fonts as well, and the IDE's templates will be update in next patch release. Happy holidays!
