### ISSUE TITLE
点击文件中的链接定位失败

### ISSUE THREAD

**Issue by qzzsunly** [asciidoctor/asciidoctor-intellij-plugin#178]
在预览界面中点击文件中的相对路径，会以编辑器的目录为根目录，不是以文件所在的位置作为根目录，导致定位失败。

**Comment by ahus1** [comment]
Hi @qzzsunly, the language for issues is English, as it is the common language for contributors from various countries. 

When submitting a bug report, please always include the version of your IDE and the version of the plugin. Please also provide a minimal asciidoc example and/or a screen shot.

**Comment by ahus1** [comment]
I can't analyze this ticket without further information. I'm closing this ticket due to inactivity.
