### ISSUE TITLE
Relative links to other asciidoc files

### ISSUE THREAD

**Issue by JerryShea** [asciidoctor/asciidoctor-intellij-plugin#180]
Hi,
thanks for the plugin!
Right now it seems that the plugin does not handle relative links to asciidoc files. From following the instructions I found in http://asciidoctor.org/docs/user-manual/#navigating-between-source-files I have a solution that works well in github (actually those instructions are a little out of date - you don't need the ifdef).
You can see the solution working in https://github.com/jerry-shea-hft/asciidoc_plugin_relative_links
When I checkout that repo locally and look at the .adocs in IntelliJ, and click on either of the links in readme.adoc then a browser window pops up and it tries to open afile.html.
Is it possible for the plugin to navigate to the afile.adoc instead? i.e. is it possible for the plugin to behave like github does?
Thanks, Jerry

AsciiDoc Plugin Version: 0.18.1

IDE Name and Version: 
IntelliJ IDEA 2017.1.3
Build #IC-171.4424.56, built on May 12, 2017
JRE: 1.8.0_112-release-736-b21 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.10.0-21-generic

**Comment by mojavelinux** [comment]
We did something similar for the chrome plugin. See https://github.com/asciidoctor/asciidoctor-chrome-extension/pull/48.

**Comment by ahus1** [comment]
There is now a pre-release 0.25.4 available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases).

Thanks to PR #256 by @bbrenne, clicking on a link the preview on the right will lead to the referenced AsciiDoc file. The work to make references clickable in the editor continues in ticket #204

The follow type of references work: 

```
<<reffile#id>>

link:reffile.adoc[]

link:reffile.html[]

link:reffile[]

link:reffile.adoc#id[]

link:reffile.html#id[]

link:reffile#id[]
```

Please give it a try. If this works for you, or if you experience problems, please leave a comment in this issue.

**Comment by JerryShea** [comment]
Yes that solved this issue - thanks very much!
