### ISSUE TITLE
add icon font support

### ISSUE THREAD

**Issue by matthiasbalke** [asciidoctor/asciidoctor-intellij-plugin#182]
AsciiDoc Plugin Version: 0.18.1

IDE Name and Version: 
```IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017
Licensed to ****** / Matthias Balke
Subscription is active until November 19, 2017
JRE: 1.8.0_112-release-408-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

*Bug Description*
When using icon font, the preview doesn't display anything.

*Expected Behavior*
The icon font should be rendered in the Java FX preview pane.

*Example Code*
```adoc
:icons: font

// display an checked checkbox
icon:check-square-o[]
```

**Comment by ahus1** [comment]
Hi, thanks for reporting this. 

the reason for this is that the icon fonts are not bundled with the current plugin. To enable offline use, the font would need to be bundled. 

Do you want to give it a try and provide a pull request? AFAIK the license of Font Awesome allows re-distribution. 

You can place font files next to scrollToElement.js. The HTML forwarded to JavaFX is created inside JavaFxHtmlPanel. Actually only the HTML body is created by AsciiDoctor, while the headers are static (this avoids referencing remote resources and allow replacing them with i.e. a local, JavaFX related CSS. I think it would be OK to include the fonts in the HTML all the time independent of `:icons: font`

I hope JavaFX works OK with font files - sometime it has some nasty habbits that need workarounds.

**Comment by ahus1** [comment]
Version 0.19.0 now available from Jetbrains plugin repo - and no longer marked as "preview". 

Thanks again for contributing!
