### ISSUE TITLE
Add Hints for encourage use of JetBrains JDK and 64bit JDK

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#189]
Users should get a hint (like the JavaFX hint) to use JetBrains JDK instead of the platform's JDK for better compatibility and for example HiDpi support (see #187)

Also users should be hinted to use a 64bit JDK to be able to use JavaFX preview.

From 2017.1 onwards 64bit Java is included even in the Windows versions. See https://intellij-support.jetbrains.com/hc/en-us/articles/206544879-Selecting-the-JDK-version-the-IDE-will-run-under for more information.

**Comment by rdmueller** [comment]
see also #223 
I wonder if there is a way that the plugin detects the slow repaint itself...

afaik, the current IntelliJ installer already brings its own JetBrains 64bit JDK, so it would be interesting to know how likely it is that someone is running on a different JDK.

**Comment by ahus1** [comment]
Looking at #231, this is apparently quite likely on Linux OS, as users hat the choice to install with or without JetBrains JDK. The next upcoming version will have an editor notification.
