### ISSUE TITLE
Support imagesDir in plugin configuration

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#190]
as reported on the pulgin's homepage (05.04.2017 03:08:28)

I have a document's tree like src/main/asciidoc/images image1.png image2.png src/main/asciidoc/part1 part1.adoc src/main/asciidoc/part2 part2.adoc asciidoctor-maven-plugin has a settings "imagesDir" (this settings could'not be switched off and by default it is "images"), that will append imagesDir to all images path. each adoc file contains images So now i have a choise - will i see images in plugin's preview: i should set image's link as image::../images/image1.png[] either i will see images in generated file. image::image1.png[] Will be nice to have some plugin's settings like 'imagesDir', that will fix it

**Comment by mojavelinux** [comment]
The approach I tend to take on this is to set the attributes in the current document for the standalone / editor / preview environment. Then, I pass an override value when converting the documents using an external tool or pipeline that is specific to that environment.

In other words, I use:

```
= Document Title
ifndef::imagesdir[:imagesdir: images]
```

(other conditions work too, like ifndef::env-site).

Then I might call Asciidoctor using:

```
asciidoctor -a imagesdir=custom/path/to/imagesdir doc.adoc
```

This strategy works out pretty well. So that I don't have to define imagesdir in every document, I tend to use an include that contains these assignments (which may itself be an include).

```
= Document Title
include::_attributes.adoc[]
```

**Comment by mojavelinux** [comment]
> Will be nice to have some plugin's settings like 'imagesDir', that will fix it

The problem with setting anything global is that this path is contextual. It depends on which project you are in and where the source file is within the project tree. That's why my suggestion is better. You manage the path to the images catalog (imagesdir) in each directory that contains AsciiDoc source files. (In other words, where am I in relation to the images catalog).

A plugin like Maven sees the whole project and can set the imagesdir accordingly, perhaps even for each file it processes.

**Comment by ahus1** [comment]
I see your point Dan, that a global setting will not solve the problem. But I also understand the situation to have a big document with lots of files and you don't want to clutter them all with settings (or even a single include) - it disturbs the ZEN of writing.

Sometimes I think about a dot-file like .asciidoc for configurations that will affect the files in subdirectories like .gitignore works. Just a pity that it's too hard to determine the root. 

Of the things you suggest I like the ifndef solution best for now. Will try it.

**Comment by mojavelinux** [comment]
We can definitely consider an implicit include file that contains header attributes and other metadata. That might be covered by https://github.com/asciidoctor/asciidoctor/issues/566.

**Comment by mramendi** [comment]
While @mojavelinux comment , or at least asciidoctor/asciidoctor#566 , seems to apply specifically to command-line asciidoctor runs, I would suggest something might be needed to make the need for includes less strong in the IntelliJ preview plugin.

My suggestion would be a generic one. Create a configuration setting for the plugin that would allow setting any asciidoc attribute for rendering. This icludes the imagesdir attribute.

**Comment by mojavelinux** [comment]
You might want to have a look at how both the Chrome and Atom extensions are handling this. They offer a configuration screen for setting AsciiDoc attributes globally. I wouldn't be opposed to the idea of supporting a project-level configuration file (perhaps in AsciiDoc) where you can set attributes globally. We don't yet have a convention for this, so feel free to play with ideas.

**Comment by mramendi** [comment]
@mojavelinux yes, the Atom configuration style is exactly what I'd like to see. 

I would appreciate hints about how to create this configuration field in the plugin configuration screen. Setting AsciiDoctor attributes is the easy part - my problem is with editing the configuration form (never dealt with this before). Would really appreciate some hand-holding here (on IRC?)

**Comment by ahus1** [comment]
Thanks to @jrmax and PR #216 you can now configure any configuration parameter in the plugin settings. This will allow you to configure a configuration variable globally within your IDE.

This is included in version 0.21.1 that I've published in the plugin repository some minutes ago.

I close this ticket for now. If there's another need please open a new issue or a pull request.

I'm still looking forward for https://github.com/asciidoctor/asciidoctor/issues/566 - a common file that holds project specific settings that I could check in to version control.

**Comment by mojavelinux** [comment]
> I'm still looking forward for asciidoctor/asciidoctor#566 - a common file that holds project specific settings that I could check in to version control.

I'd encourage you to move forward with this idea ahead of core. Once in core, it becomes permanent, so it's usually best to play with it outside of core first so we figure out what we want.

I'd just use a simple config schema much like is proposed in the issue (and is found in the AsciiDoc plugins for Jekyll and Middleman).

As for the configuration file name, you could either make it configurable, or name it something like asciidoctor-config.yml.

**Comment by ahus1** [comment]
Hello @mojavelinux - thanks for the encouragement. I've collected my thought here #220. I'm not so fond of YML files, let's see and continue the discussion in the new issue.

**Comment by mojavelinux** [comment]
Excellent. And by all means, use a format you think best suits the ecosystem.

**Comment by ahus1** [comment]
Anyone watching this ticket might be interested in experimental support of per-project configuration files that is part of the pre-prelease 0.22.0 available on the project's Github releases page. 

See https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-project-specific-configurations for details.
