### ISSUE TITLE
Converting markdown to ascii doctor

### ISSUE THREAD

**Issue by mattadamson** [asciidoctor/asciidoctor-intellij-plugin#192]
Hi

I'm very interested in understanding the code you use to parse and convert from Markdown to Asciidoctor.  I'd actually like to do this in bulk on a collection of files in one go and could extract the code into a script to call. This is required  because the tool https://www.npmjs.com/package/jsdoc-to-markdown will generate markdown but not ascii doc files from jsdoc output

Thanks

Matt

**Comment by ahus1** [comment]
Mi Matt, 

this project uses a library https://github.com/bodiam/markdown-to-asciidoc by @bodiam

If this answers your question, please close the ticket.

Regards, Alexander

**Comment by bodiam** [comment]
Hi Matt,

Also have a look at this one: https://atom.io/packages/markdown-to-asciidoc

Someone used a JavaScript Java wrapper around my library. It might help you further.

Cheers,

Erik

**Comment by ahus1** [comment]
@mattadamson I hope the two replies answered your question. If not, please re-open the issue.
