### ISSUE TITLE
Weird cursive font in JavaFX Preview

### ISSUE THREAD

**Issue by minosniu** [asciidoctor/asciidoctor-intellij-plugin#195]
AsciiDoc Plugin Version: 0.19.1

IDE Name and Version: IntelliJ IDEA 2017.2.5
Build #IU-172.4343.14, built on September 26, 2017
JRE: 1.8.0_152-release-915-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

The font is rather weird and I found nowhere to change it. This makes the preview barely readable.

![shell-examples_readme_adoc_-_vertx-examples_-____code_try-vertx-examples_](https://user-images.githubusercontent.com/109286/31858399-4ae37d94-b729-11e7-84c3-de6d3e0461bd.png)

**Comment by ahus1** [comment]
Asciidoc uses CSS to style the preview. It tries to find the following fonts (in this order):

1. Noto Serif
2. DejaVu Serif
3. serif

with the third option being any standard with "serifs". It seems that your computer translates the third option to this font. 

Could you please have a look into your font list?

An option might be to install DejaVu fonts from this site: https://dejavu-fonts.github.io/

This way it will not default to any serif font, but use the DejaVu fonts. 

Please give it a try.

**Comment by ahus1** [comment]
closed due to inactivity.
