### ISSUE TITLE
On wrap, sometimes the line starts with a space

### ISSUE THREAD

**Issue by znerd** [asciidoctor/asciidoctor-intellij-plugin#196]
Steps to reproduce:
1. Enable wrapping, e.g. at column 80.
2. Type multiple lines of text.

Expected results:
1. Lines wrap at the configured column (e.g. 80).
2. The next line never starts with a space.

Actual results:
1. Lines indeed wrap at the configured column (e.g. 80).
2. The next line sometimes starts with a space.

Extra information:
- AsciiDoc Plugin Version: 0.19.1
- IDE Name and Version: IntelliJ IDEA 2017.2.5
Build #IU-172.4343.14, built on September 26, 2017
JRE: 1.8.0_152-release-915-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by ahus1** [comment]
The recommended best practice for AsciiDoc is to have one line per sentence. This allows you to move around sentences in your document easily. It also avoids re-formatting the document which would lead to difficult to merge/track changes when using version control.

IntelliJ users enable "soft wraps" and disable "wrap on typing" for this. Please give it a try. 

To answer your original question: The "wrap when typing" option in IntelliJ seems to work like described in your "actual results". I tried this with a normal text editor: When you are at position "80" and press space, IntelliJ starts a new line and puts the space at he beginning.  This has nothing to do with the AsciiDoctor plugin and there is no way to change this for me as far as I know. If you know an open source plugin that behaves differently, please point me to the plugin.

**Comment by ahus1** [comment]
closed due to lacking feedback.
