### ISSUE TITLE
Spinning beach ball in AsciiDoc plugin 0.19.1 in IDEA 2017.2.6

### ISSUE THREAD

**Issue by znerd** [asciidoctor/asciidoctor-intellij-plugin#197]
AsciiDoc Plugin Version: 0.19.1

IDE Name and Version: IntelliJ IDEA 2017.2.6
Build #IU-172.4574.11, built on November 13, 2017
Subscription is active until January 10, 2018
JRE: 1.8.0_152-release-915-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1

Since I upgraded to to IDEA 2017.2.6, I get a spinning beach ball each and every time I open an AsciiDoc file. So then I have to Force Quite IDEA.

When I disable the plugin, it's fine again.

**Comment by ahus1** [comment]
I've update to 2017.2.6 as well and tried 0.19.1 and 0.19.2 - both work for me with my asciidoc files (on windows at least). I need some additional information from you to analyze this further.

Could you please create a minimal asciidoc file that reproduces the error?

Are you using Swing or JavaFX as preview?

Thanks!

**Comment by znerd** [comment]
I was using JavaFX.

**Comment by ahus1** [comment]
I've read the issue #198 you opened. I got two questions: 
* is this still a problem?
* can you please provide a minimal asciidoc file that reproduces the error?

**Comment by znerd** [comment]
It's still happening, even after a restart; (accidentally, even) I clicked on a README.adoc file and IntelliJ just froze.

![screenshot](https://user-images.githubusercontent.com/117866/33116153-f475b582-cf63-11e7-9ca4-fda78156fad5.png)

**Comment by znerd** [comment]
So here's the sample file contents:

```
== README
This is a minimalistic README file.
```

**Comment by znerd** [comment]
I just restarted IntelliJ IDEA, switched to the JavaFX preview, and now it works fine:

![screenshot](https://user-images.githubusercontent.com/117866/33116241-5896cc5e-cf64-11e7-8795-dbe0ee0984bf.png)

**Comment by ahus1** [comment]
as this works now I close this ticket.
