### ISSUE TITLE
Support zoom in preview window

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#199]
Comment on plugin's homepage: 

This plugin doesn't work well under high resolution screen. The font is too small. It will be much better if we can change font size(zoom) with Ctrl + Mouse Wheel. or we can change the font size.

**Comment by ahus1** [comment]
See #125 on how to use _myWebView.setZoom_

**Comment by ianflett** [comment]
I've created a [pull request](https://github.com/asciidoctor/asciidoctor-intellij-plugin/pull/279) for this, including an ability to reset to 100% zoom using Ctrl and the middle mouse button.

**Comment by ahus1** [comment]
This part of release 0.28.5. From the docs: 

> The user can zoom in and out of the preview by holding Ctrl and scrolling the mouse wheel up or down.
> Clicking the middle mouse button whilst holding Ctrl will reset the zoom to 100%.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

Anyone watching this issue: please give it a try and comment on this ticket.

**Comment by rdmueller** [comment]
hm. on my machine, the zoom level grows too fast - I guess that has to do with the high-dpi screen...

... and I don't have a middle mouse button - can we add a reset button to the menu bar?

**Comment by ahus1** [comment]
@rdmueller - I move your comment to a new issue.
