### ISSUE TITLE
Dejavu fonts can't display Chinese charaters

### ISSUE THREAD

**Issue by czheji** [asciidoctor/asciidoctor-intellij-plugin#203]
AsciiDoc Plugin Version: _0.20.0____

IDE Name and Version: _Clion 2017.3____
OS: Windows 10 1709

Dejavu fonts can't display Chinese charaters, please use Noto fonts instend.
http://www.google.com/get/noto/

**Comment by czheji** [comment]
I find CCS test-rending cause this issue:
origin default.css:
`p{font-family:inherit;font-weight:400;font-size:1em;line-height:1.6;margin-bottom:1.25em;text-rendering:optimizeLegibility}`
I delete "text-rendering:optimizeLegibility", and the plugin works perfect.
I don't know what caused this problem.

**Comment by ahus1** [comment]
Thank you for providing the _text-rendering_ solution! Amazing ... I have no idea why this works, but it works. I implement this change.

**Comment by mojavelinux** [comment]
Sounds to me like lack of proper support for the standard. But since this is not strictly necessary for a preview (it just disables kerning), it's reasonable to remove it.

**Comment by mojavelinux** [comment]
Would you be willing to try with this property instead?

```
font-feature-settings: "kern" 1;
```

or

```
font-kerning: normal;
```

You can check if kerning is being used with the letter sequence "WA".

**Comment by ahus1** [comment]
Version 0.20.1 is now available as a pre-release from the [github releases page](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases).

I'll test @mojavelinux' suggestions for the next release.

**Comment by D-first** [comment]
I tried version 0.20.1.
In most cases it will be displayed, 
Can not display table title and header.

![default](https://user-images.githubusercontent.com/1947605/37573893-d3ba5714-2b5f-11e8-8a07-40e32545c862.PNG)

**Comment by mojavelinux** [comment]
That's because the CSS change only changed the `p` element. You'll need to go deeper. Find all the cases in the stylesheet. There are more.

**Comment by ahus1** [comment]
@mojavelinux - I tried keeping `text-rendering:optimizeLegibility` and adding the `font*`settings you suggested... no luck there. So I'll stick with removing `text-rendering:optimizeLegibility` for now.

**Comment by ahus1** [comment]
@D-first - thanks for providing an example. I missed two places in the CSS when doing a search-and-replace. The next release will fix this.

**Comment by ahus1** [comment]
Version 0.20.2 is now available as a pre-release from the [github releases page](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases).

I also published it to JetBrains, it should be rolled out to the public soon.
