### ISSUE TITLE
LaTeX rendering breaks after a few seconds

### ISSUE THREAD

**Issue by Arcnor** [asciidoctor/asciidoctor-intellij-plugin#205]
**AsciiDoc Plugin Version:** 0.20.2

**IDE Name and Version:** IntelliJ IDEA 2017.3.5 (Community Edition)
Build #IC-173.4674.33, built on March 6, 2018
JRE: 1.8.0_152-release-1024-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

When using `latexmath` on my document, everything works great. But after re-rendering my documents a few times (every time I change anything), the LaTeX preview output starts to break after a minute or so. Then, after I modify my document a few more times, the preview starts to break sooner and sooner. So, to recap:

1. I edit my document, everything looks fine: 
![good_output](https://user-images.githubusercontent.com/28616/38340203-822af774-38b5-11e8-9f4c-11bca61e21a2.jpg)

2. After a while, I edit my document, things look good, then I wait ~1 minute (without touching anything at all) and the preview of my LaTeX sections disappears and strange characters appear in its place, or some symbols just disappear: 
![bad_output](https://user-images.githubusercontent.com/28616/38340223-9d81398e-38b5-11e8-98a7-533f9e940d3b.jpg) ![bad_output_2](https://user-images.githubusercontent.com/28616/38340246-bc2b0e5a-38b5-11e8-96e1-ebc8247ae35e.jpg)
3. If I continue editing my document, I just need to wait ~10 seconds for the content to break down.

Let me know if you need any more details.

Thanks!

**Comment by ahus1** [comment]
closed due to inactivity
