### ISSUE TITLE
IntelliJ IDEA stops working, when I select an Asciidoc file in project tree

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#207]
@tobiashochguertel: IntelliJ IDEA stops working, when I select an Asciidoc file in project tree.
When I uninstall the asciidoc plugin, then IDEA works like expected.

**Asciidoc Plugin Version: 0.20.2**

**IntelliJ IDEA Ultimate 2018.1**

> Build IU-181.4203.550, built on March 26,2018
> JRE: 1.8.0_152-release-1136-b20 x86_64
> JVM: OpenJDK 64-Bit Server VW by JetBrains s.r.o

_Logs form Intellij:_

- [idea.log](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/1959899/idea.log)
- [threadDumps-freeze-20180430-103529-IU-181.4203.550.zip](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/1959925/threadDumps-freeze-20180430-103529-IU-181.4203.550.zip)

**Comment by ahus1** [comment]
I can't reproduce this bug. But I found this change for the Markdown plugin that uses a similar method. https://github.com/JetBrains/intellij-plugins/commit/a50b5168adaaec565dfee758d154ea2356e47577

This seems to be necessary from 2017.1 onwards, although the reasons are unknown to me.  I tested this with 2017.2 and 2018.1 and it still works for me. I will create a new release and post a link once the build is complete.

**Comment by ahus1** [comment]
@tobiashochguertel: 

Version 0.20.3 is available as a preview from https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases. 

Please give it a try if it fixes the freezing GUI. 

If this fix works, please comment here and I will promote this release to an official release. 

If it doesn't work, I'd be happy if you could provide more details and/or a small minimal example project.

**Comment by tobiashochguertel** [comment]
@ahus1 works. Thanks!

**Comment by ahus1** [comment]
Thanks for the feedback. The logs really helped. I close this ticket, a version 0.20.4 will be available soon from the official repos.
