### ISSUE TITLE
Weird "split" effect in preview pane

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-intellij-plugin#208]
**Issue**
When scrolling through a document, sometimes the preview pane gets "scrambled" to say something.
Part of it does not refresh, sometimes a vertical part, sometimes an horizontal section, and sometimes you get a mix.

See the attachment, I marked the affected area with a red line.
![mixed](https://user-images.githubusercontent.com/5781153/40469558-479ca7a4-5f31-11e8-8aba-beba47263838.png)

**AsciiDoc Plugin Version:** 0.20.6

**IDE Name and Version: **
IntelliJ IDEA 2017.3.5 (Community Edition)
Build #IC-173.4674.33, built on March 5, 2018
JRE: 1.8.0_152-release-1024-b15 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by Kabhal** [comment]
I have this bug too for many IDEA/plugin versions now ...
The bug appears when the IDEA workspace is rearranged. (e.g. : fold the left panel, then the preview window is no more refreshed on a vertical zone having the same size than the folded panel).
I currently use Macos but I had the same bug on Linux last year.

**Comment by ahus1** [comment]
@abelsromero - do you still experience this? What is you DPI-mode? Are you running the IDE in full screen mode?

**Comment by abelsromero** [comment]
Not happening now :)
Just tested with the same document, which has become even more complex, but on Windows 10.
