### ISSUE TITLE
Error rendering asciidoctor when running Windows with Umlauts/Unicode chars in path name

### ISSUE THREAD

**Issue by sponiro** [asciidoctor/asciidoctor-intellij-plugin#210]
I installed the plugin and tried to open an adoc file. The following two errors appeared in the Event Log:

09:02	Error rendering asciidoctor: Error rendering asciidoctor: org.jruby.exceptions.RaiseException: (Errno::ENOENT) file:/C:/Users/robert.kÃ¼hne/.IntelliJIdea2018.1/config/plugins/asciidoctor/lib/asciidoctorj-1.5.6.jar!/specifications/open-uri-cached-0.0.5.gemspec

09:02	Error rendering asciidoctor: Error rendering asciidoctor: org.jruby.exceptions.RaiseException: (Errno::ENOENT) file:/C:/Users/robert.kÃ¼hne/.IntelliJIdea2018.1/config/plugins/asciidoctor/lib/asciidoctorj-1.5.6.jar!/specifications/open-uri-cached-0.0.5.gemspec

I suspect the umlaut causes the problem. In place of Ã¼ there should be an ü.

AsciiDoc Plugin Version: 0.20.6

IDE Name and Version: IntelliJ IDEA 2018.1.5 (Ultimate Edition)
Build #IU-181.5281.24, built on June 12, 2018
JRE: 1.8.0_152-release-1136-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by ahus1** [comment]
@wolfheart - i might found a workaround for this: you can specify the file encoding at VM start time. 

Please put the following as a new line at the end of your idea64.exe.vmoptions-File:

   -Dfile.encoding=UTF-8

This is the online documentation of IntelliJ that will show you how to find this file: https://www.jetbrains.com/help/idea/tuning-the-ide.html

Please give it a try. I'll still need to figure how to fix this - unfortunately I can't set this at runtime. Thanks!

**Comment by wolfheart** [comment]
> Please put the following as a new line at the end of your idea64.exe.vmoptions-File:
> `-Dfile.encoding=UTF-8`

Thanks! This workaround works fine! 👍

**Comment by cplaetzinger** [comment]
I encountered the same issue and the workaround fixed it for me. Thanks!

**Comment by ahus1** [comment]
This no longer seems to be a problem with the latest version 0.32.x of the plugin on IntelliJ 2020.3 - it was either resolved as part of the JDK11 runtime upgrade of JetBrains or a JRuby upgrade along with AsciidoctorJ. I therefore close this issue. This solution is still part of the [FAQ of the plugin](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/faq/errno-enoent.html).
