### ISSUE TITLE
IntellJ crashes when opening an specific .adoc file (with asciidoc plugin installed). Entire IntelliJ app disappears without any dialog or warning.

### ISSUE THREAD

**Issue by ge0ffrey** [asciidoctor/asciidoctor-intellij-plugin#211]
See https://youtrack.jetbrains.com/issue/IDEA-194988

**Comment by ahus1** [comment]
I analyzed your log file and it seems that you use the OpenJDK provided by your OS to run IntelliJ. 

Please use the JDK provided by Jetbrains that is included with your IDE. To my experience this has proven more stable when rendering JavaFX. 

You might want to report the crash of OpenJDK to the OpenJDK project as described in the head of the log file attached in youtrack.

**Comment by ahus1** [comment]
Closed due to inactivity. Please re-open for more comments.
