### ISSUE TITLE
Document title not displayed anymore in preview pane

### ISSUE THREAD

**Issue by ghusta** [asciidoctor/asciidoctor-intellij-plugin#217]
I found a regression in latest plugin release : the document title ([as defined here](http://asciidoctor.org/docs/asciidoc-writers-guide/#document-title)) is not displayed anymore in preview pane.
It was displayed in plugin v0.20.6

**AsciiDoc Plugin Version**: 0.21.1

**IDE Name and Version**: 
IntelliJ IDEA 2018.2.4 (Community Edition)
Build #IC-182.4505.22, built on September 18, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by ghusta** [comment]
I have this message in event log, that may be related : 

> 10:06  Message during rendering README.adoc: level 0 sections can only be used when doctype is book

**Comment by mojavelinux** [comment]
It would probably be helpful to show a sample document so that it gives us something to discuss.

**Comment by ghusta** [comment]
OK no problem.
Here is a very sample example.

[READIT.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/2433290/READIT.txt)

**Comment by mojavelinux** [comment]
Based on the information you gave, it's almost like the plugin is adding additional markup before converting. I'm not sure how else it could be complaining about the level-0 section when clearly it's the document title. That's my guess of what's going on.

**Comment by ahus1** [comment]
I'll have a look...

**Comment by ghusta** [comment]
Thanks to you for having been very reactive ! :+1:
