### ISSUE TITLE
Slow repaint when switching files

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#223]
First I have to say thanx for creating and maintaining this great plugin.
I really use it a lot.

What is a bit annoying on my machine is that almost always when I switch between Asciidoc files, the repaint of the editor and preview window is very slow. So slow, that I often am able to move the cursor within the editor and only the line in which the cursor is gets updated... 

One workaround to this which I now use is to switch IntelliJ from fullscreen mode to windows mode and back which causes a full repaint.

Seems only to happen with the JavaFX preview - the swing preview works fine but doesn't look as good :-)

Is this a known problem?

AsciiDoc Plugin Version: 0.21.3

IDE Name and Version: 
IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018
JRE: 1.8.0_152-release-1248-b19 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by rdmueller** [comment]
Update: I just switched to another JRE (hope this is a more recent one):

IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018
JRE: 1.8.0_152-release-b1358 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

still same problem. But I also went down to an older JDK for a short time span and there it worked flawless, but IntelliJ didn't respect the high DPI scaling...

**Comment by rdmueller** [comment]
I finally found a setting which works for me:

IntelliJ IDEA 2018.2.5 (Ultimate Edition)
Build #IU-182.4892.20, built on October 16, 2018
JRE: 1.8.0_151-b12 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Windows 10 10.0

ignoring the advice given in the docs, I switched to my default JVM and not the JetBrains one. Now it works.

**Comment by rdmueller** [comment]
solved for me. created PR #224 to help others to fix it also.

**Comment by ahus1** [comment]
Hello Ralf, thank you for the analysis and the PR. 

My experience with the Oracle JDK are very mixed when running IntelliJ - I've seen too many situations where the whole IDE just crashed (the IDE screen vanished without a trace) when using it. Other reported issues with high-DPI fonts.

I've uploaded 0.21.4 to the [Github Releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) that added more repaints. Maybe this helps. Please give it a try when you have time.

**Comment by rdmueller** [comment]
Hi Alexander, thanx for the update. I will keep an eye on this issue and will also give your release a go.
For me it is important to have a stable rendering when I present as W-JAX in 1 1/2 weeks :-)

**Comment by rdmueller** [comment]
I work in full-screen mode and switch via mouse clicks on the file name of the editor window.
When the problem occurs, the tooltip on the tab freezes and also the rendering of the two tabs (from and to which file I switch) is somehow "special".

![image](https://user-images.githubusercontent.com/1856308/47606067-3d250100-da0f-11e8-91dc-9bff9f2eb753.png)

**Comment by rdmueller** [comment]
update: I switched on my machine to another user and gave it a try.
So, it is the same machine, same intellij version (but "cleaner" install) same JB-JVM.
Until now, I can't reproduce my problem with this user.... Maybe I should do a diff of both installations...

**Comment by rdmueller** [comment]
update: it's ok that this ticket is closed, but just for the record, I would like to add an update:
With a new user on my machine (Demo-User) I first experienced no problems. But when I changed the scaling of the display (win 10), the problem re-appeared...
