### ISSUE TITLE
Reduce error messages logged in the console

### ISSUE THREAD

**Issue by elistevens** [asciidoctor/asciidoctor-intellij-plugin#225]
AsciiDoc Plugin Version: 0.21.4

IDE Name and Version: PyCharm 2018.2.2 (Professional Edition)
Build #PY-182.4129.34, built on August 21, 2018
Licensed to Eli Stevens
Subscription is active until December 11, 2018
JRE: 1.8.0_152-release-1248-b8 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

When working with multiple files (one per chapter), I have references to other files. Those get flagged as invalid references with every keystroke, resulting in the event log status line at the bottom of the editor window flickering as I type, which is distracting.

Can the logging please be suppressed so that it only is reported once?

Thanks!

**Comment by ahus1** [comment]
Starting with release [0.25.2 (now available as a preview release)](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) regular asciidoctor messages will now be shown as warnings/errors in the file and not in the console. Exceptions will still show up in the console. 

To work around broken links, I suggest you add a variable that you prefix for each include. You can configure the variable by putting a _.asciidoctorconfig_ file in the directories; they will be picked up automatically when rendering the preview and can set for example variables defining a relative path prefix to the includes. See https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-project-specific-configurations for a description. 

The combination should give you: 
* working includes, even when you split your documents to multiple directories
* errors no longer showing up in the console, but in the document

**Comment by elistevens** [comment]
Awesome! Can't wait to try it out.  :)

**Comment by mojavelinux** [comment]
> regular asciidoctor messages will now be shown as warnings/errors in the file

do you mean the log file?

**Comment by ahus1** [comment]
@mojavelinux - lease read "will be shown in the file opened in the editor". See screenshot attached.

![warning_in_file](https://user-images.githubusercontent.com/3957921/55274845-6d820b80-52dd-11e9-8eff-a0e5b0905372.png)

**Comment by mojavelinux** [comment]
Sweeeeeet!!!!!!

**Comment by ahus1** [comment]
This is now officially released as part of 0.25.9
