### ISSUE TITLE
Make soft wrap toggle available only in asciidoc files

### ISSUE THREAD

**Issue by unlimitedsola** [asciidoctor/asciidoctor-intellij-plugin#227]
As I commented in #222 :
https://github.com/asciidoctor/asciidoctor-intellij-plugin/pull/222#issuecomment-439757189

> the softwrap toggle should only be available when opening asciidoc files, currently it is available for all kinds of files, which is pretty annoying for me.

Proof:
![image](https://user-images.githubusercontent.com/3632663/48684162-5e7ea480-ebeb-11e8-85ae-2406505a2633.png)

**Comment by ahus1** [comment]
Thanks for reporting this. Will be fixed in next release.

**Comment by ahus1** [comment]
This available in 0.22.0. As this is still a pre-release (and it contains other experimental features) is available only from the [GitHub releases page](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) of this project.
