### ISSUE TITLE
New icons are too intrusive

### ISSUE THREAD

**Issue by netzwerg** [asciidoctor/asciidoctor-intellij-plugin#230]
AsciiDoc Plugin Version: 0.21.4
IDE Name and Version: IntelliJ IDEA 2018.3.1 (Ultimate Edition), Build #IU-183.4588.27

While the new icon looks awesome, the variant used in the plugin is too intrusive. Given that all other icons are generally b&w or at least use low saturation, the Asciidoctor icons look like error marks:

<img width="517" alt="screenshot 2018-11-30 at 08 45 09" src="https://user-images.githubusercontent.com/439387/49360553-cea42480-f6d9-11e8-827a-0893c8dcc435.png">

A b&w or otherwise less intrusive variant would be preferable.

**Comment by mojavelinux** [comment]
I support this change.

It seems like most icons are in grayscale. We could use the grays that are in the plaintext filetype icon. Here's a preview.

![asciidoctor-icon](https://user-images.githubusercontent.com/79351/49400858-beed0600-f702-11e8-8e5c-ae4b0228edbe.png)

Another idea would be to move the existing icon to an emblem on the filetype icon template. But that's would force the Asciidoctor logo to be smaller than it already is, which might not scale well.

**Comment by mojavelinux** [comment]
Another option is to use the outline version of the logo, which is a black "A" with a carmine equals sign. That was created for situations like this in mind.

**Comment by mojavelinux** [comment]
I like the second one *a lot* more than the first proposal. If it could be overlaid on the file icon, that would be perfect.

**Comment by mojavelinux** [comment]
Does anyone know where the file icon SVG is located? That would get the process started.

**Comment by mojavelinux** [comment]
Here's a very rough rendering. Unfortunately, that's the limit of my skillset in this area.

![asciidoctor-icon-alt2](https://user-images.githubusercontent.com/79351/49402234-96670b00-f706-11e8-8aa1-89ef523ab4a7.png)

**Comment by mojavelinux** [comment]
What I meant to ask is where the IntelliJ icons are on which to build. I'm
looking for the generic file icon.

**Comment by ahus1** [comment]
The last time JetBrains changed their icons was for the 2018.2 release - https://blog.jetbrains.com/blog/2018/06/26/new-icons-in-intellij-platform-2018-2/

I found the new base icon here: https://github.com/JetBrains/intellij-community/blob/master/platform/icons/src/fileTypes/any_type.svg with the pixel variant here https://github.com/JetBrains/intellij-community/blob/master/platform/icons/compatibilityResources/fileTypes/ for the 16px and 32px icon. 

It seems to me that in 2018 JetBrains changed all of their icons to SVG, but that's not compatible with older JetBrains versions. I've added a compatibility mechanism to load the old or the new icon versions. 

There now a regular and darcula version of the icon.

**Comment by netzwerg** [comment]
Thanks so much for implementing this, the new icons are looking great! 🎉

**Comment by mojavelinux** [comment]
Could you post an updated screenshot for completeness?

**Comment by netzwerg** [comment]
IntelliJ IDEA 2018.3.3 (Build #IU-183.5153.8), AsciiDoc Plugin v0.23.2

![adoc-icon-unselected](https://user-images.githubusercontent.com/439387/50884743-14948c80-13ec-11e9-849f-53dd8fca04db.png)

![adoc-icon-selected](https://user-images.githubusercontent.com/439387/50884742-14948c80-13ec-11e9-9daa-e31030d3433c.png)

**Comment by mojavelinux** [comment]
Thanks!

**Comment by bodiam** [comment]
That's elegant. Nice work!
