### ISSUE TITLE
How can we write erd with this plugin

### ISSUE THREAD

**Issue by okjesse** [asciidoctor/asciidoctor-intellij-plugin#232]
Like we can write plantuml with this plugin ,thank you!

**Comment by ahus1** [comment]
I assume ERD stands for Entity Relationship Diagrams.

I found this thread: http://forum.plantuml.net/16/entity-relationship-diagrams

It links the following examples: https://github.com/plantuml/plantuml/pull/31 and https://gist.github.com/QuantumGhost/0955a45383a0b6c0bc24f9654b3cb561

I hope works for you.
