### ISSUE TITLE
Preview closes Intellij

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#235]
When I open the following file with Asciidoctor preview, IntelliJ closes immediatly:

https://github.com/docToolchain/docs-as-co.de/blob/master/docs/_posts/2019-01-23-JAX.adoc

AsciiDoc Plugin Version: v0.23.2

IDE Name and Version: 
IntelliJ IDEA 2018.3.2 (Ultimate Edition)
Build #IU-183.4886.37, built on December 17, 2018
JRE: 1.8.0_191-b12 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Windows 10 10.0

**Comment by ahus1** [comment]
I've been able to reproduce it with JetBrains JDK on Windows 7. Windows reports an error in jfxwebkit.dll ... that will be hard to find...

**Comment by rdmueller** [comment]
maybe I should use another way to include tweets...

**Comment by ahus1** [comment]
There is a bug in JavaFX that is already fixed, but will apparently only be available in a future (major) version of JavaFX. See https://bugs.openjdk.java.net/browse/JDK-8213806 for details.
The problem is widget.js. I'll submit a PR with a workaround to your repo.

**Comment by ahus1** [comment]
The upcoming release 0.24.3 has an automatic filter for this problematic piece of JavaScript. It is now available from the [GitHub Releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) of this repository.

**Comment by rdmueller** [comment]
very cool! thanx!
