### ISSUE TITLE
Error rendering asciidoctor: 2 with no other logging message

### ISSUE THREAD

**Issue by elistevens** [asciidoctor/asciidoctor-intellij-plugin#236]
I have been getting the following error message relatively often with no other information given:
```
9:18 PM	Error rendering asciidoctor: Error rendering asciidoctor: 2
```
When this error starts appearing, the preview pane will no longer update. If I close pycharm and reopen, the error message does not immediately reappear, and edits to the .adoc file will show up again in the preview pane live as I type. I have not isolated a trigger for the error appearing.

As far as I can tell, once the error appears, the preview pane for the file in question will no longer work until pycharm is restarted. Once restarted, logging messages like the following appear (though repeated many times):
```
11:13 PM	Message during rendering uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb: level 0 sections can only be used when doctype is book
11:13 PM	Message during rendering uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb: id assigned to block already in use: figure-08_01
11:13 PM	Message during rendering uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb: no callout found for <1>
11:13 PM	Message during rendering uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb: id assigned to block already in use: xxx
11:13 PM	Message during rendering uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb: id assigned to block already in use: math_loss_fn
11:13 PM	Message during rendering uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb: id assigned to block already in use: figure-06_22
11:13 PM	Message during rendering uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb: no callout found for <1>
11:13 PM	Message during rendering uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb: id assigned to block already in use: figure-10_06
11:13 PM	Message during rendering uri:classloader:/gems/asciidoctor-1.5.8/lib/asciidoctor.rb: level 0 sections can only be used when doctype is book
```
I have perhaps 20 .adoc files in my project, ranging from trivial to about 10k words. The issue does not seem related to a particular subset of the files.

I think that the error started appearing when I upgraded off of plugin version 0.22 (0.21?), but I also upgraded my pycharm recently as well, so I'm not certain.

Happy to troubleshoot or debug, but I don't have any clues about how to isolate a minimal test case yet.

AsciiDoc Plugin Version: v0.24.0

IDE Name and Version: PyCharm 2018.3.4 (Professional Edition)
Build #PY-183.5429.31, built on January 29, 2019
Licensed to Eli Stevens
Subscription is active until December 11, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by david-franck-cbp** [comment]
Hello, I had the same issue, but only if my document had 2 or more "level 0" title. But this is forbidden in the [documentation ](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#section-titles): 

> When using the article doctype (the default), you can only have one level-0 section title (i.e., the document title) and it must be in the document header.

**Comment by elistevens** [comment]
I do have multiple level 0 titles, but those are explicitly allowed by the book doctype. Something like:

```
= Book Title
:chapter: 12
:sectnums: 
:sectnumoffset: 11  (chapter minus 1)
:leveloffset: 1

= Chapter Title
```

**Comment by ahus1** [comment]
Thank you for offering to troubleshoot. I wasn't able to track it down from the error message. 

I've added logging to investigate this further. Please upgrade to the pre-release 0.24.1 that is available from the [GitHub releases page](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases).

This also includes updated JRuby and AsciidoctorJ/AsciidoctorDiagram dependencies. 

Once this error appears again, go to the menu entry "Help | Show Log in Explorer". The idea.log should now contain more details about this error (especially the stack trace). 

You can send it to me via email if it contains information you don't want to post publicly on GitHub, or post an extract of the log here.

**Comment by ahus1** [comment]
I'm closing this ticket for now. If the issue re-appears, please comment in and/or re-open this issue.

**Comment by elistevens** [comment]
FYI, I've had the updated plugin installed, but have been travelling, and haven't been using my IDE much. I'll respond here if I get a stack trace.
