### ISSUE TITLE
Preview panel flickering and text jumping

### ISSUE THREAD

**Issue by behrangsa** [asciidoctor/asciidoctor-intellij-plugin#241]
In IntelliJ IDEA 2018.3.5 (and previous versions too), the preview pane flickers too much and the text jumps almost after every key stroke. Screen recording attached.

Plugin version: v0.24.3
OS: Ubuntu 18.10 (reproducible both on X and Wayland)
IDE:

```
IntelliJ IDEA 2018.3.5 (Ultimate Edition)
Build #IU-183.5912.21, built on February 26, 2019
Subscription is active until February 18, 2020
JRE: 1.8.0_152-release-1343-b28 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.18.0-16-generic
```

[screen-recording.zip](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/2949088/screen-recording.zip)

**Comment by ahus1** [comment]
Thanks for reporting this. The current implementation pushes a completely new HTML to the preview. Especially for math embedded into an asciidoc this is currently quite slow as the math rendering is done in a second step. 

Do you have a suggestion how to improve this/do you know a different (open source) plugin that behaves differently?

**Comment by behrangsa** [comment]
Hi @ahus1 

Off the top of my head:

* Instead of refreshing the preview pane on every key stroke, we can refresh it only after a period of no keyboard input (e.g. 500ms). This is not a solution to this problem, but could reduce how often the preview panel is re-rendered and improve the user experience.
* Looks like the preview pane, after every key stroke, shows raw AsciiDoc content for a fraction of a second before showing compiled content. If the preview pane could only show compiled content, it might reduce flickering.
* If we use a virtual DOM, we can create a diff of changed elements in the DOM and only update the modified parts of the DOM (similar to ReactJS).

Some virtual DOM and similar libraries:

* http://google.github.io/incremental-dom/
* https://preactjs.com/guide/getting-started
* https://redom.js.org/
* https://github.com/yelouafi/petit-dom

**Comment by krasa** [comment]
I thought LazyApplicationPoolExecutor already handles the delay...

**Comment by ahus1** [comment]
@krasa there is a short delay, but sometimes complex HTML will be rendered in multiple steps, and the steps are repeated on each refresh.

Most famous example: math formula will be rendered in plain format first, then JavaScript kicks in and replaces it with the nice layout. The nice layout has a different height, therefore it flickers.

Similar things happen sometimes with referenced images.

**Comment by krasa** [comment]
Thanks for the explanation. Nothing I can help with.

**Comment by ahus1** [comment]
I looked at the API of MathJax and found that I could pre-process the content in the preview before displaying it as long as it is a DOM object. I've implemented this with a few lines of JavaScript without additional frameworks.

On every change the full content of the preview is replaced. As the MathJax processing takes some time, this is only done before showing the contents if the previous preview contained a math expression. In all other cases it is done afterwards as a math expression might have appeared.

When the preview doesn't contain math expressions the speed of the preview is the same as before (less than 10 ms). 

When it contains math expressions, the preview has delay (about 200-300 ms), but it is no longer flickering. The delay is about the same time the previous was flickering before. The text below will be fix as long as the height of the equation doesn't change.

![flickeringmath](https://user-images.githubusercontent.com/3957921/61582462-ad3e5e80-ab2b-11e9-8707-ea5159c13edf.gif)

If anyone wants to try this out, I'm happy to provide a pre-release. I think I'll have to wait for MathJax 3 as this would support a vitual dom to make this faster.

**Comment by ahus1** [comment]
This is now part of release 0.28.21 (both available from GitHub releases AND from the standard JetBrains repository). 

For now it is behind the option "EXPERIMENTAL: Replace preview contents without flicker (JavaFX preview only)".

By default it is updated (while it is experimental). You have to activate it in the plugin's settings after you upgrade to this version.

Please comment if this is useful and work in your environment. I'll then enable it by default in a future release.

**Comment by ahus1** [comment]
Starting from 0.29.x (now in preview) no-flicker is enabled by default.

**Comment by ahus1** [comment]
I'll release 0.29.9 to the public repo later today. I'll therefore close this issue.
