### ISSUE TITLE
autocomplete for attributes

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#243]
would be great if the editor pane would support auto-complete for defined attributes

**Comment by rdmueller** [comment]
I just noticed that there is already autocompletion for available files for `include::` and `image::` macro.

Is it possible to use this to generate the autocomplete for attribute which are defined in the same file?

To be more specific for this feature:

Imagine you have a file like this

```
:url1: https://google.com
:url2: https://github.com

Lorem Ipsum
Link to google is {
```

and as you can see, in the example, it would be great to get with opening the `{` a list of available attributes from within the file (url1, url2). Perfect would be if their value would also be displayed.

**Comment by mojavelinux** [comment]
I 100% support this idea. Keep in mind, you may want to include the built-in (aka predefined) attributes to this list.

**Comment by mojavelinux** [comment]
To add to that point, this feature gets us one step closer to an "IDE for writers".

**Comment by ahus1** [comment]
@mojavelinux Where would I find a list of all predefined attributes?

@rdmueller would it be ok if I would present attributes that are defined in any of the files in the project? Assuming that people work with includes in larger projects, this might make sense?!

**Comment by mojavelinux** [comment]
If you've parsed a blank document, these attribute names are available via Document#getAttributes(). Otherwise, they are listed here: https://asciidoctor.org/docs/user-manual/#attribute-catalog

**Comment by rdmueller** [comment]
@ahus1 : Inthought it would be easier to only display the attributes of the current document to get started. Also, if the value is displayed (which is quite important in my example) this could betricky with the attributes of any document. But if this is easier, go ahead!

**Comment by ahus1** [comment]
@rdmueller - most of what is needed for a first implementation to auto-complete the variable names from the current and other files is in 071a2955dabfdcf9fb4dae22d6df9b3e93ef056a (this includes one or two refactorings that won't be necessary here any more) and 6bdb22c88ec28c750390c46d78f99f8ad4510513 (a little addendum in ). 

From there the course can continue to add current values and variable descriptions - but that's a second step.

**Comment by bbrenne** [comment]
I created a pull request with lexer and highlighting for attributes #260. No auto-complete or "link" for now (there should be 2 auto-complete , one for the reference and one for the declaration (:toc: for example) ).

**Comment by bbrenne** [comment]
#277

**Comment by ahus1** [comment]
@bbrenne - thank you for this PR, I just merged it. It provided documentation for all built-in attributes and autocomplete. 
I won't close this issue as find usages and rename is not supported yet. Do you want to give it a try?

**Comment by ahus1** [comment]
@bbrenne - I'm on a train and gave it a try, will commit it soon.

**Comment by ahus1** [comment]
Thank you to @bbrenne for contributing this change!

Autocomplete for attributes works now for built-in-attributes when defining them (inside ":").

Autocomplete for attributes that are defined within the projects works (inside "{}")

Built-In attributes have documentation (Alt-Q on Windows). 

Renaming of variables and find-usages works as well.

![autocomplete-with-docs](https://user-images.githubusercontent.com/3957921/59978726-d5e04080-95df-11e9-8a30-d7adbecd8fb8.png)
![doc-in-editor](https://user-images.githubusercontent.com/3957921/59978727-d5e04080-95df-11e9-86fc-1ab9ebd7d224.png)

This is part of pre-release  0.28.4. It is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

Please give it a try for corner cases and usability. Comment in this ticket with regarding what you experience vs what you expect.

**Comment by rdmueller** [comment]
Wow. this is all so cool and more than I had imagined!

But I still have to figure out how the documentation Feature (Alt-Q) works. doesn't work for me yet...

**Comment by rdmueller** [comment]
found it (Help -> find action): my shortcut on windows for Quick Documentation is Ctrl-Q.
works like a charm and is super useful!!!

**Comment by rdmueller** [comment]
So, I opened up this issue and I am more than happy with the results.
From my point of view, this issue can now be closed

**Comment by ahus1** [comment]
@rdmueller - it was always Ctrl-Q, my mistake. Happy to hear you like it. Kudos to @bbrenne!
