### ISSUE TITLE
Add option to save generated images from preview in a custom path

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-intellij-plugin#245]
We are using asciidoc diagrams for our designs and internal documentation, and from time to time we want to get the generated image to send to someone or include in another "more traditional" document format (*cough* microsoft word *cough*).

To do that, we generate the build of the docs and we search for the images we want in the generated path. This takes time and requires naming all images.

So, I'd be really nice if we could have a "Save image" option from the preview, that opens a file browser similar to how "save as..." works. If not from preview, maybe show a list of images in some menu or the top bar would help a lot also.

**Comment by ahus1** [comment]
Thanks for sharing this. Please allow me to explore some more options here and offer a workaround if you use plantuml. I am eager to hear your comments on this to steer development in the right direction. 

I could imagine a save as Word or save as PDF in the future, but this would save the whole document instead of a single image. Would that be helpful?

When I send and email of something from an Asciidoc snippet, I tend to copy-paste from the preview. I know this works for text, bit I am unsure if this works for images. 

What kind of diagrams are you using? I know Microsoft tools often have issues with SVG, I remember me repeatedly converting SVG to EMF using inkscape. What is your preferred format?

When I use plantuml, I separate the diagrams in a *.puml file and edit them with the plantuml plugin for intellij. I then include the puml in the asciidoc source. This plantuml plugin supports an export to a file if I remember correctly. This might be a workaround when you use plantuml for your diagrams.

**Comment by abelsromero** [comment]
First of all, I understand this is clearly a low prio thing. More in the Nice-2-have than the should-have :P So, no preasure or priority.

> I could imagine a save as Word or save as PDF in the future, but this would save the whole document instead of a single image. Would that be helpful?

Not really, because I just want the image.

> When I send and email of something from an Asciidoc snippet, I tend to copy-paste from the preview. I know this works for text, bit I am unsure if this works for images.

I tried but at least in Windows, when I paste I get a white image. I can copy the formatted text, included the image footer though.
What I usually do, is a screen capture, but when I have a big diagram, it gets scaled down according to the available width in the preview and text becomes unreadable. Even in a 16:9 and maxing out the preview window.

> What kind of diagrams are you using? I know Microsoft tools often have issues with SVG, I remember me repeatedly converting SVG to EMF using inkscape. What is your preferred format?

Mostly plant-uml class diagrams. So far I can get the generated jpg or png that's the only thing I need to share.

> When I use plantuml, I separate the diagrams in a *.puml file and edit them with the plantuml plugin for intellij. I then include the puml in the asciidoc source. This plantuml plugin supports an export to a file if I remember correctly. This might be a workaround when you use plantuml for your diagrams.

I wasn't aware of that plugin, thanks! 😃 This could definitely work for now and marks all checks, we are already reusing diagrams that we include in others using `!include`. It's just a matter of putting all diagrams in separate files.
...now if we could browse from the asciidoctor source to the plantuml file with a click, it would be awesome. I ma just exploring ideas here, ¿would this be easy to do? I have no idea about idea plugins code.

```
[plantuml, config-classes, png]
.Configuration
....
!include includes/common-ifaces.iuml
!include includes/common-traits.iuml

```

Maybe this could make for a nice "Tips & Tricks" section?

**Comment by ahus1** [comment]
This is a snippets how I include using asciidoc syntax:
 
```
[plantuml, document, svg]
----
include::showcase_plantuml.puml[]
----
```

See https://github.com/ahus1/asciidoctor-deepdive/blob/master/inside-documents/80_plantuml.adoc for an example (you'll have to look at the code, the GitHub preview doesn't help much).

Yes, this would be something for the tips and tricks section. 

Making include links clickable would be really nice. I will get back to you once I have the bold/italic/mono highlighting finished. Maybe we can pair up for the clickable include thing.

**Comment by abelsromero** [comment]
> This is a snippets how I include using asciidoc syntax:

Definitely nicer and more recommendable because it keeps all in AsciiDoc syntax, but this does not work for me due to pathing issues.
I have source.adoc, that includes A puml, that includes files B.puml and C.puml. A. B and C are in a subdirectory called "diagrams". Since A is a plantuml I have to use plant's include to add B & C. `!include` uses (to my knowledge) a relative path from the source file. 

````souce.adoc
!include diagrams/A.puml
````

````A.puml
!include B.puml
!include C.puml
````

Using the same `!include` in source.adoc works fine for the adoc conversion and and I can open the A.puml with the plantuml plugin too. However, using `include:: []` breaks the preview because (I assume) embeds A in source.adoc. So the !include in A expects to find B & C in the same path as source.adoc. The error shown in the preview clearly shows the path without the "diagrams" dir in it.

I am not 100% convinced because with this I have to keep another path structure, but it works at least and improves my work workflow 👍

**Comment by ahus1** [comment]
This part of release 0.28.5. From the docs: 

Thank you to @bbrenne for providing this implementation!

> When the user right-clicks on an image, the editor shows a dialog to save the file to the local file system.
> For diagrams like PlantUML it offers to save the files as PNG or SVG.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

Please give it a try and comment on this ticket.

![save-image](https://user-images.githubusercontent.com/3957921/60139425-302efc00-97ae-11e9-904e-fc57e0f413fc.png)

**Comment by ahus1** [comment]
This part of release 0.28.5. From the docs: 

Thank you to @bbrenne for providing this implementation!

> When the user right-clicks on an image, the editor shows a dialog to save the file to the local file system.
> For diagrams like PlantUML it offers to save the files as PNG or SVG.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

Please give it a try and comment on this ticket.

![save-image](https://user-images.githubusercontent.com/3957921/60139551-9a47a100-97ae-11e9-86cc-8b970d96fb3f.png)

**Comment by mojavelinux** [comment]
This is incredibly cool. What a great idea and an awesome use of the IDE!

**Comment by abelsromero** [comment]
You're all making me very happy lately 😀

**Comment by wimdeblauwe** [comment]
Has this been tested on macOS ? I just updated to 0.28.5 but I don't get a menu when I right-click on the image or anywhere else in the preview pane.

**Comment by abelsromero** [comment]
>  I don't get a menu when I right-click on the image

It's not a menu, but directly a "export image to" window shows when doing a right-click. Also this is for "generated" images, for example using the diagram plugin, not normal images using `image:` or `image::`.

![image](https://user-images.githubusercontent.com/5781153/60159229-ffbd8100-97f2-11e9-96e4-3aefe4f96c0e.png)

**Comment by ahus1** [comment]
I wasn't able to test it on a Mac due to the lack of one.

It uses the context menu JavaScript event. It is the same that I use to save an image to disk when I visit a website in a browser.

How would you open a context menu in a browser window on macos? How would you save an image on a website to local disk on macos?

**Comment by wimdeblauwe** [comment]
> It's not a menu, but directly a "export image to" window shows when doing a right-click. Also this is for "generated" images, for example using the diagram plugin, not normal images using `image:` or `image::`.
> 

Yes, I tried with a plantuml diagram like the example, but nothing happens if I right-click.

**Comment by wimdeblauwe** [comment]
> How would you open a context menu in a browser window on macos? How would you save an image on a website to local disk on macos?

I have no idea. Maybe https://stackoverflow.com/questions/2405771/is-right-click-a-javascript-event can be of inspiration? If you have something to test, I can test it for you.

**Comment by wimdeblauwe** [comment]
I just noticed that the right-click in the plantuml plugin works fine on macOS, so maybe you can have a look to the sources at https://github.com/esteinberg/plantuml4idea/ to see how they did it there ?

**Comment by ahus1** [comment]
@wimdeblauwe - for this plugin the diagram preview is part of a HTML rendered page displayed in a JavaFX WebView. The PlantUML doesn't use a WebView (I searched their code). 

I talked to a MacOS user today and we tested "Image Save As" in a regular chrome browser. Ctrl-Click or two-finger-tap opened the Chrome context menu. If this doesn't work for a context menu in the JavaFX WebView, I'm afraid this will have to wait for a developer who can debug this on a Mac. 

If neither Ctrl-click or two-finger-tap on the image in the preview work for you, please open a separate bug issue in this repo and about the system and version you use.

**Comment by ahus1** [comment]
@abelsromero - thank you for your comment that users will find this issue probably only by accident. I've opened issue #282 to collect ideas how UX can be improved.

**Comment by abelsromero** [comment]
> I talked to a MacOS user today and we tested "Image Save As" in a regular chrome browser. Ctrl-Click or two-finger-tap opened the Chrome context menu. If this doesn't work for a context menu in the JavaFX WebView, I'm afraid this will have to wait for a developer who can debug this on a Mac.

I already tried everything you mention + a normal 3 button mouse I use with my MacOS and all contextual menus in IntelliJ & Firefox work fine, but not the "Export to image" plugin.

**Comment by wimdeblauwe** [comment]
I created #283 for the the macOS issue.
