### ISSUE TITLE
constrained formatting issues with italic/bold/mono - asciidoc plugin 0.25.9 regressions

### ISSUE THREAD

**Issue by jmalin-signalfx** [asciidoctor/asciidoctor-intellij-plugin#248]
I don't know who supports the Asciidoc plugin for IntelliJ IDEA 2019.1, but its blurb links to asciidoctor.org which links to this GitHub repo.

Today (May 1, 2019 PDT) I received notification that a new version of the Asciidoc plugin for IntelliJ IDEA was available. Since I use asciidoctor in IntelliJ, I installed the plugin. The listed version is v0.25.9.

This version breaks features that were previously working, specifically:

- The plugin now interprets single `_` as underlines and highlights them in the plain text with italics. Previously, it didn't change their highlighting.
- Editing in an adoc file eventually hangs IntelliJ. The only way to fix the problem is to force quit. I've had to uninstall the plugin.

**Comment by mojavelinux** [comment]
Now it's in the right place.

**Comment by ahus1** [comment]
Hello @jmalin-signalfx, I'm sorry to hear that the plugin gives you troubles. 

While we take care of the issues you reported, you might want to downgrade to an earlier version. For example 0.24.4 that is available from the JetBrains plugin repository for download: https://plugins.jetbrains.com/plugin/7391-asciidoc/versions

To investigate further, please provide additional information for the issues you saw: 

* A minimal Asciidoc example for the `_` italic highlighting issue - a matching screenshot of what you see would be helpful
* an example of the Asciidoc file that lead to the hangup (if reproducable). Maybe the IntelliJ's logfile contains helpful information; you can access it via "Help | Show log in Explorer" or "Help | Compress Logs and show in Explorer". If you don't want to post your logs publicly, you can provide them to me via email (my email address is visible in my GitHub profile)

Thanks in advance, Alexander

**Comment by lhotari** [comment]
I'm getting this kind of exception on IntelliJ Ultimate 2019.1.1/ Linux with 0.25.9 version of the plugin. The Asciidoc preview won't show up. This happens on all Asciidoc files, so it doesn't seem to be related to the content of the file.
```
java.util.ServiceConfigurationError: org.asciidoctor.Asciidoctor: Provider org.asciidoctor.jruby.internal.JRubyAsciidoctor could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.asciidoctor.Asciidoctor$Factory.create(Asciidoctor.java:475)
	at org.asciidoc.intellij.AsciiDoc.initWithExtensions(AsciiDoc.java:123)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:285)
	at org.asciidoc.intellij.AsciiDoc.render(AsciiDoc.java:280)
	at org.asciidoc.intellij.editor.AsciiDocPreviewEditor$2.run(AsciiDocPreviewEditor.java:124)
	at org.asciidoc.intellij.editor.LazyApplicationPoolExecutor$1.run(LazyApplicationPoolExecutor.java:59)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:311)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.jruby.util.io.FilenoUtil$ReflectiveAccess
	at org.jruby.util.io.FilenoUtil.getFilenoUsingReflection(FilenoUtil.java:111)
	at org.jruby.util.io.FilenoUtil.filenoFrom(FilenoUtil.java:107)
	at org.jruby.RubyGlobal.prepareStdioChannel(RubyGlobal.java:335)
	at org.jruby.RubyGlobal.initSTDIO(RubyGlobal.java:298)
	at org.jruby.RubyGlobal.createGlobals(RubyGlobal.java:211)
	at org.jruby.Ruby.init(Ruby.java:1260)
	at org.jruby.Ruby.newInstance(Ruby.java:370)
	at org.jruby.javasupport.JavaEmbedUtils.initialize(JavaEmbedUtils.java:79)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.createRubyRuntime(JRubyAsciidoctor.java:125)
	at org.asciidoctor.jruby.internal.JRubyAsciidoctor.<init>(JRubyAsciidoctor.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 14 more
```
As a workaround, I downgraded to 0.24.4 by downloading [asciidoctor.zip](https://plugins.jetbrains.com/files/7391/60081/asciidoctor.zip?updateId=60081&pluginId=7391&family=intellij) from the plugin portal and using the "Install Plugin From Disk..." feature in IntelliJ.

**Comment by abelsromero** [comment]
I am also seeing weird highlighting of `_`.

![image](https://user-images.githubusercontent.com/5781153/57151422-39fd3a00-6dd1-11e9-8c0c-47fabe67012a.png)

![image](https://user-images.githubusercontent.com/5781153/57151433-3f5a8480-6dd1-11e9-8480-6282f4af0712.png)

**First**, it seems to highlight underscore that are close to another, even when not match* to a second (like the first in the screenshot). Close = in 2 lines, you see the other underscore below, those are not highlighted.

\* "match" means it highlights the related underscore.

**Then** the matching jumps to lack of a better word. Try typing text like "aaa_aaa", followed by a line break several times and you'll see.

**Comment by ahus1** [comment]
@jmalin-signalfx - a cause for instability has been fixed in #250 and release as 0.25.11. This might also remedy the instability you observed in this ticket. Further commits to this ticket will handle the issues reported in formatting.

**Comment by ahus1** [comment]
@abelsromero - there is now 0.25.12 available as a preview release from https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases

This does a better job in handling underscores in the middle of words and not taking them as constrained formatting.

If you discover snippets that don't parse correctly, please post them as a source code snippet here.

**Comment by abelsromero** [comment]
> This does a better job in handling underscores in the middle of words and not taking them as constrained formatting.

It does indeed :+1:  Most of cases are correctly rendered now. My obsessive compulsion greatly thanks you :smile: 

The only issues I am having now are related to the second point in which some elements are highlighted and un-highligted while I write. Here are the cases, all done with 0.25.12.

1. Start a new document with the content

```
= Test adoc

== section

```

2. Write at the end this fragment, it's **important** to write, copy & paste does not always reproduce the behavior, and don't press enter.

```
_Lorem
ipsum_
```

Now comes a few funny cases, each case assumes you start from step 2:

a. While the cursor is after the last underscore, it is highlighted, as soon as you press enter and just go a new line, the last underscore is no longer highlighted.

b. Without any line break, just insert a space after the second underscore and start typing just anything, like continuous `s`. 

```
= Test adoc

== section

_Lorem
ipsum_ sssssssssssss

```

You'll see the second highlight actives and deactivates with every stroke.

c. If I move the cursor to the beginning of the second line insert a line and start typing the second underscore is no longer highlighted. 

d. a, b, & c don't reproduce if instead of 2 lines, the paragraph has 3 or more. In that case the second underscore in almost never highlighted. Only in the case in which after typing the third line, move cursor to the begging of the third line, insert a new line and type, it will be highlighted only after the first stroke.

**Comment by ahus1** [comment]
@abelsromero - there is now 0.25.13 available from https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases

This support proper formatting as-you-type. I found out that IntelliJ will do partial lexing of the file, so I needed to adapt the lexer to this. 

Please give it a try if you have the time.

**Comment by abelsromero** [comment]
Cases a & b are fixed now.

> IntelliJ will do partial lexing of the file

That may explain why I still get weird moment where highlighting is enabled or disabled when moving across the document. Case c still happens, I edited the previous post to clarify how I do it.
Also, the first underscore gets un-highlighted when I type a space in the second line.

Anyway, so far the work is great. I hope my reports don't discourage you :smile:

**Comment by jmalin-signalfx** [comment]
Working fine for me.

**Comment by ahus1** [comment]
@jmalin-signalfx - good to head that. Thank you for your feedback.

**Comment by ahus1** [comment]
@abelsromero - I've looked into the issues you reported and a new pre-release 0.25.14 is now available.

I am aware that it highlights *test*test although it shouldn't, but I leave it for now until I figure out how to restructure the parsing of the existing rules. Please give it a try; I would then close this issue.

**Comment by abelsromero** [comment]
> I am aware that it highlights _test_test although it shouldn't, but I leave it for now until I figure out how to restructure the parsing of the existing rules. Please give it a try; I would then close this issue.

You lead here friend, feel free to close it if you consider this is the best with the current approach and re-work is needed. The major issues are solved for me.

**Comment by ahus1** [comment]
Release 0.25.14 will be available via the JetBrains plugin repository shortly. Thank you for your patience and support. 

The IntelliJ plugin for Asciidoc has now (finally) some support highlighting bold/italic/monospace!
