### ISSUE TITLE
Code Inspection for Link Reference Incorrectly Flagged as Invalid

### ISSUE THREAD

**Issue by mphouston** [asciidoctor/asciidoctor-intellij-plugin#249]
(Excellent plugin.  Keep up the good work :).

The 'inspection' style error is shown on most files: 'possible invalid reference: ABC'.

I have a lot of .adoc files for the project (50+).  I edit one that references a section in another file and there is now an inspection-style error (yellow severity) at the top of the file:

    possible invalid reference: ABC

Since I have hundreds of section references, this shows up in all of my files.  Now, the file is flagged with a yellow error, so I can't easily check for typos (green check marker with underscore).

Is there a way to turn this reference check off?   It does not appear to have a true inspection setting.
I really don't want to render the whole doc (200+ pages) just to make it go away.  I think this just showed up with 0.25.9.

A quick sample that shows the problem. 

````
== Title


See <<ABC>>
````

Thanks! 

AsciiDoc Plugin Version: 0.25.9

IDE Name and Version: 
IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by ahus1** [comment]
Version 0.25.9 is the first version that shows the Asciidoctor warnings inline in the editor. 

I see that this message is problematic in multipart documents, and it doesn't have a line number. For now, I will suppress this message. 

Currently there is no way to individually suppress messages. At some point I will probably need to add it, but not now.

If you find other warnings that should be suppressed, please report them as a ticket on GitHub.

**Comment by ahus1** [comment]
This is now fixed in Version 0.25.10 and later, available from https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases

Please give it a try, and re-open the ticket if necessary.

**Comment by mphouston** [comment]
Thanks.  That did the job.
