### ISSUE TITLE
Enable Block ID references

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#252]
This will support: 
* ``[[id]]``, ``[[id,text]]``, ``[#id]``, ``[#id.class]`` and ``[#id,text]`` with find-usages and rename refactoring
* ``<<id>>`` and ``<<id,text>>`` with find usages and autocomplete across files and rename refactoring
* search all via for all IDs

**Comment by ahus1** [comment]
Pre-release 0.26.0 is now available from the [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases). Please provide feedback of parsing and patterns I missed. Thanks!

**Comment by rdmueller** [comment]
very cool. works perfect for my use cases!

**Comment by ahus1** [comment]
Thank you for testing it!
