### ISSUE TITLE
Auto-completion of files should include ".." as well

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#253]
I just noticed that there is already autocompletion for available files for `include::` and `image::` macro. This is a great feature which helps a lot but I miss the `..` in the list of available files, just for easy navigation.

**Comment by ahus1** [comment]
The autocomplete is limited to a defined list of macro names, currently include and image. Are there other macros I've missed? You could add them to AsciiDocBlockMacro as needed. 

In the same class I'm calling FileReferenceSet. There is no obvious parameter to change it to add `..` - I haven't yet found out what I can do by passing a PsiReferenceProvider.

**Comment by ahus1** [comment]
will be handled as part of #275
