### ISSUE TITLE
Unable to customize syntax highlighting colors

### ISSUE THREAD

**Issue by elistevens** [asciidoctor/asciidoctor-intellij-plugin#254]
I cannot find a way to customize the syntax highlighting colors. They seem to be hardcoded(?) to a light theme:

````
validation set (`0.802000`) lets us appreciate
````

In the editor, this looks like:

![image](https://user-images.githubusercontent.com/138016/57737775-b90c3100-7661-11e9-8203-69f12e78a74d.png)

The rendered view is fine:

![image](https://user-images.githubusercontent.com/138016/57737862-07213480-7662-11e9-837d-a2d5fe016369.png)

I would expect that the colors would show up under an Asciidoc file type in Settings > Editor > Color Scheme > Asciidoc

AsciiDoc Plugin Version: 0.25.14

IDE Name and Version: 

PyCharm 2019.1 (Professional Edition)
Build #PY-191.6183.50, built on March 19, 2019
Licensed to Eli Stevens
Subscription is active until December 11, 2019
JRE: 11.0.2+9-b159.30 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by ahus1** [comment]
This plugin currently support Default and Darcula theme. Currently you can't set custom colors. I'll add this for an upcoming release. 

Did you select a different theme, or did you define a custom theme?

**Comment by elistevens** [comment]
I have a custom theme based on tweaks of Darcula. Seems like since it's not a recognized name, it's defaulting to Default colors? Is there a way to get it to use the Darcula-compatible colors?

**Comment by ahus1** [comment]
I think your assumption is correct, it defaults to Default colors. I'm looking into this; I hope to make this configurable over the next days.

**Comment by ahus1** [comment]
There is now a pre-release 0.25.1 available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases). 

This allows you to configure colors for highlighting, or to reset the colors for AsciiDoc highlighting to the Darcula theme. 

Please give it a try!

![settings](https://user-images.githubusercontent.com/3957921/57839588-4cab4200-77c7-11e9-8c93-48d344e0f9c2.png)

**Comment by ahus1** [comment]
version 0.26.7 is now available via the jetbrains plugin repository.
