### ISSUE TITLE
"Inject language or reference" in source code blocks

### ISSUE THREAD

**Issue by julianwilke** [asciidoctor/asciidoctor-intellij-plugin#255]
I think being able to get access to all the IDE features by being able to "inject language or reference" within source code blocks would make a big difference.

**Language injections**
https://www.jetbrains.com/help/idea/using-language-injections.html

According to [this](https://intellij-support.jetbrains.com/hc/en-us/community/posts/203371784-Allow-language-injection-in-custom-language-plugin), that would involve the PSI elements implementing the interface [PsiLanguageInjectionHost](https://github.com/JetBrains/intellij-community/blob/master/platform/core-api/src/com/intellij/psi/PsiLanguageInjectionHost.java#L27). I am not able to assess how much work that would be, though.

I did see there was [this issue](https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/12) in the past. But since it was closed in 2015 as part of housekeeping I thought it might be ok to open up a new issue.

Thanks! Any answer would be greatly appreciated.

---
AsciiDoc Plugin Version: v0.25.14
IDE Name and Version: IntelliJ IDEA 2019.1.2

**Comment by ahus1** [comment]
The Markdown plugin can do this, so we could give it a try. The Markdown plugin is [open source](https://github.com/JetBrains/intellij-plugins/tree/master/markdown), and I would be happy to accept a PR that ports this functionality to the AsciiDoc plugin. 

The Markdown Plugin made this configurable: people you don't want this functionality can disable it in the plugin's configuration; this should be ported as well.

**Comment by ahus1** [comment]
There is now the pre-release 0.26.10 available from the [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) with experimental support.

As the support is experimental, it is disabled by default. You'll need to go to the plugin's settings and re-enable it.

I need feedback in what cases highlighting should not be enabled, or where it needs to be tweaked.

Situations I could think of (as of today none of these situations is handled): 

* Java highlighting will work only for complete classes, not for Java code snippets -> possible solution: configurable exclusion for language list in plugin configuration 
* An include inside the listing block doesn't lead to valid code -> possible solution: whenever there is an "include:[]" in the block, disable highlighting 

Please provide more situations, or comment if you think these situations are relevant to be handled before considering this no longer experimental.

What is supported today (if enabled):

```
[source,json]
----
{ "hello": "world" }
----

[plantuml]
----
@startuml
Alice -> Bob: Authentication Request
@enduml
----
```

Screenshot: 

![screenshot](https://user-images.githubusercontent.com/3957921/58627758-42656980-82d8-11e9-884b-b52757575297.png)

**Comment by ahus1** [comment]
BTW: there is as-you-type support; once you write "[source," the language list (as available in IntelliJ) appears once you write the comma.

**Comment by ahus1** [comment]
Preview version 0.27.11 is now available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) with the following enhancements:

* configurable exclusion for language list in plugin configuration
* whenever there is an "include:[]" in the block, disable highlighting

**Comment by julianwilke** [comment]
@ahus1 
Thank you so much for your work on this! Works beautifully for my use case.

**Comment by mphouston** [comment]
Thanks for adding the configuration option to disable the syntax checking on source blocks :).

I had a lot of source blocks that contain invalid code that was always being flagged as bad.

Thanks again for the work on this plugin...

**Comment by ahus1** [comment]
@mphouston - thank you for your feedback. I recently learned that it is important to disable also the other error highlightings; see #296 (only available in preview releases at the moment).

Please feel free to share your opinion in the plugin's rating at https://plugins.jetbrains.com/plugin/7391-asciidoc :-)
