### ISSUE TITLE
Add support for environment variable GRAPHVIZ_DOT.

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-intellij-plugin#261]
PlantUML optionally uses environment GRAPHVIZ_DOT to locate the  `dot`  program. On Windows, for example, I've set GRAPHVIZ_DOT  to the location of the dot.exe file (and I did not add the `bin` folder to PATH):

```
GRAPHVIZ_DOT=C:\WS\Apps\graphviz-2.38\release\bin\dot.exe
```

With GRAPHVIZ_DOT defined, the Plantuml content below renders correctly in IntelliJ/Asciidoc 0.26.7.

```
[plantuml, uml-example, png]
----
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
@enduml
----
```

However, the Graphviz content

```
[graphviz, dot-example, png]
----
digraph g {
    a -> b
    b -> c
    c -> d
    d -> a
}
----
```

generates the message:

```
Failed to generate image: Could not find the 'dot' executable in PATH; add it to the PATH or specify its location using the 'graphvizdot' document attribute
digraph g {
    a -> b
    b -> c
    c -> d
    d -> a
}
```

Please locate the dot program using environment variable GRAPHVIZ_DOT (if defined) when processing Graphviz content.

With the addition of the proposed functionality, one would expect the error message to be changed to:

```
add it to the PATH or specify its location using the 'graphvizdot' document attribute or define environment variable GRAPHVIZ_DOT.
```

**Comment by ahus1** [comment]
I'm still considering options how I could provide a workaround in the plugin. The solution you propose will need to be implemented in the upstream projects (probably asciidoctor-diagram, I will need to find out about this as time permits)

For the time begin, I suggest as a workaround that you wrap the graphviz content inside a plantuml block like this: 

[plantuml, graphviz, png]
----
@startuml
digraph g {
    a -> b
    b -> c
    c -> d
    d -> a
}
@enduml
----

**Comment by ahus1** [comment]
I've looked at the code. The logic resides in asciidoctor-diagram, see https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/graphviz/extension.rb and https://github.com/asciidoctor/asciidoctor-diagram/blob/master/lib/asciidoctor-diagram/util/which.rb). 

I've implemented a workaround that I read the environment variable and pass as _graphvizdot_ attribute. 

Still, this doesn't change the error message if the file is not found. 

I plan to provide a pre-release over the next days.

**Comment by ahus1** [comment]
@wfouche - after reviewing the configuration possibilities of asciidoctor-diagram an the existing funtionality of the IntelliJ Asciidoctor Plugin, I found the following possibility that exists since version 0.21.1 and is therefore available in the currently published version of the plugin: 

Please configure the attribute _graphvizdot_ in the plugin's settings like shown in the screenshot below. 

![graphviz-config](https://user-images.githubusercontent.com/3957921/58661177-816edb80-8327-11e9-9a3e-81ac8cadfbb4.png)

Future versions of the plugin might have a more intuitive and convenient way to configure this.

**Comment by ahus1** [comment]
Preview version 0.27.11 is now available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases). 

As there as multiple external helper applications for asciidoctor-diagram, I will not provide a configuration entry for all of them. Instead, I will rely on the error message of asciidoctor diagram. The is now a [documentation on the wiki](https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki) that describes what to do.

Pull requests for a more user friendly approach are welcome.
