### ISSUE TITLE
Structure View should link to includes

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#267]
The File Structure-View (ALT+7) is very cool!

It currently shows the structure of the current file.

One Improvement could be that it also includes the structure of the included files.

And to go even one step further, it would be great if this view could be "pinned" to one file:
Imagine you have a master document which includes lots of subdocuments. When you click on one of the heading of a subdocument, the edit view should Change to this document, but it would be cool if I could configure the structure view to stay at the master document

**Comment by ahus1** [comment]
@rdmueller - the structure view is always linked to the current file. A plugin can't change this. There is an open issue for IntelliJ for this, please vote for it: https://youtrack.jetbrains.com/issue/IDEA-178175. The good news: it will only update once you leave its focus to a different file.

If the structure view integrates different files (like included files) you can look at them using the structure view. Once you change the focus to the file itself, the structure view will update with the contents of the newly selected file.

I gave it a try and it is possible to display all included files and images within the structure view (by de-referencing their references). When you include an AsciiDoc file, it will show the structure content of the included AsciiDoc file - OMG! 

Please feel free to adopt/tune the output (see referenced commit)

Here is an example screenshot

![structure](https://user-images.githubusercontent.com/3957921/58993927-3ce3b400-87ef-11e9-94df-a2af16226692.png)

Source:
````
== 1

=== 1.1

image::developerbox3.png[]

=== 1.2

.Diagram
[plantuml, pic, png]
----
include::List.iuml[]
----

=== 1.3

include::list.adoc

````

**Comment by rdmueller** [comment]
wow. this looks awesome!

**Comment by ahus1** [comment]
I think it needs icons to represents section and block, probably also diagram and listing. Any thoughts on icon language here? Java Icons use a single letter and a colour code... AFAIK.

**Comment by ahus1** [comment]
The preview release 0.26.16 is now [available from Github Releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases). 

It contains the extended structure view and an icon set for both the breadcrumbs and the icons view. 

I've also tuned the displayed texts in the structure view (it now shows either the title, the first block attribute, or the macro name depending on the element).

**Comment by rdmueller** [comment]
Wow. The icons are great - I first thought the structure view would only contain headlines, but you managed to add so much more!

However, I don't know when includes are resolved and when not.
I my examples, I have simple includes like `config.adoc` and `feedback.adoc` which are resolved, more complex examples are not resolved, only displayed as `include`

Example: https://github.com/docToolchain/docToolchain/blob/master/src/docs/manual.adoc

Any Idea what's wrong?

**Comment by ahus1** [comment]
Apparently I didn't test with subdirectories and resolved the wrong reference. I updated the code; the next pre-releases 0.26.18 will support this.

**Comment by ahus1** [comment]
The preview release 0.26.18 is now available from GitHub Releases.

I've refactored the text generation for the structure and the breadcrumbs; they are now use the same texts.

I've decided to rework the folded text to make it work more IntelliJ-like: It now shows the first line of the block (except when this is a reference) instead of adding a type prefix. For sections it will always show the section section title. 

I've updated some parts of the parser; it now understands more block types, the block types can be nested where appropriate and if their contents allow substitutions the lexer/parser will handle their content for highlighting. 

Some automated tests exist, but this version needs some more real live texts before it is ready to be released. Please give it a try and provide feedback.

Using the [article sample](https://asciidoctor.org/docs/asciidoc-article/) this delivers images like these:

![structure](https://user-images.githubusercontent.com/3957921/59164370-1635be00-8b0c-11e9-8958-932ef60c39e5.png)

![folding](https://user-images.githubusercontent.com/3957921/59164416-bc81c380-8b0c-11e9-8129-df6b768f0e8a.png)

![breadcrumb](https://user-images.githubusercontent.com/3957921/59164365-08803880-8b0c-11e9-8f83-cd7d8c995a3f.png)

**Comment by mojavelinux** [comment]
That is so cool! Impressive work, @ahus1.

**Comment by peterneubauer** [comment]
Very cool!

**Comment by rdmueller** [comment]
Wow. Just gave it a try.

The folded text now works better. It doesn't "jump" anymore.

I just noticed that for blocks like this:

    [[section_target]]
    == Headline

The fold icon will be with the section target and the "Headline" will be displayed. That is perfect.

For a table like this:

    [cols="1,4", options="header"]
    .table name
    |===

The fold icon will be with the `[cols...` and this is also what will be displayed instead of the table name. But that is ok with me since I think that the following syntax should be best practice and the one above not used:

    .table name
    [cols="1,4", options="header"]
    |===

And here the fold icon will be with the table name and the table name will be displayed... 

The full blown structure view is really helpful!

**Comment by mojavelinux** [comment]
> But that is ok with me since I think that the following syntax should be best practice

Agreed. I think it looks much better to put the title first, then the block attribute list.

**Comment by ahus1** [comment]
@mojavelinux, @rdmueller - regarding "title before block attributes": should there be an inspection that should nag users to put them in the "right" order? Including a quick-fix?

**Comment by rdmueller** [comment]
@ahus1 - that's a very low priority for me. More helpful would be to pick up the title instead of the options regardsless of the order, but that's also a very low priority.

**Comment by ahus1** [comment]
There is now pre-release [0.26.19 available from GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) that fixes some issues when using bock macros inside blocks.

I'm closing this tickets for now as the functionality is now available. If you experience issues, please open a bug ticket (with samples).
