### ISSUE TITLE
image's dir does not default to ./images

### ISSUE THREAD

**Issue by gebezs** [asciidoctor/asciidoctor-intellij-plugin#270]
The https://asciidoctor.org/docs/user-manual/#setting-asset-locations defines that the default value for the `imagesdir` is the `./images` directory.
This is not the case here.
The `{imagesdir}` is empty without further configuration.
The html5/pdf backend works with the above mentioned default value.
I understand that I can override this in the `.asciidoctorconfig` with the `#ifndef::imagesdir[:imagesdir: images]` however it would be great if the plugin and the backends would work the same way.
I execute the backends via the `asciidoctor-maven-plugin`.

Is it possible to use the default here as well?

AsciiDoc Plugin Version: v0.26.15
IDE Name and Version: IntelliJ IDEA 2019.1.2 (Ultimate Edition) Build #IU-191.7141.44, built on May 7, 2019
asciidoctor-maven-plugin version: 1.6.0

**Comment by mojavelinux** [comment]
The default value for the imagesdir is blank, so this plugin is correct.

**Comment by mojavelinux** [comment]
In fact, that section you linked to specifically says that:

"You can also use attributes to set the base path to images (default: empty)"

It's also listed that way here: https://asciidoctor.org/docs/user-manual/#builtin-attributes

**Comment by mojavelinux** [comment]
It's the Maven plugin that is doing it wrong, and that issue is being discussed here: https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/296

**Comment by gebezs** [comment]
Thanks for the quick reply. I missed the example from the end of the block title ("Base asset path configuration example").
