### ISSUE TITLE
"include" Refactoring

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#271]
hm. this might be a duplicate but I couldn't find it.

@ahus1, thanx to all your hard work during the last few weeks, the plugin is now really in a state where working with AsciiDoc is like working with code. Thanx for this!!!

Now, a really cool additional feature would be the following refactoring:

- select text, right click, "refactor -> extract to include" and the selected text gets written to anexternal file and will be replaced with the appropriate `include` statement
- right click on `include` statement, "refactor -> insert from include" and the `include`statement gets replaced by the referenced file

This would help to work with large documents.

**Comment by ahus1** [comment]
@rdmueller - what would be the most natural way to trigger the "extract" refactoring without selecting the code first? 

Trigger it for the current block/section? 

BTW I have no idea how to build that yet...

**Comment by rdmueller** [comment]
> BTW I have no idea how to build that yet...

Fascinating.  

> what would be the most natural way to trigger the "extract" refactoring without selecting the code first?

I would search for the last headline upwards and extract everything downwards up to the next heading level of the same depth.

But to be honest and simplify things, I would have exprected an error message.

**Comment by ahus1** [comment]
A first version of this is part of 0.28.10

From the docs:

> The user can extract and inline includes. This is available from the “Refactor” context menu and via context-sensitive intents via Alt+Enter (“Inline Include” and “Extract Include”). Extract will extract either the currently selected text, the current block or the current section including subsections. Inline will inline the complete referenced file at the current include; optionally it can provide a preview, inline all occurrences of the file and delete the included file afterwards. All of these changes can be undone (Ctrl+Z).

When inlining includes, tags to include partial content are not honored. Please feel free to contribute to InlineIncludeProcessor for this.

While this is a preview release, please comment on naming of menu items, functionality and corner cases. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by ahus1** [comment]
Side note: for the inlining to work the include needs to be resolvable by IntelliJ. Currently variable names in include file names are not resolved. This will be part of a different issue.

**Comment by mojavelinux** [comment]
I love the feature. I'm not sure about the use of the term "inline" in this context, though. In AsciiDoc, "inline" means an element that is sandwiched between text (in the line). If we use it for another purpose, there might be confusion about what it means. In particular, AsciiDoc does not support "inline includes", and a user may be misled to think that's what they're getting. "inject" or "insert" would be better, I think.

**Comment by rdmueller** [comment]
very cool and works like a charm. This will be my favorite feature!

**Comment by abelsromero** [comment]
I tested the "Disable include" option to see what happens and it works as expected. The thing now is, how I re enable include extraction? This seems to be a global configuration (not per project) and there's no option in the AsciiDoc plugin configuration panel.
And even, deleting the `asciidoc.xml` in my .ideaXX configuration directory did not restore it.

**Comment by ahus1** [comment]
@abelsromero - please go to the Settings and type "include" in the search bar. This leads you to Editor -> Intentions, where you can enable/disable the Intentions for Asciidoctor. Each has a preview.

**Comment by ahus1** [comment]
@mojavelinux - there might be a clash of contexts here: for a developer refactoring code there is "extract method" and "inline method". This is how this feature behaves. Instead of methods this is about includes. 

Maybe I could write "Inline/Extract include::[]" and "Extract/Extract Include Blockmacro"? Not sure if it is getting better...

**Comment by mojavelinux** [comment]
I think if it was written "inline include directive" then it would be clear. It needs to be clear that "inline" is a verb, not an adjective.

**Comment by ahus1** [comment]
@mojavelinux - thanks, will use that wording in the next prerelease.
