### ISSUE TITLE
Refactoring of Markdown-style horizontal rule

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#272]
AsciidoctorJ supports several styles of markdown style rules: 

```
---
- - -
***
* * *
```

"The motivation here is to ease migration of Markdown documents to AsciiDoc documents." (from user's manual)

The AsciiDoc way is to have 

```
'''
```

as a horizontal rule. 

Should there be an inspection & quick-fix for this?

I'd love to hear comments (summoning @rdmueller)

**Comment by rdmueller** [comment]
IMHO, it could make sense to create inspections and quick-fix for several of these markdown rules (for instance the headings too) but not a priority.

**Comment by ahus1** [comment]
@rdmueller - so "several of these markdown rules" would be not all of them? For which of these would you like to have a warning, for what other not? 

Headings already have a warning & quickfix. If you see a markdown-style-heading is missing a warning, please post a code example.

**Comment by rdmueller** [comment]
> so "several of these markdown rules" would be not all of them? For which of these would you like to have a warning, for what other not?

With "several" I tried to say "all of which we are aware" instead of just single ones :-)
I think the foll list can be derived from this part of the docs: https://asciidoctor.org/docs/asciidoc-vs-markdown/

Cool, I wasn't aware of the warning for the heading.

**Comment by bbrenne** [comment]
Fix in #302

**Comment by ahus1** [comment]
This change is now available as part of pre-release 0.28.24.

Pre-releases of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
