### ISSUE TITLE
Respect imagesdir when resolving image paths in source file

### ISSUE THREAD

**Issue by alshain** [asciidoctor/asciidoctor-intellij-plugin#275]
When typing `images::` and invoking auto-complete, completions are provided seem to be based on the current file's directory.

However, using `imagesdir: ./img` for example at the top of the file, those paths are relative to a subdirectory, which neither the auto completion nor the ctrl-click thing processes correctly.

https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/b4ffa3a9a561de6ddd4256052cbf45fbc4f64807/src/main/java/org/asciidoc/intellij/psi/AsciiDocBlockMacro.java#L48

I'm guessing here one would need to detect 1) that an image path is being processed 2) the `imagesdir` thing is used and make use of a  `PsiReferencesProvider`.

This would probably solve both things, as well as allow IntelliJ to automatically update the image paths when renaming files.

#253

**Comment by alshain** [comment]
Maybe I can take a look at the PsireferencesProvider bit later this week.

**Comment by ahus1** [comment]
@alshain - I look forward to see a solution here! Please note: variables (like `:xx:`) currently have only lexer and highlighting support, but no Parser/Named Element support at the moment. 

Let me know if you want to tackle this as well, or if you want that to be solved before.

**Comment by ahus1** [comment]
@alshain - attributes now have PSI and names element support as part of #243; this might help a bit here.

**Comment by ahus1** [comment]
I'm starting working on this. Current plan: replace FileReferenceSet in AsciiDocBlockMacro with my own implementation to resolve variables in general and taking into account imagesDir for all image::[].

**Comment by ahus1** [comment]
The preview release 0.28.15 now resolves attributes in macros, supports ".." and respects the imagesDir for images macros. It also supports inline macros (previously only block macros were supported). 

As part of the suggested completions also shows ".." and all attributes that resolve to an existing file or directory. Attributes are shown in the list with the resolved value.

You can navigate using Ctrl+Click and Ctrl+B to each of part of the path.

As of today the discovery of attributes in a compact definition like this 
```
ifndef::imagesdir[:imagesdir: ../images]
``` 
is not supported in the lexer/paser, please use the longer variant
```
ifndef::imagesdir[]
:imagesdir: ../images
endif::[]
```

**Comment by ahus1** [comment]
please comment here with 
* corner cases that I might have missed
* ideas on how to restrict the list of auto-complete elements to relevant file types and/or directories depending on the macro name
* additions to the macro names that accept files in their body. As of today this allows for "image", "include", "video" and "audio" plus asciidoctor diagram types.

**Comment by ahus1** [comment]
This is in available in the latest public release of the plugin (0.28.17+) in the regular channel.
