### ISSUE TITLE
Edit Fragment for source blocks broken in 0.28.2

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#276]
When editing a [source] block as a fragment of the respective language, there is an exception 

```
java.lang.ClassCastException: class com.intellij.psi.impl.source.tree.LeafPsiElement cannot be cast to class org.asciidoc.intellij.psi.AsciiDocListing (com.intellij.psi.impl.source.tree.LeafPsiElement is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @3b084709; org.asciidoc.intellij.psi.AsciiDocListing is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @7d63fecc)
	at org.asciidoc.intellij.psi.AsciiDocPsiElementFactory.createListing(AsciiDocPsiElementFactory.java:36)
	at org.asciidoc.intellij.psi.AsciiDocListing$Manipulator.handleContentChange(AsciiDocListing.java:198)
	at org.asciidoc.intellij.psi.AsciiDocListing$Manipulator.handleContentChange(AsciiDocListing.java:189)
```

Editing in the fragment including reformatting should update the parent document. 

```
[source,json]
----
{
     "hi": "ho"
}
----
```

AsciiDoc Plugin Version: 0.28.2

**Comment by ahus1** [comment]
A fix is available in release 0.28.3.

A new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

@wimdeblauwe - please give it a try: with "Edit Fragment" you should be able to reformat a listing as you asked for.

**Comment by wimdeblauwe** [comment]
I just tried that version by adding the EAP repo, but now nothing works anymore. There is not even code completion and I don't see any Edit Fragment option as well:

![image](https://user-images.githubusercontent.com/1115823/59828709-deb0e800-933b-11e9-8fa1-f084149af660.png)

**Comment by ahus1** [comment]
@wimdeblauwe - I'm sorry to hear that it is not working for you. 

I currently try out different upgrade scenarios and snippets to locate the problem. 

Could you please post a code snippet of asciidoc that doesn't show highlighting?

The following snippet provides highlighting for me (for parser reasons the final "----" needs to be terminated by a newline. 

```
[source,json]
----
{
  "hi": "ho"
}
----

```

![screenshot](https://user-images.githubusercontent.com/3957921/59844545-740fa480-935b-11e9-890d-02cefcd96660.png)

**Comment by wimdeblauwe** [comment]
The newline was indeed the problem! Maybe you could add the `----` lines automatically when a user selects a language from the popup that appears after you type `[source,` to avoid the problem? Or have a button in the toolbar to add:

```[source]
----
----
````

with the newline?

What I do see if I edit a Java fragment is that there is red line because the class name does not match the file name:

![Screenshot 2019-06-20 at 14 13 22](https://user-images.githubusercontent.com/1115823/59848621-e7b6af00-9365-11e9-9c76-6cea2d25a1b9.png)

**Comment by ahus1** [comment]
> What I do see if I edit a Java fragment is that there is red line because the class name does not match the file name:


@wimdeblauwe - the syntax highlighting works best with JSON or YAML where the file name is not an issue. 

For languages like Java it is not of so much use, as the file name needs to match. There are probably other inspections you'll come across. You can disable these inspections, but that would affect all Java files and I wouldn't recommend that. The plugin can't instruct IntelliJ to behave differently for injected language block than on standard Java code.

Alternatively you can go to the plugin settings and disable language injection for Java.

But I have a different scenario that I suggest: I found that I usually don't want to have a whole Java source file, but snippets of it. Therefore I put the Java code in a separate file, use include with tags like this. Benefit: you can compile the code and also run unit tests against it before publishing the document.

````
.Pick a block
[source,java]
----
include::example.java[tag=sop]
----
<1> this is your first line of Java
````

````
public class Example {
    public static int main() {
        // tag::sop[]
        System.out.println("Hello world!"); // <1>
        // end::sop[]
    }
}
````

**Comment by ahus1** [comment]
> Maybe you could add the ---- lines automatically when a user selects a language ...

There is "Statement Completion" (Shift+Ctrl+Enter) already built into the plugin. Once you have selected the language and press these keys, the lines will be added automatically and the cursor will be placed at the right place. 

Starting from release 0.28.4 it will add the necessary newlines at end of files. Even better: from this release onwards the new lines are no longer necessary for most delimiters at the end of the file.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by wimdeblauwe** [comment]
> But I have a different scenario that I suggest: I found that I usually don't want to have a whole Java source file, but snippets of it. Therefore I put the Java code in a separate file, use include with tags like this. Benefit: you can compile the code and also run unit tests against it before publishing the document.

I am aware of that, I wrote [a book](https://www.infoq.com/minibooks/spring-boot-building-api-backend/) with that system :)

But interesting to hear that you can't selectively disable certain inspections for the asciidoc editor, a pity, but not a big deal.

**Comment by ahus1** [comment]
Apparently I've accidentally conjured a mansplaining situation here, I am sorry, please excuse this. 

I'll comment here if I come across a different solution. For now I consider this issue resolved.

**Comment by wimdeblauwe** [comment]
> Apparently I've accidentally conjured a mansplaining situation here, I am sorry, please excuse this.

Don't sweat it, you could not have known that :-) Keep up the great work on the plugin!
