### ISSUE TITLE
Improve Darcula theme support

### ISSUE THREAD

**Issue by bodiam** [asciidoctor/asciidoctor-intellij-plugin#28]
The initial support is there, but needs some finetuning. See here:

https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/21#issuecomment-64713236

**Comment by checketts** [comment]
Is there somewhere I can drop my own CSS files in a project or override directory to customize the/improve the Darcula rending without having to build a new plugin?

**Comment by bodiam** [comment]
You can download the jar, extract it, change the css, and zip it back together. But if you have some good changes, just send me a pull request and I'll release a new version!

**Comment by ahus1** [comment]
The JavaFX preview now has darcula support - available as release 0.16.1 from the github releases page. 

The file https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/src/main/java/org/asciidoc/intellij/editor/javafx/darcula.css is a simple CSS override of the original AsciiDoctor CSS classes. Any elements that I've missed I'd prefer a CSS snipped and/or AsciiDoc example. 

For now I'm closing this ticket.
