### ISSUE TITLE
inject absolute location of .asciidoctorconfig file

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#280]
the `.asciidoctorconfig` file is quite useful but also has limitations.
It helps to render image in sub documents by setting the correct `imagesDir` path for the sub documents, but you have to set it for each folder or use an absolute path which depends on the folder the code has been checked out to.

So, @ysb33r showed me a cool workaround with Gradle and a template for the `.asciidoctorconfig`:

https://twitter.com/ysb33r/status/1142820372590604291

But I think it could be a trivial change to how the `.asciidoctorconfig` mechanism works now to avoid this extra effort:

What if the plugin would inject the *location of the `.asciidoctorconfig` file* when prepending the file? This way, you could specifiy absolute paths relative to the `.asciidoctorconfig` file like this:

```
//injected path
:ASCIIDOCTOR_CONFIG_LOCATION: c:/Users/me/projects/test

//correct imagesDir
:imagesDir: {ASCIIDOCTOR_CONFIG_LOCATION}/src/docs/images
```

I think this would even work for Git submodules and Gradle subprojects.

Why not the Gradle Project-Root? I think this mechanism is even more flexible.

**Comment by rdmueller** [comment]
As far as I can see, this would be an easy contribution to start with, so if the suggestion above is considered to be OK, I would like to start with the implementation.

As I can see the following tasks have to be done:

[ ] inject absolute path of config file here: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/9b6d15fa6e9491945ae54d9f68bf3c6107f21dd1/src/main/java/org/asciidoc/intellij/AsciiDoc.java#L263
[ ] consider offset calculation for error messages https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/73812be3ffb7e2df7ee394eb7a25bc9039f2c118/CHANGELOG.adoc#L190
[ ] update Changelog
[ ] update Feature-List
[ ] update Wiki https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-project-specific-configurations

**Comment by mojavelinux** [comment]
I'm not a huge fan of the all uppercase since, by default, AsciiDoc attributes get forced to lowercase. I would recommend using something like `asciidoctorconfigdir`. That's more consistent with how attributes are set elsewhere. If you prefer hyphens in there somewhere, I wouldn't be opposed to it.

**Comment by ahus1** [comment]
@rdmueller - this sounds like a reasonable case to add some functionality to the plugin. 

Some additional thoughts: the suggested variable 'asciidoctorconfigdir' sounds quite specific to the asciidoctorconfig. 

What about adding a variable 'projectbasedir' that would contain the absolute path to the root of the project?

This might be more accessible for users: 
* variable is available even without .asciidoctorconfig in project
* can be used inside any document and .asciidoctorconfig

How to implement: 
* Can be be set inside AsciiDoc.java in method getDefaultOptions - no need to recalculate any offset. It seems that a projectBasePath is present in the instance already.

What this solution does *not* provide you:
* a base path that is specific to each .asciidoctorconfig file

Let me know what you think...

**Comment by rdmueller** [comment]
@ahus1 I also thought about the `projectBasePath` but I think it is not clear where it will point to.
What if I include some docs via Git submodule? Where is then the `projectBasePath`?

Or if I open my docs in intelliJ with the `/src/docs` folder as base for intellij and not the project base folder?

Maybe it makes sense to implement both features to take care of different use cases...

**Comment by ahus1** [comment]
@rdmueller - thank for sharing your thoughts. I'm happy to have both variables. 

When you add new variables, please also update AsciiDocBundle.properties with documentation about these two variables.

**Comment by ahus1** [comment]
I've created a green "ready for development" tag for this issue :-)

**Comment by ysb33r** [comment]
> I also thought about the projectBasePath but I think it is not clear where it will point to.
What if I include some docs via Git submodule? Where is then the projectBasePath?

Is this only for IntelliJ. Then I would recommend rather injecting attributes named `intellij-projectdir` and `intellij-moduledir`. (This will be in a similar vein to the Gradle plugin injecting attributes called `gradle-projectdir`, `gradle-project-group` etc.).

**Comment by rdmueller** [comment]
@ysb33r good point...

the property will be injected to be used within the `.asciidoctorconfig` file.
The idea of the `.asciidoctorconfig` file could also be picket up by other plugins like the one for Atom or the one for Eclipse.

So how about naming it something like `asciidoc-preview-configdir` ?

> There are only two hard things in Computer Science: cache invalidation and naming things.
> -- Phil Karlton

**Comment by ahus1** [comment]
0.28.11 is now available as a new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
