### ISSUE TITLE
Broken link to IDEA-213110 issue on wiki

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-intellij-plugin#281]
[Blurry preview](https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Blurry-preview#how-do-i-know-that-i-am-affected) wiki page has broken link to IDEA-213110 issue, it should be https://youtrack.jetbrains.com/issue/IDEA-213110 . Unfortunately, I failed to find how I can edit or make a PR for wiki page.

**Comment by ahus1** [comment]
Thanks for reporting this. I fixed the link. 

Unfortunately public pull requests are not available for Wikis. The only alternative option is to allow public write access to the wiki. Maybe we'll need to move it to a proper documentation site backed by a git repository at some point.

I hope you found the article useful. If you have additions, comments and corrections, please let me know.

**Comment by slonopotamus** [comment]
> I hope you found the article useful

Absolutely, thank you.
