### ISSUE TITLE
Save image context menu not showing up on macOS

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor-intellij-plugin#283]
Using macOS 10.14.5 with IntelliJ 2019.1.3 and IntelliJ Asciidoc plugin 0.28.5, the right-click option to save a (plantuml) diagram that is rendered by the plugin is not working.

**Comment by wimdeblauwe** [comment]
I have cloned the sources and following the getting started guide. I see that the right-click is implemented in `processImages.js`. Can I add `console.log` statements there? If so, where will the output be printed?

**Comment by wimdeblauwe** [comment]
What might be interesting is that according to this SO answer, you can know the HTML element you click on from the Java side: https://stackoverflow.com/questions/38391522/javafx-webview-context-menu

Might be an alternative ?

**Comment by wimdeblauwe** [comment]
I just tried it out, and it seems to work fine, by adding this code:

```
myWebView.setOnMousePressed(e -> {
            if (e.getButton() == MouseButton.SECONDARY) {
              JSObject object = (JSObject) myWebView.getEngine().executeScript("document.elementFromPoint("
                + e.getX()
                + "," + e.getY() + ");");
              System.out.println("object = " + object);
              if (object instanceof HTMLImageElement) {
                String src = ((HTMLImageElement) object).getAttribute("src");
                System.out.println("src = " + src);
                ApplicationManager.getApplication().invokeLater(() -> runFX(() -> {
                  bridge.saveImage(src);
                }));
              }
            }
          });
```

**Comment by ahus1** [comment]
Nice! Could you please create a pull request for the version that works on Mac? I'll then test it on Windows. 

Once it works on both OS I can remove the JavaScript handler and merge it.

Thanks!

**Comment by wimdeblauwe** [comment]
Can I create a branch directly on this repo? Or should I go via a fork?

**Comment by ahus1** [comment]
Please go via creating a fork first, then create a PR from a branch in the fork. 

Creating a pull request from a branch in this repo would require you to be a member of the organisation.

**Comment by ahus1** [comment]
This is now available in release 0.28.7.

A new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

I will also publish it to the standard channel.

**Comment by ascheman** [comment]
It works great, thanks:
![image](https://user-images.githubusercontent.com/456000/60385856-74601c00-9a8e-11e9-8579-f9961dc8b012.png)

However, the file is stored without any extension (`.png` in this case). I would prefer to get a respective file name extension to easier identify the kind of file. Would you like to see a new issue for this, @ahus1?

**Comment by ahus1** [comment]
@ascheman - this is an issue currently present on mac - on a Windows (probably Linux as well) you would be able to select the file type from a drop down. 

We're collecting all issues as part of #282. Please comment on this ticket. This might be implicit in one of the comments in there already, but better have it explicitly.
