### ISSUE TITLE
Typo in project specific configurations wiki page

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor-intellij-plugin#286]
On the Wiki page https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-project-specific-configurations there is this text:

> The handling will be a mixture of behaviors like .asciidoctorconfig and .gitconfig.

This probably needs to be:

> The handling will be a mixture of behaviors like .editorconfig and .gitconfig.

Since it links to editorconfig.org

**Comment by ahus1** [comment]
Thanks, fixed!
