### ISSUE TITLE
UI not refreshing (either preview or editor)

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#288]
@rdmueller sent in a video showing an IDE where the editor or the preview now update. This affects toolbar, editor tabs, editor and preview. 

This issue will try to analyze this further. As of opening this issue this is not reproduceable for me.

**Comment by ahus1** [comment]
I was still not able to reproduce the issue locally.

Release 0.28.8 is now available as a pre-release. I studied the IntelliJ Markdown plugin and aligned it in some places that might affect the refresh. 

It is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

If this issue appears for any user, please provide the version number of the plugin and the IDE version information (Help -> About, click on 'Copy to Clipboard' and paste the contents of your clipboard to the new comment)

**Comment by rdmueller** [comment]
IntelliJ IDEA 2019.1 (Ultimate Edition)
Build #IU-191.6183.87, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by rdmueller** [comment]
Just upgraded everything:

AsciiDoc V0.28.7
IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

still the problem remains...

**Comment by rdmueller** [comment]
I just applied the "Blurry fix" (`-Dsun.java2d.uiScale.enabled=false`) and can't reproduce the problem any more. 
Removed the fix (the whole content of the file) and the problem re-appeared!

**Comment by ahus1** [comment]
@rdmueller - I see that you updated to 0.28.7, but my latest change for this issue was included in 0.28.8.

Could you please try again with 0.28.8 if the "Blurry fix" is necessary for that release? What scaling did you have when you tried it? Maybe you even used two screens with different scaling ratio? 

Thanks!

**Comment by rdmueller** [comment]
Sorry, you are right - I wasn't on the early access path.
I tried again with 0.28.8 and the "Blurry fix" is still necessary.
For these test I use a scaling of 250% (see image)
It is always the same scaling and display - it is a "demo" account on my notebook.

I start to wonder if it may have to do with my build in graphics card...

![image](https://user-images.githubusercontent.com/1856308/60543115-c666a300-9d15-11e9-9c0b-29be407ad31d.png)

**Comment by ahus1** [comment]
I'm closing this as I assume this is fixed with JBR 11.
