### ISSUE TITLE
The zoom level in the preview grows too fast

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#295]
hm. on my machine, the zoom level grows too fast - I guess that has to do with the high-dpi screen...

... and I don't have a middle mouse button - can we add a reset button to the menu bar?

_Originally posted by @rdmueller in https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/199#issuecomment-508582216_

**Comment by rdmueller** [comment]
I just connected a mouse to my system:
even with the mouse, the zoom level grows quite fast (but it is now better to control) and I can only zoom in, not out.

**Comment by ahus1** [comment]
Debugging this issue I found that using a touchpad the application received zero-delta-scroll events. These are now filtered out. Also the fast growing and not zooming out should now be fixed as the zoom level was applied twice. There'll be a pre-release soon for this.

**Comment by ahus1** [comment]
0.28.11 is now available as a new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

Please give it a try if this fixes it for you. Thanks!

**Comment by rdmueller** [comment]
Changing the zoom level with my mouse now works fine

With the touchpad, the behaviour changed the following way:
- when I try to zoom, it immediatly switches to the minimul size, zoom out
- I can't zoom in again
- ctrl-wheel click does not work

**Comment by ahus1** [comment]
I can reproduce the bug for the touchpad; I'll have to investigate (it works in development mode, but not in my local IDE, might be a version issue, let's see...)

**Comment by ahus1** [comment]
I changed it in 0.28.12. Now it works with a touch pad for me in all my environments. Could you please give this version a try? As usual, it is available as a pre-release. Thanks!

**Comment by rdmueller** [comment]
works like a charm!
This issue can now be closed from my point of view.
Thanx for all your cool work!
