### ISSUE TITLE
Add ability to disable "include" errors

### ISSUE THREAD

**Issue by melix** [asciidoctor/asciidoctor-intellij-plugin#296]
Since a few releases, the plugin tries to be smart and validate paths to includes. However, we have a setup which is more complex than just a relative path to docs. We process files before they are rendered (copied in a main directory) and also have custom include macros.

The consequence is that now the editor is bloated with red errors, as illustrated in the following screenshot:

![Selection_294](https://user-images.githubusercontent.com/316357/60723014-c5f72380-9f32-11e9-8d75-678fc8481573.png)

I don't really care about the _editor_ not resolving includes here, so it would be nice if the plugin would allow disabling those errors.

Plugin version: 0.28.7

```
IntelliJ IDEA 2019.1.3 (Community Edition)
Build #IC-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.1.5
```

**Comment by ahus1** [comment]
Hi @melix, thanks for sharing this. I see that this is not very good to work in. 

I could think of a checkbox to disable showing AsciiDoc error messages in the editor (via settings). For expert users I could imagine a regex based filter for error messages not to show. 

Can you provide me a screen shot of the error message? 

The plugin allows you to register AsciiDoc extentions also for the preview; maybe in your situation you could register either a custom include plugin or a dummy replacement that doesn't show error messages. This is currently experimental, you can [read more about it here](https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-for-Asciidoctor-Extensions).

**Comment by ahus1** [comment]
Another example: This repo is using an glob-include extension; see https://github.com/ahus1/asciidoctor-deepdive/tree/master/include-files and https://github.com/ahus1/asciidoctor-deepdive/tree/master/.asciidoctor/lib

**Comment by ahus1** [comment]
Version 0.28.12 is available as a pre-release. It allows you to disable showing the errors in the editor. Instead the errors will appear in the IDE console like before. 

I hope this improves your situation. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by melix** [comment]
Wow that was quick, thanks!

**Comment by ahus1** [comment]
I've recognized your code samples to be from the Gradle repository.

I took a quick look and added two files to improve the preview handling, see https://github.com/ahus1/gradle/tree/improve_intellij_docs_preview 
Locally the documentation still builds as before.

Please let me know if you want a PR for this.

I didn't find SampleIncludeProcessor referenced in the docs - maybe you can point me to it?

**Comment by ahus1** [comment]
The original request to disable error messages highlighting in editor is complete, therefore I close this ticket.

**Comment by EmanuelCozariz** [comment]
Is this feature still available? I cannot find the disabling of errors in intellij asciidoc plugin. Note there is no '_Show AsciiDoc errors and warnings in editor_' option present.
Could someone support, maybe I did not configure correct?

Thank you.
![image](https://user-images.githubusercontent.com/55085919/71413044-1e44ed80-2659-11ea-8ee0-8c95cfb3726d.png)
