### ISSUE TITLE
Paste images from clipboard

### ISSUE THREAD

**Issue by gamename** [asciidoctor/asciidoctor-intellij-plugin#298]
How do you (or can you?) paste an image into an .adoc file?  The ["Markdown Navigator"](https://vladsch.com/product/markdown-navigator) plugin allows this.

Do you support, or plan to support, something similar?

Thank you,
-T

**Comment by ahus1** [comment]
There is currently no support for paste-an-image. The only paste support we have is paste-as-table (added by @bbrenne in #290), which is available in our pre-releases and will soon be released. 
Pre-releases of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

I'd be happy to see "paste-an-image" in this plugin as well, but as of today this is not on any road map. 

I would be happy to see a pull request for this. Maybe the changes required for #290 could guide a volunteer. I'd be happy to support anyone who wants to prepare a pull request.

**Comment by bbrenne** [comment]
Where would the image file be copied? Same directory as the asciidoc file? Should we take the imagesdir into account?
Should be develop a menu action or just the ctrl-v, apple-v?

**Comment by ahus1** [comment]
I think a menu action would be a good start. It should open a dialogue asking for a file format (jpeg/png) and should provide an error/hint if the current contents are of type text and won't be paste-able as an image. 

Following that asking for a file name would be appropriate, maybe similar to the dialogue of saving an diagram from the preview? The user could also choose a folder, with the folder of the image as default. Discussing how the save-image works, the dialogue on Mac doesn't show the file type, therefore it needs to be before.

Having a menu item would make the functionality "discoverable". Hooking into Ctrl-V would be nice as long as it doesn't interfere with pasting text. 

These are my thoughts - happy to hear yours.

**Comment by bbrenne** [comment]
I just made a pull request for that one.

#300

**Comment by ahus1** [comment]
The PR is now merged. The feature will be part of the next preview release.

**Comment by ahus1** [comment]
There is now pre-release 0.28.23 that contains this feature. 

Please give it a try and comment in this ticket. 

Pre-releases of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by ascheman** [comment]
Tested on OSX (18.7.0), IntelliJ IDEA 2019.2 (Ultimate Edition): Works as expected, great!

**Comment by Musaizen** [comment]
Hi, is it possible to save the image with the current date without specifying it manually ?
Thanks
