### ISSUE TITLE
Run test gutter popup displays wrong test name

### ISSUE THREAD

**Issue by tfeuerba** [asciidoctor/asciidoctor-intellij-plugin#301]
AsciiDoc Plugin Version: v0.28.21

IDE Name and Version: IntelliJ IDEA 2019.1.3 (Ultimate Edition)
Build #IU-191.7479.19, built on May 28, 2019
JRE: 1.8.0_202-release-1483-b58 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

With the newest update, the run test popup for Java shows the test source as the URL encoded file name:

![image](https://user-images.githubusercontent.com/30596777/61612842-ebd53580-ac5f-11e9-9c3e-c8de6442f151.png)

When I disable the plugin, the test name displays correctly.

**Comment by ahus1** [comment]
I can reproduce the issue locally and will take a look.

**Comment by ahus1** [comment]
Thank you for tracking this issue down to the AsciiDoc plugin. I'm sorry that this mistake caused you trouble. 

A new release 0.28.22 is available from GitHub releases and should be available from the IntelliJ plugin repo soon. As I was able to reproduce it locally, I was also able to confirm that the change resolves this issue. 

Please comment here if it doesn't resolve the issue for you. Please open additional issues if you find other problems.
