### ISSUE TITLE
Support for URLs in editor

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#307]
The editor should have 
* highlighting for URLs that appear in plain text
* offer Ctrl+click for URLs

The make-link action should know about the context when turning text or a URL to a link with a text. Selection and cursor should be placed so that the user can continue typing.

**Comment by ahus1** [comment]
Hi @bric3 & @Mogztter, you asked for attribute extraction in general and for URLs in partikular (#308, #304). 

The new pre-release 0.29.1 adds some parser and editor elements that builds paves part of the road towards these features: 
* The updated lexer now recognizes URLs in text
* URLs and email addresses got references that the editor will highlight when holding Ctrl and moving the mouse or open when using Ctrl+B
* Attribute declaration's values can now contain references to other attributes; the usual highlighting and navigation works
* When creating by using the "make-link" editor action (either from a URL or from plain text) the editor will update the selection automatically (something that bothered me for quite some time)

As usual, a short screen recording tells more than an a lot of text:

![link-ehancement-editor](https://user-images.githubusercontent.com/3957921/62409463-4499bc00-b5d8-11e9-971a-9eace9bf582e.gif)

Please give it a try and let me know if there are corner cases that I forgot, or if there are some low-hanging fruits that should be part of this feature. 

With this additional lexing and parsing in place, the refactorings in the two tickets you opened are coming closer.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by Mogztter** [comment]
I gave it a try and URLs used as terms in a definition list are not recognized as URLs, for instance:

```
https://www.asciidoctor.org[Asciidoctor]:: Asciidoctor is a fast, open source text processor and publishing toolchain for converting AsciiDoc content to HTML5, DocBook, PDF, and other formats. 
```

I've also noticed that attributes navigation does not work in this context:

```
:hadoop-webhdfs: https://hadoop.apache.org/docs/stable/hadoop-project-dist/hadoop-hdfs/WebHDFS.html

{hadoop-webhdfs}#Get_Content_Summary_of_a_Directory[`GETCONTENTSUMMARY`]:: Get content summary of a directory
````

<img width="772" alt="Capture d’écran 2019-08-06 à 17 42 31" src="https://user-images.githubusercontent.com/333276/62554560-9b6df280-b871-11e9-86df-1b4334576e0e.png">


On a side note, on macOS, even if I add https://plugins.jetbrains.com/plugins/eap/list?pluginId=7391 as an additional repository I'm unable to install the EAP version 😞 

As you can see, the search returns the plugin twice but I couldn't tell which one was the EAP release (and which one was the stable release). I tried to install the plugin but I've always got version 0.28.27:

<img width="1136" alt="Capture d’écran 2019-08-06 à 17 32 49" src="https://user-images.githubusercontent.com/333276/62553851-6319e480-b870-11e9-8ff9-49d403e46008.png">

So I had to install the plugin from disk using the zip file: https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases/tag/0.29.1 (it's working fine).

**Comment by Mogztter** [comment]
Not sure if it's intended or not but windows path and relative path are not recognized:

```
link:\\server\share\whitepaper.pdf[Whitepaper]

link:index.html[Docs]
```

<img width="573" alt="Capture d’écran 2019-08-06 à 17 51 34" src="https://user-images.githubusercontent.com/333276/62555371-1552ab80-b873-11e9-8d35-109ffd1ed257.png">

Examples are from the AsciiDoc Syntax Quick Reference: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#links

**Comment by ahus1** [comment]
@Mogztter - thank you for pointing me at these examples, this is very helpful! I've started working on this. Once a new preview release is available I'll update this ticket.

**Comment by bric3** [comment]
Regarding plugin version, I've got a similar problem, although I don't have the duplicate plugin, I'm unable to tell if the update is an EAP or not.

![Screen Shot 2019-08-07 at 12 03 48](https://user-images.githubusercontent.com/803621/62614387-965d8180-b90b-11e9-944e-11b6d753a5bf.png)

But maybe this is intended, since the version is marked as prerelease in github. Although the changelog shown in IJ could make that clearer.

**Comment by bric3** [comment]
@ahus1 I'm not sure from what you described, but is there an action (either via alt+enter, or else) to extract the url to an attribute ?

**Comment by ahus1** [comment]
@birc3 - the action to refactor it not part of this ticket. This ticket is about showing URLs correctly in all places first. It will be part of the following ticket #308 to extract an URL as attribute. 

Regarding EAP: yes, there is currently no way to see if a version is a EAP version. As versions are promoted later on from EAP to the regular repo, the artifacts will not change. The UI of IntelliJ doesn't show the source of an update for now. 

You can only only go by version number: when I ask for testing a preview-release 0.29.1 or later, check that you have a version 0.29.1 or later installed.

**Comment by ahus1** [comment]
@Mogztter - the issue you describe picking the right version from the EAP repository: I tried to reproduce with 2019.2, and I am sure it worked with 2019.1 as well at least when upgrading an existing plugin. What version of IntelliJ are you using? Thanks!

**Comment by Mogztter** [comment]
I must have missed something.
I did another try on WebStorm and it worked. I was also able to upgrade to 0.29.2 on IntelliJ IDEA (where I installed the plugin from disk). I'm using IntelliJ IDEA 2019.1.2:

```
IntelliJ IDEA 2019.1.2 (Ultimate Edition)
Build #IU-191.7141.44, built on May 7, 2019
JRE: 1.8.0_202-release-1483-b49 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
```

**Comment by ahus1** [comment]
@Mogztter - there is a new pre-release 0.29.3 that handles all the examples on the quick syntax reference and the examples with the definition list (`::`)

It also handles relative and absolute `link:[]` to local files. Please note
* these references will only work if the file exists. If the file doesn't exist, it will not be clickable
* if the path is separated by "/", each segment of path is navigateable (standard behavior in IntelliJ) and autocomplete works event with attribute references in the path.
* references to local files will open in the IDE, not in the browser (as I assume the user wants to edit them)

Examples for references to local files:

```
link:index.html[Docs]
link:c:\temp\test.adoc[]
```

This pre-release supports attribute references (`{attr}`) in lots of places now: descriptions of links, IDs, references, include and link paths. Using Ctrl+B on an attribute reference in a path gives the choice dialog "Choose Declaration" to navigate to the file or to the attribute declaration.

Please give it a try and comment in this ticket.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by ahus1** [comment]
I tested it over the last few days, and will release a version to the public repo later today.

**Comment by bric3** [comment]
@ahus1 that's awesome, thanks

**Comment by Mogztter** [comment]
Sorry I didn't have the time to test it again.

> if the path is separated by "/", each segment of path is navigateable (standard behavior in IntelliJ) and autocomplete works event with attribute references in the path.

That sounds amazing!

> I tested it over the last few days, and will release a version to the public repo later today.

🚀 👍
