### ISSUE TITLE
Guide user to enable word-wrap permanently for AsciiDoc

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#316]
# Situation 

A user performs the "activate word wrap" in the tool bar several times. She/he might not know that IntelliJ has a setting to make this permanent.

# Options

1. when the user toggles this multiple times, show a EditorNotification similar to "JavaFX could be enabled" (JavaFxCouldBeEnabledNotificationProvider) or "Preview might be blurry" (JavaFxMightBeBlurredNotificationProvider). The user could directly trigger "activate word wrap". In newer versions of IntelliJ the word wrap can be restricted to specific asciidoc extensions. By default this already contains "adoc", but the action should make sure that "adoc" (and all other AsciiDoc filename suffixes and/or the suffix of the current file) are included

2. make the "word wrap" permanent within AsciiDoc (?) this would actually provide to places to do the same, this should be avoided AFAIK. 

3. The state could be persisted on a per-file base; to me it is unclear how this would behave if the global setting changes; would that clear all file-specific settings? If we would implement this, we could put it into MyFileEditorState that already preserves some of the state.

# Suggestion

Implement Option 1 (please discuss if you think differently)

(this has been created after a user shared his experience in #314)

**Comment by rdmueller** [comment]
hm I guess this is the right place to add some counter:
https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/707dab97911b5d7aab00fa7c59a3f167a17ac519/src/main/java/org/asciidoc/intellij/actions/asciidoc/ToggleSoftWrapsAction.java#L19

I guess a counter could be implemented as static property?

**Comment by ahus1** [comment]
Looks good to me. The property (or a boolean result derived from the counter to show the notification) needs to be exposed. The minimal implementation of a EditorNotification would be a link to the wiki. Everything else is optional and could be implemented later.

**Comment by ahus1** [comment]
Will be part of next release.

![image](https://user-images.githubusercontent.com/3957921/73609770-33565a00-45d1-11ea-938f-5fb897d37b4d.png)
