### ISSUE TITLE
multi-line attributes support with "+"

### ISSUE THREAD

**Issue by luvarqpp** [asciidoctor/asciidoctor-intellij-plugin#318]
Formatting multi-line attributes does broke them. Also rendering by code highlight is broken for them. See two screenshots and sample here:

highlighting; before code format:
![multilineAttributes](https://user-images.githubusercontent.com/48614551/62847161-1b161a00-bcd5-11e9-84fc-bc004400df5e.png)

result of code formatting algorithm:
![multilineAttributesAfterFormat](https://user-images.githubusercontent.com/48614551/62847160-1a7d8380-bcd5-11e9-9309-dd5f7c370836.png)

Sample document snippet:
```
= RESTful Qaron API Specification
Ľubomír Varga <lubomir.varga@qpp.sk>
v{project-version}, 2019-08-12
:toc: left
:doctype: book
:keywords: rest api, documentation, restdocs, integration, hal
:icons: font
:numbered:
:description: This document is short. +
              Despite description is long.

This is than first paragraph of documentation.
```

Multi-line attribute format is [mentioned in recommended practices](https://asciidoctor.org/docs/asciidoc-recommended-practices/#document-settings).

AsciiDoc Plugin Version: 0.29.4

IDE Name and Version:
IntelliJ IDEA 2019.2 (Community Edition)
Build #IC-192.5728.98, built on July 23, 2019
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.0.0-23-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1910M
Cores: 8
Registry: git.explicit.commit.renames.prohibit.multiple.calls=false
Non-Bundled Plugins: DBN, Lombook Plugin, com.oliverlockwood.plugins.jenkinsfile, im.jeanfrancois.ideaplugins.ideafullscreen, manifold.ij, org.asciidoctor.intellij.asciidoc, com.intellij.lang.jsgraphql, org.intellij.scala, Docker, training

**Comment by mojavelinux** [comment]
Note that `\` is the preferred line ending to continue an attribute entry. `+` is considered legacy.

**Comment by luvarqpp** [comment]
> Note that `\` is the preferred line ending to continue an attribute entry. `+` is considered legacy.

Thanks, `\` works like expected.

Can you arrange to update given recommended practices documentation? I was not able to make best guess and find origin of given page in github project.

PS: It seems that there is more than single repo with similar info. I guess from this search: https://github.com/search?q=%3Adescription%3A+This+document+catalogs+a+set+of+recommended+practices+for+writing+in+AsciiDoc.&type=Wikis

PS2: I think that this issue is not an issue, so perhaps close it?

**Comment by mojavelinux** [comment]
It's documented here: https://asciidoctor.org/docs/user-manual/#splitting-attribute-values-over-multiple-lines

If you feel a documentation update is warranted, feel free to propose a revision.

**Comment by luvarqpp** [comment]
I was probably not exact in my last post. I mean, I would propose change to this document: https://asciidoctor.org/docs/asciidoc-recommended-practices/#document-settings
There is stated in example, that I can use plus sign. I would change it to backslash there. And I was not able to quickly find its github source (if it is there).

PS: I will try to learn asciidoc a bit more, but time is a constrain.

**Comment by ahus1** [comment]
@luvarqpp - please keep this issue open. This should be possible to include in the parser; maybe even have a hint for the user to describe the modern syntax.

**Comment by mojavelinux** [comment]
You were clear. I was just pointing out that if you want that change, please submit a revision.

**Comment by ahus1** [comment]
> And I was not able to quickly find its github source (if it is there).

@luvarqpp - there is an "edit" button at the top of the page. It takes to the referenced GitHub repo and page.

![edit](https://user-images.githubusercontent.com/3957921/62848567-89aaa600-bcdc-11e9-94cb-2d60f06b478e.png)

**Comment by luvarqpp** [comment]
My apology. I was searching for edit button on right side only (things like "fork me" and so on). I have done edit and I have made pull request: https://github.com/asciidoctor/asciidoctor.org/pull/878

**Comment by mojavelinux** [comment]
Thanks! Most appreciated! :gift_heart:

**Comment by ahus1** [comment]
I've pushed some changes to rectify this. The next version of the plugin: 

* supports both `\` and `+` as continuations for attribute values
* has an inspection that highlights the use of `+` as continuations in multi line attribute as a warning
* offers a quick-fix (Ctrl+Enter) to change `+` to `\` for multi line attribute values

![attribute-continuation](https://user-images.githubusercontent.com/3957921/62965041-785cb900-be04-11e9-87ae-b4a14cf847ff.gif)

This is NOT available as a pre-release, as I will first look into the other open issue as well.

**Comment by ahus1** [comment]
pre-release 0.29.5 is now available.
