### ISSUE TITLE
Go to declaration support for tags in include macro

### ISSUE THREAD

**Issue by luvarqpp** [asciidoctor/asciidoctor-intellij-plugin#322]
Implement "go to declaration" for tags in include macro. I would like to use "ctrl+click" on given tag (`showcaseMethod`) in include line (at the end). For example, see this document part:

```
Sample code showing how to get all TestCages-s (sorted and paginated).
[source,java]
.Java code from tests to show how to get all TestCages
----
include::{testsourcedir}/sk/qpp/TestCageHttpTest.java[tags=showcaseMethod]
----
```

In included file (TestCageHttpTest.java), there is tagged some part of code like this:
```
public void method1() {
}
// tag::showcaseMethod[]
public void sampleMethod() {
    doNothingAndShowItToTheWorld();
}
// end::showcaseMethod[]
```

Similar things had happened in #320 issue (with draft proposal also for this request).

**Comment by ahus1** [comment]
The next preview-release will recognize the tags in comments and provides find-references, Ctrl+B/Ctrl-click and rename.

Limitation: the line with the tag needs to be a a comment recognized by IntelliJ. I've tested it successfully with Java, XML and AsciiDoc comments in the respective files. 

Doesn't work (yet) with plain-text files as plain-text files don't have comments.

**Comment by ahus1** [comment]
I've reworked the discovery of tag/end so that it works in plain-text files as well. I'll update this ticket once the pre-release is available.

**Comment by ahus1** [comment]
A new pre-release 0.30.36 of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
