### ISSUE TITLE
Minor syntax highlighting issue with link in source tag

### ISSUE THREAD

**Issue by bric3** [asciidoctor/asciidoctor-intellij-plugin#327]
When a link is declared in the `[source,title=...]` the right brackets are mis-rendered, both are highlighted in orange, only the outmost should be highlighted I think.

```adoc
:url-hprof-heap: https://github.com/oracle/visualvm/blob/9a43222f488b8f9e9fba71363c4bcd056c532948/visualvm/libs.profiler/lib.profiler/src/org/graalvm/visualvm/lib/jfluid/heap/HprofHeap.java#L70-L109

[source,title={url-hprof-heap}[Hprof heap tags]]
----
    // dump tags
    static final int STRING = 1;
----
```

![image](https://user-images.githubusercontent.com/803621/64351837-4dc4e100-cffb-11e9-92c5-723c07a4f484.png)

The parser probably don't understand this kind of nesting. Yet the preview works fine.

**Comment by ahus1** [comment]
Thank you for reporting this. Never used that combination before...

**Comment by bric3** [comment]
No problem. Thank you for this plugin !!!!

**Comment by mojavelinux** [comment]
In this case, the value should be wrapped in single quotes.

```
[source,title='{url-hprof-heap}[Hprof heap tags]']
```

You could also write it as:

```
.{url-hprof-heap}[Hprof heap tags]
[source]
```

**Comment by bric3** [comment]
@mojavelinux Ah yes that's way better, thanks a lot for the suggestion !

**Comment by ahus1** [comment]
Release 0.30.6 adds highlighting support for attribute references both 

```[source,title='{url-hprof-heap}[Hprof heap tags]']``` 

and 

```.{url-hprof-heap}[Hprof heap tags]```

**Comment by bric3** [comment]
@ahus1 Cool thanks
