### ISSUE TITLE
Images paste folder settings (for Antora)

### ISSUE THREAD

**Issue by AndersonDev** [asciidoctor/asciidoctor-intellij-plugin#330]
Hi! Is it possible to change:

- Location of image file to save. For example: assets/images.
- Some files naming resolver. It should handle names, like: {name}-1.png (image-1.png).

**Comment by mojavelinux** [comment]
FYI, since Antora 2.1 the assets segment is no longer required.

Rather than handle this piecemeal, I think this should be part of a general
Antora support / awareness mode. Once the plugin recognizes the structure
(which is the point of the structure), it should activate automatically.

>

**Comment by ahus1** [comment]
Making the plugin Antora-aware sounds like a good idea to go. 

Users of Antora can help moving this issue forward by commenting here with conventions they when would like to see. You could comment as text, or specify scenarios: "Given a file X.adoc in folder, when an Antora is detected, a new image should be placed in folder X". You can also comment on how to detect Antora / what to look for.

**Comment by ahus1** [comment]
The upcoming release 0.30.25 will support this: the images folder of the current Antora module will be pre-selected on pasting an image. Please be aware that the folder needs to exist before pasting the image. The folder will not be auto-created on first paste.

When the image is pasted, the imagesdir will no longer be prefixed. Ticket #373 solves the preview mode. 

This ticket also add support for handling both variants of "attachments/images" and "images".

**Comment by ahus1** [comment]
Pre-release 0.30.25 is now available that includes this issue.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
