### ISSUE TITLE
TODO listing opens documents/changes focus

### ISSUE THREAD

**Issue by luvarqpp** [asciidoctor/asciidoctor-intellij-plugin#332]
When I open "TODO" view in InteliJ Idea (that thing at bottom named "6: TODO"), it will list me all files which does contain "TODO" word inside of them. I select first one (some Jenkinsfile). Than I use down arrow and perhaps right arrow (to unfold file and see actual TODO instances in given file). When I select first adoc file (and given file does not have openned editor window already), it will open editor with given document and switch focus onto given TODO line.

I expect to have behavior same as java/pom/whatever file.

Sidenote, when I press enter key at some TODO instance in given TODO view (tree view), it will open me an editor, change viewport to given TODO line, but focus stays in TODO view and I can continue browsing TODOs with arrows.

```
Some nice document.
// TODO make it look glorious
// One TODO is enough, but we can always have two or more...
```

AsciiDoc Plugin Version: 0.30.5

IDE Name and Version:
IntelliJ IDEA 2019.2.2 (Ultimate Edition)
Build #IU-192.6603.28, built on September 6, 2019
Licensed to IntelliJ IDEA Evaluator
Expiration date: October 5, 2019
Runtime version: 11.0.2+7-LTS amd64
VM: OpenJDK 64-Bit Server VM by Azul Systems, Inc.
Linux 5.0.0-25-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1910M
Cores: 8
Registry: 
Non-Bundled Plugins: DBN, Lombook Plugin, com.oliverlockwood.plugins.jenkinsfile, im.jeanfrancois.ideaplugins.ideafullscreen, net.seesharpsoft.intellij.plugins.csv, org.asciidoctor.intellij.asciidoc, com.intellij.lang.jsgraphql, org.intellij.scala, training

**Comment by ahus1** [comment]
Thanks for reporting this. Will be fixed in next upcoming release.

**Comment by ahus1** [comment]
Pre-release 0.30.9 is now available that contains this change.
