### ISSUE TITLE
error when generating mermaid graph through mmdc

### ISSUE THREAD

**Issue by davinkevin** [asciidoctor/asciidoctor-intellij-plugin#334]
When using `mermaid` as a graph tools, with its CLI, I have the following error in the IDEA UI:

![image](https://user-images.githubusercontent.com/1970922/65157278-c894ef80-da30-11e9-8f71-29e637f9aab9.png)

The `mmdc` command line has its hashbang defined like this: 

```node
#!/usr/bin/env node
...
```

From my point of view, the IDE doesn't find node, but don't know how to check if the path variable is accessible from the plugin context. 

The preview pane looks like this
![image](https://user-images.githubusercontent.com/1970922/65157436-072aaa00-da31-11e9-9b57-e5b134a0d510.png)

For the following document, which is pretty simple:

```asciidoc
= Example
:mermaid: /usr/local/bin/mmdc

[mermaid, communications, png, css="mermaid.css"]
----
graph TD
  A --> B
----
```

**More**: 
* the `mmdc` comand is availaible in the `$PATH`
* the `node` command is available in the `$PATH`

```
AsciiDoc Plugin Version: 0.30.6

IDE Version: 
IntelliJ IDEA 2019.2.2 (Ultimate Edition)
Build #IU-192.6603.28, built on September 6, 2019
Subscription is active until April 3, 2020
Runtime version: 1.8.0_202-release-b1491 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 8
Registry: 
Non-Bundled Plugins: Key Promoter X, Lombook Plugin, com.jetbrains.jbre.bintray.downloader, mobi.hsz.idea.gitignore, net.sjrx.intellij.plugins.systemdunitfiles, org.asciidoctor.intellij.asciidoc, org.jetbrains.plugins.go-template, BashSupport, com.intellij.plugins.html.instantEditing, izhangzhihao.rainbow.brackets, org.intellij.scala, com.intellij.kubernetes
```

**Comment by ahus1** [comment]
This seems to be a MacOS symptom that has previously been discussed in #191. The discussion pointed to https://depressiverobot.com/2016/02/05/intellij-path.html for causes and fixes.

Please let me know if this works for you. If it works for you, please consider adding a short entry to our Wiki. As I am not a mac user, I feed it hard to describe (or check).

**Comment by ahus1** [comment]
Closing issue as there is no feedback for more than two weeks. Feel free to comment, and I'll re-open the issue.

**Comment by davinkevin** [comment]
I did not have the chance to test it before today... 

I choose to use the following command (run in bash):

```bash
sudo launchctl config user path $PATH
```

And this is working perfectly 👍

**Comment by dfrommi** [comment]
@WuglyakBolgoink I have the same issue and could resolve it like this...

Add document attribute `mmdc` to tell the plugin where to find the executable
```
:mmdc: /usr/local/bin/mmdc
```

Edit the file `/usr/local/bin/mmdc` to point to the absolute path of `node`, rather than using `env`. Top of `mmdc` file then reads
```
#!/usr/local/bin/node
```

This will of course be reverted on any update of mmdc.
