### ISSUE TITLE
Cursor position when using "Make title"

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-intellij-plugin#341]
When the document is empty, the cursor is positioned before the `=` symbol:

![cursor-position-empty-file](https://user-images.githubusercontent.com/333276/66316713-7bfa5100-e918-11e9-869d-578df9cb53ab.gif)

I think it should be better if the cursor was after the `=` (with a space) so you can directly type the document title.

Another example when the document contains just a newline.
Here the whole line is selected, so if I start typing the document title it will remove the `=` symbol:

![cursor-position-select-all](https://user-images.githubusercontent.com/333276/66316714-7bfa5100-e918-11e9-87ab-9d4461ee17bf.gif)

I think the behavior should be consistent and the cursor should be positioned at the end of the line (ready to type the title).

**AsciiDoc Plugin Version:** `0.30.7`
**IDE Name and Version:**
```
IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 24, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-58-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: Batch Scripts Support, CMD Support, CheckStyle-IDEA, FindBugs-IDEA, JFormDesigner, org.asciidoctor.intellij.asciidoc, org.jetbrains.plugins.slim, BashSupport, com.dmarcotte.handlebars, com.jetbrains.lang.ejs, com.jetbrains.plugins.jade, com.wix.eslint, org.intellij.scala, org.jetbrains.plugins.ruby
```

**Comment by ahus1** [comment]
Thanks for raising this issue, this should be improved. 

The markdown plugin IntelliJ has has the option to increase/decrease the level of a heading with and up/down menu item. It toggles though all heading levels and no heading at all.

I'd like to adopt that for the AsciiDoc plugin. Let me know if you think this is more useful than the current solution.

![heading](https://user-images.githubusercontent.com/3957921/66318667-085a4300-e91c-11e9-88e8-7634c976ea90.gif)

**Comment by Mogztter** [comment]
Yes that could be nice but I still think the cursor should be positioned in front of the `=` symbol (when the line is empty) so you can type your title right away.

Do you think this issue is a good one for beginners? I want to give it a try 😁

**Comment by ahus1** [comment]
Please give it a try. For a beginner's issue focus on cursor placement first. Ignore my other comments regarding increasing/decreasing the level.

There is a contributing guide in the repo that covers different areas. The first stumbling block is usually that you need JDK8 with JavaFX to compile the code (recommended: either OraxleJDK8 or JetbrainsJDK). While it supports both JDK8 and 11 to run, it depends on JDK8 to compile.

I can try to walk you through some steps if you like and give you hints. Have you coded Jetbrains Plugins before?

**Comment by Mogztter** [comment]
> There is a contributing guide in the repo that covers different areas. The first stumbling block is usually that you need JDK8 with JavaFX to compile the code (recommended: either OraxleJDK8 or JetbrainsJDK). While it supports both JDK8 and 11 to run, it depends on JDK8 to compile.

:+1:

> I can try to walk you through some steps if you like and give you hints. Have you coded Jetbrains Plugins before?

No but I've followed the contributing guide and now I have a fully working local environment :tada: 

Regarding this feature, `MakeTitle` class extends `FormatAsciiDocAction` and, as a consequence, I think it makes sense to implement a generic solution to move the cursor and set the selection after the action.
I have a strong opinion on cursor placement and selection but before making any changes I think it's important that we come to an agreement :wink: 

**Title action**
In my opinion this action should preserve the cursor placement and the selection.
If I use this action to format "Document title" as a title and my cursor is just after the word "Document" and I do not have any selected text then after the action my cursor should still be after the word "Document" and the text shouldn't be selected.

If my cursor is at the beginning of an empty line then the action should append the text "= " and move the cursor at the end of the line.

**Word action (bold, italic, code...)**
In my opinion there are three use cases:
- bold/unbold a selected text (can be a single character)
- bold the next word I'm going to type
- bold the previous word

Currently the plugin is working great for the first use case.
Now let's say I want to write "I have a strong opinion" and I want to use bold on strong. I type "I have a " and then I click on the action it will produce "I have a \*\*\*\*" and the cursor will be at the same position (just before "\*\*\*\*").
In this case I think it would be better to produce "I have a \*\*" and move the cursor between the "*" symbols so I can type "strong" without moving the cursor.

The last one is arguably less common. I type "I have a strong" (my cursor is just after the word "strong") then I click on the action and it should produce "I have a \*strong\* " so I can type "opinion" without moving my cursor.

Also if my selection is "strong" in the text "I have a \*strong\* opinion" then I think the action should unbold "strong". Currently it produces "I have a \*\*strong\*\* opinion".

Do we have control over the "Extend selection" (Ctrl + W) and "Shrink selection" (Ctrl + Sift + W)?
It would be great if the markup could be selected (ie. I select strong, then <Ctrl + W> will select "*strong*" then the whole line, then paragraph...)

Any plan on adding shortcuts, I would love to write and format AsciiDoc text without using my mouse.

What do you think? Does it make sense? If it does not I can try to create short videos to demonstrate the writing flow.

**Comment by ahus1** [comment]
Good to hear that you have now have a running development environment!

Several classes extend FormatAsciiDocAction, but MakeTitle might be the that is different. Feel free to change FormatAsciiDocAction where necessary, or decouple MakeTitle. 

Regarding word selection: The plugin doesn't tune the selection or cursor position today. To overwrite the Ctrl + W behavior the plugin needs implement a handler in the plugin.xml. I implemented a first draft in commit 3f4427a113e95fe74fdff141ab1bd9f57bf5cce1. Feel free to tune it as needed. 

Tuning expand selection might get you only half the way: a `*word*` with a cursor placed in the middle with no current selection should turn to `word` when the toggle strong is pressed, but to `*_word_*` if italic is toggled. The current `selectionModel.selectWordAtCaret` might not be what people expect.

Regarding shortcuts: I got the impression that a lot of shortcuts are already used by either IntelliJ core and other plugins, therefore I was hesitant to add new shortcuts. Users are free to assign shortcuts to actions of the plugin as they wish, but there are now standard key bindings this plugin ships. Feel free to discuss.

**Comment by ahus1** [comment]
I've added in 9241e6e67ab942f148b9e530b7756bb52bcbb882 some more developer's resources, I hope they are helpful for your work.

>**Getting into development**
>
>To get into development of IntelliJ plugins, there is a [IntelliJ SDK guide](http://www.jetbrains.org/intellij/sdk/docs/).
It walks the developer through several stages of developing a custom language plugin.
>
>This plugin pulled several ideas from the Markdown plugin for IntelliJ that is now part of the IntelliJ community edition.
>Clone the [GitHub repository for IntelliJ Community](https://github.com/JetBrains/intellij-community) and check out the [Markdown plugin](https://github.com/JetBrains/intellij-community/tree/master/plugins/markdown) in particular.
>There is no need to make the community edition compile, just use it as a reference and look up example implementations for IntelliJ's extension point base classes.

**Comment by Mogztter** [comment]
> Several classes extend FormatAsciiDocAction, but MakeTitle might be the that is different. Feel free to change FormatAsciiDocAction where necessary, or decouple MakeTitle.

Ok :+1: 

Here's a first version:

![test](https://user-images.githubusercontent.com/333276/66462775-158e4380-ea7c-11e9-9f6f-c5b7875defae.gif)

The only edge case is when the selection is on multiple lines. I'm using the caret position to add the markup `= ` at the beginning of the line but I should probably get the first line of the selection.

Apart from that what do you think?

**Comment by ahus1** [comment]
LGTM!

First I was not not sure whether the cursor position or the start of the selection should take precedence. First I thought position of cursor should take precedence. Seeing your screen recording this fails when the previous line is selected, and the cursor is on the next line. 

I wonder: why select any text at all, and only look at the cursor? This makes it simpler to explain to users: "click on toggle title to make the current line a title". 

Having said all this: I think cursor position should take precedence when changing a line to title (and back).

**Comment by Mogztter** [comment]
> I wonder: why select any text at all, and only look at the cursor? This makes it simpler to explain to users: "click on toggle title to make the current line a title".
Having said all this: I think cursor position should take precedence when changing a line to title (and back).

I think what can be confusing is that we tend to think about the caret position as the start of the selection but that's not true unless you select the text backward (from bottom to top).
Let's say I have the following content:

```
Document title
Section title
```

If I select from top to bottom my cursor will be at line 2. But If I select from bottom to top my cursor will be at line 1.
In this case, even though my selection is the same, I will either toggle title for line 1 or 2.
But you are right, I think it's easier to explain, it will toggle title on the current line.
As an alternative we could toggle title for both lines.
Another edge case is when you use multiple carets (column selection mode).

Maybe we shouldn't address edge cases for now :wink:

**Comment by ahus1** [comment]
Yeah, no edge cases for now. How to proceed from here? PR or tackling level up/down as next step?

**Comment by Mogztter** [comment]
>Yeah, no edge cases for now. 

Ok, I will open a pull request later today or tomorrow.

> or tackling level up/down as next step?

What do you mean by level up/down?

**Comment by ahus1** [comment]
I've pushed a change that improves the cursor positioning when using word actions for bold/italic etc. I doesn't go the full way yet (it doesn't automatically expand a wrapping formatting), but I hope it is a start. Feel free to improve it further.

**Comment by ahus1** [comment]
A new pre-release 0.30.10 of this plugin includes this feature. The preview is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
