### ISSUE TITLE
Include content from URI is not working (with allow-uri-read)

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-intellij-plugin#348]
Include content from URI does not work even if the safe mode is UNSAFE and the attribute `allow-uri-read` is defined:

![allow-uri-read](https://user-images.githubusercontent.com/333276/66716916-94181780-edd3-11e9-9503-b3fea81c3594.png)

```
----
include::https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/README.adoc[]
----
```

![render](https://user-images.githubusercontent.com/333276/66716883-3b487f00-edd3-11e9-858f-eb252e9b8d8d.png)

AsciiDoc Plugin Version: 0.30.7

```
IntelliJ IDEA 2019.2.3 (Ultimate Edition)
Build #IU-192.6817.14, built on September 24, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-58-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: Batch Scripts Support, CMD Support, CheckStyle-IDEA, FindBugs-IDEA, JFormDesigner, PsiViewer, org.asciidoctor.intellij.asciidoc, org.jetbrains.idea.grammar, org.jetbrains.plugins.slim, BashSupport, com.dmarcotte.handlebars, com.jetbrains.lang.ejs, com.jetbrains.plugins.jade, com.wix.eslint, org.intellij.scala, org.jetbrains.plugins.ruby
```

**Comment by ahus1** [comment]
I suppose this is due to problems initializing openssl correctly. 
After change fa7c77323900abaa61039156a58c339ad61609c8 that fixes this, the error message changes to: 

> Failed to load AsciiDoc document - no implicit conversion of URI::HTTPS into String

@Mogztter - does this indicate a cause to you? Maybe another library should be loaded in advance here?

**Comment by ahus1** [comment]
I've pushed a change to #346 that will resolve this issue; it was a bug in one of my extensions that didn't handle URLs gracefully.

**Comment by ahus1** [comment]
A new pre-release 0.30.10 of this plugin includes this feature. The preview is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
