### ISSUE TITLE
Asciidoc plug-in not sentitive to the value assigned to :prewrap:

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-intellij-plugin#350]
The Asciidoc plug-in preview window in IntelliJ (in older versions of the plug-in) did not wrap text lines in a code listing if  :prewrap!: preceded the code listing. Now it is always wrap long lines in a code listing, irrespective of the value assigned to :prewrap:

````
= Wrapping lines sample

// Disable wrapping in listing and literal blocks.

== Listing 1

:prewrap!:

[source,groovy]
----
class GroovyHelloWorld {
    String sayHello(final String message = 'world') { // Set default argument value for message argument
        "Hello $message !"
     }
}
----

== Listing 2

:prewrap:

[source,groovy]
----
class GroovyHelloWorld {
    String sayHello(final String message = 'world') { // Set default argument value for message argument
        "Hello $message !"
     }
}
----
````
Current preview output of Asciidoc 0.30.7 (lines are always wrapped)

![image](https://user-images.githubusercontent.com/13682850/66742221-7d2b0100-ee77-11e9-9453-b7fa9518fcca.png)

Current preview output in Chrome launched from Intellij/Asciidoc (value assigned to :prewrap: controls whether lines are wrapped or not. Expecting the same behaviour from the Asciidoc plug-in's preview).

![image](https://user-images.githubusercontent.com/13682850/66742332-b5cada80-ee77-11e9-92a7-ce90309063b6.png)

Also see example listing at https://mrhaki.blogspot.com/2019/05/awesome-asciidoctor-dont-wrap-lines-in.html

AsciiDoc Plugin Version: 

    0.30.7

IDE Name and Version: 

    IntelliJ IDEA 2019.2.3 (Community Edition)
    Build #IC-192.6817.14, built on September 24, 2019
    Runtime version: 11.0.4+10-b304.69 amd64
    VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
    Windows 10 10.0
    GC: ParNew, ConcurrentMarkSweep
    Memory: 2002M
    Cores: 4
    Registry: 
    Non-Bundled Plugins: CMD Support, com.jetbrains.plugins.ini4idea,  
    net.seesharpsoft.intellij.plugins.csv, org.asciidoctor.intellij.asciidoc, 
    org.jetbrains.kotlin, PythonCore

**Comment by ahus1** [comment]
Thanks for providing an example. It seems that the JavaFX preview renders the CSS attribute `word-wrap:break-word` differently from modern browsers. The next version of the plugin will patch the CSS accordingly so that the expected behavior returns in the next release. 

I've been able to reproduce the behavior locally, therefore I close the bug now. I'll update the ticket once 0.30.10 is released.

**Comment by ahus1** [comment]
A new pre-release 0.30.10 of this plugin includes this feature. The preview is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by wfouche** [comment]
Tested the new functionality this morning, and it works!  Thanks!!
