### ISSUE TITLE
Add plugin icon

### ISSUE THREAD

**Issue by FatihBozik** [asciidoctor/asciidoctor-intellij-plugin#356]
It would be nice to add an icon to the plugin.

**Comment by ahus1** [comment]
I like the idea. We can use the standard Asciidoctor logo for this.

See https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_icon_file.html to add a plugin

See https://github.com/asciidoctor/brand/blob/master/logo/logo-fill-color.svg for a logo.

We didn't use the filled logo for the icon logo as this would be too red and looks like an error icon. For the plugin logo it would be fine to use this icon.

Please check the dark mode if you think a different logo works better in dark mode (the spec allows a separate icon for that)

**Comment by ardlank** [comment]
@ahus1 can I take up task?

**Comment by ahus1** [comment]
PR merged, will be part of 0.30.14 once it is released.
