### ISSUE TITLE
Add support for scratch files

### ISSUE THREAD

**Issue by harrol** [asciidoctor/asciidoctor-intellij-plugin#36]
IntelliJ 14 has a new feature, scratch files (Tools > New scratch file), which let's you quickly create some files for small test without adding them to the actual project. It would be nice if the plugin detected these as well.

**Comment by harrol** [comment]
Thanks to @yole we are halfway there (just no preview yet)
<img width="359" alt="screen shot 2015-07-25 at 12 54 54" src="https://cloud.githubusercontent.com/assets/883535/8889131/85dff3de-32cc-11e5-9e26-46ff5485d8bb.png">

**Comment by bodiam** [comment]
Oh wow, that's nice!!

**Comment by bodiam** [comment]
Scratchfiles support asciidoc, including previews.
