### ISSUE TITLE
Add TODO comments to TODO panel in IntelliJ for AsciiDoc files

### ISSUE THREAD

**Issue by bodiam** [asciidoctor/asciidoctor-intellij-plugin#37]
In the Markdown plugin, there's a very simple implementation, but I couldn't get it to work yet.

All the code is here: https://devnet.jetbrains.com/thread/458636?tstart=0, but maybe I overlooked something?

**Comment by miago** [comment]
![screenshot from 2017-06-13 19-37-34](https://user-images.githubusercontent.com/1433693/27096040-0e44a928-5070-11e7-8a08-9659d9ed3c79.png)
Seems to be implemented. The issue can thus be closed.

Greetings from Hackergarten Bern.

**Comment by ahus1** [comment]
Thanks for the follow up!
