### ISSUE TITLE
Are source highlighters other than coderay supported for live preview?

### ISSUE THREAD

**Issue by YenForYang** [asciidoctor/asciidoctor-intellij-plugin#370]
Unsure if this is an issue on my end, but I've tried setting `:source-highlighter: highlightjs` and `:highlightjsdir:`  and `:highlightjs-theme:` but I can't seem to get it to work. My only issue with Coderay is that it doesn't support the language I am working with.

According to https://asciidoctor.org/docs/user-manual/#available-source-highlighters, AsciidoctorJ supports highlight-js and prettify; I was wondering how to get the plugin working with highlightjs. Thanks.

**Comment by ahus1** [comment]
Currently only coderay highlighting is supported in the preview the plugin. 

I'd be happy if someone would provide a pull request with an enhancement.

**Comment by ahus1** [comment]
Here an update of current affairs: 

Version 0.32.38 is the first version to support `:source-highlighter: highlightjs` with a pre-bundled version of highlight.js for the common languages as listed on https://highlightjs.org/download/ plus AsciiDoc. 

Versions prior 0.32.38 support `coderay` and `rouge`, with `coderay` being the default.

`:highlightjsdir:` and `:highlightjs-theme:` are not supported yet. 

An update to the plugin's documentation is pending. 

As version 0.32.39 contains additional bug fixes, I recommend version 0.32.39 that is available as a pre-release for those who want to give hightlightjs a try.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment]
`:highlightjsdir:` and `:highlightjs-theme:` will be supported in the upcoming release 0.32.50
