### ISSUE TITLE
Spring restdocs support does not work for build.gradle.kts based projects

### ISSUE THREAD

**Issue by AlexCzar** [asciidoctor/asciidoctor-intellij-plugin#371]
Using latest version from the IntelliJ Marketplace
- If I have project set up with `build.gradle` (groovy dsl) the plugin detects rest-docs and the support works as described in the wiki.
- If I convert the project to kotlin-dsl, plugin does detect that this is rest-docs, but doesn't provide support (auto-complete, rendering for includes and operation::)

AsciiDoc Plugin Version: 0.30.20

IDE Name and Version: IntelliJ IDEA 2019.3 (Ultimate Edition)
Build #IU-193.5233.102, built on November 28, 2019

example `build.gradle.kts`:

```kotlin

plugins {
  id("org.asciidoctor.convert") version "1.5.9.2"
  id("org.springframework.boot") version "2.2.1.RELEASE"
}

dependencies {
  asciidoctor("org.springframework.restdocs:spring-restdocs-asciidoctor:2.0.4.RELEASE")
  testImplementation("org.springframework.restdocs:spring-restdocs-mockmvc:2.0.4.RELEASE")
}

val snippetsDir by extra { file("build/generated-snippets") }
tasks {
  test {
    outputs.dir(snippetsDir)
  }

  asciidoctor {
    inputs.dir(snippetsDir)
    dependsOn(test)
  }
}
```
Not attaching a project, as I've in fact used the one which is linked in the wiki and just translated to kotlin-dsl

**Comment by ahus1** [comment]
Until now the plugin recognized only build.gradle, not build.gradle.kts when determining the snippets folder. 

I fixed this in 0.30.21 that is available as a pre-release. It available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

I tried it locally and succeeded. Please give it a try if it works for you as well. 

As I tested it locally and it worked for me I close this ticket. If you experience problems please comment here and I'll re-open the issue.

**Comment by AlexCzar** [comment]
Indeed, installed from EAP repo and it works like a charm.
Thank you! This is going to make a whole dev team just that much happier today :)

**Comment by ahus1** [comment]
Thanks for testing it, I've promoted the release to the standard repo. It will be available as an update soon. 

May I ask how you found out about the spring-rest-docs feature? Was it the editor notification, the [feature list](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/FEATURES.adoc), or somewhere else?

P.S.: We like to interact with our users: Please feel free to [rate the plugin on the marketplace](https://plugins.jetbrains.com/plugin/7391-asciidoc), [share your ideas in the GitHub issue tracker](https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues), [sponsor Asciidoctor](https://opencollective.com/asciidoctor) or [start contributing](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc).

**Comment by AlexCzar** [comment]
It was the editor notification. I've been using asciidoctor to write documentation for some time now, so the plugin is always installed.
