### ISSUE TITLE
The scrollbar of the **preview** panel is **white** when using Darcula theme

### ISSUE THREAD

**Issue by arniu** [asciidoctor/asciidoctor-intellij-plugin#372]
<img width="645" alt="white-scrollbar" src="https://user-images.githubusercontent.com/1286674/70957919-9720d400-20b2-11ea-8271-d1a3c01db201.png">

The scrollbar on the right is white.

**Comment by ahus1** [comment]
Thanks for reporting this; it will be fixed in the next upcoming release.

**Comment by ahus1** [comment]
This is now available as part of pre-release 0.30.24.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
