### ISSUE TITLE
For Antora sites, enhance Intellisense of xref: to also include the version

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#377]
Originally raised as an idea in #373, not in scope for that ticket so new one created.

For reference, see https://docs.antora.org/antora/2.2/page/page-id/#structure

Background:

original idea for intellisense suggested in #373 (in scope for that ticket):
- https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/373#issuecomment-571759212

@djencks suggested the enhancement to include the branch as well (out of scope, hence here):
- https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/373#issuecomment-571760582

**Comment by ahus1** [comment]
The Antora sites I've seen use one branch for each version. Therefore supporting a version in an Antora  xref (or include) would need to check out a version of that branch. I currently don't have an UX idea what an IDE should do once you follow and xref with a version. Also making an include with a version is a challenge to me.

Therefore this request is somewhat stalled.

A minimal implementation would maybe "just" render them (but isn't the plugin and the preview already doing this?)

If anyone knows a project that has different version inside the same git branch, I'd like to learn about it. Seeing a project where this could be put to use might accelerate the implementation.

**Comment by djencks** [comment]
There's an idea about generating a content catalog when building a site, see https://gitlab.com/opendevise/oss/antora-site-generator-ms (I have a less invasive version too). If/when something like this becomes available, support for lookups into not-checked-out branches is more plausible.

A bunch of my simple examples have many components and versions in the same branch, but they are only intended to demonstrate various antora features in the simplest possible way.

**Comment by ahus1** [comment]
Rebuilding a content catalog with an external tool isn't something a user would want to do; acquiring the meta information is something the plugin should do automatically. Not sure about the APIs withing the IDE yet to access the Git structure.

**Comment by djencks** [comment]
I don't think it's realistic to expect an IDE to access other versions/branches from git.  For instance, the current user may not have access rights, or the whole site may be too big to fit on the current hardware.  I think Dan's idea is that building with Antora -- something you're going to do anyway with an Antora site -- would generate the content catalog.

**Comment by mojavelinux** [comment]
> Rebuilding a content catalog with an external tool isn't something a user would want to do

Keep in mind that the idea is that site manifest would be available from the published site (the result of the last run). So if the IDE doesn't find the file somewhere locally (perhaps from a local run), it would use the URL from the playbook to go fetch the manifest from the published site. This is all still in early draft proposal, but perhaps that helps with ideas for this conversation.

**Comment by mojavelinux** [comment]
>  would generate the content catalog

We're calling this the site manifest, not the content catalog. The content catalog is the object form of the virtual file system. The site manifest would be an exported representation of that data (how much and what schema we don't exactly know yet).

**Comment by ahus1** [comment]
Given a base URL, any xref with a version could link to the site's currently rendered page. A minimal antora-playbook.yml could be placed in the current project containing that piece of information. Usually there would be a separate publishing project, but I found it good for local testing to have minimal playbook around for the current for local testing.

I found that Antora already creates a sitemap. Auto-complete could work based on the sitemap (see [Antora's sitemap for the antora component](https://docs.antora.org/sitemap-antora.xml) as an example); the logic would be [baseurl]/sitemap-[component].xml. Each URL in the sitemap could be parsed as [baseurl]/[component]/[module]/[page]. Different versions/configurations might either create a path or a file ending with .html; see Camel for a different example (https://camel.apache.org/sitemap-manual.xml).

It could also try to look up the sitemaps from a local output dir of Antora. 

IMHO this should be sufficient for a first prototype. Once Antora provides more metadata, this can then be enhanced.

This approach would solve issue when linking to other versions and components not part of the user's current Git repo.

**Comment by ahus1** [comment]
Version 0.30.52 is available as a preview version. It supports the version number provided in xref and includes. 

In contrast to when you run Antora directly, the plugin will not access the branches of the GitHub repository. Instead, it will only take into consideration the files of the current IntelliJ project.

This way linking to a different version will work in the following scenarios: 
* multiple components with different versions in the same repository (haven't seen that yet, but there might be a case for that)
* different versions of the same component in the same repository (I'd say a rare scenario, I've seen that only in tests)
* One IntelliJ project that combines different source roots (checked out branches on a local disc) (using "File | New | Module from existing sources...")

The last one seems to be the most relevant to me; I've given it a try for example with the camel and camel-spring-boot project; their cross-references resolve nicely.

Intellisense is supported: the version number will be added to auto-complete for all components where the version number is different from the version number of the current component.

The idea to use the published sitemap to validate/preview xrefs will be moved to a new issue.

**Comment by ahus1** [comment]
Pre-release 0.30.55 is now available with some finishing touches to the functionality when linking to the "latest" version of a component. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
