### ISSUE TITLE
For Antora sites, when completing xref:xxx.adoc[, have Intellisense lookup the title of the referenced page for within the square brackets.

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#378]
So, when enter the "[",  and hit ctrl+enter, then intellisense pops up.

Also, could hit ctrl+shift+enter and autocomplete the title plus closing "]".

As originally suggested in #373 , descoped there.

**Comment by ahus1** [comment]
The next upcoming release supports smart-enter to add the text for an xref in the brackets. 

Press Ctrl+Shift+Enter without any bracket, after adding the first bracket or within empty brackets. It will add the title of the first section in the referenced file, or (if you used an anchor) it will resolve the title of the section with the selected anchor.

Handling incomplete AsciiDoc with only one opening bracket was a bit difficult to detect. I recommend using it with either empty brackets of no brackets.

![xrefcomplete](https://user-images.githubusercontent.com/3957921/76681816-3b091580-65f7-11ea-8fb6-feb44167a6cd.gif)

**Comment by ahus1** [comment]
This feature is part of pre-release 0.30.42.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by ahus1** [comment]
Pre-release 0.30.46 completes this functionality by supporting grabbing titles from sections that have block IDs.

**Comment by mojavelinux** [comment]
This is really nice.

Do note that Antora 2.3.0 will support automatic reference text for xrefs. It uses the xreftext of the document by default. If the xref is a nav file, it first looks for a navtitle attribute, then falls back to the xreftex for the document.

**Comment by mojavelinux** [comment]
See https://gitlab.com/antora/antora/-/issues/310

**Comment by ahus1** [comment]
@mojavelinux - reading Antora's ticket the "xreftext" is derived from the title of the referenced document, is that correct? I also read that xref doesn't derive a more specific text for deep links (xref with an anchor "#").

Therefore (once the Antora 2.3 feature is released) the behavior of the plugin should change: 
* if the target document has a title and no anchor is given in the xref, don't add the title by the IntelliJ plugin automatically to the xref
* if the target document has the attribute navtitle and no anchor is given in the xref, don't add the title in the IntelliJ plugin automatically to the xref

The following functionality will persist: 
* If the xref has an anchor, the title will be added by the IntelliJ automatically

Maybe the plugin needs to receive an Antora version compatibility version level at some point.

@danhaywood - please comment with your thoughts.

**Comment by danhaywood** [comment]
Hmm, it's not clear to me from the Antora ticket whether Antora will
automatically create the xreftext attribute on each page if not present, or
whether it requires the author to explicitly specify it.  I hope it's the
former (but with the option that the author could override with an
explicitly set attribute if need be?)  If it's the latter, then there would
be cases where there is no xreftext attribute to be used.

Will wait to see what @mojavelinux says before speculating further...

**Comment by mojavelinux** [comment]
> it's not clear to me from the Antora ticket whether Antora will
automatically create the xreftext attribute on each page if not present

xreftext on the document is an alias for the doctitle, with the option to override. In other words, the xreftext matches the doctitle in this case:

```
= Document Title
```

But it's overridden in this case:

```
[reftext=Title Used in Reference]
= Document Title
```

99% of the time, the xreftext is the doctitle.

**Comment by mojavelinux** [comment]
> I also read that xref doesn't derive a more specific text for deep links 

Automatic reference text for deep links is not supported at this time.

**Comment by danhaywood** [comment]
Thanks, @mojavelinux.

For my understanding, is it

    [reftext=...]
    == Doc title

or (because the attribute is "xreftext") was that a typo and it should have
been:

    [xreftext=...]
    == Doc title

**Comment by mojavelinux** [comment]
It's defined using reftext. xreftext is the resolved value of reftext. (In other words, xreftext is the consumer, reftext is the definer).

**Comment by danhaywood** [comment]
ok, thanks for the clarification.

So, to Alexander's question - since in 2.3 there will always an implicit
xreftext, then the functionality of the plugin becomes less useful.

On the other hand, I could still see myself using it, because I want a link
to another page and maybe change the capitalization or put in a different
phrase completely in order to make the referencing sentence work.

I have a suggestion, which would work for both 2.2 and 2.3 : keep the
functionality, but have it so that ctrl-shift-enter pressed twice will
delete the contents of the block.  This would make for a convenient way to
"peek" at the implicit title.

As a slight variation, I often find myself lower-casing a referenced
title.  So I could imagine that ctrl-shift-enter would cycle around:

a) the looked up xreftext
b) the same, but lower cased
c) remove completely (perhaps this option is only available in Antora 2.3
if the plugin can detect).
d) same as (a), etc.

**Comment by mojavelinux** [comment]
I didn't mean to suggest the feature as it is isn't useful. Different
people will want to do it different ways, and there are still plenty of use
cases where the text is needed to fit with the flow of the content.

One place where the text is almost never needed starting in 2.3 is the
navigation file.

**Comment by danhaywood** [comment]
Yeah, sorry, and I didn't take your comments to imply that either.

Alexander has been doing some fantastic stuff with this plugin recently,
I'm sure he values your input as I certainly do.

Cheers
Dan H

**Comment by ahus1** [comment]
Thank you @mojavelinux and @danhaywood for commenting on this. I've opened two follow-up issues that reference this ticket. They capture further enhancements. 

I'm closing this ticket again as the initially requested functionality is complete.
