### ISSUE TITLE
For Antora sites, when enter include::xxx.adoc[ , then provide autocomplete of "leveloffset=+1"

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#379]
In almost all of my uses of include::, they follow the form:

include::subdocument-1.adoc[leveloffset=+1]
include::subdocument-2.adoc[leveloffset=+1]
include::subdocument-3.adoc[leveloffset=+1]

The "leveloffset=+1" automatically indents the subdocument headings correctly.

It would be nice if, when I enter:

include::subdocument-3.adoc[

then hit <ctrl+enter>

that "leveloffset=+1" is offered in an intellisense.

Perhaps there might be other commonly used attributes, in which case these could be selected and added in between the brackets (separated by commas).

<hr/>
NB: there's also a tiny bug in 0.30.28, which is that the current autocomplete adds in a trailing "#", ie

include::subdocument-1.adoc#

So far as I'm aware, it's not possible to include sections of subdocuments, and so the anchor "#" is not valid syntax here.  Since it *is* valid for xref:, I'm guessing that a bit of code is being reused that shouldn't be.

**Comment by slonopotamus** [comment]
I think this is useful for generic includes when chapters are organized in separate files, not only for Antora.

**Comment by ahus1** [comment]
Could you think about additional logic, like: 
* only add "leveloffset" if the included document is an AsciiDoc document AND starts with a heading
* adjust the "+x" that the effective level of the heading at the start of the included document matches the of the current paragraph's level +1

**Comment by danhaywood** [comment]
> only add "leveloffset" if the included document is an AsciiDoc document AND starts with a heading

makes sense, though sometimes headings are preceded by anchors, so would need to be intelligent enough to cater for that.

> adjust the "+x" that the effective level of the heading at the start of the included document matches the of the current paragraph's level +1

Not sure I follow this?

**Comment by ahus1** [comment]
@danhaywood - the example you have above with the "leveloffset=+1" works when the include is placed in a section with level one, and the included document starts with level one. 

If the include is placed in a section with level two, and the included document starts with level one, the attribute has to be "leveloffset=+2".

If the include is placed in a section with level one, and the included document starts with level two, the attribute has to be "leveloffset=+0" (or can be skipped).

Therefore the leveloffset needs to be dynamic and need to take the current section's level and the included document's section level into account.

**Comment by danhaywood** [comment]
OK, makes sense.  I don't think I've ever included a subdocument other than
at the top-level, which is why the more flexible design you've described
didn't compute for me.

Thanks

**Comment by ahus1** [comment]
The upcoming version 0.30.42 will support this when the user presses "SmartEnter" (Ctrl+Shift+Enter). 

Pre-conditions for the auto-completion to be applied: 
* the included file is an AsciiDoc file
* the included file contains a section (usually starting with one or more "=")
* the include is placed within a section
* the leveloffset computed as the different of the parent's section level and the first section heading in the included file plus one must not be zero

When determining the section level in the current or the included document, nested includes are not evaluated.

![complete-leveloffset](https://user-images.githubusercontent.com/3957921/76645871-24f94780-655a-11ea-8989-33dd03f967cc.gif)

**Comment by ahus1** [comment]
The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
