### ISSUE TITLE
Implement toolbar with bold, italic, etc.

### ISSUE THREAD

**Issue by bodiam** [asciidoctor/asciidoctor-intellij-plugin#38]
It would be nice to have a toolbar with icons for making text bold, italic, etc, a bit like this one:

https://stackedit.io/editor

**Comment by ehmkah** [comment]
@bodiam What is in the current implementation missing? There is, bold, italic, Monospace, strike through, create table? Do you want: code, image, hyperlink, numberred list, enum, bulleted list, and something which raises/reduces level of a heading?

PS: Sorry for annoying on so many issues, but today I have too much time in the train. ;-)

**Comment by bodiam** [comment]
@ehmkah Not annoying me at all, I very much appreciate your efforts, so thank you for that!

The items you list seem like a great idea. Hyperlinks and code are the ones which I always seem to forget, so adding that would be super. The bulleted list seems more complex to me, and I'm curious if it really improves the experience, but I'm okay if you decide to add it, no problem!

**Comment by ehmkah** [comment]
Thank you for merging. Anything I could prepare so that releasing for you would become easier?

**Comment by bodiam** [comment]
I don't think so. I'm trying to upload now, but I'm in a library with a poor internet connection. It will probably take a minute or 30. I think it's just a case of being patient :)

**Comment by ahus1** [comment]
All formatting options that are given in this discussion are now implemented and released (including the make link feature). I'm closing this ticket - please re-open (or open a new ticket) for any option you're still missing.
