### ISSUE TITLE
Doesn't properly parse/format ifdef with nested square brackets

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-intellij-plugin#380]
1. Create Asciidoctor file with following contents:
```asciidoc
= Book Title
The Author
v0.1
ifdef::ebook-format[:front-cover-image: image:images/cover.png[Front Cover,1050,1600]]
:doctype: book
:toc: left
```
2. Observe that coloring of `]` is wrong, it doesn't match it's pair `[`
3. Reformat file
4. Observe that doctype/toc lines got collapsed into a single line: `:doctype: book :toc: left`

Expected:

1. Matching square brackets are colored in pair
2. toctype/toc macros stay on separate lines

Wrong coloring of brackets:
![image](https://user-images.githubusercontent.com/92637/72143247-68430880-33a7-11ea-9517-c1c9e202b221.png)

Wrongly formatted file (after Code -> Reformat Code):
![image](https://user-images.githubusercontent.com/92637/72146224-100f0500-33ad-11ea-8b01-9209cc2c326f.png)

Things start to work properly if nested square brackets are removed from `ifdef::ebook-format` line:
![image](https://user-images.githubusercontent.com/92637/72146262-21581180-33ad-11ea-94cc-4c8f55c28953.png)

Workaround for formatting bug: add a comment line after problematic `ifdef`.

AsciiDoc Plugin Version: 0.30.21

IDE Name and Version:
```
IntelliJ IDEA 2019.3.1 (Ultimate Edition)
Build #IU-193.5662.53, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1941M
Cores: 8
Registry: 
Non-Bundled Plugins: Batch Scripts Support, CheckStyle-IDEA, PsiViewer, Pythonid, org.jetbrains.kotlin, org.jetbrains.plugins.go, com.perl5, net.sjrx.intellij.plugins.systemdunitfiles, org.asciidoctor.intellij.asciidoc, org.jetbrains.idea.grammar, org.jetbrains.plugins.ruby
```

**Comment by ahus1** [comment]
Thanks for reporting this. I've started working on it in ae97c08073aad5c6fc1cb4c583d4b91506296c4e that will be part of an upcoming release. This will fix the auto-formatting issue. 

Expect a pre-release within the next days.

**Comment by ahus1** [comment]
As a workaround you could write the content like this: 

```
= Book Title
The Author
v0.1
ifdef::ebook-format[]
:front-cover-image: image:images/cover.png[Front Cover,1050,1600]
endif::[]
:doctype: book
:toc: left
```

**Comment by ahus1** [comment]
There's a new pre-release 0.30.29 available that fixes this issue. It's also a the first release to parse the contents of ifdef, so you get proper highlighting and editor support for content inside the brackets. 

Thank to the example you provided I was able to test this issue locally. As this now works, I close the issue. Please comment if the issue persists. When testing reformatting I also found an issue with literal blocks (delimited with dots like `....`) that should also be fixed. 

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
