### ISSUE TITLE
Markdown style listing is not detected if the block has a title

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-intellij-plugin#387]
Consider the following code:

````
.app.js
```js 
const Asciidoctor = require('asciidoctor')

const asciidoctor = Asciidoctor()
```
````

In this case, the extension does not suggest to convert the Markdown style listing to an AsciiDoc listing:

![ok](https://user-images.githubusercontent.com/333276/72668433-22c9af80-3a27-11ea-9f9b-62afbe7c79e1.png)

If I remove the title then I get the warning:
![ko](https://user-images.githubusercontent.com/333276/72668434-22c9af80-3a27-11ea-8cc1-7dbcffec6186.png)

**AsciiDoc Plugin Version**
`0.30.31`

**IDE Name and Version**
```
WebStorm 2019.3.1
Build #WS-193.5662.54, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-72-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1931M
Cores: 8
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: BashSupport, net.seesharpsoft.intellij.plugins.csv, org.asciidoctor.intellij.asciidoc, org.jetbrains.plugins.slim, org.toml.lang
```

**Comment by ahus1** [comment]
Thanks, will be fixed in the next upcoming release. I've enhanced both the detection and the fix-up for this situation plus added a test case.

**Comment by ahus1** [comment]
Version 0.30.32 is now available as a pre-release that includes this change. Please comment here if there is something not working related to this issue and I will re-open the issue.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
