### ISSUE TITLE
Includes wrong PlantUML diagram

### ISSUE THREAD

**Issue by Kira-Cesonia** [asciidoctor/asciidoctor-intellij-plugin#388]
I am using Asciidoc and Plant UML in IntelliJ to write documentation using the Asciioc IntelliJ Plugin at Version 0.30.31 (updated just now).

There, I have run into a strange issue with including diagrams. I have found a way to make it work, but I don't understand why. I would like to know why it works the way it does.

I am using the following statement to include a Plant UML diagram on a page:

```
["plantuml","containers"]
----
include::../diagrams/containers.puml[]
----
```

However, instead of including ../diagrams/containers.puml as intended, this includes a different diagram from the seemingly unrelated resource of ../external-references/diagrams/external-components.puml, and then scales it up to the size of ../diagrams/containers.puml`.

For some reason, this only happens for this one includes statement. The following inclusion of a different PUML diagram, for example, works no matter where in the AsciDoc I put it:

```
["plantuml","system-context"]
----
include::../diagrams/system-context.puml[]
----
```

Now, as mentioned before, I managed to get it to work by changing the whole statement to the following (removing ",containers" in the header):

```
["plantuml"]
----
include::../diagrams/containers.puml[]
----
```

For me, that raises two questions:

1. Why does the include work for system-context.puml but not for containers.puml?
2. Why is it even affected by the second part of the syntax? I thought this was for alternative text if the image can't be displayed.

**Comment by rdmueller** [comment]
I also experienced such behaviour in the past. The `"containers"`-part in `["plantuml","containers"]` is used as filename by Asciidoctor. In my case, I had several plantUML-Blocks with the same name (mainly in test documents) and thus got strange behaviour.

COuld it be that you have the same problem?

**Comment by Kira-Cesonia** [comment]
Nope, I just verified that I only have a single file called `containers.puml` in the entire project structure, and this also does not explain why it is referencing to `external-components.puml`.

However, my `Clairvoyance 1` says that it _might_ be possible that such behaviour might be the result of incomplete refactoring. That is, the names of the diagrams might have changed at some point prior to me joining the project. I have already searched for such hidden dependencies, but was as of yet unable to find any. If such hidden dependencies existed, where or how would I be able to find them?

**Comment by ahus1** [comment]
@Kira-Cesonia - the advice from @rdmueller is not about file names, but the second parameter of the block attributes. Therefore I ask: Could you please search your project for a second appearance of `["plantuml","containers"]` in the AsciiDoc source - with or without quotes? 

Some more questions: 
* Did you set some attributes related to diagram creation? The page for [Asciidoctor Diagram](https://asciidoctor.org/docs/asciidoctor-diagram/) describes some attributes: `imagesoutdir`, `outdir`, `imagesdir`, `to_dir` or `base_dir`?
* Did you manage to create a minimal example to reproduce the issue?

I usually don't put quotes around anything inside the brackets, it should work find without. I'll have to investigate if this causes problems here (although it shouldn't).

**Comment by Kira-Cesonia** [comment]
Ah, that was the bit of information I needed. So the second parameter in the block attributes sets a global filename that is stored in "Mystic Space" and can cause issues. What is the benefit of this parameter anyway, since you still need to pass the exact path and filename in the include statement afterwards? According to my experimentation, omitting it does not cause any issues. I intuitively expected block to work on its own without needing an extra import statement below if you've declared and named it once, but alas, that does not seem to be the case.

Aka, this works:
```
["plantuml","system-context"]
----
include::../diagrams/system-context.puml[]
----
```

This also works:
```
["plantuml"]
----
include::../diagrams/system-context.puml[]
----
```

However, I intuitively expected this to work, but it does not (expected it to display the same diagram twice, but it only displays it once):
```
["plantuml","system-context"]
----
include::../diagrams/system-context.puml[]
----
["plantuml","system-context"]
```

Instead, this is required to display the same diagram twice:
```
["plantuml","system-context"]
----
include::../diagrams/system-context.puml[]
----
["plantuml","system-context"]
----
include::../diagrams/system-context.puml[]
----
```

But that could also be shortened to:
```
["plantuml"]
----
include::../diagrams/system-context.puml[]
----
["plantuml"]
----
include::../diagrams/system-context.puml[]
----
```

So, what is the advantage of including the filename in the block. As I see it, it only serves as a source of Type 3 refactoring errors.

**Comment by ahus1** [comment]
As https://asciidoctor.org/docs/asciidoctor-diagram/ points out, not specifying a target name will lead to a file name derived from the diagram's content. If I understand it correctly the generated file name will change once the contents of the file change, and the same content will lead to the same file name (if used in multiple places). 

This doesn't suite everyone, especially if one wants to reference and image by (file) name from a different source. 

Logging a warning message when two diagrams use the same specified target name (and maybe file format) sounds like a good idea to me.

As this is not related to the IntelliJ plugin but to Asciidoctor Diagram, I suggest you open an issue in their GitHub repo: https://github.com/asciidoctor/asciidoctor-diagram
A solution within Asciidoctor Diagram would fix it not only for the IntelliJ plugin, but also in situation where it is run from the command line.

**Comment by ahus1** [comment]
Update: while this is not yet implemented upstream in Asciidoctor Diagram, the IntelliJ plugin will show a warning in the editor indicating a duplicate target file name. The warning is "Duplicate target name, will overwrite file, first occurrence at..." (see commit above). Let me know how this error message can be improved.

This will be part of the next release.

**Comment by ahus1** [comment]
Closing this issue as this is has been handed over to the upstream project for a solution. The plugin will keeps its preliminary solution until an updated version of the upstream library lands in the IntelliJ plugin.

**Comment by ahus1** [comment]
Version 0.30.32 is now available as a pre-release that includes this change. 

Thank you for opening the issue in the upstream project. Please be aware that me and several other people are working on this project in their spare time. Responses (and releases) might take time to complete. We are always looking for people to contribute - for example by testing our pre-releases or contributing code.

See below of an example screenshot of your example:

![image](https://user-images.githubusercontent.com/3957921/72994046-b966e980-3df6-11ea-8214-616d1b6d1da3.png)

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
