### ISSUE TITLE
Make AsciiDoc a dynamic plugin that doesn't require restart the IDE

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#391]
Starting in IntelliJ 2020.1 JetBrains introduced dynamic plugins. 

http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/dynamic_plugins.html

Once this plugin is a dynamic plugin users will not need to restart their IDEs on initial install and subsequent updates.

**Comment by Mogztter** [comment]
> Starting in IntelliJ 2020.1 JetBrains introduced dynamic plugins.
> Once this plugin is a dynamic plugin users will not need to restart their IDEs on initial install and subsequent updates.

I didn't know, it's going to be great!

**Comment by ahus1** [comment]
With the upcoming 2020.2 release of IntelliJ (currently EAP) and the plugin's version 0.31.2 this plugin's initial installation works without a restart. 

To uninstall and to perform upgrades a restart is still required, as the plugin's classloader can't be unloaded; possibly due to some JRuby classloaders that can't be unloaded.

The new issue #503 will follow up on this; help reading this issue is appreciated.

**Comment by ahus1** [comment]
Pre-release 0.31.2 is now available. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
