### ISSUE TITLE
How to set soft-wrap globally?

### ISSUE THREAD

**Issue by diguage** [asciidoctor/asciidoctor-intellij-plugin#393]
I want to set soft-wrap for all projects and all AsciiDoc files. But I can not find the setting options. How to do it?

**Comment by ahus1** [comment]
There is a functionality in the general settings of IntelliJ. Please go to Editor -> General. You have to scroll down quite a bit to find this setting:

Check the checkbox and add *.adoc to the list of extensions. 

![image](https://user-images.githubusercontent.com/3957921/73168588-647aea00-40fa-11ea-97f5-861ec74a009c.png)

Please let me know if this solves your issue. Can you suggest where we should put this information so users find this information better? 

There is a pending idea to open an editor notification if after a user clicked wrap several times (see #316).

**Comment by diguage** [comment]
@ahus1 
Thanks a lot.

**Comment by diguage** [comment]
I clicked the soft-wrap button in the top menu many times, but IDEA did not show the tip. 

If I clicked the soft-wrap button, please show the tip or take me to the config options. Maybe it is a better way.

**Comment by ahus1** [comment]
Happy to hear this worked for you. I'll close this issue and see after issue #316 to be implemented.
