### ISSUE TITLE
Code formatting adds an empty line between listing and its caption

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-intellij-plugin#400]
Given the following document:

```adoc
= Title

..gitattributes
----
*   -text
----
```

Execute `Code->Reformat Code` IDE action (or just press CTRL+ALT+L).

Expected: text stays as-is, because it is already well-formatted.

Actual: empty is inserted between listing caption and listing block, so resulting document is this:
```adoc
= Title

..gitattributes

----
*   -text
----
```

AsciiDoc Plugin Version: 0.30.34

IDE Name and Version: RubyMine 2019.3.1
Build #RM-193.5662.59, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by ahus1** [comment]
Thanks for reporting this. Apparently a title starting with a dot isn't recognized as a title, therefore the reformatter problem. 
I'll need to fix the lexer for this.

**Comment by slonopotamus** [comment]
Are there other syntaxes for block titles? I only find dot in Asciidoctor manual.

**Comment by ahus1** [comment]
No, there isn't; you're using the title correctly.

It's a lexer problem: The lexer that is the base for highlighting and reformatting tries to mimic Asciidoctor's behavior in processing the content. As it is separate, and only mimics, it sometimes fails. And then it's time for a bug and some alignment of the lexer.

**Comment by ahus1** [comment]
I assume I'll have a bug fix as a pre-release ready within a day or two. As a workaround you could write the following:

```
.{sp}.gitattributes
----
*   -text
----
```

**Comment by slonopotamus** [comment]
Actually, there _is_ a different syntax :)

```adoc
[title=.gitattributes]
----
*   -text
----
```

No worries, I've workarounded it.

**Comment by ahus1** [comment]
I've pushed a change that now supports titles starting with a dot. An example similar to the one you provided is now part of the test suite. I therefore close this issue. I'll update this issue once a pre-release is available.

**Comment by ahus1** [comment]
Pre-release 0.30.38 is available. Please give it a try and let me know if this works for you.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
