### ISSUE TITLE
Feature request: pasting an image into the editor should create the file and image:[] ref.

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#402]
If I have an image in my clipboard, then I'd love to be able to just "paste" this into the asciidoc editor and it automatically create the file and image: link for me.

If in Antora mode (which is what I care about mostly), then the new file should be in the images/ folder (but I guess, in general, wherever {imagesdir} points to).

**Comment by danhaywood** [comment]
I see there's something similar for markdown ... https://plugins.jetbrains.com/plugin/8446-paste-images-into-markdown/reviews

**Comment by ahus1** [comment]
I've looked in the plugin you referenced and found the extension point I was missing to make the shortcut work. This will be part of the next pre-release.

**Comment by danhaywood** [comment]
Nice, very nifty.  Many thanks, lookin forward to it.

**Comment by ahus1** [comment]
I'll update this issue once the pre-release is available.

**Comment by ahus1** [comment]
Pre-release 0.30.38 is available. Please give it a try and let me know if this works for you.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by danhaywood** [comment]
Yep, works nicely.  I have one tiny enhancement request, I'll raise a separate ticket.
