### ISSUE TITLE
editor-fold is not collapsible in adoc files

### ISSUE THREAD

**Issue by verhas** [asciidoctor/asciidoctor-intellij-plugin#404]
```
//<editor-fold id="this is not collapsible">
only if there is something inside
if this is empty then it is collapsible
//</editor-fold>
```
AsciiDoc Plugin Version: 0.30.34

IDE Name and Version: IntelliJ IDEA 2019.3.3 (Community Edition)
Build #IC-193.6494.35, built on February 11, 2020
Runtime version: 11.0.5+10-b520.38 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: debugger.watches.in.variables=false, actionSystem.force.alt.gr=true
Non-Bundled Plugins: Batch Scripts Support, CMD Support, Docker, PythonCore, com.alayouni.ansiHighlight, com.andrewbrookins.wrap_to_column, com.intellij.ideolog, com.jetbrains.jbre.bintray.downloader, com.perl5, com.thoughtworks.gauge, org.asciidoctor.intellij.asciidoc, org.intellij.scala, org.toml.lang, org.rust.lang

**Comment by ahus1** [comment]
I have to admit I didn't know about editor fold using comments before you posted this issue. 

Looking at your example, I try to find out what you observe vs. what you expect. A screenshot of the snippet above look can fold in my IDE. How does it look in your IDE? What should be different?

![image](https://user-images.githubusercontent.com/3957921/74591436-45e08280-5018-11ea-9b89-e2c9ab056304.png)

![image](https://user-images.githubusercontent.com/3957921/74591441-51cc4480-5018-11ea-8416-8a7a11013d99.png)
 
IntelliJ IDEA 2019.3.1 (Community Edition)
Build #IC-193.5662.53, built on December 18, 2019
Runtime version: 11.0.5+10-b520.17 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1024M
Registry: java.completion.argument.hints.internal=false
Non-Bundled Plugins: PlantUML integration, PsiViewer, tanvd.grazi, org.asciidoctor.intellij.asciidoc

**Comment by verhas** [comment]
Now that I decided to give you screenshots and I cannot reproduce.

I certainly saw some way it was not working. We can close this issue as for now and in case I bump into the issue I will rectify more the conditions and special case that perhaps make it. It is especially interesting because I think it should not be something that the plugin has to deal with.

I extensively use the feature, because my application copies source code snippets from source code into the AsciiDoc document and in that case it is better if it can be collapsed. Especially when part of the document is written in the source code and a whole section is collected from the source. In that case, it is easy to forget it and edit into the generated test and lose your work when the snippet fixing is executed again. This is the Java::Geci project and the Docugen part of it.

**Comment by ahus1** [comment]
Thanks for letting me know. As the plugin adds some folding on its own (for example for sections and code block), there might be a situation where they interfere. 

As you suggested I'll close this ticket. Please comment here with an example when you see the symptoms again and I'll re-open the ticket.
