### ISSUE TITLE
antora include:: parsing is not always correct

### ISSUE THREAD

**Issue by djencks** [asciidoctor/asciidoctor-intellij-plugin#405]
For use with Antora page coordinates, not all include directives are parsed correctly.

For instance,

```
include::2.0@:example$example5.txt[]
```

is correct, but the plugin thinks
```
include:2.0@:example$example5.txt[]
```
is correct (it is invalid).

I'll include a page that includes all valid formats of Antora includes.  There's an Antora project with the include targets at https://gitlab.com/djencks/simple-examples in the multiple-component/includes directory.

This plugin is wonderful!!!

AsciiDoc Plugin Version: 0.30.34

IDE Name and Version: 2019.3.2

Page with all possible valid formats of Antora include:

```
= {page-component-title}

== Page Coordinates

page-component-name: {page-component-name}

page-component-version: {page-component-version}

page-module: {page-module}

page-relative: {page-relative}


== This page demonstrates all sorts of includes from examples

=== relative only, this component, version, module

include::example$example1.txt[]

include::example$src/main/java/org/example2.txt[]

=== module and relative: this component, version

include::module1:example$example3.txt[]

include::module1:example$src/main/java/example4.txt[]

=== version and relative, this component and module

include::2.0@:example$example5.txt[]

include::2.0@:example$src/main/java/org/example6.txt[]

=== version, module, and relative, this component

include::2.0@module1:example$example7.txt[]

include::2.0@module1:example$src/main/java/example8.txt[]

=== version, compoment, and relative, (ROOT) module

include::1.0@component2::example$example9.txt[]

include::1.0@component2::example$src/main/java/org/example10.txt[]

=== version, component, module, and relative

include::1.0@component2:module1:example$example11.txt[]

include::1.0@component2:module1:example$src/main/java/example12.txt[]

=== component and relative; default (master) version and default (ROOT) module.

include::component2::example$example13.txt[]

include::component2::example$src/main/java/org/example14.txt[]

=== component, module, and relative; default (master) version.

include::component2:module1:example$example15.txt[]

include::component2:module1:example$src/main/java/example16.txt[]
```

**Comment by ahus1** [comment]
Thanks for sharing this example. Would you mind adding this page to the repo you referenced? If you don't want to have it in the master, please consider a branch with these contents. This would make it a lot easier for me to test this.

Please note: version numbers in xref or include are currently not supported. There is already ticket #377 for this. 

The examples without a version number should work. I tested with a small local example; I'm looking forward to your examples. Please point out what examples work for you, and what don't behave in the expected way.

Could you please elaborate on "but the plugin thinks `include:2.0@:example$example5.txt[]` is correct (it is invalid)."? I see that this is missing a colon; but it also has a version number that is not supported yet. What do you see that the plugin treats it as "correct"?

Looking at you repo I found some xref macros inline style (one colon) and block style (two colons). The the two-colon style officially supported? On all of the Antora page I see only one colon.

Lot's of questions, I hope you don't mind. Feel free to answer some of them first, and answer others later.

**Comment by djencks** [comment]
OOPS!  I wrote that nice complete includes example and forgot to push it to GitHub!  It should be there now.

All the includes in my page with red lines under them have versions.  However, the red lines disappear when I change to the invalid single-colon syntax.  Perhaps the plugin doesn't recognize this as an include directive with only the single colon, and what it objects to with the double colon is the version it doesn't understand?  If so, it might be nice if the plugin can recognize that the single-colon version is a syntax error.

All the includes with no version look fine in the editor.

I just checked and all the links on accessible pages in the xref example work. The only xref:: I see is in the component2 version3 nav.adoc, and it works, and also works with a single colon. I guess it's time to ask Dan...

**Comment by djencks** [comment]
Dan says only the xref: with a single colon is valid.  Perhaps I'll find time to find out why Antora doesn't object to the double colons.

**Comment by ahus1** [comment]
I've looked into the examples you provided, thank your for the extensive list. I've tested them with version 0.30.41.

The plugin highlights `include:2.0@:example$example5.txt[]` like any other inline macro. This is also the rendered text. This is AFAIK the expected behavior. 

Having an include followed by only a single colon is usually wrong, but will render as valid text (the usual Asciidoctor behavior). The plugin could issue a warning here, but this is not the core of this ticket.

The plugin parses all include references without a version number correctly as I see it. The "component and relative; default (master) version and default (ROOT) module." and "component, module, and relative; default (master) version" are highlighted in in red as the text files example13.txt, example14.txt, example15.txt and example16.txt don't exist in the example folder. This is also the correct behavior as I see it. 

Handling of version numbers for Antora is planned for xref in #377, and it would make sense support it for includes as well.

I therefore suggest to close this ticket and wait for #377 to provide the version number support.

@djencks - please let me know if you agree or if I've missed something. Thanks!

**Comment by ahus1** [comment]
As long as version numbers are not supported, I could make the includes with version numbers render as normal text; they would then no longer be highlighted in red. WDYT?

**Comment by djencks** [comment]
At the moment I'm inclined to leave them red, at least that shows the plugin recognizes it as an include.

Do you know if it's possible to register an inline macro named "include"?  I haven't tried it.  If not, I think it would be appropriate to mark the single : include as an error.

**Comment by mojavelinux** [comment]
> Do you know if it's possible to register an inline macro named "include"

It's certainly possible, but I wouldn't recommend it as it's bound to create confusion. Still, technically not an error if the user wrote an extension to fulfill it.

**Comment by ahus1** [comment]
@djencks - regarding distributed components in Antroa. I had a look at the current documentation of Camel (I see that you've been involved there). 

Before Camel I thought distributing was about distributing the modules of a component, and that there would still be only one folder for each module. Then I saw that you could distribute the single files of a module and that there could be any number of folders for a module. 

The next version of the plugin will support this true distributed style as used by Camel as well.

**Comment by ahus1** [comment]
@djencks - the pre-release 0.30.52 in now available. It supports:
* fully distributed components
* xrefs with attributes in component/module/version name

I've given it a try on your example repo "simple-examples" and it looked quite good to me. 

Something it doesn't support yet is linking to the "latest" version. Instead it tries to link to the same version number of the current component.

Given a list of versions, how would I compare these strings to find out the latest version?

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by mojavelinux** [comment]
> Given a list of versions, how would I compare these strings to find out the latest version?

See https://preview.docs.antora.org/antora/2.3/how-component-versions-are-sorted/

**Comment by ahus1** [comment]
Pre-release 0.30.55 is available that support linking to the latest version across modules. 

It passes the test provided by @djencks - kudos to you for preparing this example!

As the plugin collects all antora.yml files within a project, please open the folder multiple-components/includes in IntelliJ. 

Given that it works with the example above, I'll now close this ticket. Please let me know if I missed something and I'll re-open it. 

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by ahus1** [comment]
Pre-version 0.30.56 is now available that fixes a regression when linking to the latest version of a distributed component. Sorry for any inconvenience this might have caused to you.

**Comment by mojavelinux** [comment]
> It passes the test provided by @djencks - kudos to you for preparing this example!

I second that. The time spent to prepare an example is highly appreciated. Thanks @djencks!

**Comment by ahus1** [comment]
Pre-release 0.30.59 is now available that aligns linking to the "lastest" version with the Antora mechanism. Thanks for @djencks clarifying this for me.
