### ISSUE TITLE
Hyperlinks can't be followed if there is a line break in an xref's label.

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#406]
I have this xref (appearing in a table, so limited real estate).

    xref:extensions:auditer:about.adoc[Audit Trail +
    (Extensions Catalog)]

This puts the "(Extensions Catalog)" on a new line.

I believe this is valid Asciidoc, however if I hover over the about.adoc then I can't navigate.  If I temporarily get rid of the line break, ie:

    xref:extensions:auditer:about.adoc[Audit Trail (Extensions Catalog)]

then I can navigate fine as normal.

**Comment by ahus1** [comment]
I've enhanced the parser to handle a multi line inline attribute and added some test cases. 
It will be part of the next release.

**Comment by ahus1** [comment]
Release 0.30.41 has been published including this fix.

**Comment by danhaywood** [comment]
Many thanks. You're doing fantastic work with this plugin,
really appreciate it.

**Comment by ahus1** [comment]
Hello Dan, if you like following links with on xrefs, you'll probably also like following links to Java classes and files: The recent versions of the plugin try to resolve monospace or italic text as Java class name or file names. Please give it a try, Ctrl+B and Ctrl+click work as usual to follow these links.

Please feel free to leave a review for the plugin in the [JetBrains plugin repo](https://plugins.jetbrains.com/plugin/7391-asciidoc/reviews).
