### ISSUE TITLE
Asciidoc plugin 0.30.38  - PlantUML diagram not displayed in HTML output.

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-intellij-plugin#409]
I've just upgraded to Asciidoc plugin 0.30.38 and encountered a new issue. The following PlantUML text

```
[plantuml, uml-example, png]
----
@startuml
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: Another authentication Response
@enduml
----
```

is correctly displayed in the preview window in IntelliJ.

![image](https://user-images.githubusercontent.com/13682850/75248109-331a3a80-57dc-11ea-886f-d375ce77dabb.png)

However, the HTML document generated by clicking on HTML in the toolbar, do not display the image at image all. It only displays:

![image](https://user-images.githubusercontent.com/13682850/75248210-652b9c80-57dc-11ea-9e8d-5a59b9030d9d.png)

The image is however displayed correctly when PDF output is selected.

![image](https://user-images.githubusercontent.com/13682850/75248316-a328c080-57dc-11ea-8553-e491f3c60b10.png)

This example worked correctly in earlier versions of the Asciidoc plug-in.

I have created a test document that I apply to new releases of the Asciidoc plug-in, just to check that the features I depend on, work as expected.

**Comment by ahus1** [comment]
I gave it a try in my local installation: copy-paste of the example into a file as the only content. I clicked on the browser and opened it in chrome. The result worked in my installation. 

Some seems to be missing in my setup to reproduce it. Could you please 
* paste the version information of your IDE
* did you set any attributes like imagesdir in the file, or maybe in an `.asciidoctorconfig` file?
* what browser did you use?

Thanks!

**Comment by ahus1** [comment]
I was able to reproduce it, I failed to fix it here for the browser preview as well #395. A fix is underway.

**Comment by ahus1** [comment]
I've published version 0.30.39 that fixes this issue. It should be available from JetBrains plugin mirrors shortly.

It is also available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases).

**Comment by wfouche** [comment]
I've tried the new release, and the issue remains unresolved. Please see the attached Asciidoc file that exhibits this issue. Again, when publishing from the toolbar to HTML  the PlantUML diagrams are not displayed in the HTML output, but publishing to PDF does what is expected. I'm also not setting imagesdir in the document.

[Getting-Started-With-Asciidoc.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/4255281/Getting-Started-With-Asciidoc.txt)

**Comment by ahus1** [comment]
Hello @wfouche - I'm sorry that I mis-read your bug report. I've mistaken it that you used the browser preview. 
I was able to reproduce the issue. Although I struggle to find out how this worked in previous releases: the HTML file is created in the same folder where the asciidoc-file is located. To show the image the image has to be in the same folder (if no imagesdir is set). 

I have now a working local setup that creates the plantuml image in the local folder when the HTML icon in the toolbar is pressed. Is this the behavior you expect?

Out of curiosity: Do you use the export HTML to publish the document, or do you use it as a preview? 

I plan to publish a preview version later tody.

**Comment by ahus1** [comment]
I've published 0.30.40 that in my tests fixed this issue. Please give it a try and comment if there are still problems.

**Comment by wfouche** [comment]
@ahus1 Thanks for resolving this issue! It now works as expected on Linux and Windows. 

> local setup that creates the plantuml image in the local folder when the HTML

That is the correct behaviour. It should do what the asciidoctorj tool does when run from the command-line.

> Out of curiosity: Do you use the export HTML to publish the document, or do you use it as a preview?

I use it for the final preview in order to be able to review the document and see the :toc: on the left.

Thereafter I publish the document using the command-line tools such as Maven or Docker to push the Asciidoc content to Confluence.

**Comment by ahus1** [comment]
Good to hear that it now works for you. There is also the "preview in browser", but that doesn't create the original HTML header, therefore the :toc: will not be on the left. Let's see if I can fix that when time permits.
