### ISSUE TITLE
pasted image, offer option to also add in link= attribute to image macro

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#410]
Following on from #402 (and thanks for that), it would be great if the dialog box offered the opportunity to also add in the link= attribute on the generated image: tag.

For example, I just pasted in a .png, and what was generated was:

    image::intellij-idea-run-feature.png[]

What I would like though is the option for this to have been:

    image::intellij-idea-run-feature.png[link="{imagesdir}/intellij-idea-run-feature.png"]

**Comment by ahus1** [comment]
I'm labeling this as a "good first issue" as this issue could be resolved by changing a small number of classes:

**PasteImageAction**: This class contains all the logic, and insertImageReference() inserts the final string into the document.

**RadioButtonDialog**: This class displays the dialog. One option would be to extend it to show (optional) check boxes below the radio button dialog. Another option would be to create a more specific dialog class PasteImageDialog. The existing class PasteTableDialog shows how to add drop-downs and check-boxes in dialogues.

The "[Getting started with coding](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#getting-started-with-coding)" in the Contributor's Guide shows how to setup a local development environment: IntelliJ and JetBrains JDK 8 are needed to get started.

I'm happy to help along the way. A manually tested solution is ok, no automated test is required.

**Comment by ahus1** [comment]
Adding a self-link to the image should be part of the UI theme, as it would otherwise clutter the documentation's source. 

A pull request for the Antora UI is available here, and I've submitted PRs to integrate this into the Apache ISIS Antora UI theme: https://github.com/apache/isis/pull/226, https://github.com/apache/isis-antora/pull/3

Therefore I close this issue.
