### ISSUE TITLE
IDE Drag and Drop broken by plugin

### ISSUE THREAD

**Issue by MindWithCake** [asciidoctor/asciidoctor-intellij-plugin#413]
Since version 0.30.38 the plugin breaks the Drag 'n' Drop editor feature. I had to disable the plugin to make it work correctly.

When I drag some text it is removed from its location, but when I drop it, instead of the selected text, I get whatever was stored in the OS copy buffer (like if I just ctrl + v instead of dropping).
I experienced it when editing Java files, it's not bound to Asciidoctor editing only.

What I expect is for the IDE d'n'd feature to work as expected.

I am on Ubuntu Linux 19.10 with a Gnome/Wayland session.

AsciiDoc Plugin Version: 0.30.39

IDE Name and Version: IntelliJ IDEA 2019.3.3 (Community Edition)
Build #IC-193.6494.35, built on February 11, 2020
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-40-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: DBN, Lombook Plugin, MavenRunHelper, com.intellij.ideolog, com.jetbrains.colorful.toolwindow.icons, jp.roundrop.sqlformatter, mobi.hsz.idea.gitignore, org.jetbrains.kotlin

**Comment by ahus1** [comment]
I am sorry that my latest release broke this functionality. While I prepare a fix, please consider downgrading to version 0.30.34 of the plugin.

To downgrade, download the version from the jetbrains plugin page and choose "install from disk".

**Comment by ahus1** [comment]
I've found the issue and corrected it. Fix is underway. I'll update the ticket once a pre-release is available.

**Comment by ahus1** [comment]
I've published 0.30.40 that in my tests fixed this issue. Please give it a try and comment if there are still problems.

**Comment by MindWithCake** [comment]
Yes, it's working fine now.
Thank you, you've been very fast ^^

**Comment by ahus1** [comment]
Good to hear it now works for you. Feel free to leave a rating for the plugin on the JetBrains plugin repo: https://plugins.jetbrains.com/plugin/7391-asciidoc
