### ISSUE TITLE
Syntax highlighting and block comment without empty line

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-intellij-plugin#414]
```
= Test
////
comment
////
:name: Guillaume

Hello, {name}!
```

![yo](https://user-images.githubusercontent.com/333276/75999419-75412b80-5f02-11ea-9951-bba4f6e02f71.png)

If I add an empty line before `////` then it's working.

**AsciiDoc Plugin Version**

`0.30.40`

**IDE Name and Version**

```
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020
Licensed to Guillaume GROSSETIE
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-88-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
```

**Comment by ahus1** [comment]
Thanks for reporting this. The parser didn't handle comments after a title correctly. I amended it and added a test case. 
This is fixed in the next upcoming release. I'll update this ticket once it is available.

**Comment by Mogztter** [comment]
Thanks for the blazing fast fix 👍

**Comment by ahus1** [comment]
Release 0.30.41 has been published including this fix.
