### ISSUE TITLE
Add folding for attributes in editor

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#416]
When referencing an attribute in the editor like {attribute}, the editor should offer folding, that is: displaying the resolved attribute value.

**Comment by ahus1** [comment]
The next upcoming version will contain this as an experimental feature. Users need to enable the option "Enable folding of attributes in the editor" in the settings. 

Attributes will be folded by default when the user opens a file. Attributes ending with "dir" will not be folded, as attribute names like imagesdir are used mostly in links AFAIK.

More experimentation in real life documents is required to finalize this feature.

![folding-attributes](https://user-images.githubusercontent.com/3957921/76015862-23a59a80-5f1c-11ea-9d46-e814941d87f8.gif)

**Comment by mojavelinux** [comment]
This is so incredibly cool!!

**Comment by ahus1** [comment]
Version 0.30.41 is available and contains a first experimental version. 

You need to enable it, see screenshot below. 

[Please consider using IntelliJ's fold/unfold keyboard shortcuts](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/FEATURES.adoc#user-content-folding-attributes). 

Folding of attributes works only in non-dumb-mode, that is: when all indexes are built. 

I'm looking forward to everyone's feedback as comments in this ticket. To me this might be a feature for advanced users. A first-time user of the plugin or IntelliJ might be confused how to work with attribute folding.

This feature is declared to be experimental. While it is experimental, expect bugs and not-yet-supported corner cases. The behavior may change between releases to accommodate feedback.

![image](https://user-images.githubusercontent.com/3957921/76145779-2f649e80-608d-11ea-8120-5c287f27df59.png)

**Comment by ahus1** [comment]
This feature retrieved some tuning in pre-release 0.30.42.

THe new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
