### ISSUE TITLE
Non breaking space

### ISSUE THREAD

**Issue by luvarqpp** [asciidoctor/asciidoctor-intellij-plugin#423]
1. I have need for non breaking space. I am using UTF-8 character for that: " ". I expect, that plugin will correctly handle it.

2. Second thing is that from libreoffice, I am used to insert nbsp with `Shift+Ctrl+Space`. It would be handy to have given shortcut declared.

```
Please provide a minimal Asciidoctor example for the problem. Of course I do not like breaks to occur just after the "short words" (definite article, preposition, ...). It depends on your preview window width if you trigger wrapping of nbps.
```
Plugin is through working ok with `{nbsp}` macro, described [here](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#attributes-and-substitutions).

Perhaps, this "issue" can be solved by learning, what to use as non breaking space. IMHO macro `{nbsp}` is ugly in raw text and it is "unreadable". Is there any other working non-breaking space character, which is being rendered as "space" in raw text, in plugin preview and also correctly in final html?

AsciiDoc Plugin Version: 0.30.42

IDE Name and Version: IntelliJ IDEA 2019.3.4 (Community Edition)
Build #IC-193.6911.18, built on March 17, 2020
Runtime version: 11.0.6+8-b520.43 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.3.0-40-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1910M
Cores: 8
Registry: 
Non-Bundled Plugins: DBN, Docker, Lombook Plugin, com.intellij.lang.jsgraphql, com.oliverlockwood.plugins.jenkinsfile, im.jeanfrancois.ideaplugins.ideafullscreen, net.seesharpsoft.intellij.plugins.csv, org.asciidoctor.intellij.asciidoc, org.intellij.scala, training

**Comment by mojavelinux** [comment]
You should be permitted to use a literal no-break space. There are some cases when the use of a no-break space will disrupt the parsing of the syntax. That's an inherent limitation of the language, so you'll need to understand those cases.

As an alternative, you can use `&#160;`.

**Comment by ahus1** [comment]
With the plugin you should be able to paste a no-break space and use it like normal text. If you find something that doesn't work as expected, please open a bug ticket against this plugin. 

Adding this character with a hot-key would be possible. Unfortunately the hotkey you suggest is used in IntelliJ for auto-completion. Could you think of a different hot-key? I could also add an action that you can bind to any custom hot-key. Please let me know what you think. 

The latest versions of the plugin support attribute folding, see #416. Once you enable this option, the "{nbsp}" in the raw text will fold to a regular space (with a slightly green background). 

 Folding for HTML attributes like `&#160;` is not supported yet, but I'll add it for one of the upcoming releases.

**Comment by ahus1** [comment]
@luvarqpp - I tried to copy-and-paste a non-breaking space, and I found that IntelliJ will change it to a regular space on pasting it. Therefore this doesn't seem to be an option. 

Still I could try to assign a hot-key. Please let me know if you think this would be helpful.

**Comment by ahus1** [comment]
Version 0.30.43 is available as a pre-release version and support folding of HTML attributes.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by luvarqpp** [comment]
Thanks for fast response. I have done additional research.
My setup: ubuntu 18.04 linux, i3wm (tiling window manager), intelij idea 2019.3.4.

I have found that inserting space by pressing `AltGr+Space` ([learned from wikipedia](https://en.wikipedia.org/wiki/Non-breaking_space#Keyboard_entry_methods)) will actually insert character with `C2 A0` codes (two bytes). I have turned [settings->editor->appearance->general->show whitespaces (all)](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206349049-How-to-make-show-whitespace-turn-on-as-default-) to on. Visualization is done slightly differently, so I can distinguish normal space and non breaking one.

![settings](https://user-images.githubusercontent.com/48614551/77162046-5cf91100-6aab-11ea-8b0b-1caff8584256.png)

Normal space is visualized as small dot and `AltGr+Space` is visualized as "nothing, just space". See attached image:
![sampleVisualization](https://user-images.githubusercontent.com/48614551/77162042-5bc7e400-6aab-11ea-9c13-947b99ae6ec8.png)
For ordinary humans, without magnifying glass, there is no "dot" after "of" and "the" word. After other words, there is a tiny dot.

PS: I like folding thing. I will try it when I have some spare time.

I think, this issue can be closed. I have only one think left. I need to remap `Ctrl+Shift+Space` to `AltGr+Space` in my head.

**Comment by luvarqpp** [comment]
Folding of `{nbsp}` is working. I will stick to `AltGr+Space` perhaps, but I like folding is present.

**Comment by ahus1** [comment]
I've been thinking about how to enhance the display of non-standard blanks. 
I could try some highlighting. It could be a different background color, or an [effect](https://upsource.jetbrains.com/idea-ce/file/idea-ce-e2d423f42b53eafd5c625b93149a0ebc7e49756c/platform/core-api/src/com/intellij/openapi/editor/markup/EffectType.java) like a box or underline. An inspection could show more information about the highlighted character.

Showing them as a different character would be best, but AFAIK there is no API for that.

**Comment by luvarqpp** [comment]
I think that `ROUNDED_BOX` effect could be nice (on single space character). If it would be too disturbing, IMHO colored background would be enough. Inspection would be also handy in some cases.

**Comment by ahus1** [comment]
I revisited this with IntelliJ 2020.2: it now includes visualization of special characters, like NBSP:

![image](https://user-images.githubusercontent.com/3957921/99722758-6bbc1b80-2ab1-11eb-957b-91a3f5812796.png)

Therefore there is nothing more for this plugin to visualize, therefore I close this issue.
