### ISSUE TITLE
Improve "Extend selection" logic.

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#425]
On Windows, ctrl+W. ... 

In the gif below, I hit ctrl-W twice.  First time extended selection to the word "Deployment", sexond time extended to the entire "xref:...[]".

Instead, I would have expected the second time to extend to the contents of the "[]" brackets, ie "Deployment Selection".  Only on a 3rd time, then up to "xref:...[]".

![ctrl-w](https://user-images.githubusercontent.com/1031625/77156412-3c26c080-6a97-11ea-923c-b23517bc6235.gif)

**Comment by ahus1** [comment]
With the next release extend selection now stop at more delimiters and withing delimiters.
