### ISSUE TITLE
Extend editor folding, for paragraphs too.

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#426]
The editor already folds headings, and sidebars (as per the screenshot).

It'd be nice to introduce a fold for every paragraph too..

![image](https://user-images.githubusercontent.com/1031625/77164648-a7c55980-6aa8-11ea-9822-a283459dc125.png)

**Comment by ahus1** [comment]
I'll add this to the next pre-release. I'll need some through testing though. I also updated the summaries in the structure view with a little bit longer texts. Let's see if that is helpful. 

I'll update this issue once a pre-release is available. 

cc: @donnerpeter
