### ISSUE TITLE
Add refactoring to inline an include:

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#429]
There is already a refactoring to extract a block of test into an include::xxx[]

This ticket is for the opposite: to take an include'd file and inline into the referencing file.

The refactoring should provide the option to delete the include'd file, provided that no other files reference it..  The semantics should be very similar to extract/inline for Java methods.

**Comment by ahus1** [comment]
The functionality was already there, but didn't trigger when the include was in a sub-folder or had an Antora prefix. 
This is now fixed and will be part of the next release.

**Comment by ahus1** [comment]
Pre-release 0.30.46 fixes a regression that includes without prefix or folder won't be inlined.
