### ISSUE TITLE
Provide ability to split preview pane horizontally as well as vertically.

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#431]
Provide ability to split preview pane horizontally as well as vertically.

**Comment by ahus1** [comment]
This is available in the options of the plugin: 

![image](https://user-images.githubusercontent.com/3957921/77232484-82684680-6ba1-11ea-80c5-699793789535.png)

Please comment if this doesn't resolve your request and I'll reopen the issue.

**Comment by danhaywood** [comment]
Thanks, guess I missed that. I suppose it could be made visible within the
editor? Java editor supports this, at least.
