### ISSUE TITLE
Support for custom pdf-theme

### ISSUE THREAD

**Issue by vladbragoi** [asciidoctor/asciidoctor-intellij-plugin#433]
Please provide a way to customize the theme specifying the `pdf-theme` argument expected by the asciidoctor-pdf command line tool.
Thank you

**Comment by ahus1** [comment]
I'm not familiar with the argument `pdf-theme`. Could you please provide a full command line?

What I've done in the past: To select a theme from within a document: there are the attributes `pdf-stylesdir` and `pdf-style`. The first points to a folder, the second points to a prefix of the theme file. 

You can find an example here: https://github.com/ahus1/asciidoctor-deepdive/blob/master/manual/src/main/asciidoc/manual.adoc

**Comment by vladbragoi** [comment]
This is the command I used to generate the pdf with a custom theme: 
`$ asciidoctor-pdf -a pdf-theme=basic-theme.yml index.adoc`
I tried with :pdf-theme: and was not working, but with your `pdf-style` it works:
:pdf-style: basic-theme.yml

Thank you!

**Comment by ahus1** [comment]
Happy to hear you got it working!

**Comment by wetzesa** [comment]
Short question for a better understanding of the base question...
This is a general question about using custom pdf themes and not to how to show the custom pdf theme in the IDE preview mode?

Why did I ask this...
I tried to use the configs to show the custom theme stuff in the IDE preview but it didn't work.

**Comment by ahus1** [comment]
@wetzesa - this is about the "PDF" button in the toolbar of the editor (screenshot below).

As the preview is using HTML only, any configuration in the PDF theme will not be shown in the preview. 

My recommended setup: 
* align the attributes/configuration that the HTML is close to the PDF you're about to create. 
* Use HTML preview to write the contents
* For a final proof-reading click the PDF button and look at the PDF

![image](https://user-images.githubusercontent.com/3957921/81094296-94a90480-8f03-11ea-8bc2-a263cad40954.png)

**Comment by mojavelinux** [comment]
> I'm not familiar with the argument pdf-theme.

pdf-theme and pdf-themesdir are the official attribute names now. pdf-style and pdf-stylesdir are deprecated. See https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#applying-your-theme
