### ISSUE TITLE
Provide ability to generate anchor when on a heading

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#435]
As per screencast, it would be nice if there was an additional "intention" (alt-enter) to generate the anchor for this heading.

![quick-tips-for-headings](https://user-images.githubusercontent.com/1031625/77300870-af724180-6ce6-11ea-8952-0da60131c338.gif)

**Comment by ahus1** [comment]
Thanks for sharing this idea. It will be part of the next pre-release.
Digging into this I found that block IDs work only for sections (at least two leading "=="), not for titles (just ohne "=").
The intention will add an block ID to titles as well, as these could be used as partials with leveloffsets. Just so you know.

**Comment by ahus1** [comment]
Pre-release 0.30.46 is available that includes this enhancement.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
