### ISSUE TITLE
create PDF / HTML from current file results in "unable to render AsciiDoc document"

### ISSUE THREAD

**Issue by hilbert-ralf** [asciidoctor/asciidoctor-intellij-plugin#438]
Hi,

first of all: thanks for the awesome plugin, helps me every day!

The PDF as well as the HTML button top of the editor view of asciidoc files don't work on my machine. Then I try to use these functionalities i get the following error in the idea log:

```
2020-03-25 11:18:32,433 [4325840]   WARN - org.asciidoc.intellij.AsciiDoc - unable to render AsciiDoc document 
org.jruby.exceptions.NameError: (NameError) uninitialized constant Extensions
	at org.jruby.RubyModule.const_missing(org/jruby/RubyModule.java:3749)
	at RUBY.<main>(<script>:158)
```

I remember it worked once and produced proper PDF files. Also the preview produces proper results.

I tried it with several asciidoc files. Everytime same result, even with minimal examples.

Here my system:
* AsciiDoc plugin in version 0.30.41.1
* Idea version: 
```
IntelliJ IDEA 2019.3.4 (Community Edition)
Build #IC-193.6911.18, built on March 17, 2020
Runtime version: 11.0.6+8-b520.43 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: Batch Scripts Support, CMD Support, Docker, GrepConsole, Key Promoter X, Lombook Plugin, PlantUML integration, YAML/Ansible support, amailp.intellij.robot, com.jetbrains.plugins.ini4idea, com.jivesoftware.robot.intellij.plugin, com.millennialmedia.intellibot, com.oliverlockwood.plugins.jenkinsfile, ideanginx9, mobi.hsz.idea.gitignore, org.asciidoctor.intellij.asciidoc, org.intellij.plugins.hcl, org.intellij.scala, org.mayevskiy.intellij.sonar, org.sonarlint.idea, org.sylfra.idea.plugins.linessorter

  #325

**Comment by ahus1** [comment]
Hi @hilbert-ralf - thanks for providing all these details. Unfortunately I wasn't able to reproduce it locally yet. I've installed IntelliJ IDEA 2019.3.4 + AsciiDoc plugin 0.30.41.1 on Windows 10 and a minimal conversion to PDF worked with a freshly created project.

Still, something seems to be different. To analyze:
* could you please supply the example document you ran your tests with?
* I haven't yet installed all the plugin you've installed; could you please deactivate the plugins and see if the problem persists? 
* do you know if any of the plugins you installed uses Ruby - maybe that plugin is a candidate for a conflict? 

I look forward to your analysis results!

**Comment by hilbert-ralf** [comment]
Well now i feel a little stupid. It did not work for weeks on my machine but suddenly it does. No matter which example asciidoc i test, html as well as pdf is generated properly. I not even changed anything on idea nor the installed plugins.
So sorry for the hassle and thank you for your time. I'm going to close this issue.

**Comment by ahus1** [comment]
Good to hear it works for you now!
The plugin runs several internal JRuby instances for preview, PDF and HTML. Maybe one of them got confused/stuck. Please let me know if it re-appears!

**Comment by hibahasan998** [comment]
hey, I have the same problem, it's generating xml files only

**Comment by ahus1** [comment]
Hi @hibahasan998 - this issue is old, closed and therefore most likely unrelated. Please open a bug issue and provide information about the IDE and plugin versions you're using.
