### ISSUE TITLE
Callouts with dot instead of number fail on reformat

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#443]
reformatting a page that follows, mangled the callouts underneath

```
[source,java]
----
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Service;

@Service
public class SomeSubscriber {

    @EventListener(ActionDomainEvent.class)
    public void on(ActionDomainEvent ev) {
        switch(ev.getEventPhase()) {

            case HIDE:                      // <.>
                break;
            case DISABLE:                   // <.>
                break;
            case VALIDATE:                  // <.>
                break;

            case EXECUTING:
                break;
            case EXECUTED:
                break;
        }
    }
}
----
<.> call `ev.hide()` or `ev.veto("")` to hide the action
<.> call `ev.disable("...")` or `ev.veto("...")` to disable the action
<.> call ev.invalidate("...") or ev.veto("...") if action arguments are invalid
```

Workaround is to put a line between each <.> line.

**Comment by ahus1** [comment]
The lexer doesn't yet handle situation when the callouts have dots and no numbers. Expect a fix soon.

**Comment by ahus1** [comment]
The pre-release 0.30.47 is available that fixes this issue. Please note that this pre-release also contains #439 that should speed up the plugin quite a bit. Although tests are green I hope that change doesn't break existing functionality.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
