### ISSUE TITLE
Provide a config setting to specify a default zoom level for the preview

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#444]
I find that the default rendering is too large fonts, and so I often manually change the zoom level.  But this doesn't stick, and I need to repeat for each new file I view.

It would be nice if there was a config setting that could fix the default zoom, 50%, 60%... 200% etc.

**Comment by ahus1** [comment]
Starting with 0.30.62 the default zoom factor can be configured in the plugin's settings, but only for the JavaFX preview. 

![image](https://user-images.githubusercontent.com/3957921/80137818-24fe5580-85a4-11ea-89eb-0b9fab878d96.png)

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

The UI could need a little more love (maybe an up/down arrow), but the functionality is ready-to-use as-is.
