### ISSUE TITLE
Don't create an anchor when one is already present.

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#446]
![block-anchors-too-many](https://user-images.githubusercontent.com/1031625/77709346-acb36d00-6fc2-11ea-835b-30302b50cb5c.gif)

**Comment by ahus1** [comment]
Thanks for reporting this. Hm, I missed a proper if-statement in the code, sorry for that.
A fix will be part of the next release.

**Comment by ahus1** [comment]
Pre-release 0.30.48 is available that includes this fix.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
