### ISSUE TITLE
Feature request: setting to enable/disable soft wrapping by default.

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#447]
Although this can be toggled within the editor, it would be nice if there was a global setting

**Comment by ahus1** [comment]
Hello Dan, 
this is already available in the standard settings of IntelliJ.
The plugin will give you a hint to enable it permanently if you enabled wrapping 5 times (netto) within a session.

The "soft wrap" option is somewhat in the middle of the "General" settings, you'll need to scroll down to see it (scroll bar hardly visible in screen shot).

![image](https://user-images.githubusercontent.com/3957921/77799028-38390680-7074-11ea-9c89-c10a87430ad2.png)

**Comment by danhaywood** [comment]
Thanks ... I think I used to know this, then couldn't find it again.

Is there an FAQ for these hints and tips? Perhaps the plugin should have a
little antora site of its own?

**Comment by ahus1** [comment]
A website has been discussed, but hasn't been implemented yet, see #321. For now there's the GitHub wiki. Please feel free to add a page.

**Comment by danhaywood** [comment]
ok, done.

https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/How-to:-change-soft-hard-wrap-setting
