### ISSUE TITLE
key bindings to switch from preview only to split view doesn't work

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#448]
I set up some key bindings for the 3 views : text only, split, preview only.

The key bindings work fine in the first two modes, but the binding for preview doesn't fire.

![image](https://user-images.githubusercontent.com/1031625/77776747-656ec000-7046-11ea-9088-f412f1b6bd8e.png)

**Comment by ahus1** [comment]
I tried it and it seems to be a focus issue.
Once i click on the preview with the mouse, the key binding to get to editor-only and editor-and-preview work again.
I'll have a look.

**Comment by ahus1** [comment]
The next pre-release of the plugin will fix it. But the fix will only work with IntelliJ 2020.1 Beta, not with 2019.3.4. 
I don't know why, but I had the same behavior with the Markdown plugin for IntelliJ (that inspired the preview in this plugin quite a bit). 
I've opened an issue with JetBrains, so make sure it's no coincidence: https://youtrack.jetbrains.com/issue/IDEA-236257

**Comment by ahus1** [comment]
Pre-release 0.30.48 is available that includes this fix. As described in the previous comment this will work only in 2020.1 Beta as expected.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
