### ISSUE TITLE
Two colons are not resolved as ROOT module

### ISSUE THREAD

**Issue by shendo-13** [asciidoctor/asciidoctor-intellij-plugin#449]
In Antora two colons **::** after the component means the module ROOT in page coordinates.

When I use an include or insert an image like:

include::component:**ROOT**:partial$page_to_include.adoc[]
image:component:**ROOT**:image.jpg[]

The live preview will render everything just fine.

But when I use the short form with two colons instead of the module name ROOT like so:

include::component::partial$page_to_include.adoc[]
image:component::image.jpg[]

The include and the image cannot be resolved.

The expected behavior should be equal regardless of using :: or ROOT in page coordinates.

include::component::partial$page_to_include.adoc[]
include::component:ROOT:partial$page_to_include.adoc[]

AsciiDoc Plugin Version: 0.30.41.1
IDE Name and Version: IntelliJ IDEA Community 2019.3 Build #IC-193.6911.18

**Comment by ahus1** [comment]
Thank you for reporting this issue. Older versions resolved "::" to the current module's name, not to ROOT. This has now been fixed.

Pre-release 0.30.48 is available that includes this fix.

Please give it a try and see if it solves your issue. Please note that this pre-release includes several other enhancements and fixes. Please have a look at the [change log](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CHANGELOG.adoc) for the full details. The most recent version also tries to validate xrefs. If you discover corner cases, please report them as new GitHub issues.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by ahus1** [comment]
Pre-release 0.30.49 is available, this improves the Antora handling again. Please use that version to give it a try.

**Comment by shendo-13** [comment]
Hi ahus1,
with pre-release 0.30.49 this issue is solved on my side. Many thanks for this quick fix.
Please do continue your great work on this excellent asiidoc plugin!

**Comment by ahus1** [comment]
You're welcome! Please keep the feed-back flowing.
