### ISSUE TITLE
Add or switch to a Gradle build

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor-intellij-plugin#45]
For now, the IntelliJ project files in git make it easy for contributors to develop and build the plugin.

Ideally, we want to use Gradle to build the project. This will avoid the need to maintain project files and help with automation tasks.

Using Gradle for an IntelliJ plugin project is not well documented. However, there are at least two resources we can draw from:

* https://github.com/melix/teamcity-groovy-buildstep
* http://arhipov.blogspot.com/2013/10/managing-dependencies-for-intellij-idea.html

**Comment by bodiam** [comment]
Chances are quite big that Jetbrains will never(*) improve their plugin system. Closing this issue now.

* = no, really, I mean it, never
