### ISSUE TITLE
New Feature: surround-with for tags

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#450]
I'd like to be able to use Code > Surround With, ie this function:

![tags-surround-with](https://user-images.githubusercontent.com/1031625/77935612-91d64680-72a9-11ea-8a79-2e55717299c3.gif)

in order to produce what at the moment I have to type manually:

![tags-manual](https://user-images.githubusercontent.com/1031625/77935629-98fd5480-72a9-11ea-87a4-6caa55beff61.gif)

**Comment by ahus1** [comment]
Livetemplates to the rescue! The next version of the plugin contains an template called `ad-tag-include` that will surround the selected text. It will also add a line comment before the "tag::" depending on the language of the file. 

![tag-for-include](https://user-images.githubusercontent.com/3957921/78066698-b6a7e800-7395-11ea-9cd3-76f56cee30c4.gif)

**Comment by ahus1** [comment]
Release 0.30.50 is available that includes this fix. It's finally an official release with all the changes since 0.30.42. Enjoy! 🎉
