### ISSUE TITLE
Add tag as code completion when including content

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#451]
Where Action.adoc has a tag::summary[] ... end::summary[] section, I'd like include:: to provide it as an option (and perhaps also offer "tag=" as well

![tag-intellisense](https://user-images.githubusercontent.com/1031625/77935770-cf3ad400-72a9-11ea-879d-d083758ad8c2.gif)

**Comment by ahus1** [comment]
Hello Dan, this should already work. I tried the Isis documentation in AuditerService.adoc, the autocomplete works for 

`include::refguide:applib-svc:example$services/audit/AuditerService.java[tag=refguide]`

as expected. Could you please show the source code of Ascion.adoc (as a snippet); maybe it doesn't parse the tags in the file correctly.

**Comment by ahus1** [comment]
Hello @danhaywood - I had a look at #450 and saw that the tags you added didn't include a line comment prefix. Please try again with a line comment prefix in the `Action.adoc` like

```
// tag::summary[]
This is some text.
Another line.
// end::summary[]
```

**Comment by danhaywood** [comment]
Yeah, that was a mistake on my part, they should have been commented.
