### ISSUE TITLE
intellij built-in TODO plugin doesn't list occurrences

### ISSUE THREAD

**Issue by quesada** [asciidoctor/asciidoctor-intellij-plugin#452]
behavior you see in the IDE

The TODO window (alt + 6) lists the files that have TODOs. This is good

Behavior you expect or want to see in the IDE or plugin.
There's an icon that suggest you can unfold the item if there are multiple occurrences. But this doesn't work. I have 4 occurrences on a file, but it doesn't unfold.

example; should list 4 TODOs
Put site out there

TODO: write draft of curriculum
TODO: ask teachers if they can mentor. Set price. this is an extra revenue stream for them
TODO: sprint on finding mentors
TODO: test tooling to collaborate, pair programming

AsciiDoc Plugin Version: 0.30.41.1

IDE Name and Version: pycharm 2019.3.3

**Comment by ahus1** [comment]
Hello @quesada, thanks for reporting this. 

This has been implemented to work with TODOs in comments, and these will be shown in the TODO windows and will be highlighted in the code as TODO items. 

But I see the issue that the file is listed with 4 occurrences but then can't be expanded. This is not a consistent behavior. 

Therefore we need to decide: 
* should only be TODOs in comments be counted? 

I would argue for "yes", as this is the behavior you get with TODOs in programming languages: they also work only in comments.

Please let me know what you think.

**Comment by ahus1** [comment]
Update: I've looked at the docs of Intellij: "IntelliJ IDEA lets you add special types of **comments** that are  highlighted in the editor, indexed, and listed in the TODO tool window".

The next version of this plugin will restrict the TODO view to TODOs in comments only.

**Comment by ahus1** [comment]
Release 0.30.50 is available that includes this fix.
