### ISSUE TITLE
Extreme Performance issue when editing larger Documents (~2500 lines)

### ISSUE THREAD

**Issue by xtermi2** [asciidoctor/asciidoctor-intellij-plugin#453]
When editing a larger document with lots of tables the Plugin is nearly unusable. When I type a character it takes about 10 seconds until it appears and the UI Thread is blocked (IDEA does not respond) 

I don't know since which version this performance issue exists, but with a previous version I was perfectly able to edit the same document. When I remember right, I edited this year this document, not long ago!

I'm sorry, I can't provide the document, it's internal.

AsciiDoc Plugin Version: 0.30.50

IDE Name and Version: IntelliJ IDEA 2019.3.4 (Ultimate Edition); Build #IU-193.6911.18, built on March 17, 2020

**Comment by ahus1** [comment]
I'm sorry to hear this, let's see how we can solve this: 

When the IDE freezes, IntelliJ creates an automatic thread dump. This might contain some helpful information for me. You can share it with me by email (see my GitHub profile for the address). 

Go to "Help | Show log in Explorer" to go to the log folder. In a folder like "threadDumps-freeze-..." you'll find the thread dumps. Please send the most recent ones. These files contain no data from the documents you're editing. 

There is also the "idea.log". This might contain information from documents you edited. Please review them before sending them or consider sending them to my email address. 

The public release before 0.30.50 was 0.30.41.1. As a workaround you might want to try to fallback to that version. You can download the previous versions from the IntelliJ market place: https://plugins.jetbrains.com/plugin/7391-asciidoc/versions

I'm looking forward to some logs!

**Comment by ahus1** [comment]
If you want to downgrade to a previous version, you download the ZIP file from the IntelliJ plugin page, and install it manually using the following option: 

![image](https://user-images.githubusercontent.com/3957921/78698078-09d3ea80-7902-11ea-8669-d7994c34082d.png)

**Comment by xtermi2** [comment]
On `0.30.41.1` I can't reproduce the issue, so seems to be added with `0.30.50`.

in `idea.log` is nothing interesting in the related time frame:
```
2020-04-07 20:17:16,706 [ 663112]   WARN - .diagnostic.PerformanceWatcher - UI freezed for 16064ms, details saved to /home/akeefer/.IntelliJIdea2019.3/system/log/threadDumps-freeze-20200407-201700-IU-193.6911.18-EditorImpl.processKeyTyped-16sec 
2020-04-07 20:17:41,976 [ 688382]   WARN - .diagnostic.PerformanceWatcher - UI freezed for 25250ms, details saved to /home/akeefer/.IntelliJIdea2019.3/system/log/threadDumps-freeze-20200407-201716-IU-193.6911.18-EditorImpl.processKeyTyped-25sec 
2020-04-07 20:18:07,617 [ 714023]   WARN - .diagnostic.PerformanceWatcher - UI freezed for 25639ms, details saved to /home/akeefer/.IntelliJIdea2019.3/system/log/threadDumps-freeze-20200407-201741-IU-193.6911.18-EditorImpl.processKeyTyped-25sec 
```
Here the threadDumps:
[threadDumps-freeze.zip](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/4446372/threadDumps-freeze.zip)

I hope this helps.

**Comment by ahus1** [comment]
Our original issue suggested a performance problem in the lexer, the thread dumps confirm it. 
I'm having a look at it.

**Comment by ahus1** [comment]
The pre-release 0.30.53 is now available that should fix this issue. 

I've optimized the lexer so that it faster in some several cases. I hope it is also faster in your case. I've also improved incremental lexing of the document. 

While all tests are "green", please look out for syntax highlighting problems in the editor and report any issues you see.

Please let me know if this pre-release improves the speed of the IDE.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by xtermi2** [comment]
Thanks, that was fast.
Tried `0.30.53` out. It's better/faster, but fare away from `0.30.41.1`. Here the new threadDumps: 
[threadDumps-freeze.zip](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/4452516/threadDumps-freeze.zip)

I played around a bit with the affected document:
-   The performance is extremely dependent at which part I edit. 
   -   At the top it's extreme fast (totally no issue). 
   -   In the middle it's OK (sometimes some short hangings of < 1 sec, but good usable). 
   -   At the end still unusable (freezings of 3-8 secs for each character when typing)
-   Between middle and end are some really big tables (~500 lines). When I delete them, It's nearly usable at the end of the document - but still relatively fare away from `0.30.41.1`.

I'll try to generate a demo document for you to reproduce it.

**Comment by ahus1** [comment]
> The performance is extremely dependent at which part I edit.
The incremental lexing breaks it down into parts on section headers and blank lines between blocks.

> Between middle and end are some really big tables
A table would be one big chunk in incremental lexing. I'll need to give it some thoughts on how to break it down. 

> ... but still relatively fare away from 0.30.41.1
The newer versions implement improved lexing for passthrough content and therefore have a lot of look-forward for "+". This probably kills performance.

I'll give it some thoughts to limit the look-ahead within tables. That should speed things up. And will add some logging to pin-point these issues. 

Knowing that this is about tables helps a lot; I'm looking forward to a demo document.

**Comment by xtermi2** [comment]
Here a more worse demo document then my "productive" document: 
[test.zip](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/4452834/test.zip)

**Comment by ahus1** [comment]
The next pre-release 0.30.54 is available. It implements incremental lexing for tables on row-level: lexing will re-start on every line beginning with a "|". I thought about re-starting only at blank lines within a table, but as your example didn't have blank lines I opted for "|". 

Please give this release a try and let me know if this works better. 

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by xtermi2** [comment]
Thanks a lot! 
`0.30.54` fixed the performance issue.

**Comment by ahus1** [comment]
Thank you for the fast feedback and the examples and logs on the way.
