### ISSUE TITLE
Validate block vs. inline macro

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#456]
Macros like `include` are always a block macro, that is: they have two colons (`::`). Other macros like `xref` are always inline macros: they have a single colon (`:`).

The plugin should show an error in the editor when a well known macro uses the wrong number of colons. And it should offer a quick fix.

If the user doesn't change the type, the macro will be rendered as plain text. The user could have  redefined the macro but this would be rare.

**Comment by mojavelinux** [comment]
> Macros like include are always a block macro

An include is a directive, not a block macro. Same syntax, but not the same terminology. And directives are always line-based, so they use the double colon syntax.

**Comment by ahus1** [comment]
Will be part of next upcoming release.
