### ISSUE TITLE
"Anchor doesn't resolve" error for bibliography references

### ISSUE THREAD

**Issue by mikeholler** [asciidoctor/asciidoctor-intellij-plugin#459]
Please copy/paste this self-describing report into IntelliJ to replicate. A picture is provided below so you can see what I'm seeing. Direct your attention to the red underline in the picture. Thank you for your help in advance.

```adoc
= "Anchor doesn't resolve" error for bibliography references

After updating to 2020.1 (see table: <<intellij-version>>) and updating to the latest Asciidoc plugin (`0.30.57`), I am easily able to reference *tables* (<<intellij-version>>) and *sections*  (<<references-section>>), but am unable to reference bibliography items <<asciidoctor-intellij-plugin>> without a red underline error.
However, clicking the rendered `[1]` link for *bibliography* items brings me to the bibliography, as I would expect.

[#intellij-version]
.IntelliJ Version Information
----
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Licensed to Michael Holler
Subscription is active until February 4, 2021
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-96-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Non-Bundled Plugins: IdeaVIM, mobi.hsz.idea.gitignore, io.protostuff.protostuff-jetbrains-plugin, org.jetbrains.plugins.rest, org.jetbrains.plugins.vagrant, com.intellij.kubernetes, Pythonid, ru.meanmail.plugin.requirements, org.jetbrains.plugins.ruby, org.intellij.scala, nl.rubensten.texifyidea, org.asciidoctor.intellij.asciidoc
Current Desktop: ubuntu:GNOME
----

[#references-section]
[bibliography]
== References

* [[[asciidoctor-intellij-plugin,1]]] "GitHub: asciidoctor/asciidoctor-intellij-plugin." Available: https://github.com/asciidoctor/asciidoctor-intellij-plugin
```

![Screenshot from 2020-04-13 12-48-32](https://user-images.githubusercontent.com/1164112/79144775-25694600-7d85-11ea-9f54-a89e76a669db.png)

**Comment by ahus1** [comment]
Thanks for reporting this. 

I looked at the code and the plugin doesn't yet support bibliographic references. I'll prepare a fix for the next release. 

As as workaround you might want to disable the "Link resolve inspection" and re-enable it once an update is available.

![image](https://user-images.githubusercontent.com/3957921/79156740-b109c380-7dd3-11ea-9580-08b70df6a0e2.png)

**Comment by mikeholler** [comment]
Hey, thanks for the quick response. It's worth noting that the versions I upgraded from (and I didn't keep that information) didn't have this problem. In other words, to me this appears as a regression.

**Comment by ahus1** [comment]
Checking links and references is a relatively new feature. This is a "false positive", as the plugin doesn't understand the bibliography (yet).

**Comment by ahus1** [comment]
There is now pre-release 0.30.59 available that fixes this issue. 

It includes parsing for bibliographic reference ids. You can now also find-usages and rename ids. 

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by mikeholler** [comment]
What a quick fix. Thank you!

**Comment by ahus1** [comment]
You're welcome. Please let me know when you find other glitches in the plugin. Besides that, I'm always happy for users leaving a review in the IntelliJ market place: https://plugins.jetbrains.com/plugin/7391-asciidoc
