### ISSUE TITLE
Regression in 58 or 59: handling of includes in partials

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#460]
To reproduce, in the Apache Isis documentation, open up one of the component-nav.adoc files, eg

https://github.com/apache/isis/blob/master/extensions/adoc/modules/ROOT/partials/component-nav.adoc

This is fine in 57 but fails in 59 with a stack trace.

**Comment by ahus1** [comment]
I've checked out the latest master, and opened the component-nav.adoc you named above with version 59, but didn't see an exception. 

Could you please post the exception in this issue? It should still be available from "Help | Show Log in Explorer". 

Thanks!

**Comment by ahus1** [comment]
I was able to generate a message "unable to render AsciiDoc document java.lang.NullPointerException: null" in the preview after removing a version attribute from an antora.yml. Please comment if this is the issue you're seeing.

**Comment by danhaywood** [comment]
Yes, that was it, thanks.

**Comment by ahus1** [comment]
Pre-release 0.30.60 is available that fixes the NPE.

Please note: When an xref/include references a component, the plugin will look for the latest version in the project. An antora.yml with no version set will be sorted last.

This way in a scenario with distributed components any other antora.yml from the same component with a set version will rank higher. This might lead to a situation where you're not able to reference anything from this partial component that contains the antora.yml without a version. 

An antora.yml without a version and a name is an error. The plugin should probably notify the user than antora.yml without a name and a version is invalid. I'll create an issue for that.

As I was able to reproduce the problem, I close the issue. Please comment if the problem persists and I'll re-open the issue. 

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
