### ISSUE TITLE
default zoom level for preview pan

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#465]
I find the default font size for the preview pane is just a bit too big when compared to the source code on the left, meaning that I often do a manual zoom to resize it.

It would be nice if this could be configured as a default

**Comment by ahus1** [comment]
Thanks for raising this. There is also #444. Would this be covered by this ticket, and could I close this ticket as a duplicate?

**Comment by danhaywood** [comment]
Apologies. I guess it must really annoy me!
