### ISSUE TITLE
Plugin seems to break Java 'Introduce Variable' refactoring

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciidoctor-intellij-plugin#466]
With the plugin installed and activated, editing in Java source code (and possibly other languages) seems to be affected. I've attached a video at https://youtrack.jetbrains.com/issue/IDEA-238448 that shows the behaviour I'm seeing.

In short, when you highlight an expression and perform the 'introduce variable' refactorying, the cursor jumps to directly before the newly introduced variable, but typing doesn't rename the variable. Instead the selected expression (which is still selected) gets overwritten with any entered input. This effectively breaks the introduce variable refactoring.

AsciiDoc Plugin Version: 0.30.61

IDE Name and Version: IntelliJ IDEA 2020.1 (Ultimate Edition) Build #IU-201.6668.121, built on April 8, 2020
Non-Bundled Plugins: PlantUML integration, com.jetbrains.upsource, com.stylismo.nullability-annotations-inspection, JProfiler, Pythonid, org.jetbrains.plugins.ruby, org.asciidoctor.intellij.asciidoc

**Comment by ahus1** [comment]
Thanks for reporting, will have a look.

**Comment by ahus1** [comment]
It seems that I've introduced the bug in pre-release 0.30.60. Thanks for giving the pre-releases a try, I am grateful for the early feedback on new versions. 

Expect a fixed version later today.

**Comment by ahus1** [comment]
Pre-release 0.30.63 is now available that fixes this issue. Sorry for the inconvenience. 

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by pepijnve** [comment]
Thanks for the quick fix @ahus1. I'll try it out asap.

**Comment by pepijnve** [comment]
@ahus1 confirmed that it's fixed in the 0.30.64 build.

**Comment by ahus1** [comment]
I found that the workaround I added for this is no longer compatible with EAP 2024.1. I'm about to revert it in 0.41.9 and it seems that it is no longer necessary. Please report problems in a new issue. The removal is tracked in #1533

**Comment by ahus1** [comment]
Apparently it is still necessary. Reverting the change in #1591
