### ISSUE TITLE
Support language injection/syntax highlighting in tables

### ISSUE THREAD

**Issue by docent** [asciidoctor/asciidoctor-intellij-plugin#467]
The (amazing) AsciiDoc plugin has syntax highlighting and language injection for code fragments. However, that doesn't work when the code fragment is in a table column that has "a" styling (which means it contains AsciiDoc markup). Here's an example:
```
[cols="a"]
|===
|[source,json]
----
{
    "hello": "world"
}
----
|===
```

When rendered to HTML, you can see the syntax highlighting, however it's missing in the editor.

AsciiDoc Plugin Version: 0.30.59.1

**Comment by ahus1** [comment]
The plugin doesn't yet support parsing tables completely. The current lexer/parser applies an incremental approach of the document and will not honor the "cols" attribute of the table. 

A slightly different syntax will allow the current lexer/parser to provide syntax highlighting: if the `[source...]` starts on a new line the lexer will "see" the source block. This highlighting will work even when you remove the cols attribute (but then Asciidoctor will not obviously not treat it as a source block in the rendered preview any more).  

Please note: this behavior might change in the future while the highlighting evolves. Until it is fully supported for tables, there might be a time where this kind of tweak will not work.

```
[cols="a"]
|===
|
[source,json]
----
{
    "hello": "world"
}
----
|===
```

**Comment by ahus1** [comment]
Pre-release 0.30.68 is available that parses table cells. This will recognize the original example as a source snippet.

It will treat all contents in tables with AsciiDoc highlighting, independent of cell or column "a"-format.

I'd be happy if you could give it a try. I'm trying to teach jflex some new tricks for this, and also enabled incremental lexing/parsing on table cell level to speed up the editor for large tables. I'd like to know if I missed some corner cases.

@xtermi2 - as I know you're handle large tables, I'd be happy if you could give this pre-release a try as well.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by xtermi2** [comment]
tried it out, the syntax highlighting in tables works for me without noticeable performance drawbacks :+1:
