### ISSUE TITLE
Sentence-per-line violated by reformat if sentence ends with a digit

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/asciidoctor-intellij-plugin#470]
Apply a reformat to the following document:

```adoc
= Title

Some text here.
Some text about CSS3.
Some more text.
```

Expected: document is not modified.

Actual: document is formatted this way:
```adoc
= Title

Some text here.
Some text about CSS3. Some more text.
```

AsciiDoc Plugin Version: 0.30.59.1

IDE Name and Version: RubyMine 2020.1
Build #RM-201.6668.156, built on April 14, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.

**Comment by ahus1** [comment]
Thanks for reporting this. The current heuristic recognizes an end of sentence only if the "." is a number in front of it to cover examples like "der 1. Platz" (German for "the 1st place").

A future version of the plugin might support it. Volunteers welcome.

**Comment by ahus1** [comment]
A dot after a number is ambiguous. It could be the end of a sentence or not. 
As it is ambiguous, the plugin will keep it "as is". Both two texts will not be reformatted and be kept as is.

``` 
Some text here.
Some text about CSS3.
Some more text.
```

and 

```
Some text here.
Some text about CSS3. Some more text.
```

This will be part of the next upcoming release.
