### ISSUE TITLE
Preview pane doesn't show emboldening (0.30.67)

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#471]
I don't know if this is new, but the preview pane doesn't seem to render bold words correctly.

The editor pane does, (and the rendered page produced by Asciidoctor/Antora does too).

For example: 

![image](https://user-images.githubusercontent.com/1031625/80315263-42befb00-87ee-11ea-9cac-22969a50f4e5.png)

**Comment by ahus1** [comment]
The preview sometimes mixed up the fonts; it either shows everything in bold or everything in regular. It's been reported before, see #420. I don't know yet how to track this down, it seems to be a timing issue when loading the fonts. Sometimes I fixed it by closing/re-opening the preview. Restarting the IDE worked best. :-(

I opened the file in my IDE and it shows bold text in the preview for this snippet.

I'm closing this as duplicate. Fixing this properly most likely depends on upgrading to another embedded browser (#390)
