### ISSUE TITLE
Incorrect display of .svg files in preview

### ISSUE THREAD

**Issue by MaciejPatro** [asciidoctor/asciidoctor-intellij-plugin#476]
When I incorporate image of svg type:
```
image:overview.svg[overview]
```
I can see only part of the picture rendered in the preview (UML diagrams don't show boxes etc.).
When I generate html/pdf version everything works correctly.

I would expect that Preview mode supports svg images fully. (As these are quite useful due to the fact that they are basically a sourcecode and can be easily stored as part of documentation within git repository).

AsciiDoc Plugin Version: 0.30.59.1
IDE Name and Version: CLion 2020.1.1 Build #CL-201.7223.86, built on 29 April 2020

**Comment by ahus1** [comment]
The integrated WebView doesn't support SVGs very well. For users of PlantUML and AsciidoctorDiagram I've added workaround to show PNGs instead of SVGs in the preview. 

Current hopes are for #390 to provide a better preview for SVGs, but I don't have a date when this is implemented and JCEF is included in all JetBrains IDEs.

What program do you use to create the SVGs? It would be a great help if you could provide a minimal example (I've seen some SVG images work, while other SVGs were distorted)

**Comment by MaciejPatro** [comment]
Some of the images are generated from PlantUML - at least the ones that I've noticed the problem with.

I do want to provide them as svg for a reason that most of the users of our documentation use browsers as default tool and due to some legal requirements we can't send diagrams (considered sensitive) outside internal servers - which is too easy with the default option of `kroki.io` in the plugin. (Long story short - it's safer to have it as an image).

If you have any other recommendation on how we can tackle the issue - I would really appreciate it. 

Thank you for fast response and clear explanation! :)

**Comment by ahus1** [comment]
For PlantUML there are two options you have: 
1. install [Graphiz](https://www.graphviz.org/) on your local machine and render PlantUML "on the fly" [on your local machine](https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Rendering-previews-for-asciidoctor-diagram) 
2. use Kroki and setup your own rendering instance for the diagrams

In my projects I use the first option.

Once you use the following syntax this will create a SVG for your PDFs and a nice preview in your IDE:

```
[plantuml, diagram-classes, svg]
....
class BlockProcessor
class DiagramBlock

BlockProcessor <|-- DiagramBlock
....
```

**Comment by ahus1** [comment]
(if you prefer (like me) to have your PlantUML in a separate file, you can move the contents to an include or use the shorter block-macro syntax. I mostly use the include syntax as this helped me with some relative paths and UTF-8 characters)

**Comment by ahus1** [comment]
Closing this issue for now. If there are more questions, please comment and I'll reopen the issue.
