### ISSUE TITLE
paste and save the image with the current date

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#477]
Hi, is it possible to save the image with the current date without specifying it manually ?
Thanks

_Originally posted by @Musaizen in https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/298#issuecomment-619763976_

**Comment by ahus1** [comment]
I've moved this to a new issue as the old issue has been closed for quite some time. 

When pasting contents from the clipboard, and the clipboard includes only a snippet, there is a default static name "file.<extension>" that doesn't include date or anything else. 

I you think the plugin should be improved, please share your thoughts.

**Comment by Musaizen** [comment]
Well if it's possible to pre-fill a name different from "file", based on the current date ?
And maybe a specific directory for destination ?
To discribe our current use, as we have many documents with images, we store them in a directory named from the adoc file.
ex : Pages/howToAsciidoc.adoc -> Images/HowToAsciidoc/2020-05-02_02-05.jpg
The name does not speak for itself which may not good, but it helps people to take quick notes on their work.
Anyway, the current plugin is still perfectly usable the way it is.
Thanks :)

**Comment by chunlinyao** [comment]
I use asciidoc to write user manual, which contains many screencapture. I can config  external tools to `screencapture` command and bind to a shortcut key, but when I use `ctrl-v` to paste the screencapture. the dialog is annoy. It prompt the format and file name. Which broke my writing flow. I like it generate some unique filename, and can config a default folder and format. It is convenient if only one dialog with default config filled or totally no dialog.

**Comment by ahus1** [comment]
I started working on this. The upcoming implementation will: 
* memorize the previously selected file type within the IDE's session
* memorize the previously selected folder for a given file within the IDE's session 
* Using the last folder used if this is the first image save for the file unless the user changed the Antora module
* the default image name when pasting from the clipboard will include a timestamp (`image-<yyyy-MM-dd-HH-mm-ss>.png`)

For screen capture PNG is a good default IMHO. As the target folder might depend on the file selected, I'd rather not make it configurable.

Please comment if these planned changes appear to be an improvement.

**Comment by ahus1** [comment]
This is now part of pre-release 0.31.19. A small variation of the behavior described above: the image name contains also the milliseconds, so it should be quite unique event for fast workers.

Please comment and let me know if this works for you better than before.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by chunlinyao** [comment]
Hi

The new version is far more improved. very thanks.

The folder and format is related to the edit file, maybe the module. folder change is not for every paste. so if we can display the current folder and file name in format select dialog, give default focus to the filename input. we only require single enter key for confirm the paste. but the use shold do an extra action to show folder select dialog.

**Comment by ahus1** [comment]
I'm happy to hear that this version works better for you. 

It now takes three keystores to paste the second image after the user selected the folder: Ctrl+V, Enter, Enter 

I'm afraid that I didn't understand your comment about the default focus of the filename input; in my IDE it has already the focus. As a standard IntelliJ UX feature the text of the input field is selected.

I'd like to keep the IntelliJ UX. If you want to automate it further, maybe tools like [AutoIt](https://www.autoitscript.com/site/) might help you. 

I'm closing this issue for now. If someone want to change the behavior any further, please open a new issue and discuss the change or provide a pull request.

**Comment by chunlinyao** [comment]
Hi

What I mean is put the filename in the format dialog,
========================
|  ◎ PNG
|  ○ JPEG
|  filename: foobar.png  [...]
========================

Because we provided the good default value. so if user like change folder
and filename, he can click [...]




Alexander Schwartz <notifications@github.com> 于2020年8月16日周日 上午2:58写道：
