### ISSUE TITLE
Unicode font issues in preview on Fedora/Linux

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#478]
> unicode is not properly supported (you get ??? instead of the character)

Here's a screenshot from the Antora docs:

![javafx-unicode-problem-resized](https://user-images.githubusercontent.com/79351/80841049-dd875300-8bbb-11ea-896e-623faa911305.png)

It could be lack of support for fallback fonts, or that those glyphs are in the font being used for the preview. Hard to say.

_Originally posted by @mojavelinux in https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/390#issuecomment-622565047_

**Comment by ahus1** [comment]
I gave it a try on Fedora. When I opened IntelliJ, I got the screenshot below without artifacts. Only when I changed the font in "File | Settings... | Editor | Font" the preview breaks like in your screenshot. Once I close the editor and open it again, the preview is restored like below.

Can you please provide more details on the behavior you see?

![image](https://user-images.githubusercontent.com/3957921/80923788-fe030900-8d85-11ea-9da2-6295c125aa24.png)

**Comment by ahus1** [comment]
Some background on font handling and CSS in the plugin: 

* the plugin tries to be "offline first", that is: the preview should not depend on fonts loaded from the internet. This requires fonts to be bundled.
* The standard Asciidoctor theme uses Google fonts. I haven't found a set of "Noto Serif", "Open Sans" and "Droid Sans Mono" in TTF format to bundle. Therefore the preview bundles and uses the DejaVu-fonts. The DejaVu-fonts are the first fallback font option in the Asciidoctor style sheet.
* Over time some problems with the Asciidoctor CSS and JavaFX surfaced; due to this some of the CSS is patched on the fly: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/src/main/java/org/asciidoc/intellij/editor/javafx/JavaFxHtmlPanel.java#L306

Using JCEF will probably solve some of the quirks that need patching; it will not solve the pre-packaging of Google fonts. 

I found some of the fonts except "Droid Sans Mono" for download here https://google-webfonts-helper.herokuapp.com/fonts - as they are Apache licensed it should be ok to bundle them.

**Comment by ahus1** [comment]
Update: the next version of the plugin will include "Noto Serif" and "Open Sans" for the preview. It will not include "Droid Sans Mono", as OpenJDK can't synthesize bold/italic fonts from it.

**Comment by mojavelinux** [comment]
> the next version of the plugin will include "Noto Serif" and "Open Sans" for the preview.

Yeah!

> It will not include "Droid Sans Mono"

It's not a very complete font anyway. Better would be to use an alternative. Personally, I prefer M+ 1mn, which I think is a tremendously nice monospaced font. See https://osdn.net/projects/mplus-fonts/releases/62344 and https://mplus-fonts.osdn.jp/about-en.html

However, it might be better to use the monospaced font that is used by the editor in IntelliJ. That way, it matches what you are typing in the other pane. One way or another, it needs to be a complete font (full unicode support).

> Only when I changed the font in "File | Settings... | Editor | Font" the preview breaks like in your screenshot. 

IntelliJ seems to use the system font by default, which is why we are getting different results. My Fedora machine is using Cantarell. That confirms it's a fallback fonts issue.

> the plugin tries to be "offline first", that is: the preview should not depend on fonts loaded from the internet. This requires fonts to be bundled.

That's a good strategy. However, it does seem like it doesn't use system fonts as fallbacks like some other applications. That's a constraint we have to work with.

>  I haven't found a set of "Noto Serif", "Open Sans" and "Droid Sans Mono" in TTF format to bundle. 

All of these fonts are open source.

* Noto Serif: https://github.com/googlefonts/noto-fonts/tree/master/hinted/NotoSerif
* Open Sans: https://github.com/googlefonts/opensans/tree/master/hinted_ttfs
* Droid Sans Mono: https://github.com/aosp-mirror/platform_frameworks_base/tree/master/data/fonts

> Using JCEF will probably solve some of the quirks that need patching; it will not solve the pre-packaging of Google fonts.

The difference is that the JCEF will most likely fall back to system fonts as that's what Chromium does. But we should still be bundling all the fonts that will get used.

**Comment by mojavelinux** [comment]
Just to make sure my position is clear, I'm 100% in favor of bundling the fonts used in the preview. That is a good strategy. It also matches what we've done in other tools like the browser live preview.

**Comment by ahus1** [comment]
@mojavelinux - the fonts you pointed at will cover several languages, but don't offer full Unicode support. Offering the full Noto Unicode support (including for example CJK) for regular/bold/italic/bold-italic would add several 100 MB to the plugin's size. See https://www.google.com/get/noto/ for an overview. 

See https://www.google.com/get/noto/help/guidelines/ for more details; apparently these would need to be separate font names, in the right order depending on the document's language used.

This sounds like a different issue/feature request. I know that fallback to system fonts already works with OpenJDK; it works with CJK characters, and some users confirmed that it is working. And it works also for characters in listings. If someone wants support for this (maybe by on-demand download for fonts), they should open a separate ticket.

**Comment by ahus1** [comment]
@mojavelinux - could you please reply to my comment https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/478#issuecomment-623170140? 
> Can you please provide more details on the behavior you see?

What JRE are you currently using for the IDE (did you switch JREs for JCEF support)?

**Comment by ahus1** [comment]
The next pre-release will no longer contain DejaVu Sans and DejaVu Serif fonts packaged in the plugin as the new default fonts for the preview are Noto Serif and Open Sans (as AsciiDoc users are probably used to them). 

If you depend on these fonts for the preview: The fonts are still the fallback-fonts. If you install them locally in the OS, the preview should fall-back to DejaVu Sans and DejaVu Serif for glyphs not present in Noto Serif and Open Sans.

To customize your preview for fonts and style sheets, please see #487.

**Comment by ahus1** [comment]
The pre-release 0.30.71 is now available with the updated fonts. 

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by ahus1** [comment]
The pre-release has been promoted to the regular channel, therefore I close this issue.
