### ISSUE TITLE
Dogfooding - Asciidoc/antora based website?

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#479]
It'd be nice if this plugin had a custom website, I would suggest using Antora.  The front page could be something a little prettier (as we did with isis.apache.org).

I'd be happy to assist in this as a small contribution to the great work done on this plugin.

**Comment by mojavelinux** [comment]
I agree. Note that repositories in the Asciidoctor organization will be able to be included in the docs.asciidoctor.org website. But it's up to this project to decide whether you want to be part of that site or have your own separate site.

**Comment by ahus1** [comment]
Thanks @danhaywood for triggering this. 

Thinking for a user's perspective I'd like to have a plugin-specific landing page. These would be people who haven't installed the plugin yet, who have installed it and want to familiarize themselves with the functionality, and those who look for information to go deeper or want to trouble shoot. There will also be content on how to extend the plugin/to contribute; that might not be on the landing page.

This landing page would have a navigation to "why/about", "getting started/quick tour", and a third option going deeper with something like "FAQ/getting productive".

I assume the landing page wouldn't be Antora, but having a custom layout.

After the landing page I'd like to setup the content Antora style. From a user's perspective I'd like to have it separate from the standard Asciidoctor documentation; a click on the upper-left icon should get the user to a plugin-specific page and not to an Asciidoctor page. Looking at for example https://asciidoctor-docs.netlify.app/asciidoctor.js/ the Asciidoctor-Logo, "Asciidoctor.js" and "The Docs @ Asciidoctor" link to three different places. If a user click on two of these, they won't find their way back to Asciidoctor.js :-(

To make things efficient, I'd like to setup publishing on Netlify (used it before, works reliably IMHO, AFAIK some parts of Asciidoctor already use it as well). While the Antora documentation content would live in the AsciiDoc IntelliJ plugin repo, it will need an additional repository for the site; this might also include the Antora UI.

**Comment by ahus1** [comment]
@mojavelinux - what would be the best way to provide the plugin with its own landing page? Would a sub-domain be an option (like "intellij.asciidoctor.org"?) 

We get into the well-known naming problem again. The plugin's name has always been "asciidoctor-intellij-plugin", although "IntelliJ" is the old name for "JetBrains", and most other plugins adopted "IDEA" as their suffix (like for example Checkstyle-IDEA). On the other hand this plugin works also with RubyMine etc. and this is confusing in its own way.

**Comment by danhaywood** [comment]
The isis.apache.org site has a custom landing page using supplemental-ui
... really easy, no plugins required, the entire site is build just by
running antora.

**Comment by mojavelinux** [comment]
Here's the file: https://github.com/apache/isis/blob/master/antora/supplemental-ui/index.html

**Comment by mojavelinux** [comment]
There will be a way to do this using a template in the future, but that's a good interim solution.

**Comment by danhaywood** [comment]
Works well enough for us!

**Comment by mojavelinux** [comment]
> The plugin's name has always been "asciidoctor-intellij-plugin", although "IntelliJ" is the old name for "JetBrains"

I think the IntelliJ name is pretty clear now that JetBrains has started using the term "IntelliJ-based IDEs" right on the main JetBrains site and on the blog (https://blog.jetbrains.com/idea/2020/01/intellij-based-ide-features-roadmap-for-2020/). So we could do the same.

**Comment by mojavelinux** [comment]
> Thinking for a user's perspective I'd like to have a plugin-specific landing page.

It seems very reasonable to me to have a dedicated landing page for the project that exists outside the docs. Something like `intellij-plugin.asciidoctor.org` would work (since it inverts the repo name).

**Comment by mojavelinux** [comment]
> This landing page would have a navigation to "why/about", "getting started/quick tour", and a third option going deeper with something like "FAQ/getting productive".

Btw, we have resources available if you want to contract a designer / webdev to create this page / sequence. Hit me up via e-mail and I'll share the details.

**Comment by mojavelinux** [comment]
> From a user's perspective I'd like to have it separate from the standard Asciidoctor documentation

I'll support whatever you decide to do. Though don't get too caught up in the details of the current prototype for docs.asciidoctor.org. That's just a quick and dirty configuration to get something running while we migrate the content. We can tune that layout and design based on the projects hosted there.

>  a click on the upper-left icon should get the user to a plugin-specific page and not to an Asciidoctor page.

When you're viewing the docs for the plugin, we can change the navbar template to help keep the user in context.

> If a user click on two of these, they won't find their way back to Asciidoctor.js :-(

The prototype definitely needs more work. We're not there yet.

So I encourage you to try joining with the other Asciidoctor docs at docs.asciidoctor.org (once we get it going) and let's see where we can take it. It should reduce the amount of overhead since we only have to maintain one site....yet the docs and nav still lives in your repo.

**Comment by ahus1** [comment]
> It seems very reasonable to me to have a dedicated landing page for the project that exists outside the docs. Something like `intellij-plugin.asciidoctor.org` would work (since it inverts the repo name).

@mojavelinux - please setup a Netlify site for intellij-plugin.asciidoctor.org. 
AFAIK asciidoctor.org is already on Netlify, so I can't put this sub-domain on my Netlify account. 

I've prepared a very minimal Netlify GitHub repo here: https://github.com/ahus1/intellij-plugin.asciidoctor.org that redirects to the GitHub repository of the plugin for now. I don't have access to create repositories in the asciidoctor organisation nor am I allowed to transfer the repository.

Once the technical seed is there, I'll start adding content.

Thanks!

**Comment by ahus1** [comment]
@danhaywood - I've published a first antora-based site for this plugin. 
The site is available at: https://intellij-asciidoc-plugin.ahus1.de/

@mojavelinux - I'll keep the site as a subdomain on my Netlify account for now to be able to debug/tweak as necessary.

The Antora content is in this plugin's repository in sub-folder `/doc`

The UI-part is located at https://github.com/ahus1/intellij-asciidoc-plugin.ahus1.de - it includes a start page based on Jekyll/Minimal Mistakes theme, plus the Antora playbook and and Netlify configurations.

The content from the plugin's wiki plus the contributor guide still needs to be migrated.

**Comment by mojavelinux** [comment]
> please setup a Netlify site for intellij-plugin.asciidoctor.org.

I have to research how to do this so that you can still use your own repository. I know some of the parts, but I could run into problems I don't yet anticipate. Let's get a separate issue going for it.

**Comment by danhaywood** [comment]
Looking very nice, Alexander.

Bit snowed under with work at the moment, but I'll definitely aim to give
back a bit of love with some PRs over the next few weeks.

Thanks
Dan
