### ISSUE TITLE
Support anchors in section titles

### ISSUE THREAD

**Issue by pstueck** [asciidoctor/asciidoctor-intellij-plugin#485]
Quite alike #469 the IntelliJ plugin also has some issues with anchors &hellip;

Please see attached file [test-plugin.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/4588178/test-plugin.txt) (an adoc masked as txt).
While I think &mdash; and also was mentioned so by @mojavelinux &mdash; it is okay that neither version one nor two works (`id-pretext*`), at least the `id-post` version should fully work and not claim an "unresolveable anchor" (quite alike the `id-before` header).

Although AsciiDoctor does render the first two versions with the forced ids into usable links &hellip; without a pretty text that ain't nice ;-)

So what would I like to see in the ~debugged~ enhanced version?
I'd like the plugin to offer just two ids for `<<` resp. `xref:…#` &hellip;
* `id-before`
* `id-post`
*also considered as a valid id resp. resolvable anchor*

**Comment by ahus1** [comment]
Section names and titles are not parsed to the level of detail that the editor understands the variants you attached. 

For now, please use the following variant: 

```
[[id-before]]
=== before header placed id
```

If you don't want to use this style, you can disable this check in your IDE (but then no anchors will be checked at all).  

They will work once #469 is implemented.

**Comment by pstueck** [comment]
Good to know and no bother at all &hellip; just needed to know 😃 

And no, won't disable anchor/link checks ... rather have the checks work in the plugin (that's why I'm quite unsatisfied with the plugin's handling of `xref:…#` and `xref:…#top` &hellip; maybe gonna file another issue 🤔).

**Comment by ahus1** [comment]
As #469 has been implemented, I close this issue as a duplicate.
