### ISSUE TITLE
PlantUML diagrams broken in 0.30.70 in Antora environments

### ISSUE THREAD

**Issue by agentgonzo** [asciidoctor/asciidoctor-intellij-plugin#489]
The PlantUML diagrams in the Preview panes are not working as expected. Instead of the rendered diagram, I am only seeing a blank square.

Rendered in the IDE:
![image](https://user-images.githubusercontent.com/1652511/81837421-c0983b80-953c-11ea-95b1-a095839899bb.png)

When I select `AsciiDoc` --> `HTML`, it renders correctly:
![image](https://user-images.githubusercontent.com/1652511/81837469-d148b180-953c-11ea-8c35-f56dc58c3da0.png)

It rendered correctly in 0.30.34

Thanks! 

AsciiDoc Plugin Version: 0.30.70

```
IDE Name and Version: IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: PlantUML integration, CheckStyle-IDEA, Lombook Plugin, com.oliverlockwood.plugins.jenkinsfile, Stapler plugin for IntelliJ IDEA, io.protostuff.protostuff-jetbrains-plugin, MavenRunHelper, com.intellij.kubernetes, Pythonid, com.intellij.lang.jsgraphql, org.asciidoctor.intellij.asciidoc
```

Also tested on:
```
IntelliJ IDEA 2019.3.2 (Community Edition)
Build #IC-193.6015.39, built on January 21, 2020
Runtime version: 11.0.5+10-b520.30 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: 
Non-Bundled Plugins: CheckStyle-IDEA, DBN, Docker, FindBugs-IDEA, Lombook Plugin, MavenRunHelper, Stapler plugin for IntelliJ IDEA, com.github.tinselspoon.intellij.kubernetes, com.intellij.lang.jsgraphql, com.oliverlockwood.plugins.jenkinsfile, io.protostuff.protostuff-jetbrains-plugin, org.asciidoctor.intellij.asciidoc
```

and:
```
IntelliJ IDEA 2019.3.4 (Community Edition)
Build #IC-193.6911.18, built on March 17, 2020
Runtime version: 11.0.6+8-b520.43 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: documentation.show.toolbar=true
Non-Bundled Plugins: BashSupport, CheckStyle-IDEA, DBN, Docker, FindBugs-IDEA, OdpsStudio, VisualVMLauncher, YourKit Java Profiler 2017.02-b75 Integration, com.dmarcotte.handlebars, com.intellij.lang.jsgraphql, com.soywiz.korge.korge-intellij-plugin, name.kropp.intellij.makefile, org.asciidoctor.intellij.asciidoc
```

**Comment by ahus1** [comment]
Thanks for reporting this and taking the time to trace back to the version where this was introduced. 

I tried to reproduce it with the following text locally (Windows 10) and didn't succeed yet. The following snippet worked in my IDE on Windows 10

IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b840.5 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

```
There should be a diagram here:
[plantuml]
----
@startuml
Bob->Alice: hello1
@enduml
----
```

Did you re-define `imagesdir` or `outdir` in your document? Did you set any other attributes in this document, or maybe in an `.asciidoctorconfig`-file?

**Comment by agentgonzo** [comment]
No, that was the entire document.

**Comment by agentgonzo** [comment]
I'll do some more digging tomorrow and see if I can find a trigger for it

**Comment by agentgonzo** [comment]
It looks like a few other files are needed to trigger the bug. 
Checkout https://github.com/agentgonzo/asciidoctor-489. That's the minimal project I could create that exhibited the bug.

Deleting any of the other parts of the directory structure will make the image render correctly.

**Comment by ahus1** [comment]
Thanks for preparing this excellent example; this helped a lot. 

There is now pre-release 0.30.72 available that works with the example you provided. As the example you provided now works, I close this ticket. Please comment if a the problem persists, and I'll re-open this ticket. 

Please note: PlantUML with Antora in this plugin works only with embedded diagrams and included diagrams, not with the Block-Macro style (for now). 

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by agentgonzo** [comment]
Great, thanks Alexander!
