### ISSUE TITLE
File not resolved on YouTube video

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-intellij-plugin#490]
The plugin resolves linked resources to warn the user about a missing resources. This is good but I think we should disable this check when we are using a reference to a remote providers (youtube, vimeo...). 
In theory, we could check if the reference exists on YouTube but I think it's not worth it and, in my opinion, the plugin should not do (unsolicited) remote calls.

```
video::haanomzfZbc[youtube,width=560,height=315]
```

![file_not_resolved3](https://user-images.githubusercontent.com/333276/82048654-5060f580-96b5-11ea-860b-48be14bc5bf8.png)

**AsciiDoc Plugin Version:** `0.30.72`

**IDE Name and Version**

```
WebStorm 2020.1.1
Build #WS-201.7223.93, built on April 30, 2020
Runtime version: 11.0.6+8-b765.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-99-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1931M
Cores: 8
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: org.jetbrains.plugins.slim, net.seesharpsoft.intellij.plugins.csv, BashSupport, org.asciidoctor.intellij.asciidoc, org.toml.lang
Current Desktop: XFCE
```

**Comment by ahus1** [comment]
Thanks for reporting this, the plugin is a bit too eager here. The next release will fix this.

Currently the plugin assumes files for the following macros:

```
// standard asciidoctor
"image", "include", "video", "audio",
// asciidoctor diagram
"a2s", "actdiag", "blockdiag", "ditaa", "erd", "graphviz", "meme", "mermaid", "msc",
"nwdiag", "packetdiag", "plantuml", "rackdiag", "seqdiag", "shaape", "svgbob",
"syntrax", "umlet", "vega", "vegalite", "wavedrom"
```

Any macro that I missed? Any other macro that behaves in a similar way like the video macro?

**Comment by ahus1** [comment]
Release 0.30.73 is available that resolves this issue for videos on youtube and vimeo.

**Comment by Mogztter** [comment]
Two hours later a release is already available with a fix, you are on fire! :fire: :fire: :fire:  
I've just upgraded and I can confirm that the issue is now fixed!

Thanks a lot! :bowing_man:
