### ISSUE TITLE
Move plugin's homepage to its own asciidoctor.org subdomain 

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#491]
The current plugin's homepage is hosted on https://intellij-asciidoc-plugin.ahus1.de with a GitHub repository at https://github.com/ahus1/intellij-asciidoc-plugin.ahus1.de

Hosting the homepage as part of the asciidoctor.org domain would make it more consistent. Moving the repository to the Asciidoctor GitHub organisation would make collaboration easier.

**Goals:** 
* host the plugin's homepage on intellij-plugin.asciidoctor.org 
* move the GitHub repository to the asciidoctor organization. 

**Conditions:** 
* the site should still deploy on Netlify (or a similar automatic static site hosting)
* the maintainer should be able to trigger re-deployments. 

I (Alexander) can't do this myself, as I don't have permissions in the Asciidoctor organisation to move the repository, and no permission on the Netlify hosting for asciidoctor.org.

(follow-up to #479 / @mojavelinux)

**Comment by ahus1** [comment]
@mojavelinux - if we agree on the goal and if you could provide temporary privileges/credentials, I can help moving/setting things up.

**Comment by mojavelinux** [comment]
I think you ultimately decided to keep the documentation separate. There is, however, a link from the Asciidoctor docs to the docs for the plugin the top nav.

If you ever change your mind, just let me know and we'll revisit.

**Comment by ahus1** [comment]
Thank you for the offer. By setting up its own site and maintaining it, I learned a lot about Antora, and added some additional functionality into the AsciiDoc plugin for IntelliJ. While this journey continues with this positive side effects, I plant to continue to keep the site separate. Once evidence comes up that points to another direction, I would eventually change course.
