### ISSUE TITLE
Improved partials editing support

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciidoctor-intellij-plugin#492]
When you're working on a large documentation project where many document contents are assembled using the `include` macro, editing of the included bits can be cumbersome.

When editing the page containing the `include` you have all the necessary context (e.g., attribute values) available, but all you see in the editor is the include macro.
When editing the included bit (e.g. an Antora partial) you see the content of the included bit, but you're missing the context and as a consequence may end up having unresolved attributes.
Neither option is ideal.

Being able to edit the partial content in place where it's included or conversely being able to specify the context when editing the partial directly would make the editing workflow easier I think.

**Comment by ahus1** [comment]
I could see the benefit here. Could you please point me to an open source repository, or could you provide a minimal example to evaluate this?

> When editing the page containing the include ... all you see in the editor is the include macro.

The preview should show the resolved content of the include. Can you confirm this? In the latest releases this should work for Antora projects as well. If not, please provide an example in a GitHub repo.

**Comment by pepijnve** [comment]
> I could see the benefit here. Could you please point me to an open source repository, or could you provide a minimal example to evaluate this?

Sure I'll try to cook up an example

> The preview should show the resolved content of the include.

Yes that works correctly.

**Comment by pepijnve** [comment]
I've create a little toy example at https://github.com/pepijnve/asciidoc_include_example

In short, when I'm editing the main file, I see the nice preview of the included contents but I cannot see the source for it.

<img width="1234" alt="Screenshot 2020-05-20 at 19 55 54" src="https://user-images.githubusercontent.com/225326/82480417-0e301d80-9ad4-11ea-91c4-7d9bda722b2f.png">

When I'm editing the included file, I lose the 'context' of the document attributes and the preview loses some of its value.

<img width="1239" alt="Screenshot 2020-05-20 at 19 56 01" src="https://user-images.githubusercontent.com/225326/82480525-3881db00-9ad4-11ea-8516-3fc2d40c794d.png">

So I'm trying to have my cake and eat it 😄 This is with plain asciidoc files, but the same thing applies to Antora projects.

**Comment by ahus1** [comment]
Here some comments on what works today and something new that is part of the latest pre-release 0.30.74.

What worked already:
1. If you have variables, and these variables are valid everywhere in a Antora component, you can put these variables in your Antora component descriptor; this is a feature of Antora 2.3. The plugin will pick them up, and they will be available in all pages and partials of that component. See https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/doc/users-guide/antora.yml for an example

2. If you want to set some attributes "just for the preview", put them in an ".asciidoctorconfig" file. In the case of your example repo (no Antora, just plain Asciidoc), I would add an ".asciidoctorconfig" file in the root directory and define the imagesdir attribute. This would then set the imagesdir for all files in the root folder and below. See  https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-project-specific-configurations for more information. You can also use it in to set ":icons: font" or ":experimental:". In Antora style projects I use it to re-define attributes usually only present in the playbook, see https://github.com/asciidoctor/asciidoctor-intellij-plugin/tree/master/doc for an example.

3. The imagesdir is pre-configured once you work in an Antora component; this should work in all partials as well, so there is no need to define it. If this is not working in your project, there's probably a corner-case that I didn't cover. Please file an issue if this is the (and update your example project to help me improve the plugin).

**The new stuff in 0.30.74:**

4. When a file changes on disk, the preview will update. This enables working in split mode. The following example creates a vertical split editor. The shared.adoc is on the left (editor only), the index.adoc is on the right, preview only (use the toolbar to switch). 
Every time save the contents in the editor on the left, the preview on the right updates. This is no longer instantaneous, as these are different files, but may get you a little close to your goal. 

Please let me know if this is a step in the right direction, and what further steps might be necessary. 

![fresh-all-previews](https://user-images.githubusercontent.com/3957921/82486295-ef825480-9adc-11ea-8380-6a752ac0dc5f.gif)

**Comment by ahus1** [comment]
The new pre-release 0.30.74 of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

**Comment by pepijnve** [comment]
5hat looks great @ahus1 ! Being able to see a live preview of the whole document while editing the constituent parts is exactly what I was looking for.

**Comment by ahus1** [comment]
Happy to hear this works for you. I close this issue for now; please comment if anything is missing and I can re-open the issue.

**Comment by pepijnve** [comment]
I had some time to really kick the tires of split view editing now. Works great already. The only difficulty I still see is autocompletion/validation in Antora projects.

In my project I have 4 components, one per product I'm documenting and one 'shared' component that contains partials that are used across the three other components. That shared component is never rendered itself, it's just a place to put shared content.

Those shared partials contain references to per product images. So for instance the partial contains `image::setup.png[]` and each product has a different image that's appropriate for that product. The preview of the page that `include`s the partial renders that correctly, and when I edit the partial and save the preview updates as it should. But `image::setup.png[]` gets a red squiggly underline because from the point of view of the partial editor, that image is unresolvable.

I realise this is tricky to solve; not sure how other complex document editors deal with this kind of thing. You kind of want to be able to say 'edit this file from the point of view of being included in some other file' and then have an option to toggle that point of view.

The other option is that I'm just 'doing it wrong'. Perhaps there's a simpler way to achieve the kind of content reuse I'm going for.

**Comment by ahus1** [comment]
There is always more than one way to do things. I outline some that come to my mind. 

**For a future version of the plugin**: The automatic checks shouldn't show false positives. I could disable the "AsciiDocLinkResolve" inspection on all partials. What do you think?

To get rid of the squiggly line **with the current version** of the plugin: 
1. place a dummy image in the shared component. You could even place some dummy attribute values in the shared component's component descriptor. This would give you a good preview when editing a partial; you wouldn't need to the split preview every time.
2. suppress the error - use Ctrl+Enter for that and the menu. See image below. The resulting snippet would be 
``` 
// suppress inspection "AsciiDocLinkResolve"
image::setup.png[]
``` 
![suppress-error](https://user-images.githubusercontent.com/3957921/82708870-9d2d6900-9c7f-11ea-8225-0398d36ff774.gif)

**Comment by ahus1** [comment]
Hi @pepijnve - I've revisited this issue after some time. Reading it again, I consider "placing a dummy image in the shared component" would provide the best preview in the scenario you describe above: A dummy could be just the right size to show how the content should look like. 

I would prefer to put a dummy image (to show a nice preview) instead of disabling the error message in the editor for partials and showing a broken image in the preview. 

As the dummy image is something that is already available, I close this issue as "nothing more to do". 

If you find other corner issues with partials, please let me know, and I'll re-open the issue.
