### ISSUE TITLE
Document how to customize preview

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor-intellij-plugin#493]
https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/455#issuecomment-611985921 shows that it is possible to customize the preview of the plugin, however https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/Support-project-specific-configurations makes no mention of this. It would be great if that page also included that information.

**Comment by ahus1** [comment]
The documentation of the plugin is currently in transition: some documentation is already on the new plugin's documentation web site. Some documentation from the Wiki (like the one you reference above) has not yet been moved.

The new documentation site describes a more recent approach on how to use stylesheets for the preview: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/stylesheets.html - see #487 for a discussion.

If this is not enough for what you need, the latest version of the plugin supports the `docinfo` attribute: This way you have full control over header and footer in the preview. There is documentation about `docinfo` in the Asciidoctor user guide, but not yet in the plugin's documentation. 

Contributions to the documentation are very welcome; both structure and content wise. The user's guide is in the `/doc/users-guide`, therefore pull requests are the best way to contribute.

**Comment by wimdeblauwe** [comment]
Seems like a better way indeed. Unfortunately, it does not work.

The CSS is only applied if I remove the `ifdef::css-online-preview[]` line.

Also, this completely replaces the CSS. Is there any way to import the default and just override some styles?

**Comment by wimdeblauwe** [comment]
I just tried with putting `asciidoctor.css` next to my custom css and using:

```
@import url("asciidoctor.css");
```

in my custom CSS, but that did not work.

I created the asciidoctor.css via `asciidoctor -a linkcss sample.adoc`

**Comment by ahus1** [comment]
The current implementation of the plugin inlines the CSS from the stylesheet, therefore the `@import` doesn't work as expected. 

To add CSS in addition to the existing styles, use the docinfo capability. I've updated the documentation. Please have a look: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/stylesheets.html

**Comment by wimdeblauwe** [comment]
Thanks, using docinfo works!
