### ISSUE TITLE
Statement completion no longer working

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor-intellij-plugin#494]
Statement completion used to work, but it has not anymore for quite some time, but I never got around to filing an issue. So unfortunately, I am not sure what broke it exactly.

I currently see the following behaviour:

1) List of languages not appearing

Before: Type `[source,` and a list of possible languages appeared.
Now: I get a tooltip with "No suggestions"
![image](https://user-images.githubusercontent.com/1115823/82755565-a5e38380-9dd4-11ea-8411-21d89c6377d4.png)

2) When I type `[source`, then IntelliJ inserts the closing bracket so it shows `[source]` with my cursor between the `e` and the `]`. If I then type CMD-SHIFT-ENTER (on macOS), it completes to `[source]]` instead of adding the `----` lines.

3) If I manually remove the last `]` after typing `[source`, so I actually have `[source` -> CMD-SHIFT-ENTER completes to `[source]` with the cursor after the `]`. If I do CMD-SHIFT-ENTER again, the 2 `----` lines are added and the cursor is between those lines.

* AsciiDoc Plugin Version: 0.30.73
* IDE Name and Version:
```
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020

Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.4
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Non-Bundled Plugins: PlantUML integration, com.alicannklc.tailwind, CheckStyle-IDEA, com.dubreuia, com.myoutdesk.tailwind_formatter, name.kropp.intellij.makefile, ru.adelf.idea.dotenv, org.jetbrains.kotlin, com.jetbrains.edu, training, org.asciidoctor.intellij.asciidoc, org.toml.lang
```

**Comment by ahus1** [comment]
Thanks for noticing it and opening a bug for it. I pushed some changes and it now works again. It will be part of the next release.

**Comment by wimdeblauwe** [comment]
Great! Thank you for the quick support!

**Comment by ahus1** [comment]
Pre-release 0.30.75 is available fixes this issue.

The new pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).
