### ISSUE TITLE
Large adocs with included pumls raise dot.exe abort on Windows

### ISSUE THREAD

**Issue by ascheman** [asciidoctor/asciidoctor-intellij-plugin#495]
Every now and then `dot.exe` as invoked from IntelliJ AsciiDoctor plugin on Windows aborts when working on `.adoc` files with included `.puml` files.

I see this error even if download https://github.com/dukecon/dukecon and open `src/main/asciidoc/de/index.adoc`. This file includes only very few `.puml` files.

AsciiDoc Plugin Version: 0.30.73

graphviz version 2.38.0 (20140413.2041)

IDE Name and Version: 
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020
Licensed to Gerd Aschemann
You have a perpetual fallback license for this version
Subscription is active until January 11, 2021
Runtime version: 11.0.5+10-b520.38 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: AWSCloudFormation, BashSupport, CMD Support, CheckStyle-IDEA, Error-prone plugin, Code Navigator, CodeNarc, CopyRestUrl, Dart, GrepConsole, Groovy Console Plugin, Hrisey Plugin, InspectorGroovy, Jenkins Control Plugin, Pythonid, JythonHelper, Key Promoter X, Key promoter, Lombook Plugin, PlantUML integration, Spock Framework Enhancements, Twelf Plugin, aws.toolkit, claims.bold.intellij.avro, codes.rudolph.idea.cfg, com.alayouni.ansiHighlight, com.amintado.bootstrap, com.andrewbrookins.wrap_to_column, com.arasthel.groovy.override-completion, org.jetbrains.kotlin, com.developerphil.adbidea, com.github.b3er.idea.plugins.arc.browser, com.github.novotnyr.gitlab-quickmr-idea-plugin, com.github.tinselspoon.intellij.kubernetes, org.jetbrains.plugins.go-template, org.jetbrains.plugins.go, com.google.gct.core, com.intellij.apacheConfig, com.intellij.ideolog, com.intellij.kubernetes, com.intellij.lang.puppet, com.jetbrains.php, com.intellij.phing, com.jetbrains.plugins.jade, com.junbo.idea.codenarc, com.mallowigi, com.mycila.intellij.plugin.gmavenplus, com.perl5, com.ppolivka.gitlabprojects, com.samsonova.scala.sd.id, com.siberika.idea.pascal, com.webschik.doT, org.intellij.scala, com.weirddev.testme, de.docksnet.puml.syntaxchecker, de.kontext_e.idea.plugins.jqa, mobi.hsz.idea.gitignore, name.kropp.intellij.makefile, net.seesharpsoft.intellij.plugins.csv, net.vektah.codeglance, tanvd.grazi, org.asciidoctor.intellij.asciidoc, org.intellij.plugins.hcl, org.jetbrains.plugins.ruby, org.jetbrains.plugins.vagrant, org.jetbrains.plugins.vue, org.logtalk, org.mapstruct.intellij, org.mayevskiy.intellij.sonar, org.sonarlint.idea, ru.adelf.idea.dotenv, training, xyz.ihac.derrick

**Comment by ascheman** [comment]
Sorry, cannot upload a screenshot for whatever reason (security-obscurity at current customer, you know 😉?)

**Comment by ahus1** [comment]
The latest version of PlantUML include a pre-packaged Graphviz. Running 

```
[plantuml]
----
@startuml
testdot
@enduml
----
```

shows

![image](https://user-images.githubusercontent.com/3957921/127558757-db247ea4-45bd-4ee1-aa4f-ea9d0444fb9b.png)

Do you still experience this problem?

**Comment by ascheman** [comment]
I have not seen this for a long time. My customer project is over and I am no longer working on Windows for more than 7 months.

**Comment by ahus1** [comment]
Thank you for the update. I close this issue for now. Once someone sees this issue with the more recent version I'll reopen the issue.
