### ISSUE TITLE
Image URLs do not work when absolute Windows path

### ISSUE THREAD

**Issue by source-knights** [asciidoctor/asciidoctor-intellij-plugin#498]
To use the preview but also to build overall documents structure with our build tools we have problem using relative image paths. 

Therefore we switched to absolute paths using the asciidoc buildin "docdir" attribute.
E.g. an adoc files uses: 
`image::{docdir}/images/rocketchat_installation_a.PNG[]`

When running this in IntelliJ on Windows {docdir} resolves to 
C:/dev/projects/doc/src/main/asciidoc/dokumentationen/installation_pc/

And sadly this plugin does not seem to handle paths starting with C: cause it then cannot find the images. Same problem when hardcoding that absolute path in the asciidoc file.

It only works when I remove the "c:"
Works: `image::/dev/projects/doc/src/main/asciidoc/dokumentationen/installation_pc/images/rocketchat_installation_a.PNG[]`
Does not work: `image::c:/dev/projects/doc/src/main/asciidoc/dokumentationen/installation_pc/images/rocketchat_installation_a.PNG[]`

But as we cannot modify the content of the docdir attribute it would be great if this can be fixed in the plugin (as it works in asciidoc, just not in the plugin review)

Used AsciiDoc Plugin version 0.30.73
IntelliJ version: tested with whole dev team, they all have different version up to the newest available

Thanks

**Comment by ahus1** [comment]
Hi @source-knights - I gave this issue some thoughts and I suppose I can explain the behavior you see:

* when adding {docdir} to the image, and generating a HTML file using the Asciidoctor command line, the HTML source code contains a `src="c:/..."` attribute.
* when opening the file in a web browser, the file with have a URI starting with "file:///". This will be pre-pended to the image src attribute, and the image will show up in the browser
* the preview is embedded, therefore it will not prepend the "file:///", thefore the image will not show. 

I can't recommend using `{docdir}` as the prefix, at least not in cases where one publishes the HTML files later on, as it will store the absolute path in the HTML. I assume this will make it impossible to publish the HTML on a web server.

The solutions I've seen to make images show up in the build involve setting the `imagesdir` attribute. The one thing to know about the `imagesdir` attribute: 
1. it is a relative path to the `{docdir}` unless it is a URI

I've pushed two examples on GitHub that show how to use the `imagesdir` attribute: https://github.com/ahus1/asciidoctor-deepdive/tree/master/images

They also show the usage of the *.asciidoctorconfig* file, and how you can use it to set attributes for the preview of documents. 

Please note: One of the examples uses a file URI for imagesdir in the *.asciidoctorconfig* file. This is currently not well supported in version 0.35.75 or earlier. I'll update this issue once a pre-release with better support is available.

If my answer didn't match your problem, please provide a small example project on GitHub.

**Comment by source-knights** [comment]
Ah, I see now that image::file:{docdir}/images/rocketchat_installation_a.PNG[] works when using the "file:" prefix. Thx

**Comment by ahus1** [comment]
Release 0.30.77 is available with improved file URL support. As this now seems to work for @source-knights, I'm closing this issue. Please comment if there is still an issue, and I'll re-open it.

BTW: hard-coding and repeating "file:" as part of an image macro in the AsciiDoc will make your source hard to read. Also a rendered version will not work when published to a web site as browsers will not be able to resolve "file:" URLs. I recommend: 

* setting imagesdir in a central location
* move the setting to ".asciidoctorconfig" so that it works only for previewing in the IDE
