### ISSUE TITLE
Plugin action registration throws exception on startup when used in MPS

### ISSUE THREAD

**Issue by uiterlix** [asciidoctor/asciidoctor-intellij-plugin#502]
I'm using the AsciiDoctor plugin in Jetbrains MPS instead of IntelliJ. This works really well except for an annoying exception on startup. It tries to register an action group to the 'RefactoringMenu'. This menu is not present in MPS therefore the action is automatically registered with the 'Other' group, which works fine but unfortunately leaves an exception in the "IDE Fatal Errors" view.

Plugin version: 0.30.34
IDE Name and Version: Jetbrains MPS 2019.3.4

**Comment by ahus1** [comment]
I'm happy to hear the plugin works with MPS. Thank for reporting this issue to make this plugin for you and other MPS users. 

Unfortunately I'm travelling and will not be able to setup a MPS test environment due to bandwith limitations for the upcoming weeks. 

As a workaround you could download the plugin's ZIP file and change the included plugin.xml to no longer reference the RefactoringMenu. I know this is far from ideal, and needs to be repeated for every plugin's version, but might enable you to get rid of the annoying exception.

**Comment by uiterlix** [comment]
Thanks, I will do that for now.

Op do 28 mei 2020 om 22:49 schreef Alexander Schwartz <
notifications@github.com>:

**Comment by ahus1** [comment]
The AsciiDoc plugin seems to be not the only plugin that's suffering here: https://youtrack.jetbrains.com/issue/MPS-31202

Would it be ok for you to release a fix for MPS 2020.1, or would you like to see a fix for MPS 2019.3 as well?

**Comment by uiterlix** [comment]
I did create a fork for the time being, see here:
https://github.com/uiterlix/asciidoctor-mps-plugin/tree/0.30.77-mps
Currently we're working with MPS 2019.3 but we're quickly adopting each new
version.


Op di 9 jun. 2020 om 12:19 schreef Alexander Schwartz <
notifications@github.com>:

**Comment by ahus1** [comment]
I've created a minimal add-on plugin called "asciidoctor-intellij-plugin-mps.jar"

Follow the steps outlined here: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/faq/troubleshooting-mps.html and install it together with the asciidoc plugin. 

The result should look like this: 

![image](https://user-images.githubusercontent.com/3957921/84171205-dbe26200-aa7a-11ea-8a51-94ec695cff8c.png)

I tried to auto-detect a the missing menu, but no luck. 

Trying the plugin on MPS I found also this exception https://youtrack.jetbrains.com/issue/MPS-30801 - unfortunately I don't have a workaround here. 

Also the toolbar/context menu are very "empty" on MPS as MPS doesn't forward the PSI file type. 

Please let me know if works "good enough" for you this issue could be closed.

**Comment by ahus1** [comment]
Sorry forgot: this add-on should work with any version of MPS/AsciiDoc plugin.

**Comment by ahus1** [comment]
@uiterlix - did you try this MPS add-on? Did it work for you?

**Comment by uiterlix** [comment]
Hi, I just tried the add-on, but unfortunately no luck. It still gives me
the menu error.

Op za 25 jul. 2020 om 20:56 schreef Alexander Schwartz <
notifications@github.com>:

**Comment by ahus1** [comment]
The Exception with "ActionGroupStub" doesn't appear on MPS 2020.2.2 any more, even without the workaround "AsciiDoc MPS add-on". 

The error "Wrong dependency type: class com.intellij.openapi.util.Key" still exists, and I can't provide a workaround. Please vote for it here: https://youtrack.jetbrains.com/issue/MPS-30801

I've updated the docs and watch the issue on JetBrains' YouTrack. Therefore I close the issue. If someone has ideas how to improve the situation, please comment here and I'll reopen the issue.

**Comment by ahus1** [comment]
Update: the issue `Wrong dependency type: class com.intellij.openapi.util.Key` has been fixed in MPS 2020.3 (currently available as EAP version)
