### ISSUE TITLE
'File doesn't resolve' in editor for image, but image is shown in preview

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor-intellij-plugin#506]
I just updated to version 0.30.78 and now I see that image reference show a red swiggly line in the editor with a 'File doesn't resolve' tooltip, but they are displayed just fine in the preview pane.

I am using a `imagesdir` attribute set in the `.asciidoctorconfig` file:

```
:imagesdir: ../images
```

My adoc files are in a `_chapters` directory.

This is the folder structure:

```
|-- src
|   `-- main
|       `-- asciidoc
|           |-- _chapters
|           |-- images
|           |-- theme
|           |-- index.adoc
|           `-- .asciidoctorconfig
```

AsciiDoc Plugin Version: 

> 0.30.78

IDE Name and Version:

> IntelliJ IDEA 2020.1.2 (Ultimate Edition)
> Build #IU-201.7846.76, built on June 1, 2020

**Comment by ahus1** [comment]
@wimdeblauwe - could you please provide a minimal test example on a GitHub repository? 

I have a similar setup [here](https://github.com/ahus1/asciidoctor-deepdive/tree/master/images/imagesdir_config_with_relative_path) and wasn't able to reproduce the issue.

**Comment by wimdeblauwe** [comment]
I also can't reproduce it anymore. Maybe the IntelliJ cache had an issue or something. Sorry to disturb you about this.

**Comment by ahus1** [comment]
I've given it some thought and then remembered one caching that could case this. When renaming or moving an AsciiDoc file an already open editor didn't take into account the new folder name/file name. 

This will be fixed in the upcoming 0.31.4 release.

**Comment by wimdeblauwe** [comment]
Aha :-) Maybe it was that, maybe not, but another bug fixed is always a good thing :)

**Comment by boly38** [comment]
NB: to set a canonical directory instead of relative one, you could rely on `asciidoctorconfigdir` ([src](https://github.com/asciidoctor/asciidoctor-intellij-plugin/pull/292#issuecomment-508695964))
