### ISSUE TITLE
Asciidoctor-pdf with kroki extension generates error for nomnoml diagram type

### ISSUE THREAD

**Issue by bobroro** [asciidoctor/asciidoctor-intellij-plugin#509]
@Mogztter (Guillaume Grossetie) suggested I open an issue here.

I'm using the extension found here: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/src/main/resources/kroki-extension.rb with kroki server to generate a nomnoml diagram.

Details:
- Asciidoctor-pdf (1.5.3), with this docker: https://github.com/madduci/docker-asciidoctor-pdf#docker-asciidoctor-pdf 
- Kroki docker (0.5.0) https://docs.kroki.io/kroki/setup/install/#_using_docker

Asciidoc error:
```
asciidoctor: WARNING: could not embed image: /tmp/image-20200611-1-16whoip; image file is an unrecognised format
```

Asciidoc producing the error:
```
[nomnoml,align="center"]
....
[Pirate|eyeCount: Int|raid();pillage()|
  [beard]--[parrot]
  [beard]-:>[foul mouth]
]

[<abstract>Marauder]<:--[Pirate]
[Pirate]- 0..7[mischief]
[jollyness]->[Pirate]
[jollyness]->[rum]
[jollyness]->[singing]
[Pirate]-> *[rum|tastiness: Int|swig()]
[Pirate]->[singing]
[singing]<->[rum]
```

**Comment by Mogztter** [comment]
The format attribute should be passed on the image block: https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/367b4b4ff5e7e111e7218fee4c87338e54268973/src/main/resources/kroki-extension.rb#L62-L67

You can take a look at what the JavaScript extension: https://github.com/Mogztter/asciidoctor-kroki/blob/51a3c2e9d66b6886093aa1c9a43d7b03683a6c2e/src/asciidoctor-kroki.js#L63-L67

So basically, we need to add `'format' => format`:

```rb
      block_attrs = {
          'role' => role ? "#{role} kroki" : 'kroki',
          'target' => image_url,
          'alt' => target || 'diagram',
          'title' => title,
          'format' => format
      }
```

**Comment by Mogztter** [comment]
@bobroro Can you please try to update the file with this change and run the command again?

**Comment by bobroro** [comment]
@Mogztter Yes, that did it!
While we are at it, we should also pass the float + width + height +link attributes as well.

**Comment by Mogztter** [comment]
Sorry about the noise @ahus1 but the code is currently only available in this repository.

If I publish a gem at https://rubygems.org would you be able to consume it? If that's the case, I can move the code out of this repository.

**Comment by Mogztter** [comment]
> Yes, that did it!
While we are at it, we should also pass the float + width + height +link attributes as well.

Awesome.
Yes that would be great, please feel free to open a pull request, I cannot work on it right now but I will gladly review your contribution.

**Comment by ahus1** [comment]
Hi @bobroro, hi @Mogztter - no worries; your're both welcome to use this repo to discuss the related changes. Please let me know how I can help.

**Comment by Mogztter** [comment]
@ahus1 This question was for you: "If I publish a gem at rubygems.org would you be able to consume it? If that's the case, I can move the code out of this repository.". 

I guess we could use https://github.com/jruby-gradle/jruby-gradle-plugin to fetch the gem from https://rubygems.org/ but then I don't really if it would be practical/easy to load the Ruby code from Java? 

https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/0cee09b81539784a88d34a0ce3473011c945be73/src/main/java/org/asciidoc/intellij/AsciiDoc.java#L319-L323

Maybe [`asciidoctor.rubyExtensionRegistry().requireLibrary()`](https://www.javadoc.io/static/org.asciidoctor/asciidoctorj/2.1.0/org/asciidoctor/extension/RubyExtensionRegistry.html#requireLibrary-java.lang.String-) will do everything for us?

**Comment by ahus1** [comment]
@Mogztter - sorry, I didn't realize that this question was for me.

Go ahead and publish it as a gem. We'll will figure out how to include it. 

If everything else fails I can still copy the source over to the plugin.

**Comment by ahus1** [comment]
@Mogztter - I've assigned you as a reviewer to the PR updating the ruby code.

Once you publish the code as a gem (either as part of this issue, or as a new issue), I assume you'll move over the unit tests for the code. I'd like to keep one of the tests as an integration test in this repository to see of the including of the gem is working as expected.

**Comment by ahus1** [comment]
There hasn't been activity on this ticket for more than a week. There is nothing to do in this repo until a gem is available. I'm closing this issue for now. Feel free to CC: me in any gem-related issue in this or any other repo.

**Comment by Mogztter** [comment]
For reference, here's the pull request: https://github.com/Mogztter/asciidoctor-kroki/pull/96
