### ISSUE TITLE
Anchor appears as enclose adminition in structure tree panel (example inside)

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-intellij-plugin#511]
**First describe the behavior you see in the IDE or plugin (either a problem or a bug).**
If you look at the `logHandler` explanation of the [example](https://gist.github.com/abelsromero/230ee100da0e074211aff12b3fd78b82), we have the following estructure:

```
enumerated element with an anchor
    LIST nodes
    NOTE block
    Text paragraph
        SUBLIST nodes
        SOURCE block
```

However, this is how they are shown in the tree panel.

![image](https://user-images.githubusercontent.com/5781153/84823718-17eb6900-b01f-11ea-82cd-dc98633899d3.png)

The first `[NOTE]` is in fact the anchor, and if change the contained NOTE admonition to for example WARNING, both change.

![image](https://user-images.githubusercontent.com/5781153/84823874-5719ba00-b01f-11ea-96f5-7feb62d25518.png)

**Then describe the behavior you expect or want to see in the IDE or plugin.**
I don't mind the anchor, but for sure, at least the admonition and code section should not be indented, and the anchor name should not replicate the admonitions.

**Please provide a minimal Asciidoctor example.**
Here is a copy of the document where I found the issue: https://gist.github.com/abelsromero/230ee100da0e074211aff12b3fd78b82

**AsciiDoc Plugin Version:** 0.30.78

**IDE Name and Version:**
IntelliJ IDEA 2020.1.2 (Community Edition)
Build #IC-201.7846.76, built on June 1, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.6.16-1-manjaro
GC: ParNew, ConcurrentMarkSweep
Memory: 1937M
Cores: 16
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: com.github.gtache.lsp, Lombook Plugin, com.redhat.devtools.intellij.quarkus, org.jetbrains.kotlin, org.asciidoctor.intellij.asciidoc
Current Desktop: Undefined

**Comment by ahus1** [comment]
Thanks for reporting this. Yes, the anchor should not replicate the admonition. It should derive its own name here, for example "[definition] logHandler". To me this is the primary error here. 

Both the admonition and the source are "below" the logHandler enumeration item, therefore I consider this technically correct. Although it is inconsistent as the plugin show this kind of block nesting and folding only when an enumeration item has an ID. Some users have asked to allow folding of list items. This might be handled in this issue or a different issue.

**Comment by abelsromero** [comment]
> Both the admonition and the source are "below" the logHandler enumeration item, therefore I consider this technically correct.

You are totally right!

> This might be handled in this issue or a different issue.

Whatever you consider the best.

**Comment by ahus1** [comment]
The upcoming release 0.31.7 will fix this and apply a minimal solution here. Instead of the outer "[NOTE]" and inner "[NOTE]" this will show a neutral outer "(Block)" and an inner "[NOTE]". 

This is only the minimal solution for now.

**Comment by ahus1** [comment]
There is now release 0.31.8 (for IntelliJ 2020.2 EAP) and pre-release 0.30.82 (for releases before IntelliJ 2020.1 and before) that should fix this. 

This includes also changes for other tickets, if you see regressions in the editor highlighting and/or re-formatting, please let me know by opening an issue on GitHub. 

![image](https://user-images.githubusercontent.com/3957921/85952866-780dd380-b96c-11ea-8fa3-7dfeb610290e.png)
