### ISSUE TITLE
reference tags back to their includes

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#513]
when an author includes a code fragment like this

```
include::../src/main/java/test.java[tags=main]
```

the plugin already has the feature to jump to the `test.java` by doing a ctrl-click.

Is it possible to implement this also the other way around?

When a dev encounters a tag in her source code like this

```
//tag::main[]
System.out.println("hi!");
//end::main[]
```

she should be able to ctrl-click on the `main` label and get a list of `.adoc` files which include this fragment.

**Comment by ahus1** [comment]
Hi @rdmueller, nice to see you. 

Navigating to the tag works with `ctrl-click` and `ctrl-b`. This is "go to declaration". 

The reverse action is "find usages" using `alt-f7`. 

Please give it a try if this works for you.

**Comment by rdmueller** [comment]
thanx. works fine but I somehow have to memorize the shortcuts 😃
