### ISSUE TITLE
Refactoring admonition block to long form

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#514]
I often start out with an admonition in short form, but then later want to expand to it or make it more prominent in the source, so I refactor it to long form.

It would be nice to have a refactoring to automate this (perhaps in both directions).

![automate-admonition-refactoring](https://user-images.githubusercontent.com/1031625/85940701-de1b3c00-b915-11ea-8f36-8891bb55bcc0.gif)

**Comment by ahus1** [comment]
Hi Dan, thanks for sharing this idea. Great idea!

**Comment by ahus1** [comment]
This will be part of the upcoming 0.31.15 release. It will be an intention and a menu item in the refactoring menu.

![refactor-admonition](https://user-images.githubusercontent.com/3957921/87800757-134ce700-c84f-11ea-9175-cd9b6e45a53b.gif)

**Comment by danhaywood** [comment]
It seems to join "foo" and "bar" into a single line ... is that intentional
?

**Comment by ahus1** [comment]
I looked into it while writing the change and was surprised as well. Sorry I didn't add it to my note. Here is the explanation:

I found that the IDE reformats the refactored code snippet. The same happens for example when you paste content. I remember that this can be disabled in the IDE settings, but I didn't find it. And a user can change the formatting guidelines as well.

The rendered result is the same wether the two words are on the same or different lines. Therefore the re-formatting is correct.

**Comment by danhaywood** [comment]
It's good enough for me, thanks for implementing this.

And I guess the workaround is add a full stop/period at the end of foo.
Then reformat as normal, and rely on one sentence per line.

**Comment by ahus1** [comment]
IMHO there is no need for a workaround here. If a user doesn't want reformatting, or just doesn't want the "one sentence per line" applied in reformatting, there is an option in the settings. 

This would apply for the regular reformatting, and for refactorings. See screenshot below.

![image](https://user-images.githubusercontent.com/3957921/87874599-6a77c680-c9cb-11ea-8674-ed7e9563eae8.png)

**Comment by ahus1** [comment]
This is now available as part of release 0.31.15 available for IntelliJ 2020.2+
