### ISSUE TITLE
Implement FileEditor#getFile() in AsciiDocSplitEditor

### ISSUE THREAD

**Issue by NonNullDinu** [asciidoctor/asciidoctor-intellij-plugin#518]
The split editor, [`AsciiDocSplitEditor`](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/src/main/java/org/asciidoc/intellij/editor/AsciiDocSplitEditor.java), uses [the default implementation of `FileEditor#getFile()`](https://github.com/JetBrains/intellij-community/blob/master/platform/editor-ui-api/src/com/intellij/openapi/fileEditor/FileEditor.java#L138-L139), which makes other plugins think there is no file opened(problem for Discord RP plugins); the [Markdown split editor](https://github.com/JetBrains/intellij-community/blob/master/plugins/markdown/src/org/intellij/plugins/markdown/ui/preview/MarkdownSplitEditor.java) had the same issue, but was fixed by [this PR](https://github.com/JetBrains/intellij-community/pull/1373), so I was hoping you could fix it in the AsciiDoc plugin too.

AsciiDoc Plugin Version: 0.30.78

IDE Name and Version: CLion 2020.1.2
Build #CL-201.7846.88, built on June 3, 2020
Runtime version: 11.0.7+10-b765.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.7.2-arch1-1

**Comment by ahus1** [comment]
Thank you for providing complete and accurate information in this issue and how to fix this. 

For this plugin the methods might be added to [SplitFileEditor](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/src/main/java/org/asciidoc/intellij/ui/SplitFileEditor.java), the parent class of AsciiDocSplitEditor.

I you want, I can walk you through that change if you want to provide a pull request. There is a [contributor's guide for coders](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/contribute-as-a-coder.html). Please let me know if something is missing.

**Comment by NonNullDinu** [comment]
I would love to be able to help, but unfortunately I have problems compiling the plugin locally. Namely it cannot find `netscape.javascript.JSObject` in the classpath, referenced from [here](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/src/main/java/org/asciidoc/intellij/editor/javafx/JavaFxHtmlPanel.java#L48) and I cannot find anything about it in the guide you linked.

**Comment by ahus1** [comment]
I recommend using [JetBrains JDK 8 here](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/coder/setup-environment.html). 

What JDK did you use to compile the plugin? Please run

```
./gradlew --version
``` 

to show the version of the JDK the Gradle wrapper uses.

**Comment by NonNullDinu** [comment]
Oh didn't realize that. It was trying to use my system-wide OpenJDK11. Using JetBrains JDK 8 seems to work. I will submit a PR shortly.

**Comment by ahus1** [comment]
Thank you @NonNullDinu for taking the time to prepare the pull request! As a maintainer this makes me very happy to know that the dev process works for other developers as well. I'll update the docs with the `./gradlew --version` command to help future developers. 

There are now pre-release 0.30.83 supporting IDEA 2019.3.1 to 2020.1 and pre-release 0.31.11 supporting 2020.2+ available.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
