### ISSUE TITLE
Move Asciidoclet support to its own companion-plugin

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#521]
Implementing Asciidoclet support required to override an IntelliJ service that made the main plugin non-dynamic, that is: preventing the initial install of the plugin without requiring a restart. 

Due to this the Asciidoclet support will move to its own plugin.

**Comment by ahus1** [comment]
Create new repository https://github.com/ahus1/asciidoclet-intellij-plugin

Waiting for JetBrains Marketplace team to approve the new plugin: https://plugins.jetbrains.com/plugin/14696-asciidoclet

**Comment by mojavelinux** [comment]
Seems very reasonable to me since the users of the Asciidoclet support are a subset (albeit important one) of the users of this plugin.

**Comment by ahus1** [comment]
Release 0.31.13 is now available. 

To continue using Asciidoclet support on 2020.2+, please install https://plugins.jetbrains.com/plugin/14696-asciidoclet. 

I've updated the docs to describe the installation. Please ask questions or contribute to the docs as you see necessary: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoclet.html
