### ISSUE TITLE
Saving image: filename not taken from textbox

### ISSUE THREAD

**Issue by ellipticview** [asciidoctor/asciidoctor-intellij-plugin#530]
This bug is an annoyance when using an existing image filename as a template. E.g. you are naming your images:

```
my-long-image-name-01.png
my-long-image-name-02.png
my-long-image-name-03.png
```
Scenario:

1. Copy an image (e.g. a screenshot) to the clipboard
1. Press Paste (Ctrl-V)
1. Select .png as the format, and press OK
1. Click on an existing image filename, e.g. `my-long-image-name-03.png` to default the value in the filename textbox
1. Change the name in the filename textbox to `my-long-image-name-04.png`

A popup is displayed: `my-long-image-name-03.png` already exists. Do you want to replace it?

Desired behavior: The image is saved as `my-long-image-name-04.png`

AsciiDoc Plugin Version: 0.31.15

IDE Name and Version: IntelliJ IDEA 2020.2 (Community Edition)

**Comment by ahus1** [comment]
Thanks for reporting this. I was able to reproduce this issue. The desired behavior you describe is how it should behave.

The plugin re-uses an existing class on IntelliJ. For this class a selected file in the tree view will always have preference over a file name in the text field. I'll have a look how I can override this behavior. 

In the meantime, please try the following workaround (step 6 is the new step): 

1. Copy an image (e.g. a screenshot) to the clipboard
2. Press Paste (Ctrl-V)
3. Select .png as the format, and press OK
4. Click on an existing image filename, e.g. my-long-image-name-03.png to default the value in the filename textbox
5. Change the name in the filename textbox to my-long-image-name-04.png
6. **In the tree, select the parent folder of my-long-image-name-03.png, so a directory is selected and not a file**
7. press OK

**Comment by ahus1** [comment]
I tried to put the workaround of step 6 described above in code. This is part of pre-release 0.31.19.

As it selects the parent folder if the current selection is a file, the tree view might scroll once you edit the file name. 

I'd like to hear your feedback before I raise an issue with IntelliJ core to make this the new standard behavior using this or a different implementation.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ellipticview** [comment]
Tested. This code change works fine!

**Comment by ahus1** [comment]
Apparently this is a long-outstanding issue in IDEA core. Please vote for this issue. https://youtrack.jetbrains.com/issue/IDEA-124383

I submitted a pull request to IDEA core. 

I close this issue as there is nothing left to do here. I'll keep watching the upstream issues.
