### ISSUE TITLE
Copy text from preview to clipboard

### ISSUE THREAD

**Issue by cade-rea** [asciidoctor/asciidoctor-intellij-plugin#533]
I cannot copy text from the preview pane. I can copy text from the edit pane.
I would like to be able to copy text from the preview pane.
This behavior occurs with any text, even a simple 1 word example

AsciiDoc Plugin Version: 0.31.15
IDE Name and Version: IntelliJ IDEA 2020.2 (Ultimate Edition) Build #IU-202.6397.94, built on July 27, 2020

**Comment by ahus1** [comment]
Hi @cade-rea, copy-and-paste should generally be possible. 

When I use it on Windows with the JavaFX or the JCEF preview, I can use the mouse to select text in the preview. Ctrl-C copies the selection to the clipboard. I can then copy the text for example into the IDEs editor. 

For me to reproduce the issue, please provide more details on your environment:
* the operating system you use
* the preview mode you use (see screenshot below where to find it in the settings)
* the mouse and/or keyboard interactions you use to copy/paste, and where you try to paste the contents to

I know that when I paste for example into Microsoft Word, it will paste the formatting from the preview into the Word document.

![image](https://user-images.githubusercontent.com/3957921/90184545-919c9a80-ddb5-11ea-833a-97f877649055.png)

**Comment by ahus1** [comment]
Is this still an issue for you? Maybe you could record a short video (animated GIF) to show what is not working: https://www.screentogif.com/

**Comment by cade-rea** [comment]
Thanks for the reply. I tried switching the preview browser, but that did not help.

I'm using IntelliJ 2020.2.1 on MacOS Catalina

In the attached video, I try to copy from the preview pane with CMD-C. I also try right clicking in the preview pane, but no menu comes up. The behavior is the same in split mode or full preview mode.

![asciidoc-copypaste](https://user-images.githubusercontent.com/1037240/91217110-9f6aed80-e6dc-11ea-8323-2f20c4a242ea.gif)

**Comment by ahus1** [comment]
I repeated the steps I see in your video and they work fine on Windows. Unfortunately I don't have access to a MacOS machine to debug the situation. 

The preview of this plugin uses similar technologies like the JetBrains plugin. There is already an open issue for the this in the YouTrack issue tracker; see https://youtrack.jetbrains.com/issue/IDEA-241604. Reading the related issues this is about the JCEF preview. It is "work in progress", but it might help if you would vote for it. If it is rooted in the IntelliJ core, the issue on YouTrack will most likely fix it for the AsciiDoc plugin as well.

I leave the issue open, maybe someone with debugging skills and a MacOS machine can help here.

**Comment by simonnagl** [comment]
I can confirm the behaviour on MacOS. I also can not copy text from the preview pane.

**Comment by ahus1** [comment]
Following the upstream ticket, this will be fixed in 2020.3 the latest. Let's keep fingers crossed it will end up in a patch release for 2020.2.

**Comment by ahus1** [comment]
For 2020.3 the early access version (and now also the beta version) is available. Can anyone please confirm that this is working with 2020.3? Thanks!

**Comment by pOH7** [comment]
Yes, it fixed in 2020.3 EAP (203.5981.41 build)

**Comment by ahus1** [comment]
Added to the plugin's docs. Also added a workaround (in addition to switching to JavaFX preview): 
> As a workaround, open the preview in the browser by clicking on your favorite browser symbol when hovering in the upper right corner of the editor and copy the contents from the browser window.
https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/preview/jcef-preview.html

**Comment by abelsromero** [comment]
I was still trying to resist with 2002.2 after latest changes, but I guess I have no option now. With 2020.3 cmd+C works 👍
