### ISSUE TITLE
mermaid problems

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#534]
Yesterday, I had to work with mermaid for the first time.
I noticed error messages coming from the plugin saying, that no mermaid executable is installed.

```
Failed to generate image: Could not find the 'mermaid' executable in PATH; 
add it to the PATH or specify its location using the 'mermaid' document attribute
```

So I searched for a way to install it and found out that I need to install npm first.

    npm install -g mermaid.cli

After I installed it, the plugin was broken in such a way that the preview pane only displays "initializing..." and never changes to the preview.

AsciiDoc Example for rendering mermaid:

```asciidoc
a test

[mermaid]
----
graph TD
A[Christmas] -->|Get money| B(Go shopping)
B --> C{Let me think}
C -->|One| D[Laptop]
C -->|Two| E[iPhone]
C -->|Three| F[Car]
----
```

AsciiDoc Plugin Version: `0.30.86`

IDE Name and Version: 

```
IntelliJ IDEA 2020.1.4 (Ultimate Edition)
Build #IU-201.8743.12, built on July 21, 2020
Runtime version: 11.0.7+10-b765.65 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
```

*Update:* after quite a while the diagram was rendered. I tried to modify it but It didn't re-render. Instead, I got the following error message in the Event Log:

```
Error during rendering scratch_13.adoc
	uri:classloader:/gems/asciidoctor-diagram-2.0.2/lib/asciidoctor-diagram/util/cli_generator.rb:50: warning: Tempfile#unlink or delete called on open file; ignoring
```

**Comment by ahus1** [comment]
I gave mermaid a try. I found that after installing mermaid (like you did), the IDE preview behaved strangely:
* mermaid CLI starts node, that then starts an (old) version of chromium to render the preview
* an invalid diagram (while typing contents) seemed to stall the mermaid rendering
* I was able to unblock the preview by killing the node process
* even when rendering valid diagrams the preview is quite slow

The preview might be more interactive if the mermaid would use just JavaScript in the preview (like MathJax). This way it would be interruptable when a timeout occurs, and wouldn't need to start so many processes in the background. 

Someone would need to give it a try to see if it is possible.

I'd like to see some votes/comments on this to find out if there is demand for this.

**Comment by ari** [comment]
I'm trying to make this work as well, but I can't get past the 

    Failed to generate image: Could not find the 'mermaid' executable in PATH; 
    add it to the PATH or specify its location using the 'mermaid' document attribute

problem. What PATH is being used here? I'm using gradle with asciidoctorj. Is there some way to have this plugin pick up dependencies from there?

**Comment by ahus1** [comment]
@rdmueller - there seem to be some updates to handle incorrect mermaid diagrams in https://github.com/asciidoctor/asciidoctor-diagram/issues/257 and https://github.com/asciidoctor/asciidoctor-diagram/issues/275 - both are part of asciidoctor-diagram 2.0.3. 

I'm currently waiting for the new release to propagate to asciidoctor**j**-diagram https://github.com/asciidoctor/asciidoctorj-diagram/pull/5

**Comment by ahus1** [comment]
@ari: it uses the PATH environment of the IDE when rendering the preview.

You can set a full path to the executable using an attribute (either in the plugin's settings or in the document) [as described in the FAQ](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/faq/could-not-find-dot-executable.html).

```
:mermaid: ./node_modules/.bin/mmdc
:phantomjs_2: ./node_modules/.bin/phantomjs


[mermaid]
----
classDiagram      
      class Animal {
          +int age
    }
      
----
````

Reading the notes in https://github.com/asciidoctor/asciidoctor-diagram/issues/275 this attributes will change in the upcoming asciidoctorj-diagram 2.0.3

**Comment by ari** [comment]
I'm not having much success.

```
:mermaid: ../../node_modules/.bin/mmdc
:mmdc: ../../node_modules/.bin/mmdc
:phantomjs_2: ../../node_modules/phantomjs-bin/bin/darwin/phantomjs
```

and similar options in the plugin settings (but with paths like ./node_modules/.bin/mmdc since the relative path is different). On the other hand running the gradle plugin works fine. It is just the preview I can't get to work right. In the gradle plugin I can pass absolute paths like:

```
'phantomjs_2': "${rootDir}/node_modules/phantomjs-bin/bin/darwin/phantomjs",
'mermaid': "${rootDir}/node_modules/.bin/mmdc",
'mmdc': "${rootDir}/node_modules/.bin/mmdc"
```

But even absolute paths in the ascidoc plugin aren't helping. And when I manage to get the binary to be found, then I get errors like:

```
Failed to generate image: Cannot run program
"../../node_modules/.bin/mmdc": error=2, No such file or directory
```

For reference I've used gradle configuration like:

```
plugins {
 id "com.moowork.node" version "1.3.1"
}
asciidoctor.dependsOn npm_install
```

with a package.json file

```
{
  "name": "xxx",
  "version": "1.0.0",
  "dependencies": {
    "@mermaid-js/mermaid-cli": "*",
    "phantomjs-bin": "*"
  }
}
```

**Comment by ari** [comment]
Never mind. I've moved over to PlantUML and although there was more work to set up nice styling, it has a lot more flexibility and the integration is easier.

**Comment by OliverO2** [comment]
This worked for me:
* IntelliJ IDEA 2020.2.2
* Asciidoc plugin version 0.31.30 with asciidoctor-diagram 2.0.3 (installed via plugin settings)
* node 12.18.4 on Ubuntu 20.04 (installed via `sudo snap install node --classic`)
* mermaid-cli version 8.8.0 installed via `npm install @mermaid-js/mermaid-cli`

Document rendered correctly:
```asciidoc
:mmdc: {user-home}/node_modules/.bin/mmdc

== Diagram

[mermaid]
....
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail!
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
....
```

If `:mmdc:` is not set properly, `asciidoctor-diagram` still proposes to set the obsolete `mermaid` document attribute, which is misleading:
```
Failed to generate image: Could not find the 'mermaid' executable in PATH; add it to the PATH or specify its location using the 'mermaid' document attribute
```

**Comment by ahus1** [comment]
A new version 2.0.5 asciidoctor-diagram is available. Support of Mermaid seems have improved. This includes the case where mermaid diagrams contain errors (it no longer blocks the rendering). 

Version 0.31.34 of the plugin is now available as a pre-release. The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

The setup I had: 

* AsciiDoc plugin 0.31.34
* minimal `package.json` to install @mermaid-js/mermaid-cli in version 8.8.1 (that being the "new" CLI version of Mermaid)
* setting attribute `mmdc` to the path of the CLI index.bundle.js (as this is passed to node directly - to my surprise)
* node 12.14.0 in the path 
* running Windows 10

Examples: 

mermaid.adoc:
```
:mmdc: {docdir}/node_modules/@mermaid-js/mermaid-cli/index.bundle.js

[mermaid]
....
sequenceDiagram
    participant Alice
    participant Bob
    Alice->>John: Hello John, how are you?
    loop Healthcheck
        John->>John: Fight against hypochondria
    end
    Note right of John: Rational thoughts <br/>prevail!
    John-->>Alice: Great!
    John->>Bob: How about you?
    Bob-->>John: Jolly good!
....
``` 

package.json:
```
{
  "dependencies": {
    "@mermaid-js/mermaid-cli": "^8.8.1"
  }
}
```

Output (as expected) - each re-render takes about 2-3 seconds: 

![image](https://user-images.githubusercontent.com/3957921/95120577-1371ca00-074e-11eb-8748-37f6b74f74af.png)

When have an invalid Mermaid diagram I get in the preview:

![image](https://user-images.githubusercontent.com/3957921/95120881-7ebb9c00-074e-11eb-909d-fc028acc0015.png)

I therefore consider this solved. I'll trigger the upstream project as setting `mmdc` to a JavaScript file doesn't seem very intuitive for me and is not clear from the docs IMHO
