### ISSUE TITLE
Throughput in sidebar breaks syntax highlighting

### ISSUE THREAD

**Issue by simonnagl** [asciidoctor/asciidoctor-intellij-plugin#535]
After a throughput in a sidebar, syntax is no more hilighted.

```
****
++++
Special content
++++
****

== Heading not hilighted

****
++++
```

Is has a syntax warning: `Convert to modern AsciiDoc heading`
The asciidoc document compiles as expected.

If I put an empty line between `****` and `++++` syntax highlighting works.

I do not expect the snipped above to break syntax highlighting.

AsciiDoc Plugin Version: 0.30.85

IDE Name and Version:  
IntelliJ IDEA 2020.1.1 (Ultimate Edition)
Build #IU-201.7223.91, built on April 30, 2020
Runtime version: 11.0.6+8-b765.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.6

**Comment by ahus1** [comment]
Thanks, I'll fix this in the upcoming 0.31.21 release. Would you need a backport to the previous release branch 0.30.x, as 0.31.x will only work with 2020.2.x?

**Comment by simonnagl** [comment]
Thank you for your quick feedback. I can update to 2020.2.x. I do not need a backport.

**Comment by ahus1** [comment]
Pre-release 0.31.21 is now available. Please give it a try. As I was able to reproduce the issue and the fix locally, I close this ticket. Please comment if the issue persists and I'll re-open the ticket.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by simonnagl** [comment]
I just tested the release and can give you positive feedback. Thank you for this amazing support in a private project!

Just one thing: I could not use the AsciiDoc EAP repository. Intellij told me it can not find the link. I did not invest any time in finding the error. Maybe it was me.

Installing the release from disk an GitHub releases worked.
