### ISSUE TITLE
Nested table overflows into cell beneath it.

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-intellij-plugin#537]
The example below is rendered incorrectly in the Preview and HTML but rendered correctly in PDF.

```
[cols="1,2a"]
|===
| Col 1 | Col 2

| Cell 1.1
| Cell 1.2

| Cell 2.1
| Cell 2.2

[cols="2,1"]
!===
! Col1 ! Col2

! C11
! C12

!===

| Cell 3.1
| Cell 3.2

|===
```

Preview and HTML.

![image](https://user-images.githubusercontent.com/13682850/90787444-04050180-e305-11ea-8ce2-ae70c5ced317.png)

PDF.

![image](https://user-images.githubusercontent.com/13682850/90787642-3b73ae00-e305-11ea-8f9a-950adbcf4834.png)

AsciiDoc Plugin Version: 0.31.15

IDE Name and Version: 2020..2.1 RC

**Comment by mojavelinux** [comment]
This was a regression in Asciidoctor 2.0.10, has been fixed in master, and will be corrected in the upcoming 2.0.11 release. See https://github.com/asciidoctor/asciidoctor/issues/3370.

**Comment by ahus1** [comment]
I remember being tricked by this bug before. I'll add a backport in the upcoming 0.31.21 release. This will work in all previews, exception when you create a HTML export (that would use the original CSS).

**Comment by ahus1** [comment]
Pre-release 0.31.21 is now available. Please give it a try. I tested it successfully for the JavaFX, JCEF and HTML-in-browser preview. Please comment if the issue persists and I'll re-open the ticket.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by wfouche** [comment]
Thank you! The preview is now correct.

**Comment by mojavelinux** [comment]
Thanks for confirming @wfouche. That gives me confidence about the change in core too.
