### ISSUE TITLE
Allow soft-wrap to be enabled by default

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciidoctor-intellij-plugin#540]
I prefer using the 'one sentence per line' writing style when authoring asciidoc files. Soft-wrap is rather essential for that. At the moment, every time I open a new file I have to reenable soft-wrap. It would be nice if this could be set to be on by default in the preferences.

**Comment by ahus1** [comment]
This is not a plugin settings, but an IDE setting. Please see [Recommended Settings](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/recommended-settings.html) for more information. 

I haven't figured out yet how to guide users to find this intuitively. One thing I implemented: if a user enables soft wrap five times within an IDE session but not disables it again, this triggers an editor notification guiding the user to this setting. Maybe I should reduce this to two net soft wraps.

**Comment by pepijnve** [comment]
Thanks for the pointer. I indeed hadn't realised there was a connection between the two.

**Comment by ahus1** [comment]
Alright, closing it. Please ping me if you come across a more intuitive way.
