### ISSUE TITLE
JCEF Preview not rendered on Windows 10

### ISSUE THREAD

**Issue by atgomes** [asciidoctor/asciidoctor-intellij-plugin#543]
The preview is not rendered in real time even for simple asciidoc files. This issue started a few weeks ago, but I can't be sure if it started right from the 2020.1 release of Intellij or sometime later.

The PDF or HTML export and other functions work just fine, but the preview is never rendered. On the IDE logs (idea.log) I find this line every time I open an adoc file:

```
2020-09-01 17:08:41,437 [5973502]   WARN - tor.jcef.AsciiDocJCEFHtmlPanel - rendering didn't complete in time, might be slow or broken 
```

The minimal example is just a new project with an adoc file in it:

![image](https://user-images.githubusercontent.com/7239375/91869568-55eb4700-ec76-11ea-90d3-cab8def5cae4.png)

I have tried multiple things like uninstalling the plugin and cleaning the cache but the problem even persisted after upgrading Intellij from 2020.1 to 2020.2 and currently in 2020.2.1.

AsciiDoc Plugin Version: 0.31.20

IDE Name and Version: 
IntelliJ IDEA 2020.2.1 (Ultimate Edition)
Build #IU-202.6948.69, built on August 24, 2020
Licensed to ***************
Subscription is active until ****************
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1949M
Cores: 8
Registry: compiler.automake.allow.when.app.running=true
Non-Bundled Plugins: JMeter plugin, Lombook Plugin, net.ashald.envfile, org.sonarlint.idea, MavenRunHelper, ru.adelf.idea.dotenv, org.asciidoctor.intellij.asciidoc

**Comment by ahus1** [comment]
I'm sorry to hear the plugin is causing you troubles. Looking at the logs you're probably using the JCEF preview.  I'm using Windows 10 myself, and haven't seen a blank preview with JCEF yet. Something must be different in your setup. The runtime stated in the IDE settings is also the shipped runtime, so nothing suspicious there. 

The preview area is completely blank. Strange.

As a short-term workaround you might want to install the JavaFX plugin and then switch to the JavaFX preview. From [the docs](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/installation.html):

> Up to and including IntelliJ IDEA 2020.1 the pre-bundled OpenJDK includes JavaFX, wich is required for a rich preview. Starting with IDEA 2020.2 the JavaFX preview is only available after installing the plugin [“JavaFX for plugins”](https://plugins.jetbrains.com/plugin/14250-javafx-runtime-for-plugins).

But as JavaFX is considered legacy, and JCEF is the new thing, I like to figure out what's not working for JCEF. 

Could you please provide a full log file? You can send it to the email address you see in my GitHub profile.

Do you experience the same problem with Markdown files (Markdown uses JCEF preview as well). 

I'm looking forward to your reply!

**Comment by atgomes** [comment]
Thanks a lot for your feedback. 

Indeed now that you mention it, Markdown preview also started behaving erratically recently, it still displays, but it's often half "off-screen" and I need to manually adjust the preview frame for it to trigger some kind of redrawing in the correct position.

I sent you by email the complete log file from the moment I open Intellij up until I write something on an adoc file.

Also, the workaround using JavaFX works and will have to serve for now, thanks for the tip.

**Comment by ahus1** [comment]
Thank you for sending the log file. I searched it for clues, but haven't found a clue yet. I tested it locally with Windows 10, also a second screen, but wasn't able to reproduce the issue you experienced.

When I run my IDE on windows, I see some JCEF helper processes. Do you see them as well (or do you see error messages related to them)?

![image](https://user-images.githubusercontent.com/3957921/93002821-f6c0e880-f539-11ea-8fe3-ef87ae59fcfd.png)

I noticed that you have a non-ASCII home directory: "C:\Users\AndréGomes". Now and then I've seen errors with JRuby ([see here](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/faq/errno-enoent.html)), but this doesn't affect your preview. And you reported your preview works find with JavaFX. 

As you experienced problems with the Markdown plugin, it might suffer the from the same cause. May I suggest you open an issue with JetBrains describing your problems with the Markdown plugin? If there's a bug within JCEF, and if they find and fix it for Markdown, they will fix it for the AsciiDoc plugin as well. Please post the link to the issue in this ticket so people can upvote it.

**Comment by atgomes** [comment]
You are definitely onto something there with the non-ASCII home directory. I got this error from "Show Dev Tools" after enabling it by following the steps at [Reporting JCEF problems](https://intellij-support.jetbrains.com/hc/en-us/articles/360016644459-Reporting-JCEF-problems):

`chromewebdata/:1 Not allowed to load local resource: file:///jbcefbrowser/625543517#url=jar:file:/C:/Users/Andr%C3%A9Gomes/AppData/Roaming/JetBrains/IntelliJIdea2020.2/plugins/asciidoctor-intellij-plugin/lib/asciidoctor-intellij-plugin.jar!/org/asciidoc/intellij/editor/jcef/AsciiDocJCEFHtmlPanel.class@1118741798
`

I have faced issues related to home dir with several other tools including Maven, and as such I created an alternative C:\Users\me (changing the home directory name is not an option for me) for that effect. With that in mind I tried the following:

1. changed plugin directory by adding `idea.plugins.path=C:/Users/me/.intellij/plugins` to idea.properties
2. uninstalled Asciidoctor plugin
3. restarted Intellij and installed plugin again
4. success! the JCEF preview works great again

Hope this helps someone else. 

Thanks a lot for your help figuring this thing out and sorry that I bothered you since it is not really related to any problem on this plugin.

**Comment by ahus1** [comment]
This is great investigative work you did, @atgomes! Especially the "Show Dev Tools" option does straight to the plugin's docs. This is quite useful to inspect the preview. 

I tried it locally by specifying a `idea.plugins.path` with non-ASCII-characters, and was then able to reproduce the issue locally.

The JCEF preview seems to be allergic to non-UTF8 characters; therefore I started to encode them. Then the preview started to work again.

There is now pre-release 0.31.33 - please give it a try. This should no longer require settings an `idea.plugins.path`. 

I'm looking forward to your feedback. Once this works, I'll recommend this change upstream as other plugins probably have the same issue.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by atgomes** [comment]
I confirm that, with 0.31.33, JCEF preview works with my non-ASCII home directory and setting a custom path is no longer necessary. Great work!

**Comment by ahus1** [comment]
Thank you for testing this again. I promoted 0.31.33 to a regular release and it is now rolling out to all users. 

I opened an upstream issue https://youtrack.jetbrains.com/issue/IDEA-252128 as this affects other plugins as well; let's see how this is handled upstream.
