### ISSUE TITLE
include file not found in nested include is highlighted in first line of the master document

### ISSUE THREAD

**Issue by mariushilleke** [asciidoctor/asciidoctor-intellij-plugin#550]
Experiencing an IDE-error cf. picture, in the manual documentation itself, saying

```
include file not found: doctoolchain/build/docs/contributors/manual/04_further_reading.adoc 
(doctoolchain/src/docs/manual/feedback.adoc, line 6)
(uri:classloader:/gems/asciidoctor-2.0.10/lib/asciidoctor/reader.rb:preprocess_include_directive)
```

![image](https://user-images.githubusercontent.com/29111781/93069735-4e686c80-f67e-11ea-8828-79ed2cd2b83c.png)

AsciiDoc Plugin Version: 0.31.27

IDE Name and Version: IntelliJ 2020.2.1

**Comment by ahus1** [comment]
When rendering the preview, a nested include is mission. 

The plugin currently maps all errors that occur outside of the current document to the first line of the document. 

What would be the behavior you expect?

**Comment by ahus1** [comment]
The next upcoming release highlight errors in the parent files on the correct line, event for nested includes.
