### ISSUE TITLE
Back port AsciidoctorJ extensions feature to IntelliJ 2020.1.1

### ISSUE THREAD

**Issue by JMikeP** [asciidoctor/asciidoctor-intellij-plugin#551]
There is a critical feature I am looking for that was released in 0.31.20 with support AsciidoctorJ extensions in the preview.  I work at a large corporation that is slow to increase version of IntelliJ. Can you please make this feature available for 2020.1.1?

The current version i am using (0.30.85) does not support this feature.

**Comment by JMikeP** [comment]
Looks like my description didn't save when i submitted the issue.

I need a feature in that was made available in 31.20, support AsciidoctorJ extensions in the preview.  My company is behind in IntelliJ version this feature is critical to me.  Can you make it available for 2020.1.1.

I am currently on 30.85 and it does not have this feature and i don't see it in 30.86.

**Comment by ahus1** [comment]
Good to hear that you like the AsciidoctorJ feature. Please be aware that not all AsciidoctorJ extensions might work as expected. Did you test the extension you want to use with the latest version of IntelliJ and the AsciiDoc plugin?

I usually back-port only bug fixes, not features. Are you (or is someone else in your organisation) willing to provide a pull request with a backport of #532?

**Comment by ahus1** [comment]
Hi @JMikeP - did you have a chance to tackle the first question: 

> Did you test the extension you want to use with the latest version of IntelliJ and the AsciiDoc plugin?

Please let me know if you into issues.

**Comment by JMikeP** [comment]
Hi @ahus1, I think just getting my company to update to the latest version would be the best course.  With everything that corporate process is, I though it might be easier to just back port the update.  Now thinking about this from another perspective, it would be a waste of your time.

Keep up the good work, I really enjoy using this plugin as a way to document my architecture designs!

**Comment by ahus1** [comment]
Thank you for the update. Please open a new issue when you run into issues with any AsciidoctorJ plugin.
