### ISSUE TITLE
Asciidoclet: The correct rendering requires additional blank lines

### ISSUE THREAD

**Issue by schittli** [asciidoctor/asciidoctor-intellij-plugin#554]
Hello

**Thanks a lot for your great and very useful work!**

### The behavior you see in the IDE or plugin

If I have this comment:
```
 /**
 * = Introduction
 * This Class:
 * - The username
 * - The password
 */
```

Then, the Asciidoclet rendering hides text which should _never_ happen:

![image](https://user-images.githubusercontent.com/8282673/93869533-3327dd80-fccc-11ea-9487-b484bb4a3c28.png)

If we add additional, cosmetic new lines:

```
 /**
  * = Introduction
  * 
  * This Class:
  *  
  * - The username
  * - The password
  */
```

Then, the Asciidoclet renders the comment right (except that the header is smaller than the normal text):

![image](https://user-images.githubusercontent.com/8282673/93869825-a598bd80-fccc-11ea-82a0-6a9247eb48dd.png)

### The behavior you expect or want to see in the IDE or plugin.

I guess it should **never** happen that any comment text gets hidden. 

In case of any problem (parsing, syntax errors, etc.), then comments must never gets hidden - in this case a fallback would have to exist and the text must be displayed as a normal paragraph.

Otherwise it can easily happen that very annyoing errors occur - just because AsciiDoc has hidden parts of the comment to a developer and and therefore he misunderstood e.g. a concept.

**A tool must never provoke such errors!**
**It's always better to see the complete comment which has a bad layout than to see wrong / incomplete comments.**

AsciiDoc Plugin Version: 0.31.27
Asciidoclet Plugin Version: 0.1.0
IDE Name and Version: IntelliJ IDEA 2020.2.2 Community Edition

Thanks a lot!,
kind regards,
Thomas

**Comment by ahus1** [comment]
Hi @schittli, thanks for reporting this. The behavior you see is the ["header" of an AsciiDoc document](https://asciidoctor.org/docs/user-manual/#author-and-email).

The two lines of text just after a title (the one with the single `=`) are used for revision and author information. They will never show up in the preview. 

The first real content will start after two lines of text OR after a blank line. If you add attributes into the header these don't count as lines. A full example looks like this: 

```
= The Dangerous and Thrilling Documentation Chronicles
Kismet Chameleon <kismet@asciidoctor.org>
v1.0, October 2, 2013: First incarnation
```

I hope this explains the behavior you see. 

Unfortunately the AsciiDoclet snippets can't show syntax highlighting in the editor. If you copy your example to an AsciiDoc file you could at least see some syntax highlighting. I would like to name an automated rule how to detect such a situation, but unfortunately I can't.

**Comment by mojavelinux** [comment]
> The two lines of text just after a title (the one with the single =) are used for revision and author information.

Exactly. The text hasn't been hidden. It has been consumed as the author name. And the author name does not show in the embedded HTML.

You could demote the document title to a discrete heading by adding `[discrete]` above it.

```
[discrete]
= Introduction
This Class:
- The username
- The password
```

In general, though, it's best to always separate a section title from its contents by a blank line. That will make it more clear when you are making a document header vs when you are making a section body.

**Comment by ahus1** [comment]
Closing this issue as there isn't much I can do here today. Please comment and I'll re-open the issue.
