### ISSUE TITLE
Bad Link to Documentation in the "JCEF Preview is Available" Banner

### ISSUE THREAD

**Issue by Javaru** [asciidoctor/asciidoctor-intellij-plugin#555]
### What Happens
1. AsciiDoc presents a banner indicating an advanced JCEF preview is available.
2. When you click on the "Yes, tell me more!" link, it results in a 404

![image](https://user-images.githubusercontent.com/2196944/93922168-940ce100-fcdf-11ea-9eed-8b3ffcca3d8d.png)

### Excepted
The correct link should open.

The link is pointing to:
https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/preview/jcef-preview.html
But the correct link is:
https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/preview/jcef-preview.html

Looks like it is [this line](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/bc493a4e056a6f7d266667832a73a712ddac0a07/src/main/java/org/asciidoc/intellij/editor/jcef/notification/ChangeJdkForJCEFNotificationProvider.java#L53) that needs fixing. If you would like a PR, I can submit one. But it seems to me a PR would be a lot more work for you given the simplicity of the fix.

###  Versions
AsciiDoc Plugin Version: 0.31.28

IDE Name and Version: 
IntelliJ IDEA 2020.2.2 (Ultimate Edition)
Build #IU-202.7319.50, built on September 14, 2020

**Comment by ahus1** [comment]
Thanks, will be fixed in next upcoming version. 

I wonder: what runtime did you use for your IDE? The pre-packaged runtime of 2020.2.2 should support JCEF out of the box.

**Comment by Javaru** [comment]
I'm on an oddball runtime (765.65, specifically 11.0.7+10-b765.65 amd64) at the request of JetBrains while trying to troubleshoot a [GUI popup issue](https://youtrack.jetbrains.com/issue/IDEA-247060) I reported.

**Comment by ahus1** [comment]
Thanks, I was wondering if the notification was valid. It appears it is. As the next release will contain the fix, I'll close this issue then.
