### ISSUE TITLE
Preview: Support for remote CSS

### ISSUE THREAD

**Issue by GauntletPL** [asciidoctor/asciidoctor-intellij-plugin#556]
I'd like to to use `stylesdir` and `stylesheet` attributes to override default styles applied to my document by the JCEF Browser. This, however, only works if CSS files are stored locally.
My company has an internal repo, where all asciidoc related files are stored (e.g. css, common includes etc.) - this allows everyone to start working on the document with almost zero configuration.

Is there a way to specify placement of CSS files like this 

```
:stylesdir: https://internal.asciidoc.repository/asciidoc/css/asciidoc-skins
:stylesheet: adoc-colony.css
```

instead of this

```
:stylesdir: ./
:stylesheet: adoc-colony.css
```

**Comment by mojavelinux** [comment]
Yes, you can. Just assign the URL to the stylesheet attribute and set the linkcss to instruct Asciidoctor to link direct to the stylesheet instead of embedding it.

```
:linkcss:
:stylesheet: https://darshandsoni.com/asciidoctor-skins/css/dark.css
```

The stylesdir is just a way to break the value into parts, so this will also work:

```
:linkcss:
:stylesdir: https://darshandsoni.com/asciidoctor-skins/css
:stylesheet: dark.css
```

I haven't tested whether this works in the plugin, but it works when calling Asciidoctor directly.

**Comment by ahus1** [comment]
@GauntletPL - thanks for reporting this. This is a reasonable scenario that the plugin should support. 

As the plugin uses the "embedded" Asciidoctor converter and later adds a custom header/footer, some feature that affect header/footer might not be supported yet. 

A quick test on my side revealed that `linkcss` is not supported by the plugin, yet.

I'll see after it that the preview supports this in an upcoming release.

**Comment by ahus1** [comment]
I've added support for `linkcss` in the preview in the pre-release version 0.31.31. The example provided by @mojavelinux works now both in the JavaFX and the JCEF preview.

I've also updated the docs: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/stylesheets.html

@GauntletPL - please give it a try. If the docs need improvement, please comment here or provide a pull request.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

![image](https://user-images.githubusercontent.com/3957921/94337968-c3c52d00-ffee-11ea-9ad5-18888c6abb6a.png)

**Comment by mojavelinux** [comment]
That's great news @ahus1!

I'll also look into supporting the remote stylesheet in core when linkcss is not enable..for the future.

**Comment by ahus1** [comment]
Pre-release 0.31.32 supports also the shorter version where `stylesdir` is not set in the document.

**Comment by GauntletPL** [comment]
I can confirm that remote CSS are now working in the preview.
Thank you @ahus1 for immediate fix.

**Comment by ahus1** [comment]
Good to hear that! As usual I'll keep this version for a few more days as a pre-release before I promote it to a regular release. This allows you and other users of this pre-release to report bugs regarding this and other features that are part of the pre-release.

If I should forget to promote it to a regular, please ping me with a short comment in this ticket.
