### ISSUE TITLE
Clicks in Preview with include directives should open file in editor

### ISSUE THREAD

**Issue by Alvis-pixel** [asciidoctor/asciidoctor-intellij-plugin#557]
**The current Preview functionality:**
When the user clicks on text in the preview, the editor moves the cursor to the clicked text. This is accurate at block level, unfortunately not yet on line or character level.

**I would like to propose an addition:**
If we have split documentation into include directives, then the cursor could also jump into the correct file and move the cursor to the clicked text.

AsciiDoc Plugin Version: 0.31.30

IDE Name and Version: IntelliJ 2020.2.2 (Community Edition)

**Comment by ahus1** [comment]
Thank you for this suggestion. I agree this would help the users, and it is IMHO technically possible.

At first a user might be surprised when a new editor opens, but they will soon love this feature.

What is the current behaviour you see? Am I correct to assume that the cursor in the editor is placed at the include statement?

**Comment by Alvis-pixel** [comment]
For me, cursor is not placed at the include statement.

**Comment by ahus1** [comment]
This feature will be part of release 0.32.5. I'll update this ticket once a pre-release is available. 

Thanks again for suggesting this enhancement.

**Comment by ahus1** [comment]
Pre-release 0.32.5 is now available.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
