### ISSUE TITLE
Add a Keymap Reference to the plugin's documentation

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#565]
The plugin's documentation [lists all the features](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features.html), and this is a good start for users. 

To make users more productive, they should have a please to learn about the keyboard short cuts they can use when writing AsciiDoc content. 

Most keyboard shortcuts are common to IntelliJ (like Ctrl+Space or Ctrl+B), but they might still be new to documentation writers. 

There is at least one shortcut : did you know that you can select some text, and then press asterisk (`*`) to make it bold? This works similarly for backticks and underscore (`_`).  

To contribute, add a new page to the plugin's documentation with a table of all keyboard shortcuts relevant for writers of AsciiDoc.

**Comment by ahus1** [comment]
To contribute, you find all documentation in the [sub-folder doc of this repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/tree/master/doc).

The [contributors guide to write documentation](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/docs/edit-documentation-content.html) is available on the plugin's web site.

Please ask your questions here by adding a comment.

**Comment by EEM86** [comment]
@ahus1 hello, I want to clarify, would you like to have a page with a copy of the list of Intellij shortcuts? Just format using the table? Also, markdown features should be written?

**Comment by ahus1** [comment]
@EEM86 - yes, a table would be great. 

All shortcuts relevant to users of the AsciiDoc plugin should be listed. The description should be specific to the AsciiDoc plugin. 
If a shortcut is not relevant for an AsciiDoc plugin user, the shortcut shouldn't be in the list.

You asked: 

> Also, markdown features should be written?

I'm not sure about that question, maybe the following is the answer:

Suggested columns: 

* Description 
* Shortcut



| Description | Shortcut   |
| ------------- | ------------- | 
| Expand Selection | Ctrl + W |
| Toggle bold for selected text | *  |
| ...              | ... |

Here the original keymap reference from JetBrains: https://resources.jetbrains.com/storage/products/intellij-idea/docs/IntelliJIDEA_ReferenceCard.pdf

A grouping would be nice (as in the reference card), but could be added in a separate step.

Maybe you could start with a table with only a few, most important entries. After a review we add more shortcuts later. What do you think?

**Comment by EEM86** [comment]
Thank you, I'll start with the most important entries. Assign me please, I'll try to create PR tomorrow.

**Comment by ahus1** [comment]
Done! I'm looking forward to your pull request.

**Comment by ahus1** [comment]
The new keymap is available here: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/keymap.html

Windows/Linux AND MacOS! 🎉
