### ISSUE TITLE
Highlight "bash" code

### ISSUE THREAD

**Issue by knutwannheden** [asciidoctor/asciidoctor-intellij-plugin#568]
We have quite a few shell script (bash) code examples and declare them as of type `bash` because we use highlight.js to do the highlighting in the rendered HTML. This part works nicely.

Unfortunately the rendered preview done by the Asciidoc plugin in IntelliJ doesn't do any highlighting for these blocks, as it expects `shell script` instead of `bash`. It would be nice if it would also highlight source blocks declared as `bash`.

```asciidoc
[source,bash]
----
echo "foo"
----
```

AsciiDoc Plugin Version: 0.31.33

IDE Name and Version: 
```
IntelliJ IDEA 2020.3 EAP (Ultimate Edition)
Build #IU-203.4203.26, built on September 30, 2020
IntelliJ IDEA EAP User
Expiration date: October 30, 2020
Runtime version: 11.0.8+10-b1098.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 5916M
Cores: 12
Non-Bundled Plugins: EclipseCodeFormatter, org.jetbrains.plugins.spotbugs, org.intellij.plugins.hcl, com.atlassian.bitbucket.references, org.jetbrains.kotlin, org.asciidoctor.intellij.asciidoc
```

**Comment by ahus1** [comment]
Sure - that should be fixable. Do you want to give it a try? 

The change should be applied to [LanguageGuesser.java](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/src/main/java/org/asciidoc/intellij/injection/LanguageGuesser.java)

There is already a special case to map "javascript" to "js". A similar case to match "shell script" to "bash" would be sufficient here. Another `if()` would be good to ensure no-one else explicitly registered `bash` as a language.

The contributor's guide lists some information to [get you started as a coder](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/coder/setup-environment.html).

If you don't pick it up, maybe someone else will pick it; I think it is a good starter issue.

**Comment by knutwannheden** [comment]
It might take a while until I find time to look into this. So if anyone else wants to take care of this, go for it 🚀

**Comment by ahus1** [comment]
Will be part of upcoming 0.31.37 release.

**Comment by ahus1** [comment]
Pre-release 0.31.37 is now available.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
