### ISSUE TITLE
Live Preview

### ISSUE THREAD

**Issue by juhoffma** [asciidoctor/asciidoctor-intellij-plugin#57]
Hi,

maybe a stupid question, but how do i actually activate the `Live Preview`feature? I have found nothing in the README.

Thanks in advance, and again sorry for the stupid question

**Comment by aheusingfeld** [comment]
I open the file I'm working on in two editor windows side by side. In one window I type, the other one updates automatically. I guess that's pretty much it.

We should probably add this to the README though. ;)

**Comment by bodiam** [comment]
Not a stupid question at all, it's a bit hidden. 

You'll have to open a document, then do split pane, and then it will display the live preview. Hope that helps.

**Comment by bodiam** [comment]
Well, better two replies than one :-)

**Comment by juhoffma** [comment]
worked like a charm. For any reason the tabs on the bottom of the editor were missing. Restarting IDEA fixed it. Thanks for the responses.

**Comment by bodiam** [comment]
That's weird. Probably an IntelliJ bug ;-)
