### ISSUE TITLE
JavaFX wiki page points to 404 page

### ISSUE THREAD

**Issue by EnricoGueli-TomTom** [asciidoctor/asciidoctor-intellij-plugin#573]
When opening an AsciiDoc file in IntelliJ, the message "You could enable the advanced JavaFX..." can appear at the top. When clicking "Yes, tell me more!", the web browser opens with https://github.com/asciidoctor/asciidoctor-intellij-plugin/wiki/JavaFX-preview.

The page says that the contents have been moved to https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/preview/javafx-preview.html, but clicking on that link all I get is a 404 error page.

I'd expect instead the "Tell me more" button to point directly to a page with relevant contents.

**Comment by ahus1** [comment]
Hello @EnricoGueli-TomTom, thanks for reporting this broken link. It is not fixed. The correct link is https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/preview/javafx-preview.html

The most recent plugin versions starting with release 0.31.30 will link directly to the new page. 

Release 0.31.x is available for IntelliJ platform releases 2020.2+

Older releases 0.30.x still point to the old page and users need to follow the redirect. As the redirect is now fixed (thanks again for point this out)

Am I correct to assume that you use plugin version 0.30.x or earlier?

**Comment by EnricoGueli-TomTom** [comment]
Thanks for fixing the link! At least the relevant contents are now reachable. Issue is fixed for me. 
Indeed I'm using 0.30.87, in Android Studio 4.1 (Build #AI-201.8743.12.41.6858069)

**Comment by ahus1** [comment]
Thank you for letting me know, so I close this issue.
