### ISSUE TITLE
"create file" action for images

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#575]
There is a "create the missing file" inspection for the `include`-macro:

![image](https://user-images.githubusercontent.com/1856308/97055456-232f4200-1587-11eb-986e-4e06090b773d.png)

but for the image-macro, this seems not to exist.
But it would be quite helpful for the new draw.io plugin to specify a diagram like 

    image::diagram.drawio.svg[]

and have the "create the missing file" inspection for this to create an empty `svg`-file.
A Ctrl-Click will open the corresponding editor and initialize the file.

**Comment by ahus1** [comment]
So far I wasn't sure how automatically creating an image could work. With https://github.com/docToolchain/drawio-intellij-plugin that "black swan" appeared, and it is now clear what should happen from a user's perspective. 

I'm happy to accept hard-coded default files for diagrams.net in a first version. Future releases could trigger a "new file" functionality in drawio (or other plugins) to provide an empty file.

**Comment by ahus1** [comment]
This is part of pre-release 0.31.37.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
