### ISSUE TITLE
Ensure that test methods start with either "test" or "should"

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#583]
The convention for unit test methods is to start with "test" or "should". 

A good way to ensure this would be an ArchUnit test. This framework is already in use within this project, see  ClassNameConventionsTest

See https://www.archunit.org/ for more information.

**Comment by idosal** [comment]
Hey,
what would such a test look like?
All public methods that are in package test should have name beginning with "test" or "should"?

**Comment by ahus1** [comment]
@idosal - with the ArchUnit API it should be possible to write something like "all methods that are annotated with `@Test` should have a name beginning with `test` or `should`". 

The failing test should report test methods for example in ImageServiceTest as violations to the rule.

**Comment by idosal** [comment]
Got it. I'd like to take it if you don't mind.

**Comment by ahus1** [comment]
Find, I'm looking forward to a PR! Don't hesitate to submit a draft PR so we can discuss details.

(adding to that: as this would include changing the test method's names that are currently violating the rule: let's start with a the validation rule right as a draft PR. If the rule works as expected, tackle the violations afterwards. If you are unsure with some of the violations, we can discuss).

**Comment by ahus1** [comment]
I didn't add to the issue why I think it is important: When tests methods starts with the word "should", it helps the developer to describe the behavior they want to see. This will help focusing on the right stuff and structuring the test. There are lots of existing test cases starting with "test", and I want to keep them as-is, so I want to allow "test" and "should". 

"should" is the new "test"!

**Comment by idosal** [comment]
Naturally. Personally, I'm a fan of the [[UnitOfWork_StateUnderTest_ExpectedBehavior]](https://osherove.com/blog/2005/4/3/naming-standards-for-unit-tests.html) naming scheme.
