### ISSUE TITLE
Context menu usability

### ISSUE THREAD

**Issue by jotomo** [asciidoctor/asciidoctor-intellij-plugin#59]
The plugin adds an entry in the context menu. This has some usability problems, IMHO
- The entry is added at the top and thus changes the position of the items at the top, which are the most used. This requires relearning item positions. From my experience, the usual way is to add entries, stemming from an extension, to the bottom of the context menu.
- If no AsciiDoc actions are applicable (e.g. the context menu for a method name) the AsciiDoc group is greyed out. My experience, again, is that items that are not applicable to the context are hidden entirely.

In case you already know this, I'm using this issue to poke you ;-)

**Comment by bodiam** [comment]
Hi Johannes,

Thanks for reporting this. You are right, we knew about this, and we've
tried to solve this in many ways, even with Support from Jetbrains, but we
couldn't find a way to fix this.

If we won't be able to fix it, I'll propose to remove the menu (including
all the functionality in the menu), unless better options are prevented.

Sorry for the troubles this has caused!

Erik
Op 13 jan. 2015 19:16 schreef "Johannes Mockenhaupt" <
notifications@github.com>:

**Comment by jotomo** [comment]
Hm, I just toke a look at the source of the _gitignore_ plugin - which adds itself at the bottom of the context menu: https://github.com/hsz/idea-gitignore/commit/22611036b772f0d244b7a10de980455528424c84. The reference to _NewGroup_ seems strange (not found and thus defaulting to root)?
Looking at the definitions in the AsciiDoc plugin here https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/META-INF/plugin.xml#L102 ... changing those anchors seems to simple, you tried that, right?
Alright, I'll stop, I know where the thought _"let's just take a quick stab at it"_ leads to ;-)

**Comment by jotomo** [comment]
Oh well, I did tinker a bit. Placing the actions below the other edit options (Cut, Copy, Paste) didn't seem to work, but placing them at the end works. While they would be more correct under the edit options, I usually search for those items at the bottom. Code is at https://github.com/jotomo/asciidoctor-intellij-plugin/commit/c369d9aaf73edf86897888d2797577b62ec4180d (Version number incremented only to ensure I'm testing the updated version of the plugin). Would that be usable? 
![editor-context](https://cloud.githubusercontent.com/assets/1732305/5731168/d4228482-9b80-11e4-80c5-111566460cd8.png)
![project-view-context](https://cloud.githubusercontent.com/assets/1732305/5731169/d42bad96-9b80-11e4-9bd8-f26797772f2a.png)

**Comment by wimdeblauwe** [comment]
+1 for this. I also don't like having the menu at the top there. Is it possible to remove the menu item completely instead of greying out if not on an .adoc file?

**Comment by krasa** [comment]
Why just not make a toolbar? :)
![image](https://cloud.githubusercontent.com/assets/1160875/8385755/f4c9a54e-1c4a-11e5-9711-d28d7b4b32db.png)

**Comment by mojavelinux** [comment]
:+1:

**Comment by krasa** [comment]
@bodiam actually it is quite easy to hide the group
```
<group id="AsciiDoc" class="org.asciidoc.intellij.actions.asciidoc.AsciiDocActionGroup">
...
public class AsciiDocActionGroup extends DefaultActionGroup {
  @Override
  public boolean hideIfNoVisibleChildren() {
    return true;
  }
}
```
Here is a prototype of the toolbar: https://github.com/krasa/asciidoctor-intellij-plugin/tree/toolbar
(I found some icons on google, you might want to get new ones...)

**Comment by bodiam** [comment]
@krasa That's amazing! Is it also possible to have dropdowns lists in the toolbar?

**Comment by krasa** [comment]
Sure, it's just a plain swing.
I am going to hook on a better API now...

**Comment by bodiam** [comment]
Ah, yes, I see, it works:

![screen shot 2015-06-27 at 11 45 48](https://cloud.githubusercontent.com/assets/46468/8391378/18279448-1cc2-11e5-828e-e85d1130e6c7.png)

**Comment by bodiam** [comment]
I was thinking of doing a similar thing for the bootstrap 3 plugin I have (https://plugins.jetbrains.com/plugin/7572). It would be nice to organise the templates in a way that you can easily find them, and something like this might be nice.

**Comment by ahus1** [comment]
The current version of the plugin 0.15 has both the tool bar and the context menu. The context menu is only available in asciidoc documents, and hidden in other places. 

What is left to be done as part of this ticket? Should the context menu be removed completely?

**Comment by ahus1** [comment]
As nothing needs to be done for this ticket any more I close this ticket.
