### ISSUE TITLE
Travis CI changes in pricing plans

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#597]
This project uses Travis CI. On November 2nd they [announced their new pricing model](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). 

This boils down to that all open source projects:
* EITHER need to move over to travis-ci.com and apply for free build minutes or pay for their build minutes
* OR they need to find some other place (maybe GitHub actions)

**Comment by mojavelinux** [comment]
Many of the Asciidoctor projects have moved to GitHub Actions with great success. You can find examples in asciidoctor, asciidoctor-pdf, asciidoctor-epub3, and asciidoctor.js.

**Comment by mojavelinux** [comment]
Ping me once the switch is complete so that I can disable the link in Travis CI.

**Comment by ahus1** [comment]
The first pre-release was delivered via GitHub actions from the master branch.
Travis CI will be active on the 0.30.x branch in case an error fix release would become necessary. 

Should an error fix release for the 0.30.x branch become necessary after Dec 2020 (which I consider unlikely), the 0.30.x branch needs to be migrated to GitHub actions ad-hoc.

**Comment by mojavelinux** [comment]
So for now you want me to keep the Travis CI link active? Or shall I disable it entirely?

**Comment by ahus1** [comment]
@mojavelinux - please keep the Travis CI link active until end of December 2020.

**Comment by mojavelinux** [comment]
Gotcha! Thanks for clarifying. :+1:
