### ISSUE TITLE
Spellcheck please

### ISSUE THREAD

**Issue by kittylyst** [asciidoctor/asciidoctor-intellij-plugin#6]
The Markdown plugin has a spellchecker integrated - can we pinch some code from them?

**Comment by p-himik** [comment]
I don't have any spellchecking on v0.26.15.
If I'm not the only one, maybe this issue needs to be reopened.

**Comment by ahus1** [comment]
@p-himik - I did a quick check and for me spellchecking works in 0.26.15.

If the problem persists, please open a new ticket and provide the information about your IDE and plugin versions and a short sample document.

**Comment by p-himik** [comment]
Thanks for checking! I tried reinstalling the plugin and clearing the indices to no avail. But it's definitely something on my side since starting with IDEA and AsciiDoc from a blank slate makes the spellcheck work again.

**Comment by ahus1** [comment]
@p-himik - I've opened ticket #269, please continue the documentation there.
