### ISSUE TITLE
line wrapping

### ISSUE THREAD

**Issue by jmMeessen** [asciidoctor/asciidoctor-intellij-plugin#60]
I might have overlooked a possible solution. In that case, sorry.

I spend quite some time reformatting the asciidoc source code of a paragraph especially when I edit text. I would like a possibility to (re) wrap a paragraph at 80 columns for example.

Setting the editor to automatic line wrap solves part of the problem but doesn't work reliably especially when editing an existing test.

**Comment by bodiam** [comment]
Hi @jmMeessen , thanks for the feature request. At the moment, I personally don't have time to implement this, but if you want to implement something yourself, I might be able to help and offer advise, and pull requests always welcome of course!

**Comment by mojavelinux** [comment]
I understand the instinct to want to hard wrap lines to tidy up the source. However, I strongly encourage you not to hard wrap lines in the AsciiDoc source. It's much easier to both localize changes and move sentences around when you follow a sentence-per-line (or phrase per line) strategy.

Keep in mind, this is just a recommendation. I know there are circumstances that will require hard wrapping and it's still reasonable to have this option in the plugin.

**Comment by jmMeessen** [comment]
Hello

Indeed, you're making an interesting point @mojavelinux. Maybe hard lines wraps is not what I am looking for. It would rather be "consistant line wraping" in my case. It looks like that Intellij is not very good at this type of behaviour (or I missed something). I end up being distracted quite a lot when editing (in the sense style, spelling, clearness, etc) because of these soft/hard wrap.

If somebody else has an idea / recommendation / work pattern to solve my issue he is welcome. In the mean time, I will think about.

I will also try the one sentence-per-line strategy. I am to much influence by years behind a wordprocessor. This happens with older people ;-). Any publications/reads recommendation on these documentation writing patterns and strategies ?

Jean-Marc

**Comment by mojavelinux** [comment]
> I will also try the one sentence-per-line strategy.

It's the single best thing that's ever happened for my writing. Kind of like flash cards do for learning...they just click.

**Comment by mojavelinux** [comment]
> Any publications/reads recommendation on these documentation writing patterns and strategies ?

Not a whole lot, though I plan to publish something on the topic. I picked it up from the Neo4j guide.

http://neo4j.com/docs/stable/community-docs.html

**Comment by bodiam** [comment]
What do you think @jmMeessen ? Do you still feel like you need this feature?

**Comment by jmMeessen** [comment]
Hi Eric. Well I tried the "phrase per line" technique. Amazing how it improves the documentation workflow. Adopted.

So consider this enhancement as unnecessary. Thanks for the support and the ideas.

Jean-Marc

PS: thanks (again) for the neat addition to IntelliJ

**Comment by mojavelinux** [comment]
> I tried the "phrase per line" technique. Amazing how it improves the documentation workflow. Adopted.

\o/

What pleases me the most is to hear that word "improves". That's how we define success. I love it!
