### ISSUE TITLE
A space between line comment marker and the following text

### ISSUE THREAD

**Issue by john-cj** [asciidoctor/asciidoctor-intellij-plugin#601]
Currently, when I press `Ctrl+/`, there is no space between `//` and the text which follows it.

Most style guides advocate for this space, and so we are very used to use it. It will be useful to have an option to enable it.

Current behavior:

```
foo
becomes
//foo

// foo
becomes
 foo (with a space in the beginning; bad)
```

Requested behavior (optional):

```
foo
becomes
// foo

// foo
becomes
foo
```

**Comment by ahus1** [comment]
Thanks John for observing and reporting this!

A future version should behave like described above. 
In addition, it needs to handle old comments without the blank:

```
//foo
becomes
foo
```

I'm marking this issue as a "good first issue", as this allows contributors to get familiar with the IntelliJ API: It seems that only a few classes need to be touched to implement this functionality.

As with all issues (and especially the ones labeled good-first-issue) maintainers are willing to help.
See the Guide [Contributing as a Code](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/contribute-as-a-coder.html) on how to set up a development environment.

Details on getting into coding with this issue:

Commenting is currently implemented in [AsciiDocCommenter](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/src/main/java/org/asciidoc/intellij/AsciiDocCommenter.java). 

As it seems, the IntelliJ API provides an additional API _SelfManagingCommenter_ to implement the behavior described above. See [PropertiesCommenter.java](https://github.com/JetBrains/intellij-community/blob/master/plugins/properties/properties-psi-impl/src/com/intellij/lang/properties/PropertiesCommenter.java) for an implementation.

**Comment by hemantmandge** [comment]
Assign it to me!

**Comment by ahus1** [comment]
Done! Happy coding .... please feel free to ask questions, I'll assist!

**Comment by hemantmandge** [comment]
Thanks for assigning! I have raised PR! If approved it will be my first PR towards Hacktoberfest 2021

**Comment by ahus1** [comment]
Hi @hemantmandge - as outlined in my comment of the PR this issue is not about changing comments in the plugin's code. It is about changing the plugin's behavior when commenting/uncommenting AsciiDoc snippets in IntelliJ using this plugin. 

Please let me know if you're willing to take on that task.

**Comment by hemantmandge** [comment]
Hi @ahus1 - Thanks for your patience and helping to understand the issue. I would certainly want to work on it. Kindly assign it to me. Is there a slack channel which I can join?

Also as per above comment, "Commenting is currently implemented in AsciiDocCommenter.

As it seems, the IntelliJ API provides an additional API SelfManagingCommenter to implement the behavior described above. See PropertiesCommenter.java for an implementation."

Is it suggested to do it with IntelliJAPI? or updating existing code?

**Comment by ahus1** [comment]
Thanks to #601 and the @marcoebbinghaus's work, this will be part of the next upcoming release.

**Comment by ahus1** [comment]
As I needed to fix a performance regression, this has been release a bit earlier than expected as 0.37.52 and is now already available from the JetBrains marketplace. Enjoy!
