### ISSUE TITLE
Toggle buttons on top bar don't wrap words correctly when placed at the end of word

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-intellij-plugin#602]
## Observed vs. expected behavior

When I have the cursor in the middle or beginning (right before first character) of a word, and use one of the *Toggle* options (bold, italics, mono, strike through, highlight and url*) the word gets correctly wrapped.
For example `conversion` -> becomes `*conversion*`.

However, when the cursor is at the end of the word, the markup is double and added at the end. `conversion` -> becomes `conversion****`.

 *  Url is special, the link macro is concatenated at the end.

## Steps to reproduce

. Write a sentence, for example, "The conversion happens in 2 flavors"
. Place cursor after a word, in the example right between the "n" of conversion and the space.
. Press "Toggle Bold"

## Environment

Plugin Version: 0.31.43

IntelliJ Details:
IntelliJ IDEA 2020.2.3 (Community Edition)
Build #IC-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.9.8-2-manjaro
GC: ParNew, ConcurrentMarkSweep
Memory: 1937M
Cores: 16
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: Lombook Plugin, org.toml.lang, org.jetbrains.kotlin, org.asciidoctor.intellij.asciidoc, org.rust.lang
Current Desktop: Undefined

**Comment by ahus1** [comment]
Thanks for reporting this, I'll look into it. 

As you noticed it works best with the cursor placed in the the middle of the word. 
It works even better if the text is selected before clicking the icon. 

While you wait for the fix to arrive, here are the keyboard macros you can use: 
* Ctrl+W to mark a word to be marked in bold (press multiple times to select more, press Shift+Ctrl+W to shrink)
* Press "*" to make the selection bold

Creating an URL also works best with pre-selected text. The action will behave differently depending whether you selected text or URL before pressing it. It's a behavior I replicated from GitHub's text areas: 
* Select some text, press the URL icon, and paste the URL from the clipboard
* Select an URL, press the URL icon, and then paste (or type) the text

**Comment by ahus1** [comment]
This will be part the next upcoming release. I'll update this ticket once the ticket is available.

**Comment by ahus1** [comment]
The pre-release 0.32.1 includes a fix for this. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
