### ISSUE TITLE
File name `conversion-options.adoc` is not recognized

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-intellij-plugin#603]
## Observed vs. expected behavior

:man_shrugging: weird one...File with name `conversion-options.adoc` is not recognized as Asciidoc file, and does not open preview.

![image](https://user-images.githubusercontent.com/5781153/100390822-f9f44c80-3031-11eb-95b5-cb93fa86527c.png)

I tried to see if it was the ending, or the beginning of the filename, but I could only make ot happen with this name.

## Steps to reproduce

Just create a file with name `conversion-options.adoc`.
Does reproduce in and out of Antora modules.

## Environment

Plugin Version: ____
0.31.43

IntelliJ Details: ____

IntelliJ IDEA 2020.2.3 (Community Edition)
Build #IC-202.7660.26, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.9.8-2-manjaro
GC: ParNew, ConcurrentMarkSweep
Memory: 1937M
Cores: 16
Registry: debugger.watches.in.variables=false
Non-Bundled Plugins: Lombook Plugin, org.toml.lang, org.jetbrains.kotlin, org.asciidoctor.intellij.asciidoc, org.rust.lang
Current Desktop: Undefined

**Comment by ahus1** [comment]
I tried to reproduce it locally and didn't succeed yet. I tried to install the Rust plugin, and was still unable to reproduce it. 

Could you please check your settings in "Settings... > Editor > File Types"? May the name was miss-associated with another file type? Unfortunately I didn't find a way to search across all file types.

**Comment by abelsromero** [comment]
Yes, there was an association with another type. No idea how it got there though :thinking:
