### ISSUE TITLE
Formatting broke some titles

### ISSUE THREAD

**Issue by luvarqpp** [asciidoctor/asciidoctor-intellij-plugin#604]
## Observed vs. expected behavior

When I format document with titles with variables or/and custom anchors, plugin does broke given titles. For example:

```
== [[customAnchor]] Čo je {variableName} a na čo slúži?
```

## Steps to reproduce

Execute format (ctrl+alt+L) command. This will change given title to something like this:
```
== 
[[customAnchor]]

 Čo je 

{variableName}

 a na čo slúži?
```

## Environment

Plugin Version: 0.31.43

IntelliJ Details: IntelliJ IDEA 2020.2.4 (Community Edition)
Build #IC-202.8194.7, built on November 24, 2020
Runtime version: 11.0.9+11-b944.49 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-53-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1976M
Cores: 8
Non-Bundled Plugins: PlantUML integration, DBN, Lombook Plugin, com.oliverlockwood.plugins.jenkinsfile, im.jeanfrancois.ideaplugins.ideafullscreen, training, net.seesharpsoft.intellij.plugins.csv, org.jetbrains.plugins.hocon, Docker, org.jetbrains.kotlin, org.intellij.scala, com.intellij.lang.jsgraphql, org.asciidoctor.intellij.asciidoc
Current Desktop: i3

**Comment by ahus1** [comment]
Thanks for reporting this; I'll fix this for the upcoming release.

**Comment by luvarqpp** [comment]
Thanks, one additional catch, if it is not problem to report in single issue:
```
Some sentence. {variable} other sentence.
```
Is not being formatted by rule "one sentence on one line".

**Comment by ahus1** [comment]
The detection of end of sentences is a heuristics. The current heuristic recognizes dots that are an end of a sentence if they are (among others) are followed by a capital letter. With an attribute like in your example its hard to decide without evaluating it. And re-formatting should depend on other files with attributes. 

The current behavior in this case is: As it is hard to decide if it is the end of a sentence, keep it in one line if it is in one line, and keep it in two lines if they are in two lines. Unless you can suggest a good heuristic, I'd prefer to leave it this way. If you have a heuristic you want to discuss, please create an enhancement issue.

**Comment by ahus1** [comment]
The pre-release 0.32.1 includes a fix for this issue. I used the example you provided to test it. As this now works, I close this issue. Please comment here if you continue have issue with formatting headers, or open a new issue if you discover other issues. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
