### ISSUE TITLE
Issue rendering docinfo file, stylesheet, and author info

### ISSUE THREAD

**Issue by 8thHalfHour** [asciidoctor/asciidoctor-intellij-plugin#607]
## I am unable to do the following:

1. Make the docinfo.html file to render into the head of my document when converted to html
2. Render the document using the correct stylesheet
3. Link to the stylesheet instead of embedding it in the page.
4. Stop creating a `{asciidoctorconfigdir}` folder with files in it at the level of my file
5. Stop showing the author name and email address in the rendering.

---

### This is my file tree:

```
o
`-- main_folder
    |-- css > tufte.css
    |-- folder_1
    |   |-- folder_1-1
    |   `-- folder_1-2
    |       |-- folder_1-2-1
    |       `-- folder_1-2-2 <- the file I am rendering -> file.adoc
    |-- .asciidoctorconfig
    `-- docinfo.html
```

### And this is my .asciidoctorconfig file:

```
= Title
:myprojectbasedir: {asciidoctorconfigdir}
:docinfo: shared
:docinfodir: {asciidoctorconfigdir}
:stylesdir: {asciidoctorconfigdir}/css/
:stylesheet: tufte.css
:author: Frank Mann
:authorinitials: FM
:email: fmann@gmail.com
:source-highlighter: highlights.js
:icons: font
:linkcss:
```

### My document (file.adoc) has this header:

```
:myprojectbasedir: {asciidoctorconfigdir}
```

### My docinfo.html

```
<meta charset="utf-8">
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
<!-- FontAwesome 5 CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" />
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"></script> -->
<!-- jQuery and JS bundle w/ Popper.js for Bootstrap -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
```

---

## Checking that everything is seeing each other

From within the document, I make sure all of the variables are being seen, from the `.asciidoctorconfig` file on up. One-by-one, I try each attribute in curly braces and the correct values and paths are returned. It appears to be set up correctly.

`{docinfo}` renders `shared`
`{docinfodir}` renders the full path on my hard drive to the root folder. The `docinfo.html` file is in the root.
`{stylesdir}` renders the root dir/css; this is also correct.
. . . and so on.

I test font icons are working:

`icon:tags[]` displays the tags icon. Still good here. I think I'm ready to go.

---

## The issue

When I finally go to the terminal and navigate to the directory where that file is located, I enter the following command:

`asciidoctor file.adoc`

The html file renders FAST. It's awesome. BUT! It's all wrong:

  1. My docinfo.html info is not placed into the head of the html.
  2. A random folder called `{asciidoctorconfig}` is now in the directory with my file.
  3. The stylesheet I specified was not applied.
  4. The default stylesheet is embedded in the head.
  5. The author name and email address are displayed beneath the header

---

## Troubleshooting

I tried various techniques to see if I could get it working, but ultimately, I had to put that full header directly into `file.adoc` and use relative urls to the files for the file to use the correct stylesheet and put the head info in correctly. This is the only thing that worked (though the author name and email continue to be displayed. I don't know what to do about that.):

```
= Title
:myprojectbasedir: {asciidoctorconfigdir}
:docinfo: shared
:docinfodir: ../../../../
:stylesdir: ../../../../css/
:stylesheet: tufte.css
:author: Frank Mann
:authorinitials: FM
:email: fmann@gmail.com
:source-highlighter: highlights.js
:icons: font
:linkcss:
```

---

I'm guessing I'm missing something crazy simple, but I've read through the docs and looked online and I just can't figure it out.

**Comment by ahus1** [comment]
Hi Charisma, Dan moved this issue over to the AsciiDoc IntelliJ plugin repository. 

The `{asciidoctorconfigdir}` attribute and also the functionality of `.asciidoctorconfig` you use are currently supported only within the IntelliJ plugin. I'll update the documentation to state that in the docs. The intention to add them originated from a situation where I wanted to configure the preview of files that would later be included in a main document. 

If you want to use the contents of an `.asciidoctorconfig` file when rendering on the command line, you'll need to include its contents using an `include::[]` preprocessor macro. When you have a single main document that includes multiple child documents, you would include this file in the main document. 

If you want to have the `{asciidoctorconfigdir}` set when rendering on the command line, you could pass the file path on the command line similar to this: 

```
asciidoctor -a asciidoctorconfigdir=<relative or absolute path> file.adoc
```

The above is a summary to explain what you see, and what options you have. I'll now outline how a setup could look like.

I haven't yet fully understood the result you are aiming for. I assume that you want 
* several single files
* render each of them individually
* each rendered file should have the same common attributes and setup.

The following bits and pieces might be part of a solution for you: 
* Use the `include::[]` preprocessor macro to include the common part in each single file at the top. Use an attribute to point to it (like: `include::{mainfolder}/header.adoc`. 
* put the contents you need 
* on the command line, pass mainfolder as an attribute with an absolute path
* in the ´.asciidoctorconfig` file, set the `mainfolder` attribute to `{asciidoctorconfigdir}`

I hope that this explains what you see, and offers some bits for a solution.

**Comment by ahus1** [comment]
There hasn't been a comment in this issue for more than a month, therefore I close this issue. Please comment to re-open this issue.
