### ISSUE TITLE
Could preset a default folder when paste images

### ISSUE THREAD

**Issue by c332030** [asciidoctor/asciidoctor-intellij-plugin#608]
## Why the new feature should be added
Eveny time I must create a folder before paste images in documents on the first time. 
I usual put images in folders which name associate with document files.
The default folder name can be set manually or use last rule you input.

## How the new feature should work
This is markdown paste images dialog of idea plugin.
It's provider an default folder name rule but you can change and it will remember what you give.
![image](https://user-images.githubusercontent.com/15310784/101275955-d759f480-37e4-11eb-9c99-72f00301f240.png)

**Comment by ahus1** [comment]
Thanks for raising this issue. 

I'd like to explore another option than defining a directory name rule: 
In AsciiDoc the writer can specific an attribute `imagesdir` that points to a folder with all the images. Do your documents have an `imagesdir` attribute defined? If this would be the case, the plugin could open that folder as the default.

Please let me know if this would support your scenario. Thanks!

**Comment by c332030** [comment]
No, I've never defined it.
