### ISSUE TITLE
Live-Template for Admonitions

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#609]
I always have a problem to remember the list of available admonitions.
A live template would help.

**Comment by ahus1** [comment]
Yes, maybe a live template for admonitions would be good thing to have. 

Please note that all users can add their own live templates at any time; this way you can give new live templates a test run within your own day-to-day environment first.

**Comment by rdmueller** [comment]
I've added two templates (block & paragraph) which help me a lot because they provide a drop down with the available admonition types.

**Comment by ahus1** [comment]
Thanks for adding these two templates; I've merged the change!

**Comment by ahus1** [comment]
This change is now available as part or pre-release 0.32.4.

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
