### ISSUE TITLE
Missing class "org.asciidoc.intellij.actions.ConvertToAsciiDocAction"

### ISSUE THREAD

**Issue by wsidl** [asciidoctor/asciidoctor-intellij-plugin#61]
Installed the latest build of the plugin (#56) into PyCharm and get this PluginException on startup:

    class with name "org.asciidoc.intellij.actions.ConvertToAsciiDocAction" not found [Plugin: org.asciidoctor.intellij.asciidoc]: class with name "org.asciidoc.intellij.actions.ConvertToAsciiDocAction" not found [Plugin: org.asciidoctor.intellij.asciidoc]

**Comment by bodiam** [comment]
I installed PyCharm CE 4.0.4 with AsciiDoc 0.7, and I couldn't reproduce it. Have you tried invalidating your caches and maybe reinstalling the plugin?

**Comment by wsidl** [comment]
Invalidated Cache, Upgraded from PE 3.4.1 to PE 4.0.4, Invalidated again and still getting the error.

**Comment by bodiam** [comment]
Hmmm, that's so strange! 

@harrol , can you try to reproduce this?

**Comment by harrol** [comment]
Mmm. I have and oldie: NoClassDefFoundError: update failed for AnAction with ID=asciidoc.maketitle: com/intellij/openapi/actionSystem/DataKeys. Wasn't this fixed with the 0.7 release? Or will it be fixed in the next release?

**Comment by harrol** [comment]
... and when running with the latest development version everything is fine...

**Comment by wsidl** [comment]
Found my mistake. Need to build plugin first.
Built, installed and everything works now.

**Comment by harrol** [comment]
:+1: And @bodiam, I guess it is time for a 0.8 release? 0.7 is not usable on non-IDEA IDE's...

**Comment by bodiam** [comment]
Totally right! I thought 0.7 fixed this already, but apparently not. I've created a 0.8 version, and it's being uploaded right now.

**Comment by mojavelinux** [comment]
:+1: Should we call this one the birthday release?
