### ISSUE TITLE
Sort autocompletion items for image and include macros

### ISSUE THREAD

**Issue by rdmueller** [asciidoctor/asciidoctor-intellij-plugin#610]
currently, when autocompletion kicks in, you get a list of folders and files as drop down.
This list has no sort order. It should first display all folders and then all files, sorted alphabetically.

**Comment by rdmueller** [comment]
I thougt I've found the right location to sort the items of the drop down:

https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/ad6d138880063f0d0280b3ea1dfeabc8529a3e9e/src/main/java/org/asciidoc/intellij/psi/AsciiDocFileReference.java#L925

but sorting the list of PsiElements will not change the drop down :-o
https://github.com/rdmueller/asciidoctor-intellij-plugin/blob/9c68e688beb9f0af4d744126a793480d19e3cc1d/src/main/java/org/asciidoc/intellij/psi/AsciiDocFileReference.java#L934

Any idea?

**Comment by ahus1** [comment]
IMHO IntelliJ tries to sort the list by most recently used entries. To sort it alphabetically, as a user choose the three dots while editing. Then change it to alphabetically sorted. It will not sort directories first.

**Comment by rdmueller** [comment]
thanx. as most of the time, this was a RTFM :-) But I learned something new about the code of the plugin :-)
I'll close this now
