### ISSUE TITLE
Why does my custom extension attributes not resolve in IntelliJ preview?

### ISSUE THREAD

**Issue by Stmated** [asciidoctor/asciidoctor-intellij-plugin#612]
If I am using `spring-restdocs-asciidoctor` and in preview editor write:
`Snippets: {snippets}`

The preview will read:
`Snippets: [path]/target/generated-snippets`

But if I have written a custom extension with:
```
    public void register(Asciidoctor asciidoctor) {

        asciidoctor.javaExtensionRegistry().preprocessor(new Preprocessor() {

            @Override
            public void process(Document document, PreprocessorReader preprocessorReader) {
                document.setAttribute("foo", "bar", false);
            }
        });
    }
```

And I write:
`Test: {foo}`

It will not resolve in the preview. However, when I compile (execute the plugin), it is resolved and rendered properly. So all the /WEB-INF/service locator stuff seems to be right.
I cannot see anything in the `spring-restdocs-asciidoctor` code that it does differently compared to me. But for restdocs it works, but not for me. How come?

Thought it could be related to https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/416, but no, even with it enabled there's no difference.

Am I registering something improperly, or is this not supported yet?

**Comment by Stmated** [comment]
Okay, I took the time to read the code of AsciiDocUtil.java, and it does seem like it is hard-coded at the moment.

I have never built any plugins for IntelliJ, but some for Maven and other systems.... but did you see any issues with going the route of auto-discovering the attributes that the plugin could have access to?

If there's no certain reason why not, could I take a look at it and submit a PR?

**Comment by ahus1** [comment]
Hi - as you found out the support for `{snippets}` is built-in for Spring REST docs. See the [user's guide for details](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/spring-rest-docs.html).

For the situation you describe above, I see two options (although I don't know all the details of the situation and what you want to achieve): 

**Option 1:** If you want to set a specific attribute for your project, and assuming that is is a constant path or value in your project, I suggest you have a look at [the `.asciidoctorconfig` file](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctorconfig-file.html). You can place it in a parent folder and put `:foo: bar` in it, and you're done.

**Option 2:** If you want to use an Asciidoctor extension (either Ruby or Java) within your project, you can place it in a folder `.asciidoctor/lib`. The [user's guide has a little bit more information on how to do this](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctor-extensions.html). When using Java, you can place a JAR with the extension and all needed dependencies in the folder. 

I recommend to try out option 1 first, as it is straight-forward to set up and is a proven setup. 

With option 2 might run into issue with class loaders and memory leaks that run within your IDE; please proceed with caution. I consider using Asciidoctor extensions within the IDE plugin still quite experimental.      

If you think none of these options match your need, please provide more details about your situation.

**Comment by ahus1** [comment]
There hasn't been a comment in this issue for more than a month, therefore I close this issue. Please comment to re-open this issue.
