### ISSUE TITLE
Comment / uncomment lines

### ISSUE THREAD

**Issue by PascalGugenberger** [asciidoctor/asciidoctor-intellij-plugin#63]
I would love to see the feature "comment / uncomment lines" for asciidoc files.

We are using a template for our documentation. We would like to comment out all the parts we are currently not using without removing them from the file completely.

**Comment by mojavelinux** [comment]
:+1: 

Keep in mind that AsciiDoc supports two types of comments, line comments and block comments, just like Java.

**Comment by ehmkah** [comment]
@bodiam I think this feature is already working. I use "comment with line comment" and "comment with block command" from intellij menu. Or am I doing something wrong? Tried version 0.10.

**Comment by ahus1** [comment]
@yole added this in July 2015 - thanks!
