### ISSUE TITLE
Diagram : pikchr

### ISSUE THREAD

**Issue by phreed** [asciidoctor/asciidoctor-intellij-plugin#647]
## Description
I have been trying to construct a diagram using the PikChr language but it is not rendering.
Which of the diagram generators should be available?
https://asciidoctor.org/docs/asciidoctor-diagram/#specifying-diagram-generator-paths
I have had luck with:
* ditaa
* graphviz
* plantuml

The remaining diagram types have not worked for me.

**Comment by ahus1** [comment]
Thanks for asking this question. 

Reproduce this locally, could you please provide a snippet of AsciiDoc content plus diagram that you used? 

As you want to use PikChr, did you configure this plugin to use Kroki, or did you go with the "standard" to use Asciidoctor Diagram? If you are not sure, please post a screen shot of your plugin's settings via "File | Settings... | Languages & Frameworks | AsciiDoc"

**Comment by ahus1** [comment]
No feedback for several weeks, closing this issue. If you can provide more details, please comment here and I'll re-open the issue.
