### ISSUE TITLE
plugin makes editor unberably slow

### ISSUE THREAD

**Issue by gggeek** [asciidoctor/asciidoctor-intellij-plugin#65]
I have a medium-sized asciidoc file (4k lines).
After enabling the plugin, whenever I type a couple of characters in the file, I have to wait 5/10 secs to see them appear and the caret follow the arrow keys I keyed.

I am not 100% sure, but it seems that
- the doc is re-rendered on each keypress
- the rendering does not happen in a separate thread

This is on a dell xps15 laptop with 16gb ram, full ssd disk.

**Comment by bodiam** [comment]
Can you share the document, so I can reproduce it? If you don't want it to be public, you can also send it to my email: <firstname>.<lastname>@gmail

**Comment by gggeek** [comment]
Hi. It is this one: https://github.com/gggeek/phpxmlrpc/blob/php53/doc/manual/phpxmlrpc_manual.adoc

**Comment by pmcneil** [comment]
I can confirm it is rather slow even on a 315 line file. Perhaps if we could disable the preview?

**Comment by leonard84** [comment]
I can also confirm this, it seems to run the preview generation on every key press. There should be an option to only compute the preview, when the preview tab is opened.

**Comment by bodiam** [comment]
Hi guys, thanks for the feedback, and good suggestions. I don't have time to work on this, but if any of you can send me a pull request, I'll release a new version to fix this! Thanks!!

**Comment by krasa** [comment]
Interesting thing, JEditorPane#setText took 400ms on EDT, but every next call took more and more (even several seconds) until a full GC was triggered, then it went back to 400ms. #setDocument on the other hand takes less and less down to 30ms on EDT.

**Comment by mojavelinux** [comment]
Thanks for the pull request, @krasa!

setDocument seems like the way to go! Is that how the pull request is implemented?

**Comment by krasa** [comment]
Yep.

**Comment by leonard84** [comment]
@bodiam can we get a fixed version as soon as pr #66 is merged? Thanks @krasa

**Comment by bodiam** [comment]
Hi @leonard84 , the plugin is available now. Thanks all for reporting, but especially @krasa for fixing this!
