### ISSUE TITLE
Preview error: Cannot Open the Page

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-intellij-plugin#658]
With 0.32.14 and 0.32.15 (and some of the pre-releases as well), I infrequently encounter an error when opening an Asciidoc file. The Asciidoc text is displayed in the editing window, but the preview window contains the following error:
````
Cannot Open the Page

file:///jbcefbrowser/1872897587#url=jar:file:/home/acidocs/.local/share/JetBrains/IdeaIC2020.3/asciidoctor-intellij-plugin/lib/asciidoctor-intellij-plugin-0.32.15.jar!/org/asciidoc/intellij/editor/jcef/AsciiDocJCEFHtmlPanel.class@2111284841

ERR_ABORTED
````
If I click on the Asciidoc file a second time (in the Project window), it reloads and the preview is correct.

IntelliJ IDEA 2020.3.2 (Community Edition)
Build #IC-203.7148.57, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-65-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 979M
Cores: 2
Non-Bundled Plugins: de.docs_as_co.intellij.plugin.diagramsnet, org.jetbrains.kotlin, PythonCore, org.asciidoctor.intellij.asciidoc
Current Desktop: X-Cinnamon

**Comment by ahus1** [comment]
Thanks for reporting this. I digged into the IntelliJ code of 2020.3.x and found situation where a cancelled refresh in the preview triggers this message. This cancellation could happed for an embedded iframe, or for the page itself when the user is still typing. 

The next upcoming release will fix this by disabling this "feature" in the IntelliJ code base. I see that it is being reworked for 2021.x, so it seems they are aware of this situation. [IDEA-259472](https://youtrack.jetbrains.com/issue/IDEA-259472)

I update this issue once the release is available.

**Comment by ahus1** [comment]
Version 0.32.16 is available that includes this fix.
