### ISSUE TITLE
Provide dark mode for plugin's documentation

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#662]
## Why the new feature should be added

Users are used to dark mode in their IDEs, let's add it to the documentation at https://intellij-asciidoc-plugin.ahus1.de/ as well.

## How the new feature should work

When the user shows preference of a dark theme, the theme should be dark. There is already a CSS media query for this: 

```
@media (prefers-color-scheme: dark) {
}
```

There are already some snippet's in the plugin's `darcula.css`

**Comment by gs-kug** [comment]
The docs are good about highlighting features of source code and are very flexible; I just need to search a little bit, and I was able to improve it a lot.
Thanks for the excellent work on this plugin!

**Comment by ahus1** [comment]
@gs-kug - thanks for raising this. Your comment about the preview was already reported in issue #1668. 

Please follow the discussion over there as this issue is about the documentation web site of the plugin you find here: https://intellij-asciidoc-plugin.ahus1.de/
I've updated the description. 

BTW, the problem you reported is now fixed in 0.43.1

**Comment by ahus1** [comment]
No volunteer found to work on https://intellij-asciidoc-plugin.ahus1.de/ in dark mode over the years. Closing as "won't fix".
