### ISSUE TITLE
0.32.16: Document links are opened inside IDEA preview instead of external browser

### ISSUE THREAD

**Issue by dvponomarev** [asciidoctor/asciidoctor-intellij-plugin#665]
## Observed vs. expected behavior

Before 0.32.16 every link click in preview was opened in default browser, Ctrl+Wheel preview zoom was working.
Since 0.32.16 in some documents links are opened inside IDEA preview, at the same time Ctrl+Wheel preview zoom is not working.
Expect every link open in external browser by click, preview zoom should work.

## Steps to reproduce

Some documents are opened with slightly larger text side in IDEA preview and Ctrl+Wheel zoom is not working on it. And links are opened inside IDEA preview instead of external browser.
Tried to copy contents of problem file to other .adoc file - links and zoom are ok but after IDEA restart the same problem occurs in the file.
Tried to simplify file (to contain only one link) - the problem remains.
Tried to create the new IDEA project with single file - works ok, no problem with link open and zoom, even after IDEA restart.

Simple flow is reproducible in both 2 my projects (I have only 2 projects with .adoc files):

- create file a.adoc
- enter contents: https://google.com (leave it in "Show Editor and Preview" mode)
- for now it works OK
- restart IDEA
- the file a.adoc is opened in "Show Editor and Preview" mode, now it works NOT OK (link is opened inside preview, Ctrl+Wheel zoom is not working)

Note that if the file is opened in "Show Editor and Preview" mode - NOT ok.
When open in "Show Preview Only" - OK.
But for some files it is NOT OK even in "Show Preview Only" mode.

Workaround for one file:
- open file in "Show Editor and Preview" mode - NOT OK
- switch mode to "Show Preview Only"
- close file with Ctrl+F4
- again open file, it is opened in "Show Preview Only" mode - OK

Workaround for whole project:
- close all opened project files (.adoc files)
- open any file in any mode - works OK

So I don't know how to reproduce it exactly... Somehow it is related to the project currently opened files.

## Environment

Plugin Version: 0.32.16

IntelliJ Details: IntelliJ IDEA 2020.3.2 (Community Edition)
Build #IC-203.7148.57, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 4.15.0-134-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1484M
Cores: 12
Non-Bundled Plugins: com.github.holgerbrandl.pasteimages/, com.javampire.idea-openscad, org.asciidoctor.intellij.asciidoc
Current Desktop: ubuntu:GNOME

**Comment by ahus1** [comment]
I'm sorry to hear the latest release causes you problems. I'm starting to dig into it. Could you please provide a log file to me, maybe there's a hint in there. If you don't want to post it in public, you can choose to send it to me by email (see my profile for the address).

Thanks!

**Comment by ahus1** [comment]
I reworked the fix for #658; I suspect this broke the preview for you. 

The fix is part of pre-release 0.32.17. Please give it a try and let me know if it works for you. 

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by dvponomarev** [comment]
pre-release 0.32.17 fixed the issue on both of my projects!!!
Thanks a lot!!!

**Comment by ahus1** [comment]
Thanks - I promoted this release from pre-release to a proper release!
