### ISSUE TITLE
"HTML" button raises an error when activated on MacOS 

### ISSUE THREAD

**Issue by jpgringo** [asciidoctor/asciidoctor-intellij-plugin#666]
## Observed vs. expected behavior

When clicking the "HTML" button at the top of the editor, I expect:

- an HTML file to be generated from the current AsciiDoc file
- (if successful) the HTML file to be opened in my default browser

Observed:

- HTML file is successfully generated
- IntelliJ display an error dialog stating "Browser Error: The file /file:/{correct absolute path to generated doc}.html does not exist. Options are "OK" (which dismisses the dialog) and "Fix…" which brings up the browser preferences
- browser is not launched/activated; link is not loaded
- from the timing of updates in the UI, it appears that the browser is being notified before the document has been created (although maybe not… this occurs even when the output file already exists. Could it be that the plugin is deleting the existing file, notifying the browser, and then writing a new version?)
- right-clicking on the output file in the IntelliJ Project window and choosing "Open In > Browser > Default" works as normally

## Steps to reproduce

In IntellIJ:

1. go to Preferences: Tools > Web Browsers and ensure the Default Browser is correctly configured
2. test this by previewing any .html file from the Project pane
3. open any AsciiDoc file know to successfully translate to HTML
4. click the "HTML" button

## Environment

Plugin Version: 0.32.17

IntelliJ Details: 

IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 25, 2021
Licensed to ####
Subscription is active until ####.
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.16
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Registry: compiler.automake.allow.when.app.running=true, ide.balloon.shadow.size=0, js.debugger.webconsole=false
Non-Bundled Plugins: de.docs_as_co.intellij.plugin.diagramsnet, indent-rainbow.indent-rainbow, org.jetbrains.erlang, org.jetbrains.kotlin, izhangzhihao.rainbow.brackets, Pythonid, org.jetbrains.plugins.vue, ru.adelf.idea.dotenv, org.asciidoctor.intellij.asciidoc

**Comment by ahus1** [comment]
I tried to reproduce it on Windows, but without luck.

I noticed in your error message "The file /file:/" a slash "/" in front of "file:" that shouldn't be there. Could you please double check that there is a slash before **and** after the "file:"? If this is the case, this might be a key to solve this issue. 

Thanks in advance!

**Comment by jpgringo** [comment]
Yeah, I can confirm that. The error message starts out `The file /file:/Users/rick/…`

And thanks back, the plugin is great. And it still outputs the HTML, so that's an annoyance, not a showstopper.

Looks like you've already started to address it. I'm happy to test the fix for you (although I'll have to look up how to manually install a plugin on IntelliJ!)

**Comment by ahus1** [comment]
I tried again to using a Linux VM, and I was still unable to reproduce the issue. 

Anyway, I prepared a pre-release 0.32.18 with some changes. Please give them a try.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by jpgringo** [comment]
Sorry… got swamped and didn't get a chance to test this week, but just installed v0.32.19 and same issue

**Comment by ahus1** [comment]
Strange. Unfortunately I'm out of ideas here. Anyone who would be able to debug or reproduce this on MacOS is welcome to join in here.

**Comment by jpgringo** [comment]
@ahus1 I will try to have a look myself, but no promises. Quite busy at the moment and have never written an IntelliJ plugin (although a close colleague has) but it _is_ my issue, after all, so I'll give it a try

**Comment by ahus1** [comment]
Thank you. Here's for you (or anyone else) a starting point: 
 * The plugin's doc contain a [Getting started for Coders](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/coder/setup-environment.html) that starts with setting up the development environment.
* The code snippet that opens the browser is `BrowserUtil.browse()` in file [CreateHtmlAction.java](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/src/main/java/org/asciidoc/intellij/actions/asciidoc/CreateHtmlAction.java).

Good luck!

**Comment by jpgringo** [comment]
@ahus1 I've started by asking a few colleagues to double-check this (sorry, don't know why I didn't think to do this earlier.) All are running IntelliJ 2020.3.2 and v0.32.17 of your plug-in, and no one else is experiencing this. I'm going to continue to look at this as I can, if only out of curiosity about what's going on in my local environment, but given that response and the lack of any other reports from your end on this phenomenon, I'm going to close the issue. Thanks for being so responsive!

**Comment by ahus1** [comment]
Thanks for asking around. On the other hand my personal experience is that bugs don't just vanish, nor appear on just one machine. Instead they re-appear, and there is always someone else experiencing the same problem, even if it hasn't been reported yet. 

Therefore: I'm happy to support in any way needed once some can reproduce and debug this on MacOS X.
