### ISSUE TITLE
Zoom level for JCEF Browser **must** have the % sign or it won't work

### ISSUE THREAD

**Issue by barspi** [asciidoctor/asciidoctor-intellij-plugin#674]
## Observed vs. expected behavior

I was going to write that the zoom level for the JCEF Browse is not sticking, but now I figured out that it **MUST** have the `%` sign next to the number.

The zoom text field starts as `100%`. I've spent days trying to change it to, say, `90` or whatever, and as soon as I left the field focus, it would revert back to `100%`.  

As I was writing a new github bug report, for some reason I thought to append the `%` sign after the number and now the value seems to stick!

In any case, it's a **very confusing behavior**. It should at least be documented, or be more lenient, and if the user enters `90`, the value should be interpreted/updated as `90%` instead of ignoring what was just entered and revert to `100%`

(some way to change the zoom level per-window, at least with +/- buttons in 10% steps would be really nice, but that may merit a new github enhancement issue)

## Steps to reproduce

* Open the AsciiDoc preferences.
* Choose the `JCEF Browser`
* Change the zoom level to some value **without** entering the percentage `%` sign
* Expect the new value to be interpreted as a percentage, and stick in the field
* Seen behavior: the value reverts back to `100%`

## Environment

Plugin Version: `0.32.17`

IntelliJ Details: `Community Edition 2020.3.2`

**Comment by ahus1** [comment]
I'm sorry to hear that caused you trouble. 

Documentation alone will not solve it, it should be intuitive. I'll look into it.

**Comment by ahus1** [comment]
This will be fixed in the upcoming 0.32.21 release. The percent sign will no longer be part of the input field, but will be placed after the input field (see below). Zoom level per-tab is tracked in #675

![image](https://user-images.githubusercontent.com/3957921/109067230-82948e80-76ee-11eb-9346-be4e8f10dfd7.png)
