### ISSUE TITLE
Please add math support as in asciidoctor.js

### ISSUE THREAD

**Issue by asyrovprog** [asciidoctor/asciidoctor-intellij-plugin#69]
There is a very nice support for math formulas in asciidoctor.js which would be great to incorporate into this plugin. 

Please see resolved asciidoctor issue for more details:
https://github.com/asciidoctor/asciidoctor/issues/492

(Alternatively please provide opening of the document in external browser.)

**Comment by bodiam** [comment]
Sure, I can do this, but how? I read the link you provided, but I'm not sure what the solution is to support this. If you want to implement this yourself, I'm happy to approve any pull requests.

**Comment by mojavelinux** [comment]
The question really comes down to whether JavaScript works in the web view and how well. If it does, this is just a matter of adding the library. If not, well, then we have to think about other tricks to get the content converted to SVG...to which there are solutions on the JVM.

**Comment by bodiam** [comment]
I don't remember if it was built completely, but didn't we use AsciiDoctor.js some time ago to render the documents? I remember rendering the HTML with Nashhorn, but does rendering the Math work in the same way? 

Then I'd have to replace the JRuby stuff with AsciiDoctor, or make an option to switch (maybe better)

**Comment by mojavelinux** [comment]
To clarify, there is no reason to use Asciidoctor.js. I'm referring to the MathJax script that needs to be loaded into the web view.

**Comment by mojavelinux** [comment]
...with that said, I'm not ruling out the idea of exploring Asciidoctor.js, but that is a separate thread.

**Comment by bodiam** [comment]
I understand that's what you mean. But what I mean is: what if the webview can only render 'static' HTML? Would we then be able to use nashorn to render the AsciiDoc document to HTML using Asciidoctor.js? Would that work, or is it really needed to use MathJax in the webview because it does some SVG tricks or whatnot?

**Comment by mojavelinux** [comment]
Asciidoctor doesn't do anything to interpret stem expressions (aka math). We simply ensure that the expressions pass through unparsed and get wrapped with the appropriate delimiters so that MathJax can take over. So without MathJax, no math.

There are libraries that can do what MathJax can do, which we can use when creating the static HTML (i.e., server-side). But we'll cross that bridge if and when we determine we have to.

One solution to this problem is to use a JavaFX browser view (like AsciidocFX does) so that we get a real browser in the preview pane instead of whatever second-rate webview Java 6 comes with.

**Comment by bodiam** [comment]
I don't think JavaFX is an option. IntelliJ runs by default on a Java 6 version (at least, it does on a Mac, though IntelliJ 15 will change that a little). I think this makes it hard to run any JavaFX on it (http://stackoverflow.com/questions/13696061/will-java-6-latest-run-javafx-2-out-of-the-box) 

The JEditorPane, which is currently used, for sure doesn't support any Javascript.

**Comment by mojavelinux** [comment]
Understood.

**Comment by bodiam** [comment]
IntelliJ now runs on Java 8, so it might be possible. Also, the JetBrains Markdown plugin is doing a similar thing.

**Comment by sunsolve** [comment]
No this feature in latest release, any plan for this?

**Comment by bodiam** [comment]
Hi @sunsolve , this feature is not there yet, but if you're willing to give a go at it, that would be most appreciated!

**Comment by sunsolve** [comment]
Hi @bodiam ,I can solve this problem in a dirty way quickly, just appended a small snippet at the end of generated html string, then you can get the mathematical formula render in the preview panel

````
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  messageStyle: "none",
  tex2jax: {
    inlineMath: [["\\(", "\\)"]],
    displayMath: [["\\[", "\\]"]],
    ignoreClass: "nostem|nolatexmath"
  },
  asciimath2jax: {
    delimiters: [["\\$", "\\$"]],
    ignoreClass: "nostem|noasciimath"
  },
  TeX: { equationNumbers: { autoNumber: "none" } }
});
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.6.0/MathJax.js?config=TeX-MML-AM_HTMLorMML"></script>

````
AsciidocPreviewEditor.java

````
private void render() {
    LAZY_EXECUTOR.execute(new Runnable() {
      @Override
      public void run() {
      String math_script = "text string above ";
        try {
          if (!document.getText().equals(currentContent)) {
            currentContent = document.getText();

            String markup = asciidoc.get().render(currentContent);
            if (markup != null) {
              myPanel.setHtml(markup+math_script);
            }
          }

<img width="934" alt="screen shot 2017-02-15 at 20 10 23" src="https://cloud.githubusercontent.com/assets/10296416/22973924/d658620a-f3ba-11e6-89ca-8e598410e208.png">

I knew it was not a normal solution,but it can work now.

**Comment by mojavelinux** [comment]
Seems reasonable to do this. However, like the built-in HTML converter, we should only do it if the stem attribute is set on the document. See https://github.com/asciidoctor/asciidoctor/blob/9e3d8b43103527fb9b5428ff7b9f88c7256ac334/lib/asciidoctor/converter/html5.rb#L221-L242

**Comment by mkraft89** [comment]
Hi all,
is this feature available in the current release?

**Comment by ahus1** [comment]
No it's not. Apparently the development has stalled. I'm happy to accept a pull request to implement this. 

Recently a contributor added some icon fonts so there are examples on how to implement this. See #182 for details.

My minimum requirement: When we include MathJax, it should be an offline installation and no CDN solution, as it should work offline as well. If we make it work offline, there is no need to make the CDN configurable or to make it configurable at all. It will be on by default (plus maybe an auto detection if it is enable in the AsciiDoc document)

**Comment by mojavelinux** [comment]
It should respect the stem setting in the document. Other than that, :+1:

**Comment by ahus1** [comment]
First mathjax support landed in master branch thanks to @aplatanado!

For the moment there is no automatic detection if stem is active in the document; mathjax is enabled by default. 

@mojavelinux - I don't know yet how to detect if stem is set in for the document. Currently we render with header/footer false. Maybe you can give a hint? Thanks!

**Comment by ahus1** [comment]
@pantelis - you commented on the plugin's homepage that MathJax support was missing. Please watch this ticket to get updates on the MathJax support in the plugin.

**Comment by ahus1** [comment]
The 0.20.0 is now available as a preview from the Github releases page of this project: https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases
