### ISSUE TITLE
File preview renders partially offscreen when first opening a file

### ISSUE THREAD

**Issue by dwhitelf** [asciidoctor/asciidoctor-intellij-plugin#690]
## Observed vs. expected behavior

When first opening an adoc file, the file preview renders poorly. There is a large gap between the code half of the screen and the preview. This causes the preview to not display a portion of the file, as it renders in a space that falls outside of the IntelliJ window.

![image](https://user-images.githubusercontent.com/53910321/109329163-df439680-781f-11eb-9307-92adda7cbdb0.png)

Manipulating the IntelliJ window in any way (such as resizing the window, moving it around the screen, moving the window to a different monitor) causes the preview to update and render as expected:

![image](https://user-images.githubusercontent.com/53910321/109329271-fe422880-781f-11eb-92af-ee6152c38db7.png)

The preview should display in the split screen as in the second screenshot that happens after manipulating the window. I should not have to do anything to the window every time I open a new file.

## Steps to reproduce

This occurs when first opening any .adoc file.

## Environment

Plugin Version:  0.32.23

IntelliJ IDEA 2020.3.2 (Community Edition)
Build #IC-203.7148.57, built on January 25, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1957M
Cores: 8
Non-Bundled Plugins: org.asciidoctor.intellij.asciidoc

**Comment by dwhitelf** [comment]
I have two displays; the laptop screen is 1920x1080 resolution, and set at 125%.
An external monitor is also 1920x1080, set to 100%.

When I switched the laptop display to 100% instead, the issue resolved.

**Comment by ahus1** [comment]
I fixed this for pre-release 0.32.24. This will apply the workaround of re-sizing the preview automatically. The observed behavior would now match the expected behavior. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

Found an open issue at YouTrack, please consider voting: https://youtrack.jetbrains.com/issue/IDEA-246551

**Comment by ahus1** [comment]
just found that the workaround works only for EAP 2021.1, stay tuned for an update that targets 2020.3 as well.

**Comment by ahus1** [comment]
Pre-release 0.32.25 is available that supports this for 2020.3.2 as well. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment]
As I was able to reproduce the issue with two screens with different zoom level, I assume this fixes the issue. Please comment if it doesn't, and I'll re-open the issue. Happy AsciiDoc coding!
