### ISSUE TITLE
Line numbers incorrect when wrapping occurs

### ISSUE THREAD

**Issue by wimdeblauwe** [asciidoctor/asciidoctor-intellij-plugin#694]
## Observed vs. expected behavior

When using a `source` block with `linenums`, the preview does not show the correct line numbers if there is wrapping of lines in the preview.

## Steps to reproduce

Assume this source block:

```
[source,html,linenums,highlight=1..19|3|10|13..15|14]
----
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:th="http://www.thymeleaf.org"
      lang="en">
<head>
    <meta charset="UTF-8">
    <title>Taming Thymeleaf</title>
</head>
<body>
<h1 th:text="#{scientists.title}">Scientists</h1>
<div>
    <ul>
        <li th:each="scientist : ${scientists}">
            <span th:text="${scientist}"></span>
        </li>
    </ul>
</div>
</body>
</html>
----
```

When there is enough room, it is shown like this:

![image](https://user-images.githubusercontent.com/1115823/110026340-cdd32080-7d30-11eb-98df-638e91e1d22d.png)

if there is not enough room, it is shown like this:

![image](https://user-images.githubusercontent.com/1115823/110026416-e3e0e100-7d30-11eb-85dc-e2263b5e5cfb.png)

For example, the `<li>` is shown as if it is on line 16, but it is on line 13 in reality.

## Environment

Plugin Version: 0.32.16

IntelliJ Details: 
IntelliJ IDEA 2020.3.2 (Ultimate Edition)
Build #IU-203.7148.57, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1145.77 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 16
Non-Bundled Plugins: CheckStyle-IDEA, com.dubreuia, name.kropp.intellij.makefile, org.toml.lang, com.intellij.tailwindcss, org.jetbrains.kotlin, ru.adelf.idea.dotenv, PlantUML integration, org.asciidoctor.intellij.asciidoc

**Comment by ahus1** [comment]
Hi Wim, thanks for raising this issue. Whether or not the line numbers are displayed together with their line depends on the highlighter. The support depends on what Asciidoctor and the respective highlighter provides. 

A brief survey shows me that only the `prettify` highlighter supports this out of the box. 

The AsciiDoc IntelliJ plugin supports highlighters `rouge` and `coderay`. Unfortunately they both have the problem with the line numbers you see above. 

The workaround for this: adding "nowrap" to the listings adds a horizontal scroll bar. 

```
[source,html,linenums,highlight=1..19|3|10|13..15|14,options=nowrap]
...
```  

I suggest you raise this issue "upstream" with Asciidoctor first, and then maybe with the respective highlighter (I am not sure if the line numbers are part of Asciidoctor or the respective highlighter).  

Adding support for an additional highlighter in the AsciiDoc plugin for IntelliJ requires extra code in the plugin as the plugin uses inline rendering, and doesn't want to rely on external CDNs when rendering a preview. If you miss a specific highlighter that would solve your problem, please let me know so I can look into it.

**Comment by wimdeblauwe** [comment]
This was using the highlight.js highlighter as I was using asciidoctor-revealjs to create slides. Revealjs uses highlight.js by default. I created https://github.com/asciidoctor/asciidoctor/issues/3959 as upstream issue to futher investigate this.

**Comment by ahus1** [comment]
Reading the upstream issue I don't think there anything this plugin can do as of today. Therefore I close this issue.

If you discover any actions this plugin should follow up on, please comment here and I'll re-open this issue.
