### ISSUE TITLE
Support attributes in antora.yml

### ISSUE THREAD

**Issue by ysb33r** [asciidoctor/asciidoctor-intellij-plugin#701]
## Why the new feature should be added

There is a section in `antora.yml` where one can do

```
asciidoc:
    attributes:
        foo: bar
```

These attributes are global to the whole Antora component. 

## How the new feature should work

These attributes should be read and made available whilst rendering in IntelliJ.

See also: https://docs.antora.org/antora/2.3/component-attributes/

**Comment by ahus1** [comment]
Hi, the feature you suggest should be already working, at least for standard cases. I tried a simple example and adding an attribute to a component, and then previewing a rendered page - that worked for me.

If it is not working for you, could you please provide a minimal example project? Maybe the plugin misses a valid scenario. 
Thanks!

**Comment by ysb33r** [comment]
Try this:

```
asciidoc:
    attributes:
      curl: $ curl@
```

and then do 

```
[listing.terminal]
[subs=+attributes]
----
{curl}
----
```
Done with IntelliJ 2020.3 and plugin version 0.32.26

**Comment by ahus1** [comment]
I've created a small folder in an existing repo here where replacing works for me (tested with 2020.3 & 0.32.26), please let me know what is missing:
https://github.com/ahus1/asciidoctor-deepdive/tree/master/antora-sample

Tree view: 

![image](https://user-images.githubusercontent.com/3957921/111173457-f49e1c00-85a6-11eb-9864-9767c40326a5.png)

antora.yml: 

```
title: My Example
name: my-example
version: master
nav:
  - modules/ROOT/nav.adoc
asciidoc:
  attributes:
    curl: $ curl@
```

index.adoc:
```
= My start page

[listing.terminal]
[subs=+attributes]
----
{curl}
----
```

Rendered preview (as expected): 

![image](https://user-images.githubusercontent.com/3957921/111173676-231bf700-85a7-11eb-83a0-f7021e9796a7.png)

**Comment by ysb33r** [comment]
OK. I'm going to see if maybe there is some issue on my side.
