### ISSUE TITLE
Plug-in 0.32.23 (stable) to be upgraded to 0.32.26 (Pre-release).

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-intellij-plugin#702]
I have installed version 0.32.23 (latest release) of the Asciidoc plug-in. All subsequent releases are pre-releases, but now I see an Update message saying that I can upgrade to version 0.32.26 (a Pre-release version). This is wrong; the plug-in should stay at 0.32.23 and the update message should only be displayed when a new Latest Release version is available.

![image](https://user-images.githubusercontent.com/13682850/111164219-88231d00-85a6-11eb-9861-9fb094f39689.png)

See https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases

IntelliJ IDEA 2020.3.2 (Community Edition)
Build #IC-203.7148.57, built on January 26, 2021
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: Batch Scripts Support, CMD Support, com.robohorse.robopojogenerator, de.docs_as_co.intellij.plugin.diagramsnet, org.jetbrains.kotlin, io.ktor.intellij.plugin, PythonCore, org.asciidoctor.intellij.asciidoc

**Comment by ahus1** [comment]
Thanks for spotting this. I've promoted the pre-release 0.32.26 to a regular release on March 1st for the JetBrains Marketplace and forgot to update the GitHub releases.

GitHub releases is now updated; it's now a regular release on GitHub releases as well.
