### ISSUE TITLE
Support idprefix and idseparator in suggested values

### ISSUE THREAD

**Issue by sturtison** [asciidoctor/asciidoctor-intellij-plugin#703]
## Why the new feature should be added

When typing cross references <<anchorname>> to sections in the document, the plugin suggests sections it has found when `<<` is typed.

As is, the suggestions appear to not apply the settings from `antora.yml` for `idprefix` and `idseparator`.

For example, the plugin will suggest <<`_my_section_name` 
when `antora.yml`  contains  `idprefix: ''` and `idseparator: '-'`

## How the new feature should work

With an `antora.yml` file containing: `idprefix: ''` and `idseparator: '-'`

And asciidoc of:

```
== My Section Name
This section...

```

Typing `<<` should suggest `my-section-name`

Thanks for the plugin!

**Comment by ahus1** [comment]
Thanks for pointing out this missing feature. I implemented the change and it will be part of the next release. 

While you're waiting for this to be implemented, the same result can be achieved using an `.asciidoctorconfig` file like I do in my projects, see [here for an example](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/doc/.asciidoctorconfig) and [here for the docs](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctorconfig-file.html).

My thoughts for this: 
* the Antora playbook should contain all attributes that are necessary to render the output and that are common to all component - this includes `idprefix` and `idseparator` for me
* the Antora component descriptor should contain only component specific attributes, and attributes that change between component versions

These two leave a gap for rendering a preview: the playbook is usually in a separate repository form the components, therefore inaccessible when rendering the preview. So I place all attributes relevant for rendering the preview in `.asciidoctorconfig`.

One could could argue that the two attributes need to be known at component level to create automatic links; on the other hand I usually try to have explicit IDs for all sections that I reference to avoid me breaking links when changing section titles.

That being said, from the next release onwards the two attributes `idprefix` and `idseparator` will be picked up from the Antora component descriptor as well. I'll update this issue once a pre-release is available.

**Comment by ahus1** [comment]
Pre-Release 0.32.30 is available that includes these changes.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
