### ISSUE TITLE
Copy from preview

### ISSUE THREAD

**Issue by abelsromero** [asciidoctor/asciidoctor-intellij-plugin#705]
## Why the new feature should be added

Right now (at least on MacOS) you cannoy copy text from the preview. The shortcut does not work and there's no UI option.
This would be useful when you want to copy a command that on source is composed using attributes, for exemple `{build-command} && rm -rf build && ./gradlew distTar`.

## How the new feature should work

Would be nice for shortcuts to work, if not, maybe a UI options.

**Comment by ahus1** [comment]
Hi Abel, something like this has been discussed in issue #533.

Please check the version of your IDE and the plugin, and update this issue with the versions you tried this on MacOS. What shortcuts did you use?

**Comment by abelsromero** [comment]
Upgraded to 2020.3 and cmd+c work fine.
I've been reluctant to upgrade after latests changes but I guess resistance is futile 🤖
