### ISSUE TITLE
Reference anchor in a relative file such that it works on GitHub Wiki

### ISSUE THREAD

**Issue by PHPirates** [asciidoctor/asciidoctor-intellij-plugin#706]
## Observed vs. expected behavior

When we use a relative link to an anchor in a different file with `link:file-name#anchor[text]` then Asciidoctor says 'File doesn't resolve', but in fact in the GitHub wiki it works fine, so I would expect Asciidoctor to handle that also.

## Steps to reproduce

`Home.asciidoc`:
```
This file references link:other-file#other-anchor[this file].
```

`other-directory/other-file.asciidoc`:
```
Text.

[#other-anchor]
== Other anchor.
```

```
.
├── Home.asciidoc
└── other-directory
    └── other-file.asciidoc

1 directory, 2 files
```

Working example: https://github.com/PHPirates/latex-mwe/wiki
Not working Asciidoctor: 
![image](https://user-images.githubusercontent.com/15669080/112016696-3c83ec80-8b2d-11eb-8031-ffd0222909de.png)

## Environment

Plugin Version: see below

IntelliJ Details:
```
IntelliJ IDEA 2021.1 Beta (Ultimate Edition)
Build #IU-211.6556.6, built on March 17, 2021
IntelliJ IDEA EAP User
Expiration date: April 16, 2021
Runtime version: 11.0.10+9-b1341.20 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.7-arch1-1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry: ide.plugins.snapshot.on.unload.fail=true, ide.tooltip.initialDelay=1100
Non-Bundled Plugins: com.eclectide.intellij.whatthecommit (1.2), org.jetbrains.plugins.rest (211.6556.6), nl.rubensten.texifyidea (0.7.5-alpha.6), com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.11.0), org.asciidoctor.intellij.asciidoc (0.32.29)
Kotlin: 211-1.4.21-release-IJ6556.4
Current Desktop: XFCE
```

I have tried other ways of referencing, that either did not work for Asciidoctor or GitHub Wiki: see https://github.com/PHPirates/latex-mwe/wiki

#180 or #204 did not help me further here, nor did https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/editor.html

**Comment by ahus1** [comment]
In several places only the ".adoc" extension was supported when left out. The next release will look at the extension of the current file to determine the extension of files for links and xrefs. I'll update this issue once a pre-release is available.

**Comment by PHPirates** [comment]
Thanks, that seems to fix the extension issue, however there seems to be a subdirectory issue still:

`link:other-directory/other-file#other-anchor[does not work for GitHub]` while it works for Asciidoctor, but
`link:other-file#other-anchor[does not work for Asciidoctor]` but works for GitHub.

Do you know of something which works for both?
If not, is it in scope for Asciidoctor to provide support for this 'feature' of GitHub Wiki?

See https://stackoverflow.com/a/24237161/4126843

**Comment by ahus1** [comment]
Thanks for commenting, I have to admit I only half-read your issue. 

I can't comment on how subdirectories would work on GitHub wikis. This repo is "just" about the AsciiDoc plugin for IntelliJ. 

The behavior of GitHub regarding `link` is rather strange. Again, this is not the place to discuss how Asciidoctor could work in the future. This is repo is only about the AsciiDoc plugin for IntelliJ. 

The editor and validations of the AsciiDoc plugin for IntelliJ try to mimic the Asciidoctor behavior as best as possible and practical.

Defining the behavior of link and xref is something that should part of an AsciiDoc specification, and the working group at Eclipse is on its way to create a spec. Once there is a spec, implementations can align. While there is no spec, it is hard to align.

For the time being, you could fall back to a conditional attribute that would make it work for both GitHub and Asciidoctor. This example should keep the link-validation functionality of the plugin. Beware that adding to many attributes to a link might disable  navigation and validation.

```
ifndef::env-github[:suffix: .html]

link:sub{suffix}[alink]
```

On a side note: I found the GitHub wiki limited in several places, as it didn't allow for pull requests of non-repo owners. Therefore I switched to [Antora](https://antora.org/) at some point.

I suppose this is all I can do for now. If you don't have additional questions, please close this ticket (can open it again when there are new questions).

**Comment by PHPirates** [comment]
Yeah I think we can agree that it's a bug with GitHub Wiki, and is just part of the many other things that make GitHub Wiki limited. But so far it's good enough for us, and we will keep Antora in mind when we want something better, thanks for the suggestion!
At least it's convenient for us that anybody can edit the wiki without a pull request.

Thanks for the context, I am sometimes confused by the differences between the rendering in IntelliJ and on GitHub (example: they don't render a title above a code listing correctly), but I think those are mostly issues on the side of GitHub (not sure whether they use Gollum or whatever), apart from the references to other pages I am happy with editing the wiki using this plugin.
