### ISSUE TITLE
JCEF sudden high CPU usage

### ISSUE THREAD

**Issue by barspi** [asciidoctor/asciidoctor-intellij-plugin#711]
## Observed vs. expected behavior

Sometimes, I will hear the computer fans start to go wild, and I found a JCEF process consuming close to 100% CPU.

I kill the offending process and everything calms down. The killing of the JCEF process doesn't seem to produce any instability to the AsciiDoc plugin or IDEA itself.   Apparently new processes are respawned as needed.

I want to point out that I work on several .adoc files at once in separate tabs (all included from a single `master.adoc`).
Also, I keep a separate window in another monitor where I'm showing the full live `master.adoc`.  So there are several JCEF renderers in parallel, I guess.

Also, my document has a few plantuml and mermaid diagrams embedded, which are built with outside tools found on the path.

## Steps to reproduce

Not sure how to reproduce. Sometimes it happens more than once within the same day. Sometimes it doesn't happen at all.  Always working on the same document I've been working on for the last weeks.

## Environment

* macOS Mojave 10.14.6
* 32 gigs of RAM
* 6 cores
* 3 separate monitors
* loaded systems with lots of other apps, 3 or 4 browsers, etc

Plugin Version: 0.32.29

IntelliJ Details: 2020.3.3 Community Edition

I'm attaching a capture of the plugin's config

<img width="756" alt="Screen Shot 2021-03-29 at 11 08 16" src="https://user-images.githubusercontent.com/1316018/112849301-4f437780-907f-11eb-854b-c7309c88d411.png">

**Comment by ahus1** [comment]
Thanks for raising this issue. So far I've seen this issue twice in daily usage, and haven't been able to reproduce it yet. Other people seems to experience this as well with the JCEF preview of Markdown, see https://youtrack.jetbrains.com/issue/IDEA-262629.

So far I don't know about a way to remote debug JCEF. 

For the time being, could you please provide me with the logs via email? You find my email address in my GitHub profile. Working with very large documents could trigger a back-off mechanism if the preview doesn't render in in time. Let's see what the logs tell me.

**Comment by barspi** [comment]
I'll do it next time it happens

**Comment by ahus1** [comment]
There's been no update in the recent weeks on this, therefore I close it for now. Please comment here if this happens again and I'll re-open the issue.
