### ISSUE TITLE
Using continuation character in page attribute incorrectly flags spelling errors.

### ISSUE THREAD

**Issue by RayAtRadix** [asciidoctor/asciidoctor-intellij-plugin#712]
## Observed vs. expected behavior

Using the continuation character in an attribute causes the editor to flag a spelling mistake because it thinks the two words are joined together. For example:

```
= Hardware Requirements
:description: details the hardware requirements for the most  popular cloud platforms that can support \
the application
```

## Steps to reproduce

See screenshot

<img width="1274" alt="Screenshot 2021-03-30 at 16 09 17" src="https://user-images.githubusercontent.com/77050471/113012756-f94ffc00-9172-11eb-9800-5b9133825a52.png">

## Environment

MacBook Pro (13-inch, 2019, 16GB) running macOS Big Sur 11.2.3
Plugin Version: 0.32.29

WebStorm 2021.1 EAP
Build #WS-211.6693.17, built on March 25, 2021
WebStorm EAP User
Expiration date: April 24, 2021
Runtime version: 11.0.10+9-b1341.21 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins: com.fxiaoke.lizc8407 (2.0.0), com.jetbrains.plugins.code-notes-plugin (1.3), de.cmm.side_nodes (1.2), tv.twelvetone.intellij.plugins.intellivue (1.1.0), com.intellij.lang.jsgraphql (2.9.1), org.asciidoctor.intellij.asciidoc (0.32.29)

**Comment by RayAtRadix** [comment]
> Thanks for reporting this. Will be fixed in the next upcoming release. I will update this issue once a preview is available.
> 
> Actually the "description" attribute is the only attribute where I enabled spell- and grammar checking, as I assumed that other attributes rarely contain text that can be spell checked. What do you think: are there other well-known attributes that should be checked? I'm hesitant to activate it for all attributes.

I would probably check the title. I don't really there would be much of a need to check anything else.

**Comment by ahus1** [comment]
Thanks, will do.

**Comment by ahus1** [comment]
This is part of pre-release 0.32.32. The following attributes will be spell-checked: "description", "title", "doctitle", "navtitle", "reftext"

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by RayAtRadix** [comment]
Yep, fixed!
