### ISSUE TITLE
Document attribute :text-align: 

### ISSUE THREAD

**Issue by undesconocido** [asciidoctor/asciidoctor-intellij-plugin#713]
## Description

Hello!

I am learning to use asciidoc for some personal projects and I am very satisfied with it but there is one thing that bothers me a lot: text justification.

It seems there is a document attribute called `:text-align:` with a `left | right | center | justify` parameter that would allow, or so I understand, to justify all the paragraphs of the file. But neither in the preview nor in its export to html does this happen. I have also tried placing it below the chapter headings, to see if its effect was only contained there. It doesn't seem to work either.

The workaround I have found is to place `[.text-justify]` above each new paragraph. But it's a bit cumbersome. So I came to ask to see what I'm doing wrong or if it's really a limitation or a bug.

**Comment by mojavelinux** [comment]
The text-align attribute is unique to Asciidoctor PDF. It's a shorthand override to control the base_align key in the theme. It is documented here: https://github.com/asciidoctor/asciidoctor-pdf/blob/v1.5.x/docs/theming-guide.adoc#theme-related-document-attributes It's not an attribute that would effect the HTML output, and thus not the preview. See

**Comment by ahus1** [comment]
As Dan's answer seems to be exhaustive here and this issue has been idle for more than a week, I close this issue. 

The plugin's in-line-documentation for attributes marks this as "pdf converter only".

Please comment if this needs further improvements, and I'll re-open this issue.
