### ISSUE TITLE
Revision Information not render

### ISSUE THREAD

**Issue by pOH7** [asciidoctor/asciidoctor-intellij-plugin#720]
## Observed vs. expected behavior

content:
```
= The Intrepid Chronicles
Kismet Lee
2.9, October 31, 2021: Fall incarnation

```

Observed preview:
![image](https://user-images.githubusercontent.com/2225767/114169117-bc9ab680-9963-11eb-9658-44f8aee58b31.png)

expected preview:
![image](https://user-images.githubusercontent.com/2225767/114169233-df2ccf80-9963-11eb-8ec3-de012a70d88e.png)

## Steps to reproduce

![image](https://user-images.githubusercontent.com/2225767/114169478-36cb3b00-9964-11eb-8dcf-7ac82886220a.png)

## Environment

Plugin Version: 0.32.35

IntelliJ Details: IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021

**Comment by ahus1** [comment]
Thanks for raising this issue. Unfortunately Asciidoctor, the project this plugin builds upon, doesn't render this information when Asciidoctor is called in embedded mode. 
This issue has been discussed upstream, see https://github.com/asciidoctor/asciidoctor/issues/2408

As a workaround: To see this information, create a full HTML file using the "HTML" action from the button bar. 

A workaround in the plugin could be possible, but it would need work and ongoing maintenance. 
As you opened this as a bug, could please classify how this affects you: Is it a minor nuisance or does it break your workflow?

**Comment by pOH7** [comment]
In fact, I want to see revision information in PDF, not in HTML. Because I often share documents with the PDF format.

**Comment by ahus1** [comment]
When you're looking for PDFs, the embedded Asciidoctor PDF will print the version and author only if you switch to document type "book" (via setting in the plugin's properties) or set the attribute "title-page" in the document. 

The author and version will only show on the title page; this will always be the first page, all content follows on another page. 

I'm not sure if that works for you. 

I see two more variants on how to add version number of author name to the output file: you could ...
* repeat the author and version in the document, for example: `{author} {revnumber}`
* configure a template for asciidoctor-pdf that repeats the information always in the header or the footer

Does that work for you?

**Comment by pOH7** [comment]
Thanks, I will try.
