### ISSUE TITLE
"Anchor doesn't resolve" for Antora xref page fragment in nested include

### ISSUE THREAD

**Issue by aisbergde** [asciidoctor/asciidoctor-intellij-plugin#737]
## Observed vs. expected behavior

In Antora I use xref to fragments in documents in other modules, for example

```
xref:sqldb:uspgenerator.GeneratorUspStep.adoc#column-Statement[uspgenerator.GeneratorUspStep.Statement]
```

They work in Antora, but they are marked by the plugin as error:

![image](https://user-images.githubusercontent.com/9020187/116232055-e886ac00-a759-11eb-8616-3b54045c2817.png)

The link to pages is resolved:

```
xref:sqldb:uspgenerator.GeneratorUspStep.adoc[]
```

I am not sure if this is a general issue of if it is related to fact, that I use to deeply nested includes. this is the include structure

partials like sqldb:uspgenerator.GeneratorUspStep.adoc contains the fragments like column-Statement

```
// tag::AntoraColumnDetails[]

//other columns

[[column-Statement]]
=== Statement

[cols="d,m,m,m,m,d"]
|===
|
|Statement
|nvarchar(max)
|NULL
|
|
|===

//other columns

// end::AntoraColumnDetails[]
```

partials are addressed by template partial (sqldb:partial$template/master-page-5.adoc) partials containing

```
ifdef::ExistsProperty--Columns[]

== Column Details

include::partial${docname}.adoc[tag=AntoraColumnDetails]

endif::ExistsProperty--Columns[]

```

these templates are used in the final page
sqldb:uspgenerator.GeneratorUspStep.adoc

```
include::partial$template/master-page-5.adoc[]
```

and finally, the page is referenced in another page which is in another repository / in another module:

```
xref:sqldb:uspgenerator.GeneratorUspStep.adoc#column-Statement[uspgenerator.GeneratorUspStep.Statement]
```
## Steps to reproduce

the repositories are available on github:

* final repository where I get the error: https://github.com/DataHandwerk/DataHandwerk-docs
* source repository containing the code per entity and column: https://github.com/DataHandwerk/sqldb-docs

I added both repositories as modules in one IntelliJ project

## Environment

Plugin Version: 0.32.37

IntelliJ Details: ____

IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Licensed to DataHandwerk-toolkit-mssql / Germo Goertz
Subscription is active until February 28, 2022.
For non-commercial open source development only.
Runtime version: 11.0.10+9-b1341.35 amd64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 5000M
Cores: 4
Non-Bundled Plugins: com.intellij.plugins.vscodekeymap (211.4961.30), org.asciidoctor.intellij.asciidoc (0.32.37)
Kotlin: 211-1.4.32-release-IJ6693.72

**Comment by ahus1** [comment]
Thanks for reporting this. 

I looked into it, and found that the internal resolver doesn't resolve the attribute `docname` in a nested include correctly (see `include::partial${docname}.adoc[tag=existing_properties]`). 

It should either correctly resolve it, or not report a problem when it hasn't managed to resolve all includes.  

I'll revisit this.

**Comment by ahus1** [comment]
There is now pre-release 0.32.40 that will resolve the `docname` attribute in includes as expected. It also fixes situations where the attribute was filled with the wrong value if the file name contained more than one dot. 

When clicking on `column-Statement` inside `xref:sqldb:uspgenerator.GeneratorUspStep.adoc#column-Statement[uspgenerator.GeneratorUspStep.Statement]`, this will take you the the correct section heading in the editor.

Opening pages like `uspgenerator.GeneratorUsp.adoc` will now resolve all includes and diagrams correctly and show a nice preview with PlantUML diagrams.

Please leave a feedback comment in this ticket if it now works for you as expected. 

I see that the plugin does not resolve page titles for Antora `xrefs:[]` macros if these titles are in nested includes. Please open another issue for that. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by aisbergde** [comment]
So schnell kann man gar nicht lesen, wie hier issues gefixt werden! Top! 

I can test only this weekend. The next few days I am in a new on-site project and I will travel without my notebook.

**Comment by ahus1** [comment]
Take your time, no need to rush. All the best for your travels.

**Comment by aisbergde** [comment]
the issue is solved
