### ISSUE TITLE
Asciidoc indexing very slow / blocking IDE starting with release 0.32.37

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-intellij-plugin#742]
When I clone a very large Git repo, with a complex folder structure and just under 100,000 adoc files, then if Asciidoc plugin v0.32.37 or later is installed and enabled, IntelliJ's indexing takes many hours to complete. The IntelliJ UI also locks up, so I'm not able to click on any options. 

If the Asciidoc plug-in is disabled before starting the Git clone operation, then IntelliJ's indexing completes in minutes.    I do not experience this issue if version 0.32.36 of the plugin is installed and enabled. The latest version 0.32.41 of the plugin exhibits the same slow indexing behaviour.  It seems that an unresolved indexing issue was introduced to the code base starting with version 0.32.37.

IntelliJ IDEA 2020.3.4 (Community Edition)
Build #IC-203.8084.24, built on April 27, 2021
Runtime version: 11.0.10+8-b1145.96 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2002M
Cores: 4
Non-Bundled Plugins: Batch Scripts Support, CMD Support, de.docs_as_co.intellij.plugin.diagramsnet, PythonCore, org.jetbrains.kotlin, org.asciidoctor.intellij.asciidoc

**Comment by ahus1** [comment]
I'm sorry to hear that. Version 0.32.37 contained an update on parsing line comments, this was the only change I would connect to performance problems in indexing. 

I'm starting to prepare a pre-release. 

I assume that there is no public repository for me to test this with?

While I'm doing this, could you please collect some profiling information: 
* Step one: "Help | Diagnostic Tools | Activity Monitor" -> This should report the plugin and a package name. Please provide a copy / screenshot. If it shows "Plugin AsciiDoc: org.asciidoc.intellij.lexer", I'm on the right track.
* Step two: Details CPU profiling information: "Help | Diagnostic Tools | Start CPU Usage Profiling". Let it capture some information for a minute or so, then choose "Help | Diagnostic Tools | Stop CPU Usage Profiling". Please send the file to me by email (you'll find my email address in my GitHub profile).

**Comment by ahus1** [comment]
I releases pre-release 0.32.42 that contains a fix. Please have a look if this resolves the issue. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

If it doesn't resolve it, please do the following:
Reading the issue again, I read "The IntelliJ UI also locks up, so I'm not able to click on any options". 
Capturing a thread dump as described below should still be possible from the command line. This should be able to show me where the program blocks.

To gather the thread dump information, please do the following: 
* start IntelliJ
* use your process manager to find the process ID of idea64.exe
* find the file jstack.exe that is part of the JRE installed by the IntelliJ IDEA
* run "jstack.exe PID >> threaddump.txt", where PID is the process ID.
* repeat the command above 3-4 times within a 10-15 seconds time frame to capture different states of the indexing process 
* post the contents of the threaddump.txt files here or send them to me via email.

**Comment by wfouche** [comment]
@ahus1, thanks for the quick response.  

0.32.42 did not resolve the issue, so I created a few thread dump output files.

[output1.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/6407362/output1.txt)

[output2.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/6407363/output2.txt)

[output3.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/6407368/output3.txt)

[output4.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/6407370/output4.txt)

**Comment by ahus1** [comment]
Thank you for the files. They show that it is running in the lexer, and it seems to be related to TODO indexing. Let's see if I can figure out what's happening there.

**Comment by wfouche** [comment]
I'm happy to report that 0.32.43 resolves the issue!  Thanks!!  No more UI lockups.

**Comment by ahus1** [comment]
Thank you for your test, I'm relieved! The next upcoming release 0.32.44 will include a code snippet to detect these kinds of loops and will report an exception instead of locking the UI.

**Comment by ahus1** [comment]
The pre-release 0.32.44 has been published. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
