### ISSUE TITLE
Plugin freezes the IntelliJ IDEA

### ISSUE THREAD

**Issue by OljaKli** [asciidoctor/asciidoctor-intellij-plugin#743]
IDEA gets completely frozen.
More details: 
https://youtrack.jetbrains.com/issue/IDEA-268164

<img width="914" alt="image" src="https://user-images.githubusercontent.com/7487853/116869887-3dbf3380-ac1a-11eb-9d71-683c2d9b4fb1.png">

## Environment
IntelliJ IDEA 2021.1.1 Preview
Plugin Version: 0.32.41

**Comment by ahus1** [comment]
Thanks for reporting this. This has already been reported as part of #742. 

This fix has been released in 0.32.43. Please update.

**Comment by OljaKli** [comment]
Thank you for the prompt update!
