### ISSUE TITLE
image:: doesn't resolve right in editor, however it renders fine

### ISSUE THREAD

**Issue by barspi** [asciidoctor/asciidoctor-intellij-plugin#746]
## Observed vs. expected behavior

In IDEA AsciiDoc config, I configure the `imagesdir` custom attribute with the absolute path to the images, as shown here:

<img width="562" alt="Screen Shot 2021-05-04 at 17 52 43" src="https://user-images.githubusercontent.com/1316018/117068498-bc42d080-ad01-11eb-83bd-f06798ada0d1.png">

If I include an image with `image::` and give just the file name, it will tell me it can't resolve. If I give it the relative path from the `.adoc` file I'm editing, it doesn't complain.  

<img width="512" alt="Screen Shot 2021-05-04 at 18 02 36" src="https://user-images.githubusercontent.com/1316018/117069945-7e46ac00-ad03-11eb-8091-b0c67d0d4579.png">

However, in **both** cases, as shown above, it really resolves fine.  
It's just in the first case that the text is underlined as not resolving.

## Steps to reproduce

Create a config attribute called  `imagesdir` in the plugin's config screen, with absolute path to images.
Add an image to it. Test it both ways as in the picture above.

## Environment

Plugin Version:  0.32.28  (I think)

IntelliJ Details: IDEA 2020.3.3 on macOS

**Comment by ahus1** [comment]
Thanks for reporting this. It seems that the validation in the editor is not picking up the attributes in the config. This ticket will fix this. 

As an alternative to the plugin's GUI dialog configuration, there is the option to create a configuration file called _.asciidoctorconfig_. While the configuration in the GUI is global, the _.asciidoctorconfig_ is project specific (even sub-tree specific).
Have a look what this can do for you: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctorconfig-file.html

There are plans to make this feature more discoverable, see #740. 

Again: The editor should use the attributes in the GUI config dialog as well when validating. This ticket will fix this.

**Comment by ahus1** [comment]
This will be fixed in the next upcoming release. I'll update this issue once a pre-release is available.

**Comment by barspi** [comment]
Thanks! That was quick :-)
Thanks cor the `.asciidoctorconfig` too. Didn't know about that.

**Comment by ahus1** [comment]
I contribute my time on a "as time permits" and "supporting contributors and fixing bugs & annoying edge cases first" policy. 

Helping hands are always welcome.

**Comment by ahus1** [comment]
The pre-release 0.32.44 has been published that includes the fix.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
