### ISSUE TITLE
False positive code inspection result in unordered list

### ISSUE THREAD

**Issue by holgerbrandl** [asciidoctor/asciidoctor-intellij-plugin#747]
Great plugin, thanks for supporting & developing it!

**Observed**: It displays a false positive warning at the beginning of unordered list items:
![image](https://user-images.githubusercontent.com/200952/117100558-517ead00-ad74-11eb-9cfb-a707febd858f.png)

**Expected**: According to ascidoc spec https://docs.asciidoctor.org/asciidoc/latest/lists/unordered/ unordered lists are of the form
```
* foo
* bar
```
and the plugin should not display a warning here.

Used version: 0.32.43 with Intellij 2021.1.1

**Comment by ahus1** [comment]
Thanks for reporting this. Yes, the spell/grammar check should be tuned not to report this as a problem. Probably the adapter AsciiDocGrazieLanguageSupport should skip that blank.

**Comment by holgerbrandl** [comment]
I should have read the inspection warning more carefully. It's provided by the LanguageTool plugin

![image](https://user-images.githubusercontent.com/200952/117104045-bdb0df00-ad7b-11eb-94d7-3ee75cbb62af.png)

So I guess this somehow relates to me using https://plugins.jetbrains.com/plugin/12175-grazie as well. Interestingly, I do not see the same false-positive in markdown documents.

**Comment by ahus1** [comment]
The AsciiDoc plugin has an adapter that passes the data on to the Grazie plugin (the class named above). So this should be fixed on the AsciiDoc plugin's side.

**Comment by ahus1** [comment]
I've fixed this for the next upcoming release. I'll update this issue once a pre-release is available.

**Comment by holgerbrandl** [comment]
Awesome, thanks for the great support.

**Comment by ahus1** [comment]
The pre-release 0.32.44 has been published that includes the fix.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
