### ISSUE TITLE
Footnote numbering error in headers

### ISSUE THREAD

**Issue by claudiociardelli** [asciidoctor/asciidoctor-intellij-plugin#750]
## Description

More of a question than an issue for the moment, as I am not sure this is a Asciidoctor plugin issue. Maybe that is how asciidoctor works.

I am trying to add a footnote on a header. The footnote link appears but it is numbered 1 instead of the expcted number (based on the position of the header in the document).

This appears incorrectly in the IntelliJ IDE Preview tool AND in the generated PDF.

I found an issue referring to this in the Asciidoctor project's github repository. Now that issue mentions a fix for this in version 2.0 of asciidoctor. 

https://github.com/asciidoctor/asciidoctor/issues/2903

Looking at the build log in IntelliJ I wonder if the plugin uses Asciidoctor 1.5.3 as I saw "Downloading from central: https://repo.maven.apache.org/maven2/org/asciidoctor/asciidoctorj-pdf/1.5.3/asciidoctorj-pdf-1.5.3.jar" in the logs.

**Comment by ahus1** [comment]
The plugin is using Asciidoctor 2. The download you see is the dependency for creating PDFs called "Asciidoctor PDF". Both Asciidoctor and Asciidoctor PDF have Java variants, and are called AsciidoctorJ and AsciidoctorJ PDF respectively. 

To retrieve the version of Asciidoctor used in a rendering, I suggest printing the attribute "{asciidoctor-version}". The latest version of the IntelliJ AsciiDoc plugin uses Asciidoctor 2.0.14.

The issue you reference is still open. It describes a workaround to add IDs. Did you try that? Your question didn't include an example snippet or plugin version. 

Given the plugin version 0.32.43 that embeds Asciidoctor 2.0.14 and the following example snippet with IDs:

```
== H2

Para1.footnote:[fn #1]

[[h3,H3]]
=== H3footnote:[fn #2]

Para2.footnote:[fn #3]
```

I receive the following preview:

![image](https://user-images.githubusercontent.com/3957921/117411472-e10e9200-af13-11eb-83e3-34bcef88cc4d.png)

and the following PDF:   

![image](https://user-images.githubusercontent.com/3957921/117411577-026f7e00-af14-11eb-9f68-542b9ed9d95f.png)

Please let me know if this works for you, or provide a sample to show what is not working for you (together with the plugin version you're using).

**Comment by ahus1** [comment]
There hasn't been an update for the last two weeks, therefore I close it. If there are further questions, please comment here and I'll re-open the issue.
