### ISSUE TITLE
How to show the admonitions icon

### ISSUE THREAD

**Issue by jaune162** [asciidoctor/asciidoctor-intellij-plugin#754]
## Description

![image](https://user-images.githubusercontent.com/10142624/118356495-1700e580-b5a8-11eb-94aa-0092a48ed841.png)

It dos not show the admonitions icon. Just show a text.

Is there need some config? I have no config file in my project.

**Comment by ahus1** [comment]
Hi - yes, a config is necessary to show admonitions icons. Once you add `:icons: font` the icons will show. 

You can add the attribute to the document (as shown below), configure it in the plugin's settings, or add [an _.asciidoctorconfig_ configuration file](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctorconfig-file.html).


The following snippet

```
:icons: font

[IMPORTANT]
.Feeding the Werewolves
====
While werewolves are hardy community members, keep in mind the following dietary concerns:

. They are allergic to cinnamon.
. More than two glasses of orange juice in 24 hours makes them howl in harmony with alarms and sirens.
. Celery makes them sad.
====

```

will show

![image](https://user-images.githubusercontent.com/3957921/118357023-33852980-b578-11eb-8a28-be9b6412158d.png)

Please let me know if this works for you.

**Comment by jaune162** [comment]
It's works. Thanks very much!!!
