### ISSUE TITLE
Artefact on IntelliJ background canvas

### ISSUE THREAD

**Issue by ascheman** [asciidoctor/asciidoctor-intellij-plugin#761]
## Observed vs. expected behavior

The Plugin could not render an embedded PlantUML diagram and issued an error message to the UI (extended screenshot with personal/client information communicated directly to @ahus1):

![image](https://user-images.githubusercontent.com/456000/119221796-52903800-baf1-11eb-8ae8-d1f89c69c09d.png)

For some reason the error left an artefact on the background canvas of IntelliJ which overloaded parts of other windows.

## Steps to reproduce

It is not completely clear to me what led to this behaviour, since several conditions were changed before experiencing the problem.

* I was setting up a new IntelliJ instance (either version upgrade, or switch to new Laptop with restore from time machine), or new plugin version: I had to download current asciidoc diagram library (which is no longer implicitly integrated with the plugin for some time now).
* I was creating a new embedded PlantUML like this

```adoc
[plantuml, tst, svg]
----
@startuml

@enduml
----
```

## Environment

Plugin Version: 0.32.48

IntelliJ IDEA 2021.1.1 (Ultimate Edition)
Build #IU-211.7142.45, built on April 30, 2021
Licensed to Gerd Aschemann
Subscription is active until January 10, 2022.
Runtime version: 11.0.10+9-b1341.41 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3
Jenkins Plugin 0.13.11-2020.3
GC: G1 Young Generation, G1 Old Generation
Memory: 6120M
Cores: 16
Registry: ide.balloon.shadow.size=0, ide.images.show.chessboard=true
Non-Bundled Plugins: CMD Support (1.0.5), Key Promoter X (2021.1.1), SnakeYAML plugin (1.17.0), claims.bold.intellij.avro (0.3.1), codes.rudolph.idea.cfg (0.3.1), com.alayouni.ansiHighlight (1.2.4), com.andrewbrookins.wrap_to_column (1.4.0), com.github.b3er.idea.plugins.arc.browser (0.23), com.intellij.apacheConfig (211.6693.108), com.intellij.ideolog (203.0.27.0), com.jetbrains.ChooseRuntime (1.2), com.jetbrains.plugins.ini4idea (211.6693.44), com.webschik.doT (1.5.4), net.seesharpsoft.intellij.plugins.csv (2.16.3), net.vektah.codeglance (1.5.4), org.intellij.plugins.hcl (0.7.10), org.jetbrains.plugins.go-template (211.6693.44), com.codestream.jetbrains-codestream (11.0.6+146), com.github.novotnyr.gitlab-quickmr-idea-plugin (21), mobi.hsz.idea.gitignore (4.1.0), name.kropp.intellij.makefile (211.6693.108), org.jetbrains.plugins.vagrant (211.6693.111), AWSCloudFormation (211.6693.108), com.intellij.lang.puppet (211.6693.44), com.theodo.serverless.plugin.serverless-plugin (1.3.0), ir.msdehghan.plugins.ansible (0.92), ru.sadv1r.ansible-vault-editor-idea-plugin (1.12), org.logtalk (1.0.15), org.mayevskiy.intellij.sonar (2.9.9), CheckStyle-IDEA (5.52.0), CopyRestUrl (1.5), com.intellij.kubernetes (211.7142.13), Error-prone plugin (211.7142.13), GrepConsole (11.9.211.6086.0), Groovy Console Plugin (0.1.5), Jenkins Control Plugin (0.13.11-2020.3), de.docksnet.puml.syntaxchecker (0.2.0), de.kontext_e.idea.plugins.jqa (2.0), io.thundra.debugger (1.3), org.sonarlint.idea (4.16.0.31683), com.neueda4j.intellij.plugin.cypher (3.0.3), com.perl5 (2021.1), com.jetbrains.plugins.jade (211.6693.65), Dart (211.7233), org.jetbrains.plugins.vue (211.7142.13), org.jetbrains.kotlin (211-1.5.0-release-759-IJ6693.72), org.mapstruct.intellij (1.2.4), Osmorc (211.6693.65), org.intellij.scala (2021.1.20), com.jetbrains.php (211.7142.45), com.intellij.phing (211.6693.44), org.jetbrains.plugins.ruby (211.7142.36), PlantUML integration (5.3.0), Pythonid (211.7142.45), com.intellij.selenium (211.7036.8), org.asciidoctor.intellij.asciidoc (0.32.48), org.jetbrains.plugins.go (211.7142.36), ru.adelf.idea.dotenv (2021.1)
Kotlin: 211-1.5.0-release-759-IJ6693.72

**Comment by ahus1** [comment]
Thanks for reporting this. I already analyzed the issue where an input field was rendered in the preview. The next version will escape content in the error message; this will provide a better readable error message in the preview when PlantUML rendering fails. 

To analyze the preview overlay issue that was left behind, could you please do the following: 
* Go to "Help | Show log in Explorer" (or similar menu entry on macOS
* Review the log file for Exceptions in the time frame. Maybe maybe the code bailed out with an exception and left the preview open

You can share log contents with me by email if you don't want to share your logs in public. Thanks!

**Comment by ascheman** [comment]
Log from last Friday sent by private mail

**Comment by ahus1** [comment]
Pre-release 0.32.49 is available that includes improvements and a potential fix: 

* the error message will show nicely in the preview when there is a problem with the PlantUML diagram
* when there is a (well known) PlantUML syntax error, there will be no log entry in the IDE's log file
* it will less frequently trigger "disposal of preview", this might stabilize it as well

Please let me know if this helps. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment]
The regular release 0.32.50 is available that includes this fix, therefore I close this issue. If the issue persists, please comment here and I'll re-open the issue.
