### ISSUE TITLE
What is this Preview pop-up called and how do I get rid of it?

### ISSUE THREAD

**Issue by nancym** [asciidoctor/asciidoctor-intellij-plugin#762]
I'm new to IntelliJ IDEA and this AsciiDoc plugin, which seems great so far, and have a newbie question that can be interpreted as a suggestion for improving the docs. What is the following pop-up called and how do I set things up so that I never see it?

![image](https://user-images.githubusercontent.com/161490/119383542-4da9c080-bc78-11eb-8c01-eb120271fa62.png)

I preview all my AsciiDoc in the Hugo server, via `hugo server` and never want to preview inside IntelliJ.

Thanks!

**Comment by ahus1** [comment]
Hi @nancym, there is a setting "Web Browsers" to configure this (see screenshot below):
* uncheck the browsers you don't want to see to make the list of browsers shorter
* uncheck "Show browser popup in the editor ... For HTML files" to disable it completely (not only for AsciiDoc content, but also for HTML files)

Is this what you've been looking for? 

Where would you like to see this documented? I wouldn't mind a pull request, all docs are in this repo in the _doc_ folder :-)

![image](https://user-images.githubusercontent.com/3957921/119403375-85e3ea00-bcde-11eb-9818-f5afdfc610d9.png)

**Comment by ahus1** [comment]
I haven't received a feedback for about two weeks sind my latest comment, therefore I assume this is solved. 

If the issue persists, please comment and I'll re-open the issue.
