### ISSUE TITLE
typo in antora.yml may cause NPE

### ISSUE THREAD

**Issue by danhaywood** [asciidoctor/asciidoctor-intellij-plugin#770]
the following error:

![image](https://user-images.githubusercontent.com/1031625/120471996-50ee2c00-c39d-11eb-8dea-c74ade1f71ae.png)

... I think may have been responsible for NPEs, and for not providing intellisense on xref: prompts.

(see also automatic bug report submitted via plugin a few minutes ago --- but I think this might have been the underlying problem).

**Comment by ahus1** [comment]
Will be fixed in upcoming release. Thanks for reporting this!
