### ISSUE TITLE
Attributes in playbooks should be available for rendering the preview and auto-complete

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#776]
## Why the new feature should be added

Currently the plugin 
* picks up AsciiDoc attributes from component descriptors. 
* doesn't pick up attributes from a Antora playbook. 

Picking up attributes from a playbook would be useful, as a playbook would usually contain global attributes that apply to all components that a user wouldn't want to repeat in each component. 

This was first suggested by @Grolribasi in the Antora chat.

## How the new feature should work

In order for this to work, the playbook needs to be:
* either in the same Git repository [not the standard case from my point of view], or 
* the user must create a multi-module project in IntelliJ that contains multiple Git repositories (see #734)

The plugin would pick up all AsciiDoc attributes from a YAML file that has both "antora" and "playbook" in its name. 

An attribute would be used for the preview if an attribute is defined in exactly one of the playbooks, or if the value of the attribute is the same in all playbooks.

**Comment by ahus1** [comment]
This will be supported in the next pre-release of the plugin. I'll update this issue once a pre-release is available.

**Comment by ahus1** [comment]
Pre-release 0.34.2 is now available that includes this change. I made changes in several places, I hope these changes didn't break anything else. Please give it a try and comment here with your findings.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by Grolribasi** [comment]
I'll try it out and report back!

**Comment by Grolribasi** [comment]
I have updated the plugin from the IntelliJ AsciiDoc EAP repository, restarted IntelliJ.
There was an error upon startup, I have reported it. Error report with ID 36f85a526ba148e48c1cda55808d1db1
Then I proceeded to add a new module with my playbook. The module is listed, I can see it in the IDE, but I don't see the attributes from the playbook in the preview. I guess I did something wrong, but I don't know what.

IntelliJ has also updated is that matters:
IntelliJ IDEA 2021.2.2 (Community Edition)
Build #IC-212.5284.40, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2044M
Cores: 8
Non-Bundled Plugins: com.github.jk1.ytplugin (1.2.9), org.asciidoctor.intellij.asciidoc (0.35.1)
Kotlin: 212-1.5.30-release-409-IJ4638.7

**Comment by ahus1** [comment]
Antora playbooks are picked up by name: they should end with ".yml" and need to contain both "antora" and "playbook" in their name. What's the name of your playbook? 

Is the playbook in the same IntelliJ project like the components? If they are in different Git repositories, you'll need to create a multi-module project. See https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/multimodule.html

**Comment by ahus1** [comment]
For the exception you reported, I created issue #864. It is unrelated to this change. It shouldn't prevent picking up the attributes from your playbook.

**Comment by ahus1** [comment]
Let me double check for the attributes, something seems to be broken...

**Comment by ahus1** [comment]
I found that my previous commit implemented only parts of this feature. With pre-release 0.35.2 this should now be fixed. 

Please give this new pre-release a try. Any Antora playbook should end with ".yml" and need to contain both "antora" and "playbook" in their name. If this convention doesn't work for you, please let me know. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by Grolribasi** [comment]
And another error occured. Error report with ID efcd9b253a404b57bdcc77bd64b5e024

**Comment by Grolribasi** [comment]
Ok, this is now working. The note that `Any Antora playbook should end with ".yml" and need to contain both "antora" and "playbook" in their name.` was crucial.

**Comment by ahus1** [comment]
Thanks for testing it. I didn't come up with a better solution yet to determine what YAML file is a playbook, and which is not. I see that Antora's examples use `antora-playbook.yml`, still there is the need to have multiple playbooks around.

What name did you choose for your playbook?

**Comment by mojavelinux** [comment]
>
> Originally we designed Antora to give people flexibility to name playbooks
anything because we weren't sure what to call it then. I think it makes
sense to standardize on the antora-playbook.yml suffix or antora-playbook-
prefix, so I like what you have done here.

**Comment by Grolribasi** [comment]
> What name did you choose for your playbook?

Just `antora-playbook.yml`.

**Comment by ahus1** [comment]
Alright, as this works now (and as I've added this description to the plugin's docs as well), I close this issue.

If there is anything else that needs to be taken care of, please let me know. 

Happy AsciiDoc-ing! ❤️
