### ISSUE TITLE
PDF Converter should not include passthrough html

### ISSUE THREAD

**Issue by RayOffiah** [asciidoctor/asciidoctor-intellij-plugin#777]
## Observed vs. expected behavior

I have an AsciiDoc document that has a stylesheet attached inside a passthrough html block:

```
++++
<style>

// Style stuff
</style>

++++
```

When I press the button to convert to a PDF, the resulting document has the passthrough html included in the PDF file.

I don't know if this is possible, but I think the passthrough HTML should be stripped out.

## Steps to reproduce

Create an AsciiDoc file.

Add a pass through block with some HTML.

Press the button that for converting to PDF:

<img width="352" alt="Screenshot 2021-06-07 at 11 52 58" src="https://user-images.githubusercontent.com/77050471/121004880-19a9c180-c787-11eb-8377-a125baae734b.png">

The resulting document will have the passthrough stuff included.

## Environment

Plugin Version: 0.32.55

IntelliJ Details: 

WebStorm 2021.2 EAP
Build #WS-212.3724.2, built on June 1, 2021
WebStorm EAP User
Expiration date: July 1, 2021
Runtime version: 11.0.11+9-b1481.1 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Non-Bundled Plugins: com.intellij.properties (212.3724.3), de.cmm.side_nodes (1.2), name.kropp.intellij.makefile (212.3724.3), org.toml.lang (0.2.147.3871-211), com.intellij.lang.jsgraphql (2.9.1), izhangzhihao.rainbow.brackets (6.17), org.asciidoctor.intellij.asciidoc (0.32.55), org.rust.lang (0.3.146.3826-211), com.github.shiraji.yaemoji (1.0.7)

**Comment by RayOffiah** [comment]
I should point out that there are other ways to generate the PDF, so it's not really a priority. Just thought I'd mention it.

**Comment by mojavelinux** [comment]
This is standard behavior for the PDF converter. To exclude it, you need to use an ifndef.

```
ifndef::backend-pdf[]
++++
passthrough content
++++
endif::[]
```

**Comment by RayOffiah** [comment]
This reply came back so fast, I literally jumped.

I'll withdraw it.
