### ISSUE TITLE
Disable Antora support for files ignored by Antora

### ISSUE THREAD

**Issue by Grolribasi** [asciidoctor/asciidoctor-intellij-plugin#797]
## Why the new feature should be added

1. According to Antora [documentation](https://docs.antora.org/antora/2.3/standard-directories/#hidden-files) Antora ignores any files stored in hierarchy that begin with a dot (.). If there is a file that starts with a dot, it will be ignored by Antora and won't be published.
   
1. Antora has nav files that have the following structure:
   ```
   .Nav title
   * xref:Annotation.adoc[Annotation]
   * xref:Introduction.adoc[Introduction]
   ** xref:Scope.adoc[Scope]
   ```
   
1. I've made a copy of a nav file with the following structure:
   ```
   .Nav title
   * include::pages/Annotation.adoc[Annotation]
   * include::pages/Introduction.adoc[Introduction]
   ** include::pages/Scope.adoc[Scope]
   ```
   
1. I gave the copied and altered nav file a name starting with a dot so it will be ignored by Antora.
   
1. Opened the project with IntelliJ, it is displayed like this: 
   ![not desired](https://s6.gifyu.com/images/imagec3e50c12bfc35cd8.png)
   
1. If I copy the module folder where this file is located and put it separately from Antora, then open it with IntelliJ, it will open as desired:
   ![desired](https://s6.gifyu.com/images/image74958da2a608d939.png)

## How the new feature should work

It appears that some of the Antora settings interfere with the AsciiDoc document's settings.
Is it possible to (automatically or manually) disable Antora support for files that should be ignored by Antora i.e. starting with a dot?

**Comment by mojavelinux** [comment]
> I gave the copied and altered nav file a name starting with a dot so it will be ignored by Antora.

That's not even necessary. If the file is not listed as a nav file in antora.yml, Antora will ignore it. (This is different from pages, which get scanned automatically, so the leading dot is required to hide them).

**Comment by ahus1** [comment]
Looking at the screenshots, I assume you try for the following: Creating an additional file (a master document) that includes all pages and creates the standard single-HTML output. 

The second example in your feature request is different from the screenshot: the include should not be pre-pended by two dots. 

Could you please share the error message that is presented once you place your cursor on the first line? Looking at the error message, I could determine if it is a valid error message or not.

Once thing that might happen: Does your Antora module descriptor include AsciiDoc attributes? The first example, where the content is inside a component, will use this for the preview, and this might cause errors. If you provided the attribute with a plain key/value, the new master document can't override them. If this is the case, please try "soft set" attributes, where the value has a "@" at the end, see https://docs.antora.org/antora/2.3/component-attributes/#component-version-attributes
This way your master document can again override the attributes.

If you could point me at a GitHub repo with a minimal example, this would be helpful.

**Comment by Grolribasi** [comment]
> Could you please share the error message that is presented once you place your cursor on the first line? Looking at the error message, I could determine if it is a valid error message or not.

Here it is (headings are on the second line of each document):
![error message](https://s6.gifyu.com/images/imagece2ba3c3c7652587.png)]

This is interesting because if I delete `:doctype: book`, no error messages are displayed, but the file is still not rendered correctly.
![image4ea6c61dcfbf36ec.png](https://s6.gifyu.com/images/image4ea6c61dcfbf36ec.png)

> Does your Antora module descriptor include AsciiDoc attributes?

Yes, it does. Here is the excerpt from a component descriptor file:
```yaml
asciidoc:
  attributes:
    toclevels: 10
    sectids: ''
    sectlinks: ''
    sectanchors: ''
    toc-title: Содержание
    icons: font
    figure-caption: Рисунок
    appendix-caption: Приложение
    wc: WebClient
    dv: Docsvision
    leveloffset: -1
```

The repo is here - https://github.com/Docsvision/docstest
And the file is here - https://github.com/Docsvision/docstest/blob/main/modules/user/.nav-with-includes.adoc
It is not the main file, it's just a file that happens to be located in the same folder. At least, I don't consider it to be the main file,. I'm not sure if IntelliJ does consider.

**Comment by Grolribasi** [comment]
> If the file is not listed as a nav file in antora.yml, Antora will ignore it.
Totally forgot about that, thanks. I renamed the file when I just starting using Antora, so it kind of a legacy name :)

**Comment by ahus1** [comment]
Thanks for providing the link to the repository. 

The behavior your you see results form the following: 
* antora.yml defines `leveloffset: -1`. This is a hard set attribute. Hard set attributes can't be changed in a document. 
* In this case, it disables the possibility to use `:leveloffset: +1` within the document. Therefore the table of contents doesn't structure correctly, and you see error message.

Even if you would change antora.yml to `leveloffset: -1@` to make it a soft-set attribute, the plugin doesn't support it in this version 0.33.3. I'll have a look at how to fix this in a future version. 

What you can do today when using this plugin.: 
* in antora.yml, remove `leveloffset: -1`
* change all your Antora pages to the first heading starts only with a single `=`. 

Once you make this change, this enables another feature of the plugin: 
* The plugin will read the title of a page, and the title must start with a single `=`. While Antora might do this, the plugin doesn't take `leveloffset` into account for that. After changing all pages to start with a the first heading with a single line, you can change `xref:Annotation.adoc[Аннотация]` to `xref:Annotation.adoc[]` and it will pick the title of the page in the preview for navigations and xrefs in pages. 

Read more about the automatic use of a page title here: https://docs.antora.org/antora/2.3/navigation/xrefs-and-link-text/#specify-link-text-in-an-xref
(it was a new feature in Antora 2.3.0)

As this turned out to be a lot of text, I provided an example here: https://github.com/Docsvision/docstest/pull/1/files

I hope this note helps you to proceed in your project.

**Comment by Grolribasi** [comment]
Thanks for the clarification, now I see the issue.

As for your recommendations. I completely agree that I should convert all headings to single `=` and probably remove titles. And I will get to it soon. However right now I apologize, but I have to decline your pull request since it will break the project. There is a lot of other small issues and improvements that will need to be done. This is a working demo and work in progress. But I can promise that I will get to it as soon as possible. Thanks again!

Still. Do you think a feature to exclude files starting with a dot from being affected by Antora would be useful?

**Comment by ahus1** [comment]
Sure, I'm fine that you closed the PR. It was only to show how the code could like.

I don't think that excluding the files from pulling any attributes from the Antora component descriptor is the way to go. There might be other cases where users might want this, for example to replace a product name like `dv` or `wc` in your case. 

The error message that was shown revealed the problem, so I don't want to suppress all validations. If someone presents a validation that should be suppressed, I'll handle that validation specifically. 

In your case, a future version of the plugin will support a soft-set leveloffset attribute. With that in place, there should be no more error messages in your _.nav-with-includes.adoc_. 

A temporary solution with the current plugin could be to move _.nav-with-includes.adoc_ up one folder. Then the plugin won't consider it to be part of the module.

**Comment by Grolribasi** [comment]
You're probably right. I didn't think of the other side of the case when someone actually wants it to work this way.
And it is not recommended to use `==` for headings and amend it with `:leveloffset:` anyway. I will close the issue then.

**Comment by ahus1** [comment]
I created a follow-up issue for this to take care of soft-set attributes in the Antora component descriptor: #798
