### ISSUE TITLE
Plugin steals focus from built-in IDEA HTML preview window

### ISSUE THREAD

**Issue by kriegaex** [asciidoctor/asciidoctor-intellij-plugin#802]
## Observed vs. expected behavior

See https://youtrack.jetbrains.com/issue/IDEA-272653, the problem and how to reproduce it is described in detail there.

## Environment

Plugin Version: 0.33.3

IntelliJ Details:

IntelliJ IDEA 2021.1.3 (Ultimate Edition)
Build #IU-211.7628.21, built on June 30, 2021
Runtime version: 11.0.11+9-b1341.60 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: debugger.watches.in.variables=false, projectView.always.show.inner.classes=true, documentation.show.toolbar=true, scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins: org.intellij.RegexpTester (1.0.8), com.urswolfer.intellij.plugin.gerrit (1.2.5-203), ASM Bytecode Viewer (7.2), jclasslib (5.7), Spock Framework Enhancements (0.12), Osmorc (211.6693.65), com.guidewire.build.ijdevkitmvn (0.4.1), org.jetbrains.kotlin (211-1.5.20-release-284-IJ7442.40), org.intellij.scala (2021.1.21), PlantUML integration (5.5.1), org.asciidoctor.intellij.asciidoc (0.33.3)
Kotlin: 211-1.5.20-release-284-IJ7442.40

**Comment by ahus1** [comment]
Thanks for reporting and analyzing this issue. I'll need to analyze this further, and will then update this issue.

**Comment by ahus1** [comment]
It seems that the the focus handling I added to the AsciiDoc plugin leaked to other JCEF/HTML based previews. I removed the custom focus handling for the release 0.33.5.

I was able to reproduce the situation you described before the change; I needed to open an AsciiDoc file before the situation you described triggered. With the new version I wasn't able to reproduce it. 

I ask you to try out the pre-release, and test if this is fixed for you as well.  

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by kriegaex** [comment]
I installed the new version from the EAP repository and can confirm that the problem is gone.

Thank you very much for the swift reaction and the bugfix release. 😊

**Comment by ahus1** [comment]
Thanks for testing this release. I've promoted it to a regular release; it should be available from the JetBrains marketplace soon. Happy doc writing!

**Comment by ahus1** [comment]
I missed a problem in 0.33.5 so there is now already 0.33.6; it's already on the marketplace.
