### ISSUE TITLE
Toolbar - remove markup

### ISSUE THREAD

**Issue by rmpestano** [asciidoctor/asciidoctor-intellij-plugin#81]
Hi guys,

I'm using v 0.10 and when using the toolbar I would like to remove a markup, example:

1. I select the word 'text';
2. click in bold toolbar icon
3. 'text' becomes '\*text\*'
4. click again in bold toolbar icon
5. '\*text\*' becomes '\*\*text\*\*'

It would be nice if the second time the toolbar was clicked the bold markup was removed.

**Comment by bodiam** [comment]
Thanks for the suggestion! I just built it in a quick and ugly way, and it works, but the selection is messed up, giving a not so nice user experience, so I need fix that in some way.

**Comment by ehmkah** [comment]
I am not sure whether I understand this issue right, but I think that this feature is working in snapshot (the current version from github). @bodiam are you closing the issues you have already fixed?

**Comment by bodiam** [comment]
@ehmkah Nope, I love to keep them open to confuse other contributors.

**Comment by ehmkah** [comment]
@bodiam :-D sorry i did not want to offend you :-) maybe I have a deeper look to understand the problem.

**Comment by bodiam** [comment]
@ehmkah You didn't, and I'm sorry if I offended you! I was a bit too quick in responding, my apologies for that!

However, as you can see in my first reply, I did build something in to make this work. However, it doesn't work all the time. I'm having a hard time reproducing it, and every combination I've used seems to work. @rmpestano , maybe you can try it?

**Comment by rmpestano** [comment]
Hi there,

tried it with 0.11 and looks like it is working.

One thing that we need to improve is the 'Title' option,  it adds a  ' =' every time (with a space) we click the title option. I think it would be nice to add a '=`'without spaces (maybe it could be renamed to "headings"

**Comment by rmpestano** [comment]
maybe we can open another issue for the title/headings thing

**Comment by bodiam** [comment]
Okay, closing this on then! Thanks for testing!
