### ISSUE TITLE
Add "Open in Browser" action on the "right click menu"

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-intellij-plugin#82]
I'm using both the Intellij plugin (write) and the Chrome extension (output). On HTML files I can right click and choose "Open in Browser" (or select a browser in the upper right corner of the editor) to view/render the file in the browser. I know I can click on "Preview" tab but I think that would be great to have the choice to preview the file in the browser.

Would it be possible to add this action on AsciiDoc files ?

**Comment by bodiam** [comment]
If you'd open the AsciiDoc file in your browser, what would you expect to happen? Cause what I would expect, is that you would see the plain text version, not the HTML version of the file. But I assume that's not what you want, correct?

**Comment by Mogztter** [comment]
I'm using the Chrome extension so the file is rendered and I can see the HTML.

It's just a quick link to avoid to right click > "open in explorer", then drag and drop the AsciiDoc file on Chrome.

**Comment by bodiam** [comment]
Okay, I understand. I have tried and googled a bit, but I have actually no idea how IntelliJ does this. It might be hardcoded thing based on filetype. If you can tell me how to do it, I have no problems adding it to the plugin.

**Comment by bodiam** [comment]
<img width="607" alt="screen shot 2015-08-19 at 13 01 04" src="https://cloud.githubusercontent.com/assets/46468/9354637/6448590a-4672-11e5-8082-5e6644c5e551.png">

**Comment by Mogztter** [comment]
Nice, thanks! :+1:

**Comment by bodiam** [comment]
It's also released btw!

**Comment by Mogztter** [comment]
Wow that was fast!!
Just updated the plugin and the action is there but nothing is happening when I click on "Default", "Chrome" or on other browsers.
I created a simple `test.html` just to be sure and the file opens in the selected browser (as expected).

I'm using Intellij 14.1.4 (build 141.1532) jre 1.8 64bits on Ubuntu.

**Comment by bodiam** [comment]
Hmm, that's weird. This is a typical 'it works on my machine' thing. Can you give me more information? OS, File path, etc.

**Comment by Mogztter** [comment]
Same on Windows, the file extension is `.adoc` and the file is at the root of my workspace (nothing fancy). I can do a screencast if you want ?

**Comment by bodiam** [comment]
I discussed this with @yole here: https://devnet.jetbrains.com/thread/472091?tstart=0, and I don't have solution unfortunately. It only seems to work in develop mode, not when the plugin is released, and I don't know why. Either it's hard to open arbitrary files using the browser or I'm just missing something.

**Comment by ahus1** [comment]
I'm fine with a rendered HTML. This would work in all browsers without a plugin. 

For the preview we render it only in-memory, but we could write it to a file. We already have temporary file handling (and cleanup) in place. Or we could serve it via an embedded web browser (IntelliJ does this in some places already, but I have no idea how to do this. This would allow us to update the content on a reload of the page)

**Comment by ahus1** [comment]
The next preview-release will open the contents of the preview in the browser; this includes also rendered diagrams.

**Comment by ahus1** [comment]
This is part of release 0.28.9 that is now in preview. 

The user can now choose any of the browsers presented in browser hover bar. 

![browser-choose](https://user-images.githubusercontent.com/3957921/60585415-023e4e80-9d90-11e9-8ca6-1bfc4e67d48b.png)

The functionality previously provided here was opening the .adoc-file directly in the browser (for example Chrome) and used the installed Asciidoctor-plugin in Chrome to to render the preview. 

For users who want to use this feature, please configure Chrome as an external tool. This way it will be accessible from the context menu, and the user can configure a keyboard shortcut of her/his choice. 

Except from [FEATURES.adoc](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/FEATURES.adoc#editor): 
> To do this, add Chrome as an [external Tool in the settings](https://www.jetbrains.com/help/idea/settings-tools-external-tools.html).
> Provide `$FilePath$` as the argument so that Chrome knows where to find the file.
> The user can assign a shortcut to the external tool using "Help | Find action... | (type the name of external tool) | kbd:[Alt+Enter] | (type the shortcut of choice) | OK".

The pre-release of the plugin is available from [GitHub releases](https://github.com/asciidoctor/asciidoctor-intellij-plugin/releases) and the [IntelliJ AsciiDoc EAP repository](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/master/CONTRIBUTING.adoc#eap).

The preview is limited in the following ways:
* to see updates, the user needs to press reload in the browser (F5)
* you can't navigate links to relative documents

I'd be happy to see contributions for this. I'm leaving this ticket open for now for comments, and move ideas for improvements to new tickets later.

**Comment by ahus1** [comment]
This preview has now been published some time ago. Closing ticket.
