### ISSUE TITLE
Properly handle spell-checking in lists

### ISSUE THREAD

**Issue by 0xDiddi** [asciidoctor/asciidoctor-intellij-plugin#822]
## Why the new feature should be added

I am using the spelling and grammar checking built into intellij.
For the most part, this plays well with asciidoctor and the plugin, but lists sometimes cause trouble.

It appears that the spell checker considers a block of (un)ordered lists items as a single paragraph,
ignoring the fact that each list item effectively acts as its own small paragraph.

This may then lead to false positive grammar errors, for example intellij will report a duplicate word when one list item starts with the same word(s) that the previous item ended with, or similarly it will sometimes report a block of list items as a sentence with too many words, if the list items are not terminated with a period (which they usually aren't).

One workaround is of course to seperate all list items by blank lines, however this runs the risk of making the document source hard to read as it would prevent grouping list items into logical blocks.

## How the new feature should work

I haven't worked with intellij plugins, nor do I know how they would interact with the spell checker.
I suppose the solution would involve either adding a rule to the spell checker that separates list items,
or alternatively somehow internally altering the text that is passed to the spell checker without impacting what is shown to the user.

**Comment by ahus1** [comment]
Thanks for suggesting this change. The ticket describes both what is missing today and how this feature should work in the future from a user's point of view.

Regarding the implementation: Probably the parser needs to change to create on AST node for each list item, even when they are not separated by an empty line. 

While this is not implemented and what works today: The empty line could be skipped as long as each item is a sentence that starts with a capital letter and ends with a full stop. This might not work in all places, but some: 

```asciidoc
* Sentence number one.
* Sentence number two.
* Sentence number three.
```

**Comment by ahus1** [comment]
I remember this has sometimes annoyed me as well. I pushed a change and this will be included in the next pre-release. 

This will include: 

* grammar check per item as suggested for numbered, unnumbered. definition and callout lists

In addition as list items now have a better representation in the AST

* folding for items 
* showing items as entries in the structure view

The following text

```
* this is an item
with a second line
* this is a folded item
with a second line
* a third item
```

will show as follows in the editor when the second item is folded

![image](https://user-images.githubusercontent.com/3957921/128414242-57277fae-1916-464e-9899-a5f9b4ef71e8.png)

and in the structure view like this

![image](https://user-images.githubusercontent.com/3957921/128414315-6cda9bc8-7828-45f5-92da-e1278b58ac05.png)

I'm not so sure if the texts in the structure need some touch ups, but let's see.

I'll comment here once the pre-release is available for download.

**Comment by ahus1** [comment]
There is now pre-release 0.33.12 that includes this change. Please give it a test run and let me know by adding a comment to this issue if this work for you as expected and if something needs tuning or fixing. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by 0xDiddi** [comment]
I probably haven't encountered every scenario yet, but across the last few days the new version seems to behave as expected 👍

**Comment by ahus1** [comment]
Thank you for the feedback, I'll close this issue for now. If you find something related to this ticket, please comment and I'll re-open it. Or just open a new issue. 

This change promoted to a general release as I wanted to fix a different bug. 0.33.13 is available, and soon 0.33.14 will be available as well.

**Comment by 0xDiddi** [comment]
During a lengthy compile process just now I took a closer look at the structure tab, and did notice something, then went to investigate and found some more.

I compiled a document in [this gist](https://gist.github.com/0xDiddi/6993fa4b147b53e2452c1c84673150d9) with all the things I found.
The document contains both descriptions and examples of the problems, and its raw form can be put into intellij to observe the described behaviour.

**Comment by 0xDiddi** [comment]
Another thing I just found which I think is also related:

![image](https://user-images.githubusercontent.com/10011726/129192328-c4a7e80a-e665-49d2-947e-659c59e44b20.png)

Description list items are not being highlighted properly when commented out, and also still appear in the structure when they probably shouldn't (or at least not in the same style as non-commented ones).

**Comment by ahus1** [comment]
Thank you for testing it rigorously. Samples are always welcome; I can re-use them for automated tests as well. 

Pre-release 0.33.16 fixes at least the comment problem, and also some cases where definition lists with more than one word created weird structure views. 

I'll move the remaining items to a new issue that will take care of folding lists.
