### ISSUE TITLE
Option to hide edit controls in Asciidoc editor and preview mode

### ISSUE THREAD

**Issue by overfullstack** [asciidoctor/asciidoctor-intellij-plugin#824]
## Why the new feature should be added

I wish to use Asciidoc in presentation mode directly from intellij, but the controls at the top are hurting my intent. Can I please have an option to hide them. (PFA the screenshot)

## How the new feature should work
An option in plugin setting to hide the controls
<img width="1792" alt="Screenshot 2021-08-10 at 07 53 11" src="https://user-images.githubusercontent.com/13434911/128798932-bbfd7c49-bc9d-4a96-9f2b-1abca7a0de26.png">

**Comment by ahus1** [comment]
Thanks for suggesting this change. Maybe no new control would be needed, maybe it should just hide once a user chooses the full screen mode.

**Comment by ahus1** [comment]
This change will be part of the next release. I'll update this issue once a pre-release is available.
