### ISSUE TITLE
Video file resolution inconsistent with Antora

### ISSUE THREAD

**Issue by rocec** [asciidoctor/asciidoctor-intellij-plugin#828]
## Observed vs. expected behavior

Antora looks for videos in the images family directory. I.e., if you place `somevid.mp4` in the `images` directory of a module,
```
video::somevid.mp4[]
```
works fine with Antora.

The IntelliJ plugin does not apply the same search path and reports an error "File doesn't resolve".

Identical handling by Antora and the plugin would be expected, although Antora does not officially support local videos. The current behavior may be subject to change. See [Zulip thread](https://antora.zulipchat.com/#narrow/stream/282400-users/topic/.E2.9C.94.20Videos.20in.20the.20IntelliJ.20plugin) and the [Antora issue](https://gitlab.com/antora/antora/-/issues/319) linked therein.

## Steps to reproduce

As outlined above, starting from an empty Antora project structure with a ROOT module:
- Place a video file `somevid.mp4` into `modules/ROOT/images`
- Create page `modules/ROOT/pages/somevideo.adoc` and embed the video there.
  ```
  video::somevid.mp4[]
  ```

## Environment

Plugin Version: 0.33.16

IntelliJ Details:
IntelliJ IDEA 2021.2 (Community Edition)
Build #IC-212.4746.92, built on July 27, 2021
Runtime version: 11.0.11+9-b1504.13 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1933M
Cores: 8
Non-Bundled Plugins: IdeaVIM (0.69), PlantUML integration (5.5.1), PythonCore (212.4746.96), org.asciidoctor.intellij.asciidoc (0.33.16)
Kotlin: 212-1.5.10-release-IJ4746.92

**Comment by ahus1** [comment]
I had a look into this. This will be part of the next upcoming (pre-)release. I'll update this issue once it is available.

**Comment by ahus1** [comment]
Pre-release 0.34.2 is now available that includes this change.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
