### ISSUE TITLE
How to prevent "class or interface expected" error for inlined Java code fragments

### ISSUE THREAD

**Issue by fcurts** [asciidoctor/asciidoctor-intellij-plugin#830]
## Description

```
[source,java]
----
System.out.println("Hello, world!");
----
```

The above gives the  following error in IntelliJ:

> 'class' or 'interface' expected

Is there a way to prevent (or at least suppress) this error?
The quick fix "Hide errors in source blocks for all languages" is too broad.

**Comment by ahus1** [comment]
Thanks for asking this question. I see at least two possibilities for this: 

* add the Language "java" to the field "Hide errors for:" in the settings to suppress all errors for Java code snippets
* move the source code to a real Java file and then use an tag comments and and an include to use the line you're marked with tags in your document.

See the [include content by tagged region docs](https://docs.asciidoctor.org/asciidoc/latest/directives/include-tagged-regions/) for details. The "indent" option is quite useful to fix the indentation for included regions. See below for an example.

```java
// In the Java file
public class Example {
    public static int main() {
        // tag::sop[]
        System.out.println("Hello world!"); // <1>
        // end::sop[]
    }
}
```

```asciidoc
// in the AsciiDoc file
.Fix indentation
[source,java,indent=0]
----
include::Example.java[tag=sop]
----
<1> this is your first line of Java
```

Please let me know if one of the options work for you.

**Comment by fcurts** [comment]
Thanks for the quick response. 

I wasn't aware of "Hide errors for:". This is certainly better than nothing, but too broad and (I think) not easily shareable. A way to support Java code fragments or a way to suppress errors for a particular code block would be preferable.

Moving the source code to a real Java file is what we do for Antora docs. However, for `README.adoc` and other files viewed on GitHub, it is unfortunately not an option because GitHub doesn't support includes (https://github.com/github/markup/issues/1095). Also, sometimes inline code is a better fit.

Fortunately, Kotlin code blocks don't have this problem.

**Comment by ahus1** [comment]
For a `README.adoc` scenario this is all I can offer for now I suppose, except maybe removing the `java` language indicator to  make it plain text. 

If you consider this question to be answered, please close this issue, or add further questions/suggestions.

**Comment by fcurts** [comment]
(Why) is suppression via comment, which is very common in IntelliJ, not a viable option?

**Comment by ahus1** [comment]
I had another look and found that the error is a parser error, and that can't be suppressed with a comment. 
Only inspections can be suppressed with a comment. 

I tried similar plugins like for example the Markdown plugin, and they didn't come up with a different solution yet. 
Therefore the options listed above are the ones I can offer today.

**Comment by holly-cummins** [comment]
This seems like an important missing feature.

**Comment by ahus1** [comment]
Hi @holly-cummins - happy to see a colleague here. Can you please check if the options described in my comment https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/830#issuecomment-900861410 work for you?

**Comment by holly-cummins** [comment]
> Hi @holly-cummins - happy to see a colleague here. Can you please check if the options described in my comment [#830 (comment)](https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/830#issuecomment-900861410) work for you?

Neither was ideal for me. The warnings have the potential to catch real programming issues, so I don't want to turn them off for all snippets. Sometimes they've saved my bacon when I was about to commit malformed code. Another issue there is some some projects might have a policy of not committing .idea files. In those environments a fix in IDE settings would reduce noise for me, but not for my colleagues. 

The option of moving the code to its own file probably would do the trick, but it looked like hard work! I most often see validation issues on short code fragments, where I might just have part of a line of code. Making a whole java class for that content fragment and then defining tags and then fixing the tags because I get them wrong the first time feels like overkill. 

The ideal for me would be something like 

----
[source,java,no-validation]
----
System.out.println("Hello, world!");
----

**Comment by mojavelinux** [comment]
I like the idea of a hint. However, it should be an option since positional attributes mean something very specific. So it would need to be:

```
[,java,opts=novalidate]
```

or

```
[%novalidate,java]
```

When the language is specified, the `source` block name is implied.

**Comment by ahus1** [comment]
The change as Dan suggested above is now part of pre-release 0.43.3. Please give it a try and let me know your thoughts. 

I still want to make it more discoverable. Possibly with an intent by pressing Alt+Enter on a source block and having the option to add it to the source block definition it if doesn't exist there, yet. 

Maybe someone would want to comment which syntax would be preferred for the intent. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment]
No response to the preview version, promoting 0.43.3 to a regular release now. It should be available in the marketplace soon.

**Comment by ahus1** [comment]
Documentation is now available here: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/faq/validation-for-asciidoc-files.html#validation-of-source-code-snippets

**Comment by ahus1** [comment]
Pre-release 0.43.4 now contains intents to switch on this setting for a code block. Use Alt+Enter when inside of a source block. See a recording below.

![hide-errors-in-source-block](https://github.com/user-attachments/assets/b47675ad-8cbb-4cad-8281-411417455adb)

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
