### ISSUE TITLE
Markup symbol for bold and italic inside work must be doubled

### ISSUE THREAD

**Issue by Mogztter** [asciidoctor/asciidoctor-intellij-plugin#86]
If a the selection is not an entire word, the markup symbol must be doubled for bold and italic action.
For example, if I select the letter `b` from the word `about`, and then click bold, the result must be `a**b**out`.

**Comment by ehmkah** [comment]
@bodiam What do you expect to happen in the following cases. the "_" marks the beginning and ending of the selection, so your example would be ````a_b_out           => a**b**out````

Testcases (same should be valid for italic):
````
a_b_out           => a**b**out
_about_           => *about*
a_**b**_out       => about
_about s_omething => **about s**something
_about_/            => **about**/
hel _about_ u    => hel **about** u

unsure about this:
_ab_*ut           => **ab***ut
````

Questions:
* Are there any testcases missing?
* Would be OK to always use two asterisks, then we would not run in the trouble?

**Comment by bodiam** [comment]
I'm not sure if there are testcases missing, it seems good, and I think I agree about the last one too, the one which you are unsure of.

I think we should always use two asterisks indeed when it's not an entire word. If you could build that, I'll release a new version (it's due anyway), and if there's some kind of scenario we missed, we can fix it later.

**Comment by bodiam** [comment]
Fixed by @ehmkah !
