### ISSUE TITLE
Completion of imagefoldernames and imagefiles not refreshed

### ISSUE THREAD

**Issue by HaLo1701** [asciidoctor/asciidoctor-intellij-plugin#875]
## Completion not refreshed

Hello,

when I am editing Asciidocfiles and using the keyword image:: the completion of the foldernames and files in the folder are not refreshed since files are added by another process.

In my example the folder hurims-75 exists and the file Berechtigung.png in it also:

![grafik](https://user-images.githubusercontent.com/50229818/135625309-a4881105-e291-4f92-bb97-a1a869b70fcd.png)

The completion only shows the folder hurims-77 which exists since the startup of IntelliJ.

## Steps to reproduce

Edit an AsciiDoc file. Add an image-tag with an image in an subfolder.
Add with an other program a new subfolder or image.
Add another image-tag and use the completion popup. The new folder or file doesn't occur.

## Environment

Plugin Version: 0.35.4

IntelliJ Details:
IntelliJ IDEA 2021.2.2 (Ultimate Edition)
Build #IU-212.5284.40, built on September 14, 2021
Runtime version: 11.0.12+7-b1504.28 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins: com.intellij.plugins.netbeanskeymap (212.4535.15), org.asciidoctor.intellij.asciidoc (0.35.4), org.jetbrains.kotlin (212-1.5.31-release-546-IJ4638.7)
Kotlin: 212-1.5.31-release-546-IJ4638.7

Many thanks in advance,

Hans

**Comment by ahus1** [comment]
Thanks for reporting this, I'm sorry to hear this bugs you.

IntelliJ caches the directory structure to speed up auto-completion and other features. From what I observe it caches it most aggressively in target/build folders (most of the time text appear as "excluded" in IntelliJ). 

Most of the time I've seen IntelliJ to catch up with external changes eventually without a restart. It runs a process "fsnotifier" in the background that listens for file system changes.

The the refresh didn't work as expected, I sometimes used the "Reload from Disk" option using right-click on the older in the project view. There is also a menu item "File | Reload all from Disk" that has a hot-key associated (Ctrl-Alt-Y as the IntelliJ default). 

When you run external tools, you can run them via IntelliJ and ask IntelliJ to synchronize the files after execution, see screenshot below. Adding it to the run/debug configurations should work in a similar way.

Please let me know if these hints help you to resolve the situation.

![image](https://user-images.githubusercontent.com/3957921/135706969-3ad8af3b-944e-41b3-98ce-38ea65e4f5c1.png)

**Comment by HaLo1701** [comment]
Hello @ahus1,
thank you for the very fast response.
In my case the reload from disk helps me to solve the problem.
What I have seen is, if I type a new line in with "image::", the cache is loaded new.
If I use the completion in an existing line, it is not reloaded.
Very strange.

**Comment by HaLo1701** [comment]
FYI, that's the answer from JetBrains:

It is expected that IDE would not immediately discover the files if they were modified by the external process. It synchronizes files on various IDE actions (like refactorings) and also on IDE main frame activation/deactivation. You can tune the synchronization options in Settings (Preferences on macOS) | Appearance & Behavior | System Settings | Autosave settings.

**Comment by ahus1** [comment]
Thanks for digging deeper. In addition to that I did a debugging session to see if the method to compute the list of file sis re-evaluation on each auto-complete: it is, so this is good. It all depends on the file structure cache.

Please let me know if the current solution using a refresh (either via IDE menus or via hotkey) works sufficiently for you.

I briefly considered triggering a refresh from the plugin. I then hesitated as it could break the IDE's performance. I'll need to do more investigations based on your experiences with the current solution and then weight it against possible trade-offs.

**Comment by HaLo1701** [comment]
Hi,
thanks for your answere.
The solution is sufficiently working for me.
I am also fear that the performance will break down by refreshing every time by using the completion.
Many thanks for your support.
