### ISSUE TITLE
Correct Icon and Font Size after switch from Presentation Mode

### ISSUE THREAD

**Issue by cinhtau** [asciidoctor/asciidoctor-intellij-plugin#88]
![intellij-asciidoctor-bug](https://cloud.githubusercontent.com/assets/7956174/9783648/44dc6544-57a6-11e5-818c-19a1f9714e95.png)

When I use the Presentation Mode (ALT + P) and I switch back to normal mode, the toolbar with asciidoc icons and font are not resized properly.

**Comment by ehmkah** [comment]
hi @cinhtau I can not reproduce this issues. I tried plugin version 0.10 and 0.11 which will be released soon. Sometimes it needs some (very very few) moments until font-size is corrected. Which platform do you use? I use IntelliJ 143.381 on mac os x (el captain).

**Comment by cinhtau** [comment]
Well Windows :-1: IntelliJ 14 was since then. Using 15 right now. Will observe.

**Comment by bodiam** [comment]
Thank you both for chasing this! Good that it's "fixed"!
