### ISSUE TITLE
LanguageTool flags space errors around button macros

### ISSUE THREAD

**Issue by infotexture** [asciidoctor/asciidoctor-intellij-plugin#890]
Follow-up to related issue https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/846 _(that was about e-mail addresses, this time it's button macros)._

## Observed vs. expected behavior

The [LanguageTool](https://languagetool.org) grammar & spell checker complains about extra spaces around button macros, but the spaces are correct in the source document.

### Button macro at end of sentence

With the following sentence end in a German document:

> …Schaltfläche btn:[Download].

LanguageTool complains with the following message:

> “Vor dem Punkt sollte kein Leerzeichen stehen.”

### Button macro in middle of sentence

> …klicken auf btn:[Öffnen] öffnet etwas…

LanguageTool complains with the following message:

> Möglicher Tippfehler: mehr als ein Leerzeichen hintereinander

In the first case, there is no space before the final period in the sentence, and in the second case, the spaces flagged are those immediately before and after the button macro, which suggests that whatever logic is used to exclude button macros from spellchecking may lead LanguageTool to think there are extra spaces where there are none.

The fix for this is probably very similar to that for https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/846, though it may be necessary to add a few more test cases for similar scenarios (I haven't tested [keyboard or menu macros](https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/#keyboard-button-and-menu-macros)).

## Environment

Plugin Version: 0.35.8

### IntelliJ Details

```
IntelliJ IDEA 2021.2.1 (Community Edition)
Build #IC-212.5080.55, built on August 24, 2021
Runtime version: 11.0.11+9-b1504.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: org.asciidoctor.intellij.asciidoc (0.34.1)
Kotlin: 212-1.5.10-release-IJ5080.55
```

**Comment by ahus1** [comment]
This fix is now available as part of pre-release 0.35.9.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
