### ISSUE TITLE
allow-uri-read attribute is ignored in the .asciidoctorconfig file

### ISSUE THREAD

**Issue by artemy-osipov** [asciidoctor/asciidoctor-intellij-plugin#896]
allow-uri-read attribute must be set to include external files https://docs.asciidoctor.org/asciidoc/latest/directives/include-uri/
In addition, it must be specified through Asciidoc attributes https://github.com/asciidoctor/asciidoctorj/issues/71

## Observed vs. expected behavior

allow-uri-read attribute is only recognized in the IDEA settings

## Steps to reproduce

1. Write some adoc that includes external file

```adoc
== Example

include::https://raw.githubusercontent.com/asciidoctor/asciidoctor-intellij-plugin/main/FEATURES.adoc[]
```

2. Set `allow-uri-read` attribute in gradle extension

```groovy
asciidoctorj {
    attribute('allow-uri-read', 'true')
}
```

3. Run asciidoctorEditorConfig task to generate .asciidoctorconfig file

The line `:allow-uri-read: true` is successfully added to the file, but the preview only shows a link to a external file

![image](https://user-images.githubusercontent.com/1992775/138281747-5a7eecc8-317c-459e-88cc-b8737a28652a.png)

However, if you generate documentation (run asciidoc task), the file will be successfully included

If the attribute is set through the IDEA settings, then the preview works fine

![image](https://user-images.githubusercontent.com/1992775/138281620-80fc3754-ecf4-45c1-826a-809c61f48ba8.png)

![image](https://user-images.githubusercontent.com/1992775/138281495-6619ae29-bdd8-4153-b874-cb9a667e1bde.png)

## Environment

Plugin Version: 0.35.8

IntelliJ Details:
```
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.40 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: Key Promoter X (2021.2), org.sonarlint.idea (6.1.0.38326), org.asciidoctor.intellij.asciidoc (0.35.8), org.mapstruct.intellij (1.3.0), izhangzhihao.rainbow.brackets (6.21)
Kotlin: 212-1.5.10-release-IJ5457.46
```

**Comment by ahus1** [comment]
Closing this issue as no additional steps are planned for the AsciiDoc plugin.
