### ISSUE TITLE
feature: support ditaa in puml files

### ISSUE THREAD

**Issue by aklemp** [asciidoctor/asciidoctor-intellij-plugin#902]
## Why the new feature should be added

The current version of plantuml is supporting Ditaa directly: https://plantuml.com/de/ditaa
Diagrams like this should be rendered correctly in AsciiDoc plugin as well.

## How the new feature should work

The puml file would look like this:

```
@startditaa -E
+---------+
| example |
+---------+
@endditaa
```

The usage would be like this:

```
plantuml::example.puml[target=example]
```

An error is shown in IntelliJ which is sadly only an image instead of text.

![error](https://user-images.githubusercontent.com/9880351/138843125-0ebefd0b-32a9-410a-97bf-1da1aaa19312.PNG)

The advantage of using Ditaa via PlantUML is that such a diagram could be previewed in IntelliJ on its own once it is supported by PlantUML plugin: https://github.com/esteinberg/plantuml4idea/issues/327

**Comment by ahus1** [comment]
This has been fixed upstream, and I added this to the AsciiDoc plugin in pre-release 0.37.22. 

I've tested the pre-release and it works as expected with the example you provided. 

```
[plantuml]
----
@startditaa -E
+---------+
| example |
+---------+
@endditaa
----
```

renders as

![image](https://user-images.githubusercontent.com/3957921/171509609-c01040ed-95a9-463b-b7af-0d079c46ed2e.png)

Therefore I close this issue.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
