### ISSUE TITLE
How to enable extensions for the preview?

### ISSUE THREAD

**Issue by thammegowda** [asciidoctor/asciidoctor-intellij-plugin#915]
## Description

Asciidoctor has a list of official and 3rd-party extensions https://asciidoctor.org/docs/extensions/
Many of them are very helpful.

For example, I want to use [asciidoctor-bibtex](https://github.com/asciidoctor/asciidoctor-bibtex) extension, and enable it in HTML preview.
How to do it?
VS Code's counterpart has an option to set command-line arguments, which is sufficient to enable any plugin we need.

<img width="461" alt="Screen Shot 2021-11-14 at 10 23 09 AM" src="https://user-images.githubusercontent.com/1865964/141693638-635c30ff-2417-4d1f-864c-3615377cb2e4.png">

 It'd be nice to get a similar option in IntelliJ/Pycharm.

**Comment by ahus1** [comment]
Thanks for reaching out. There is an option to place extensions in the _.asciidoctor/lib_ folder in the project. See [the docs](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/advanced/asciidoctor-extensions.html) for details. 

While this works for small, self-contained extensions, it will get a bit more complicated to put all dependencies there as well. 

If that approach doesn't get you where you'd like to be, some like could be achieved: having a build script download the necessary gems, then the IDE could pick up the gems from a folder. See https://github.com/pont-us/asciidoctor-bibtex-maven-example for an example where _gem-maven-plugin_ downloads the gems, then _asciidoctor-maven-plugin_ picks them up from a folder.

**Comment by ahus1** [comment]
(addendum: please read "some like this could be achieved" as "the plugin could be enhanced to support this")

**Comment by thammegowda** [comment]
@ahus1 Thanks a lot for the reply and link to relevant docs! I will give it a try.
