### ISSUE TITLE
Improve PSI structure for Text with Quotes

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#920]
## Why the new feature should be added

A text in quotes like 

```
Text `quotes` more text.
```

is broken down like this today in the PSI (whitespace excluded):

![image](https://user-images.githubusercontent.com/3957921/142396693-39ebf2e7-3c47-457f-9ab8-59a9a78ce73b.png)

The quotes to start and end the mono are outside the PSI element. This makes it difficult for other tools to group the quotes together with the text. 

## How the new feature should work

* Quotes should be part of the PSI-Element
* Currently there is AsciiDocTextMono und AsciiDocTextItalic, this will be combined as AsciiDocTextQuoted
* The Manipulator for the element will return with getRangeInElement() the text without the quotes. 

Note to implemententors: Quotes texts can be nested.

**Comment by ahus1** [comment]
The following tokens will lead to a "AsciiDocTextQuoted" element: bold, italic, mono, single typographic quotes and double typographic quotes -- [see code](https://github.com/asciidoctor/asciidoctor-intellij-plugin/blob/main/src/main/java/org/asciidoc/intellij/psi/AsciiDocTextQuoted.java#L34-L43). Will add more upon request. 

This is the new structure for the next pre-release:

```
Text `quotes` more text.
```

![image](https://user-images.githubusercontent.com/3957921/142735319-1f1b2950-4851-45f3-89a8-b78b3029378b.png)

Note: quoted texts can be nested. For AsciiDoc, the quotes need to balance, but they don't need to be properly nested. For now, PSI parsing is undefined and best effort if quotes are not properly nested. 

```
Text `qu__**ot__es**` more text.
```

![image](https://user-images.githubusercontent.com/3957921/142735400-b622dd7a-9031-4c95-a0ff-80856e674c61.png)

**Comment by donnerpeter** [comment]
Ouch, non-nesting makes this change seem less like an obvious improvement. I wonder if Markdown support allows that, and how it deals with that. I can check that next week.

**Comment by ahus1** [comment]
@donnerpeter - The non-nesting quotes shouldn't hurt much: Most documents would use it properly nested, so non-nesting formatting shouldn't be an issue. I just wanted you to make you aware of this in case you would stumble on this during testing. The approximation is good enough IMHO.

Another question: If something is bold and italic like `*_Text_*` - would you expect it to be one AsciiDocTextQuoted PSI, or two AsciDocTextQuoted that are nested (one for bold, one for italic)? When it is one AsciiDocTextQuoted it would be simpler to find out that it is bold and italic, and expanding the selection would expand both quotes in one go. If they would be nested, it would be simpler to expand a selection in two steps (first the inner, then the outer quotes).

I'd like to hear your thoughts on nesting vs. non-nesting the double-quoted texts.

**Comment by donnerpeter** [comment]
Aha, Markdown doesn't support non-nested emphasizing at all (at least in IntelliJ). I realize it's a rare case so it probably won't cause issues in practice. Still, the PSI could be surprising there to uninitiated readers (if any ever exist). I have no better ideas though, except for giving up on this structural PSI idea entirely :(

As for structural double nesting, the only case I can imagine for separate steps is that someone wants to select the _ text without the * one, and then maybe replace it with something else, or use a toolbar action to change its formatting. I'm not sure how often this is needed though, so not having this functionality might be fine. For my use cases it doesn't matter. Single nesting would also break the invariant that a Quoted PSI always starts with a single "quote" leaf, if that invariant is ever needed for anything.

**Comment by ahus1** [comment]
I gave it a thought and found that I would need the code anyway to figure out if a child's parent is for example bold text, and this element would then be bold and italic. So I decided to make formatting nest-able, with one pair of quotes per AsciiDocTextQuoted. 

I just published pre-release 0.36.1 that contains a first iteration on this. 

Please give it a try if it works as expected. The parser isn't yet so universal that everything can be quoted: at the moment a URL within quotes will not create the AsciiDocTextQuoted element. It should follow soon. If you run into problems, please post a small AsciiDoc snippet so I can use it for tests.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by donnerpeter** [comment]
I've played with some samples, and things seem to work as I expect. Thanks!

**Comment by ahus1** [comment]
Thanks for giving it a try. I now close this issue. Please let me know if you run in any issues.
