### ISSUE TITLE
Illegible preview in Darcula theme for JCEF browser

### ISSUE THREAD

**Issue by tgrip** [asciidoctor/asciidoctor-intellij-plugin#921]
## Observed vs. expected behavior

when using the preview with darcula Theme with the default JCEF browser, the preview is not looking good. It looks almost like without any stylesheet, like default HTML style. It looks better with the Swing preview.

## Steps to reproduce

![jcef](https://user-images.githubusercontent.com/451357/142430231-b3bed59b-c66f-4b85-95c4-62a8101ec5d5.png)
![swing](https://user-images.githubusercontent.com/451357/142430235-0e5589f3-7230-45a4-bf85-186f35f23f14.png)

Open an Asciidoc File with Darcula theme and check the preview

## Environment
OS Mac OS X(x86_64) v11.6.1

Plugin Version: 0.35.12

IntelliJ Details: IU-212.5457.46
JRE 11.0.12+7-b1504.40x64 J

**Comment by ahus1** [comment]
Thanks for raising this issue. 

As the preview looks as if it is not styled, one possible reason is that your document set the `:stylesheet:` attribute to a URL that can't be loaded by the preview. 

Is the document you look at open source?

Could you please check if this attribute has been set? You could add `{stylesheet}` to the document to render the URL that is used. 

A more in-depth analysis is to 
* open the in-browser preview by hovering with the mouse in the upper right corner of the editor and choose a browser; this should show the same problem, and you can access the browser's developer tools as usual.
* open the preview's browser developer tools [as described in the docs](https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/preview/jcef-preview.html#benefits-of-the-jcef-preview).

Please let me know what you discover.

**Comment by tgrip** [comment]
The document is part of our developer documentation. It can be seen here: https://documentation.abas.cloud/en/esdk/#integTest

{stylesheet} gives me an relative url to an existing CSS in the build folder.

When I open the adoc file with one of the browsers, it is rendered correctly. 
However, when I open the developer tools of the preview it isn't loading any stylesheet, just the Chrome defaults.

**Comment by ahus1** [comment]
Is the source of the documentation available in a git repository, so I can try it myself? 

I assume the relative link to the CSS in the build folder is not working for some reason.

**Comment by ahus1** [comment]
I tried some examples and found that `:stylesheetdir:` was allowed to be relative, but not `:stylesheet`. 

I fixed this for the pre-release 0.35.16. 

This release supports a relative ':stylesheet:' attribute and will automatically fallback to the standard stylesheet if the configured stylesheet is not available.

Please let me know if this works for you.

Please note: the Swing preview always looks ugly, as it doesn't support proper CSS. Please use JCEF preview (preferred).

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by tgrip** [comment]
Thanks, that sounds great and should fix it

**Comment by ahus1** [comment]
Thanks for the feedback. I now close this issue, please let me know if you experience any issues.
