### ISSUE TITLE
Format error of tables with source code blocks in cells

### ISSUE THREAD

**Issue by mederel** [asciidoctor/asciidoctor-intellij-plugin#923]
## Observed vs. expected behavior

When editing asciidoc files containing tables that contain source code blocks, table lines stop being recognized and the formatter starts to bug. It does not keep newlines between columns and puts newlines after legend texts of source code blocks (prefixed with dot .).

Observed behaviour:

```asciidoc
= Table formatting bug

.Incorrect format
[cols="1,a"]
|===
| Col1 | Col2

| Some text
| Lorem ipsum

.code.sh
[source,bash]
----
#!/bin/bash
date
----

| New line | New code

.code.sh
[source,bash]
----
#!/bin/bash
date +%y%m%d
----

| Code insert without introduction text | .code.sh

[source,bash]
----
#!/bin/bash
date +%Y%m%d
----

|===
```

Expected:

```asciidoc
= Table formatting bug

.Correct format
[cols="1,a"]
|===
| Col1 | Col2

| Some text
| Lorem ipsum

.code.sh
[source,bash]
----
#!/bin/bash
date
----

| New line
| New code

.code.sh
[source,bash]
----
#!/bin/bash
date +%y%m%d
----

| Code insert without introduction text
| .code.sh
[source,bash]
----
#!/bin/bash
date +%Y%m%d
----

|===
```

See the | all put on one line for the 2 last rows and the whitespace between legen (`.code.sh`) and source code block with `[source,bash]`.

## Steps to reproduce

Edit above example with asciidoc plugin and let it reformat the content.

## Environment

Plugin Version: 0.35.12

IntelliJ Details:
IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Licensed to Emile de Weerd
Subscription is active until November 27, 2021.
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.11.0-40-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Non-Bundled Plugins: org.jetbrains.plugins.go-template (212.5457.62), EclipseCodeFormatter (21.1.203.000.1), com.intellij.kubernetes (212.5457.4), org.asciidoctor.intellij.asciidoc (0.35.12), org.jetbrains.kotlin (212-1.6.0-release-799-IJ5457.46)
Kotlin: 212-1.6.0-release-799-IJ5457.46
Current Desktop: KDE

**Comment by ahus1** [comment]
Thanks for reporting this. Using the examples you provided I can reproduce the issue. I'll have a look what's causing this over the next days when time permits.

**Comment by ahus1** [comment]
I've published pre-release 0.36.2 that should handle this. I tried it with the example you provided and it doesn't mess up the AsciiDoc content any more. 

Please note that for the snippet 

```
| .code.sh
[source,bash]
```

it will reformat it as 

```
| 
.code.sh
[source,bash]
```

that is: the title will go to a separate line. This is valid AsciiDoc, and doesn't change the rendered document. Previous it already did the same for a block heading (the `[source,bash]` - if that would be after a cell delimiter, it would move that to a new line also.

I know this is kind of opinionated. Please let me know if this works for you. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by mederel** [comment]
Hi @ahus1, I confirm it is working well, Thanks for the reactivity!

**Comment by ahus1** [comment]
Happy to hear that it works for you! Closing this issue for now. Please comment here or open a new issue if needed.
