### ISSUE TITLE
Code inspection gets stuck

### ISSUE THREAD

**Issue by Grolribasi** [asciidoctor/asciidoctor-intellij-plugin#925]
## Observed vs. expected behavior

As described at [Antora chat](https://antora.zulipchat.com/#narrow/stream/282400-users/topic/IntelliJ.20plugin.20code.20inspection.20gets.20stuck). Code inspection gets stuck on a file, if I delete the file, it gets stuck on another. 

## Steps to reproduce

I've sent a performance log to Alexander's email.

## Environment

Plugin Version: 0.36.1

IntelliJ Details: IntelliJ IDEA 2021.2.3 (Community Edition)
Build #IC-212.5457.46, built on October 12, 2021
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2044M
Cores: 8
Non-Bundled Plugins: com.github.jk1.ytplugin (2021.4.34), PlantUML integration (5.7.2), org.asciidoctor.intellij.asciidoc (0.36.1)
Kotlin: 212-1.6.0-release-799-IJ5457.46

**Comment by ahus1** [comment]
Thank you for the thread dump. The code was running hot in a situation with nested includes; maybe they were referencing each others. The recursion is limited in depth, still it can take quite some time to process them. 

The new pre-release 0.36.3 is available that tries to fix this. It caches results and prevents needless recursion where possible. 

Please give it a try. 

If you still experience performance problems, I now see that the menu option I mentioned in the Zulip chat isn't available by default in the community edition. 
Please see https://intellij-support.jetbrains.com/hc/en-us/articles/207241235 in section "The CPU usage is high or IDE is slow" on how to install the necessary plugin and run the performance analysis. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by Grolribasi** [comment]
Thanks for the feedback. I have installed the prerelease version and it did solve the issue indeed!

**Comment by ahus1** [comment]
I'm always happy when users contribute by writing bug reports, suggest features and test pre-releases. They help to improve the plugin.

As this is a spare time project, I can't promise any completion dates ... still when looking back, the releases have been quite frequent :-)
