### ISSUE TITLE
Parser problem with image after include

### ISSUE THREAD

**Issue by holgerbrandl** [asciidoctor/asciidoctor-intellij-plugin#941]
## Observed vs. expected behaviour

The plugin seems to struggle when parsing the following code (grey bits starting in line 11), although it's rendered correctly
![image](https://user-images.githubusercontent.com/200952/145279081-b7af3555-04eb-4f3d-ac09-7949c014fb0b.png)

## Steps to reproduce

```
.Dashboard
[image]
image::Images/dabr.ses.png[]

Example Query
[source,sql]
----
include::Queries/DownTimeDurationsEquipment.sql[]
----

.Dashboard
image::Images/dabr.ses.png[]


bla bla bla

[WARNING]
bla bla bla

```

## Environment

IDE version: 2021.3
plugin version: 0.36.8

**Comment by ahus1** [comment]
Hi Holger, thanks for reporting this. 

The lexer and parser for the syntax highlighting in the editor on the left are independent of the preview rendering via the Asciidoctor engine on the right. This leads now and then to some differences. 

I'll have a look and tune the lexing/parsing for the syntax highlighting for a future release. 

As a workaround, please add a blank line after "Example Query". This would also be the recommended syntax here IMHO, as the "Example Query" is treated as one block, and the block starting with `[source,...]` is then another block.

**Comment by ahus1** [comment]
... or remove `[image]`, as it is unnecessary.

**Comment by holgerbrandl** [comment]
Thanks for your suggestions.

**Comment by holgerbrandl** [comment]
Thanks for your suggestions.

**Comment by ahus1** [comment]
Thanks for providing this minimal example. I found a situation where the state in the lexer wasn't cleared properly. 
This would occur whenever there are block attributes (`[image]`) followed by a block macro (`image::[]`).

The minimal example helped me to debug and fix it. The change will be part of the next release. I'll update this issue once a pre-release is available.

**Comment by holgerbrandl** [comment]
Awesome, thanks for your great support.

**Comment by ahus1** [comment]
Release 0.36.9 is now available that includes this change.
