### ISSUE TITLE
Line with bad attribute {qwe} will be deleted,  but not!

### ISSUE THREAD

**Issue by WuglyakBolgoink** [asciidoctor/asciidoctor-intellij-plugin#942]
## Observed vs. expected behavior

I started to learn https://powerman.name/doc/asciidoc

But found some inconsistency :

![image](https://user-images.githubusercontent.com/2271337/145382463-dc401ba6-678f-4325-876b-34dc4a5d7b34.png)

in WebStorm preview not
![image](https://user-images.githubusercontent.com/2271337/145382669-fdc7511c-bea9-44c8-a07a-f89ce28b18cb.png)

## Environment

Plugin Version: `0.36.8`

IntelliJ Details:

```
WebStorm 2021.3
Build #WS-213.5744.224, built on November 27, 2021
Runtime version: 11.0.13+7-b1751.19 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.0.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Non-Bundled Plugins:
    patrick.kelleter.angular-cli-quick-switch (1.3)
    org.asciidoctor.intellij.asciidoc (0.36.8)
    in.thekalinga.snippet.intellij (6.1.0)
    ideanginx9 (0.1.9)
    de.netnexus.camelcaseplugin (3.0.8)
    de.cmm.side_nodes (1.2)
    com.xrath.plugin.fold (1.5.0)
    com.mnr.java.intellij.idea.plugin.base64helper (2.0.3)
    com.jsonts.kotlin (1.0.35)
    com.intellij.swagger (213.5744.122)
    com.intellij.ideolog (203.0.27.0)
    com.github.leomillon.uuidgenerator (4.5.1)
    com.andrey4623.rainbowcsv (2.0.1)
    com.alayouni.ansiHighlight (1.2.4)
    cn.jxzhang.plugin.json-formatter (1.4)
    com.intellij.jira (3.7.2)
    String Manipulation (8.23.203.000.0)
    PlantUML integration (5.8.0)
    mobi.hsz.idea.gitignore (4.3.0)
    izhangzhihao.rainbow.brackets (6.21)
    com.github.etkachev.nxwebstorm (0.9.2)
    Dummy Text Generator (1.2.0)
    ru.adelf.idea.dotenv (2021.3.0.213)
    lermitage.intellij.extra.icons (1.67.0.203)
```

**Comment by ahus1** [comment]
Thanks for reaching out. 

The documentation you found is for the Python implementation of an AsciiDoc renderer, this version is available here: https://asciidoc-py.github.io/index.html

The plugin uses a different implementation called Asciidoctor. See here https://asciidoctor.org/ for its homepage. 

The differences you see about Autor and Revision are related to the header you folded away. I assume this is not the different you're interested in.

Regarding the removal of blank lines for unknown attributes, this is something that can be enabled for the Asciidoctor implementation by setting the attribute `:attribute-missing: drop`. As dropping lines with an undefined attribute is a surprise to users, I assume this has been disabled by default for the Asciidoctor implementation. 

To learn about AsciiDoc, I recommend you have a look at this documentation, https://docs.asciidoctor.org/asciidoc/latest/. It also has a Quick Reference, see https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/. 
This documentation is also the basis of the AsciiDoc standardization efforts at the Eclipse Foundation. 

Please let me know if this is helpful, and if this issue can be closed.

**Comment by WuglyakBolgoink** [comment]
@ahus1  thank you very much for information!
