### ISSUE TITLE
How to handle `.idea` folder?

### ISSUE THREAD

**Issue by fwilhe** [asciidoctor/asciidoctor-intellij-plugin#95]
Hey,

I have a question. How do you handle changes in the `.idea` folder in the project root? I do not want to commit them because the changes that intellij makes are very specific for my setup (plugin sdk location, a custom formatter that I use, etc). Currently, I stash and apply the changes before and after checking out branches, but that is very cumbersome. Is there a better way to handle that? What are the benefits of having that folder in the repo rather than ignoring it?

**Comment by bodiam** [comment]
Good question. I don't know actually. I think I added it, or it was already there, and nobody mentioned it before. If you want to get rid of it and add it to the .gitignore, that seems like a sensible plan.

**Comment by bodiam** [comment]
Btw, this is the 'official' answer from JetBrains: https://devnet.jetbrains.com/docs/DOC-1186

**Comment by bodiam** [comment]
Can this be closed?

**Comment by fwilhe** [comment]
The link does unfortunately not solve my problem, but it seems there is no better solution, so this can be closed.

**Comment by bodiam** [comment]
I'm sorry for that. What we can do is remove the .idea directory completely from git and put it on the .gitignore ? That way you won't have to exclude it, and I don't mind if I loose the directory.

**Comment by fwilhe** [comment]
If that is ok with everyone, I would prefer this.

**Comment by bodiam** [comment]
I'm :+1:

**Comment by bodiam** [comment]
See #105
