### ISSUE TITLE
Add support for convert AsciiDoc to Markdown

### ISSUE THREAD

**Issue by gerryhjs** [asciidoctor/asciidoctor-intellij-plugin#953]
1. Plugin now support convert markdown to AsciiDoc, but doesn't support convert AsciiDoc to Markdown.
It will be very helpful to convert to Markdown in some case ,such as use for some website performance.

2. Also it will be very nice if plugin can support render markdown and export directly, instead of Jetbrains Markdown plugin.

3. Convert to both Asciidoc and markdown, leave the original file. 
For example convert markdown to AsciiDoc, don't delete original markdown file.

**Comment by ahus1** [comment]
Current, this is not supported out of the box. 

A known converter procedure is described here: https://github.com/arc42/arc42-generator/blob/master/subBuild.gradle. 

It has two steps:

1. convert AsciiDoc to DocBook using Asciidoctor
2. convert DocBook to Markdown (other other formats) using PanDoc

While this is not (yet) part of this plugin, I assume one could create a script for that.

**Comment by ahus1** [comment]
With issue #1074, there is now support for creating DOCX via Pandoc. The class `CreateDocxAction` created for the other ticket could serve as a template to create also Markdown. 

I'd be happy to lend a hand to anyone who wants to give it a try.
