### ISSUE TITLE
Custom css in preview causes rendering problem with Webstorm 2021.3.1 RC

### ISSUE THREAD

**Issue by RayOffiah** [asciidoctor/asciidoctor-intellij-plugin#954]
## Observed vs. expected behavior

Using a custom CSS file, the preview rendering isn't displayed properly. Scrolling up and down the preview causes all the text to get merged into a sold blob. It looks the like the redrawing is off.

Using Webstorm 2021.3 Build #WS-213.5744.224, built on November 27, 2021 --> works correctly

Using Webstorm 2021.3.1 RC Build #WS-213.6461.38, built on December 21, 2021--> doesn't render correctly

## Steps to reproduce

Create `.asciidoctorconfig` file that points to a local css file.

The local CSS file should point to an alternative CSS that can be used for the rendering:

```
@import 'https://docs.couchbase.com/_/css/site.css';
```

Testing a local CSS file also produces the same problem.

The plugin picks up the CSS correctly, but the rendering is a bit squiffy for the latest RC of Webstorm. The previous version works correctly.

## Environment

Plugin Version:  0.36.11

IntelliJ Details: ____

WebStorm 2021.3.1
Build #WS-213.6461.38, built on December 21, 2021

Runtime version: 11.0.13+7-b1751.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins:
    org.toml.lang (213.5744.224)
    name.kropp.intellij.makefile (213.5744.224)
    com.intellj.plugin.SpringBootBannerPlugin (0.2.9)
    org.asciidoctor.intellij.asciidoc (0.36.11)
    com.github.beansoft.iscratch (2020.3.8)
    String Manipulation (8.23.203.000.0)
    Shifter (1.9.6)
    PlantUML integration (5.9.1)
    org.rust.lang (0.4.162.4321-213)
    com.intellij.database (213.6461.19)
    izhangzhihao.rainbow.brackets (6.21)
    com.github.shiraji.yaemoji (1.0.7)

**Comment by ahus1** [comment]
Thanks for reporting this. I reproduce a strange behavior that is similar to your description - unfortunately I didn't see a screenshot in your issue.

It seems to me that this is triggered by a CSS that doesn't define a background color. 

![image](https://user-images.githubusercontent.com/3957921/147656575-da9733db-c050-4bb2-b841-da2b567012fb.png)

As a workaround, you could add background for the body like this to a local CSS file: 

```
@import 'https://docs.couchbase.com/_/css/site.css';

body {
  background-color: rgb(255, 255, 255);
}
```

Not defining a background color could also affect users that configure their browser with a different background color (maybe dark mode?), therefore I would recommend that you set a background color for the CSS you include as well. 

I'll look into this issue in more detail to see if I include a default background color for the next version of the plugin.

**Comment by ahus1** [comment]
Raised an upstream issue as I think this is a regression, adding a workaround as well.
https://youtrack.jetbrains.com/issue/IDEA-285899

**Comment by RayOffiah** [comment]
Apologies for forgetting the screenshot. I was going to put together an animated gif, but didn't think you'd look at  it until after Christmas :-)

I added the extra bit of CSS and it works perfectly.

I also have a look at the content in dark mode and see if we need to tweak a few things there. Thanks for pointing that out.

**Comment by ahus1** [comment]
@RayOffiah - no worries, happy holidays!

There's a pre-release 0.36.12 available that includes the workaround. I'd be happy if you could give it a try when you time permits.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by RayOffiah** [comment]
Removed the background CSS
Updated the plugin
The plugin works perfectly!
Great job. Thanks very much.

**Comment by ahus1** [comment]
Thanks for the update and being the first to report this regression and to test the fix. 

I'll promote 0.36.12 to a regular release and it should be visible in the marketplace for regular updates later today or tomorrow.
