### ISSUE TITLE
Formatting rendered incorrectly for variable names with underscores

### ISSUE THREAD

**Issue by RayOffiah** [asciidoctor/asciidoctor-intellij-plugin#963]
## Observed vs. expected behavior

When typing a variable name with an underscore character, the entire line is rendered in italics.

I would expect that only portions of the text encased in underscores would be shown as italics, not the whole section.

## Steps to reproduce

Add text to asciidoc document. Something like this:

`Use _default as the variable name`

## Environment

Plugin Version: 0.36.12

IntelliJ Details: 
WebStorm 2021.3.1
Build #WS-213.6461.79, built on December 28, 2021
Licensed to Ray Offiah
Runtime version: 11.0.13+7-b1751.21 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6.2
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins:
    org.toml.lang (213.5744.224)
    name.kropp.intellij.makefile (213.5744.224)
    com.intellj.plugin.SpringBootBannerPlugin (0.2.9)
    org.asciidoctor.intellij.asciidoc (0.36.12)
    com.github.beansoft.iscratch (2021.1.0 EAP)
    String Manipulation (8.24.203.5981.1)
    Shifter (1.9.6)
    PlantUML integration (5.9.1)
    org.rust.lang (0.4.162.4321-213)
    com.intellij.database (213.6461.79)
    izhangzhihao.rainbow.brackets (6.21)
    com.github.shiraji.yaemoji (1.0.7)

![text](https://user-images.githubusercontent.com/77050471/148213618-be63f467-7be4-4dc2-9af9-b667ad7663cd.png)

**Comment by ahus1** [comment]
Thanks for reporting this. Something like this might happen whenever there are two underscores in a paragraph.

While Asciidoctor handles this correctly as you see in the preview, the parser for the editor doesn't recognize that the second underscore is followed by a letter and therefore is not a valid terminating italic formatting character.

I'll have a look.

**Comment by ahus1** [comment]
I added your example to the test suite and did a refactoring that turned out bigger than expected. All tests are green, still I'd like you to give the pre-release a try once it is available. Maybe it needs some more "training" with some test cases what you might find in your day-to-day work. 

I'll update this issue again once a pre-release is available.

**Comment by ahus1** [comment]
Pre-release 0.36.15 is now available. Please give it a try. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by RayOffiah** [comment]
I can confirm that this is fixed! Thank you very much.

![image](https://user-images.githubusercontent.com/77050471/148675021-abd928d7-6fff-466b-bb40-875780c1fc37.png)

**Comment by RayOffiah** [comment]
No problem. I’ll keep an eye on it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
