### ISSUE TITLE
Cross reference linking broken in preview.

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-intellij-plugin#965]
## Problem Description

Navigating to a document section with anchor `[[anchor-id]]` from a paragraph of text containing reference `<<anchor-id>>` does not work reliably in the Asciidoc Preview in IntelliJ. In a document with multiple sections each with a unique anchor ID, clicking on a `<<unique-section-id>>` in the Asciidoc Preview, does not always move the preview to the correct document section.

In the generated HTML or in the Asciidoc Text window, navigation always works correctly.

## Steps to reproduce

[test_adoc.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/7841055/test_adoc.txt)

![image](https://user-images.githubusercontent.com/13682850/148818804-360358c3-2581-4ab5-8cab-2d0e1193b2c9.png)

Maybe this is the intended behaviour, but it seems a little bit inconsistent to me.

If I click on "Section A" or "Section C.1.1" in the TOC on the left, then the requested section heading is immediately displayed.

If however, I click on the corresponding heading link in the NOTE section at the top of the document, the requested document section is not always displayed. I have to use Ctrl-Home (on Windows) to go back to the top of the document, and click again on the same link; only then is the section heading displayed.

## Environment

Plugin Version: 0.36.13

IntelliJ Details:

IntelliJ IDEA 2021.3.1 (Community Edition)
Build #IC-213.6461.79, built on December 28, 2021
Runtime version: 11.0.13+7-b1751.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    de.docs_as_co.intellij.plugin.diagramsnet (0.1.12)
    com.jetbrains.plugins.ini4idea (213.5744.190)
    com.intellij.grazie.pro (0.3.58)
    com.github.bric3.excalidraw (0.3.2)
    org.asciidoctor.intellij.asciidoc (0.36.13)
    PythonCore (213.6461.82)
    com.github.copilot (1.1.4.220)
    PlantUML integration (5.9.1)
    CMD Support (1.0.5)
    org.mapstruct.intellij (1.3.1)

Kotlin: 213-1.5.10-release-949-IJ6461.79

**Comment by ahus1** [comment]
Thanks for noticing this behavior. I found an issue in the JavaScript where an event should not be propagated. 

Thanks to example provided I could test this locally and that this now works better. 

I close this issue and post another comment once a preview version is available.

**Comment by ahus1** [comment]
This now available as pre-release 0.36.16. Please give it a try.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by wfouche** [comment]
@ahus1, thank you! It works perfectly now.

**Comment by ahus1** [comment]
Great to hear this works for you now! What a difference one line of JavaScript can make :-)
