### ISSUE TITLE
Unresolved Antora reference - include example

### ISSUE THREAD

**Issue by aisbergde** [asciidoctor/asciidoctor-intellij-plugin#967]
## Observed vs. expected behavior

I use includes like:

```
--
[source,sql]
----
include::example$tt-export_poc_1003.sql[]
----
--
```

this works fine directly in Antora, the content is included. But the Plugin doesn't resolve it:

![image](https://user-images.githubusercontent.com/9020187/149306227-0faa0838-769f-44b1-8908-f87892a300f0.png)

expected:

show the include like Antora shows.

I also tried
```
--
[source,sql]
----
include::ROOT:example$tt-export_poc_1003.sql[]
----
--
```

but it is also not resolved

## Steps to reproduce

- use standard

- place a text file with file extension 'sql' in Antora example folder
- check in the plugin
- build with Antora

## Environment

Plugin Version:  0.36.13

IntelliJ IDEA 2021.2.3 (Ultimate Edition)
Build #IU-212.5457.46, built on October 12, 2021
Licensed to DataHandwerk-toolkit-mssql / Germo Goertz
Subscription is active until February 28, 2022.
For non-commercial open source development only.
Runtime version: 11.0.12+7-b1504.40 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 5000M
Cores: 4
Non-Bundled Plugins: com.intellij.plugins.vscodekeymap (212.3116.29), PlantUML integration (5.9.1), org.asciidoctor.intellij.asciidoc (0.36.13)
Kotlin: 212-1.5.10-release-IJ5457.46

**Comment by ahus1** [comment]
Hi @aisbergde - I gave it a try locally and got the same message while project was still indexing.

Once indexing was complete, it worked for me, see screenshot below. I used the same version as you did. 

![image](https://user-images.githubusercontent.com/3957921/149388794-2e234618-dcff-416f-819d-a7ba4e435041.png)

Could you please provide a minimal ZIP file that helps me to reproduce it? Thanks!

**Comment by aisbergde** [comment]
@ahus1 Ich würde ein Repo gerne per Email schicken, statt es öffentlich zu posten. Die Email steht ja im Profil. Wäre das OK? Dann kann ich es so belassen, wie es ist.

**Comment by ahus1** [comment]
@aisbergde - yes, sending the file by email to the address on my profile works fine for me.

**Comment by ahus1** [comment]
Thanks for the file. It worked locally for me. So it suspect it has something to do with the settings. 

Digging a bit deeper, the error message can be triggered by the following: 

* IDE is in dumb mode due to indexing running
* AsciiDoc rendering is set in the plugin settings to something other than UNSAFE mode
* IDE is in lightedit mode

Does one of these settings apply to your environment? 

I'll prepare a plugin version that will show more detailed information, and will trigger a refresh of the preview once the indexing is complete.

**Comment by ahus1** [comment]
The changes are available as pre-release 0.36.16. 

The message you see in the preview should change and should be more specific to the cause. Please give it a try and let me know what you see.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment]
I published pre-release 0.36.17 that tries to resolve Antora references without indexes in simple scenarios, and this should improve your experience while indexes are still built. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by aisbergde** [comment]
![image](https://user-images.githubusercontent.com/9020187/149626377-95b133d5-f786-4c52-80b5-cf75ca8e21d4.png)

It is not indexing.

And all other include:: are working, especially to partials, but I did not include the other repositories in the examples (I could add them, if required). It is only this "example" not working.

Could anything else be different? I use includes from partials in many cases, and normally they work fine. It is only this one example. And it is not a big issue, because it is working in Antora. But what is strange: that you can't reproduce the issue.

Now I will try the EAP version...

Now it looks different:
![image](https://user-images.githubusercontent.com/9020187/149626729-2142adda-0bb4-4d4c-ae3a-38b159d8fc39.png)

the folder structure:
![image](https://user-images.githubusercontent.com/9020187/149626830-eb9a5474-2cb2-42fd-90ea-258f8679f25c.png)

and what's interessting, the error messages for the other missing includes (because I did not add the repositories in the examples) looks different:
![image](https://user-images.githubusercontent.com/9020187/149626918-ef920cd8-db06-442a-8181-d531586db5e7.png)

Now I will try to make a copy from the sql file and I will rename it .adoc: I also included something into the partials folder, nothing helps.

Maybe this is an issue?
![image](https://user-images.githubusercontent.com/9020187/149627265-ca99655a-5772-474e-8232-1e0c4b0a9a49.png)

No change.

Maybe I am in this "lightedit mode"? How to know? But in the status bar, there is no information about any lightedit mode:
![image](https://user-images.githubusercontent.com/9020187/149627479-300571ac-6a6e-410a-8572-7c58c1ca5f22.png)


Now I will open the whole project, including playbook and all repositories

I get a different error message:
![image](https://user-images.githubusercontent.com/9020187/149627565-8e19f1f9-4cf2-4b7b-9014-5bcea7698f4e.png)

Maybe, because it is still indexing... I will wait to finish the indexing...

Now it is finished: other includes also do not work now:
![image](https://user-images.githubusercontent.com/9020187/149627761-daa7fe49-4571-4e88-9db1-8ebf9a895266.png)

Maybe this is because I just used the parent folder of my repositories as project? But I think, this worked in the past:
![image](https://user-images.githubusercontent.com/9020187/149627836-27ddce25-fd65-42a7-9f79-cbc3ca32f7e0.png)

Now I am confused...

**Comment by aisbergde** [comment]
It looks like I have a General issue and the include detection stopped to work at all, also in other projects where this worked fine before. Everywhere I get this kind of errors, but these projects worked before. No indexing happens.
![image](https://user-images.githubusercontent.com/9020187/149628095-6c67e387-082f-4fcd-a68d-c5bf3b992739.png)

**Comment by aisbergde** [comment]
Now I just closed InteliJ, I reopened it. And now all works fine! So it looks like an InteliJ related issue.

**Comment by aisbergde** [comment]
It looks like, it works only in the first project I open. As soon as I open a second project, even in the same Windows, it stoppes to work. I will try again to confirm this. 

No, something different. I need to find out, when it works and when it doesn't work.

**Comment by aisbergde** [comment]
I don't understand anything: the include of the example works now, but only the sample repository I send you.
And all other includes in all other repositories stopped to work.

Is there an easy way to downgrade the plugin? I will just uninstall and install the older version to compare.

**Comment by ahus1** [comment]
Thanks for trying the different aspects. 

Trust mode is the problem as shown in this screenshot: 

![image](https://user-images.githubusercontent.com/9020187/149627265-ca99655a-5772-474e-8232-1e0c4b0a9a49.png)

Once you trust the project, either close and re-open the AsciiDoc editor, switch editor tabs or do a minor change in the document to force a re-render of the preview. Once you're no longer in safe mode, rendering should work as expected.

Safe mode is configured on a per project level. If you installed different IDEs, each IDE maintains its own list of trusted projects. 

To roll back to a previous release of the AsciiDoc plugin: 
1. download the ZIP file from the GitHub releases here: https://plugins.jetbrains.com/plugin/7391-asciidoc/versions  
2. install the plugins "from disk" as described here: https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/installation.html#download-install-from-disk

Please let me know if that helps.

**Comment by aisbergde** [comment]
back to 0.36.13 
nothing helps. same effect: but now the example include sometimes workes, sometimes not, sometimes only in the example repository, sometimes in the full repository. But I when I close the file and repoen, it doesn't solve again. Very hard to reproduce the same results every time.

I think, I should restart my Windows system. Maybe this helps. Maybe there are some caches or some other InteliJ issues.

**Comment by aisbergde** [comment]
After a long time of indexing one project worked as before. But when I switched to another project, the indexing happened very fast (it was not reindexed), and includes doesn't work.

- it looks like, IntelliJ thinks, the index is OK, and doesn't reindex, and this could be the reason for my issues. I will try to **"invalidate caches"** as described here: https://www.jetbrains.com/help/idea/2021.2/invalidate-caches.html
- now it is indexing again (which always takes very long, several minutes, but that's live). 
- includes are still not working, but I will restart IntelliJ again. includes are still not working on this project.
- one more thing: there is no "indexing" in the taskbar, but "indexing" on the right uper corner of the page. Could this be an issue?
![image](https://user-images.githubusercontent.com/9020187/149631928-70eec71a-c220-4662-8c96-176d6bcc54d1.png)
- I still think these are issues with indexes, otherwise, why the includes are working on some projects, but not on other projects. And sometimes they are working on the same project, sometimes not. It is hard to reproduce.
- would it be possible to check if indexing were really successful? Or should a user "invalidate caches", if includes are not solved?
- should I still try the early access version? Does it improve index handling?

**Comment by ahus1** [comment]
We looked at some examples today, and found that it now works. The preview will show the correct results: 

* after indexing is complete
* the project has to be trusted
* the preview was closed and re-opened to force a refresh

Sometime references within the same component can sometimes be resolved earlier, but only if it isn't a distributed component. 

A future version will try to update the preview once indexing is complete. I'll update the issue once this change is available.

**Comment by ahus1** [comment]
I just released pre-release 0.36.18 that will should more reliably refresh the preview once the indexing is complete. 
It should also show the titles of the Antora pages referenced using xref in the preview with the examples you provided. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by Uriziel47** [comment]
I also faced this kind of issue with "Unresolved Antora Reference: include::example$...". 
After digging in the code I realized. I forgot to add the required fields in the _antora.yml_, naming:

- name
- version

After adding these fields the include shows the expected output.

FYI:
Code analysis _antora.yml_ having not the required fields _name_ and _version_.

AntoraIncludeAdapter::process
 ```
if (localModule != null) {
  target = AsciiDocUtil.replaceAntoraPrefix(project, localModule, sourceDir, target, "page", "include").get(0);
}
```

AsciiDocUtil::replaceAntoraPrefix
_otherDirs_ are empty 
```
List<VirtualFile> otherDirs = getOtherAntoraModuleDir(project, moduleDir, myModuleName, myComponentName, myComponentVersion, otherComponentVersion, otherComponentName, otherModuleName);
List<String> result = new ArrayList<>();
for (VirtualFile otherDir : otherDirs) {
```

AsciiDocUtil::getOtherAntoraModuleDir
_otherComponentName_ is set to _myComponentName_ which is _null_, so the last if-statement is been skipped, which results in
empty list as return value.
```
if (otherComponentName == null && otherModuleName == null) {
  otherComponentName = myComponentName;
  otherModuleName = myModuleName;
}

if (otherComponentName != null) {
```

_myComponentName_ is set in AsciiDocUtil::replaceAntoraPrefix
```
String myComponentName = getAttributeAsString(antora, "name");
String myComponentVersion = getAttributeAsString(antora, "version");
```

**Comment by ahus1** [comment]
@Uriziel47 - I've created issue #1728 to discuss alternatives / better heuristics for this.
