### ISSUE TITLE
Asciidoctor-pdf 1.6.2 fails to correctly render SVG diagram created with draw.io

### ISSUE THREAD

**Issue by wfouche** [asciidoctor/asciidoctor-intellij-plugin#971]
## Observed vs. expected behavior

A draw.io SVG diagram with icons 

![image](https://user-images.githubusercontent.com/13682850/150501640-98526964-c303-456e-b868-2d594cbfb799.png)

is exported to PDF without the icons.

![image](https://user-images.githubusercontent.com/13682850/150501695-7f521d13-039a-4d0f-8ba7-0f2cd6314987.png)

The following three errors are logged, one for each missing icon.  Note that rendering to HTML is working fine.

11:23	Message during rendering bug-icon-example.adoc: WARN uri:classloader:/gems/asciidoctor-pdf-1.6.2/lib/asciidoctor/pdf/converter.rb:convert_image:  problem encountered in image: C:/Users/wfouche/IdeaProjects/w-confluence/wfouche/docs-as-code/bug-icons-example.drawio.svg; Error retrieving URL data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcKICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICB4bWxuczpjYz0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjIgogICB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiCiAgIHhtbG5zOnN2Zz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiAgIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICAgeG1sbnM6c29kaXBvZGk9Imh0dHA6Ly9zb2RpcG9kaS5zb3VyY2Vmb3JnZS5uZXQvRFREL3NvZGlwb2RpLTAuZHRkIgogICB4bWxuczppbmtzY2FwZT0iaHR0cDovL3d3dy5pbmtzY2FwZS5vcmcvbmFtZXNwYWNlcy9pbmtzY2FwZSIKICAgaWQ9ImE5Njc5MmI3LWNlMjgtNGNhMy05NzY3LTRlMDY1ZWY0ODIwZiIKICAgd2lkdGg9IjEyLjgyIgogICBoZWlnaHQ9IjE3IgogICB2aWV3Qm94PSIwIDAgMTIuODIgMTciCiAgIHZlcnNpb249IjEuMSIKICA... (show balloon)

11:23	Message during rendering bug-icon-example.adoc: WARN uri:classloader:/gems/asciidoctor-pdf-1.6.2/lib/asciidoctor/pdf/converter.rb:convert_image:  problem encountered in image: C:/Users/wfouche/IdeaProjects/w-confluence/wfouche/docs-as-code/bug-icons-example.drawio.svg; Error retrieving URL data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcKICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICB4bWxuczpjYz0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjIgogICB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiCiAgIHhtbG5zOnN2Zz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiAgIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICAgeG1sbnM6c29kaXBvZGk9Imh0dHA6Ly9zb2RpcG9kaS5zb3VyY2Vmb3JnZS5uZXQvRFREL3NvZGlwb2RpLTAuZHRkIgogICB4bWxuczppbmtzY2FwZT0iaHR0cDovL3d3dy5pbmtzY2FwZS5vcmcvbmFtZXNwYWNlcy9pbmtzY2FwZSIKICAgaWQ9ImFjYWM1YTM0LWEwMzItNDlmOS05Mzk3LTM3ZjRmMWI0YWU5YSIKICAgd2lkdGg9IjE2Ljk5NDM3MSIKICAgaGVpZ2h0PSIxNi45OTQzNzEiCiAgIHZpZXdCb3g9IjAgMCAxNi45OTQzNzEgMTYuOTk0Mzc... (show balloon)

11:23	Message during rendering bug-icon-example.adoc: WARN uri:classloader:/gems/asciidoctor-pdf-1.6.2/lib/asciidoctor/pdf/converter.rb:convert_image:  problem encountered in image: C:/Users/wfouche/IdeaProjects/w-confluence/wfouche/docs-as-code/bug-icons-example.drawio.svg; Error retrieving URL data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9Im5vIj8+CjxzdmcKICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICB4bWxuczpjYz0iaHR0cDovL2NyZWF0aXZlY29tbW9ucy5vcmcvbnMjIgogICB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiCiAgIHhtbG5zOnN2Zz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciCiAgIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIKICAgeG1sbnM6c29kaXBvZGk9Imh0dHA6Ly9zb2RpcG9kaS5zb3VyY2Vmb3JnZS5uZXQvRFREL3NvZGlwb2RpLTAuZHRkIgogICB4bWxuczppbmtzY2FwZT0iaHR0cDovL3d3dy5pbmtzY2FwZS5vcmcvbmFtZXNwYWNlcy9pbmtzY2FwZSIKICAgaWQ9ImI3NTk0M2JhLTFhM2YtNDg1ZC1iNDVkLTNmZWUwMGVkN2U1ZSIKICAgd2lkdGg9IjE0LjcyIgogICBoZWlnaHQ9IjE3Ljk5NzU3MiIKICAgdmlld0JveD0iMCAwIDE0LjcyIDE3Ljk5NzU3MiIKICAgdmV... (show balloon)

## Steps to reproduce

[bug-icons-example.drawio.svg.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/7912288/bug-icons-example.drawio.svg.txt)
[bug-icons-example.adoc.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/7912289/bug-icons-example.adoc.txt)

Open file bug-icons-example.adoc and publish it to HTML and to PDF.

## Environment

Plugin Version: 0.36.18

IntelliJ Details: 

IntelliJ IDEA 2021.3.1 (Community Edition)
Build #IC-213.6461.79, built on December 28, 2021
Runtime version: 11.0.13+7-b1751.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 12
Registry:
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    de.docs_as_co.intellij.plugin.diagramsnet (0.1.12)
    com.jetbrains.plugins.ini4idea (213.5744.190)
    com.intellij.grazie.pro (0.3.63)
    org.jetbrains.kotlin (213-1.6.10-release-944-IJ6461.79)
    com.github.bric3.excalidraw (0.3.2)
    org.asciidoctor.intellij.asciidoc (0.36.18)
    PythonCore (213.6461.82)
    com.github.copilot (1.1.4.220)
    PlantUML integration (5.10.0)
    CMD Support (1.0.5)
    org.mapstruct.intellij (1.3.1)

Kotlin: 213-1.6.10-release-944-IJ6461.79

**Comment by wfouche** [comment]
The following error message is generated by prawn-svg.

"prawn-svg only supports base64-encoded image/png and image/jpeg data URLs".

**Comment by wfouche** [comment]
@mojavelinux, 

In issue https://github.com/mogest/prawn-svg/issues/139 you commented.

"Asciidoctor PDF 1.6.0 does not support loading an image in an SVG from a data URI. Support for that feature was added in the upcoming Asciidoctor PDF 2.0.0 release. So I believe this question does not pertain to prawn-svg. Though it is curious that we still need a workaround for this in Asciidoctor PDF. See https://github.com/asciidoctor/asciidoctor-pdf/blob/main/lib/asciidoctor/pdf/ext/prawn-svg/loaders/data.rb Seems to be a regex issue."

Does this mean that Asciidoctor PDF 2.0 will support loading an **SVG image** in an SVG from a data URI? Or are we still limited to PNGs and JPGs?

**Comment by ahus1** [comment]
I understand that the SVG diagram embeds another SVG diagram. Reading the issue in prawn-svg you mentioned above, I'm not sure if this is about the same issue - I'm just not so deep into SVG I'm afraid.

To my experience, prawn-svg only supports regular SVGs, and I know there are problems embedding HTML that diagrams.net uses for example for word wrapped text. 

See https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/faq/diagrams-in-pdf-without-text.html for details, and how to work around this.

**Comment by wfouche** [comment]
Thanks @ahus1. I've started using Web PDF, and it is a suitable workaround for me. Will close this issue now.

**Comment by mojavelinux** [comment]
> Does this mean that Asciidoctor PDF 2.0 will support loading an SVG image in an SVG from a data URI? Or are we still limited to PNGs and JPGs?

We will still be limited to PNGs and JPEGs since prawn-svg does not support external images that are SVGs. That limitation is independent of how the external image is resolved. See https://github.com/mogest/prawn-svg/issues/144#issuecomment-972426242

**Comment by wfouche** [comment]
Thanks @mojavelinux.

**Comment by wfouche** [comment]
```
from cairosvg import svg2png
from bs4 import BeautifulSoup
import base64
import glob, os

for filename in glob.glob("*.drawio.svg"):
    update_file = False
    data=""
    for line in open(filename,'r').readlines():
        data += line
    soup = BeautifulSoup(data, "xml")
    for tag in soup.find_all('image'):
        width = tag.get('width')
        height = tag.get('height')
        xlink_href = tag.get('xlink:href')
        if 'data:image/svg+xml;base64,' in xlink_href:
            update_file = True
            svg_text_base64 = xlink_href.split('base64,')[1]
            #print(svg_text_base64[:40])
            svg_text = base64.b64decode(svg_text_base64).decode('utf-8')
            #print(svg_text)
            png_binary = svg2png(bytestring=svg_text,output_width=float(width), output_height=float(height))
            png_text_base64 = base64.b64encode(png_binary).decode('utf-8')

            #print(width,height,png_text_base64[:40])
            tag['xlink:href'] = "data:image/png;base64,%s"%(png_text_base64)
    if update_file:
        print(filename)
        with open(filename,'w') as f:
            f.write(soup.prettify())
```
