### ISSUE TITLE
tag::your_tag[] is displayed in preview

### ISSUE THREAD

**Issue by ehmkah** [asciidoctor/asciidoctor-intellij-plugin#98]
When I work with tags inside asciidoctor documents they are also shown in the preview page: Try the following to see what I mean:

    tag::summary[]
    * lorem ipsum
    end::summary[]

I would expect that this is not show in the preview since after generating the html output it disapperaed?

**Comment by bodiam** [comment]
Hi @ehmkah, good question, and to be honest, I don't know. I use AsciidocJ for the rendering, I don't do anything myself for that, so I think it's better to ask @mojavelinux, I'm sure he knows.

**Comment by mojavelinux** [comment]
You need to put them behind line comments:

```
//tag::summary[]
* lorem ipsum
//end::summary[]
```

`tag::[]` and `end::[]` aren't actually AsciiDoc syntax.
