### ISSUE TITLE
False positive quickfix after link: Sentence should start with upper case

### ISSUE THREAD

**Issue by holgerbrandl** [asciidoctor/asciidoctor-intellij-plugin#980]
## Observed vs. expected behavior

It reports a false positive fix after a link:
![image](https://user-images.githubusercontent.com/200952/152655841-1f4bf9e6-1e62-443a-aaa0-ed5e2f9c56c9.png)

## Steps to reproduce

Create an ascidoc with the following content
```
Foo bar. <<Extra Bedarfe>> should be modelled.
```

## Environment

Plugin Version: 0.36.18 

IDE: Build #IU-213.6777.52

**Comment by ahus1** [comment]
Thanks for reporting this, I'm looking into it. Expect a pre-release soon.

**Comment by ahus1** [comment]
Created upstream issue: https://youtrack.jetbrains.com/issue/IDEA-288084

**Comment by ahus1** [comment]
A fix for that is now available as part of the pre-release version 0.37.1. Please give it a try.

IntelliJ 2021.3.1 or later is necessary for this release.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by ahus1** [comment]
Arg, fumbled the release. Will need to do another pre-release. Please stay tuned.

**Comment by ahus1** [comment]
Another pre-release version 0.37.2 is now available. Please give it a try.

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by holgerbrandl** [comment]
Thanks for following up on the report so quickly.

**Comment by holgerbrandl** [comment]
I've installed the EAP, and can confirm that the problem is fixed. Thank you very much.

**Comment by ahus1** [comment]
Thanks for letting me know, then this issue is closed. Happy writing!
