### ISSUE TITLE
Support complex colspec

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor-intellij-plugin#984]
Thank you for this extension. I'm really enjoying using it and comparing it with the VS Code extension which is less usable for Antora documentation with the advanced completion features this extension provides.

## Why the new feature should be added

Having syntax highlighting of language features gives the user confidence that they are "on the right track". The syntax completion is already great, this is just a little improvement suggestion for a complex use case.

## How the new feature should work

Currently the colspec is well supported, however the "Comment" column is a case where it is not:

```asciidoc

[#conn_by_type]
.Process Devices
[cols="1*<.^,1*^.<,1*^.<2,1*^.<,1*<.^,1*",options="unbreakable"]
|===
.2+h|Bay Type 2+h| Prot 1 Devices 2+h| Prot 2 Devices .2+^.^h|Comment
^.^h| Prot h| Control h| Prot h| Control

|Line
| 1 +
LDif1
^.^| 0
| 1 +
LDif2
^.^| 0
|

|Transformer +
Reactor
| 1 +
Dif
| 3 +
WTI1, WTI2, VReg
| 1 +
Dif
^.^| 0
|

|Capacitor
| 1 +
CapProt1
^.^| 0
| 1 +
CapProt2
^.^| 0
|

|Bus
| 1 +
Dif1
^.^| 0
| 1
Dif2
^.^| 0
|

|===
```

I believe the colspec for the Comment column is valid but it is not shown as such:

![image](https://user-images.githubusercontent.com/674783/153916959-3980dd3d-1cad-473d-bee9-411182ba0c19.png)

https://docs.asciidoctor.org/asciidoc/latest/tables/span-cells/

**Comment by ahus1** [comment]
Thanks for notifying me that the syntax highlighting is off here. I found that the current version of the IntelliJ plugin has a problem when the cell formatting contains more than one dot. 

I've prepared a fix for the upcoming version of the plugin and I'll update this issue once  a pre-release is available. 

I hope that the VS Code plugin will eventually have Antora support as well as this will benefit the AsciiDoc and Antora ecosystem.

**Comment by ahus1** [comment]
Pre-Release 0.37.4 is available that should fix this issue. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
