### ISSUE TITLE
Create new Antora page chooses an incorrect location

### ISSUE THREAD

**Issue by danyill** [asciidoctor/asciidoctor-intellij-plugin#985]
## Observed vs. expected behavior

When creating a new page using the included Antora support, my workflow is:

* Go to the nav page
* Create an xref
* Create a new file from the error:
    ![image](https://user-images.githubusercontent.com/674783/153918393-2089bc86-987d-4da3-aab4-07e9efa4adf8.png)

When I do this, the file is created under the module root.

![image](https://user-images.githubusercontent.com/674783/153918554-ea11ac18-f42b-4be3-8126-100f04b9f08c.png)

I think by default it should be included under the `pages` folder (and that this should be created if necessary, possibly it would be).

I believe the Antora resource ID structure requires that pages do not belong in the module folder which is structural and not for placing content (if I have that right).

## Steps to reproduce

As above (I have updated to the latest version of the extension and replicated but the screenshots are a couple of releases behind).

## Environment

Plugin Version: 0.36.18

IntelliJ Details: IntelliJ IDEA 2021.3.1 (Community Edition)
Build #IC-213.6461.79, built on December 29, 2021
Runtime version: 11.0.13+7-b1751.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.7-051507-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 958M
Cores: 8
Non-Bundled Plugins:
    org.asciidoctor.intellij.asciidoc (0.36.18)

Kotlin: 213-1.5.10-release-949-IJ6461.79
Current Desktop: KDE

**Comment by ahus1** [comment]
Pre-Release 0.37.4 is available that should fix this issue. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
