### ISSUE TITLE
Creating a local cross-reference prompts refrerences to external documents

### ISSUE THREAD

**Issue by Grolribasi** [asciidoctor/asciidoctor-intellij-plugin#986]
## Why the new feature should be added

Referencing to an internal anchor looks for similar anchors in other documents.

![image](https://user-images.githubusercontent.com/75079192/154225371-e5141478-65c2-408e-8a71-54bc43f69303.png)

## How the new feature should work

The more correct behavior would be to search for anchors only in the current document. 
However, sometimes it may be useful when a different file is included in the current one. 
Maybe it would be better to first look for the references in the current file and prioritize them in the prompt.

**Comment by mojavelinux** [comment]
Technically, the shorthand xref syntax supports making a reference to an anchor in another document (interdocument xref). For example `<<other.adoc#idname>>`. However, we strongly discourage this practice in Antora. If possible, I'd like for it to not be offered for Antora projects, but allow it (perhaps in priority order as you suggest) outside of Antora. In an Antora project, it should only offer targets within the current document (after considering any included content).

**Comment by ahus1** [comment]
Thanks for suggesting this optimization. 

This could work for Antora pages when all includes can be resolved. For partials, that could be included in different contexts, such an optimization would not be possible. Technically also a page could be included in another page, but that would be a rare case. 

This reasoning would only be done for Antora, not for standard AsciiDoc projects as in those projects it is IMHO a order of magnitude more complicated to determine where a document could be included.

**Comment by ahus1** [comment]
This will be part of the next pre-release. I'll update this issue once it is available.

**Comment by mojavelinux** [comment]
> This reasoning would only be done for Antora, not for standard AsciiDoc projects as in those projects

That's precisely why we have created the restricted environment in Antora. It's absolutely essential for paving the way for strong tooling.
