### ISSUE TITLE
Argument rangeInElement ... endOffset must not exceed descriptor text rangeOne more issue with exceptions.

### ISSUE THREAD

**Issue by ahus1** [asciidoctor/asciidoctor-intellij-plugin#990]
One more issue with exceptions.
Not sure if it's also related to AsciiDoc plugin.
I've already submitted a lot of reports to JetBrains and opened an [issue](https://youtrack.jetbrains.com/issue/IDEA-287942). I forgot about the exceptions for some time since I disabled the plugin. I thought I disabled it only for code inspection, but it appeared that I disabled it for the whole project.
I am attaching the stacktrace FYI.

[stacktrace.txt](https://github.com/asciidoctor/asciidoctor-intellij-plugin/files/8107564/stacktrace.txt)

I updated the test repo by adding one more file to the project. When I edit this file (change lists, delete text, etc) exceptions are getting generated one after the other.

_Originally posted by @Grolribasi in https://github.com/asciidoctor/asciidoctor-intellij-plugin/issues/981#issuecomment-1046598033_

**Comment by ahus1** [comment]
@Grolribasi - there is now pre-release 0.37.5 available. With the example and video you provided I was able to reproduce the problem and also to verify the fix. 

Please give this pre-release a try. Once you confirm that the pre-release works for you, I'll publish it to the regular repository on the JetBrains marketplace for everyone else to download it automatically. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).

**Comment by Grolribasi** [comment]
Thanks! I will try it out and report back.

**Comment by Grolribasi** [comment]
The fix is working. Haven't noticed any exceptions in Grazie.

**Comment by ahus1** [comment]
Thanks for letting me know, I triggered the publishing to the JetBrains marketplace just now. The fix is available for IntelliJ 2020.3.1 or later. 

Reading the original bug report on the JetBrains tracker, you started to experience this bug with IntelliJ 2020.3.2. I don't know from what version you updated, therefore I wonder if I would need to publish a plugin update also for earlier versions of IntelliJ. I'd be glad if you could briefly comment on that before I close this issue. If you're not sure (which is perfectly fine), I'll publish the change for the earlier versions just to be safe.

**Comment by Grolribasi** [comment]
> 2020.3.1

You probably mistyped 202**1**.3.1.

The first time I experienced the issue was when I upgraded to IntelliJ 2021.3.2. I've upgraded from the previous latest release version which was 2021.3.1.

**Comment by ahus1** [comment]
Oops, that was indeed mistyped. Reading your reply, it seems to be safe not to publish an update for older releases. Therefore I close this issue.

Should someone else experience this with an earlier version, please comment here and I'll reopen the issue.
