### ISSUE TITLE
Unexpected Bracket Recognition with Double Angle Brackets on References

### ISSUE THREAD

**Issue by JulMack** [asciidoctor/asciidoctor-intellij-plugin#995]
## Observed vs. expected behavior

When I have a double angle bracket surrounded reference to a heading with additional Text which includes a single angle bracket for a menu-like description, the IDE doesn't hit the correct way to recognize the reference. This leads to faulty reference refactoring. I do not know if this is an IDE problem or can be fixed within the plugin (or even is expected behavior) and I'm sorry if this bugreport is placed at the wrong spot.

## Steps to reproduce

If i have a reference 
```
<<Some Heading, Some Text>>
```
and I want to add a menu like description: 
```
<<Some Heading, Some Text > Additional Text>>
```
the IDE switches the recognized pair of brackets to the first opening angle bracket and the closing angle bracket right before "Additional Text", which then leads to the described problem. Rendering works as expected, though.

## Environment

Plugin Version: 0.37.5

IntelliJ Details: Using Webstorm 2021.3.2

**Comment by ahus1** [comment]
Pre-release 0.37.6 is now available that includes this change. I tested it locally and therefore I assume it works as expected. If that shouldn't be the case, please comment here and I'll reopen the issue. 

The pre-release of the plugin is available from [GitHub releases](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/installing-a-preview-release.html) and the [IntelliJ AsciiDoc EAP repository](https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/user/add-eap-repository-to-ide.html).
